### ISSUE TITLE
Underlying browser does not resize with window under windows

### ISSUE THREAD

**Issue by jonathon-love** [r0x0r/pywebview#10]
Hi,

When resize is set to True, the webview window can be resized, but the underlying browser instance does not resize with it. See the screenshot below:

<img width="690" alt="screen shot 2015-10-25 at 11 55 12 am" src="https://cloud.githubusercontent.com/assets/3240247/10715250/9ea16372-7b0f-11e5-88ce-2084659f669c.png">

It seems a pity I'm only getting in touch when something is going wrong, but pywebview is sensational!

with thanks

**Comment by r0x0r** [comment]
Somehow it got broken in one of the refactoring rounds. Fixed and created a new release.

**Comment by jonathon-love** [comment]
awesome! thanks
