### ISSUE TITLE
[bug] create_file_dialog broken in cocoa

### ISSUE THREAD

**Issue by shivaprsdv** [r0x0r/pywebview#100]
Line [#222](https://github.com/r0x0r/pywebview/blob/master/webview/cocoa.py#L222) in `cocoa.py`:

KeyError: There is no longer a key called `'global.saveFile'` in `localization`.

Strange enough, this doesn't log any error at all. Had to use the debugger to figure out the issue. To reproduce the bug, try running `examples/save_file_dialog.py`, nothing happens. Quits fine on Cmd+Q; but the window becomes not responding on closing, and needs Force quit.

**Comment by shivaprsdv** [comment]
Not sure adding the key back is the best fix keeping up with the project's interests. Hence an Issue instead of a PR. 🤓

**Comment by r0x0r** [comment]
Changed linux.saveFile to global.saveFile. Fixed in master.
