### ISSUE TITLE
How to Hide Html Templete folder when create executable file

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1001]
### Specification
- pywebview version: 3.7
- operating system: windows 10

### Description  
  if i am using --onfile in pyinstaller 
so my html is hide but executable  file is very heavy and execution time is so far

but 

  if i am using  without --onefile in pyinstaller  so execution time is very fast but my html folder is  not hide and every person seen the html logic

so please tell me how to solve

**Comment by r0x0r** [comment]
You could also encrypt / obfuscate your files, before serving them. This is not very secure, as you have to keep decryption key / algorithm somewhere in your code, but will deter most prying eyes.

**Comment by MominIqbal-1234** [comment]
@r0x0r Thanks so much 
i already use a similar technique during run time generate HTML and after using remove files 
I create password manager using pywebview 
https://mefiz.com/download/password_manager

thanks so much :)
