### ISSUE TITLE
Unable To Create Separate Process In Pywebview

### ISSUE THREAD

**Issue by shivjeetbhullar** [r0x0r/pywebview#1009]
### Specification
- pywebview version:  3.7
- operating system: Window
- web renderer: QT

### Description  
  
whenever I try to create a separate process it popups the same running window again.
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I do not understand.
