### ISSUE TITLE
webview.load_html not showing image.

### ISSUE THREAD

**Issue by JeanPierreFig** [r0x0r/pywebview#101]
On a Raspberry Pi I am trying to load an html page that just makes the background black and centers the image on screen, but I'm getting this error 

> Message: console message: @32 Not allowed to load local resource: FilePath

**Comment by shivaprsdv** [comment]
This probably is not a `pywebview` issue. You seems to be accessing a local file at an absolute path, which is restricted by sandboxing for security reasons.

See [http://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource](http://stackoverflow.com/a/39007314).

Can you show us the HTML your are trying to load?

**Comment by JeanPierreFig** [comment]
Yeah That's what I thought, I was testing it first on a mac and it worked. I think the problem is that the raspberry pi Uses Chromium as it's base. 

```

html = """
    
        <!DOCTYPE html>
        <html>
    
        <head>
    
        </head>
        <style media="screen">
    
        body{
        background-color: black;
    
        }
    
        .center {
        max-width: 100%;
        max-height: 100%;
        bottom: 0;
        left: 0;
        margin: auto;
        overflow: auto;
        position: fixed;
        right: 0;
        top: 0;
    
        }
        </style>
    
        <body>
    
        <img src="/data/" alt="HTML5 Icon" class="center">
    
        </body>
    
    
    
        </html>
    
    
        """.replace('/data/', data)
```


This is the string that I am passing. data is `file:///home/pi/images/imageName`
interestingly if I pass the image file alone with out html then it works but I need the styling

**Comment by r0x0r** [comment]
First things first, GTK or QT?

**Comment by r0x0r** [comment]
Try the relative path instead

**Comment by shivaprsdv** [comment]
Also, have you tried saving the code in an `.html` file and running it in a web browser in the same machine?

**Comment by r0x0r** [comment]
@JeanPierreFig Is this still relevant?

**Comment by edif** [comment]
"Not allowed to load local resource"
