### ISSUE TITLE
Pywebview & pyinstaller: How to set inbuilt-http server root as current folder as exe

### ISSUE THREAD

**Issue by nithi2023** [r0x0r/pywebview#1010]
### Specification
- pywebview version: latest
- operating system: windows
- web renderer: Edge

```
import webview
import os
cwd = os.getcwd()

def get_current_url(window):
    window.load_url(window.get_current_url()+'/index.html')
    print(window.get_current_url())

if __name__ == '__main__':
    window = webview.create_window('Application Chart v1', 'index.html', min_size= (1000,800), width=1280, height=1024)
    webview.start(get_current_url, window, http_server=True, debug=True)
```
    
Everything works until I pack this into single exe using pyinstaller. It says "Path /index.html not found". 
I use this command to build exe: `pyinstaller.exe --onefile --noconsole --icon=favicon.ico .\httpd.py`

There is not option set http server root folder as current directory as exe. 
Please help!

**Comment by mphirke** [comment]
The issue is arising because you are not including your index.html with your pyinstaller exe, so it cannot find it.

In your .spec file (generated by pyinstaller), add your index.html in the data or while giving pyinstaller command, add your index.html as data.

For example, try this command (note the -add-data part).
`pyinstaller.exe --onefile --noconsole --add-data='index.html;.' .\httpd.py`

You can also just edit your .spec file (automatically built in the folder you ran pyinstaller) and add the 'index.html' there. For example,


```
a = Analysis(['1010.py'],
             pathex=[],
             binaries=[],
             datas=[('index.html', '.')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
....
rest of stuff here
```

**Comment by nithi2023** [comment]
I forgot to mention, the index.html displays a chart with a data from a excel file, I want keep the index.html & excel file outside (instead of packing), so that I can change excel in future. Also, If you have noticed I have set `http_server=True` so, that I can use  fetch() to load xlsx file over http ( and avoid content security warning). Is there any way to set http root directory as current directory as the .exe ?

**Comment by mphirke** [comment]
```
import webview
import os
import sys

base_dir = '.'
if hasattr(sys, '_MEIPASS'):
    base_dir = os.path.join(sys._MEIPASS)

def get_current_url(window):
    window.load_url(window.get_current_url()+'/index.html')
    print(window.get_current_url())

if __name__ == '__main__':
    window = webview.create_window('Application Chart v1', os.path.join(base_dir,'index.html'), min_size= (1000,800), width=1280, height=1024)
    webview.start(get_current_url, window, http_server=True, debug=True)
```
> Is there any way to set http root directory as current directory as the .exe ?
Sorry if I'm misunderstanding your question, but the above code works for me, while keeping index.html outside of the .exe.

Also I think http_server will be depreciated in favor of bottle.py in next release so maybe it's a good time to switch to that.
