### ISSUE TITLE
Multiple HTTP servers starting with a single URL

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#1017]
A fresh bug from the 4.0 release. When starting pywebview with a local url (ie url='src/index.html'), two bottle.py servers are started. @robb-brown could you take a look?

**Comment by robb-brown** [comment]
I’ll have a look tonight. 

Robert Brown, PhD
ShadowLab Research Inc.
www.deepdiscovery.org
github.com/robb-brown
www.robbtech.com

**Comment by robb-brown** [comment]
PR [1018](https://github.com/r0x0r/pywebview/pull/1018/commits/7022fbef4a58ccf0fb0c966ec9e6d78ece3875ed)

should fix it. Example http_server.py only starts one server now.

**Comment by r0x0r** [comment]
Thank you!
