### ISSUE TITLE
Pressing delete key causes back navigation

### ISSUE THREAD

**Issue by shivaprsdv** [r0x0r/pywebview#102]
Pressing the Delete key on Mac causes the webview to navigate to the previous page.

Doesn't happen in Linux[GTK]. Don't know the case of Windows.

Seems undesirable in a desktop application.

**Comment by r0x0r** [comment]
Confirmed. It occurs on Windows as well. I managed to fix it on Windows, but OSX is more tricky. Cannot figure out how to capture a backspace key event on the webview.
The current progress (ie. the Windows fix) can be found in the disable-backspace branch

**Comment by r0x0r** [comment]
Ok, the problem on OSX is that an event handler captures alphanumerical keys, but not backspace. I have pushed an intermediate version to the disable-backspace branch.

**Comment by shivaprsdv** [comment]
For me the event handler _does_ capture backspace the very first time we run the application (just after it is given focus). The problem is, even after making our WebView the `firstResponder`, it gets overridden once you click inside the WebView. A mysteriously-undocumented class called `WebHTMLView` is designated the `firstResponder` then (try printing `theEvent.window().firstResponder()` inside the `keyDown_` method, you'll see), and I strongly believe it is that class that handles the Delete button and causes the back navigation.

Alas, this `WebHTMLView` seems to be resistant to sub-classing, somewhere in an SO thread I found it was a 'private' class or something. The only reference is the [source-code](https://opensource.apple.com/source/WebKit/WebKit-7536.30.1/mac/WebView/WebHTMLView.mm.auto.html), try searching for `firstResponder` in that code.

A temporary hack was to implement `resignFirstResponder` of our WebView and let it return `NO`, and it works, but it now blocks all events on the view including mouse-clicks. \*sigh\*

Hope that help figure out a better solution. For now I've dug it deep enough. \*exhausted\*

**Comment by shivaprsdv** [comment]
For a quick confrontation with the 'villain', run:
```
import WebKit
print WebKit.WebHTMLView
```

**Comment by r0x0r** [comment]
This post seems to deal with the responder problem above http://www.taffysoft.com/pages/20120908-01.html

This goes way over my head, though

**Comment by shivaprsdv** [comment]
Seen that already, no idea what it's all about.

**Comment by shivaprsdv** [comment]
Solved it finally! See PR. 😄

**Comment by r0x0r** [comment]
Windows and OSX fixes are now in master.
Thank you 👍

**Comment by stackJolin** [comment]
> Seen that already. Same here, no idea what it's all about.

So，how did you do，I have a same problem。。。。
