### ISSUE TITLE
Problem with loading local HTML since 4.0

### ISSUE THREAD

**Issue by CrisPinto06** [r0x0r/pywebview#1020]
### Specification
- pywebview version: 4.0, 4.0.1
- operating system: Windows 10
- web renderer: mshtml

### Description  
  
 Since 4.0 update, local HTML files only load some of the time. In version 3.7.2, I can load local HTML everytime. Why is this?

**Comment by r0x0r** [comment]
A built-in web server is launched automatically for local HTML files in 4.0. Could you share more details on cases when local html files are not loaded? Does `debug=True` give any more information?
You can still local HTML files without spinning up a web server  using `file://` schema.

**Comment by brotherhero** [comment]
It loads, but takes over a minute for the page to come up.  No difference in http_server=false nor debug=True.  For me, it's Windows 10 x64 running python 3.10 (tried 3.11 as well using virtualenv.)  Example http_server.py cat video scared me this morning since I forgot it was running 😁

**Comment by r0x0r** [comment]
With debug=True, do you get any useful console output?

**Comment by brotherhero** [comment]
Ah, it's an issue when running in a virtual environment.  I changed my cores and it no longer has an issue.  I noticed it immediately when I ran on my own desktop and did not have a lag problem.  As for the user that opened this issue, I'm assuming he's running it in a VM as well.

**Comment by r0x0r** [comment]
Should be fixed in 4.0.2
