### ISSUE TITLE
 function window.get_cookies() throws KeyError exception

### ISSUE THREAD

**Issue by LTsCreed** [r0x0r/pywebview#1021]
### Specification
- pywebview version:  4.0.1
- operating system: Windows 10
- web renderer:  cef
- Python: 3.9

### Description  
 Function get_cookies throws KeyError exception because key ''samesite" does not exists.
 
![Screenshot from 2023-01-22 21-05-33](https://user-images.githubusercontent.com/3992437/213935664-a5344b5b-32cf-4340-8eba-feac76335777.png)

**Comment by r0x0r** [comment]
Fixed in master
