### ISSUE TITLE
debug mode often fails to load resources

### ISSUE THREAD

**Issue by geekzsp** [r0x0r/pywebview#1025]
### Specification
- pywebview version:  4.0.1
- operating system: win10
- web renderer:  WinForms / Chromium

### Description  
  
  When I use the `debug=True, http_server=True`, I often run into situations where I can't load front-end resources
  
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/23443948/215633565-f75d62f0-9912-41a1-bde2-ae62b7c9efc6.png">

Resources are loaded only after multiple restarts
<img width="1730" alt="image" src="https://user-images.githubusercontent.com/23443948/215633678-64bb388f-48df-4686-a663-94a795740c1d.png">

### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
What do server requests looks like in Network tab of the dev tools?

**Comment by geekzsp** [comment]
> What do server requests looks like in Network tab of the dev tools?
No request.When I tried to access port 42001 in my browser, it took a long time to respond

**Comment by r0x0r** [comment]
There is a similar issue here https://github.com/r0x0r/pywebview/issues/1020
According to the op, it is caused by a virtual environment. Can you test whether this is the case for you as well?

**Comment by geekzsp** [comment]
> There is a similar issue here #1020 According to the op, it is caused by a virtual environment. Can you test whether this is the case for you as well?

This may not be the case. I am running a packaged pyinstaller application. no virtual environment

**Comment by r0x0r** [comment]
Sounds like this might be caused by the default single-threaded server. Maybe switching to `paste` or similar would help. https://bottlepy.org/docs/dev/deployment.html#server-options

Would you able to give it a go?

**Comment by geekzsp** [comment]
> Sounds like this might be caused by the default single-threaded server. Maybe switching to `paste` or similar would help. https://bottlepy.org/docs/dev/deployment.html#server-options
> 
> Would you able to give it a go?

```python
   server.thread = threading.Thread(
            target=lambda: bottle.run(app=app, port=server.port, quiet=not _debug['mode'], server='cheroot'),
            daemon=True)
```
According to the documentation, after setting multithreading mode, it worked fine ，Thank you

**Comment by r0x0r** [comment]
I have implemented a simple multithreaded server in https://github.com/r0x0r/pywebview/tree/multithreaded-server branch. @geekzsp would you be able to test it and see if it solves the problem?

**Comment by geekzsp** [comment]
> I have implemented a simple multithreaded server in https://github.com/r0x0r/pywebview/tree/multithreaded-server branch. @geekzsp would you be able to test it and see if it solves the problem?

It's perfect
