### ISSUE TITLE
Could not find module 'shcore' (or one of its dependencies).Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by LeoMyMe** [r0x0r/pywebview#1027]
### Specification
- pywebview version: 4.0.1
- operating system:win7 64bit
- web renderer: webview2
- python version:python 3.8
### Description  
   Python.Runtime.PythonException: **Could not find module 'shcore' (or one of its dependencies).Try using the full path with constructor syntax.**
   在 Python.Runtime.PythonException.ThrowLastAsClrException()
   在 Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   在 Python.Runtime.Dispatcher.Dispatch(Object[] args)
   在 __System_Threading_ThreadStartDispatcher.Invoke()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callbac
k, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Objec
t state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Objec
t state)
   在 System.Threading.ThreadHelper.ThreadStart()
So I must back to pywebview-3.6.3 with pythonnet-2.5.2.
I guess this may be the missing DLL or python 3.8's new DLL loading rule.
### Practicalities
- YES/NO I am willing to work on this issue myself.
No
- YES/NO I am prepared to support this issue financially.
No

**Comment by r0x0r** [comment]
Sorry I have no idea about this error. Looks like a broken Python installation if I must take a guess
