### ISSUE TITLE
Suggestion: add take_focus window option

### ISSUE THREAD

**Issue by mi4code** [r0x0r/pywebview#1030]
### Specification
- pywebview version: 4.0.1
- operating system: Windows, Linux
- web renderer: gtk, qt, winforms

### Description  
 add option to not focus to the webview window when user clicks it (useful when making floating tools like onscreen keyboard so you can type into another window)
  can be someting like `webview.create_window(..., take_focus=True)`

I managed to implement it for `winforms`, `qt` and `gtk` (since i dont have macOS enviroment to test on i havent tried make it work on `cocoa` - maybe [this](https://stackoverflow.com/questions/11936915/cocoa-prevent-window-activation) can be the way to go)

[See my current implementation](https://github.com/mi4code/pywebview)

In general it works fine but the `qt`’s and `gtk`’s implementations seem to not be compatible with every system/desktop enviroment.

Can I make PR?
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Yes, please go ahead. The parameter signature could be `create_window(focus=True)`
