### ISSUE TITLE
Frameless window flickers when dragged from one monitor to the other on Mac OS

### ISSUE THREAD

**Issue by max-uho** [r0x0r/pywebview#1031]
### Specification
- pywebview version: 4.0.1
- operating system: Mac OS Ventura 13.2
- web renderer: Cocoa Webkit

### Description  
  
When creating a frameless window on Mac OS it flickers if dragged across monitors.
It sort of jumps back and forth between them at a high rate.
This does not happen when frameless is set to False. 
Happens with easy_drag set to both True or False.
  
### Practicalities

- YES I am willing to work on this issue myself.

~~- NO I am prepared to support this issue financially.~~

**Comment by resonates** [comment]
I also ran into this issue, the window keeps moving  at high frequencies in its original position and where i want.

**Comment by r0x0r** [comment]
This bug does not occur on my system. Macbook Pro 14, 2021, Ventura 13.0.1

**Comment by max-uho** [comment]
Surprising. It occurs for a short period when the window is at the same time on both monitors (my monitors are set up to be one above the other - haven't tested the X-Axis). It gets confused on what Y-coordinates it should use (mouse or edge of the window).
My workaround will be to have more control on the chrome of the window, maybe using native toolbar elements - the behaviour of the window (sticking to the edge of the screen if moved slowly for example) seems it should be handled by the OS.
