### ISSUE TITLE
on_top  Does not work

### ISSUE THREAD

**Issue by zd20041** [r0x0r/pywebview#1036]
### Specification
- pywebview version:  4.0.1
- operating system: win11
- web renderer: I don't know

### Description  
![图片](https://user-images.githubusercontent.com/100107030/217883877-b16db6a4-be9b-45ad-9f26-ce8098a2591e.png)

run exampes/on_top.py
on_top  Does not work

**Comment by mi4code** [comment]
Same thing happens to me on Windows 10 when using `edgechromium` web renderer (it seems to be something wrong with winforms).
Using `qt` instead solved it for me (just change `webview.start(deactivate, window)` to ` webview.start(deactivate, window, gui='qt')`).

**Comment by zd20041** [comment]
> Same thing happens to me on Windows 10 when using `edgechromium` web renderer (it seems to be something wrong with winforms). Using `qt` instead solved it for me (just change `webview.start(deactivate, window)` to ` webview.start(deactivate, window, gui='qt')`).

Thanks Solved

**Comment by THEGOLDENPRO** [comment]
I don't think this should be closed as it still doesn't work on `edgechromium` and I really need a chromium browser in my project. I hope a fix to this is discovered.

**Comment by THEGOLDENPRO** [comment]
> I don't think this should be closed as it still doesn't work on `edgechromium` and I really need a chromium browser in my project. I hope a fix to this is discovered soon.

I'm having this issue on both 4.0.1 and also 3.6.3 of pywebview. I'm on windows 10 using python 3.8 atm.

**Comment by r0x0r** [comment]
This issue has existed for quite a bit of time, but the fix was surprisingly simple. No idea why it has not been fixed before.
I pushed the fix to master.

**Comment by THEGOLDENPRO** [comment]
thank you 💛
