### ISSUE TITLE
Error: Requiring namespace 'Soup' version '2.4', but '3.0' is already loaded

### ISSUE THREAD

**Issue by JamesClarke7283** [r0x0r/pywebview#1041]
### Specification
- pywebview version: 4.0.1
- operating system: GNU/Linux, Parabola(Archlinux)
- web renderer: gtk or cef

### Description  
Any time i use the gtk or cef web renderer i get this error:
"ImportError: Requiring namespace 'Soup' version '2.4', but '3.0' is already loaded"
  If i use the latest 3.x version it runs fine.
### Practicalities

- I am not able to work on this issue myself.

- I am not prepared to support this issue financially at this time.

**Comment by keredson** [comment]
@JamesClarke7283, apologies if I'm stating the obvious here, but for a workaround you can add that line (`gi.require_version('Soup', '2.4')`) in your own code before you import `pywebview`.

**Comment by r0x0r** [comment]
Should be fixed in 4.0.2
