### ISSUE TITLE
FOLDER_DIALOG and SAVE_DIALOG should allow for folder creation

### ISSUE THREAD

**Issue by max-uho** [r0x0r/pywebview#1042]
### Specification
- pywebview version: 4.0.1
- operating system: all
- web renderer: any

### Description  
  
I suggest adding the option allow_folder_creation=False to window.create_file_dialog()
There are many cases where this would be useful:

- When saving (obvious) SAVE_DIALOG
- When choosing a download destination FOLDER_DIALOG

On Cocoa, 
```
open_dlg = AppKit.NSOpenPanel.openPanel()
open_dlg.SetCanCreateDirectories_(True)
```

or 
```
save_dlg = AppKit.NSSavePanel.savePanel()
save_dlg.setCanCreateDirectories_(True)
```

I tried fiddling with the cocoa.py file but no luck.

### Practicalities

- YES/NO I am willing to work on this issue myself.

~~- YES/NO I am prepared to support this issue financially.~~

**Comment by r0x0r** [comment]
Folder creation can be enabled by default for save dialogs. There is no need to have it for open dialogs in my opinion.

**Comment by max-uho** [comment]
One use case for open dialog folder creation would be a download manager app where you would want to set a destination.

**Comment by r0x0r** [comment]
Fair enough. A compromise could be to have allow_folder_creation set to True for save dialogs and False for open dialogs.
