### ISSUE TITLE
Unable to run with pythonw or PyInstaller

### ISSUE THREAD

**Issue by simonrob** [r0x0r/pywebview#1044]
#1029 reported an issue with PyInstaller that was resolved for the original reporter with the [logwriter-bottle branch](https://github.com/r0x0r/pywebview/tree/logwriter-bottle) that was merged in #1038.

For me this does not fix the issue, because `bottle`, which is causing the problem, requires `stdout` and `stderr` to exist before it is even imported. On Windows, neither `pythonw` nor PyInstaller support this.

To replicate without needing PyInstaller, run the pywebview Hello World example with `pythonw` rather than `python`. This is a regression since pywebview version 4.0 because of the introduction of `bottle`.

One fix would be to import `bottle` *after* the new `DummyLogWriter`, and change the `hasattr(sys, '_MEIPASS')` check in `http.py` to instead check for `stdout` and `stderr` existing (similar to [how this used to work in PyInstaller](https://github.com/pyinstaller/pyinstaller/pull/7217/files#diff-6fd40ede55a45d6e668b717c4c44676484fa0c4650e410b9be76c9e3979255ae)).

The root cause is that `bottle`, for almost its entire existence until relatively recently, tested for the `write` method of `stdout` and `stderr`, but only caught an `IOError`, not an `AttributeError`. This was [fixed in 2021](https://github.com/bottlepy/bottle/commit/5e2efb6ad9c12d986c59926d0b3f99be003189d0), but it doesn't seem like a new PyPi release is coming anytime soon, so most pywebview users will probably have the latest version (0.12.23) that does not include this change.

I'm happy to submit a PR, but thought you might have your own preferred way of resolving things like this that are related to importing dependencies.

**Comment by codedocta** [comment]
use --windowed flag
