### ISSUE TITLE
How to specify startup screen when the device has multi monitors

### ISSUE THREAD

**Issue by bnuzhouwei** [r0x0r/pywebview#1045]
How to specify startup screen when the device has multi monitors?

**Comment by r0x0r** [comment]
You cannot. This is not implemented.

**Comment by bnuzhouwei** [comment]
Is any system apis that can do this.

**Comment by r0x0r** [comment]
I have not investigated this, but I am sure there is API for that.
If you decide to implement, then API can be something like this `create_window(screen=screen_instance)`, where screen_instance is a screen object of `webview/screen.py`. Some kind of screen identifier should be added to the screen object as well
