### ISSUE TITLE
fetch api cannot load http://127.0.0.1/js_api/xxxxxxxxxxxxxxx due to access control checks

### ISSUE THREAD

**Issue by bnuzhouwei** [r0x0r/pywebview#1046]
### Specification
- pywebview version: latest
- operating system: ubuntu 22.04 desktop
- web renderer: gtk

### Description  

The current url is from https://...., and it occurs:

can't post message to jsapi for:

fetch api cannot load http://127.0.0.1/js_api/xxxxxxxxxxxxxxx due to access control checks
  
It is correct on windows with Webview2, but in Ubuntu got the error, is the setting incorect?

**Comment by r0x0r** [comment]
Can you post a minimal example?

**Comment by bnuzhouwei** [comment]
```python
import webview
import time
class JSAPI():
    def log(self, msg):
        print(msg)
def done():    
    print("done func start")
    time.sleep(6)
    #print("send msg to python")
    #webview.windows[0].evaluate_js('''alert("1")''')    
    window.evaluate_js('''window.pywebview.api.log('message from js')''')
    print("done func end")
window = webview.create_window('Hello world', 'https://pypy.org', js_api=JSAPI(), min_size=(1024,768))
webview.start(done, debug=True)
```

got error:

```
fetch API cannot load http://127.0.0.1:21388/js_api/abdb136a-ad22-11ed-aca5-a36e69518321 due to access control checks.
```

**Comment by bnuzhouwei** [comment]
It seems that on windows, there is direct message post method with out starting a web server.
but on linux, a web server is started with the app, and cause the access control from https to http.

**Comment by r0x0r** [comment]
The reason for this error is because 127.0.0.1 is http and pypy.org is https. It refuses to make an unsecure connection.
Coincidentally this PR https://github.com/r0x0r/pywebview/pull/1039 introduces ssl support, which fixes this problem. Just set `start(ssl=True)`.
