### ISSUE TITLE
pywebview] WebView2 initialization failed with exception:

### ISSUE THREAD

**Issue by KVS08** [r0x0r/pywebview#1053]
### Specification
- pywebview version 4.0.1: 
- operating system win7:
- web renderer could'n determine: 

### Description  
  
By running this code:
import webview
webview.create_window("test", "https://www.google.com/")
webview.start(storage_path=r'D:\Documents\python_projects\trashProject', private_mode=False)

i get the following error:
[pywebview] WebView2 initialization failed with exception:
 Была сделана попытка загрузить программу, имеющую неверный формат. (Исключение из HRESULT: 0x8007000B)
   в Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   в Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()

����ࠡ�⠭��� �᪫�祭��: Python.Runtime.PythonException: Could not find module 'shcore' (or one of its dependencies). Try using the full path with constructor syntax.
   � Python.Runtime.PythonException.ThrowLastAsClrException()
   � Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   � Python.Runtime.Dispatcher.Dispatch(Object[] args)
   � __System_Threading_ThreadStartDispatcher.Invoke()
   � System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   � System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   � System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   � System.Threading.ThreadHelper.ThreadStart()

Process finished with exit code -532462766

### Practicalities

NO I am willing to work on this issue myself.

NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry I have no idea about Windows 7.
It is a 15 years old operating system and its support was ended by Microsoft three years ago. 

Having said that if somebody finds a fix for this, I will accept a PR.
