### ISSUE TITLE
System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib

### ISSUE THREAD

**Issue by wuwuwuwuwuwuwuwuwuuuu** [r0x0r/pywebview#1055]
`Unhandled Exception: System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at ClrLoader.DomainData..ctor(AppDomain domain)
   at ClrLoader.ClrLoader.Initialize() `

win11、python3.8,pycharm,flask,pywebview,pyinstaller
I package a web to exe,but it can not operate in win7,there is a wrong like up
I try to write in win7、python3.8,pycharm,flask,pywebview,pyinstaller
it can not run
I have exclude flask,pyintaller
pywebview make this problem
somebody say win7 need .net4.0,I have upgrade to .net4.8
how to solve it ,thank you very much!

**Comment by r0x0r** [comment]
Sorry I have no idea about Windows 7. It is a 15 years old operating system and its support is ended by Microsoft three years ago.

**Comment by wuwuwuwuwuwuwuwuwuuuu** [comment]
Thanks for your reply，I use python3.6 and older pycharm solve it.Some old computer can not operation over win7 os.I have to study how to make software onwin 7.Thank you！发自我的手机-------- 原始邮件 --------发件人： Roman ***@***.***>日期： 2023年2月22日周三 05:57收件人： r0x0r/pywebview ***@***.***>抄送： wushiyou ***@***.***>, Author ***@***.***>主    题： Re: [r0x0r/pywebview] System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib (Issue #1055)
Sorry I have no idea about Windows 7. It is a 15 years old operating system and its support is ended by Microsoft three years ago.
