### ISSUE TITLE
Can the menu be customized for each window?

### ISSUE THREAD

**Issue by InfernalAzazel** [r0x0r/pywebview#1056]
### Specification
- pywebview version: 4.0.1
- operating system: Ubuntu 20.04 tls
- web renderer: 

### Description  
  
  Can the menu be customized for each window?

  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Not currently. This is planned, but implementation has been left out of the 4.0 release.

**Comment by InfernalAzazel** [comment]
You can refer to tauri for design. There are many functions in use and it is user-friendly. I still hope to see pywebview become another tauri. The language I am most familiar with is python.
