### ISSUE TITLE
Problem with running examples/menu.py on Windows and clicking on the menu

### ISSUE THREAD

**Issue by oudon-umai** [r0x0r/pywebview#1058]
### Specification
- pywebview version: 4.0.0 - 4.0.2
- operating system: Windows11 22H2
- web renderer: 

### Description  
  
![名称未設定](https://user-images.githubusercontent.com/126043732/220583526-687bf488-d139-44ae-b702-45bc54fb132a.png)

When I run "pywebview/examples/menu.py" on Windows and click on the menu, I get a "Python.Runtime.PythonException".
The reason for this seems to be that when a click event is added in winforms.py, a "System.Threading" Thread function is registered when a "threading" Thread function should be registered.
  
```
action_item.Click += lambda _,__,menu_line_item=menu_line_item : Thread(target=menu_line_item.function).start() #crash
↓
(import threading)
action_item.Click += lambda _,__,menu_line_item=menu_line_item : threading.Thread(target=menu_line_item.function).start() #It works
```

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This one is fixed in master.
