### ISSUE TITLE
[BUG] The qt menu click event cannot be triggered, and there is also a problem with rendering

### ISSUE THREAD

**Issue by InfernalAzazel** [r0x0r/pywebview#1059]
### Specification
- pywebview version: 4.0.2
- operating system: Ubuntu 20.04 lts
- web renderer: qt

### Description  
  
![20230223-101139](https://user-images.githubusercontent.com/40333954/220806991-9b1b963c-c87f-49bf-85de-b1cf679a2dfd.gif)

code:

https://github.com/InfernalAzazel/PYChatGPT.git

  
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I could not reproduce this with `examples/menu.py`. Correct event handler is called for every menu item.
