### ISSUE TITLE
Got GTK error when running webview.start twice

### ISSUE THREAD

**Issue by bismarckkk** [r0x0r/pywebview#1063]
### Specification
- pywebview version: 4.0.2
- operating system: ArchLinux
- web renderer: gtk

### Description  
test code:
```python
import webview
import time

if __name__ == '__main__':
    first_window = webview.create_window('Window #1', html='<h1>First window</h1>')

    def destroy():
        time.sleep(2)
        first_window.destroy()

    webview.start(gui='gtk', func=destroy)
    twice_window = webview.create_window('Window #2', html='<h1>Second window</h1>')
    webview.start(gui='gtk')
```
It will get error "g_application_parse_command_line: assertion '!application->priv->options_parsed' failed".
I found that this may be due to it setup app when app is not none, but app did not be set to None when app running ends.
https://github.com/r0x0r/pywebview/blob/90b64462184e8bb666ce1562e94e3053238feba2/webview/platforms/gtk.py#L529-L533  
Maybe should add `_app = None` to L548?
https://github.com/r0x0r/pywebview/blob/90b64462184e8bb666ce1562e94e3053238feba2/webview/platforms/gtk.py#L545-L547
### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
To be honest running `webview.start` has not been taken into consideration. I see not reason why it should not work though. If you find a fix, please submit a PR.
