### ISSUE TITLE
Retain zoom level when loading new url? 

### ISSUE THREAD

**Issue by wrjenny** [r0x0r/pywebview#1064]
### Specification
- pywebview version: 3.7
- operating system: Windows

### Description  
  
possible to retain zoom level when loading new url?
1) creating window zoomable=true
2) zooming in/out to different zoom level than 100%
3) subsequent loading of new url with window.load_url:  zoom level is lost / again back to 100%
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
WebView2 has ZoomFactor property, so it might be possible by storing this value and setting it again on a new page load. If anyone wants to give it a go, PR is welcomed.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.zoomfactor?view=webview2-dotnet-1.0.1462.37
