### ISSUE TITLE
'Window' object has no attribute 'events'

### ISSUE THREAD

**Issue by Boris-code** [r0x0r/pywebview#1065]
### Specification
- pywebview version: 3.5
- operating system: macos
- web renderer: 

### Description  
  
python3.9
```
>>> import webview
>>> window = webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
>>> window.events
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Window' object has no attribute 'events'
```
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Upgrade to the latest version of pywebview. `window.events` was introduced after 3.5
