### ISSUE TITLE
set_cookies() function in python

### ISSUE THREAD

**Issue by eldjoko** [r0x0r/pywebview#1067]
Hi,

Is there a way we can set/create cookies from python same way there is a get-cookies() function ?

Thanks!

**Comment by r0x0r** [comment]
No, this is not implemented.
It can be done, but the real question is how much of JS functionality should be duplicated in Python. The reason for get_cookies was to get all cookies, including those not in available via JS (ie. SameSite). You can set cookies via `window.evaluate_js('document.cookies=your_cookies')`

**Comment by eldjoko** [comment]
Thank you @r0x0r !!

Valid point, i have chosen to keep frontend code separate from backend by just having JS set cookies on the frontend.

This issue can be closed. Thank you!
