### ISSUE TITLE
NiceGui + Pywebview

### ISSUE THREAD

**Issue by hditano** [r0x0r/pywebview#1069]
### Specification
- pywebview version: 4.0.2
- operating system: Windows 10/ ArchLinux
- web renderer: 

### Description  
  
  Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.
  
  Has anyone been able to make work **nicegui** along with **pywebview**, mostly because for features on both sides.
  
as you can see on the nicegui docs:

![image](https://user-images.githubusercontent.com/6069906/223397847-581c1489-17d1-4be6-9e61-86f88d576abe.png)

  here's my code... 
  
```
import webview
from nicegui import ui


ui.label("Hello World")
ui.button("click me", on_click=lambda: ui.notify("clicked button"))
ui.run(port=8080)

window = webview.create_window('Hello', url='http://0.0.0.0:8080')
webview.start(debug=True, private_mode=False)
```

  
 It starts a browser + pywebview: At first it will open browser with page not found error + pywebview not found error.
  
  
![image](https://user-images.githubusercontent.com/6069906/223399699-9ff2a65a-d0e3-4a1a-8a7e-eb584649158a.png)

then... if I close pybwebview window, it will reload perfectly.

![image](https://user-images.githubusercontent.com/6069906/223399930-a3b06d7e-427e-4001-976b-313ad6eb4f3c.png)

**Comment by r0x0r** [comment]
Both nicegui and pywebview must be run on main threads. Here is a working example. You might want to replace sleep with events

```
import webview
from nicegui import ui
from multiprocessing import Process
from time import sleep

def start_webview():
    sleep(1)
    window = webview.create_window('Hello', url='http://127.0.0.1:8080')
    webview.start(debug=True, private_mode=False)

if __name__ in '__main__':
    t = Process(target=start_webview)
    t.start()

ui.label("Hello World")
ui.button("click me", on_click=lambda: ui.notify("clicked button"))
ui.run(port=8080, show=False)

```

**Comment by micocube** [comment]
> Both nicegui and pywebview must be run on main threads. Here is a working example. You might want to replace sleep with events
> 
> ```
> import webview
> from nicegui import ui
> from multiprocessing import Process
> from time import sleep
> 
> def start_webview():
>     sleep(1)
>     window = webview.create_window('Hello', url='http://127.0.0.1:8080')
>     webview.start(debug=True, private_mode=False)
> 
> if __name__ in '__main__':
>     t = Process(target=start_webview)
>     t.start()
> 
> ui.label("Hello World")
> ui.button("click me", on_click=lambda: ui.notify("clicked button"))
> ui.run(port=8080, show=False)
> ```

The idea of pywebview+nicegui is very interesting, I have another solution, I think when the window of webview is closed, nicegui should automatically exit, so, I let nicegui run in the thread, you can try it:https://github.com/micocube/nicepywebview.git , welcome comments

**Comment by firai** [comment]
Sorry to bring up a semi-dead thread, but I wanted to put this here in case anyone else lands here from Google or Github search:

NiceGUI v1.2 introduced a [`native` mode](https://nicegui.io/documentation#native_mode), which is powered by `pywebview`. Therefore, you don't need to manually manage the two using multiprocessing as shown above anymore. Also, since v1.2.4, the options listed in [`webview-create-window`](https://pywebview.flowrl.com/guide/api.html#webview-create-window) and [`webview-start`](https://pywebview.flowrl.com/guide/api.html#webview-start) can be passed through NiceGUI's `app.native.window_args` and `app.native.start_args` (see NiceGUI's documentation for `native` mode linked to above).
