### ISSUE TITLE
exe.WebView2 folder created next to the executable.

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#1071]
### Specification
- pywebview version:  4.0
- operating system: win10
- web renderer: edgechromium

### Description  
  
 When executing the EXE, after packaging it in a single EXE with pyinstaller, that is called proyect.exe, when executing the exe, it creates, next to it a **proyect.exe.WebView2**.

This was not happening before, so I don't know why it started happening now, but I read here:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32

That is related to the webview. But, is there anyway, or should there be a way, to specify another location for that folder in thge pywebview eco-system?

Thanks, 
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This looks like it is because of this change. https://github.com/r0x0r/pywebview/commit/0b61f882603dc5fc8d5dedbe426945aa38761d77

The corresponding issue is https://github.com/r0x0r/pywebview/issues/1037
Try to set `storage_path` to a desired location to see if it fixes the issue

**Comment by martinlombana** [comment]
Thanks.

By the way, in the docs, that setting is not reflected. And the link the the changelog in the main menu is broken. Moreover, when clicking in the What's new link, it directs to the changelog, but to an older version. Just to let you know.

Thanks,

**Comment by r0x0r** [comment]
With private_mode=True user data folder had not been set at all prior the change. The change was introduced to address the case when c: drive was not writable. My guess it was writing to %APPDATA%. 
Anyhow some sensible default location should be introduced

**Comment by jczic** [comment]
Hello @r0x0r and @martinlombana,
the current problem is that WebView2 is stored next to the executable.

However, the executable is very often installed, for all users, in **```<ProgramFiles>\<Company>\<AppName>\<app>.exe.WebView2```**
Thus, when running, WebView2 tries to access its folder adjacent to the application and does not have write permissions...

By default, the storage folder should be placed in **```<User>\AppData\Local<AppName>\```**, right?
This used to work fine but would get mixed up in ```<User>AppData\Local\pywebview\```
What do you think about it?

**Comment by r0x0r** [comment]
@jczic I agree that the default location should be `<User>\AppData\Local\<AppName>\`, but to my knowledge it is not possible to get Application name for Pyinstaller frozen applications during runtime. Correct me if I am wrong.

There are improvements to the user data folder commited to the master as follows 
1) User data folder is always set
2) the default location is  <User>AppData\Local\pywebview\. If this is not writable, then it uses <User>\pywebview\

**Comment by jczic** [comment]
Yes @r0x0r, you are right, the name of the application is not known.
And on MacOS, it is even more complex with the location in the bundle of the app and the authorized storage location.

Finally, for my part, I simply force an application name from my sources, then it is stored in the best possible place to work properly.

Here's what I do:

```python
storage_path = (str(conf.DIRECTORY_FILES) if conf.IS_WIN32 else None)
```

Where in `conf`, I have for **Windows** :
`DIRECTORY_FILES = Path('~/AppData/Local').expanduser() / APPLICATION_BUNDLE_NAME` where the bundle name is hard coded but maybe anything at all.

For other systems, `storage_path=none` and I manage config files in :
`Path('~/Library/Application Support').expanduser() / APPLICATION_BUNDLE_NAME` for **MacOS**
`Path('~/.config/').expanduser() / APPLICATION_BUNDLE_NAME` for **Linux**

So, no worries with that.

( Be careful though, if I want to access the resources of my application on MacOS, I have to use a particular conditional path depending on whether it is in an App Bundle or simply elsewhere (launch with standard python...) by using `sys.executable` or `__file__` depending).

---
Also, thank you @r0x0r for your work! 😉
It's top notch and I was able to make a nice interface with it ([ESP32 MPY-Jama](https://github.com/jczic/ESP32-MPY-Jama) if you want to have a look).
