### ISSUE TITLE
Block external open

### ISSUE THREAD

**Issue by jtssi** [r0x0r/pywebview#1075]
### Specification
- pywebview version: 4
- operating system: Windows
- web renderer: webview2

### Description  
Hello, I am looking for a way to block the external opening of pages but I can't find it in the api. When I click on a link, my default browser opens the page, I wanted to know if there is a way to block the opening of external windows.

**Comment by r0x0r** [comment]
This is by design. What is your use case for blocking external links?

**Comment by jtssi** [comment]
Hello, in fact when you click on the mouse wheel, it is the default browser that opens.
In the same way, when certain sites open new windows, it is the default browser that opens the page. Is there a way to block this or to open the pages in the same window? Thanks

**Comment by r0x0r** [comment]
Correction: only links with target=_blank are opened in an external browser. All other links are opened inline.

**Comment by jtssi** [comment]
thank you, can't we block this and the mouse wheel click?

**Comment by r0x0r** [comment]
It can be done, but I must ask you again. What would you want do this?

**Comment by Fidode07** [comment]
You can inject some JS where you search all <a> Tags and remove the target='_blank' attribute from each element.

**Comment by r0x0r** [comment]
I have introduced `webview.settings` dict to control pywebview's default behaviour. To open links internally you set `webview.settings['OPEN_EXTERNAL_LINKS_IN_BROWSER'] = False`. To be released in 5.0.

**Comment by Upgreydd** [comment]
@r0x0r Hey mate, sorry for disturbing you, but is it possible to add that sooner than 5.0 release? I've tested 5.0 but I guess it's not ready yet.
