### ISSUE TITLE
[Question] What's the suggested way to open and show image in webview?

### ISSUE THREAD

**Issue by link89** [r0x0r/pywebview#1076]
Hi, I am new to pywebview and I have just walk through the example to learn how to use it.  I would like to use pywebview to work with OpenCV to do some analysis tasks which require to open a image file and show it in the webivew window. There is example of open file dialog which could be used to selected the path, but I don't know how to display the processed image (which is a numpy array) in the webview. 

Do I need to implement a JS API to set the base64 encoded content to the webview runtime, or there is better option? I would like to write an example for such use case once I figure out how to make it. Thank you!

**Comment by r0x0r** [comment]
If I understand correctly, you want to open a file using open file dialog, process it in numpy and display the result to user. If so, you could achieve this with `webview.create_file_dialog` and `webview.evaluate_js('document.write("<img src=\'base64\'>")')`
JS API is for passing data from Javascript to Python.

**Comment by link89** [comment]
I see. Just wondering is it possible to pass binary data as blob from Python to Javascript, or base64 encoding is the only possible method? And is there a detecated API for data transfer or I should always use `webview.evaluate_js` for such task?

**Comment by r0x0r** [comment]
You can always use a http server (built-in or an external one) for communication between Python and Javascript domains. Otherwise base64 and `evaluate_js` is the only option.
