### ISSUE TITLE
NoneType has no len() and  WebView2 (E_ACCESSDENIED) exceptions

### ISSUE THREAD

**Issue by al-eax** [r0x0r/pywebview#1081]
im currently working on a way to add icon support for pywebview. I stumbled over these issues:

### Specification
- pywebview version: current master branch at commit https://github.com/r0x0r/pywebview/commit/9257c25a1e6ae35696b872de77e12d347d33fa04
- operating system: Windows 10
- web renderer:  winforms

### Description  

running the following example i get two exceptions:

```py
import webview
webview.create_window("foo",url="https://google.com")
webview.start()
```

### first exception `NoneType has no len()`
```
Python.Runtime.PythonException: object of type 'NoneType' has no len()
   bei Python.Runtime.PythonException.ThrowLastAsClrException()
   bei Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   bei Python.Runtime.Dispatcher.Dispatch(Object[] args)
   bei __System_Threading_ThreadStartDispatcher.Invoke()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, O
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object st
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object st
   bei System.Threading.ThreadHelper.ThreadStart()
```
 
__caused by:__

https://github.com/r0x0r/pywebview/blob/9257c25a1e6ae35696b872de77e12d347d33fa04/webview/platforms/winforms.py#L189

__simple fix:__

```py
if BrowserView.app_menu_list:
     self.set_window_menu(BrowserView.app_menu_list)
```
or set `app_menu_list = []` in https://github.com/r0x0r/pywebview/blob/9257c25a1e6ae35696b872de77e12d347d33fa04/webview/platforms/winforms.py#L135

### second exception `E_ACCESSDENIED`

```
[pywebview] WebView2 initialization failed with exception:
 Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 (E_ACCESSDENIED))
   bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()
```

__caused by:__

https://github.com/r0x0r/pywebview/blob/9257c25a1e6ae35696b872de77e12d347d33fa04/webview/platforms/edgechromium.py#L155

after some research i found out that webview has no access to `UserDataFolder`, see here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1128

The `cache_dir` passed to `EdgeChrome` instance is `None`:
https://github.com/r0x0r/pywebview/blob/9257c25a1e6ae35696b872de77e12d347d33fa04/webview/platforms/winforms.py#L196

caused by [the else statement](https://github.com/r0x0r/pywebview/blob/9257c25a1e6ae35696b872de77e12d347d33fa04/webview/platforms/winforms.py#L120L131):

```py
if not _private_mode or _storage_path:
    try:
        app_data = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
        cache_dir = _storage_path or os.path.join(app_data, 'pywebview')


        if not os.path.exists(cache_dir):
            os.makedirs(cache_dir)
    except Exception as e:
        logger.exception(f'Cache directory {cache_dir} creation failed')
else:
    cache_dir = None
```

### Practicalities

- YES I am willing to work on this issue myself.
   - I will create a PR this evening

**Comment by r0x0r** [comment]
This can be solved by setting `storage_path` parameter of `webview.start`. A more robust solution could be check if %APPDATA% is writable and if not write to UserProfile or something like that.

**Comment by al-eax** [comment]
I think the second exception is raised because `cache_dir` is None by default.
