### ISSUE TITLE
pywebview open with blank page

### ISSUE THREAD

**Issue by yinkh** [r0x0r/pywebview#1083]
### Specification
- pywebview version: 3.7.2
- operating system:ubuntu16.04.7
- web renderer: gtk

### Description  
use flask for backend,and use vue for frontend. run well on ubuntu18\ubuntu20\ubuntu22, but on ubuntu16, open client get blank page;
  
on ubuntu18,webkit2 version is 2.32.3
![image](https://user-images.githubusercontent.com/8170059/228223634-1de43b40-d9b1-4407-9875-37e38cebce7a.png)

on ubuntu16, webkit2 version is 2.20.5
![image](https://user-images.githubusercontent.com/8170059/228223910-597e0267-df52-4189-8576-2d95cc5fd1fc.png)

my main.py is 
![image](https://user-images.githubusercontent.com/8170059/228224081-b6ef0eb9-85f7-4678-927b-f4412f3717cc.png)

python main.py will get blank page with js error on console
![image](https://user-images.githubusercontent.com/8170059/228224361-62c10b7e-e1a2-432a-958d-cc8231bf806b.png)

this is no js error when open same address on firefox

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

If you need any other info, pls comment below

**Comment by yinkh** [comment]
https://pywebview.flowrl.com/guide/installation.html#dependencies

![image](https://user-images.githubusercontent.com/8170059/228225012-ae94f863-a213-46b4-b2af-d927cc79683b.png)
i have notice some feature require webkit2 > 2.22, is this the reason why i cant open vue inside webview?

**Comment by yinkh** [comment]
![image](https://user-images.githubusercontent.com/8170059/228420870-b8215511-8963-4af8-b1eb-29dea09d9602.png)
some error like this

**Comment by yinkh** [comment]
try use qt webengine , and it work, issue finished!

**Comment by r0x0r** [comment]
This issue has existed for some users for quite a bit of time, but I have never managed to reproduce or track it down. This is definitely something that should be fixed, so any help is welcomed

**Comment by yinkh** [comment]
@r0x0r If you mean blank page on window10，I have meet this situation there times. the error code is  **STATUS_INVALID_IMAGE_HASH**, you need to change regedit table, create folder name Edge under \HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft ,then create folder WebView2 under Edge, new config name **RendererCodeIntegrityEnabled**, set value to 0. then reopen pywebview.
