### ISSUE TITLE
Python errors, when coming from the UI api class, do not show in python console but in Dev Console. 

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#1084]
### Specification
- pywebview version: 4.0.2
- operating system: Windows
- web renderer: edgecrome

### Description  
  
When I am using the intermediary API class, the errors that could arise in python, are redirected, somehow, to the developers console, and they do not show in the debug trace of python. As I do not use the dev-console for my main development (as the UI that I designed has only 3 buttons and that's all) I spent 3 hours scratching my head, trying to debug an error that I thought was silent... 

How can I get all errors and avoid any redirect, in the regular console? (I am speaking about python errors, not JS errors).

In this self contained example, you can see that when you click on the button, there is an error, because, obviously, "sdd" is not defined, and it is a python error. But I get it in the developers console, and NOT in my regular console with all my python traces, as you can see here:

![image](https://user-images.githubusercontent.com/18351919/228236307-fb015360-3c97-4d82-83f7-33c5507fc973.png)

  
```
from dataclasses import dataclass
import webview
from webview import Window
import enum
from typing import Callable

subscribers = dict()


def subscribe(event_type: enum, fn: Callable):
	if event_type not in subscribers:
		subscribers[event_type] = []
	subscribers[event_type].append(fn)


def post(event_type: enum, data=None):
	if event_type not in subscribers:
		return
	for fn in subscribers[event_type]:
		if data is not None:
			fn(data)
		else:
			fn()


class UIApi:
	window: Window = None
	
	def test_send(self):
		print('Class: UIApi, Function: test_send, Line 33')
		post('TESTEVENT', 'teststrdata')


@dataclass
class TestClass:
	
	def __init__(self):
		subscribe('TESTEVENT', self.test)
	
	def test(self, data):
		sdd
		print("data", data)


def init_program(window):
	global robot_maker
	robot_maker = TestClass()


# event.post(UIEvent.OPEN_DATA_FILE, "sdsds")


if __name__ == '__main__':
	ui_api = UIApi()
	html_code = '''
	 <head></head>
	 <body>
	  <button onclick="api.test_send()" id="open_button"><img src="img/icons/bar-chart-outline.svg">Click me</button>
	 <body>
	 
	 <script>
	 let api = null
	 window.addEventListener('pywebviewready', function() {
    api = pywebview.api
    });
	 </script>
	'''
	window = webview.create_window('JEM', html=html_code, js_api=ui_api, min_size=(1024, 720))
	
	ui_api.window = window
	webview.start(init_program, window, debug=True, gui='edgechromium')

```

Thanks,

**Comment by martinlombana** [comment]
Thanks. I can't see the fix in the master though, where exactly?

**Comment by r0x0r** [comment]
Sorry my bad. Github's new signing key caught me by suprise. Try now.

**Comment by martinlombana** [comment]
I see it thanks! (I had applied it myself just this morning, in the raw code, but I didn't know if that was the exact place to put it).

And, how about the reverse, also? Is there or would there be a way to get the console.logs and or JS errors in the python console? Where would that be feasible?
