### ISSUE TITLE
TypeError: start_server() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by intervall-peter** [r0x0r/pywebview#1085]
### Specification
- pywebview version: 4.0.2
- operating system: Ubuntu 22.04 ARM64
- web renderer: GTK

### Description  
I use the `FLASK_DEBUG` environment variable to activate debug mode and implemented a file watcher to reload the flask server and the webview. On MacOS everything works fine but on Ubuntu I get following error message:  
```
Traceback (most recent call last):
  File "/home/trost/app/src/backend/main.py", line 32, in <module>
    webview.start(debug=DEBUG, server_args={'debug': DEBUG})
  File "/home/trost/app/.venv/lib/python3.9/site-packages/webview/__init__.py", line 142, in start
    prefix, common_path, server = http.start_global_server(http_port=http_port, urls=urls, server=server, **server_args)
  File "/home/trost/app/.venv/lib/python3.9/site-packages/webview/http.py", line 133, in start_global_server
    address, common_path, global_server = start_server(urls=urls, http_port=http_port, server=server, **server_args)
  File "/home/trost/app/.venv/lib/python3.9/site-packages/webview/http.py", line 128, in start_server
    return server.start_server(urls, http_port, **server_args)
TypeError: start_server() got an unexpected keyword argument 'debug'
```
  
It looks like the `start_server` method of the `BottleServer` does not accept any kwargs. On MacOS there is a different code path going from `__init__.start` through `window._initialize`, while on Ubuntu it is `__init__.start` through `http.start_global_server`. 

This is the code I'm using, the `server_args` are passed in the last line:  

```python
if __name__ == "__main__":
    DEBUG = os.environ.get("FLASK_DEBUG", False)
    default_width = 1320
    default_height = 800
    min_size = (default_width, default_height)
    stream = StringIO()
    with redirect_stdout(stream):
        window = webview.create_window(
            "MyApp",
            url=server,
            min_size=min_size,
            width=default_width,
            height=default_height,
            text_select=True
        )
        if DEBUG:
            from observer import observe_and_reload

            # run file watcher for dev in a separate thread
            threading.Thread(target=observe_and_reload, args=(window, server), daemon=True).start()
        webview.start(debug=DEBUG, server_args={'debug': DEBUG})
```
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Yes, you are correct that server_args is not passed to start_server. There has been no need for that, but this could be fixed. Feel free to submit a PR. Thanks!
