### ISSUE TITLE
Qtwebkit: Mouse single click doesn't work

### ISSUE THREAD

**Issue by daidalvi** [r0x0r/pywebview#1089]
### Specification
- pywebview version: 4.0.2
- operating system: Kubuntu, Alt K Workstation
- web renderer: qt (qtwebkit)

### Description  
  
Cannot select inputs and run javascript on click events with mouse single click. Works only with double click. On qtwebengine everything works fine 
  
### Practicalities

I fixed it by adding condition  if is_webengine before mousePressEvent in `qt.py` on line **161**:

I changed

```
        def mousePressEvent(self, event):
```

with

```
        if is_webengine:
            def mousePressEvent(self, event):
```

**Comment by r0x0r** [comment]
Could you try if removing `event.accept()` at line 162 fixes the problem?
