### ISSUE TITLE
2023-04-07 18:24:56.750 Python[1418:1149756] -[WKWebView _setDrawsTransparentBackground:] is deprecated and should not be used

### ISSUE THREAD

**Issue by linktomarkdown** [r0x0r/pywebview#1094]
### Specification
- pywebview version: 
- operating system:
- web renderer: 

### Description  
  
  Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Feel free to provide a PR. Thanks!
