### ISSUE TITLE
Right-click context menu not showing up

### ISSUE THREAD

**Issue by naoufelfrioui** [r0x0r/pywebview#1096]
### Specification
pywebview 3
platform / version: Windows 10  64-bit
- web renderer: Chromium 

### Description  
  
When running:

webview.create_window(window_title)
webview.start(debug=False)

I can right-click what I want , but the contextmenu  is not showing up but it is enabled when debug is set to true

how Enable right-click to copy or paste when i use debug= False

**Comment by r0x0r** [comment]
This is by design to hide browser UI attributes.

**Comment by naoufelfrioui** [comment]
i want to enable the right-click context menu in a webview window  when i use debug= False
