### ISSUE TITLE
how to install it on rasberry pi?

### ISSUE THREAD

**Issue by Jzhenli** [r0x0r/pywebview#1097]
Hi, I'm newer to this project, and want to know how to install it on the rasberry pi ?

I have tried as the guide installation, but failed.

**Comment by r0x0r** [comment]
There is this three years old ticket on issues with Raspberry https://github.com/r0x0r/pywebview/issues/523
I tested it back then and managed to install GTK dependencies (but with poor performance), but no success with QT. Haven't investigated it since then.
