### ISSUE TITLE
pywebview menu  is not similar to Electron js menu 

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1098]
### Description  
Electron js menu is similar to windows menu but pywebview is not why please explain
  <br>
![image](https://user-images.githubusercontent.com/61788052/232735484-fc5cf138-2c56-44fc-bf82-b52d897decda.png)

**Comment by r0x0r** [comment]
Windows has three or four official GUI toolkits and each one of them has a slightly different menu. pywebview uses https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.menustrip?view=windowsdesktop-8.0 with default settings. I don't know what Electron is using.
