### ISSUE TITLE
Javascript module serverless mode

### ISSUE THREAD

**Issue by cdbdev** [r0x0r/pywebview#1101]
### Specification
- pywebview version: 4.0.2
- operating system: Windows 10
- web renderer: default (WinForms / Chromium)

### Description  
  
  When I try to run a javascript module, the file is translated as "text/plain" instead of "application/javascript".
  Is there any option to set an asset directory or something? Maybe I've missed it.

  Thx

**Comment by cdbdev** [comment]
Ok, I managed to get it work with a workaround like this:
```
import mimetypes
mimetypes.add_type('application/javascript', '.js')
```

**Comment by r0x0r** [comment]
Sorry I don't follow. Give me an example of your code running a Javascript module

**Comment by cdbdev** [comment]
main.py:
```
import webview

import mimetypes
mimetypes.add_type('application/javascript', '.js')
# print(mimetypes.guess_type('index.js'))

class Api():
    def doSomething(self):
        pass

if __name__ == "__main__":
    api = Api()
    webview.create_window("pyace editor", "index.html", js_api = api, min_size = (600, 450))
    webview.start(debug=True)
```

index.html contains the following:
```
<script type="module" src="/js/index.js" charset="utf-8"></script>         
```
It is the "script type" that causes the problem, but is fixed if I add the mimetype for javascript.
It seems like Windows does not correctly guess the type...

**Comment by r0x0r** [comment]
I could not reproduce this on Windows 10 / EdgeChromium.

Python
```
import webview
webview.create_window('test', 'index.html')
webview.start()
```

index.hml
```
<!doctype html>
<html lang="en" data-framework="javascript">
	
<body>
<script type="module" charset="utf-8">
    import './test.js'
</script>

	</body>
</html>
```

test.js

```
alert('w00t')
```

Result:

<img width="524" alt="image" src="https://github.com/r0x0r/pywebview/assets/1549657/ba019472-faa5-4f47-b5b4-cfe2d434fbe9">
