### ISSUE TITLE
how to not to use the bottle server in master branch

### ISSUE THREAD

**Issue by kletel** [r0x0r/pywebview#1104]
how to not to use the bottle server in master branch please @r0x0r ?

**Comment by r0x0r** [comment]
`webview.start(http_server=False)`
Note that for relative local URLs (e.g. `location/index.html`), http server starts automatically.

**Comment by kletel** [comment]
> `webview.start(http_server=False)` Note that for relative local URLs (e.g. `location/index.html`), http server starts automatically.


Hi @r0x0r Roman,

with the following code : 
self.application_path = os.path.dirname(os.path.abspath(sys.executable))
self.htmlpath = os.path.join(self.application_path, 'htmlui')
api.currenthtmlfile = 'login.html'
url = os.path.join(api.htmlpath, api.currenthtmlfile)
browserwindow = webview.create_window(
            title=appname,
            url=api.url,
            width=width,
            height=height,
            localization=window_localization_override,
            confirm_close=confirmclosetrue,
            js_api=api,
            server=None
        )

browserwindow.load_url(url)
webview.start(debug=debugwebview, http_server=False)

[pywebview] Using WinForms / Chromium
Bottle v0.12.25 server starting up (using ThreadedAdapter())...
Listening on http://127.0.0.1:58371/
Hit Ctrl-C to quit.

the bottle server is still started, I have only local html files and not relative local URLs.

Thanks.


>

**Comment by kletel** [comment]
in the file venv/Lib/site-packages/pywebview-4.0.2-py3.11.egg/webview/__init__.py in master branch

if (http.global_server is None) and \
        (http_server or has_local_urls or (guilib.renderer == 'gtkwebkit2')):
            if not _private_mode and not http_port:
                http_port = DEFAULT_HTTP_PORT
            prefix, common_path, server = http.start_global_server(http_port=http_port, urls=urls, server=server, ssl=ssl, **server_args)

maybe we could add a condition here to not start the bottle server.

**Comment by kletel** [comment]
it start again the bottle server when it load another local html page

**Comment by r0x0r** [comment]
Could you format your code snippets? Thanks.

**Comment by kletel** [comment]
https://paste.ofcode.org/BF3M5b3yX4ukJZCMwua28V

**Comment by r0x0r** [comment]
Local paths (absolute or relative) always start a http server. If you don't want that, prepend your path with `file://` schema. Note that `file://` comes with all kind of limitations based on a renderer

**Comment by kletel** [comment]
I will try that thank you.
