### ISSUE TITLE
Create conda-forge package

### ISSUE THREAD

**Issue by juanfcocontreras** [r0x0r/pywebview#1106]
I think it would be good for the spread of the package, if it was available in the conda-forge repositories. Many companies and organizations use conda, and it is not good to mix pip and conda installations in the same environment, so many anaconda users choose not to install packages that are not available in conda.

The process is well documented and available from:

https://conda-forge.org/docs/maintainer/adding_pkgs.html

Do you think it would be possible?

**Comment by r0x0r** [comment]
I have very little experience with Conda. If you would like to create a Conda configuration file, then it could be incorporated.
