### ISSUE TITLE
How to load local images in pywebview?

### ISSUE THREAD

**Issue by sgxl** [r0x0r/pywebview#1107]
### Specification
- pywebview version: latest
- operating system: windows
- web renderer: 

### Description  
  
  Hi, thank you for making this great tool open source. I have no idea how to load local images with pywebview, 
I want to load local images in a serverless mode. Could you please give me some advise?
  
``` html
local image does not work:
<img src="{local_path}/xxx.jpg">

but remote image works
<img src="https://th.bing.com/th?id=OSK.b0698415d6276924ef8a793f0c09241a&w=148&h=148&c=7&o=6&dpr=1.3&pid=SANGAM">
```

**Comment by r0x0r** [comment]
Check `examples/todos` app. You need to include your images as relative paths to index.html.

**Comment by sgxl** [comment]
> Check `examples/todos` app. You need to include your images as relative paths to index.html.

Thanks for your reply, I know that. I want to make something like gallery viewer that can view the image files in the disk, but I do not know how to access local files (maybe in any directory) from html.

**Comment by rainy-25Ghz** [comment]
> Place images in the same directory or one of its subdirectories then you can access them via using relative urls as in the todos example

this will result in bad performance, for e.g. if there is an gallery app that need to show all images on the disk , it's impossible to copy all the file to the same dir as index.html
