### ISSUE TITLE
How to use bottle server route

### ISSUE THREAD

**Issue by sungyoun0216** [r0x0r/pywebview#1114]
### Specification
- pywebview version: 4.0.2
- operating system: win10
- web renderer: edgechromium

### Description  
I use the bottle server.
Accessing http://127.0.0.1:12233/test always returns 404.
How do you do routing?

**[test code]**
```
import webview.http as http
from bottle import route
...
@route('/test')
def test():
    return "test"
...

   webview.start(
        http_server=True, 
        debug=True, 
        server=http.BottleServer,
        http_port=12233
    )
```

**[webview start log]**
Bottle v0.12.25 server starting up (using ThreadedAdapter())...
Listening on http://127.0.0.1:12233/
Hit Ctrl-C to quit.

**Comment by einsqing** [comment]
Does anyone answer？ @r0x0r
