### ISSUE TITLE
key event help?

### ISSUE THREAD

**Issue by dan-garvey** [r0x0r/pywebview#1116]
### Specification
- pywebview version: 4.1
- operating system: "nt"
- web renderer: tk?

### Description  
  
  If I wanted to make it so my application will fullscreen pywebiew on a keypress, but my webapp itself doesn't natively support key events (gradio), is there a way to support this via evaluate_js?

**Comment by r0x0r** [comment]
I would say it depends on the application. With evaluate_js you can freely inject any Javascript, but hooking it to the application logic is another matter.
