### ISSUE TITLE
Disable Touchpad Elastic Overscroll for Edge/WebView2

### ISSUE THREAD

**Issue by firai** [r0x0r/pywebview#1118]
### Specification
- pywebview version: 4.1
- operating system: Windows
- web renderer: Edge (WebView2)

### Description  
  
Elastic overscroll for touchpads is enabled by default in Edge/WebView2, which doesn't look or feel right for desktop UI. It seems possible to turn off that flag as an environment option if WebView2 is initialized directly (https://github.com/MicrosoftEdge/WebView2Feedback/issues/3016), but it doesn't seem possible to pass this flag through pywebview currently. I propose that we disable this overscroll flag by default.
  
### Practicalities

- YES I am willing to work on this issue myself. (If I can figure out how this gets passed.)

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I agree, it should be disabled by default. Feel free to submit a PR
