### ISSUE TITLE
fullscreen is not window maximize, it just browser fullscreen mode, how to nativly maximize window?

### ISSUE THREAD

**Issue by kaluluosi** [r0x0r/pywebview#1119]
### Specification
- pywebview version: latest
- operating system: windows11
- web renderer:  edge

### Description  
My app is frameless and I reimplement titlebar myself.
But I can't find maximize function in window instance, only ToggleFullScreen.
 But ToggleFullsSreen is not window maximize, it just fullscreen mode of brower, how to nativly maximize window?
 
### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
`window.maximize` is not implemented. Feel free to contribute.
