### ISSUE TITLE
Use websockets with pywebview

### ISSUE THREAD

**Issue by mubarakalmehairbi** [r0x0r/pywebview#1120]
### Description  
  
When running a Flask-based pywebview app with Flask-sock package, I get this error:
`RuntimeError: Cannot obtain socket from WSGI environment.`
My goal is to use websockets with pywebview. 

### Practicalities

- YES/NO I am willing to work on this issue myself. NO

- YES/NO I am prepared to support this issue financially. NO

**Comment by r0x0r** [comment]
You can supply a custom WSGI server via `webview.start(server=wsgi_instance)`. You can try to supply eventlet.wsgi server there. Please report back if that works for you.

**Comment by mubarakalmehairbi** [comment]
I do not know how to create an instance of WSGI server because eventlet.wsgi.server returns `None`. It seems that `webview.serving` module was removed in pywebview v4 so the method in #774 cannot be used in the new version. However, I tried the following and it currently works:
```python
port = webview.http._get_random_port()
import eventlet
from eventlet import wsgi
def run_server():
    server = eventlet.listen(('localhost', port))
    wsgi.server(server, flask_app)

webview.create_window("Flask app with websockets", f"http://localhost:{port}")
webview.start(run_server)
```

Do you think that this is a proper way to do it? or will this method cause other concerns? For example: does using "http" instead of "https" in the desktop app matters?

**Comment by mubarakalmehairbi** [comment]
Or alternatively (easier way):
```python
port = webview.http._get_random_port()
def run_server():
    flask_app.run(port=port)

webview.create_window("Flask app with websockets", f"http://localhost:{port}")
webview.start(run_server)
```

**Comment by mubarakalmehairbi** [comment]
I will close this issue because my problem is solved, but if there are any security issues with my approach, please inform me of them. Thanks.
