### ISSUE TITLE
PyObjC Error: Exception during dealloc of proxy

### ISSUE THREAD

**Issue by chdominguez** [r0x0r/pywebview#1122]
### Specification
- pywebview version:  4.1
- operating system: macOS Monterey 12.6.5
- web renderer: Cocoa / Qt

### Description  
  
After setting up my pywebview project, I compiled some React code which works perfectly on the browser (Safari/Chrome) but, when running in pywebview I get the following error in the terminal when using Cocoa:
```
PyObjC: Exception during dealloc of proxy: Completion handler passed to -[BrowserDelegate webView:didReceiveAuthenticationChallenge:completionHandler:] was not called
```
Then some of the features coded in React won't work. I have searched in the [pyobjc repo](https://github.com/ronaldoussoren/pyobjc) about this but I did not find anything meaningful. When using Qt I do not get any error in the terminal but React code does not work as expected also.
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by chdominguez** [comment]
Okay so I fixed it by installing the whole pyobjc library. By default while installing pywebview, it only installed:
- pyobjc-core
- pyobjc-framework-cocoa
- pyobjc-framework-webkit

I ran `pip install pyobjc` and it fixed the issue after installing all the pyobjc modules. I suppose that not all of them are needed, but as a quick fix this works.

**Comment by r0x0r** [comment]
`pyobjc-framework-security` is a missing package that fixes this problem. I will update pyproject.toml
