### ISSUE TITLE
how i can use system tray

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1123]
### Description  
  
 @r0x0r 
tell me please how to can use system tray in pywebview 
like this :

![image](https://github.com/r0x0r/pywebview/assets/61788052/5ee07e88-a2f8-4595-9a26-f68ede0a6a79)

**Comment by r0x0r** [comment]
https://github.com/r0x0r/pywebview/blob/master/examples/pystray_icon.py
