### ISSUE TITLE
Since version 4.0，App inside high resolution screens looks too small

### ISSUE THREAD

**Issue by yinkh** [r0x0r/pywebview#1126]
### Specification
- pywebview version: 4.1
- operating system:window10
- web renderer: 
![image](https://github.com/r0x0r/pywebview/assets/8170059/12b6137e-e612-40e2-978b-1382c0640e45)

### Description  
  
 Since version 4.0，App inside high resolution screens looks too small

this is my desktop display config
![image](https://github.com/r0x0r/pywebview/assets/8170059/0cb41264-feaa-4911-982b-e818f4c1a3d1)

pywebview 4.1 looks like 
  ![image](https://github.com/r0x0r/pywebview/assets/8170059/12b6137e-e612-40e2-978b-1382c0640e45)

in pywebview 3.7.2 with same display config,app looks like:
![image](https://github.com/r0x0r/pywebview/assets/8170059/fd9a046b-0208-4496-bfa9-1157027e4d44)

I have find this issue https://github.com/r0x0r/pywebview/issues/87
### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by yinkh** [comment]
![image](https://github.com/r0x0r/pywebview/assets/8170059/f381692d-8c79-4510-b31f-bcc7320fa2ae)
commit 4a3c0a94 delete pywebview/webview/platforms/winforms.py:167 
```
self.AutoScaleDimensions = SizeF(96.0, 96.0)
```

**Comment by yinkh** [comment]
If i add this line back to /webview/platforms/winforms.py, this problem is fixed,shall i create a pr?

**Comment by r0x0r** [comment]
@yinkh I am not sure why it was deleted, nor I could find the reason in the git log. Let's introduce this back and if somebody complains, let's think of another solution.

**Comment by einsqing** [comment]
How to reslove it ?

**Comment by yinkh** [comment]
add self.AutoScaleDimensions = SizeF(96.0, 96.0) 
in pywebview/webview/platforms/winforms.py:167
