### ISSUE TITLE
Appending information to default user agent before starting webview

### ISSUE THREAD

**Issue by koolkunz** [r0x0r/pywebview#1132]
### Specification
- pywebview version: 4.1
- operating system: Windows 10
- web renderer: edgechromium

### Description

I want to add some information to the default user agent rather than completely replacing it. I could not figure out how to do it.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You cannot set it dynamically. It can be done though, if you want to give it a go. I propose adding `window.user_agent` getter/setter.

**Comment by koolkunz** [comment]
Ok but can you guide me a little how to do it?

**Comment by r0x0r** [comment]
Searching for `_user_agent` will reveal how user agent is got/set for different platforms. User agent getter/setter should be placed to `window.py`, you can take an example from other getters/setters.
