### ISSUE TITLE
this page is having a problem

### ISSUE THREAD

**Issue by x011** [r0x0r/pywebview#1133]
### Specification
- pywebview version: 4.1
- operating system: Windows 11
- web renderer: Assumed Chromium (no arguments on webview.start())

### Description

Error while starting:

```
[pywebview] Using WinForms / Chromium
[pywebview] WebView2 initialization failed with exception:
 'int' value cannot be converted to System.Boolean
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_EventHandler`1\[\[Microsoft_Web_WebView2_Core_CoreWebView2InitializationCompletedEventArgs\, Microsoft_Web_WebView2_Core\, Version=1_0_1518_46\, Culture=neutral\, PublicKeyToken=2a8ab48044d2601e\]\]Dispatcher.Invoke(Object , CoreWebView2InitializationCompletedEventArgs )
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()
```

Windows may have updated Microsoft Edge Webview2 Runtime. `113.0.1774.50` installed now.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by x011** [comment]
If I change the `1` to `True` on the debug arguments, the error disappears, old (bad habits) to use `1` as `boolean `, it works on many occasions, but it definitely creates problems sometimes.

 But I'm getting this after now after opening?

![image](https://github.com/r0x0r/pywebview/assets/4313821/dd530e47-a651-4daa-bb0d-bc318df1cf61)


The edge debug window  closes immediately after opening and I cannot debug this properly.
Any idea how to solve this error?
```
api = Api()
window = webview.create_window(url="https://somesite/index.html", js_api=api, width=width, height=height, title=win_title
webview.start(debug=True)
```

**Comment by r0x0r** [comment]
Looks like an edge chromium issue to me. Do you get this with any website?

**Comment by x011** [comment]
Solution: 
`Go to Settings > Apps > Apps & Features` > search for `Microsoft Edge` / `Microsoft Edge  WebView 2 Runtime` > click on the `...` dots > `Modify` > `Repair` or `Reset`.
