### ISSUE TITLE
CORS Policy in websocket + pywebview request on js

### ISSUE THREAD

**Issue by GGTEC** [r0x0r/pywebview#1134]
### Specification
- pywebview version: 4.0.1
- operating system: win 11
- web renderer: Chromium/Edge

### Description

  I'm trying to run a websocket server together with pyewbview, I managed to start both without problems, but when I need to make an http request to the pywebview server, an error related to CORS is returned, is it possible to disable CORS when starting pywebview?
  
  
JS Code to conect on websocket and make the http request = 

`        <script>
              
              var iframe = document.getElementById('myiframe');

              function update_iframe() {
                // iframe.src == http://localhost:7000/highlight/highlight.html
                fetch(iframe.src)
                  .then(function(response) {
                    // Verifica se a solicitação foi bem-sucedida
                    if (response.ok) {
                      // Processa a resposta como texto
                      return response.text();
                    } else {
                      throw new Error('Erro na solicitação. Código de status: ' + response.status);
                    }
                  })
                  .then(function(content) {
                  
                    iframe.contentDocument.documentElement.innerHTML = content;

                  })
                  .catch(function(error) {
                    console.error('Erro na solicitação:', error);
                  });
                }

              var socket = new WebSocket("ws://localhost:7688");
              socket.onopen = function(event) {
                  console.log("Conexão WebSocket estabelecida");
              };

              socket.onmessage = function(event) {
                if (event.data == 'HIGH'){
                  update_iframe()
                }
                console.log("Mensagem recebida do servidor: " + event.data);
              };
        </script>`

### Practicalities

-NO 

-NO

**Comment by r0x0r** [comment]
CORS cannot be disabled without disabling Chromium web security altogether. Cannot you set CORS headers on your websocket server?

**Comment by GGTEC** [comment]
I tried applying the headers cors from my websocket server function but it still didn't work (I had to use an alternative method to create the server, maybe that's why it's not working)

Here is the code snippet that handles the headers, if you prefer I can post the full code as well


```
def handshake(client_socket):
    data = client_socket.recv(1024).decode()

    key = ''
    for line in data.split('\r\n'):
        if 'Sec-WebSocket-Key:' in line:
            key = line.split(':')[1].strip()

    response = (
        'HTTP/1.1 101 Switching Protocols\r\n'
        'Upgrade: websocket\r\n'
        'Connection: Upgrade\r\n'
        'Sec-WebSocket-Accept: {accept_key}\r\n'
        'Access-Control-Allow-Origin: *\r\n'
        'Access-Control-Allow-Headers: *\r\n'  
        '\r\n'
    ).format(accept_key=generate_accept_key(key))

    client_socket.send(response.encode())
```

**Comment by GGTEC** [comment]
I was able to change the js to remove the fetch and keep it working, and now it works without any issues, sorry to mess it up.
