### ISSUE TITLE
Will developers provide mobile support in the future?

### ISSUE THREAD

**Issue by wjsw1781** [r0x0r/pywebview#1135]
First of all, I am Chinese, I don't know English, and my description may not be correct.  I found that Rust's tauri is also for WebView and wrappers Tauri is supporting Android and iOS, and I would like to ask if PyWebView will support mobile in the future

**Comment by baseplate-admin** [comment]
Hi,

Check https://github.com/r0x0r/pywebview/issues/377

**Comment by r0x0r** [comment]
Android support has been planned and it is certainly doable, but I have not worked on it, nor anyone else to my knowledge. IOS support was not something worth pursuing the last time I checked (several years ago), not sure if it has changed.

**Comment by baseplate-admin** [comment]
Hi @r0x0r ,

Thanks for creating this awesome library.

---
>  it is certainly doable

Can you share your idea on this? ( like technically speaking how do you plan to achieve this? )

**Comment by r0x0r** [comment]
It can be done with Kivy (maybe with help of bulldozer). Now looking at Kivy, there is iOS support as well, so maybe iOS can be implemented as well.

**Comment by baseplate-admin** [comment]
> It can be done with Kivy 

Actually yes. Recently [flet](https://github.com/flet-dev/flet) made this possible. 

If you need a tad bit of inspiration, you can take a look at[ flet architecture](https://flet.dev/blog/flet-mobile-update/#flet-mobile-architecture) to get a better idea on how they have implemented it
