### ISSUE TITLE
Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)

### ISSUE THREAD

**Issue by xabispacebiker** [r0x0r/pywebview#1140]
### Specification
- pywebview version: 4.1
- operating system: Debian 10
- web renderer:

### Description

When login into an odoo instance I get in the debug console: "Failed to load resource: the server responded with a status of 414 (Request-URI Too Large)
  https://mydomain/web/webclient/qweb/7293847987fs9d8f798237498sd7f9a8sd7fs987234h234792837487sdf?mods=base,web,queue_job,base_setup,bus,web_tour,mail,sales_team,product,web_editor,http_routing,auth_signup,portal,resource,digest,account,payment,utm,sale,sale_management,barcodes,stock,purchase,report_xlsx,date_range,account_financial_report,contacts,purchase_stock,account_invoice_constraint_chronology,account_invoice_line_report,account_payment_mode,account_payment_partner,account_payment_purchase,account_payment_purchase_stock,account_payment_sale,account_tax_balance,auth_totp,auth_totp_portal,auto_backup,base_iban,base_bank_from_iban,base_import,base_iso3166,base_location,base_location_geonames_import,debug_permission,iap,l10n_es,l10n_es_aeat,l10n_es_aeat_mod303,report_qweb_parameter,report_xml,l10n_es_partner,l10n_es_facturae,mail_bot,web_decimal_numpad_dot,partner_contact_personal_information_page,partner_contact_in_several_companies,payment_transfer,sms,stock_packaging_sale_purchase,web_kanban_gauge"

Any clue ?
### Practicalities

- YES/NO I am willing to work on this issue myself.
YES
- YES/NO I am prepared to support this issue financially.
MAYBE

**Comment by r0x0r** [comment]
This is a server side error. Does the same url work with a browser?

**Comment by xabispacebiker** [comment]
It works with any browser, chrome, firefox, safari, etc.. you can test here.. https://demo.odoobai.com/ demo:demo

**Comment by r0x0r** [comment]
@xabispacebiker I reproduced this error, but my best bet is that the problem is with GTK webkit renderer. It works with qt though.
