### ISSUE TITLE
intercept requests  and  modify the response content 

### ISSUE THREAD

**Issue by wall-git** [r0x0r/pywebview#1143]
I want to listen to and intercept requests or local redirect behavior in web pages, and then modify the returned content as needed. How can I achieve this?I haven't found any relevant events to support this matter. Is there a good way?

**Comment by wall-git** [comment]
Microsoft WebView2  solution is as follows
coreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
coreWebView2.WebResourceRequested += WebResourceRequested;
Is there a similar event in this？

**Comment by r0x0r** [comment]
I have not explored this. Implementing a cross-platform solution seems to be tricky.

**Comment by wall-git** [comment]
Actually, I want to do the encryption function for static files and decrypt them when reading. The previous plan was to intercept requests and decrypt the returned messages. Is there a good idea?
