### ISSUE TITLE
Python PyWebView - Blank page on my Mac when try to loads any external item outside my localhost

### ISSUE THREAD

**Issue by viniciusramaral** [r0x0r/pywebview#1144]
Hi. How are you?

I'm trying to execute a PyWebView example from this repo: https://github.com/r0x0r/pywebview I'm using the Flask Example: https://github.com/r0x0r/pywebview/tree/master/examples/flask_app

When I try to load or interact with external item out of my localhost, the PyWebView appears as blank like don't load anything. When I comment or exclude any element that refers a online content, the window opens normally.

It doesn't matter if my content is an image, or a CSS Google Fonts, or trying to call an external authentication, the system doesn't work anyway.

I tried the same code in a Windows PC and it works normally. I tried http and https and in both cases the problem was the same.

I'm using a Macbook Pro M1, Ventura 13 and I don't have firewall or VPS.

Thanks

I've tried in Windows and It Works. I've tried in Mac again switching off all references from external elements and the system worked normally in both platforms.

**Comment by haavee** [comment]
Oh! We're running into the same problem trying to use @simonrob 's email-oauth2-proxy on (some) versions of MacOS!
For us, being doomed to use Office365 mail, being able to add OAuth2 using `pywebview` that's embedded in the proxy is a life saver!

**Comment by haavee** [comment]
Well, it's literally what happens in our case on some systems: for the OAuth the window needs a redirect to localhost and all we end up with is a very empty blank screen

**Comment by r0x0r** [comment]
Can you try running it with debug=True and see if there are any errors in JS console?

**Comment by haavee** [comment]
The system showing the issue is not my own system so access to it is limited, but I will try, thanks!
Having said that - specifically _where_ do I pass `debug=True`?

**Comment by r0x0r** [comment]
`webview.start(debug=True)`

**Comment by viniciusramaral** [comment]
> Can you try running it with debug=True and see if there are any errors in JS console?

When I do It, the PyWebView does not allow to check the console. The right click is not allowed too.

if __name__ == '__main__':
    webview.create_window(
            'SERVER PHOTORF – PIXEL3', 
            app, 
            width=1920, 
            height=1080,
            x=None, 
            y=None, 
            resizable=True, 
            fullscreen=False, 
            min_size=(800, 600),
            hidden=False, 
            frameless=False, 
            easy_drag=True,
            minimized=False, 
            on_top=False, 
            confirm_close=True, 
            background_color='#FFFFFF',
            transparent=False, 
            text_select=False, 
            zoomable=False, 
            draggable=False,
            localization=None)
    webview.start(debug=True)

You can check the same code executing in diferent OSs.
Windows work wells and in the Mac, blank page.

https://www.loom.com/share/b571766f49154ae79aee7c98470bb5e3

**Comment by haavee** [comment]
Update: yesterday I was able to run with `webview.start(..., debug=True)` on my colleague's computer.
The only information shown was:

    webview using Cocoa
    2023-06-15 12:11:3: python3.9[30839:12165130] PyObjC: Exception during dealloc of proxy: Completion handler passed to -[BrowserDelegate webView:didReceiveAuthenticationChallenge:completionHandler:] was not called
    2023-06-15 12:11:3: Waiting for URL matching `redirect_uri`; following browser redirection to [login.microsoftonline.com/[](http://login.microsoftonline.com/[)...]

**Comment by r0x0r** [comment]
Try `pip install pyobjc-framework-Security`.

**Comment by viniciusramaralpython** [comment]
@r0x0r 
Sorry for my late feedback.
You were amazing.
Your advise has saved my life.
Thanks a lot.
