### ISSUE TITLE
Frameless laggy windows when moving

### ISSUE THREAD

**Issue by xpierroz** [r0x0r/pywebview#1152]
### Specification
- pywebview version:  4.0.2
- operating system: Windows 11
- web renderer: I don't know what this is, but i'm using a NiceGUI Server

### Description

I'm using a frameless windows, however, when moving it, it is very laggy, even makes sometimes like 3 seconds response time, it looks like the same error as #713 

If you need the code to my project please ask i'll send it

### Practicalities

- YES _I am willing to work on this issue myself._ **I can help but I don't know how to help**

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Yes this is the same issue.
I cannot reproduce it with `examples/drag_region.py` (Macbook M1, Parallels, Windows 10), but if you want to investigate it, then "winforms easy drag lag" may be a good starting query.

This discussion might be of help too
https://stackoverflow.com/questions/67532369/winforms-form-lags-when-trying-to-move-drag-it-on-windows-10

**Comment by xpierroz** [comment]
I'll try to look into it this week, however i'm not very experienced, so don't except results.
