### ISSUE TITLE
папка cookie отдельно для каждого сайта

### ISSUE THREAD

**Issue by FenixZip** [r0x0r/pywebview#1157]
### Specification
- pywebview version:
- operating system:
- web renderer:

Можно сделать так, чтобы в приложение для каждого сайта была своя папка для cookie.
Все должно быть в одном окне, не создавая дополнительных окон.
Как пример: в меню сайт вк моя и вк друга. 
### Description

  Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
В теории можно, но на данный момент не позволяет архитектура. Если есть желание этим заняться, то можно добавить параметр `create_window(storage_path=None)`. При любом другом значении чем None, параметр бы устанавливал бы папку для конкретного окна. В случае None, использовалась бы глобальная настройка.
