### ISSUE TITLE
Активная сессия, поток

### ISSUE THREAD

**Issue by FenixZip** [r0x0r/pywebview#1158]
### Specification
- pywebview version: 4.1
- operating system:
- web renderer:

### Description
Я уже весь интернет облазил, не могу найти информацию.
Через приложение я захожу на сайт, логинюсь и когда я перехожу на другой сайт, меня выкидывает.
Сессия прерывается.
Можно сделать так, чтобы сессия была активная при этом я мог переходить на другие сайты?
Все должно быть в одном окне. Я не силен в этом, не удите срого.
  Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Какая платформа?

**Comment by FenixZip** [comment]
windows

**Comment by r0x0r** [comment]
`webview.start(private_mode=True)` пробовал?

**Comment by FenixZip** [comment]
> `webview.start(private_mode=False)`испытал?

да. при переходе на другоой сайт и возвращаясь нужно заново логиниться.

**Comment by r0x0r** [comment]
Протестировал с win10 / webview2, не удалось воспроизвести
  1.
```
webview.create_window('test', 'https://mail.google.com')
webview.start(debug=True, private_mode=False)
```
2. логин
3. в js console `window.location.href = 'https://woot.fi'`
4. в js console снова `window.location.href = 'https://mail.google.com'`
