### ISSUE TITLE
Input type file not working

### ISSUE THREAD

**Issue by Anuj16** [r0x0r/pywebview#116]
Hey guys,

I am trying to upload a file using html's default file type input. But the file dialog is not opening from pywebview window. It's working in other browsers.

<input  id=""  name="" type="file" />

Can anyone please guide me with what may be wrong here  ? Is there any settings that needs to be done ?

Thanks in advance.

**Comment by shivaprsdv** [comment]
This is unimplemented. Confirmed on Mac. Need to work on a fix. Thanks
for pointing it out @Anuj16.👍 On what platform you are?

Btw you may need to edit your comment to read "_But the file dialog is
**not** opening from pywebview window..._"

**Comment by Anuj16** [comment]
@shivaprsdv Thanks for the quick reply. 
I am on mac.

**Comment by shivaprsdv** [comment]
Working on it.

**Comment by shivaprsdv** [comment]
Mac implementation is ready. The patch is up at [my fork repo](https://github.com/shivaprsdv/pywebview/commit/d1173bacea8d428d3a5e1ce3b3262d3c818eab94), you might
want to check it out, it should solve your problem.

**Comment by Anuj16** [comment]
Thanks so much @shivaprsdv . Will surely check this out.

**Comment by r0x0r** [comment]
Merged Shiva's PR with master. 
I've checked with other platforms and it is implemented everywhere else but OSX. Thanks again for your contribution, Shiva.

**Comment by shivaprsdv** [comment]
Welcome, Roman. 🙂 

@Anuj16 Hope you got it working..
