### ISSUE TITLE
Frameless window on linux not moving

### ISSUE THREAD

**Issue by EightShift** [r0x0r/pywebview#1164]
### Specification
- 4.1
- Ubuntu 22.04.2
- GTK

### Description

When trying to move a frameless window on linux with ".pywebview-drag-region", the window is not moving, but the following lines are displayed in the console:

`...`
`127.0.0.1 - - [29/Jun/2023 19:30:20] "POST /js_api/c64542d0-1680-11ee-8c78-69eba9940b8b HTTP/1.1" 200 4`
`127.0.0.1 - - [29/Jun/2023 19:30:30] "POST /js_api/c64542d0-1680-11ee-8c78-69eba9940b8b HTTP/1.1" 200 4`
`127.0.0.1 - - [29/Jun/2023 19:30:40] "POST /js_api/c64542d0-1680-11ee-8c78-69eba9940b8b HTTP/1.1" 200 4`
`127.0.0.1 - - [29/Jun/2023 19:30:50] "POST /js_api/c64542d0-1680-11ee-8c78-69eba9940b8b HTTP/1.1" 200 4`
`...`
And on windows 11 everything works as it should.

### Practicalities

- YES.

- NO.

**Comment by r0x0r** [comment]
Works for me with `examples/drag_region.py`. Excessive logging is due `debug=True`. I have removed it from the example.

**Comment by EightShift** [comment]
@r0x0r, thanks for your answer.
Surprisingly, even your simple example doesn't work on my Ubuntu...
Everything starts and works as it should, but dragging the window doesn't want to work...

Am I missing some dependencies or environment variables?

Everything works perfectly on Windows...
