### ISSUE TITLE
python calling issue 

### ISSUE THREAD

**Issue by rraammiinn** [r0x0r/pywebview#1167]
I have problem calling python from js .
is it because of heavy function or because I passed more than one argument to it ?

**Comment by rraammiinn** [comment]
I encountered rejected promise error when calling python from js .

**Comment by r0x0r** [comment]
Please post a minimal working example along with platform details.

**Comment by rraammiinn** [comment]
my code is pretty ugly and unsuitable for explaining the problem but it was a migration from eel to pywebview .

**Comment by rraammiinn** [comment]
https://github.com/rraammiinn/pinit

it's the eel version .
its ui is located in "nui/pinit" and python code is in "pinit" directory .

I refactored it by replacing "eel." with "pywebview.api." and ")()" with ")" .
