### ISSUE TITLE
Suggestion to support access to the AdditionalObjects property of WebMessage.

### ISSUE THREAD

**Issue by gojuukaze** [r0x0r/pywebview#1171]
I would like to get the file path by dragging and dropping files. 

After searching, I discovered that in **WebView2**, file information can be attached and passed to the handlers by calling `postMessageWithAdditionalObjects`.   ( https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md#examples )
   
In the code, I found the `on_script_notify` function and printed all the methods of `args`, but did not find a method to get `AdditionalObjects` . I hope to support obtaining `AdditionalObjects`.

**Comment by r0x0r** [comment]
I think getting file path would be a worthy addition, but what would API be like?

**Comment by gojuukaze** [comment]
> I think getting file path would be a worthy addition, but what would API be like?

How about implementing it through subscribing to on_script_notify, just like subscribing to events?

**Comment by chdominguez** [comment]
Any news on this?

**Comment by r0x0r** [comment]
Not really. A cross platform solution on how to this could be implemented needs to be figured out first.

**Comment by r0x0r** [comment]
Just an update, full file path for drag and drop is now implemented. Check this thread for details https://github.com/r0x0r/pywebview/issues/1192
