### ISSUE TITLE
packaging pywebview projects

### ISSUE THREAD

**Issue by superpythonguy** [r0x0r/pywebview#1172]
### Specification
- version V4.2.1:
- Win 10:
- edge webview2:

### Description

 how to package a webview project to distribute to clients

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
I have used pyinstaller for Windows and py2app for macOS.

**Comment by superpythonguy** [comment]
hello thank you for your speedy reply
unfortunatly i already tried pyinstaller and it didnt work
however i have found a solution
i am just going to package a python binary with the end user folder
