### ISSUE TITLE
can't resize a frameless window

### ISSUE THREAD

**Issue by ibrahemesam** [r0x0r/pywebview#1173]
```python
import webview
webview.create_window('Hello world', 'https://fast.com', frameless=True)
webview.start()
```
> OS: Linux - Manjaro KDE
> Python: v3.10.4
> display server: X11
> WM: openbox

**Comment by r0x0r** [comment]
This is how frameless windows are. Resize border is part of the frame.

**Comment by ibrahemesam** [comment]
I know. but, for some reason, it works in Electron

**Comment by ibrahemesam** [comment]
ok, here is [my solution](https://gist.github.com/ibrahemesam/715fb80876226eba1977dbc98217bd96)
> it is not the best, but it works !

**Comment by ibrahemesam** [comment]
> Ok, here is [my solution](https://gist.github.com/ibrahemesam/715fb80876226eba1977dbc98217bd96)
> 
> > it may not be the best, but it works !

what is your opinion ?
