### ISSUE TITLE
logo for the project?

### ISSUE THREAD

**Issue by denfromufa** [r0x0r/pywebview#118]
could be something related to pythons and webs.

**Comment by shivaprsdv** [comment]
Upvote. :+1:

**Comment by r0x0r** [comment]
Good idea. I will think of something. Suggestions are as always welcome.

**Comment by r0x0r** [comment]
Fiver delivered this logo. What do you guys think?
![pywebview 3](https://user-images.githubusercontent.com/1549657/30038338-0051d8d4-91cc-11e7-8041-deae9bcb9092.jpg)

**Comment by shivaprsdv** [comment]
Nice, can we add some web-strands across the hexagon? Will give
it a non-generic, spider-web look, as @denfromufa suggested..

**Comment by r0x0r** [comment]
The Fiver deal is over, but if someone would like to give it a go, that would be nice. Otherwise let's use this one.

**Comment by shivaprsdv** [comment]
I don't know, something like this:
![pywebview 002](https://user-images.githubusercontent.com/18247990/30162089-f7f4e236-93f0-11e7-94a1-2727dba03e1b.png)

Or, with a bit of color inversion:

![pywebview 001](https://user-images.githubusercontent.com/18247990/30162909-6cf2f3d6-93f4-11e7-83c4-2cdc5f2e97ad.png)

It's kind of rough work; I don't do much design, haven't
got any vector editing software either.

**Comment by shivaprsdv** [comment]
I tinkered with it further, so that we don't leave out the _python_ of pywebview 😉

![pywebview 001](https://user-images.githubusercontent.com/18247990/30229354-2b0ff32c-94ff-11e7-8aba-45fa12e1358e.png) | ![pywebview 002](https://user-images.githubusercontent.com/18247990/30229355-2b10eeda-94ff-11e7-81ea-66f8c74f5528.png)
----- | -----

**Comment by r0x0r** [comment]
The python and web make the logo too noisy. Let's stick with the original version, never mind the genericity

**Comment by shivaprsdv** [comment]
I must have over-did. I confessed I didn't do design. 🙃

May be have one last look at this (I have stripped down
the noisy stuff, still maintaining the flavour):
![pywebview-gen](https://user-images.githubusercontent.com/18247990/30290237-43ef995c-974c-11e7-9422-3e60eb5f55b1.png)

If this too doesn't pass, then bingo on the original one.

**Comment by r0x0r** [comment]
Could you make another version with the shape of the last revision but with the original "p"?

**Comment by shivaprsdv** [comment]
With _python_ | Without _python_
--|--
![pyweb 001](https://user-images.githubusercontent.com/18247990/30600433-0527d8f6-9d7d-11e7-9cb4-38fd1c20d598.png) | ![pyweb 001 copy](https://user-images.githubusercontent.com/18247990/30600435-05f259f0-9d7d-11e7-86c6-6ff80e51831d.png)

Never mind the snake (I couldn't dispense with it 😇). The plain one should be good enough.

**Comment by r0x0r** [comment]
Let's use the middle ground.

![pywebview](https://user-images.githubusercontent.com/1549657/30611724-dcd0da2a-9d8a-11e7-9f6c-7e7c2fa4d227.png)

**Comment by shivaprsdv** [comment]
W/o the tail? Right. I can make a dark-themed version as well.

Any other opinions? OP @denfromufa ?

**Comment by denfromufa** [comment]
all of them look great :)

**Comment by r0x0r** [comment]
Updated README with the last logo.

**Comment by shivaprsdv** [comment]
I have redone the logo in Gravit vector design software and pushed
it to the source tree. See #135.
