### ISSUE TITLE
Weird content scaling

### ISSUE THREAD

**Issue by rojamit** [r0x0r/pywebview#1183]
### Specification
- pywebview: latest
- os: windows 10
- web renderer: winforms / chromium

### Description

Content scaled weird on another win10 PC (white areas at bottom and right corners, small content).
On my win10 machine all looks good. I tried to lower the window size but content got "compressed" inside window
On another machine content is smaller than window: ![report](https://github.com/r0x0r/pywebview/assets/86718351/873ad67f-6f86-4bb3-97e1-1605ae27e842)

Window size (in code) is same on both machines of course
### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by rojamit** [comment]
hero of the occasion is windows scaling value, ctypes.windll.shcore.GetScaleFactorForDevice(0)
i'm using pyinstaller --onefile --windowed & css with position: absolute on all elements (html layout from constructor) so layout doesnt scale

at this moment ended up with ctypes.windll.user32.SetProcessDpiAwarenessContext(-2) and resizing window according to scaling value

**Comment by r0x0r** [comment]
This is an old issue and there are already a couple of DPI related issues. To be honest I am not sure how it should solved. Does setting SetProcessDpiAwarenessContext have any effect on how content is displayed?
