### ISSUE TITLE
Allow selection of the monitor to use with each webview window

### ISSUE THREAD

**Issue by louisnw01** [r0x0r/pywebview#1186]
### Specification
- pywebview version: 4.2.2
- operating system: macOS
- web renderer: n/a

### Description

I noticed that the `webview.screens` method will return the dimensions of all available monitors; yet there is no way to use this information to distinguish between the monitors and use that information to position a webview on a different monitor.

I think a `monitor` parameter added to `create_window` would be a great addition to the library, as multi monitor setups could be programatically declared rather than having to resize and drag the windows to the correct place upon each rerun. It could be used as follows:

```python
webview.create_window('Main Monitor', html=html, on_top=on_top, width=800, height=600, monitor=0)
webview.create_window('Second Monitor', html=other_html, width=800, height=600, monitor=1)
```

### Practicalities

- YES/NO I am willing to work on this issue myself. 
no

- YES/NO I am prepared to support this issue financially.
no

**Comment by r0x0r** [comment]
This would be a nice addition. API could be `create_window(screen=screen_instance)`
Feel free to contribute.

**Comment by louisnw01** [comment]
I'd be happy to give it a go; any guidance?

**Comment by louisnw01** [comment]
> This would be a nice addition. API could be `create_window(screen=screen_instance)`
> Feel free to contribute.

Just as an update; I have integrated a basic version of this feature using Cocoa ([view fork here](https://github.com/r0x0r/pywebview/compare/master...louisnw01:pywebview:main)), but wanted to check if any obvious issues stand out to you before I add support for Qt/Gtk.

**Comment by louisnw01** [comment]
🔥
