### ISSUE TITLE
Issue with window focus on keystrokes in macOS

### ISSUE THREAD

**Issue by jlixfeld** [r0x0r/pywebview#1187]
### Specification
- pywebview version: 4.2.2 / Python 3.11.4
- operating system: macOS 13.4.1 (c) / Intel
- web renderer:

### Description

The window generated by this MRE won't retain focus on keystrokes.

```python
import webview
import threading

class MyApi:
    def log_value(self, params):
        print(params)

def run_app():
    api = MyApi()
    window = webview.create_window('Hello world', html='<body><input type="text" id="keyinput"></body>', js_api=api)

    def on_load():
        window.evaluate_js('''
        document.getElementById("keyinput").oninput = function(){
            pywebview.api.log_value(this.value);
        };
        ''')

    threading.Timer(1, on_load).start()

    webview.start(debug=True)

if __name__ == '__main__':
    run_app()
```

Included is a video that demonstrates the behaviour. Even though the window is clicked on, and the input box is clicked on, it doesn't have sole focus so keystrokes are registered on whatever window also has focus.  Here it's the VS Code window that ran the code, but if I had a terminal window open as well and clicked on that window after I ran the code, and then clicked on the webview window input box, the terminal window would register the keystrokes since it's still in focus.

I have run this code from a VS Code terminal, macOS's built-in Terminal.app and iTerm.app, all exhibiting the same symptoms.

A few other issues that I've found here mentioning macOS also mentioned `pyobjc-framework-Security`.  I tried installing that and it had no effect.

https://github.com/r0x0r/pywebview/assets/17339017/b576089f-86c7-457e-8602-4cb26108cb51

### Practicalities

- [NO] I am willing to work on this issue myself.

- [NO] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I cannot reproduce this.  Keystrokes are visible both in the input box as well as the terminal window. Tested on the latest master / Ventura 13.0.1 
<img width="957" alt="image" src="https://github.com/r0x0r/pywebview/assets/1549657/6278f773-0d24-4ed5-8f49-1adadc510c91">

**Comment by PaulShiLi** [comment]
Could reproduce this issue on mac where typing is an issue on MacOS Sonoma

https://github.com/r0x0r/pywebview/assets/74270733/fb1361b5-47c3-4d4a-9ba7-7483d3487a53

**Comment by PaulShiLi** [comment]
> I cannot reproduce this. Keystrokes are visible both in the input box as well as the terminal window. Tested on the latest master / Ventura 13.0.1 <img alt="image" width="957" src="https://user-images.githubusercontent.com/1549657/258040430-6278f773-0d24-4ed5-8f49-1adadc510c91.png">

It probably works on Ventura but is bugged in Sonoma!

**Comment by einsqing** [comment]
Same issue

**Comment by alitrack** [comment]
It functions properly when using the Python installation from Brew, as opposed to the versions from macOS or Miniconda (Anaconda).

**Comment by r0x0r** [comment]
@jd-solanki The consensus is this issue is caused by using certain Python executables as a base for your virtual environment. See alitrack's comment above.

**Comment by jlixfeld** [comment]
> @r0x0r @jlixfeld this issue still exist. I'm using python 3.12 via pyenv.

Here's how I resolved it: https://github.com/louisnw01/lightweight-charts-python/issues/55#issuecomment-1712826275

**Comment by jd-solanki** [comment]
@jlixfeld So you no longer use pyenv 🥹

Isn't it hard to maintain multiple py versions without pyenv?

**Comment by jlixfeld** [comment]
I suppose so, if you needed to do that.  I didn't, so removing pyenv wasn't a big deal for me.

That said, there does seem to be a 3rd party fix.  See the first link in the comment I linked above.  I haven't tried it though.

**Comment by r0x0r** [comment]
@jlixfeld, Thanks for linking possible fix. I have implemented it in this branch https://github.com/r0x0r/pywebview/pull/new/macos-focus-fix

@jd-solanki will you test if it solves the issue for you?

**Comment by jd-solanki** [comment]
Thanks @r0x0r looking into this. I added this line in my env's site-packages and it's working as expected.

Can you please make a minor release if possible.

https://github.com/r0x0r/pywebview/assets/47495003/4836b28b-9b92-4b89-9601-e8fa5e1b3191

**Comment by r0x0r** [comment]
Yeah, I could do that. Hold on.

**Comment by r0x0r** [comment]
4.4 is out now
