### ISSUE TITLE
Animation Lag on Startup

### ISSUE THREAD

**Issue by jcomish** [r0x0r/pywebview#119]
I am testing with the flask_app example included in this project and I am seeing one small problem.  When I start the project and click on any of the elements, there is about a 3 second delay before the screen responds.  Everything starts working normally after the animation occurs.

I developing on Windows 7 with the following versions:
Python 3.5.2
pywebview 1.7
pythonnet 2.3.0
Flask 0.12.2
Jinja2 2.8.1

**Comment by r0x0r** [comment]
The problem occurs only on Windows and has to with controlling the Visible property of the WebBrowser control on startup. Tweaking the property shows the control immediately, but it is not responsive until it is fully loaded. In the default state the WebBrowser is shown only until it is fully loaded.  I have no idea, why this delay exists and whether it can be avoided. However, I've implemented a hackish workaround that disables tweaking visibility, if background color is not set. You get the same delay but on the white screen.

**Comment by r0x0r** [comment]
Closing this.
