### ISSUE TITLE
DND from / to file explorer

### ISSUE THREAD

**Issue by thewh1teagle** [r0x0r/pywebview#1192]
I would like to have the abbility to drag and drop file from file explorer into `pywebview` window
or copy files / element from `pywebview` window out into file explorer

Just like `vscode` has, where you can drag file from explorer and it will add it to the project directory
or you can darg file from the file list in `vscode` out into `explorer`

ig it should be cross platform? 
do you have plans for that? inspirations from other projects? (`tauri`/`wails`/`electron`)

**Comment by r0x0r** [comment]
Dnd would be nice. Any suggestions on what API should look like?

**Comment by TransparentLC** [comment]
Just use the standard HTML's `ondrop` event.

```js
document.ondragenter = document.ondragover = e => {
    e.stopPropagation();
    e.preventDefault();
};
document.ondrop = e => {
    e.stopPropagation();
    e.preventDefault();
    console.log(e.dataTransfer.files); // File[]
};
// [
//     {lastModified: 1592394869216, name: "example.png", size: 2183677, type: "image/png"},
//     ...
// ]
```

However, we usually need to get the full path of the dragged file when using DnD in desktop apps, which is not available in browsers for security reasons. Electron adds a `path` property to the `File` object to represent the file's path. I'm not sure if it is possible to implement it with pywebview's web engines.

Electron's drag-out example: https://www.electronjs.org/docs/latest/tutorial/native-file-drag-drop

**Comment by r0x0r** [comment]
I am currently working on DOM support, which allows handling DOM events in Python among other things. So you can do things like `window.dom.document.events.drop += handle_drop`. You can check the current implementation in the `dom` branch.
This, however, still leaves the problem of getting a full path of dropped files. As @TransparentLC said it is not possible to obtain a full path on the JS side due security reasons. However, I think it might be possible to handle drag and drop events separately in Python, get a full paths and append the path information to the DOM event when passing it to Python. I have not investigated it and this is very theoretical, but it might work at least for some renderers. Webview2 does not have DnD support at this point, Cocoa has one, the rest I am not sure.
If somebody wants to give this a go, help would be much appreciated.

**Comment by r0x0r** [comment]
This is now implemented for GTK, QT and Cocoa. Not sure if Windows is feasible, but I will take a closer look at it.
The new implementation is in the `dnd` branch (will be merged to the `dom` branch later). You can take a look at the dnd example in `examples/drag_drop.py`.

In short _pywebview_  adds `event['domTransfer']['files'][idx]['pywebviewFullPath']` property to the DOM drop event on Python side. To get a full path of the dropped file you subscribe to the drop event in Python like this `window.dom.document.events.drop += on_drop`

**Comment by r0x0r** [comment]
Windows implementation is done as well. This feature is now completed and will be released in 5.0.

**Comment by pythons** [comment]
> This is now implemented for GTK, QT and Cocoa. Not sure if Windows is feasible, but I will take a closer look at it. The new implementation is in the `dnd` branch (will be merged to the `dom` branch later). You can take a look at the dnd example in `examples/drag_drop.py`.
> 
> In short _pywebview_ adds `event['domTransfer']['files'][idx]['pywebviewFullPath']` property to the DOM drop event on Python side. To get a full path of the dropped file you subscribe to the drop event in Python like this `window.dom.document.events.drop += on_drop`
The implementation of “pywebviewFullPath” is effective for files, but not work for folders.

**Comment by pythons** [comment]
> This is now implemented for GTK, QT and Cocoa. Not sure if Windows is feasible, but I will take a closer look at it. The new implementation is in the `dnd` branch (will be merged to the `dom` branch later). You can take a look at the dnd example in `examples/drag_drop.py`.
> 
> In short _pywebview_ adds `event['domTransfer']['files'][idx]['pywebviewFullPath']` property to the DOM drop event on Python side. To get a full path of the dropped file you subscribe to the drop event in Python like this `window.dom.document.events.drop += on_drop`


The implementation of “pywebviewFullPath” is effective for files, but not work for folders.
