### ISSUE TITLE
if use  webview.screens before webview.create_window  private_mode=False will fail

### ISSUE THREAD

**Issue by cddldg** [r0x0r/pywebview#1193]
### Specification
- pywebview version:4.2.2
- operating system:windows 10
- web renderer:

### Description

![image](https://github.com/r0x0r/pywebview/assets/10046182/f2cae501-d0e4-436b-b0fd-3670de364f03)
![image](https://github.com/r0x0r/pywebview/assets/10046182/2e80dd4e-6c69-4c85-9fb1-ec5c5cae52e7)

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Could you post a working example instead of the screenshot?

**Comment by cddldg** [comment]
> Could you post a working example instead of the screenshot?

`import webview


def initScreen(window):
    # screens = webview.screens
    # screens = screens[0]
    # width = screens.width
    # height = screens.height
    # initWidth = int(width * 2 / 3)
    # initHeight = int(height * 4 / 5)
    # window.resize(initWidth, initHeight)
    print(window.width,window.height)

if __name__ == '__main__':
 
    
    template='http://localhost:8080/apihelper/'

    from api.api import API
    api=API()

    screens = webview.screens
    screens = screens[0]
    width = screens.width
    height = screens.height
    initWidth = int(width * 2 / 3)
    initHeight = int(height * 4 / 5)

    window = webview.create_window('APIHelper', template,js_api=api,width=initWidth,height=initHeight)
    webview.start(initScreen, window, private_mode=False,debug=True)`

if i use initWidth、initHeight ， Every time I reboot the software, localStorage is gone.  
I'm using this method window.resize now

**Comment by r0x0r** [comment]
I fixed this bug in master. Please test.

**Comment by cddldg** [comment]
> I fixed this bug in master. Please test.

Thanks！
