### ISSUE TITLE
Having some problems when quitting program

### ISSUE THREAD

**Issue by DragonBeast829** [r0x0r/pywebview#1197]
Hey, so when I use `os._exit()` to close my game when the window is closed (code snippet below) it gives me an error coming from pywebview presumably (error below)

Code:
```python
def close_game():
    print('Quitting')
    os._exit(0)

window.events.closed += close_game
```

Error:
`[0819/143038.916:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0`

Can anyone help me with this? If I use `sys.exit()`, `exit()`, or `quit()`, that only stops the main thread and not any other threads (which, these threads are, to my knowledge, out of my control), so I need to use `os._exit()` which does stop all the threads but I think also causes that error.

**Comment by r0x0r** [comment]
From the Python documentation
```
os._exit(n)
Exit the process with status n, without calling cleanup handlers, flushing stdio buffers, etc.
```

I am not familiar with `os._exit`, but to me it looks like a wrong choice for quitting the program.
Cannot you set your threads as daemon or use atexit handler in your threads?
