### ISSUE TITLE
Disable right-click context menus 

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#12]
Right clicking on the browser container generates a context menu on every platform. They must be disabled in order to hide implementation details and prevent unwanted actions such as page reload. Any input on how this could be achieved on any platform is appreciated.

**Comment by jonathon-love** [comment]
under Qt, you can call

    webview->setContextMenuPolicy(Qt::NoContextMenu)

(under C++, not sure what the equivalent python would be) to disable the right click menu

**Comment by r0x0r** [comment]
Implemented in master
