### ISSUE TITLE
Still problems with destroy (including fix)

### ISSUE THREAD

**Issue by jorants** [r0x0r/pywebview#120]
There are still problems with the destroy function for GTK, adding a time.sleep(5) at the end of the example script shows that the window does not get destroyed utill the end of the script. Instead only the gtk main loop is exited, so the window freezes.

A possible fix:
[destroy_fix.zip](https://github.com/r0x0r/pywebview/files/1152072/destroy_fix.zip)

I am not fluent in GTK, so please check that this does not introduce any new bugs.

**Comment by r0x0r** [comment]
Could you do a pull request?

**Comment by r0x0r** [comment]
Thanks for the PR. Closing.
