### ISSUE TITLE
Windows System `transparent=True`

### ISSUE THREAD

**Issue by NelsonProia** [r0x0r/pywebview#1200]
### Specification
- pywebview version: 4.2.2
- operating system: Windows 10
- web renderer: Chromium

### Description

  I looked at the different issues on the subject but I'm not sure to understand it correctly. Is it possible, on a Windows system, to make the window transparent without losing events handling etc. ? If yes is it possible to achieve it with pywebview only ?

### Practicalities

- NO I am willing to work on this issue myself.

- YES/NO(MAYBE) I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
It's a bug in WebView2.
See  https://github.com/MicrosoftEdge/WebView2Feedback/issues/1004 for details and current progress on this issue.
