### ISSUE TITLE
The latest title content cannot be obtained after window.set_title

### ISSUE THREAD

**Issue by shengchenyang** [r0x0r/pywebview#1202]
### Specification
- pywebview version: 4.2.2
- operating system: Window 10 22H2
- web renderer: default

### Description

In the [example in this document](https://pywebview.flowrl.com/examples/window_title_change.html), the window title can be changed immediately when using the window.set_title method, but getting the title returns the title unchanged. The code example is as follows:

```python
def change_title(window):
     window.set_title("new_title")
     print(
         window.title,
         webview.windows[0].title,
         webview.active_window().title,
     )
```

Possible solution: You need to modify the `Window` class part in `webview/window.py`, specifically:
``` diff
@_shown_call
 def set_title(self, title: str) -> None:
     """
     Set a new title of the window
     """
+    self.title = title
     self.gui.set_title(title, self.uid)
```
Or just modify the example in the docs:
``` diff
def change_title(window):
     window.set_title("new_title")
+    window.title = "new_title"
     print(
         window.title,
         webview.windows[0].title,
         webview.active_window().title,
     )
```
Please correct me if I am wrong.

### Practicalities

- YES/NO I am willing to work on this issue myself.  YES

- YES/NO I am prepared to support this issue financially. NO

**Comment by r0x0r** [comment]
Thanks for pointing this problem out, but a more robust solution would be to return `document.title`. This way it will catch title changes via Javascript. `window.title` can be converted to a get/set property.

**Comment by shengchenyang** [comment]
It is true that fetching via `document.title` is the most reliable, but `window.set_title` will not be associated with setting the value of `document.title`. I am using the `save_file_dialog` scene of `wm.Menu`. When I save a file, I need to judge the value of `window.title`. For example, if the value is `untitle.file`, I need to activate `save_file_dialog`. If When the value is `named*.file` I need to update it to `named.file`. I need to get the `title` method through the current `window`, am I making it complicated? Is there a better way?

**Comment by r0x0r** [comment]
I don't see a problem here. `window.set_title` updates 'document.title', so `window.title` should return `document.title` as well.

**Comment by shengchenyang** [comment]
`window.set_title` did not update the value of `document.title`, is there something wrong with my code？

```python
import time

import webview


def change_title(window):
    """changes title every 3 seconds"""
    for i in range(1, 100):
        time.sleep(3)
        window.set_title("New Title #{}".format(i))
        title = window.evaluate_js("document.title", callback=None)
        print("title:", title)  # The new title cannot be obtained here

        # This will get the new title
        window.evaluate_js(f"document.title = 'New Title #{i}'", callback=None)
        title_second = window.evaluate_js("document.title", callback=None)
        print("title_second:", title_second)


if __name__ == "__main__":
    window = webview.create_window(
        title="Change title example", url="https://pywebview.flowrl.com/hello"
    )
    webview.start(change_title, window)
```

**Comment by r0x0r** [comment]
Apologies, I had a thought error here. `window.title` is not related to `document.title` at all.
Anyhow I fixed the `window.title` logic, now it is a get/set property. The fix is in the master.

**Comment by shengchenyang** [comment]
Now this issue is resolved, thanks.
