### ISSUE TITLE
`maximize` throws an error on MacOS

### ISSUE THREAD

**Issue by louisnw01** [r0x0r/pywebview#1206]
### Specification
- pywebview version: 4.3
- operating system: MacOS
- web renderer: Cocoa

### Description

  When using maximize I get this error:

```
AttributeError: 'BrowserView' object has no attribute 'maximize'
```

I took a look at the codebase and AppKit's docs, and it doesnt seem like there is a straightforward way to maximize the window; perhaps a better way of integrating this feature would be to get the window width and height before creating the app, and then set the size as the size of the used monitor.

Louis

**Comment by r0x0r** [comment]
I forgot about macOS implementation of maximized. 
As there is no maximized window concept in macOS world, the original idea was to got fullscreen. Making window as big as the monitor is a better option though. It is now implemented in 4.3.1
