### ISSUE TITLE
[4.3.x] window is dragging when it shouldn't

### ISSUE THREAD

**Issue by PythonFZ** [r0x0r/pywebview#1207]
### Specification
- pywebview version: 4.3 / 4.3.1
- operating system: windows
- web renderer: default ?

### Description

I'm using three.js to visualize particles and use pywebview to run the visualisation in a dedicated window.
Since release 4.3 the webview window is being dragged together with the three.js scene.
![webview_bug](https://github.com/r0x0r/pywebview/assets/46721498/7e86b9f4-1860-4d56-a291-74eed4bcec31)

I'm using

```python
wv.create_window(
        "ZnDraw",
        url,
        width=1280,
        height=720,
        resizable=True,
        fullscreen=false,
        confirm_close=True,
        background_color="#FFFFFF",
    )
wv.start()
```
This can be reproduced either by using the ZnDraw package `pip install zndraw==0.2.0a15` and running `zndraw` in the terminal.
Alternatively, I found this three.js demo website that demonstrates the same issue via:

```python
import webview as wv
wv.create_window(url="https://dev-sandbox.pixotronics.com/webgi/0.8.2-dev.4/demos/core~viewer.html?m=pixo://gltf/ijeweldemo1.glb", title="three")

wv.start()
```

**Comment by r0x0r** [comment]
`easy_drag` was mistakenly enabled by default. This is now fixed in 4.3.2.
