### ISSUE TITLE
bug: README.md - Contribute link is not valid

### ISSUE THREAD

**Issue by shubham-pawar** [r0x0r/pywebview#1209]
### Description

  The contribute link in the README file is not valid. Need to update with the correct path. 

### Practicalities

- YES, I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
The opencollective link works here just fine.

**Comment by shubham-pawar** [comment]
https://github.com/r0x0r/pywebview/blob/master/CONTRIBUTING.md

Page not found!

**Comment by r0x0r** [comment]
Your PR did not address a correct link, but you are right there was a dead link in the README. I have fixed it now.
