### ISSUE TITLE
Window crashes when displaying large file

### ISSUE THREAD

**Issue by stefan-alistar** [r0x0r/pywebview#1213]
### Specification
- pywebview version: 4.0.2
- operating system: Windows 11
- web renderer: NA

### Description

  I am running the following code:

fp = self.manager.get_screen("main").file_pointer_html
        fp.seek(0)
        html = fp.read()
        self.report_file = html.decode("utf-8")
        webview.create_window(f"Report name", None, self.report_file)
        webview.start()

fp is just a SpooledTemporaryFile where the html is stored.

I am trying to display a html report in a window. The report is essentially a large table with thousands of rows.
When I click my "View report" button webview works for a small report (of around 6000 rows),
but when a larger html gets uploaded (around 16k rows) the app returns the following error:

[ERROR  ] [WebView2 initialization failed with exception]
 Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.NavigateToString(String htmlContent)
   at Microsoft.Web.WebView2.Core.CoreWebView2.NavigateToString(String htmlContent)
--- End of stack trace from previous location where exception was thrown ---
![image](https://github.com/r0x0r/pywebview/assets/110895919/85adc49f-ec48-4572-ae46-e994b516f514)

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Looks like a bug in Webview2. See for example
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1552

Are you using the latest Webview2 runtime version? Does it work if instead of loading html, you save it to a html file and serve with the built-in http server?
