### ISSUE TITLE
Xvfb and start without heavy X

### ISSUE THREAD

**Issue by senzacionale** [r0x0r/pywebview#1216]
I am using pywebview[qt] with flask and HTML for GUI.

I want to start it like 

pkill Xvfb
Xvfb :1 -screen 0 1024x768x16 &
export DISPLAY=:1
python3 src/backend/main.py

and I see no errors and also no GUI. Is it possible to run Xvfb to see GUI?

[pywebview] Using Qt 5.11.3
Bottle v0.12.25 server starting up (using ThreadedAdapter())...
Listening on http://127.0.0.1:38223/
Hit Ctrl-C to quit.

I don't want heavy X, just GUI to be started. Any suggestions?

I install
sudo apt install python3-pyqt5 python3-pyqt5.qtwebkit python-pyqt5 python-pyqt5.qtwebkit libqt5webkit5-dev Xvfb
pip install qtpy

**Comment by r0x0r** [comment]
To be honest I do not know. I have no experience with xvfb.
If it is possible to run QT with xvfb, then it should be possible to run pywebview as well.
