### ISSUE TITLE
file:///Not allowed to load local resource?

### ISSUE THREAD

**Issue by juntaosun** [r0x0r/pywebview#1219]
### Specification
- pywebview version:
- operating system:
- web renderer:

### Description

`
<audio src="file:///C:/Users/myname/Desktop/1.mp3" autoplay="true"></audio>
`
I specify audio to a path on the local hard disk. 
Running it in python (pywebview) prompts: Not allowed to load local resource. 
However, it is normal in electron. 
Whether pywebview can support loading hard disk file:///local resources like electron.
 Instead of using http.

我将audio指定本地硬盘上的一个路径。
在 python (pywebview)  中运行它提示：Not allowed to load local resource。
然而electron中却正常。
pywebview是否能够像electron那样支持加载硬盘file:///本地资源。
而不使用http。

### Practicalities

- YES/NO I am willing to work on this issue myself.
- NO

- YES/NO I am prepared to support this issue financially.
- NO

**Comment by juntaosun** [comment]
solved

**Comment by r0x0r** [comment]
file:// urls may be blocked by your renderer. As far as I remember latest version of Chromium block file:// urls for security reasons.
The solution is to use relative paths, so that built-in http server is used instead.
