### ISSUE TITLE
Pywebview with dev tools

### ISSUE THREAD

**Issue by foreseaz** [r0x0r/pywebview#122]
I am wondering that is there a way to add dev tools for pywebview just like in electron?

**Comment by shivaprsdv** [comment]
On what platform you are? If you are on Mac, I can tell you a quick
hack: in `cocoa.py`, comment out the first method of the class
`BrowserDelegate`:
```
class BrowserDelegate(AppKit.NSObject):
#    def webView_contextMenuItemsForElement_defaultMenuItems_(self, webview, element, defaultMenuItems):
#        return nil
```
This will enable the right-click context menu, from which you can
choose `Inspect Element` as you'd do from a browser (you might
have to [_enable_](https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html#//apple_ref/doc/uid/TP40007874-CH2-SW7) it first). I think something similar works on Linux as well.

I too have felt that adding a 'Debug' menu to enable the dev tools
on pywebview apps would be helpful on all platforms. We could add
a config option to turn this menu off in release builds. What do you
say @r0x0r ?

**Comment by r0x0r** [comment]
I have tested my code in a web browser with a local web server serving content, but of course this approach is limited in functionality. We could add a `debug=False` to the create_window function signature. Windows will probably be tricky as always, but at least Linux and OSX should be covered with little effort

**Comment by r0x0r** [comment]
@shivaprsdv what would be the bundle identifier for a running Python process?

**Comment by r0x0r** [comment]
Answering to my own question, it is org.python.python

**Comment by r0x0r** [comment]
debug-feature branch is up and the OSX implementation is done.

**Comment by shivaprsdv** [comment]
Nice work. The whole time I'd been searching for a way to
programmatically show the webview on Cocoa, which turned
out to be tricky. This is fine, I reckon we could employ similar
technique on Linux. Now does Trident feature a web-inspector?

**Comment by r0x0r** [comment]
It is not possible on Trident. I might try one of the solutions described here, but getting devtools in a pywebview window akin to WebKit is out of the equation.
https://stackoverflow.com/questions/1917314/is-there-a-way-to-enable-the-ie8-developer-tools-from-inside-webbrowser-control#5291367

**Comment by shivaprsdv** [comment]
Web inspector support can be added on Linux fairly easily if we add multi-window
support (#43). Tried with positive results. 👍

**Comment by r0x0r** [comment]
I have merged the OSX implementation to help with debugging of JSBridge.

**Comment by r0x0r** [comment]
The situation with QT is quite messy. Before QT 5.5 it provides a built-in web inspector and after that it relies on Chrome remote debugging. There is no way to consolidate all the platforms in uniform way. I think the best approach would be to make best use of each platform and print instructions to the console on how debugging can be activated on each platform.

**Comment by r0x0r** [comment]
One more thing, Visual Studio has its own version of remote debugging, hopefully with a bit of luck it could be made to work with pywebview.

**Comment by shivaprsdv** [comment]
As I had said, I have implemented web inspector on GTK with the now merged
multi-window functionality. Pushed to the restored [`debug-feature`](https://github.com/r0x0r/pywebview/tree/debug-feature) branch.

**Comment by shivaprsdv** [comment]
Slight improvement for Windows: providing the `debug` flag should now enable
the right-click menu on WinForms.

**Comment by shivaprsdv** [comment]
Managed to implement native debug support for Qt 5.5+. Like GTK it uses the
multi-window feature to open a Chrome Remote debugger inside a Pywebview
window itself; see 8f5041173895c55a886a08df44d7dab73c5ebd38.

**Comment by r0x0r** [comment]
I have no idea how relevant older QT versions are. As this is not an essential feature, it can be left out for now, unless you wish to give it a go. I managed to get a working QT 5.2 environment up and running in Ubuntu Trusty, using QT packages specified in `.travis.yml`. Ironically I could not get a > 5.5 environment working with Xenial, now another attempt with Aardvark.

Visual Studio is not able to attach to a running Python process, so I guess this is the end of the story. One thing that could be done on Windows is to reroute console.log's to Python console, but it can be done at a later time.

**Comment by shivaprsdv** [comment]
> I have no idea how relevant older QT versions are.

Neither do I. I just thought it would be a bit incomplete to leave out only <5.5
on Qt. It would have been a no-brainer if it was just Qt4; to break support in a
middle point-release felt odd. But now I think of it, that's exactly what the Qt
dev's did, so if you think it's not a big deal, I quite agree to leave it out. Better
be clear about it in the doc by the way.

About Windows, the first of those articles says that it works with any exe, but
it won't work with Python? Have you tried freezing an app and attaching to it?

**Comment by r0x0r** [comment]
Freezing the app would defeat the purpose. I  suspect it would not make a
difference too, as it is still the Python interpreter that is executed and
not a .NET app

**Comment by shivaprsdv** [comment]
Let's get done with this then.
