### ISSUE TITLE
app crash issue: relative to `on_top` param

### ISSUE THREAD

**Issue by Zirpon** [r0x0r/pywebview#1222]
### Specification
- pywebview version:
- operating system:
- web renderer:

### Description

```python
    wm.MenuAction('top', on_top),
    ...
    def on_top():
        active_window = webview.active_window()
        active_window.on_top = not active_window.on_top
```

the above code run normally in debug mode
after freezing app, pressing the `top` menu button, app will be crashed

**Comment by r0x0r** [comment]
Could you post a standalone complete example?
