### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#1227]
The next major release 5.0 will include following features

- Android support https://github.com/r0x0r/pywebview/issues/377
- Support for DOM manipulation / events https://github.com/r0x0r/pywebview/issues/1218
- **BREAKING**: `window.get_elements` returns a list of instances of `Element` objects.
- New more powerful JS data serializer capable of handling many data types and detecting circular references https://github.com/r0x0r/pywebview/issues/1217
- **BREAKING**: `evaluate_js` throws a JavascriptException if executed codes raises an error
- File drag n drop with with full path support  https://github.com/r0x0r/pywebview/issues/1192
- `webview.settings` Additional options that would override default behaviour of _pywebview_ to address popular feature requests. These will include controlling opening `target=_blank` links in an external browser or opening `devtools` automatically in debug mode. 
```
settings = {
    'ALLOW_DOWNLOADS': False,
    'OPEN_EXTERNAL_LINKS_IN_BROWSER': True,
    'OPEN_DEVTOOLS_IN_DEBUG': True,
}
```
- WebView2 control updated to 1.0.2045.28
- Support for file downloads. To enable file downloads, set `webview.settings['ALLOW_DOWNLOADS'] = True`. Disabled by default.

The release progress can be tracked in the [5.0](https://github.com/r0x0r/pywebview/tree/5.0) branch
Target release date is towards the end of this year.

**Comment by r0x0r** [comment]
Added support for file downloads. To enable file downloads, set `webview.settings['ALLOW_DOWNLOADS'] = True`. Disabled by default.

**Comment by paulocoutinhox** [comment]
+1

**Comment by r0x0r** [comment]
You can use 5.0 already by installing the dev version in the `5.0` branch. It is ready feature wise, but documentation is still missing and there are probably bugs as well. Testing would be much appreciated.

**Comment by juanjoselazohoyos** [comment]
Thank you very much, your library solved my life. I will be waiting very patiently for version 5.0

**Comment by r0x0r** [comment]
Version 5.0.1 is on pypi now

**Comment by mominiqbal1234** [comment]
Please make step by step for android installation code and then build 
thanks so much :)

**Comment by MominIqbal-1234** [comment]
Please make step by step for android installation code and then build
thanks so much :)
