### ISSUE TITLE
Edge swipe navigates back on Windows

### ISSUE THREAD

**Issue by forceflow1049** [r0x0r/pywebview#1230]
### Specification
- pywebview version: 4.3.3
- operating system: Windows 11
- web renderer: MS Edge

### Description

When using a touchscreen and swiping from the left/right edge of the app window, an arrow is shown and the page navigates back/forward through the history. This happens whether the window is fullscreen (so window edge is display edge) or not (so window edge can be middle of screen). This happens regardless of the state of the allow edge gestures setting in Windows.

This behavior is the default functionality of the regular Edge browser, so this behavior is clearly being pulled in from there. The behavior is interfering with my app's behavior, which uses user swipes on the screen.

**Comment by r0x0r** [comment]
Fixed in master

**Comment by forceflow1049** [comment]
Thank you! For anyone who needs a stopgap solution, you can set the `touch-action` CSS property to `none` or `manipulate`
