### ISSUE TITLE
Selected file is empty if filename contains a space

### ISSUE THREAD

**Issue by falkoschindler** [r0x0r/pywebview#1231]
### Specification
- pywebview version: 4.0.2
- operating system: Mac OS 13.4.1
- web renderer: WebKit

### Description

We noticed that our [file picker](https://nicegui.io/documentation/upload) yields empty files if we run with pywebview and the file contains a space.
The problem seems to be on the client side before the upload actually happens.
We boiled it down to this minimal example:

```py
import webview

webview.create_window('Test', html='''
    <input type="file" onchange="displayFileSize()" />
    <script>
    function displayFileSize() {
        document.write(document.querySelector("input").files[0].size + " bytes");
    }
    </script>
''')
webview.start()
```

When picking a non-empty file like "test file.txt", the displayed size is 0.
When picking a non-empty file like "test_file.txt", the displayed size is not 0.

**Comment by r0x0r** [comment]
Spaces in filenames were incorrectly encoded with %20s. I have fixed this in master now.
