### ISSUE TITLE
Page not destroyed when window closed

### ISSUE THREAD

**Issue by forceflow1049** [r0x0r/pywebview#1235]
### Specification
- pywebview version: 4.3.3
- operating system: macOS 13.4
- web renderer: Webkit

### Description

When multiple windows are open, closing one doesn't seem to actually destroy the page or stop code execution. Here's a minimal working example:

`page1.html`
```html
<html>
    <body>
        <video src="input.mp4" autoplay loop></video>
    </body>
</html>
```

`input.mp4` should be a video with sound.

`page2.html`
```html
<html>
    <body>
        Page 2
    </body>
</html>
```

Start a web server to serve the pages:
`python3 -m http.server`

Python:
```python
import webview

window1 = webview.create_window('Page 1', url='http://localhost:8000/page1.html')
window2 = webview.create_window('Page 2', url='http://localhost:8000/page2.html')

webview.start()
```

Run the script and close Page 1 (the one with the video).

**Expected behavior**: the page is destroyed and the video stops playing.
**Actual behavior**: the video continues to play (you can still hear the audio).

**Comment by r0x0r** [comment]
This seems to be a bug in WKWebView, as video keeps playing even after explicitly setting webkit reference to None. https://stackoverflow.com/questions/27410413/wkwebview-embed-video-keeps-playing-sound-after-release

A rather ghetto workaround is to load empty html just before closing window. I have pushed it to master.
