### ISSUE TITLE
Delete key not removing characters

### ISSUE THREAD

**Issue by mdigi** [r0x0r/pywebview#124]
I'm using python 3.5.3 with Windows 7 and noticed that the delete key does not work when trying to remove characters from a text box.

Was the delete key's functionality removed because of issue [#102](https://github.com/r0x0r/pywebview/issues/102)? Is there any way to get the delete key to work?

**Comment by r0x0r** [comment]
There was no handler for the Delete key. The fix for WinForms is now pushed to master.

**Comment by r0x0r** [comment]
Other platforms do not have this problem. I am closing this issue.
