### ISSUE TITLE
Trouble for select text

### ISSUE THREAD

**Issue by jtssi** [r0x0r/pywebview#1244]
### Specification
- pywebview version: 4.4 and before
- operating system: Windows 10 & 11
- web renderer: default (webview2)

### Description

Hello, I'm having trouble selecting the text on certain pages. I noticed this on ChatGPT, it's impossible to select the text in the pages, whether it's my messages or the robot's replies.

Thank you for your support.

**Comment by jtssi** [comment]
*edit : my code :
`import webview
import sys
import tkinter as tk
from tkinter import messagebox

def show_error_message(message):
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror("ChatGPT : Start Error", message)
    root.destroy()

if len(sys.argv) < 4:
    show_error_message("Start only with Launch.exe!")
else:
    webview.create_window('ChatGPT','https://chat.openai.com/','','',int(sys.argv[2]),int(sys.argv[3]))
    webview.start(private_mode=False,storage_path=sys.argv[1])
`

**Comment by r0x0r** [comment]
Try `webview.create_window(..., text_select=True)`

**Comment by jtssi** [comment]
ha! it works, I hadn't seen it in the documentation. thanks!
