### ISSUE TITLE
🤔 Building & Packaging vue based app using pyinstaller

### ISSUE THREAD

**Issue by jd-solanki** [r0x0r/pywebview#1245]
Hi 👋🏻 

### Specification
- pywebview version: 4.4
- operating system: Apple M1 - macOS Sonoma v14
- web renderer: IDK what's this but I'm using file to render Vue app

### Description

> _P.S. I'm not using FastAPI now. Ref: #1175_

I have couple of queries regarding building & packaging.

Reproduction repo: https://github.com/jd-solanki/vue-webview. You can read instrcutions in README

- [ ] **How to setup dev & build?** In my repo, I have set `url=entry` which loads the `index.html` of vue app which according to react example in docs but it doesn't work for me. I need to set `url="http://localhost:5173"` but it won't work when app is build.
- [ ] **How to make app truely single file?** When I run the build using pyinstaller I get `./dist/main` but it requires `index.html` to load the UI. Shouldn't it be standalone 🤔 
- [ ] **Add docs for building the app** I'll be happy to introduce the docs if I know the setup (Probably I'll need your help for accurate docs)

### Practicalities

- YES/~~NO~~ I am willing to work on this issue myself.

- ~~YES~~/NO I am prepared to support this issue financially.

> _I'll later try using nuxt instead of vue but let's resolve this first 😉_

**Comment by r0x0r** [comment]
Use `dist/index.html` (or similar depending where your built vue app is) for your entry url. `pywebview` will start a http server automatically for relative urls.
There is `--onefile` option in pyinstaller. You need to instruct pyinstaller to include your `dist` dir too.

**Comment by jd-solanki** [comment]
Hi @r0x0r 

Thanks for your response. If check the reproduction repo and use `entry` parameter, pywebview doesn't render the vue app 🤔

As this issue can be devided into two steps, let's first tackle how we can render the vite based vue app in pywebview that will be compatible with build parameters.

Can you please let me know which system you are on? (Let me switch the repo to `venv`)
Have you tried running the repo?

**Comment by r0x0r** [comment]
I checked your repo and successfully managed to produce an exe using provided spec file on Windows. I get a blank screen on macOS though.

**Comment by jd-solanki** [comment]
Just to let you know I'm really nice at Python but I'm new to building executables so my spec file or other distribution code might need some update.

Regarding the original issue, What should be in `create_window` considering development & build? I guess using `url` will be best choice but how can we configure it for Vue SPA app, Nothing is showing up in development.

Just to make sure we are on the same page, I'm on Ubuntu at home and I get blank screen when I run `python app/main.py` but when I build the app (as shown in readme) and run it (`./dist/main`) vue app show up (but without routing content as stated in another issue).

**I really appreciate your efforts here if you could help as pywebview is the only preferable way for me to build GUI in python. Everything else requires too much effort. To give you hint, If everything works fine, I'm aiming for something like [scriptkit](https://www.scriptkit.com/) or [raycast](https://www.raycast.com/) but based on python and cross platform.**

> _P.S. I don't have a mac ATM (it's in the office, will check tomorrow)._

**Comment by Zirpon** [comment]
> I checked your repo and successfully managed to produce an exe using provided spec file on Windows. I get a blank screen on macOS though.

i freeze my app on macos also get a blank screen  when launch but still can use menu button load other url 
how to fix this blank screen 

please check my repository [https://github.com/Zirpon/majSoulRecordPrint](https://github.com/Zirpon/majSoulRecordPrint) 

```python
# APP.py
webview.create_window(MenuApi.RecordWindowTitle, "https://www.baidu.com", js_api=RecordApi(), text_select=True, zoomable=True, draggable=True)
webview.start(private_mode=False, menu=MenuApi().menu_items, debug=DEBUG)
```

**Comment by Zirpon** [comment]
i search some guys have same issue with me refer [Jetson Nano problem with pywebview, blank screen](https://forums.developer.nvidia.com/t/jetson-nano-problem-with-pywebview-blank-screen/263331)

and his solution is 
```bash
export WEBKIT_DISABLE_COMPOSITING_MODE="1"
```
but not work for me 

i have search webkit github issue found some similar such as :
(https://github.com/WebKit/WebKit/pull/9505#issue-1567571040)[https://github.com/WebKit/WebKit/pull/9505#issue-1567571040]

please check Roman @r0x0r

**Comment by Zirpon** [comment]
never mind i solve it in another way：
```python
    windowtmp = None
    if DEBUG:
        windowtmp = webview.create_window(MenuApi.RecordWindowTitle, "https://cn.bing.com/", js_api=RecordApi(), text_select=True, zoomable=True, draggable=True)
    else:
        windowtmp = webview.create_window(MenuApi.MajSoulWindowTitle, MenuApi.majSoul_url, js_api=RecordApi(), text_select=True, zoomable=True, draggable=True)
    def loadWindowUrl(window):
        # mac webkit 加载第一个页面失败 这是研究出来暂时使用的办法
        window.evaluate_js("alert('click me finished');")
        window.load_url(window.original_url)
    webview.start(loadWindowUrl, windowtmp, private_mode=False, menu=MenuApi().menu_items, debug=DEBUG)
```

the create_window url load failed ( it should be blank screen normally ) 
and i make it load again after use window.evaluate_js 

just refer the code above

**Comment by jd-solanki** [comment]
In my case, when I load via `entry` parameter **while developing**, `index.html` gets loaded but as `pywebview` can't process it like a vite server nothing renders. However, after the build as I get normal HTML and JS files that doesn't require vite server running app renders the app correctly.

**Comment by jd-solanki** [comment]
Closing this as I'm no longer using pywebview
