### ISSUE TITLE
vue router doesn't work in build

### ISSUE THREAD

**Issue by jd-solanki** [r0x0r/pywebview#1246]
### Specification
- pywebview version: 4.4
- operating system: Ubuntu 22.04.3 LTS
- web renderer: GTK

### Description

Reproduction repo: [jd-solanki/vue-webview](https://github.com/jd-solanki/vue-webview)

Just follow the steps in README and run the generated app. You will get some UI which is loaded from `App.vue` entry file but content of route isn't get loaded: 

![image](https://github.com/r0x0r/pywebview/assets/47495003/c8c6a454-fc50-4886-8ad4-6315a0e04cc8)

### Practicalities

- YES/~NO~ I am willing to work on this issue myself.

- ~YES~/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Generally for SPA routing to work, url rewrite is needed on the server side.

There is no url rewrite support in the built-in http server, so the best course for now would be either pass a custom WSGI server via the `url` param (see `examples/multiple_servers.py`) or use an external http server.

Some kinds of support for SPAs is definitely needed for _pywebview_, but I am not sure what API should look like. Suggestions welcomed.

**Comment by r0x0r** [comment]
To expand my answer, a custom WSGI server would look something like this (code is not tested). You need to put all the assets under the `static` directory. 

```
app = bottle.Bottle()

@app.route('/static/<filename:path>')
def serve_static(filename):
    return static_file(filename, root='./static')  # Adjust the root path as needed

@app.route('/<path:path>')
def catch_all(path):
    return static_file('index.html', root='./static') 

webview.create_window('Window', url=app)
```

**Comment by jd-solanki** [comment]
I tried this in [bottle-wsgi](https://github.com/jd-solanki/vue-webview/tree/bottle-wsgi) branch but it throws 404 error.

Let's keep this open if you wish to improve built in server of pywebview or you can close this.

One last comment I have for this issue is, I'm assuming any normal web app will get injected into pywebview and work fine. Am I correct? If no, what are the limitations?

> _P.S. I use vue, nuxt, TS & FastAPI_

**Comment by jd-solanki** [comment]
I recently tried the build again and found that routing works but requires first navigation via link click:
![Screenshot 2023-10-31 at 11 12 41 AM](https://github.com/r0x0r/pywebview/assets/47495003/75fcc740-f625-4651-b0dc-9f23b7060f7b)

Are you aware of why pywebview doesn't load the `home` route initially but loads it on click of link?

**Comment by jd-solanki** [comment]
Closing this as I'm no longer using pywebview
