### ISSUE TITLE
Is it possible to pass variables like list & dicts via js_api instead of just functions?

### ISSUE THREAD

**Issue by jd-solanki** [r0x0r/pywebview#1248]
### Specification
- pywebview version: 4.4
- operating system: Ubuntu
- web renderer: GTK

### Description

Hi 👋🏻 

I recently realized I can't pass list of dict to `js_api`. pywebview only allows executing passed functions 🤷🏻‍♂️ 

```py
import os
import pathlib

import webview


class Api:
    def __init__(self):
        self.version = "1.0.0"
        self.items = [1,2,3]
        self.data = [{"one": 1}]


if __name__ == "__main__":
    window = webview.create_window(
        "pywebview-vue",
        url="http://localhost:5173",
        js_api=Api(),
    )
    webview.start(debug=True)
```

### Practicalities

- YES/~NO~ I am willing to work on this issue myself.

- ~YES~/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
No, it is not possible, I like this syntax and feel free to work on this.
Bidirectional reactivity would be nice too, not sure if it is achievable though.
