### ISSUE TITLE
Scale down content

### ISSUE THREAD

**Issue by nmaas87** [r0x0r/pywebview#125]
Is there any way for pywebview to scale down / zoom out of content so that it fits the current fullscreen webview? This would be especially useful with small screen applications / i.e. tft displays :).

**Comment by r0x0r** [comment]
First of all, would setting zoom via javascript (document.documentElement.style.zoom) do the trick?
Nothing like this is implemented, but it could be done by setting zoom as an additional parameter to create_window.

**Comment by nmaas87** [comment]
Thats a very good idea, I could embed the code within my webpage, however, including it directly into pywebview - especially in terms of an additional parameter would be very welcome, so that one did not need to change every app 👍.
Any interest in including that parameter :)? Best regards :)

**Comment by r0x0r** [comment]
This could be done, but I would like to know the rationale first. Couldn't it be solved with the zoom property in CSS or meta viewport?

**Comment by nmaas87** [comment]
Well, that would require to inject the said parameters into every WebApp / Webpage before using it in pywebview. This is often not possible. Best example would be using pywebview to support an existing App on a Small Touchscreen of an Raspberry Pi or similar device: Things like i.e. an Twitterwall or other foreign apps cannot be changed by i.e. the developer of said device and therefor need some kind of possibilty to inject those parameters directly into the app to scale the app to the correct size of the display / make it useable :). But not only for scaling down, also scaling up i.e. in use with a projector, that would be a very useful feature.

**Comment by r0x0r** [comment]
Fair enough, let's make it a feature.
Scaling could be an additional parameter to the create_window function and
the value type would be float (scale=1.0 by default). The scale factor
would be set per window. Is there a need to change the scale factor after
window is created?

**Comment by nmaas87** [comment]
Thank you 👍 
That sounds very reasonable to me, I think there shouldn't be a need to change the scale factor after the window is created, as the main usecase would be to scale down/up the content for use on a special device which would not be changed after the program launched :)

**Comment by shivaprsdv** [comment]
If this can be done by injecting custom JS, then the `evaluate_js()`
method I wrote in response to #123 can be of use. After all this is a
not-so-common requirement, meanwhile the ability to run any JS is
proving to be increasingly useful. I reckon the newly proposed `scale`
parameter too would require running JS code on the webpage loaded.
If so, have a look at the [method](https://github.com/shivaprsdv/pywebview/commit/8106fc0da5e5ba73363c71003c98734cc204af80) I test-implemented on Cocoa. Then,

`webview.evaluate_js('document.documentElement.style.zoom = <value>')`

immediately after `create_window` would do what the OP asks for.

**Comment by nmaas87** [comment]
@shivaprsdv Thanks for your hint, however, I do not use Cocoa, but QT5 due to an dockerized Debian Environment :)

**Comment by shivaprsdv** [comment]
Of course. What I am suggesting is that this particular problem
can be solved using the more general approach I took in writing
that method, besides its other uses. I am pretty sure it can be
implemented on all platforms. @nmaas87 🙂

**Comment by r0x0r** [comment]
@shivaprsdv Let's introduce the evaluate_js function. Could you create a feature branch with your changes?

**Comment by shivaprsdv** [comment]
The branch is up, with the commit for Cocoa. Meanwhile I've tested this feature with `evaluate_js()`. Here:

Scale down | Scale up
-- | --
![untitled](https://user-images.githubusercontent.com/18247990/30386936-ba3dbf58-98c8-11e7-826f-3825040a745e.png) | ![untitled2](https://user-images.githubusercontent.com/18247990/30386937-bab57570-98c8-11e7-81fc-9ffa88eba7ce.png)

Is this what we want?

**Comment by nmaas87** [comment]
could not test it yet, but it looks good :)

**Comment by shivaprsdv** [comment]
@nmaas87 Hey, the QT5 implementation has been pushed to the
`eval-js` branch. Please checkout setting the zoom using JS. 🙂

**Comment by shivaprsdv** [comment]
#123 is almost done, scaling content can be done using `evaluate_js()`
on all platforms. I have a working sample [here](https://gist.github.com/shivaprsdv/5b69d57b1fd6a507e1fd7c26697f7f57). @nmaas87

**Comment by nmaas87** [comment]
@shivaprsdv I tried to build myself my project with the eval-js branch, 
( https://github.com/nmaas87/docker-raspbian_pywebview/blob/master/pywebview_fixed_test/Dockerfile in contrast to the normal file: https://github.com/nmaas87/docker-raspbian_pywebview/blob/master/pywebview_fixed/Dockerfile )

However, the system does not recognize QT anymore now. Very interesting error.

````
Errors from xkbcomp are not fatal to the X server
ERROR:webview:GTK cannot be loaded
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/webview/__init__.py", line 74, in _initialize_imports
    import webview.gtk as gui
  File "/usr/local/lib/python3.4/dist-packages/webview/gtk.py", line 15, in <module>
    import gi
ImportError: No module named 'gi'
WARNING:webview.qt:PyQt4 is not found
ERROR:webview.qt:PyQt5 is not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/webview/qt.py", line 44, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: No module named 'PyQt5.QtWebKitWidgets'
Traceback (most recent call last):
  File "/app/app.py", line 52, in <module>
INFO:werkzeug: * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
    webview.create_window("Calculator", "http://127.0.0.1:80/")
  File "/usr/local/lib/python3.4/dist-packages/webview/__init__.py", line 186, in create_window
    _initialize_imports()
  File "/usr/local/lib/python3.4/dist-packages/webview/__init__.py", line 83, in _initialize_imports
    import webview.qt as gui
  File "/usr/local/lib/python3.4/dist-packages/webview/qt.py", line 58, in <module>
    raise Exception('This module requires PyQt4 or PyQt5 to work under Linux.')
Exception: This module requires PyQt4 or PyQt5 to work under Linux.
xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
````

**Comment by nmaas87** [comment]
Ok I was missing python3-gi, my bad.
However, eval is not working, no js query is executed at all.
I tried following:

````
# -*- coding: utf-8 -*-

import re
from flask import Flask, jsonify, render_template, request

import webview
import sys
import threading

app = Flask(__name__)


@app.route('/_calculate')
def calculate():
    a = request.args.get('number1', '0')
    operator = request.args.get('operator', '+')
    b = request.args.get('number2', '0')
    m = re.match('-?\d+', a)
    n = re.match('-?\d+', b)
    if m is None or n is None or operator not in '+-*/':
        return jsonify(result='I Catch a BUG!')
    if operator == '/':
        result = eval(a + operator + str(float(b)))
    else:
        result = eval(a + operator + b)
    return jsonify(result=result)


@app.route('/')
def index():
    return render_template('index.html')

def start_server():
    app.run(host='0.0.0.0',port='80');

if __name__ == '__main__':

    t = threading.Thread(target=start_server)
    t.daemon = True
    t.start()

    webview.create_window('Calculator', 'http://127.0.0.1:80/')
    webview.evaluate_js('document.documentElement.style.zoom = 250.0')
    #webview.evaluate_js(alert('test'))
    webview.toggle_fullscreen()

    sys.exit()
````

and it does not zoom at all.
Also the alert does also not work, if I enable it.

**Comment by shivaprsdv** [comment]
You can't call API methods on the main thread after `create_window`.
> Calling this function will block application execution, so you have to
execute your program logic in a separate thread.

You have to call them on a secondary thread, like you're doing above
with `start_server`. See the gist I shared. :)

**Comment by nmaas87** [comment]
@shivaprsdv Thanks a lot, I missed that.
Yes, it is working now, I can confirm that 👍

**Comment by shivaprsdv** [comment]
`evaluate_js()` is now in master. Can I close this?

**Comment by nmaas87** [comment]
Yes, perfect and thank you very much :)!
