### ISSUE TITLE
Using `import { X } from './'

### ISSUE THREAD

**Issue by louisnw01** [r0x0r/pywebview#1250]
### Description

Hey @r0x0r,

Im curious to know if there is a way to use module scripts placed in the HTML within other scripts; preferably within the `evaluate_js` method:

```python
import webview


html = '''
<script type="module">

class Test {
    constructor() {
        console.log('hello!')
    }
}
export {
    Test as T
}

</script>

<body>

<script type="module">
    // this throws "Module name, './' does not resolve to a valid URL."
    import { T } from './'
    new Test();
</script>

<h1>Hello</h1>
</body>
'''

window = webview.create_window('', html=html)

def start():
    window.evaluate_js('''
    // this throws "Unexpected token '{'. import call expects one or two arguments."
    // likely as evaluated JS is not treated as a module.
    
    import { T } from './';
    new Test()
''')

webview.start(debug=True, func=start)

```

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
There are several issues here.
When you load html like this, there is no file system, nor files paths. You must use a http server for script modules. This configuration works, for example

### test.js
``` javascript
class Test {
    constructor() {
        console.log('hello!')
    }
}
export {
    Test as T
}
```

### test.html
``` html
<html>
<body>

<script type="module">
    import { T } from './test.js'
    new T();
</script>

<h1>Hello</h1>
</body>
</html>
```

```
window = webview.create_window('', "test.html")
webview.start()
```
For the same reason, loading modules via `evaluate_js` does not work either. It might work if you inject a `<script type="module">` tag with `evaluate_js`. I have not tested it though

Is 'import { T } from './'' valid syntax by the way? What does './' refer to?
