### ISSUE TITLE
Custom Browser Flags

### ISSUE THREAD

**Issue by 17hoehbr** [r0x0r/pywebview#1252]
### Specification
- pywebview version: 4.4.1
- operating system: Fedora Linux
- web renderer: GTK

### Description

I am trying to implement pywebview as the front end for a karaoke project I'm working on using Flask, here is the source code for reference: https://github.com/17hoehbr/OpenMic-Karaoke

The problem I'm running into is that currently my project requires video autoplay to be enabled in the browser settings because the frontend is intended to be running on a TV without a mouse or keyboard. The song queue is managed by a mobile interface and uses websockets to communicate with the TV. I am also open to suggestions on another way to initiate the playback if possible. Below are the relevant pieces of code that demonstrate the problem:

app.py:
```
@app.route("/tv")
def tv():
    # get local ip address
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("10.0.0.0", 0))

    local_ip = s.getsockname()[0]
    qr = qrcode.make(local_ip)
    qr.save("./static/qrcode.png")

    return render_template("tv_index.html", local_ip=local_ip)

@app.route('/play_video')
def play_video():
    next_song = song_queue[0]
    return render_template("video_player.html", next_song=next_song)

@app.route('/songs/<path:filename>')
def serve_video(filename):
    return send_from_directory(f'{song_dir}', filename)
```

tv_index.html:
```
    socket.on('play_video', function() {
        window.location.replace("{{ url_for('play_video' )}}");
    });
```

video_player.html:
```
  <video id="video" autoplay>
      <source src="/songs/{{ next_song }}.mp4" type="video/mp4">
  </video>
```

### Practicalities

- **YES**/NO I am willing to work on this issue myself.

- YES/**NO** I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
A generic solution for browser settings is tricky, as different platforms expose settings in different formats despite the fact that they all are WebKit. 5.0 will introduce `webview.settings` that will have flags for controlling app and browser behaviour. What webkit setting controls autoplay?

**Comment by 17hoehbr** [comment]
Based on the webkit [documentation](https://lazka.github.io/pgi-docs/#WebKit-6.0/classes/Settings.html#WebKit.Settings.set_media_playback_requires_user_gesture) I found I believe the setting is "webkit_settings.media_playback_requires_user_gesture"

However when I tried adding that to the /webview/platforms/gtk.py file it did not seem to change anything

gtk.py
```
...
        webkit_settings = self.webview.get_settings().props
        user_agent = settings.get('user_agent') or _settings['user_agent']
        if user_agent:
            webkit_settings.user_agent = user_agent

        webkit_settings.enable_media_stream = True
        webkit_settings.enable_mediasource = True
        webkit_settings.enable_webaudio = True
        webkit_settings.enable_webgl = True
        webkit_settings.javascript_can_access_clipboard = True
        webkit_settings.allow_file_access_from_file_urls = True
        webkit_settings.media_playback_requires_user_gesture = False
...
```
And if I try to manually play the video with javascript I get the following error:
```
> video.play()
< Promise {status: "rejected", result: NotAllowedError: The request is not allowed by the user agent or the platform in the current context…}
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	play
	Console Evaluation (Console Evaluation 1:3)
```

**Comment by 17hoehbr** [comment]
For anyone else facing a similar problem I worked around it using pyautogui in the meantime: https://github.com/17hoehbr/OpenMic-Karaoke/commit/1b29219bdeaf301d307fd52bcd82a3e4c4349c3c

Basically I just added a listener so that the video will play when the space key is pressed, then I used pyautogui to press the space bar once the page is loaded.

**Comment by 17hoehbr** [comment]
Update: the window.evaluatejs() function resolved the issue in a much cleaner way.

Ex:
```
def autoplay_workaround():
  window.evaluate_js(
    r"""
      const video = document.getElementById('video');
      video.play();
    """
  )
```

Apparently when the javascript play function is passed through the evaluate_js function instead of in the html template it bypasses the autoplay restriction.

Here is the full commit where I changed it in my project: https://github.com/17hoehbr/OpenMic-Karaoke/commit/e16e5b0f29ab3c43cea52d3a835534ceb9de6931
