### ISSUE TITLE
Menu doesn't work

### ISSUE THREAD

**Issue by useewa** [r0x0r/pywebview#1254]
### Specification
- pywebview version: 4.4.1
- operating system: win11
- web renderer: None(idk)

### Description

  I will be writing a thesis on the topic of my browser, when I wanted to understand the insides of the library, how everything works. I noticed that if I move it somewhere or rename it, then everything except Menu stops working. I took a simple menu example from the folder with examples.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry I do not follow. What stops working?

**Comment by useewa** [comment]
@r0x0r 

Here is the library as it is
![image](https://github.com/r0x0r/pywebview/assets/80559012/037146a8-9d14-4814-81b8-b1d842dafa71)

And this is the same pywebview library but just copied and renamed (Why is there no menu here?)
![image](https://github.com/r0x0r/pywebview/assets/80559012/0ed6a831-6627-4e12-a4ec-e013e695120b)
