### ISSUE TITLE
can i run another desktop application in this webview  ?

### ISSUE THREAD

**Issue by MohamedSafaa** [r0x0r/pywebview#126]

**Comment by shivaprsdv** [comment]
Probably no. 👎 

I'm afraid your question is not clear. Pywebview is a platform to run
web apps, i.e. apps written using web technologies (HTML, CSS and
JavaScript). In other words it is only capable of displaying web pages
(like a browser, but in its own window). It's cross-platform, meaning
you need to write your web app only once, and it will run on Windows,
Linux or Mac.

A desktop application, on the other hand, is bound to be platform-
specific (different code for different platforms). If you're planning to
build a cross-platform desktop app, pywebview can be of help. If you
are asking whether pywebview can be used as a "wrapper" for an
existing desktop app of some kind, then the answer is no (why would
you want to do such a thing, anyway?).

If this doesn't answer your question, please describe a little about
what you are trying to do. Hope that helps.

**Comment by r0x0r** [comment]
Shiva is correct. You might want to rethink you application structure and what you would like to achieve.
