### ISSUE TITLE
Error: Failed to load module script: Expected a JavaScript module script (MIME Type)

### ISSUE THREAD

**Issue by PaulusElektrus** [r0x0r/pywebview#1261]
### Specification
- pywebview version: 4.4.1
- operating system: Windows 11 - 22H2 - 22621.2715
- web renderer: Microsoft Edge WebView2 - DevTools (Microsoft Edge)

### Just for information purposes or changes in future releases...

When I start pywebview nothing appears in the window. When I debug I get the following error message:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

#### Solutions:

- In webview/http.py file, line 129, add following code:
  ```py
  if str(file).endswith('.js'):
               return bottle.static_file(file, root=server.root_path, mimetype='application/javascript')
  else:
               return bottle.static_file(file, root=server.root_path)
  ```

- Or before starting the app executing the following code:
  ```py
  import mimetypes
  
  mimetypes.add_type('application/javascript', '.js')
  ```

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by PaulusElektrus** [comment]
My inspiration: https://github.com/pallets/flask/issues/1045

**Comment by Barafu** [comment]
Yes, encountered the same problem trying to use Xel.js
Thank you very much for the second workaround, it works. I believe it should at least be addressed in documentation.

```
import webview
import mimetypes


from gui_api import MainWindowApi


def main():
    """Main"""
    mimetypes.add_type("application/javascript", ".js")
    api = MainWindowApi()
    window = webview.create_window(
        "Character Card Viewer", url="assets/index.html", js_api=api
    )
```
