### ISSUE TITLE
Using <a> element in files doesn't work.

### ISSUE THREAD

**Issue by FirstFox2** [r0x0r/pywebview#1265]
### Specification
- pywebview version: 4.4.1
- operating system: Windows 10
- web renderer: It uses chrome in debug mode

### Description

  Describe your issue in details. Provide a stand-alone code example that would demonstrate the problem.

Using the <a> element in a  loaded html file won't properly load the file being linked to. Both are HTML.

Code:
import webview

#fromFile is a file that is read and then loaded
fromFile = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <a href="toFile.html">A</a>
</body>
</html>
"""

#toFile is an actual file
toFile = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <h1>A</h1>
    <p>Hakadskdf</p>
</body>
</html>
"""

window = webview.create_window(None, html=fromFile, maximized=True)

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

Sorry, I would help but I am not very good at coding.

**Comment by r0x0r** [comment]
What's fromFile? It should be a string containing html
