### ISSUE TITLE
The window fails to initialize properly after a screen size change.

### ISSUE THREAD

**Issue by Error063** [r0x0r/pywebview#1270]
### Specification

- pywebview version: 4.4.1
- operating system: Windows 11 Pro 23H2 22631.2715
- web renderer: edgechromium

### Description

Some problematic code:

```python
while True:  # Enters this loop if the user can initialize the pywebview on their device.
    if load:  # Using the global variable 'load' to control the program initalize the window or not.
        load = False  # Set false to make sure only one main window on the desktop.
        webview.create_window('example', app)  # Using Flask as application backbone.
        webview.start(debug=True)
    time.sleep(1)
 
# This program have a thread to handle some event about the tray (using pystray), one of the event is if the user click the icon on the tray, the global variable 'load' will set true that let the main loop to initalize the pywebview again.
```

The screen record about this problem (after screen size changed):

https://drive.google.com/file/d/1nQ8Sjo9jL2Tf1zqcCkU4uUAAEBX56v3r/view?usp=drive_link

### Practicalities

- NO I cannot to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry I do not follow what the problem is. The video is really wild.

**Comment by Error063** [comment]
Sorry about my poor English. It's a problem about if you open the window on the screen like the screen on the laptop or using remote desktop like mstsc and then connect to the another screen, the program will faill at the next initialize.


Maybe more clearly.

---Original---
From: ***@***.***&gt;
Date: Sun, Nov 26, 2023 04:56 AM
To: ***@***.***&gt;;
Cc: "Chen ***@***.******@***.***&gt;;
Subject: Re: [r0x0r/pywebview] The window fails to initialize properly after ascreen size change. (Issue #1270)




 
Sorry I do not follow what the problem is. The video is really wild.

**Comment by Error063** [comment]
Because the screen size changed, the program will faill at the next initialize. It looks like the window was opened but no any content on it

**Comment by Error063** [comment]
The pervious window which was created before screen size changed, it's work but looks so mushy because the DPI also changed

**Comment by Error063** [comment]
Full record about this problem: https://drive.google.com/file/d/16cUTYFCY4iRokqwwbWcDYyAk1Irw0yra/view?usp=drive_link
