### ISSUE TITLE
Issues related to window transparency and mouse penetration

### ISSUE THREAD

**Issue by Tamakostory** [r0x0r/pywebview#1271]
### Specification
- pywebview version:4.4.1
- operating system:win11
- web renderer:cef

### Description

  Can pywebview set the transparency of specific values for the window?
After setting `transparent=True`, the mouse will penetrate the window
I need to solve this problem

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a known issue and unfortunately nothing can be done about it until Microsoft fixes it in WebView2. See https://github.com/r0x0r/pywebview/issues/1200
