### ISSUE TITLE
Locked Down Web Engine Newer than Chrome 66

### ISSUE THREAD

**Issue by AndrewStuhr** [r0x0r/pywebview#1278]
### Specification
- pywebview version: 4.1 (can update if needed)
- operating system: Windows
- web renderer: CEF

### Description

Thanks for the great library, and pardon the question as I'm unfamiliar with the details of CEF.  Is it possible to use a fixed version of chromium that is newer than CEF (Chrome 66)?  I'm looking for a locked down version of a web browser, which CEF provides.  However, CEF is missing some CSS & JS features from the past 5 years that would be helpful.  I'm looking to deploy an application onto systems with unknown browser versions, so I don't want to rely on edgechromium (Evergreen) as each system could behave differently.  Any thoughts on this predicament?

### Practicalities

- YES I am willing to work on this issue myself.

- MAYBE I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
It seems possible, but I haven't looked into it for a while, nor I do not want getting into maintaining an up-to-date CEF runtime. cefpython3 seems to be abandoned too, so the prospect of maintaining a deprecated platform does not seem very appealing to me. 
If somebody gets it working, then necessary support can be incorporated into _pywebview_ (in form of documentation or code).
