### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by idbeny** [r0x0r/pywebview#1284]
I noticed android support with #377 , but no support plan for iOS. Can you tell me what are the difficulties in supporting pywebview on iOS? I have ideas to support iOS and hope to get your guidance and your research report.

**Comment by r0x0r** [comment]
I have not researched IOS support apart from that it could be added via Kivy, same way as with Android. I do not know what Kivy experience on IOS is like and whether pywebview features like Javascript-Python bridge can be implemented. Besides that I am not a IOS user nor I have a recent IOS device.
Contributions are welcomed.

**Comment by pavloshargan** [comment]
+1 for IOS, following this issue
