### ISSUE TITLE
Process Run forever

### ISSUE THREAD

**Issue by mohvfx** [r0x0r/pywebview#1288]
### Specification
- pywebview version: 4.4.1
- operating system: Windows
- web renderer: Chrome

### Description

  I was creating a webview to see my web app directly from a window but once I close it the process still running

### Practicalities

- YES/NO I am willing to work on this issue myself. NO

- YES/NO I am prepared to support this issue financially. NO

**Comment by r0x0r** [comment]
Does it occur with `examples/simple_browser.py`?
