### ISSUE TITLE
How to access camera?

### ISSUE THREAD

**Issue by banx9x** [r0x0r/pywebview#1289]
### Specification
- pywebview version: 4.4.1
- operating system: MacOS Ventura 13.6.3
- web renderer: Webkit

### Description

 I want to access camera and show in player, but navigator.mediaDevices is undefined

### Practicalities

- YES/NO I am willing to work on this issue myself. NO

- YES/NO I am prepared to support this issue financially. YES

**Comment by r0x0r** [comment]
Might be possible to implement as per https://forums.developer.apple.com/forums/thread/134216
