### ISSUE TITLE
[Question] 'pywebviewready' does not trigger, where start troubleshooting?

### ISSUE THREAD

**Issue by eik-dahms** [r0x0r/pywebview#1290]
### Specification
- pywebview version: 4.3.3
- operating system: Ubuntu 

### Description

I am working on a react-vite boilerplate. Similar to https://pywebview.flowrl.com/examples/#react-boilerplate. Everything works fine so far. I can call python functions from JS and vice versa.

My Problem is when I add the eventlistener 'pywebviewready' it never gets triggered except in the entry script. So e.g.

for main.tsx:
```tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

window.addEventListener('pywebviewready', function () {
  console.log('pywebview ready')
})


ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
) 
```
this works but if I try that in the App script App.tsx

```tsx
import Editor from './components/Editor/Editor'
import Ticker from './components/Ticker/Ticker'
import Header from './components/Header/Header'

function App() {

  window.addEventListener('pywebviewready', function () {
    console.log('pywebview ready')
    })
  

  return (
    <div>
      <Header />
      <Ticker />
      <Editor />
    </div>
  )
}

export default App
```
will log nothing as the event listener never gets triggered. And this is true for the child components too.

This is not such a big of a problem as I could simply check in the main script if pywebview is ready and render the App component dependend on that.

But it works in the boilerplates from the documentation? So I see no reason why it should not work here.

So my Question is, how do I best start troubleshooting this? Are there some file/ naming conventions which need to be fullfilled for this to work properly? Might this be due to some vite specific building behaviour? Thankful for any ideas/ hints.

### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
The problem is that if you add `pywebviewready` event handler in the React code, it gets attached only after the event is fired. I think it is safe to assume that `window.pywebview` is set up already, when React code is initialized, so you would not need any extra check.

**Comment by eik-dahms** [comment]
Thanks! The reason I wanted to do this is to provide some sort of fallback/ switch. E.g. in case I want to use the frontend with different backends depending on where the frontend lifes or for development purposes. 
But this could also be setup in the mainscript then.
