### ISSUE TITLE
Use waitress as the server

### ISSUE THREAD

**Issue by tmblog** [r0x0r/pywebview#1297]
### Specification
- pywebview version: 4.4.1 
- operating system: win 11
- web renderer: edge

### Description
Trying to pass waitress server to pywebview, this is how I do it using a separate thread:
Wondered if a separate thread is necessary and can be done by passing the server as an argument.
```
app = Flask(__name__)

def run_waitress():
    serve(app, host='127.0.0.1', port=5000)
    
if __name__ == '__main__':
    waitress_thread = threading.Thread(target=run_waitress)
    waitress_thread.start()

    webview.create_window('Flask example', 'http://127.0.0.1:5000')
    webview.start(debug=True)
```
Why am I not able to do:
```
waitress_server = serve(app, host='127.0.0.1', port=5000)
webview.create_window('Flask example', app, http_server=waitress_server)
webview.start(debug=True)
```
Any help will be appreciated.
Thank you

**Comment by r0x0r** [comment]
http_server is a boolean param to turn the built-in server on/off, so your example should be 
```python
app = Flask(__name__)
webview.create_window('Flask example', app)
webview.start()
```

**Comment by r0x0r** [comment]
waitress seems cool though. might be a more modern alternative for a built-in server than bottle.

**Comment by tmblog** [comment]
> http_server is a boolean param to turn the built-in server on/off, so your example should be
> 
> ```python
> app = Flask(__name__)
> webview.create_window('Flask example', app)
> webview.start()
> ```

waitress_server = serve(app, host='127.0.0.1', port=5000)
webview.create_window('Flask example', waitress_server)
webview.start()

Should this work?

**Comment by hasansezertasan** [comment]
> waitress seems cool though. might be a more modern alternative for a built-in server than bottle.

Did you consider starlette?

**Comment by tmblog** [comment]
> > waitress seems cool though. might be a more modern alternative for a built-in server than bottle.
> 
> Did you consider starlette?

No I haven't tried it does it work with pywebview built in?

**Comment by hasansezertasan** [comment]
> No I haven't tried it does it work with pywebview built in?

I am not entirely sure but It's an ASGI framework/toolkit unlike Waitress or Bottle (WSGI) but you can serve FastAPI (uses Starlette underneath) applications alongside PyWebView.
