### ISSUE TITLE
Windows, extended second display - app window disappear after restoring windowed mode

### ISSUE THREAD

**Issue by ales-vilchytski** [r0x0r/pywebview#1298]
### Specification
- pywebview 4.4.1, tried master 0eef180d6c9e
- system: Windows 10 Pro 22H2 (19045.3803), laptop + external monitor
- renderer: edgechromium (default)

### Description

With minimal example code:
```
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()
```

#### Steps to reproduce
1. Use 2 displays in 'Extend these displays' mode 
2. Not sure if it matters, but main display - 1920x1080 scale 100%, second (attached) display - 3840x2160 scale 300%, connected via HDMI 2.1, layout (left, right, top, bottom) doesn't matter
3. Run app `python <script>` (or run app and then connect second display, it doesn't matter)
4. Move window to second display
5. Maximize window (Win + ↑)
6. Disconnect external display / switch to 'Duplicate these displays' mode
7. Restore windowed mode (Win + ↓) (note, that minimize window Win + M works as expected)
8. Try to show up window again (click taskbar)

#### Actual result
App window disappear after restoring windowed mode, seems like it collapses and then moves (all animated) somewhere to unaccessible area

#### Expected result
Show window on current display. It's expected to have size not larger than current display but may fill all available width and height in windowed mode (checked ER with MS Word)

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I fixed a similar sounding issue some time ago https://github.com/r0x0r/pywebview/issues/1229. You can see the fix here https://github.com/r0x0r/pywebview/commit/63a713af39b835b53606e7d47afc6452fc8824a4 
Maybe this logic can be tweaked to address this case
