### ISSUE TITLE
Feature Request: ability to specify a minimum size for the window

### ISSUE THREAD

**Issue by jonathon-love** [r0x0r/pywebview#13]
at the moment the user can resize to whatever they like, and this can be a bit funny:

![screen shot 2015-10-27 at 12 48 57 pm](https://cloud.githubusercontent.com/assets/3240247/10757172/5d435fc0-7ca9-11e5-871a-5ee26611fd82.png)

low priority i know!

thanks

**Comment by r0x0r** [comment]
I added the feature in the master branch. Pass the min_size=(width, height) parameter to the create_window function.

**Comment by jonathon-love** [comment]
awesome! thanks so much.
