### ISSUE TITLE
Debugging javascript

### ISSUE THREAD

**Issue by carlitoselmago** [r0x0r/pywebview#130]
Is there any way to debug if there's errors in the javascript side once the app is running?

Back in the day when using a similar library like pywebview I could enable chromium developer window to see possible bugs in javascript. (That one was using chromium in particular).

**Comment by r0x0r** [comment]
If you are running a local dev server, you can debug your code in a web browser. Otherwise see this issue #122 on how to enable dev tools inside the pywebview window.

**Comment by MisterY** [comment]
What would be the recommended way to debug an HTML/CSS/JavaScript page when using the integrated API approach (no separate server component)? Browser, of course, complains that `pywebview is not defined`.

**Comment by r0x0r** [comment]
Does `debug=True` work for you? I noticed yesterday that it crashes GTK for local files, not sure about other platforms.

**Comment by MisterY** [comment]
Tried it today on Windows but not sure where the debug output would be. There was nothing in the console from which the app was started.

**Comment by r0x0r** [comment]
There's no debugging on Windows, apart from error logging. This is a
limitation of the rendering engine. Hopefully the coming Edge engine will
provide its own debugger.
As for your original question, mocking the pywebview object is probably
your best bet.

**Comment by MisterY** [comment]
Thanks for the comment. As expected, I think using a server would be a more convenient and useful option so I'll pursue that option.
