### ISSUE TITLE
Shortcuts do not work in Web Inspector

### ISSUE THREAD

**Issue by AlecHaring** [r0x0r/pywebview#1300]
### Specification
- pywebview version: 0eef180d6c9e76ef01729a082ee02ea4026a795e
- operating system: macOS 14.2.1
- web renderer: WebKit

### Description

Shortcuts such as `CMD + C`, `CMD + V`, `CMD + W`, etc., do not work in the WebKit Inspector.

I suspect it has something to do with the fact that shortcuts like those are typically handled by the menu shortcuts, but since menu shortcuts are not implemented yet, the logic is handled inside `WebKitHost.keyDown_`. But keyDown events from the Web Inspector don't trigger that method.

### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
Sorry, I have no idea about this issue, but my experience with WKWebView that you have to implement every "non-standard" feature by hand. This would probably require to have a separate keyDown_ implementation for the web inspector.
