### ISSUE TITLE
Bundling on Linux

### ISSUE THREAD

**Issue by FeralFox** [r0x0r/pywebview#1303]
### Specification
- pywebview version: 4.1.1
- operating system: Any Linux
- web renderer: Gtk

### Description

I have a question regarding bundling applications on Linux using pyinstaller.
Since Gtk is used here, the size of the package will be quite big as PyGobject etc. is bundled. So in the bundle I have Gtk + Webview which actually makes the bundle bigger than when using plain Gtk. I guess it is the same for Qt.
On Windows, the bundle size is about 100mb less, using the native controls.
Am I doing something wrong here or is this expected?

Thank you very much!

**Comment by r0x0r** [comment]
You can always explicitly exclude dependencies when freezing or at least Pyinstaller has got this option. Excluding a dependency will make the executable having to depend on installed libraries, so you have to make sure that the target machine has got them or install on the fly. Keep in mind that Pyinstaller picks all the dependencies referenced by pywebview whether you use them or not. So if you have both PyQT and pygobject installed, both will be bundled in the executable. The solution for this is to use either a clean virtual environment or explicitly exclude dependencies you do not need.

I have no experience with freezing on Linux, so I do not know what is the best way to handle this

**Comment by FeralFox** [comment]
I usually build the Linux version in a Docker container, which - in the end - works like the virtual env. So I just package gtk. However, I was wondering why the Linux version has about double the size of the Windows version.
I guess this is because pygobject ships the webview itself and does not use the one of the system. But I might be wrong here
