### ISSUE TITLE
Does pywebview have `window.maximize`?

### ISSUE THREAD

**Issue by XcantloadX** [r0x0r/pywebview#1304]
### Specification
- pywebview version: 4.4.1
- operating system: Windows 11
- web renderer: WinForms / Chromium

### Description
There are `window.minimize`, `window.restore` and `window.resize`, but no `window.maximize`.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
No there is no one, but it could be added.

**Comment by r0x0r** [comment]
Version 5.0.1 has `window.maximize`
