### ISSUE TITLE
`window.destroy()` crashes with `KeyError` if the window has already been closed

### ISSUE THREAD

**Issue by Aran-Fey** [r0x0r/pywebview#1306]
```python
import webview

win = webview.create_window('Demo', 'https://www.github.com')
webview.start()  # Note: Manually close the window when it appears
win.destroy()
# Traceback (most recent call last):
#   File "D:\Users\Aran-Fey\Desktop\temp {e}\untitled.py", line 15, in <module>
#     win.destroy()
#   File "C:\Python312\Lib\site-packages\webview\window.py", line 50, in wrapper
#     return function(self, *args, **kwargs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "C:\Python312\Lib\site-packages\webview\window.py", line 324, in destroy
#     self.gui.destroy_window(self.uid)
#   File "C:\Python312\Lib\site-packages\webview\platforms\winforms.py", line 771, in destroy_window
#     window = BrowserView.instances[uid]
#              ~~~~~~~~~~~~~~~~~~~~~^^^^^
# KeyError: 'master'
```

**Comment by r0x0r** [comment]
The behaviour of window objects after their destruction is not defined. This should be improved, though.

Options for behaviour of invoking a function of a destroyed window are either a) print a warning message and do nothing or b) throw a custom exception. Not sure which one is better or maybe there is a third solution. Comments welcomed.

**Comment by Aran-Fey** [comment]
Another option is to make `.destroy()` idempotent, i.e. simply do nothing if the window is already destroyed.

By the way, I think this error also occurs if `.destroy()` is called *too early*, before the window has been actually opened. I don't know how you can tell when it's safe to call `.destroy()`.
