### ISSUE TITLE
window.onblur was unexpectedly triggered

### ISSUE THREAD

**Issue by yllhwa** [r0x0r/pywebview#1307]
### Specification
- pywebview version: 4.4.1
- operating system: Windows 11
- web renderer: edgechromium

### Description

Reproduction code:
```python
import webview

def preload(window):
    window.evaluate_js('window.onblur = ()=>{pywebview.api.log("blur")}')
    window.evaluate_js('window.onfocus = ()=>{pywebview.api.log("focus")}')
class RuntimeApi:
    def log(self, message):
        print(message)

if __name__ == '__main__':
    window = webview.create_window('test', js_api=RuntimeApi())
    webview.start(preload, window)
```
When the window loses focus and regains focus, three events will be triggered in sequence: focus, blur, and focus.

Expect only focus events to be triggered once.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Check `on_activated` logic in `winforms.py:235`. Maybe it could be improved.

**Comment by yllhwa** [comment]
comment this helps.
```python
def on_activated(self, *_):
      if not self.pywebview_window.focus:
          windll.user32.SetWindowLongW(self.Handle.ToInt32(), -20, windll.user32.GetWindowLongW(self.Handle.ToInt32(), -20) | 0x8000000)
      elif self.browser:
          pass
          # self.browser.web_view.Focus()

      if is_cef and self.pywebview_window.focus:
          CEF.focus(self.uid)
```
It seems that the webview automatically gained focus, 

and setting focus again would result in repeated triggering of events

**Comment by r0x0r** [comment]
Feel free to submit a PR
