### ISSUE TITLE
How to configure zoon/scale when opening a new URL ?

### ISSUE THREAD

**Issue by eriksdev1** [r0x0r/pywebview#1309]
### Specification
- pywebview version:  4.4.1
- operating system: Debian 12 stable
- web renderer:  ?

### Description

I'm running this and I would like to know how to make the window that is created have a smaller zoom factor, thanks in advance:

`import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello',
                      width=200, height=200, zoomable=True,)
webview.start()`

### Practicalities

- YES/NO I am willing to work on this issue myself.     YES

- YES/NO I am prepared to support this issue financially.     YES

**Comment by r0x0r** [comment]
This is not implemented.
It is probably doable, but I haven't researched anything on the subject.

**Comment by eriksdev1** [comment]
Thank you for replying @r0x0r

**Comment by mphirke** [comment]
How about doing it with javascript instead on load or on the HTML page?

```
import webview
import webview.menu as wm

HTML = """<h2>Hello World</h2>
<script>
            document.body.style.zoom = "200%";
</script>"""

if __name__ == '__main__':
    window = webview.create_window(
        'Programming Menu', html=HTML, zoomable=True, 
    )
    
webview.start()
```

Just change the 200% to your desired zoom value.

**Comment by eriksdev1** [comment]
Thank you @mphirke  ! I was wondering how to set the zoom but with an existing web page from the web, I tried searching inhecting javascript but I'm new at this, I would for example, the following page to have less zoom:




`import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello',
                      width=400, height=400, zoomable=True,)



webview.start()`
