### ISSUE TITLE
Moving window and selecting screen does not work on Wayland

### ISSUE THREAD

**Issue by mrckompadre** [r0x0r/pywebview#1311]
### Specification
- pywebview version: 4.4.1
- operating system: Linux Wayland
- web renderer:

### Description

    The x, y and screen parameters do not work in the Wayland composer.  Works correctly on Xorg

### Practicalities

- NO

- NO

**Comment by paulocoutinhox** [comment]
+!

**Comment by r0x0r** [comment]
Is this GTK or QT?

**Comment by mrckompadre** [comment]
QT. Testing was carried out on KDE Plasma 5

**Comment by peeweek** [comment]
I have been having the same issue on my own lately, this time using GTK on Wayland Gnome session

Both move_window or even the default position do not affect the window position.
Moreover, the easy_drag or even the `pywebview-drag-region` do not seem to work either on wayland

All these do work correctly when switching to a x11 Gnome session

**Comment by r0x0r** [comment]
It seems that you cannot programmatically move a window in Wayland. See for example https://stackoverflow.com/questions/72891037/work-arounds-for-lack-of-qwidgetmove-under-wayland

**Comment by ElDonad** [comment]
Window position handling in Wayland is the responsability of the Desktop Manager. This functionality is usually implemented in support libraries provided by the graphical shell. For example with Gnome, you would write an extension in JavaScript using the Shell API and invoke functions such as https://gjs-docs.gnome.org/meta14~14/meta.window#method-move_frame to set the window position, and communicate between your regular application and the extension using whatever means you want (sockets, dbus,...) 

Unfortunately there doesn't seem to be a way to access this API from a regular application, so pywebview wouldn't be able to do it in a non intrusive fashion, much less in a desktop agnostic way.
