### ISSUE TITLE
Bug or limitation about load two Window with one HTML file for each?

### ISSUE THREAD

**Issue by paulocoutinhox** [r0x0r/pywebview#1314]
### Specification
- pywebview version: latest
- operating system: any
- web renderer: any

### Description

When i try load the second HTML file in a new Window, it show not found message:

<img width="912" alt="image" src="https://github.com/r0x0r/pywebview/assets/395096/962f773f-8e52-4b3e-be1b-6b0cc9413d1e">

My project:
https://github.com/paulocoutinhox/dataxow

When you press:
<img width="166" alt="image" src="https://github.com/r0x0r/pywebview/assets/395096/3f6c7faa-dcbf-43c9-afe0-30af7efde1f4">

In the first i can load any HTML, but in the second, the first html or the second, still give me not found.

Source:
- https://github.com/paulocoutinhox/dataxow/blob/main/src/backend/window/wpanel.py
- https://github.com/paulocoutinhox/dataxow/blob/main/src/backend/window/wplayer.py

To test the demo:
```
python3 src/backend/main.py
```

Can anyone help me?

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What is the url for the first window?

**Comment by paulocoutinhox** [comment]
I'm using local files for both.

When I debug I see that it open a server in a port for the first window but when I open the second window it try a server in a new port for localhost too.

It is not related to files because I can change the files from one window to other, to open the same file or different and the problem persists and open only in the first window.

All final urls are both localhost + random port.

**Comment by paulocoutinhox** [comment]
Another way that work is when you start with:
```
PYWEBVIEW_DEBUG=1 python3 src/backend/main.py  
```

Instead of load local HTML files, i point the URL to localhost:8081 for panel and localhost:8081 for player, and it works, but it is used while develop web projects to don't need build final HTML files everytime while develop.

**Comment by r0x0r** [comment]
I don't follow what your setup is. This example works in the examples folder.
```python
import webview

if __name__ == '__main__':
    # Master window
    master_window = webview.create_window('Window #1', url='assets/index.html')
    second_window = webview.create_window('Window #2', url='todos/assets/index.html')
    webview.start()
```
