### ISSUE TITLE
CEF for all platforms

### ISSUE THREAD

**Issue by paulocoutinhox** [r0x0r/pywebview#1317]
### Specification
- pywebview version: latest
- operating system: all
- web renderer: cef

### Description

Hi,

If i use CEF as renderer it will embed CEF binaries?

With CEF it works for Windows, Linux and macOS?

Thanks.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
CEF support was introduced at the time when Windows did not have anything better than MSHTML (IE11). With the Edge Chromium support, deprecated cefpython3 and outdated CEF binaries, CEF is pretty much outdated. I see no point in porting it to other platforms.
