### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by wehe64** [r0x0r/pywebview#1318]
### Specification
![image](https://github.com/r0x0r/pywebview/assets/22494096/eb709673-40aa-44fb-a4a5-e51baf809756)

pywebview==4.4.1 [QT]
QtPy==2.4.1
Linux 6.7.0-0-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Jan  8 02:04:09 UTC 2024 x86_64 GNU/Linux

### Description
I'm noticing in my own app the menu always triggers the last item's function.

So I checked out examples/menu.py, and there it is as well, slightly different:

the change_active_window_content gets fired correctly,
but within the 'Random' menu the 'click me' item always triggers the open_file_dialog action
(consistent with the experience in my own menu where there is no sub-menu and the last action is always called).

And I just checked, the same worx well on a Windows box (where I ultimately need it), 
so its most propably an issue under pywebview[qt]

Thanks for the great PyWebView and all the best!

**Comment by r0x0r** [comment]
I pushed a fix to the `5.0` branch

**Comment by wehe64** [comment]
thanks!!
