### ISSUE TITLE
Get current URL on page change

### ISSUE THREAD

**Issue by armin567ip** [r0x0r/pywebview#1320]
Hi, I want a feature request, I want a function to get the current page URL on each page change.
Let's say I'm simply viewing amazon.com and then I enter a product page. Lets say I use print in the fuction so it will have to print.
Amazon.com/HP_laptop blu bluh bluh.

There currently is a "Get current URL" in the documentation, But it only works on  the webview start, And that's not what I want.

Is 10 dollar OK for the donation?

**Comment by r0x0r** [comment]
You can pair get_current_url with the loaded event. That should give you what you want

**Comment by r0x0r** [comment]
https://github.com/r0x0r/pywebview/discussions/1335

**Comment by r0x0r** [comment]
I do not follow. Are you using `history.pushstate` or something like that for updating your url?
