### ISSUE TITLE
Error WebView2 initialization failed with exception after updating to 5.0.1

### ISSUE THREAD

**Issue by lixuelong135** [r0x0r/pywebview#1323]
### Specification
- pywebview version: 5.0.1
- operating system: Windows
- web renderer:edge HTML

### Description
[pywebview] WebView2 initialization failed with exception:
 'CoreWebView2Settings' object is not subscriptable
   在 Python.Runtime.PythonException.ThrowLastAsClrException()
   在 Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   在 Python.Runtime.Dispatcher.Dispatch(Object[] args)
   在 __System_EventHandler`1\[\[Microsoft_Web_WebView2_Core_CoreWebView2InitializationCompletedEventArgs\, Microsoft_Web_WebView2_Core\, Version=1_0_2045_28\, Culture=neutral\, PublicKeyToken=2a8ab48044d2601e\]\]Dispatcher.Invoke(Object , CoreWebView2InitializationCompletedEventArgs )
   在 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Fixed in master. A new release will follow soonish.

**Comment by r0x0r** [comment]
Released
