### ISSUE TITLE
Logging inside function of API object throws RTE on Windows

### ISSUE THREAD

**Issue by wehe64** [r0x0r/pywebview#1327]
## Specification
- pywebview version: 5.0.4
- operating system: Windows 11
- web renderer:

### Description

  when pywebview.api.title() is called in Javascript, pywebview 5.0.4 throws "unsupported callable"
  under 4.4.1 the same code works well

### Practicalities

see stack trace and test-api.obj.py attached
try on windows with 5.0.4 (vs 4.4.1)
change line #23 DO_LOGGING=True/False

[stacktrace_win-5x.txt](https://github.com/r0x0r/pywebview/files/14498363/stacktrace_win-5x.txt)
[test-api-obj.py.txt](https://github.com/r0x0r/pywebview/files/14498370/test-api-obj.py.txt)

**Comment by r0x0r** [comment]
The logger object causes an infinite recursion. I have implemented a simple check and the fix can be found in master.
If you do not want an API object attribute to be exposed, prefix its name with an underscore

**Comment by wehe64** [comment]
wow, underscore prefixing the logger attribute does the trick!

hm, so **all** my members are exposed now unless prefixed with _
obviously a byproduct of the new feature allowing the api object having sub-objects
which now implicitly exposes all member attributes.... this explains the break from 4.4.1
maybe exposing through a decorator explicitely w'd be a bit cleaner

anyway, I'm happy now, **thanks a great lot**!
