### ISSUE TITLE
Hanging on exit when other thread running and dialog box opened

### ISSUE THREAD

**Issue by ElDonad** [r0x0r/pywebview#1329]
### Specification
- pywebview version: 4.4.1
- operating system: Windows 10
- web renderer: The default one (winform/chromium)

### Description

My app setup is that I have another thread running a custom Bottle server, and the main thread running the webview. I sometimes need to open a dialog box from the Bottle server, which I can do using `webview.windows[0].create_dialog_box`, however if I do that the application refuses to close like normal, and I have to kill the terminal. 

It is entierly possible that my approach is very wrong in terms of how pywebview handles multithreading, and there might be a better way to close the other threads than just relying on daemon thread being killed by the OS on exit, but I didn't find much info about it online...

Below is a minimal reproductible (for me at least) example :
```python
from time import sleep
import webview as wv
from threading import Thread


def other_thread():
    sleep(3)
    print(wv.windows[0].create_file_dialog(wv.OPEN_DIALOG))
    while True:
        sleep(0.1)

th = Thread(target=other_thread, daemon=True)
window = wv.create_window("Test window", "https://www.google.com")

th.start()
wv.start()
```

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
At which point does your program hang? You cannot close the window when file dialog is open. Closing file dialog either by selecting a file or cancelling and then closing the window works fine for me.

**Comment by ElDonad** [comment]
Alright, my theory on the matter is that opening a dialog leaves unfinished threads in the process, and that prevents python's daemon thread from bruteforce exiting. Meanwhile I found out that I could subscribe to events on the window which I had missed before, so I can just use terminate the server thread this way, and that seems to do the trick. 

Probably the cleanest way to do it anyways, so I doubt there is much need to investigate this matter further, at your discretion.

**Comment by ElDonad** [comment]
> At which point does your program hang? You cannot close the window when file dialog is open. Closing file dialog either by selecting a file or cancelling and then closing the window works fine for me.

The program hangs after closing the dialog window and the main window.
