### ISSUE TITLE
Corrupted Window Contents

### ISSUE THREAD

**Issue by natankeddem** [r0x0r/pywebview#1331]
### Specification
- pywebview version: 
pywebview==5.0.5
- operating system: 
Raspberry Pi 5 running RASPIOS bookworm 64bit with Python 3.11.2
- web renderer:
PyQt5==5.15.9
PyQt5-sip==12.11.1
PyQtWebEngine==5.15.6

### Description

I am getting a corrupted window display when running the simple-browser.py example.
![image](https://github.com/r0x0r/pywebview/assets/44515217/81c895cc-fec0-4c32-b5da-f31401dc32a7)

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sounds like RPI specific problem. Did this occur with previous versions of pywebview?

**Comment by natankeddem** [comment]
I am not sure, I have never tried to use pywebview before. The same thing seems to happen when using GTK (PyGObject) instead of QT5. Also, I found if you resize the window it seems to fix the issue. Video for reference:
[google_screen_recording_2024-03-08T14-01_35.900Z.webm](https://github.com/r0x0r/pywebview/assets/44515217/d93287c8-bbfb-40a4-aa71-d36a48ebcba9)

Here is a `pip freeze` of my current environment using GTK in case that might be useful:
```
addict==2.4.0
aiofiles==23.2.1
annotated-types==0.6.0
anyio==4.3.0
astunparse==1.6.3
bidict==0.23.1
bottle==0.12.25
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorzero==2.0
contourpy==1.2.0
cycler==0.12.1
EasyMCP2221==1.6.2
fastapi==0.109.2
fonttools==4.49.0
gpiozero==1.6.2
h11==0.14.0
hidapi==0.14.0
httpcore==1.0.4
httptools==0.6.1
httpx==0.27.0
idna==3.6
ifaddr==0.2.0
itsdangerous==2.1.2
Jinja2==3.1.3
kiwisolver==1.4.5
markdown2==2.4.10
MarkupSafe==2.1.5
matplotlib==3.8.2
nested-lookup==0.2.25
nicegui==1.4.11
numpy==1.26.4
orjson==3.9.15
packaging==23.2
pillow==10.2.0
proxy-tools==0.1.0
pscript==0.7.7
pycairo==1.26.0
pycparser==2.21
pydantic==2.6.3
pydantic_core==2.16.3
pyftdi==0.52.9
Pygments==2.17.2
PyGObject==3.46.0
pyodbc==5.1.0
pyparsing==3.1.2
Pypubsub==4.0.3
pyserial==3.5
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-engineio==4.9.0
python-multipart==0.0.6
python-socketio==5.11.1
pyusb==1.2.1
PyVISA==1.11.3
pywebview==5.0.5
PyYAML==6.0.1
requests==2.31.0
scipy==1.11.4
simple-websocket==1.0.0
six==1.16.0
smbus2==0.4.1
sniffio==1.3.1
sounddevice==0.4.1
starlette==0.36.3
tqdm==4.66.1
typing_extensions==4.10.0
urllib3==2.2.1
uvicorn==0.27.1
uvloop==0.19.0
vbuild==0.8.2
watchfiles==0.21.0
websockets==12.0
wsproto==1.2.0
```

**Comment by r0x0r** [comment]
Seems like the same problem with VSCode on RPI https://www.reddit.com/r/raspberry_pi/comments/199yhpy/application_gui_corrupted/
