### ISSUE TITLE
Can't resize down to min_size on GTK

### ISSUE THREAD

**Issue by coffeejunk** [r0x0r/pywebview#1332]
### Specification
- pywebview version: 5.0.5
- operating system: Fedora F39
- web renderer: GTK

### Description

With a `min_size` of  `(10,10)` for an application running on GTK (GNOME, Wayland), executing a `resize(10, 10)` resizes the application to `(46,46)`. 

![image](https://github.com/r0x0r/pywebview/assets/205556/fb3370f9-ebb4-42b6-a203-e33c3cae4868)

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by coffeejunk** [comment]
Hm, I find that confusing. If I change the [GTK getting started C example](https://docs.gtk.org/gtk4/getting_started.html) to use `10x10` (and set window decoration to `false`) it complies:

![10-by-10](https://github.com/r0x0r/pywebview/assets/205556/39604911-2e6f-4a5b-9821-acf5ab3c7baf)

**Comment by coffeejunk** [comment]
It also works correctly with the Python bindings:

```python
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk

def on_activate(app):
    win = Gtk.ApplicationWindow(application=app)
    win.set_default_size(10, 10)
    win.set_decorated(False)
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)

app.run(None)
```

![gtkpy](https://github.com/r0x0r/pywebview/assets/205556/3bf69789-d60e-4a6a-b538-4f388a9b36ac)

**Comment by r0x0r** [comment]
Try  `webview.create_window(..., frameless=True)`. It invokes `set_decorated(False)`on GTK

**Comment by coffeejunk** [comment]
I tried that [here](https://private-user-images.githubusercontent.com/205556/311290657-fb3370f9-ebb4-42b6-a203-e33c3cae4868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTM0ODEsIm5iZiI6MTcwOTk1MzE4MSwicGF0aCI6Ii8yMDU1NTYvMzExMjkwNjU3LWZiMzM3MGY5LWViYjQtNDJiNi1hMjAzLWUzM2MzY2FlNDg2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwMjU5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2M2ZDZmNDQ5NTYyMWQwOTM4NjJlMjQyYTBmNWZlMjMxZmU0MDRkZWY1NDJmNDhlZjY3ZWY5OGY5ZWI5ZTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8F4LdPwBPZZO-isr2ncXiAAc0g_eNgys5Ov2_6hAxrg) but it didn't work 🤔

**Comment by coffeejunk** [comment]
I think I've found the culprit in this matter: [`Gtk.ScrolledWindow()`](https://github.com/r0x0r/pywebview/blob/713b43a9f9b559ece697d517f4b2831784cdb643/webview/platforms/gtk.py#L119-L120). 

[`Gtk.ScrolledWindow()`'s default policy](https://docs.gtk.org/gtk3/method.ScrolledWindow.set_policy.html) (for the visibility of the vertical and horizontal scrollbars) is `Gtk.PolicyType.AUTOMATIC`. This appears to enforce a minimum height and width of 46px respectively. 

the white square is the application running with `46x46`
![Screenshot from 2024-03-20 01-01-31](https://github.com/r0x0r/pywebview/assets/205556/07d70da3-1f27-4f35-942b-ddd3bb019ab1)
_(the window itself is reporting a size of `3x3`)_

This can be remedied by setting the policy to `Gtk.PolicyType.NEVER`:

![Screenshot from 2024-03-20 01-06-57](https://github.com/r0x0r/pywebview/assets/205556/992d7de3-2d75-4f6a-99b2-896c6a01a565)
_(a little hard to see, but the tiny square in the top left corner is the application running with `3x3`)_

<details>

<summary> <code>gtk-scrolled-window.py</code> </summary>

```python
import gi
gi.require_version('Gtk', '3.0')

from gi.repository import Gtk

window = Gtk.Window()
window.set_default_size(3, 3)
print(f".set_default_size: {window.get_size()}")
window.set_decorated(False)
window.connect("destroy", Gtk.main_quit)

scrolled_window = Gtk.ScrolledWindow()
# uncommenting the line below fixes the issue
# scrolled_window.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.NEVER)
scrolled_window.set_propagate_natural_height(False)
scrolled_window.set_min_content_height(3)
scrolled_window.set_max_content_height(3)
print(f".get_min_content_height: {scrolled_window.get_min_content_height()}")
print(f".get_max_content_height: {scrolled_window.get_max_content_height()}")

print(f"before .add: {window.get_size()}")

window.add(scrolled_window)

print(f"after .add: {window.get_size()}")
window.show_all()
Gtk.main()

```

</details>


In `pywebview` I've found two options to solve the issue for me:

1. [Setting the policy to `Gtk.PolicyType.NEVER`](https://github.com/r0x0r/pywebview/compare/master...coffeejunk:pywebview:gtk-scrolled-window-policy?expand=1)
2. [Removing the `Gtk.ScrolledWindow()` entirely.](https://github.com/r0x0r/pywebview/compare/master...coffeejunk:pywebview:gtk-remove-scrolled-window?expand=1)

Interestingly (read: I don't understand why), I do still get scrollbars with either of the patches applied:


<details>
<summary>policy set to <code>Gtk.PolicyType.NEVER</code></summary>

![Screenshot from 2024-03-20 01-19-59](https://github.com/r0x0r/pywebview/assets/205556/10b20fad-b9c1-4c26-996f-610765d0d8c9)

</details>

<details>
<summary><code>Gtk.ScrolledWindow()</code> removed</summary>

![Screenshot from 2024-03-20 01-24-47](https://github.com/r0x0r/pywebview/assets/205556/5b47b1ca-b35e-4c9f-9b1b-8fe2bb2cfba6)


</details>

Let me know if you have any thoughts on this. I'm happy to open a PR for either of the options, whichever you prefer.

**Comment by r0x0r** [comment]
I get a blank screen with removing ScrolledWindow, so the first option is certainly better. Feel free to provide a PR
