### ISSUE TITLE
i want get httponly cookies

### ISSUE THREAD

**Issue by erbhosting** [r0x0r/pywebview#1337]
### Specification
- pywebview version: last one
- operating system: win 11
- web renderer:

### Description

  Describe your issue in details. Provide a stand-alone code example that would demonstrate the problem.

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

i need to do it for my project please help me i will pay if need money to solve this problem
if possible contact me in telegram
@erbabsaji
thanks a lot

**Comment by r0x0r** [comment]
`window.get_cookies()` is able to fetch httponly cookies

**Comment by erbhosting** [comment]
> `window.get_cookies()` is able to fetch httponly cookies

dont show all cookies
i want all cookie
httponly or other
there is any way to get all cookies?!

**Comment by r0x0r** [comment]
Do you have an example that would demonstrate the problem? The relevant code for getting httponly cookies can be seen here https://github.com/r0x0r/pywebview/blob/a80cb40121adb09dc9e24feca21d7c758914d67a/webview/platforms/edgechromium.py#L117

I assume you are using EdgeChromium
