### ISSUE TITLE
Custom JSON encoders for js bridge call

### ISSUE THREAD

**Issue by XcantloadX** [r0x0r/pywebview#1339]
### Specification
- pywebview version: 4.4.1
- operating system: Windows 11
- web renderer: Webview2

### Description
[Custom JSON encoders](https://stackoverflow.com/questions/51286748/make-the-python-json-encoder-support-pythons-new-dataclasses) will be helpful if you want to return a namedtuple or dataclass object.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Replacing `json.dumps` with `orjson.dumps` seems like a straightforward solution.

**Comment by ylm-king** [comment]
That's a good idea. There are many libraries that perform faster than json, and I myself have given up using json and replaced it with ujson or something else

**Comment by r0x0r** [comment]
I ran into a problem with orjson. There is no recipe for p4a, so it cannot be used on Android. There is an issue about adding a recipe in the p4a repo https://github.com/kivy/python-for-android/issues/3001
Let's wait until the support is added.
