### ISSUE TITLE
Add example for python-for-android

### ISSUE THREAD

**Issue by benma** [r0x0r/pywebview#134]
Hi

> While Android is not supported, you can use the same codebase with solutions like Python for Android for creating an APK.

Did you test this successfully? If so, it would be helpful to add some lines describing how to do it exactly. I am having trouble figuring it out. Any help is appreciated.

Thanks.

**Comment by r0x0r** [comment]
I've tested it once, but it failed at that time as python 3 was not supported. The instructions were pretty clear though. What problem do you have?

**Comment by benma** [comment]
Maybe a kivy driver is needed for android/ios support?

The android apk is compiled and deployed, but when starting it, it immediately crashes. I am new to mobile app dev, so I don't have more infos at the moment.

I'll leave it to you if you want to close this issue or leave it open to track it. Thanks.

**Comment by shivaprsdv** [comment]
@benma Have you checked the Python for Android docs? It's quite
extensive, might be helpful. Cheers.

**Comment by MisterY** [comment]
This issue comes up prominently when searching on whether pywebview will work on Android. Has anyone succeeded running the UI on Android?
