### ISSUE TITLE
Webview on Android 

### ISSUE THREAD

**Issue by hlohaus** [r0x0r/pywebview#1340]
I created a app for android with webview, but file upload and downloads are not working.

I search for a solution and found AdvancedWebview. It supports request permissions and file uploads and downloads.

Can someone add it to pywebview?

And how can I create a custom .jar build?

Thank you

**Comment by r0x0r** [comment]
File downloads should work. You need to set `webview.settings['ALLOW_DOWNLOADS'] = True` first
File uploads nor file dialogs are not implemented

**Comment by hlohaus** [comment]
Thanks. It was a blob file download. Maybe I need more permission.

I'm not good at Java. It's too complex for me to add downloads and stuff. The keyboard covers the text field. Also, it sometimes shuts down.
