### ISSUE TITLE
Disable control click

### ISSUE THREAD

**Issue by tmblog** [r0x0r/pywebview#1341]
### Specification
- pywebview version: 5.0.5
- operating system: win 11
- web renderer: edge

### Description
Couple of things, firstly thank you for the excellent library. 
I found that I am able to control click a hyperlink and then this loads the page on the browser, how to disable this? Also 
`maximized=True, resizable=False` when double clicked on the menu bar at top it becomes smaller and there is no way to resize it.

Just thought I'd let you know.

**Comment by HariZalan** [comment]
Sorry, I am not r0x0, but in webview.settings, disable opening _blank links in browser.

**Comment by tmblog** [comment]
> Sorry, I am not r0x0, but in webview.settings, disable opening _blank links in browser.

That's great thank you!

**Comment by r0x0r** [comment]
Double clicking the title bar should be fixed.

**Comment by tmblog** [comment]
> Double clicking the title bar should be fixed.

In latest release?
I have this version:
```
Name: pywebview                                                                                                                
Version: 5.0.5
```
But I am still able to double click and that behaviour exists - Windows 11.

Thank you!

**Comment by r0x0r** [comment]
Sorry, I worded it incorrectly. I mean this issue should be addressed.
