### ISSUE TITLE
"[Circular Reference]" when serializing list containing the same object twice

### ISSUE THREAD

**Issue by l3kn** [r0x0r/pywebview#1342]
### Specification
- pywebview version: 5.0.5
- operating system: Windows
- web renderer: Edge

### Description

The function for serializing JS objects at https://github.com/r0x0r/pywebview/blob/master/webview/js/api.py#L100 includes a check for circular references but this seems to be triggered also on lists including the same object twice.

In a JavaScript console where `window.pywebview` is available, this can be replicated as follows:

``` javascript
let a = [];
let b = [];
window.pywebview.stringify([a, b]) // returns '[[], []]'
window.pywebview.stringify([a, a]) // returns '[[], "[Circular Reference]"]'
```

Is this behavior intentional? I found an implementation of a similar check at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value that uses a stack of ancestor objects for its cycle detection.

### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
The circular reference check is quite simple. It keeps track of already processed objects and obviously does not address your example. Improvements are welcomed.

**Comment by r0x0r** [comment]
I fixed this in master
