### ISSUE TITLE
Getting button event

### ISSUE THREAD

**Issue by armin567ip** [r0x0r/pywebview#1344]
Hi, Is it possible to get a button's click event in pywebview?

**Comment by HariZalan** [comment]
Yes, it is. Using JavaScript, you can connect to Python API.

**Comment by HariZalan** [comment]
Yes, of course: https://pywebview.flowrl.com/guide/usage.html#communication-between-javascript-and-python

**Comment by HariZalan** [comment]
And another:
`
import webview
class ourApi():
 def __init__(self):
  pass
 def printitorideletethisscript(self,text):
  print (text)
webview.create_window("JS API test",html="<!DOCTYPE html>\n<html>\n<button onclick='pywebview.api.printitorideletethisscript(\"Success\")'>Test</button>\n</html>\n",js_api=ourApi())
webview.start()
`

**Comment by r0x0r** [comment]
You can use new DOM support to subscribe to DOM events directly from Python. See https://pywebview.flowrl.com/examples/dom_events.html
