### ISSUE TITLE
Enable Spell Check without Requiring webview.start(debug=True)

### ISSUE THREAD

**Issue by juanjoselazohoyos** [r0x0r/pywebview#1348]
I'm working on a project and noticed that spell check can only be enabled when debug=True in webview.start(). However, I aim to have spell check enabled while debug=False. This issue pertains to finding a solution to activate spell check without relying on webview.start(debug=True).

**Comment by r0x0r** [comment]
What platform is this?

**Comment by juanjoselazohoyos** [comment]
windows 10
