### ISSUE TITLE
Issue with pywebview Version Upgrade from 4.4.1 to 5.0.5

### ISSUE THREAD

**Issue by led-mirage** [r0x0r/pywebview#1350]
### Specification

- pywebview version: 5.0.5
- operating system: Windows 11
- web renderer: edgechromium

### Description

Hello,

I've encountered an issue when upgrading the pywebview library from version 4.4.1 to 5.0.5 in my project. The following code snippet, which worked perfectly in 4.4.1, fails to run in 5.0.5 regardless of the content of "index.html" (the issue persists with any content):

``` python
import webview

class Application:
    def __init__(self):
        self.window = None

    def start(self):
        self.window = webview.create_window("Sample Window", url="index.html", js_api=self)
        webview.start()

app = Application()
app.start()
```

Saving the return value of webview.create_window() to a member variable self.window seems to cause the issue. The code runs without issue if I avoid saving to a member variable or set js_api=None.

The exception is thrown when webview.start() is called, with the following message:

```
\webview\window.py", line 45, in wrapper
    raise WebViewException('Main window failed to start')
```

Could you please help me understand if this behavior is expected in version 5.0.5 or if there's a workaround or fix available? Thank you for your support and for maintaining such a useful library.

Best regards,  
led-mirage

**Comment by r0x0r** [comment]
5.0 introduces nested JS API support. In your case, it tries to serialize `self.window` object, but fails at some point. Changing `self.window` to `self._window` should fix the problem.

**Comment by led-mirage** [comment]
Thank you so much for your prompt and helpful response! I followed your advice and changed `self.window` to `self._window`, and it indeed resolved the issue. I really appreciate your support and guidance. Best regards.
