### ISSUE TITLE
Whether to support webgal

### ISSUE THREAD

**Issue by panyan520** [r0x0r/pywebview#1351]
https://gamemcu.com/su7/ , Error reported in pywebview, WebGL: INVALID_OPERATION: useProgram: program not valid
![20240402-143439](https://github.com/r0x0r/pywebview/assets/78577002/1fe5e1bb-197a-4d5e-8117-dfaeef98b87a)

**Comment by r0x0r** [comment]
Are you on macOS? I cannot reproduce this on 14.3, works as it should for me.

![image](https://github.com/r0x0r/pywebview/assets/1549657/8c33ed8b-0312-429c-8f95-1ff6aa343daf)

**Comment by panyan520** [comment]
Yes, I am macos


潘琰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r0x0r/pywebview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月2日(星期二) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [r0x0r/pywebview] Whether to support webgal (Issue #1351)





 
Are you on macOS? I cannot reproduce this on 14.3, works as it should for me.
 
image.png (view on web)
