### ISSUE TITLE
how to build android apk

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1352]
https://github.com/r0x0r/pywebview/tree/master/examples/todos
 
i convert this code into the apk 
I run all steps in google cloab 

tell me how to build apk

**Comment by r0x0r** [comment]
There is a brief freezing guide here https://pywebview.flowrl.com/guide/freezing.html#android
Ultimately you need to get familiar with Buildozer. Start here https://buildozer.readthedocs.io/en/latest/quickstart.html

**Comment by diyism** [comment]
@r0x0r ,

When I run "buildozer -v android release" in ~/pywebview/examples/todos,
I happen this error in ~/pywebview/examples/todos/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/libffi/armeabi-v7a__ndk_target_21/libffi/config.log:
```
configure:4544: ~/.buildozer/android/platform/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target armv7a-linux-androideabi21 -fomit-frame-pointer -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -fPIC -V >&5
clang-14: error: argument to '-V' is missing (expected 1 value)
```
It seems that the libffi require GCC, but the NDK has get rid of GCC since r18(https://github.com/kivy/buildozer/issues/1281)

How to work around this error?

Thanks.

**Comment by r0x0r** [comment]
Sorry, I cannot help with buildozer issues.

buildozer is finicky when it comes to getting environment right. Good luck!

**Comment by diyism** [comment]
Sad, there's another error:
```
configure:4575: checking whether the C compiler works
configure:4597: ~/.buildozer/android/platform/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -target aarch64-linux-android21 -fomit-frame-pointer -march=armv8-a -fPIC -DANDROID -I~/.buildozer/android/platform/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I~/pywebview/examples/todos/.buildozer/android/platform/build-arm64-v8a/build/python-installs/pywebview todos/arm64-v8a/include/python3.1   -L~/pywebview/examples/todos/.buildozer/android/platform/build-arm64-v8a/build/libs_collections/pywebview todos/arm64-v8a conftest.c  >&5
clang-14: error: no such file or directory: 'todos/arm64-v8a/include/python3.1'
clang-14: error: no such file or directory: 'todos/arm64-v8a'
```
It seems the "todos/buildozer.spec" file needs some path configuration.

**Comment by r0x0r** [comment]
Here is the deploy/build script that is working for me

``` bash
export ANDROIDSDK="/Users/roman/Library/Android/sdk"
export ANDROIDNDK="/Users/roman/Library/Android/sdk/ndk/25.0.8775105"
export ANDROIDAPI="30"  # Target API version of your application
export NDKAPI="21"  # Minimum supported API version of your application
export JAVA_HOME=/usr/local/opt/openjdk@17/
export ANDROID_SERIAL=emulator-5554

buildozer android debug deploy runad
```

**Comment by MominIqbal-1234** [comment]
buildozer Run Linux  so i use the google cloab to make apk file first time you wait minimum 30 mint firt apk build

https://colab.research.google.com/drive/1kmIVFtTyXQF-PbSONC1uR7pnoMSh-aIk?usp=sharing

**Comment by diyism** [comment]
Finally, I figured out what's the problem:
1.fixed the error "clang-14: error: no such file or directory: 'todos/arm64-v8a'", the buildozer package.name requirement is one word with only ASCII characters and/or numbers. It should not contain any special characters
2.fix the error "if exclude_dir[-1] != '/':IndexError: string index out of range" while "buildozer -v android release"
Now the command "buildozer -v android debug deploy run" works like a charm.

I've submitted a pull request: https://github.com/r0x0r/pywebview/pull/1368

**Comment by r0x0r** [comment]
The issue with building the todos app was incorrect `setup.py` present in the folder, which was picked by p4a. I removed it and made a few other adjustments to the app. I can build and run todos.apk on my machine now.
