### ISSUE TITLE
webview tag in pywebview

### ISSUE THREAD

**Issue by vision-tao** [r0x0r/pywebview#1353]
### Specification
- pywebview version:
- operating system:
- web renderer:

### Description

 webview tag  like electron to view website in the custom GUI , basically i am making a browser 

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I do not follow.

**Comment by NormVg** [comment]
What does that mean , bro that's is a good stuff , I want to use something like that

**Comment by Xanderplayz16** [comment]
Just use a sandboxed Iframe.

**Comment by vision-tao** [comment]
Not working fude

**Comment by Xanderplayz16** [comment]
> Not working fude

??? It should work, it is pretty much an integral feature of HTML.
 <iframe src="https://google.com"></iframe>

**Comment by NormVg** [comment]
go and run it , it will not run google and other site is protected from iframe
