### ISSUE TITLE
Drag Area cannot be initialized by a script after page loads.

### ISSUE THREAD

**Issue by JustAnEric** [r0x0r/pywebview#1355]
### Specification
- pywebview version: 4.0.2
- operating system: Windows 11
- web renderer: WinForms / Chromium

### Description
PyWebView is unable to initialize a drag area after the page loads. I am trying to make a custom Spotify client and I initialize the drag area like this:
```js
document.body.insertAdjacentHTML('beforeend', `
    <div class="pywebview-drag-region">
            
    </div>
`);
```
How can I make PyWebView sort of check for the `pywebview-drag-region` class name again or is there an alternative?

**Comment by r0x0r** [comment]
The drag area is checked on the application startup. Dynamic check is not implemented, but it can be done with MutationObserver

**Comment by JustAnEric** [comment]
@r0x0r Would you be kind enough to provide an example of this implementation so I can understand it further?

**Comment by r0x0r** [comment]
@JustAnEric look at `webview/js/events.py` lines 26-29 where events are attached to drag selector. A mutation observer would look something like this (courtesy of ChatGPT, untested). I am not sure about performance implications, if this is enabled by default. This needs to be tested first.


```js
// Options for the observer (which mutations to observe)
const config = { attributes: true, childList: true, subtree: true };

// Callback function to execute when mutations are observed
const callback = function(mutationsList, observer) {
    for(var i = 0; i < mutationsList.length; i++) {
        var mutation = mutationsList[i];
        // Check if any of the added nodes have the class '.drag-region-selector'
        if (mutation.type === 'childList') {
            mutation.addedNodes.forEach(node => {
                if (node.nodeType === 1 && node.classList.contains('%(drag_selector)s')) {
                    node.addEventListener('mousedown', onMouseDown);
                }
            });
        } else if (mutation.type === 'attributes' && mutation.target.classList.contains('%(drag_selector)s')) {
            node.addEventListener('mousedown', onMouseDown);
        }
    }
};

// Create an observer instance linked to the callback function
const observer = new MutationObserver(callback);

// Start observing the document for configured mutations
observer.observe(document, config);

// Later, you can disconnect the observer when you don't need it anymore
// observer.disconnect();

```

**Comment by JustAnEric** [comment]
How would PyWebView load that JavaScript in? I'm guessing `util.inject_pywebview()` ?

**Comment by r0x0r** [comment]
The JS code is to be placed in `webview/js/events.py`. It will be loaded by `util.inject_pywebview()` automatically

**Comment by JustAnEric** [comment]
Alright. From observing the code, I also just found out that PyWebView has a bridge function that allows you to move the window, as defined below.
```
window.pywebview._bridge.call('pywebviewMoveWindow', [x, y], 'move');
```
Instead of editing the events.py file, I just pasted the first function into my JavaScript code (basically reinitializing the drag system).
