### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by Haoke98** [r0x0r/pywebview#1356]
### Specification
- pywebview version: 5.0.5
- operating system: Darwin Kernel Version 22.6.0: Tue Nov  7 21:40:08 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_ARM64_T6000 arm64
- web renderer: 

### Description

  When I was use the pywebview with Vue+Typescript+JS project, it was throw the exception like `RangeError: Maximum call stack size exceeded.` But, the same code use on the html+JS is work will.  My code on the python is good , i was write it according to the pywebview official examples.
![截屏2024-04-06 19 38 06](https://github.com/r0x0r/pywebview/assets/55436234/e505f318-3f2e-4edd-bb61-5ace9fb4acf8)

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Are you using js api in your project? It sounds like a problem with the _pywebview_ serializer

**Comment by Haoke98** [comment]
In addition, I am wondering if there are any dependent libraries or SDKs for pywebview that can be installed using npm or yarn. 
Hope to provide some of the following functions:
* Grammar tips.
* Interface call.
* Development environment debugging

**Comment by Haoke98** [comment]
After several attempts, I found that this problem only existed in Vue/Cli projects. After switching to React, this problem did not occur.
* `vue/cli@3` + `TypeScript` + `Vite` ❗️❗️ 
* `React`+`TypeScript` + `Vite` + `AntDesign`   ✅

**Comment by r0x0r** [comment]
I cannot pinpoint the problem from the provided screenshots. Are you able to determine where infinite loop occurs?

I am not aware of any libraries built on top _pywebview_
