### ISSUE TITLE
1.8 release

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#136]
It is time for a new release.
Anything that needs to be addressed before the release?

**Comment by shivaprsdv** [comment]
Would have been great if we could include the `debug` feature
as well, but it looks like a lot more work. I think we're good to go.

**Comment by r0x0r** [comment]
Well, let's include it as an OSX only feature for now.

**Comment by shivaprsdv** [comment]
That doesn't seem ideal. Are we sure we'd be able to implement it
cross-platform by a future release? We still don't know we'd _ever_ be
able to implement it on Windows; Linux doesn't look prospective
either, I have tried on GTK.

Let's not hurry it, hold back it for now.

**Comment by r0x0r** [comment]
Window is no go, other than some rudimentary debug features like logging
errors to python stderr. As linux does not look prospective either, I
suggest to push the OSX implementation to 1.8 and document that it is a osx
only feature.

**Comment by shivaprsdv** [comment]
Well, that kind of violates the cross-platform policy.. I agree it's not
such a major feature, may be it won't hurt. 🆗 then.

**Comment by shivaprsdv** [comment]
BTW you might consider updating `Contributing.md` before the release. 😉

**Comment by r0x0r** [comment]
Done

**Comment by shivaprsdv** [comment]
You seem to have made a mistake. The debug feature is not yet merged.

Also 405755f697f5babdff2e730fde7c8bc71fa38951 seems to have end up in the wrong branch.

**Comment by r0x0r** [comment]
That's what I get for coding late at night. Let's keep the debug feature
out of this release then
Thanks for pointing these out!
