### ISSUE TITLE
Use window inside of tkinter

### ISSUE THREAD

**Issue by PanosHatz** [r0x0r/pywebview#1360]
Can I create a window using create_window and place it inside a frame of my tkinter app somehow? 

In general, I am trying to create an app with a tkinter window divided in half where the left half will have a local PDF from my PC and the right half will have some buttons and fields

The reason I want this is because I need to embed a pdf in tkinter window with the ability to select text and copy/paste

**Comment by r0x0r** [comment]
No you cannot do that.

I investigated it at some point, but did not find a solution. It might be possible though.

**Comment by MominIqbal-1234** [comment]
```python
def delete():
    gui_win = Tk()
    gui_win.withdraw() # remove the main TK window only show message box
    gui_win.iconbitmap('icon.ico')
    msg  = messagebox.askquestion("Message", "Are You Sure Delete Password \t")
    if msg =='yes':
            print("Delete data")
    gui_win.destroy()
    gui_win.mainloop()

```

**Comment by HariZalan** [comment]
Why is this code related, @MominIqbal-1234 ?

**Comment by MominIqbal-1234** [comment]
```python


import webview
from tkinter import *
from tkinter import messagebox
class Api():
  def delete(self, value):
        gui_win = Tk()
        gui_win.withdraw() # remove the main TK window only show message box
        msg  = messagebox.askquestion("Message", "Are You Sure \t")
        if msg =='yes':
                print("Delete data")
        gui_win.destroy()
        gui_win.mainloop()

webview.create_window("Test", html="<button onclick='pywebview.api.delete(\"Woah dude!\")'>Delete</button>", js_api=Api())
webview.start()

```


![image](https://github.com/r0x0r/pywebview/assets/61788052/32f59159-8490-44de-9dd7-1ad0a404c878)

**Comment by Jzhenli** [comment]
> No you cannot do that.
> 
> I investigated it at some point, but did not find a solution. It might be possible though.

pywebview is a lightweight cross-platform wrapper around a webview component that allows to display HTML content in its own **native GUI window**.  Here why use the native gui window to instead of tkinter frame?? As we know, tkinter is a lightweight cross-platform gui too. @r0x0r

**Comment by Jzhenli** [comment]
hi, I find a project [tkwebview2](https://github.com/Smart-Space/tkwebview2) which is based on the pywebview, and display the content on the tkinter frame. @r0x0r @PanosHatz

**Comment by B16f00t** [comment]
Hi everyone,

I've been exploring alternatives like **tkwebview2**, which allows embedding web content directly into a `tkinter` frame. However, I've run into a significant limitation: the lack of support for JavaScript APIs, such as `window.external.invoke` or other mechanisms for JavaScript-to-Python communication. 

### Questions:
1. Has anyone successfully implemented a solution to enable `js_api` in **tkwebview2**? 
2. Alternatively, is there any roadmap or plan for **pywebview** to support embedding its content into a `tkinter` frame in the future? Having this feature would greatly enhance integration with tkinter-based applications.

This would be a game-changer for scenarios where we need seamless communication between JavaScript and Python while maintaining tkinter as the main GUI framework.

Thank you for any insights or updates on this topic!

**Comment by r0x0r** [comment]
I agree that tkinter support would be a nice additition, but it would require a substantial refactor of the whole codebase. I am not sure what architecture would look like or whether it is possible to do it in a neat way without overhauling the whole codevase.

`tkwebview2` supports only EdgeChromium. Its implementation is rather straightforward and is done by passing webview's hwnd to a tkinter control. As for other platforms, I have no idea.
