### ISSUE TITLE
Nuitka support

### ISSUE THREAD

**Issue by Xanderplayz16** [r0x0r/pywebview#1363]
### Specification
- pywebview version: 5.0.5
- operating system: Windows 10 Pro for Workstations / Manjaro Linux KDE
- web renderer: Edge / GTK / QT

### Description

I think that Nuitka support should be added, as it has many more features, is just really useful for the people who are not used to Pyinstaller, Windows Defender really does not like Pyinstaller executables (false flagging), and it is just faster in general, and smaller (in my experience.) 

### Practicalities

- MAYBE I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I am not familiar with Nuitka. Feel free to contribute to this, I will gladly accept a PR.

**Comment by Xanderplayz16** [comment]
> I am not familiar with Nuitka. Feel free to contribute to this, I will gladly accept a PR.

I think I'll make a PR. I mean, it might just really be some tweaks and setting _MEIPASS.

**Comment by Xanderplayz16** [comment]
Looks like viewing a website works fine. I guess I'll test out HTML.

**Comment by Xanderplayz16** [comment]
Looks like onefile mode works, I guess I just have to see why it can't work for plain standalone.

**Comment by Xanderplayz16** [comment]
> Looks like onefile mode works, I guess I just have to see why it can't work for plain standalone.

Nevermind, I guess it just doesn't bundle the files on standalone.
Time to test .so!

**Comment by Xanderplayz16** [comment]
It works. The last time I checked, it didn't work. I guess Nuitka implemented _MEIPASS. Well, I guess I am not smart.

**Comment by Xanderplayz16** [comment]
I guess I'll make a PR that adds Nuitka to the docs.
