### ISSUE TITLE
[WIN] Folder Dialog - New folder is renamed with a delay.

### ISSUE THREAD

**Issue by Igazii** [r0x0r/pywebview#1367]
### Specification
- pywebview version: 5.0.5
- operating system: Windows 11
- web renderer: Edge

### Description

Hello. Every time i create a folder via Folder Dialog it is renamed with a delay. 
Steps to reproduce:
For example I create new folder for saving files.
1. Click on create new folder - default name is "New folder"
2. Rename it.
3. For a few seconds it could stay "New folder" and causes the exception: FileNotFoundError: [WinError 3]  - its because new name isn't applied and folder is still using "New folder" but after few seconds new name is being applied:
seems like the issue with FolderBrowserDialog from win forms, because SelectedPath also includes the old name ("..../New folder") on the line 635.
Mb you have thoughts on how to deal with it, thank you:
  
![example](https://github.com/r0x0r/pywebview/assets/51091362/4240978c-9d49-40c8-8a21-0d73914d42ce)

<img width="528" alt="image" src="https://github.com/r0x0r/pywebview/assets/51091362/2c83e937-69ba-4470-9d66-c3bae4fbd79c">

### Practicalities

- Yes, I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
Sorry for the late response, this issue flew under my radar. I managed to reproduce it, seems like it is a known issue in Winforms. Here are some workarounds. Feel free to submit a PR.
https://stackoverflow.com/questions/6647761/problem-with-folderbrowserdialog
https://stackoverflow.com/questions/36541808/folderbrowserdialog-shows-incorrect-selectedpath-after-new-folder-is-being-creat
