### ISSUE TITLE
google account logout after close the pywebview window

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1370]
google account logout after close the pywebview window how to handle

**Comment by r0x0r** [comment]
It should log out automatically with the `private_mode=True` (that's default). You can also use `window.clear_cookies()` to achieve the same thing

**Comment by MominIqbal-1234** [comment]
### code
import webview
webview.settings['private_mode'] = False
window = webview.create_window('Simple browser', 'https://bing.com')
webview.start()

## Error
webview.settings['private_mode'] = False
AttributeError: module 'webview' has no attribute 'settings'. Did you mean: '_settings'?
