### ISSUE TITLE
[QUESTION] Can pywebview be embedded anywhere?

### ISSUE THREAD

**Issue by HariZalan** [r0x0r/pywebview#1374]
### Specification
- pywebview version: 5.0.5
- operating system: Ubuntu 24.04
- web renderer: WebKit

### Description

Is there any way to embed pywebview to a GUI? I have created a browser, but it is problematic that the poor user has to enter the URL in a separate window.
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
No, embedding is not implemented. _pywebview_ is designed as a stand-alone windows(s) that hosts a webview. Embedding functionality would require an architectural overhaul. Nor I am entirely sure how it should look like in practice and what purpose it would serve.
