### ISSUE TITLE
How can we lift the CORS restrictions in pywebview?

### ISSUE THREAD

**Issue by lightpig7** [r0x0r/pywebview#1375]
![image](https://github.com/r0x0r/pywebview/assets/144079423/a4187cfe-68b6-4161-890c-22f49938b82f)

**Comment by r0x0r** [comment]
It might be possible by modifying response headers. There is an ongoing effort to add header editing support in https://github.com/r0x0r/pywebview/issues/1371

**Comment by lightpig7** [comment]
Thank you very much for your reply. I would like to ask if there is a direct interaction function now. For example, there is `window.send('str')` in the python code, and then there is a `Javascript` function in the `webview` to receive it. The application scenario is when a `js` calls python-api. , can return data multiple times, for example: thread

**Comment by r0x0r** [comment]
You can proxy XHR requests via JS API. In other words you would fetch data in Python and make it available to your frontend via JS API. Something like this

``` python
class API:
  def fetchData(self):
     return urlopen(..)

webview.create_window(..., js_api=Api())
```

``` javascript
pywebview.api.fetchData().then(response => response)
```
