### ISSUE TITLE
javascript print() not working with pywebview

### ISSUE THREAD

**Issue by hadiawahab** [r0x0r/pywebview#1376]
### Specification
- pywebview version: 5.1
- operating system: MacOS Ventura 13.2.1
- web renderer: waitress

### Description

javascript print() not working with pywebview

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Works for me. `examples/simple_browser.py` in debug mode. typed `window.print()` in console
Sonoma 14.3
