### ISSUE TITLE
There's a problem here

### ISSUE THREAD

**Issue by jekajek** [r0x0r/pywebview#1377]
### Specification
- pywebview 5.1:
- Windows:
- Edge:

### Description

 I wanted to test the Js Api directly from the official website to understand how to use it, but it outputs this
![Снимок](https://github.com/r0x0r/pywebview/assets/71945759/dd5934c6-1dc8-4734-9143-28ef8ecd2711)
If you don't know how.. Then just tell me or drop the code, I need the mic_on variable with the True or False parameter to be passed from the js code directly to the python file

### Practicalities

- YES/NO I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
It is hard to tell what you are trying to do here without any code

**Comment by Xanderplayz16** [comment]
Your code raised the exception on line 155. Look there, and you can see, it is raising an exception.
