### ISSUE TITLE
[Feature] Message Box function

### ISSUE THREAD

**Issue by divadsn** [r0x0r/pywebview#1379]
### Specification
- pywebview version: 5.1
- operating system: Windows 10
- web renderer: edgechromium

### Description

I have not seen any method to create a message box in pywebview, only some half-baked solutions using Tk, but they don't integrate very well with the window GUI. There was a method in the PR for #949 but it doesn't seem to be in 5.1 anymore 🤔 

JS alert() don't look good on Windows with edgechromium

**Comment by r0x0r** [comment]
it is `create_confirmation_dialog`

**Comment by divadsn** [comment]
Yes but that one creates as the name already tells an Yes/No dialog, I am searching for a method to have an alert/message box with an icon (warning/info/error) and an OK button. `alert()` in JS shows the built-in error which doesn't look good:

![image](https://github.com/r0x0r/pywebview/assets/28547847/e141ce49-5d8d-4bf8-acda-dd37bd288e78)

**Comment by r0x0r** [comment]
There is a custom message box implementation that overwrites `window.alert`, but it is not enabled for EdgeChromium. I will look into this.

**Comment by yllhwa** [comment]
If you only plan to run on Windows, simply use win32 api like this.
```python
import webview
import ctypes


def my_alert(title, text, flags=0x00001030):
    ctypes.windll.user32.MessageBoxW(None, text, title, flags)


window = webview.create_window("Hello world", "https://pywebview.flowrl.com/hello")
window.expose(my_alert)
webview.start(debug=True)

# js: pywebview.api.my_alert("Error", "error while loading")

```
![image](https://github.com/r0x0r/pywebview/assets/42028599/194f26e7-70ca-44e7-ab54-5731908e521d)

**Comment by r0x0r** [comment]
I pushed a fix to master

**Comment by shirooo39** [comment]
so are we now able to create a custom dialog window? because I'm not seeing anything about that on the Examples, guessing it's not yet possible to do.

I don't need to use the confirmation dialog, I just want a simple dialog with a single button that can act as an alert window or whatever it's I want it to be.

**Comment by r0x0r** [comment]
You can use `window.alert("Your message")`. The alert dialog has a custom implementation that creates a native message box.

**Comment by tsiens** [comment]
> 您可以使用 .警报对话框具有创建本机消息框的自定义实现。`window.alert("Your message")`

raceback (most recent call last):
  File "Y:\1.py", line 6, in <module>
    window.alert('1111')
    ^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'alert'

**Comment by r0x0r** [comment]
`window.alert` That's Javascript, not Python.

**Comment by divadsn** [comment]
If you want native message boxes, I have written some code to show those natively on top of the WebView window: https://github.com/divadsn/UBahnSimBerlinInstaller/blob/master/usb_installer/winforms.py
