### ISSUE TITLE
how Intercept and filter files or requests ?

### ISSUE THREAD

**Issue by wall-git** [r0x0r/pywebview#1380]
How to modify the content (encryption and decryption of static files) during HTML file or request loading is similar to the WebResourceRequested event in webview2?

**Comment by Xanderplayz16** [comment]
See issue 1371:

> Currently no, but I have been planning to add editing requests and responses. Help is welcomed.
-r0x0r

**Comment by wall-git** [comment]
thanks , I have seen your reply, and indeed, there is currently no better solution. I have read that the source code file or request loading is implemented internally in webview, and each platform is different. If you want to be compatible with all platforms, it is difficult. It may be fine to implement this feature, but if there are other interfaces to implement, the burden on the author would be too heavy.
    I am wondering if it is possible to implement my own webview interface for a certain platform by opening custom events. Pywebview does not implement specific interfaces, it simply interacts with the customized interface directly, which is written by the user.

**Comment by wall-git** [comment]
thanks , I have seen your reply, and indeed, there is currently no better solution. 

    I have read that the source code file or request loading is implemented internally in webview, and each platform is different.
    If you want to be compatible with all platforms, it is difficult. It may be fine to implement this feature, but if there are other interfaces to implement, the burden on the author would be too heavy.
    I am wondering if it is possible to implement my own webview interface for a certain platform by opening custom events. 
Pywebview does not implement specific interfaces, it simply interacts with the customized interface directly, which is written by the user.
