### ISSUE TITLE
on Windows, create_file_dialog() is not disposing of dialog after ShowDialog()

### ISSUE THREAD

**Issue by pemn** [r0x0r/pywebview#1383]
### Specification
- pywebview version:
1.4.2
- operating system:
Windows 10.0.22000.2899
- web renderer:
webview.platforms.winforms
### Description
When calling any create_file_dialog(), the dialog is not being disposed (`dialog.Dispose()`). So the python process does not finish after the main window is closed. Not even keyboard interrupt (CTRL+C) will terminate the process. Only taskkill is able to kill the python process.
Im not sure if calling `dialog.Dispose()` will be enough to fix the issue, but thats a good start.

images and a minimal test file on the zip:

[test_bug_filedialog.zip](https://github.com/r0x0r/pywebview/files/15313444/test_bug_filedialog.zip)

### Practicalities

- YES/NO I am willing to work on this issue myself.
NO
- YES/NO I am prepared to support this issue financially.
NO

**Comment by r0x0r** [comment]
I ran your example and could not reproduce the problem. If calling `dialog.Dispose()` solves it for you, feel free to submit a PR.
