### ISSUE TITLE
Can't use multiple pywebviews at the same time

### ISSUE THREAD

**Issue by huan1936** [r0x0r/pywebview#1387]
### Specification
- pywebview version:5.1
- operating system:Windows 10
- web renderer:edgechromium

### Description

  Using two python processes
After python process 1 starts pywebview, python process 2 can no longer use pywebview.
A computer can only run one pywebview?

`[pywebview] WebView2 initialization failed with exception:
  (0x8007139F): 组或资源的状态不是执行请求操作的正确状态。 (异常来自 HRESULT:0x8007139F)
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__8.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()
`

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by huan1936** [comment]
It seems because EnsureCoreWebView2Async  never returns

**Comment by huan1936** [comment]
Is it because of this reason?  
Multiple environment objects
[https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2environment?view=webview2-winrt-1.0.2478.35](url)

**Comment by huan1936** [comment]
```
from Microsoft.Web.WebView2.Core import CoreWebView2Environment

class EdgeChrome:
	def __init__(self, form, window, cache_dir):
		# ...

		def _callback(task):
			self.web_view.EnsureCoreWebView2Async(task.Result)

		webView2Environment = CoreWebView2Environment.CreateAsync()
		webView2Environment.ContinueWith(
			Action[Task[CoreWebView2Environment]](_callback),
			self.syncContextTaskScheduler,
		)
		# self.web_view.EnsureCoreWebView2Async(None)
```

**Comment by huan1936** [comment]
I used it this way because I thought pywebview was pretty good, so I planned to build some small tools using pywebview, but in the end I found that these tools couldn't work at the same time, so I looked for the reason why they couldn't be used at the same time.

**Comment by huan1936** [comment]
After testing, private_mode and cookie can work normally.

**Comment by r0x0r** [comment]
@huan1936 feel free to submit a PR
