### ISSUE TITLE
pywebview  headless window like selenium python

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1389]
is it possible @r0x0r

**Comment by r0x0r** [comment]
`webview.create_window(..., hidden=True)` is the closest to headless you can get.

**Comment by MominIqbal-1234** [comment]
thanks  and please tell me can i add the proxy in pywebview @r0x0r

**Comment by r0x0r** [comment]
No, proxy is not implemented, but prozy support could be a nice addition.

**Comment by hasansezertasan** [comment]
> No, proxy is not implemented, but prozy support could be a nice addition. 

Can we use browser extensions with pywebview?

**Comment by r0x0r** [comment]
> > No, proxy is not implemented, but prozy support could be a nice addition.
> 
> Can we use browser extensions with pywebview? If yes, I believe one could use a proxy extension.

No
