### ISSUE TITLE
Allow only certain file extensions in create_file_dialog()

### ISSUE THREAD

**Issue by pomplesiegel** [r0x0r/pywebview#139]
It is often helpful to have only certain file types with certain extensions selectable when performing an `OPEN_DIALOG` with create_file_dialog(). This way, files without this extension are not possibly selectable, and will be greyed out. Is there a cross-platform way to easily do this?

**Comment by shivaprsdv** [comment]
Doable, not necessarily _easy_ though. Good suggestion BTW ✌️

**Comment by pomplesiegel** [comment]
Great. On the mac side I remember the granular calls for this through Swift to the NSOpenPanel() were something like

```swift
        let dialog = NSOpenPanel();
        dialog.title                   = "Select an update file";
        dialog.showsResizeIndicator    = true;
        dialog.showsHiddenFiles        = false;
        dialog.canChooseDirectories    = true;
        dialog.allowsMultipleSelection = false;
        dialog.allowedFileTypes        = [".image"];
```

**Comment by shivaprsdv** [comment]
Yeah, on Cocoa it's single line. Win & QT needs a bit more work, GTK, a little more.

**Comment by r0x0r** [comment]
Let's decide first what format an appropriate parameter to create_file_dialog would look like. 

How do different platforms handle this issue? Windows provides a breakdown for different filetypes (both by individual file extensions and extension groups, eg. *.gif and 'All picture files'). On Mac most apps I have checked do not have an option for file type filter, but instead apply filtering by default by disabling unsupported file types. Chrome's open file dialog, for example, has one, but it has only "All files" option. I don't have access to Linux at the moment, so no comment on that.

Based on that Mac would require a tuple of supported file extensions and Window would require a breakdown for extensions and their descriptions. Maybe something like this would do`file_types=((file_masks, mask_description),)`, where file_masks would be a list extensions separated by a semicolon or a pipe or whatever. E.g. `file_types=(('*.gif|*.jpg|*.jpeg', 'Picture files'), ('*.gif', 'GIF files'), ('*.jpg|*.jpeg', 'JPEG files'))`. The first item could be the default one.

What do you think?

**Comment by r0x0r** [comment]
Update on Linux. GTK is similar to Windows. So OSX is the only that needs a special treatment. `file_types=((file_masks, mask_description),)` could work with the first item being an option selected by default, as well as OSX file mask. Or do it in a more explicit way and introduce a dictionary with keys like `file_mask`, `default_option` or something like that.

**Comment by shivaprsdv** [comment]
QT is similar too. Cocoa could ignore the descriptors; we'd need to do platform
specific formatting in the backend anyway.

**Comment by shivaprsdv** [comment]
I suppose a cleaner interface would be a single tuple of strings; each string
specifying _both_ description and file mask, directly in the Windows format:

`file_types = ('<mask_description> (<file_masks>)', ...)`.
e.g. `file_types = ('Image Files (*.bmp;*.jpg;*.gif)', 'All files (*.*)')`

The first string can be the default. On macOS, we could merge all the given
file masks except the `All files` mask.

**Comment by pomplesiegel** [comment]
That solution sounds fine to me!

**Comment by r0x0r** [comment]
I am reluctant to store data in strings, but seeing as Windows uses exactly the same syntax, this could be a good approach. How does QT and GTK handle this issue?

**Comment by shivaprsdv** [comment]
Qt uses the [same](http://doc.qt.io/qt-5/qfiledialog.html#setNameFilter), with spaces instead semicolons. Makes life easy 😇 
GTK needs adding everything one at a time. See [e.g.](http://www.pygtk.org/pygtk2tutorial/examples/filechooser.py)

**Comment by shivaprsdv** [comment]
We could start working on this now.

**Comment by shivaprsdv** [comment]
I have pushed implementations for Mac and Linux. The interface is based on the
Windows format as I proposed. The open file dialog example is modified to demo
the feature. Testing and suggestions welcome.

**Comment by r0x0r** [comment]
WinForms implementation is done. I have done some refactoring as well.
If you have no objections, we are good to go with a PR.

**Comment by shivaprsdv** [comment]
Almost there. Just need to add feature documentation before merge. 👍

**Comment by r0x0r** [comment]
Merged

**Comment by shivaprsdv** [comment]
A bit late, but I have discovered a way to add a menu to the open dialog on Mac
to choose between multiple filters, similar to that on Windows and Linux:
![screen shot 2017-11-18 at 3 43 26 pm](https://user-images.githubusercontent.com/18247990/32979264-02a3627e-cc78-11e7-900f-ffdc34fb7815.png)
The menu view can be toggled on/off by the `option` button. Currently I have
set it to be visible by default.

I have pushed the commit to `file-filter`. If it is in accord, we could merge.

**Comment by NiceneNerd** [comment]
Could this be added to save dialogs as well?

**Comment by shivaprsd** [comment]
Can you elaborate the rationale / use-case for that?

**Comment by NiceneNerd** [comment]
In many cases a program will only, or ordinarily, be saving to a specific file format, in which case it can be convenient or helpful to end users to have the save dialog restrict the file format or provide specific options. Note that many popular programs already do this (e.g. standard office suites).

**Comment by shirooo39** [comment]
really sorry for bumping old issue instead of opening a new one but, is it possible to allow literally only a certain file types WITHOUT having to define an `All Files (*.*)` filter?
```Python
async def choose_file():
    file_types = ('Image Files (*.bmp;*.jpg;*.jpeg;*.png)', 'Image Files (*.bmp;*.jpg;*.jpeg;*.png)')
    files = await nicegui.app.native.main_window.create_file_dialog(allow_multiple=False, file_types=file_types)

    if files is not None:
        for file in files:
            # ui.notify(f'You picked: {file}')
            textinput.set_value(file)
    else:
        ui.notify('No file selected')
```
my workaround is to just define the same filter twice. while this does work, but it doesn't look good.  
can we just do something like `file_types = ('Image Files (*.bmp;*.jpg;*.jpeg;*.png)')`?
