### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by aes219** [r0x0r/pywebview#1390]
### Specification
- pywebview version: 5.1
- operating system: Ubuntu 24.04 LTS
- web renderer: webkit2gtk-4.1

### Description

I receive the following error when trying to run the [basic setup](https://pywebview.flowrl.com/guide/usage.html#basics) of pywebview. I already have `python3-gi`, `libweb2kitgtk-4.1-0`, `libweb2kitgtk-4.1-dev` and `libweb2kitgtk-4.1` installed. I also have all the other [dependencies](https://pywebview.flowrl.com/guide/installation.html#linux) installed.
```bash
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/media/vaidik/Projects/aegis/.venv/lib/python3.12/site-packages/webview/guilib.py", line 37, in import_gtk
    import webview.platforms.gtk as guilib
  File "/media/vaidik/Projects/aegis/.venv/lib/python3.12/site-packages/webview/platforms/gtk.py", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

```

**Comment by ZhaoZuohong** [comment]
It seems that you are using a virtual environment. Does installing pycairo and PyGObject `pip install pycairo PyGObject` help?

**Comment by aes219** [comment]
> It seems that you are using a virtual environment. Does installing pycairo and PyGObject `pip install pycairo PyGObject` help?

That fixed it! Thanks for the help.
