### ISSUE TITLE
js_bridge_call: use logging instead of print()

### ISSUE THREAD

**Issue by MacMoneysac666** [r0x0r/pywebview#1391]
### Specification
- pywebview version: 5.1
- operating system: Windows
- web renderer: Chromium

### Description

  The function _js_bridge_call_ uses _print()_ if an exception occur:

```
def js_bridge_call(window: Window, func_name: str, param: Any, value_id: str) -> None:
    def _call():
        try:
            result = func(*func_params)
            result = json.dumps(result).replace('\\', '\\\\').replace("'", "\\'")
            code = f'window.pywebview._returnValues["{func_name}"]["{value_id}"] = {{value: \'{result}\'}}'
        except Exception as e:
            print(traceback.format_exc())
            error = {'message': str(e), 'name': type(e).__name__, 'stack': traceback.format_exc()}
            result = json.dumps(error).replace('\\', '\\\\').replace("'", "\\'")
            code = f'window.pywebview._returnValues["{func_name}"]["{value_id}"] = {{isError: true, value: \'{result}\'}}'

    ...
```

Imho, it would be a good idea to use logging instead. User applications in particular can make heavy use of the logging framework.

If the change is not easily possible due to backwards compatibility, it would still be great if it could be configured - e.g. via an environment variable.

I hope I haven't overlooked anything and would like to thank you for this project!

### Practicalities

I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
Good suggestion. I pushed this change to master
