### ISSUE TITLE
[Question] Embedded HTTP server on unix domain socket

### ISSUE THREAD

**Issue by gioboske** [r0x0r/pywebview#1393]
### Specification
- pywebview version: 5.1
- operating system: macOS
- web renderer: WebKit

### Description

Is it possible to configure `pywebview` so to communicate with an HTTP server running over Unix domain socket (instead of specific local port)?
Something similar to send requests with `curl` by using `--unix-socket <path>` option?

Thank you.

**Comment by r0x0r** [comment]
Not really, at least with the current http server implementation.

**Comment by gioboske** [comment]
What a pity! This would be very useful so to run `pywebview` on systems where consuming a local port is not allowed or undesirable.

Any plan to support this feature in the near future?

In any case, thank you for the clarification and for the very useful `pywebview`.

**Comment by r0x0r** [comment]
_pywebview_ uses bottle.py and its dev server for its http server. It may be not the best choice, but it does the job for now. bottle.py's dev server does not support binding to a unix socket. 

You can use a third party http server of your choosing though. Start a server in a thread and point _pywebview's_ url to the entrypoint  provided by the server.

**Comment by gioboske** [comment]
Thank you @r0x0r.
I will do some test using `uvicorn`, that support serving on unix domain socket.

Mi concern is about how to point _pywebview_'s url to the server entrypoint, since the web server would listen on a unix socket and, as far as I know, there is no standard url scheme for unix domain socket.
In fact, similar feature request for Chromium lead to a WONTFIX also for the lack of a standard url scheme. 

I guess supporting unix socket would imply some changes on `pywebview`-side so to proxy all connections to the unix socket.
