### ISSUE TITLE
getting a blank/empty window when trying to open a webpage

### ISSUE THREAD

**Issue by tedmoorman** [r0x0r/pywebview#1396]
### Specification
- pywebview version: 5.1
- operating system: Windows 10
- web renderer: chromium (I think)

### Description

Used example in simple_browser.py and am getting a blank/empty window. Web page appears with QtWebEngine and with webbrowser.  System is an internal network. Glad to try whatever troubleshooting I can on my end.

### Practicalities

- NO, I am willing to work on this issue myself.

- NO, I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Are there any errors?

**Comment by tedmoorman** [comment]
Not getting any errors.
Tried another web address and was asked for login credentials, whereas webbrowser will open a new tab in an existing browser without asking for login credentials. 
The particular site that is blank/empty quickly goes from a white background to a gray background upon closer inspection. Attaching screen shot below.
![pywebview_blank_screen](https://github.com/r0x0r/pywebview/assets/63677618/e45dda85-ec83-4030-82c9-0ecd7fabe219)

**Comment by r0x0r** [comment]
Are you using PyQT? This looks like a known issue, which is solved by disabling sandbox mode in qt.py line 49 for a selected platform.

Other than that, I suggest using Edge Chromium on Windows.

**Comment by r0x0r** [comment]
It is a known QT problem with a fix for selected platforms here. Adding your platform there should help. https://github.com/r0x0r/pywebview/blob/99f18d01434773407cc0d32a01678bbc8ae0034e/webview/platforms/qt.py#L49

I recommend using EdgeChromium webview2 over QT on Windows, though
