### ISSUE TITLE
create_file_dialog() showing anomalous return behaviour

### ISSUE THREAD

**Issue by shivaprsdv** [r0x0r/pywebview#140]
Platform: Lubuntu 17.04 in VirtualBox, Python 2.7.13, pywebview current `master`
Since: Merging PR #121; commit 7c8762b0
Issue: Calling `create_file_dialog()` results in either of the following errors:
```
(open_file_dialog.py:2864): Gdk-ERROR **: The program 'open_file_dialog.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadImplementation (server does not implement operation)'.
  (Details: serial 1424 error_code 17 request_code 20 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```
or
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

At first I thought this should be an issue with GTK on my system (as I am running
it inside VBox). But I found it doesn't happen before 7c8762b0 was applied. Seems
like that commit made `create_file_dialog` non-thread-safe.

I have added a branch with a fix that is working for me. Can you check if this issue
happens elsewhere? If it does, we need to apply the fix before implementing #139.

**Comment by r0x0r** [comment]
The bug occurs here as well (Ubuntu 14.04). I have made some minor changes to your fix and will merge the branch.

**Comment by r0x0r** [comment]
Merged the branch

**Comment by shivaprsdv** [comment]
Sorry for the late response. I delayed the merge because the changes you made
had one minor side effect. I have [the fix](https://github.com/r0x0r/pywebview/commit/00d4745ba1d28ccaa059ef1bc10905a8cf624903) now.

Also `create_file_dialog` has anomalous return behaviour on Qt5 as well. I believe
it is supposed to return a tuple in all cases, but it returns variously a list, a tuple or a
string, and never `None`, even if the dialog is cancelled. I've fixed it, don't know if it
would break Qt4; was it working properly on Qt4 before? And what about Windows?
On Cocoa it works perfectly.

Now that you have merged the Gtk branch, I shall create a [new branch](https://github.com/r0x0r/pywebview/tree/file-dialog-fix) with the fixes.

**Comment by r0x0r** [comment]
PyQT4 implementation is broken, individual chracsters as QStrings are returned. I have made a fix, will push it, as soon as I test it with PyQT5

**Comment by shivaprsdv** [comment]
Thought so. It's working with PyQt5, I've checked. I suggest you add a version
check to run the appropriate implementation.

**Comment by r0x0r** [comment]
Fix pushed. I will merge the branch.

**Comment by shivaprsdv** [comment]
I have made a small correction for Qt5. Shouldn't affect Qt4, but we might want
to make sure. Is there anything to be done on Winforms?
