### ISSUE TITLE
'WebView' object has no attribute 'evaluate_javascript'

### ISSUE THREAD

**Issue by ppaaccoo** [r0x0r/pywebview#1401]
### Specification
- pywebview version: 5.1 (webview version 0.1.5)
- operating system: Linux Mint 20.3
- web renderer: gtk? (no idea, to be honest)
- python version: 3.8.10

### Description

When I run this code (or any other code that uses webview or pywebview):

import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()

I obtain this error:

File "/home/asaselo/.local/lib/python3.8/site-packages/webview/platforms/gtk.py", line 335, in on_navigation
    if decision.get_navigation_action().get_frame_name() == '_blank':
AttributeError: 'NavigationAction' object has no attribute 'get_frame_name'
Traceback (most recent call last):
  File "/home/asaselo/.local/lib/python3.8/site-packages/webview/platforms/gtk.py", line 303, in on_load_finish
    webview.evaluate_javascript(
AttributeError: 'WebView' object has no attribute 'evaluate_javascript'

I am a newbie both on coding and linux, so I'm very open to have missed this very same problem on other issue (I've tried to find it) or to be doing something very stupid myself that creates this problem. My conclusion is that it has something to do with being on linux, but I don't know how to solve it.

Thanks in advance for your attention.

**Comment by Xanderplayz16** [comment]
Try replacing `webview.start()` with `webview.start(gui="qt"`. This will force pywebview to use QT instead of GTK. You do need to install the dependencies, it says them on the docs.
