### ISSUE TITLE
Problems with pyinstaller packaging

### ISSUE THREAD

**Issue by 2622594863** [r0x0r/pywebview#1402]
### Specification
- pywebview version:5.1
- operating system:windows 10
- web renderer:

### Description

`window = webview.create_window('FastAPI', url='./page.html', js_api=Api())
webview.start(custom_logic, window)`

I like this project very much, and I can make python use the front end to write a very beautiful interface, but now I have a problem, I use the debugging state when everything is normal, but I want to use the pyinstaller package this program into an exe to send to my friends to use, open the exe will prompt 404 can not find the page, I have packed my html file and static folder into it, but I can't. Is there any solution
![a1](https://github.com/r0x0r/pywebview/assets/65318836/0c16391b-9045-4fd5-946b-341c2e89f0f9)
![2](https://github.com/r0x0r/pywebview/assets/65318836/ad6ff27a-0e91-4a71-9982-d1f8d4b07c9a)

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by 2622594863** [comment]
Or is there an official recommended packaging solution where I have multiple html files and a static folder

**Comment by 2622594863** [comment]
I have solved this problem, but there is something wrong with the way I pack. May I ask how to make the window rounded

**Comment by MominIqbal-1234** [comment]
you can use the http server i think better way to solve this problem 
https://pywebview.flowrl.com/guide/usage.html#communication-between-javascript-and-python
