### ISSUE TITLE
pywebview's `js_api` option fails to register a class method with an argument named `function`

### ISSUE THREAD

**Issue by IsaiahCoroama** [r0x0r/pywebview#1405]
### Prologue
This issue aims to assist others who may encounter the same problem in the future. I struggled with this for a while, and I want to help anyone else who might face this issue.

### Specification
- pywebview version: 5.1
- operating system: Windows 11 (amd64)
- web renderer: Winforms
- python version: 3.12.3

### Description
When creating a `js_api` class object, if a method has an argument named `function`, it causes `pywebview` to not register the method with JavaScript.

**Broken Test Case**
``` python
import webview

HTML_TEMPLATE = f"""
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <button onclick="alert(Object.getOwnPropertyNames(pywebview.api))">View Registered Objects</button>
    </body>
</html>
"""

class WebviewApi:
    def my_method1(self):
        pass

    def my_method2(self, function):
        pass

def main():
    webview.create_window("Demo", html=HTML_TEMPLATE, js_api=WebviewApi())
    webview.start()

if __name__ == "__main__":
    main()
```

**Output**
![image](https://github.com/r0x0r/pywebview/assets/167656806/5c609428-309c-4426-bd86-0660d59196f4)

**Working Test Case**
``` python
import webview

HTML_TEMPLATE = f"""
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <button onclick="alert(Object.getOwnPropertyNames(pywebview.api))">View Registered Objects</button>
    </body>
</html>
"""

class WebviewApi:
    def my_method1(self):
        pass

    def my_method2(self, func):
        pass

def main():
    webview.create_window("Demo", html=HTML_TEMPLATE, js_api=WebviewApi())
    webview.start()

if __name__ == "__main__":
    main()
```

**Output**
![image](https://github.com/r0x0r/pywebview/assets/167656806/14712b9c-ef4b-4c81-818d-970c84cb1123)

### Practicalities

- No I am not willing to work on this issue myself.

- No I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
That's an interesting bug that flew under the radars for years. I pushed a fix to the master.
