### ISSUE TITLE
open multiple sites in same pywebview window 

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1409]
![Screenshot from 2024-06-14 10-25-04](https://github.com/r0x0r/pywebview/assets/61788052/9307db91-ab4d-473a-8c3c-50d3710174dd)

this example in arc browser but
its possible in pywebview window 
open multiple site in the same window

**Comment by r0x0r** [comment]
No multiview is not supported. You can try to emulate it with iframes if target sites CSP allows it.

**Comment by MominIqbal-1234** [comment]
thansk so much but iframe is biggest problem every site is not support
