### ISSUE TITLE
Django and pywebview issue

### ISSUE THREAD

**Issue by kwstaskara** [r0x0r/pywebview#141]
Hello i managed to make pywebview  to start  whenever i start my local server in django
But pywebview runs first and of course local server will not run because pywebview occupies terminal...
Pywebview runs as it should and after closing webview runserver executes normally.
Can i make pywebview to work more transparent and  let terminal free after execution?

**Comment by shivaprsdv** [comment]
Unfortunately this is not exactly possible the way you want. pywebview _should_
run on the main thread and it _will_ block execution and 'occupy terminal'. But you
can get around this easily by creating a thread and running your server on it. e.g.
```py
import threading

def run_server():
    # code to start your server
    ...

t = threading.Thread(target = run_server)
t.start()

create_window('My title', 'My url')
```
For more info see the examples the `examples` directory of the repo. 🙂

**Comment by kwstaskara** [comment]
Worked great! thank you!

**Comment by shivaprsdv** [comment]
Great! Feel free to showcase your apps, we have a small [gallery](https://github.com/r0x0r/pywebview#gallery). :)

Happy to help. I am closing this.
