### ISSUE TITLE
how can I reander gui after html loading is completed ?

### ISSUE THREAD

**Issue by Dumbliidore** [r0x0r/pywebview#1410]
### Specification
- pywebview version: 5.1
- operating system: Win11
- web renderer: chromium

### Description
I use pywebview to encapsulate flask app, when I run the code， the gui be rendered is always before html loading is completed，this led to a blank interface for a while.

Before html loading is completed.
![image](https://github.com/r0x0r/pywebview/assets/35067857/0f7cedc9-dad7-4f3e-a786-3de14c045ed1)

After html loading is completed.
![image](https://github.com/r0x0r/pywebview/assets/35067857/38b37410-27ec-444c-b380-54c7ee0cf955)

Thanks.

**Comment by r0x0r** [comment]
There is a loading animation example to address cases like this https://github.com/r0x0r/pywebview/blob/master/examples/loading_animation.py

**Comment by Dumbliidore** [comment]
Thanks, it works for me.
