### ISSUE TITLE
How to replace the icon in the top left corner?

### ISSUE THREAD

**Issue by plane55** [r0x0r/pywebview#1411]
### Specification
- pywebview version: 4.4.1
- operating system: windows 10
- web renderer: 

### Description

  How to replace the icon in the top left corner?

### Practicalities
![Snipaste_2024-06-15_14-30-15](https://github.com/r0x0r/pywebview/assets/41913958/7fcf6de5-5c5d-4e12-981c-10cd041a49d7)

**Comment by r0x0r** [comment]
_pywebview_  extracts and displays application icon from the executable. In other words you specify the application icon via a bundler.

**Comment by Cqy11223344** [comment]
Webview. start (gui='qt '), when the gui is configured as qt, the correct icon cannot be displayed. If it is cef or other parameters, it is normal

**Comment by Cqy11223344** [comment]
![Uploading QQ五笔截图未命名.png…]()

**Comment by r0x0r** [comment]
@Cqy11223344 Do you get this behaviour when application is frozen? The icon support comes only with frozen apps.

**Comment by GbSeason** [comment]
This is my solution. Firstly, this library uses native window handles in the Windows system, so you need to consult the. NET documentation to find the loading method for window icons. Fortunately, there is just a method to load ICO files based on the path.

![image](https://github.com/user-attachments/assets/0fa5d44d-d85f-41ba-882c-ef8ae908dbc1)

At this point, you need to make slight changes to the source code by adding the path attribute of the ICO file to the custom window object, and adding code to specify the window icon when creating the window

![image](https://github.com/user-attachments/assets/c7b0b315-c072-4eee-a145-fe3fcd4ecd38)

![image](https://github.com/user-attachments/assets/01db6499-ffa6-4e9b-9fda-0a569ac73749)

![image](https://github.com/user-attachments/assets/11127a6d-e5ad-44ba-9313-6dcfcb14ebb1)

![image](https://github.com/user-attachments/assets/77c0ee66-ea97-446b-abf8-980f828f1e40)

Create a webview and set 'icon_path'.

`webview.create_window('Hello world', html="<div></div>", icon_path=f"{img}/favicon_play.ico")`

Now the icon is changed.

![image](https://github.com/user-attachments/assets/b23d0fd4-2de4-48fc-b13a-e98ba74cc240)

**Comment by Cqy11223344** [comment]
I tried to modify it using the above method, but it still doesn't work. You can try calling it using the following method.
webview.start(gui='qt')

> This is my solution. Firstly, this library uses native window handles in the Windows system, so you need to consult the. NET documentation to find the loading method for window icons. Fortunately, there is just a method to load ICO files based on the path.
> 
> ![image](https://private-user-images.githubusercontent.com/169735452/357258289-0fa5d44d-d85f-41ba-882c-ef8ae908dbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk3MTcsIm5iZiI6MTcyMzU1OTQxNywicGF0aCI6Ii8xNjk3MzU0NTIvMzU3MjU4Mjg5LTBmYTVkNDRkLWQ4NWYtNDFiYS04ODJjLWVmOGFlOTA4ZGJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjhjYjY1ZmZhODU1NzgxMTc5NjRlZTUzMDIzOGE4NzZhZTFjOWJkZmEzZWJhZWFiNTdkOTMzNDE0YjUwMTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aki6w47nUyqS25oOvLOAMv3TM7N9rNRsmYePkUbEwfs)
> 
> At this point, you need to make slight changes to the source code by adding the path attribute of the ICO file to the custom window object, and adding code to specify the window icon when creating the window
> 
> ![image](https://private-user-images.githubusercontent.com/169735452/357259019-c7b0b315-c072-4eee-a145-fe3fcd4ecd38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk3MTcsIm5iZiI6MTcyMzU1OTQxNywicGF0aCI6Ii8xNjk3MzU0NTIvMzU3MjU5MDE5LWM3YjBiMzE1LWMwNzItNGVlZS1hMTQ1LWZlM2ZjZDRlY2QzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzlkNjE0NzViZjZiOGY4M2ZmZDdjNzZhNTc0ZmExZjNkNzU3MWFhMTgyMDBiOThjNGM5MGQ3YWUyMmEzMWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dtPQb33SN2X4jLkFAmKWNv69T-OR6UC1iYC839V7Oww)
> 
> ![image](https://private-user-images.githubusercontent.com/169735452/357259284-01db6499-ffa6-4e9b-9fda-0a569ac73749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk3MTcsIm5iZiI6MTcyMzU1OTQxNywicGF0aCI6Ii8xNjk3MzU0NTIvMzU3MjU5Mjg0LTAxZGI2NDk5LWZmYTYtNGU5Yi05ZmRhLTBhNTY5YWM3Mzc0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGE3OTU5ZTgxNWE1MTM0OTJlYjIzMGMyMWQ4YzRmZjg0YjVhYjNiODU3M2Y2YTY3OTUwMmZmNmI4MTZjYjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.taYzcmalxDzCPu0436DyudPAOXsw_XeYgYgkgLYO_Xw)
> 
> ![image](https://private-user-images.githubusercontent.com/169735452/357259356-11127a6d-e5ad-44ba-9313-6dcfcb14ebb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk3MTcsIm5iZiI6MTcyMzU1OTQxNywicGF0aCI6Ii8xNjk3MzU0NTIvMzU3MjU5MzU2LTExMTI3YTZkLWU1YWQtNDRiYS05MzEzLTZkY2ZjYjE0ZWJiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTBjOTcxMTM5YzhhNTcyODU5ZmVmMWUyNzYyM2ZjYzAwMzcxOWQ3MWUzYjkwYjg4MjBlNTJkYWFhYzczN2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ahpOz5nWJvv5AgdzzvHP_sQ7Fs8atTWAaKYob0YGRiQ)
> 
> ![image](https://private-user-images.githubusercontent.com/169735452/357259518-77c0ee66-ea97-446b-abf8-980f828f1e40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk3MTcsIm5iZiI6MTcyMzU1OTQxNywicGF0aCI6Ii8xNjk3MzU0NTIvMzU3MjU5NTE4LTc3YzBlZTY2LWVhOTctNDQ2Yi1hYmY4LTk4MGY4MjhmMWU0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWM0NDM5M2I3NmY0NmJhMmRjZTVkMGQ2MThlYTYyMDk3N2Y4ZjFkZGRlNjlmODExYTdmY2U1NzcwNjU3MjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U9kNnCOg1Qgi-HF8jDU4_z8XMBpuSc4NF1qr58HWPF8)
> 
> Create a webview and set 'icon_path'.
> 
> `webview.create_window('Hello world', html="<div></div>", icon_path=f"{img}/favicon_play.ico")`
> 
> Now the icon has changed.
> 
> ![image](https://private-user-images.githubusercontent.com/169735452/357260310-b23d0fd4-2de4-48fc-b13a-e98ba74cc240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk3MTcsIm5iZiI6MTcyMzU1OTQxNywicGF0aCI6Ii8xNjk3MzU0NTIvMzU3MjYwMzEwLWIyM2QwZmQ0LTJkZTQtNDhmYy1iMTNhLWU5OGJhNzRjYzI0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTY3NThlYTg2YWIxNDkzODFlZTgwMDgwNDVjMDk5ODczZTkxY2ZhOWQxOGVjY2YwYWZmYTQzYzE2Y2Q1YWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.czZEkRq5szs3f8S6PvX6nu8wk-56Oj6yf0ICBDpR7Ug)

I tried to modify it using the above method, but it still doesn't work. You can try calling it using the following method.
webview.start(gui='qt')

**Comment by GbSeason** [comment]
> I tried to modify it using the above method, but it still doesn't work. You can try calling it using the following method. webview.start(gui='qt')
======================================
The 'icon_path' variable needs to be declared in the 'create_window' method,otherwise, an error will be reported,
probably at line 246 of the file 'webview/__init__. py', insert codes declaring variables  'icon_path'  like this 'icon_path:str|None=None' .

**Comment by r0x0r** [comment]
I have added `windows.start(icon=<path_to_icon>)` to address QT and partly GTK. The icon is not displayed on Wayland, as you are supposed to specify application icon using other means.

As for other platforms (Window, macOS, Android) icon must be specified when freezing.

**Comment by paco-sevilla** [comment]
Since [release 6.2](https://github.com/r0x0r/pywebview/releases/tag/6.2) it is possible to set an icon with `webview.start(icon=<file_path>)` on Windows and Mac, as well.
The file has to be `*.ico` on Windows and on a `*.icns` on Mac.
See #1755 and #1757.

However, providing an icon during freezing is still the preferred way. See https://github.com/r0x0r/pywebview/pull/1665#issuecomment-3015063983
