### ISSUE TITLE
Using windll.gdi32.CreateRoundRectRgn to set round corner makes the window have a white frame

### ISSUE THREAD

**Issue by mimi99528** [r0x0r/pywebview#1413]
### Specification
- pywebview version:5.1
- operating system:Windows10
- web renderer:Chromium

### Description

......
# 定义一些Windows API函数和常量
user32 = windll.user32
gdi32 = windll.gdi32

def set_window_region(hwnd, radius):
    rect = win32gui.GetWindowRect(hwnd)
    width = rect[2] - rect[0]
    height = rect[3] - rect[1]
    hRgn = windll.gdi32.CreateRoundRectRgn(0, 0, width + 1, height + 1, radius, radius)
    if hRgn != 0:
        windll.user32.SetWindowRgn(hwnd, hRgn, True)
        windll.gdi32.DeleteObject(hRgn)

......

if __name__ == '__main__':
    api = API()
    window = webview.create_window('JS API example',
                                   html=custom_titlebar_html,
                                   js_api=api,
                                   frameless=True,
                                   background_color='#000000')

    time.sleep(1)

    webview.start(func=on_window_loaded)

The code makes the window have a white frame, like below:

![{~UMBAY%QX(O}LD{@MJ{D4C](https://github.com/r0x0r/pywebview/assets/111690846/0464cfd5-aca9-4d74-ad35-49ef986e8167)

### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You can probably hide the window border in a similar manner using win32.
