### ISSUE TITLE
Different menus for different windows?

### ISSUE THREAD

**Issue by SublunarSage** [r0x0r/pywebview#1414]
### Specification
- pywebview version:5.1
- operating system:Windows 10
- web renderer:default

### Description

Good evening! I recently discovered your library and am very much enjoying using it so far, but I had a question regarding its functionality: is it possible to have different menus for different windows (I.E, one window could have 3 different menu items, another window could have 1 menu item, and a third window could no menu), or is that not implemented yet? I ask because I want to see whether or not it's possible to do in the program first before doing a more manual solution using frameless windows.

Thank you for your assistance!

### Practicalities

- **YES**/NO I am willing to work on this issue myself.

- YES/**NO** I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Window specific menus have never been done, but it should be added. The api could be the same with an exception that menu would be given to `create_window` instead of `start`. If both are supplied, window specific menu would overwrite the global menu. 
Feel free to work on this.

**Comment by SublunarSage** [comment]
Hi there! Thanks for the super quick response. I'll be honest and say that I'm still pretty new to programming, so after looking through the code on adding different menus to different windows, I'm honestly not sure where to start. ^^;
I know it's rather frustrating to have someone say they'll do something but then doesn't, but if it's any consolation, I could try and see if I could provide some monetary funds to see this feature be added.

**Comment by garyganyang** [comment]
i got a way to do so. use the following to create your second window, it works

`    webview.guilib.set_app_menu([])
    window2 = webview.create_window(
        '关于', url=url,
        easy_drag=False,
        width=400, height=300`

**Comment by cjb1234567** [comment]
> i got a way to do so. use the following to create your second window, it works
> 
> `webview.guilib.set_app_menu([])` `window2 = webview.create_window(` ` '关于', url=url,` ` easy_drag=False,` ` width=400, height=300)`

Niu bi!
