### ISSUE TITLE
how to overlay on top of  the webview or make the webview and kivy main window one.

### ISSUE THREAD

**Issue by onsosb** [r0x0r/pywebview#1418]
### Specification
Package             Version
------------------- ---------
bottle              0.12.25
certifi             2024.6.2
charset-normalizer  3.3.2
docutils            0.21.2
idna                3.7
Kivy                2.3.0
Kivy-Garden         0.1.5
kivy-garden.xcamera 2020.613
numpy               2.0.0
opencv-python       4.10.0.84
packaging           24.1
pillow              10.3.0
pip                 24.0
proxy_tools         0.1.0
pycairo             1.26.0
Pygments            2.18.0
PyGObject           3.48.2
PyQt5               5.15.10
PyQt5-Qt5           5.15.2
PyQt5-sip           12.13.0
PyQtWebEngine       5.15.6
PyQtWebEngine-Qt5   5.15.2
pywebview           5.1
QtPy                2.4.1
requests            2.32.3
typing_extensions   4.12.2
urllib3             2.2.2
xcamera             2020.613

### Description

 I have a complete JS based package that  I need to make a desktop application with some extension.  pywebview can run the package without problem, I can deal with events and Dom through pywebview features perfectly, the problem I have i s I have add  some python code to show up a tooltip when some text is selected in pywebview,  the tool tip does not appear in pywebview, but behind it on kivy window is there any way the I can resolve this issue.  Thanks

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I don't understand what your problem is. What platform are you using?

**Comment by onsosb** [comment]
> I don't understand what your problem is. What platform are you using?
Sorry, I try to explain it better.  There is an epub reader package in JS, that I would like to run it as a desktop app on linux with extended functionality to use some python linguistic tools.   Basically what I want is when a text is  being selected a tooltip shows up and based on  the option chosen from the tooltip, a  python  function is called  and displays the result on top or bottom of the selected text or in a new window depending on the context.  
What happens is I am able to catch the evens and popup the tooltip, but the tooltip does not appear on the window created by pywebview, but it remains hidden and when I close pywebview, it show it on kivy default window.
My questionis/was how can I make it to appear on the pywebviw window where the text is selected from. text.
Here is the  test program that I have.  Also, I could not map the js in the program to a pytton style based on your examples!
And many thanks for yourhelp

[readerJun24V4.py.tar.gz](https://github.com/user-attachments/files/15984395/readerJun24V4.py.tar.gz)

**Comment by r0x0r** [comment]
_pywebview_ is not designed to be used in this way. Sorry I cannot help you with kivy related questions
