### ISSUE TITLE
Frameless Window Broken AF

### ISSUE THREAD

**Issue by MonaChanDev** [r0x0r/pywebview#1420]
### Specification
- pywebview version: 5.1
- operating system: Windows 10 - 64bit
- web renderer: default one on Win 10 (gui= not setted)

### Description

I am trying to break away from Tauri and Electron, trying flask + pywebview. I am making a custom window, with custom title bar that integrates classic windows controls. The problem is that the frameless window doesn't work properly, maximize makes the app fullscreen and the window animations simply don't work, and from the taskbar you can't take advantage of the classic window functions...

To replicate everything, just try calling the maximize() and minimize() functions on the frameless window and also see the behavior on the taskbar...

In the meantime, do you recommend another alternative?

### Practicalities

- NO I am willing to work on this issue myself (sadly 😢).
- NO I am not prepared to support this issue financially (sadly x2 😢).

**Comment by Xanderplayz16** [comment]
> maximize makes the app fullscreen
That's intended behavior. Maximize should make the app fullscreen.

**Comment by MonaChanDev** [comment]
I don't think so, since the same command on a bordered window does the same thing as the Windows maximize button, also doing the animation...
Furthermore, I don't know what kind of contribution you thought you were bringing to the issue with this answer :/

**Comment by r0x0r** [comment]
While it has never been spec'd, I agree with @Xanderplayz16 that maximized state of frameless window is fullscreen.
What is your proposal?
