### ISSUE TITLE
storage_path doesn't seem to work

### ISSUE THREAD

**Issue by User-Clb** [r0x0r/pywebview#1421]
### Specification
- pywebview version:5.1
- operating system:Windows 10
- web renderer:default

### Description

 private_mode=False,storage_path="xx" is set, but it doesn't seem to work, and I don't see any files in the directory I set

**Comment by r0x0r** [comment]
Cannot reproduced this with `examples/cookies.py` and set `storage_path`. Are you using EdgeChromium?

**Comment by User-Clb** [comment]
> 无法用 和 设置 重现此内容。您使用的是 EdgeChromium 吗？`examples/cookies.py``storage_path`
I just followed the default set by the docs. No change in expensive: 
window = webview.create_window('Woah dude!', 'https://xxxxx')
webview.start(private_mode=False,storage_path="./xxxx")

The directory is indeed created, but there is no content.

**Comment by User-Clb** [comment]
> 无法用 和 设置 重现此内容。您使用的是 EdgeChromium 吗？`examples/cookies.py``storage_path`

I just followed the defaults set by the docs：
window = webview.create_window（'Woah dude！'， 'https://xxxxx/'）
webview.start（private_mode=False，storage_path=“./xxxx”）

The directory is indeed created, but there is no content.

**Comment by User-Clb** [comment]
> Cannot reproduced this with `examples/cookies.py` and set `storage_path`. Are you using EdgeChromium?

I just followed the defaults set by the docs：
window = webview.create_window（'Woah dude！'， '[https://xxxxx/'）](https://xxxxx/'%EF%BC%89)
webview.start（private_mode=False，storage_path=“./xxxx”）

The directory is indeed created, but there is no content.

**Comment by r0x0r** [comment]
Are you using Edge Chromium? Start in debug mode and see what renderer is used.
