### ISSUE TITLE
Some computers cannot start pywebview properly

### ISSUE THREAD

**Issue by Cqy11223344** [r0x0r/pywebview#1422]
webview.start(debug=True, http_port=39878, gui='qt')， I can open the window interface normally in PyCharm, and the normal output log is
[pywebview] Using Qt 5.15.2
Bottle v0.12.25 server starting up (using ThreadedAdapter())...
Listening on  http://127.0.0.1:39878/
Hit Ctrl-C to quit.
DevTools listening on ws://127.0.0.1:8228/devtools/browser/356109e9-d0a6-43d5-a46f-143e466f3854
After using pyinstaller to package into exe, pywebivew cannot be launched. The output log only has [pywebview] Using Qt 5.15.2
Missing a lot of logs and no additional errors

**Comment by r0x0r** [comment]
What do you mean by failing to start? Do you get a blank screen?

**Comment by Cqy11223344** [comment]
The window cannot be opened at all, and the HTTP process has not started. The key is that there are no error logs.
