### ISSUE TITLE
Is there a way to hide this

### ISSUE THREAD

**Issue by bailaoshijiadao** [r0x0r/pywebview#1426]
### Specification
- pywebview version:
- operating system:
- web renderer:

### Description

  Describe your issue in details. Provide a stand-alone code example that would demonstrate the problem.

### Practicalities

- NO I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

They can get the HTML source code through this.

![QQ图片20240702110547](https://github.com/r0x0r/pywebview/assets/47207238/b01e6478-e607-48a9-9f57-7625b54c5db9)

**Comment by Xanderplayz16** [comment]
No, unless you load the HTML in manually. If you store any secrets in the Javascript, instead put those in the Python code a and make a function that does whatever you do with the secrets, and then compile the Python script. You could even encrypt the secrets and decode them at runtime, so it doesn't appear like anything if you use strings (unix command).
