### ISSUE TITLE
How can I set the background color of the header in macOS?

### ISSUE THREAD

**Issue by pengRW** [r0x0r/pywebview#1427]
### Specification
- pywebview version: 5.1
- operating system:  macos 10.15.7
- web renderer:

### Description

  Hello, I have reviewed the documentation but couldn't find a solution. I don't know how to proceed. 

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by pengRW** [comment]
![Uploading 3839825541.png…]()

**Comment by pengRW** [comment]
![3839825541](https://github.com/r0x0r/pywebview/assets/126999769/2f15350e-695f-47ca-b64e-f18d2a485f12)

**Comment by r0x0r** [comment]
You cannot. What you can do, make window frameless and implement your own header.

**Comment by pengRW** [comment]
Got it, thanks.
