### ISSUE TITLE
Application sometimes doesn't launch

### ISSUE THREAD

**Issue by TailyFair** [r0x0r/pywebview#143]
Enviroment
* windows 10 x64
* pywebview: 1.7
* flask: 0.12.2

Application not always launches, it just freezes on flask init. After few times closing and relaunching, application finally launches successfully (I wait about 10-20 seconds before closing and relaunching).

Console logs:
```
C:\Users\Karolis\Desktop\ajax test>python main.py
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

C:\Users\Karolis\Desktop\ajax test>python main.py
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

C:\Users\Karolis\Desktop\ajax test>python main.py
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

C:\Users\Karolis\Desktop\ajax test>python main.py
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
hi
INFO:werkzeug:127.0.0.1 - - [26/Oct/2017 21:01:32] "GET / HTTP/1.1" 200 -
```

I couldn't find how to run in debug mode. If you could help me with that, I would give more details.

**Comment by r0x0r** [comment]
Sounds like a threading issue. Can you run the provided flask example?

**Comment by TailyFair** [comment]
It was same snippet as in https://github.com/r0x0r/pywebview/issues/145 which you suggested was concurrency.

I rewrote this snippet in example project provided in repository. Now both issues seem to be gone.

I should have given more attention to already provided example.
Will now try to adapt my project to this kind of structure.

Thank you for very fast reply. Also great project.
