### ISSUE TITLE
ability to return binary data to frontend

### ISSUE THREAD

**Issue by AnupamKris** [r0x0r/pywebview#1430]
### Specification
- pywebview version: 5.1
- operating system: Ubuntu 24.04
- web renderer: Gtk

### Description

Is it possible to return a binary data as such to frontend rather than converting it into a string and parsing in js?

### Practicalities

- NO - I am willing to work on this issue myself.

- NO - I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You may serve binary data using a custom http server.
Data passed between frontend and backend using js api is serialised using JSON. Encoding binary as base64 or such is one option, but it is probably not suitable for serving large amounts of data.

**Comment by AnupamKris** [comment]
But can I use the custom http server the same way as exposing functions or should I use fetch or axios to use it?

**Comment by r0x0r** [comment]
You can use js api with an external http server, but you would need to fetch binary data exposed by http server using rest api.
