### ISSUE TITLE
[URGENT] A ticking sound happens when clicking on keyboard keys!

### ISSUE THREAD

**Issue by D3vMohab** [r0x0r/pywebview#1431]
JS CODE: 
```
document.onkeypress = function (e) {
    e = e || window.event;
    // use e.keyCode
};

```

CSS:

```
overflow: hidden;
```
Pywebview code:
```
webview.create_window("TITLE","http://localhost:3000")
webview.start()
```

A ticking sound happens in macOS when clicking a any keyboard key
When removing the css, the ticking sound stops, but I want to make the page non scrollable!

**Comment by r0x0r** [comment]
Have you tried catching and preventing onKey event on the upper level?
