### ISSUE TITLE
DIfferent min working area sizes being set using min_size on different OS

### ISSUE THREAD

**Issue by Igazii** [r0x0r/pywebview#1432]
### Specification
- pywebview version: 5.1
- operating system: win11, macos 14.4.1, ubuntu 22.04
- web renderer: qt, cocoa, winforms (edgechromium)

### Description
Hello, I'd like to highlight the moment (peculiarity of each os and render), i have such example:

```
import webview
webview.create_window('Hello world', 'https://www.google.com', min_size=(600, 600))
webview.start(debug=True)
```

So i expected min_size to work the same way on different platforms but it behaves different on darwin, win and *nix systems:
For Mac and Win it sets the full size of the window including toolbar (and borders on win)
The actual sizes of working areas are following for the case 600 x 600: 

600 x 572 for Mac:
![mac](https://github.com/user-attachments/assets/6727f303-4f98-463a-8375-2356c80db991)

578 x 544 for Win:
![win](https://github.com/user-attachments/assets/c282f63d-252a-4460-9f4e-23afe8d3b5f3)

600 x 600 for Ubuntu (The best working option in my opinion because i expect it to set the actual size of working area):

![lin](https://github.com/user-attachments/assets/7bea8ba8-4733-4d7d-93ff-91769477b735)

So what do you think about it? Should it be viewed as bug? May be this would be a great idea to implement smth to control client area? Or treat it as a "working area" adding fixes for mac and win? 

For win i was able to set desired area (600 x 600) using this snippet (default winforms API doesn't provide method for setting min client area (https://stackoverflow.com/questions/59795639/create-form-minimumclientsize-property)):

```
    class BrowserForm(WinForms.Form):
        def __init__(self, window, cache_dir):
              ...
              height_diff = self.Height - self.get_ClientSize().Height
              width_diff = self.Width - self.get_ClientSize().Width
              min_size = (window.min_size[0] + width_diff, window.min_size[1] + height_diff)
              self.MinimumSize = Size(*min_size)
              ...
```

for mac:

```
    class BrowserView:
        def __init__(self, window):
            ...
            titlebar_height = int(self.window.titlebarHeight())
            self.window.setMinSize_(AppKit.NSSize(window.min_size[0], window.min_size[1] + titlebar_height))
            ...
```

May be it will make any sense to add WebView Window methods to access titlebar height etc (also borders for win).

Thank you, for such a great library, feel free to ask more about details :)

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry for a late response.
I have been thinking about this issue and client area sounds like a good solution to me. As each platform has its their unique window titlebar and chrome design, there is no way to set client size with window size alone.  `create_window` could have `client_size` or like. Open questions are
a) How it would relate to window_size and min_size
b) whether min client size needs to be introduced as well
