### ISSUE TITLE
on_loaded() missing 1 required positional argument: 'window'

### ISSUE THREAD

**Issue by 001-person** [r0x0r/pywebview#1435]
### Specification
- pywebview version: 4.1
- operating system: win11
- web renderer: edge

### Description

  As shown in the screenshot, after discovering the issue, I tried the webview.event example again, but the on_loaded function still couldn't obtain the window object. please take a look at what's going on?
![屏幕截图 2024-07-15 013853](https://github.com/user-attachments/assets/3aab4a70-8e6e-47f9-bcb6-b2d5399cce56)

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Support for window param in event handlers was introduced in 5.1
