### ISSUE TITLE
native splash screen before loading a page completely

### ISSUE THREAD

**Issue by bin-san** [r0x0r/pywebview#1438]
### Specification
- pywebview version: latest as of today
- operating system: ubuntu24.04
- web renderer: webkitgtk

### Description

Is there a way to achieve "native" splashscreen or loading screen before the page completely loads? I know there exists a solution from html side that obviously would not work for websites that are not modified that way... 

Thats it. no control over html. Still want to show splashscreen before the page loads completely.

I have seen in discussions 7years ago about implementing this native feature... Is it complete?or discarded?

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by bin-san** [comment]
Is there any window.events.loading like there is a window.events.loaded? This would help when the window starting to change its url

**Comment by r0x0r** [comment]
There are no plans to add a splash screen support. While I have nothing against it, the implementation looks like a feature creep. Different image formats, animations support (for loading spinners), videos etc.

There is no loading event, but it could be added.
