### ISSUE TITLE
javascript command 'confirm()' returns False immediately (Mac)

### ISSUE THREAD

**Issue by pomplesiegel** [r0x0r/pywebview#144]
Using the master branch on mac (Cocoa) merged with the dev tools branch, calling confirm like
```js
confirm("Press a button!");
```
through `webview.evaluate_js()` instantly returns boolean False, and never shows the window. Strangely, `alert()` and `prompt()` do work. The text for prompt is cut off, but that's another matter. 

Any idea why this is the case and if there's any quick fix? 

With dev tools enabled, if I do the same command in the console, it has the same behavior (returning instantly with the value 'false'). Are we accidentally overriding the confirm() command? 
![image](https://user-images.githubusercontent.com/1450352/32070883-a58587d0-ba5b-11e7-877d-9a4ba294e506.png)

**Comment by shivaprsdv** [comment]
The `confirm` method isn't implemented by default for Webview in Cocoa. Same
was the case with `alert` and `print`, which were implemented some time ago. It
wouldn't need much work, as the code for a confirm dialog box is already in place
for the `confirm_quit` parameter, let me see.

**Comment by shivaprsdv** [comment]
Implemented.

**Comment by pomplesiegel** [comment]
@shivaprsdv, Just tested your PR #146 and it fixes this issue. Thank you!
