### ISSUE TITLE
The program is not displayed on the status bar

### ISSUE THREAD

**Issue by WHG555** [r0x0r/pywebview#1441]
### Specification
- pywebview version:
- operating system:
- web renderer:

### Description

  Describe your issue in details. Provide a stand-alone code example that would demonstrate the problem.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

# feature

My program wants not to show up on the status. How this feature is written

**Comment by r0x0r** [comment]
What platform? What status bar?

**Comment by WHG555** [comment]
platform is windows 10

# now is this
![image](https://github.com/user-attachments/assets/57e5258e-9d2e-4ca6-957a-335a3fbb7342)

# but i want to this
![image](https://github.com/user-attachments/assets/9b642cc6-fea1-4110-aa4e-cb10b896f32d)

## It doesn't appear on the status bar. Instead, it is only displayed in the system tray

**Comment by WHG555** [comment]
？？？
