### ISSUE TITLE
All web engines very slow

### ISSUE THREAD

**Issue by EmberLightVFX** [r0x0r/pywebview#1444]
### Specification
- pywebview version: 5.1
- operating system: Windows 10
- web renderer: All

### Description

  What ever web engine I use it lags a lot when I resize the window. The only engine that wasn't slow was MSHTML but as it's depricated I guess it's no good to use it.
  For QT I have tried both PySide2 and 6, same result
  CEF doesn't give any difference than the other ones
  For edgechromium I have made sure I have the latest WebView2 runtime installed, still slow.
  
  Is this normal and expected? Here is a video on how it looks for me:

https://github.com/user-attachments/assets/0bb936e8-ffb0-42c4-b863-bc46d32a55b5

### Practicalities

- YES/NO I am willing to work on this issue myself. I know python but that's all. If I can help I'm happy to do so

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I do not notice any resize lag. EdgeChromium appears maybe a bit slower than MSHTML, but nothing serious on my machine. Tested with Macbook M1 via Paralells / Windows 11.

**Comment by EmberLightVFX** [comment]
So it doesn't look like it does in my video for you?On Aug 1, 2024 09:48, Roman ***@***.***> wrote:
I do not notice any resize lag. EdgeChromium appears maybe a bit slower than MSHTML, but nothing serious on my machine. Tested with Macbook M1 via Paralells / Windows 11.

**Comment by EmberLightVFX** [comment]
I tried on my other computer and on it it's super smooth. It's just on my laptop that it's very laggy like in my video.
Do you have any suggestions on what I can do to try and see what causes the lag on my laptop? I have tried reinstalling WebView2 and checked pywebview's debugging but can't see any direct difference between my two computers.

**Comment by r0x0r** [comment]
Perhaps GPU acceleration (or lack of) is the reason for lag? There is some information on the web that disabling GPU process can help some ui issues, but apparently there is no way to do it for webview2.
