### ISSUE TITLE
Partially initialized module 'webview' has no attribute 'create_window' (most likely due to a circular import) error on Linux

### ISSUE THREAD

**Issue by MyroslavMay** [r0x0r/pywebview#1445]
### Specification
- pywebview version: 5.1
- operating system: Linux, Ubuntu Studio (Ubuntu-based), KDE Plasma 5, X11 graphical server
- web renderer: webkit

### Description

  Describe your issue in details. Provide a stand-alone code example that would demonstrate the problem.
When I try to run example code, it shows me this error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "/home/myroslav/webview.py", line 1, in <module>
    import webview
  File "/home/myroslav/webview.py", line 7, in <module>
    window = webview.create_window('Woah dude!', htm='Woah dude!') 
AttributeError: partially initialized module 'webview' has no attribute 'create_window' (most likely due to a circular import)

My code:
import webview

def custom_logic(window):
    window.toggle_fullscreen()
    window.evaluate_js('alert("Nice one brother")')

window = webview.create_window('Woah dude!', htm='<h>Woah dude!<h>')
webview.start(custom_logic, window)
#(comment) anything below this line will be executed after program is finished executing
pass

### Practicalities

- YES/NO I am willing to work on this issue myself. NO

- YES/NO I am prepared to support this issue financially.NO

**Comment by r0x0r** [comment]
https://pywebview.flowrl.com/guide/faq.html#webview-has-no-attribute-create-window
