### ISSUE TITLE
Event on Window Focus loss?

### ISSUE THREAD

**Issue by bweinlich** [r0x0r/pywebview#1446]
### Specification
- pywebview version: 5.1
- operating system: Windows 11
- web renderer: winforms

### Description

Is it possible to detect through an event if a window has lost focus? I have an interactive application running in a webview that I would like to pause as soon as my window loses focus. Would love to see this feature in a future version :)

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
It is possible, but neither focus nor blur events are implemented. `window.events.activated` and `window.events.deactivated` could be added.
