### ISSUE TITLE
Javascript state hangs/fails to initialize in webview intermittently on startup

### ISSUE THREAD

**Issue by evmaki** [r0x0r/pywebview#1447]
### Specification
- pywebview version: 5.1
- operating system: Ubuntu 22.04.4 LTS
- web renderer: GTK (w/ WebView2 4.0)

### Description

First off, thanks for your hard work on this awesome framework. I have been encountering an issue when attempting to integrate pywebview with a React frontend on Ubuntu 22.04.4.

Sometimes after starting the application, I get a JavascriptException when attempting to call a React hook via `evaluate_js`. I encounter this error even when using the boilerplate [pywebview-react](https://github.com/r0x0r/pywebview-react-boilerplate) project with no changes. I noted that the error occurs less frequently (or not at all (?)) on macOS and Windows, which leads me to believe it has to do with the platform code.

It seemed like a race condition, so I tried blocking calls to `evaluate_js` until `window.pywebview.state !== undefined`, like so:

``` python
js = f"""
(() => {{
    if (window.pywebview.state !== undefined) {{
        window.pywebview.state.setGreeting("hello world")
        return true;
    }}
    return false;
}})();
"""
res = window.evaluate_js(js)
while not res:
    time.sleep(1)
    res = window.evaluate_js(js)
```

This just results in the thread sleeping forever. I tried placing this in a separate thread - that thread also just sleeps forever.

I ALSO tried getting the "greeting" from the frontend (by calling a `js_api` passed to `webview.start()`) after I'm certain that the hooks should be initialized, like so:

*Frontend*
``` javascript
function App() {
  const [greeting, setGreeting] = useState("");

  useEffect(() => {
    window.addEventListener('pywebviewready', function() {
      if (!window.pywebview.state) {
        window.pywebview.state = {}
      }

      // get the greeting from the backend once the hooks are initialized
      window.pywebview.api.get_greeting().then((g) => {setGreeting(g)})
    })
  }, [])

  return (
    <div> {greeting} </div> 
  )
```

*Backend*
``` python
class Api:
    def __init__(self, greeting):
        self.greeting = greeting

    def get_greeting(self):
        return self.greeting

webview.create_window("Window 1", './index.html', js_api=Api("hello world"))
webview.start()
```

This also just hangs forever, leading me to believe the Javascript execution never gets to `window.pywebview.api.get_greeting().then((g) => {setGreeting(g)})`

Any help or input on this issue is appreciated.

### Practicalities

- POSSIBLY I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What JavascriptException do you get? Can you provide a standalone example that would reproduce the problem?
You can use Devtools in debug mode and debugger statements to debug Javascript code btw.
