### ISSUE TITLE
Provides examples of vite builds?

### ISSUE THREAD

**Issue by blackawn** [r0x0r/pywebview#1448]
I am not very familiar with the operating principle of pywebview. When I used vite to build a web application, the web service was not successfully started and the page loading failed. I hope there is an example of vite construction.

**Comment by ylm-king** [comment]
额，这个问题太基础了。前端的问题，不是webview问题

**Comment by kletel** [comment]
vite is working with default settings.

**Comment by pangao1990** [comment]
可以看看 [PPX](https://github.com/pangao1990/PPX)  ，这个框架是基于pywebview，pyinstaller构建的。基础示例用的是Vue3，也就是前端用vite打包的。 @blackawn
