### ISSUE TITLE
JS function SetTimout doesn't work

### ISSUE THREAD

**Issue by TailyFair** [r0x0r/pywebview#145]
Enviroment:
* windows 10 x64
* pywebview: 1.7
* flask: 0.12.2

Javascript function ` SetTimeout` doesn't seem to work. I made minimal [app (gist)]( https://gist.github.com/TailyFair/a923aac4cbe52adb199557e0ec4a3772).
Where on link press, JS starts calling Flask API every 200 ms.

But in pywebview app, JS calls API once and stops. 
While in browser (tested in IE 11.6 and Chrome) it works perfectly fine.

I'm quite lost on how to start debug this. I would really appreciate any help.

**Comment by r0x0r** [comment]
This looks like a race condition. You open a webview window, before the server start. See the examples/flask_app for an example how to avoid this. 
To test your JS/HTML, just use your favourite browser.
