### ISSUE TITLE
Use a custom function interface instead of wrapping `window.`

### ISSUE THREAD

**Issue by sjehuda** [r0x0r/pywebview#1461]
Related to #1460

### Specification
- pywebview version: python-pywebview 5.1-1
- operating system: Arch Linux
- web renderer: ?

### Description

It appears to be impossible to verify whether pywebview is available or otherwise, and `try/catch` do not work.

```
document.addEventListener('DOMContentLoaded', () => {
    // Check if pywebview API is available
    try {
        
        // This function will be called when an anchor is clicked
        function regulator(event) {
            event.preventDefault(); // Prevent the default link behavior
            const url = this.href; // Get the URL from the clicked link
            
            // Call the exposed Python function
            window.pywebview.api.regulator(url) // try and catch do not work here.
                .catch(error => {
                    console.error("Error calling regulator:", error);
                });
        }

        // Attach event listeners to all anchor elements
        document.querySelectorAll('a').forEach(element => {
            element.addEventListener('click', regulator);
        });
    } catch {
        console.warn("pywebview API or regulator function not available.");
    }
});
```

I suggest to manifest the API as `PV.api` instead of `window.pywebview.api`.

See Greasemonkey API as an example to it.

https://sourceforge.net/p/greasemonkey/wiki/Greasemonkey_Manual:API/

The Greasemonkey API structure does not hinder the use of `try` and `catch`.

### Practicalities

- YES/NO I am willing to work on this issue ~myself~ with help and guidance.

- NO I am prepared to support this issue financially.

**Comment by sjehuda** [comment]
Has functionality feature been added?

Is there a documentation of it?

**Comment by r0x0r** [comment]
https://pywebview.flowrl.com/guide/api.html#dom-events

**Comment by sjehuda** [comment]
I use that, as per your instructions that you have conveyed to me in
the past.

Yet, I could not make use of try/catch.

If that there would be an interface as proposed in this issue, then it
would be possible to ctach try/catch events.

Am I correct?

**Comment by sjehuda** [comment]
I do not know whether or not `window.pywebview.api` is undefined in the
callback of `pywebviewready` event.

This code is the first attempt that I have made:

window.onload = async function(){
    if (window.pywebview && window.pywebview.api && window.pywebview.api.regulator) {
        // This function will be called when an anchor is clicked
        function regulator(event) {
            event.preventDefault(); // Prevent the default link behavior
            const url = this.href; // Get the URL from the clicked link
            try {
                window.pywebview.api.regulator(url); // Call the exposed Python function
            } catch {
                // Software pywebview is not engaged.
            }
        }
        // Attach event listeners to all anchor elements after the DOM is fully loaded
        document.addEventListener('DOMContentLoaded', () => {
            document.querySelectorAll('a').forEach(element => {
                element.addEventListener('click', regulator);
            });
        });
    }
}

The even try/catch was never met, even though, I think that, it should
have.

The current working code is at
https://git.xmpp-it.net/sch/Blasta/src/branch/main/script/regulator.js

Also, for example:

This is a Greasemonkey script which makes use of GM API, with which
it is possible to use try/catch when needed, hence it is useable with
and without Greasemonkey.

https://greasyfork.org/en/scripts/465932-newspaper-html-feed-reader

**Comment by r0x0r** [comment]
Well instead listening to DOMContentLoaded subscribe to `pywebviewready`. It is launched after `DOMContentLoaded`

**Comment by sjehuda** [comment]
I understand. My use case, is that Blasta has no JS involved.

The only JS code is dedicated to pywebview.

So, I have to consider both:

* People who use Blasta as a deskotp software (via pywebview).

* People who use Blasta online (no JS).

Hence, the need for try/catch, and this is why I have requested a
library interface, similarly to GM of Greasemonkey.

**Comment by r0x0r** [comment]
What is Blasta?

**Comment by sjehuda** [comment]
On Fri, 20 Sep 2024 13:49:23 -0700
Roman ***@***.***> wrote:

> What is Blasta?
> 

https://git.xmpp-it.net/sch/Blasta (code)
https://blasta.woodpeckersnest.eu/ (instance)
https://video.xmpp-it.net/w/cfozoUeVLFbBFMCCSCJ1Dn (06:38)

pywebview is mentioned at:
https://blasta.woodpeckersnest.eu/help/about/software
