### ISSUE TITLE
White border in fullscreen on Windows

### ISSUE THREAD

**Issue by forceflow1049** [r0x0r/pywebview#1462]
### Specification
- pywebview version: latest
- operating system: Windows 11
- web renderer: edge

### Description

  When Windows is set to light mode and the webview is fullscreened, there is a 1px white border around the entire window. It looks like Windows is automatically rounding the corners, which might be triggering the same bug as https://github.com/r0x0r/pywebview/issues/1413 (but I am not doing anything non-standard).

Steps to reproduce:
1. Tweak the hello world example:
```python
import webview

# use a page with non-white background
window = webview.create_window('Woah dude!', 'https://developer.mozilla.org/en-US/', fullscreen=True) 
webview.start()
```
2. There is a 1px white border around the edge of the display.

Conversely, if Windows is set to dark mode, this border is also there but dark/black. So the same bug, but much less noticeable.

**Comment by r0x0r** [comment]
Thanks for reporting this. I have never noticed the border before. 
The issue should be fixed in master. I addressed rounded corners in fullscreen window as well.
