### ISSUE TITLE
Error: 404 when starting application from windows start menu

### ISSUE THREAD

**Issue by fitzroy-2011-02** [r0x0r/pywebview#1463]
### Specification
- pywebview version: 5.1
- operating system: Windows 10
- web renderer: Chromium

### Description

I built an application using pywebview for the GUI and used pyInstaller to compile an executable for windows. It all works very good. Thanks for your great work on pywebview!!

The issue is the following, when I start the program (executing the .exe file) the program starts as expected but when I start the program via the windows start menu the following error appears.

![grafik](https://github.com/user-attachments/assets/bcff6ce5-7c43-4cc0-b688-a35a6f8df291)

I suppose its not directly connected to pywebview but more to the underlying web server that is used. It looks like the call from the start menu does not contain the information of where the program is installed (different environment variables?).

I'm thankful for any hint.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I am glad you got this resolved.

Generally you need to bundle your assets with pyinstaller. pywebview has got support for sys._MEIPASS.

**Comment by fitzroy-2011-02** [comment]
Thanks for the reply!! This was my first github comment ever, so getting such a nice response to a not related issue is a very nice feedback :)
