### ISSUE TITLE
There are 2 title's in webview.create_window

### ISSUE THREAD

**Issue by cleesmith** [r0x0r/pywebview#1464]
### Specification
- pywebview version: 5.2
- operating system: macOS Sonoma 14.6 on a Macbook Pro M3 Max
- web renderer: webkit (?)

### Description
This all started coding a python app with NiceGUI's native mode (native=True) and noticing that only my macbook 
was showing the title twice.

All laptops are using python 3.10.14 and this code:
```
import webview
if __name__ == '__main__':
    webview.create_window('New Title #2', 'https://pywebview.flowrl.com/hello')
```
... i see 2 titles in webview window on a Macbook Pro macOS Sonoma 14.6, 
but this does NOT happen on Windows 10 or a Macbook Air

macbook pro macOS Sonoma 14.6:
whomever:~$ 
defaults read /System/Library/Frameworks/WebKit.framework/Versions/A/Resources/version.plist CFBundleVersion
19618.3.11.11.5

macbook air macOS Sonoma 14.2:
whomever:~$ 
defaults read /System/Library/Frameworks/WebKit.framework/Versions/A/Resources/version.plist CFBundleVersion
19617.1.17.11.9

... all of them are using:
pip show pywebview

Name: pywebview
Version: 5.2
Summary: Build GUI for your Python program with JavaScript, HTML, and CSS
Home-page: 
Author: 
Author-email: Roman Sirokov <roman@flowrl.com>
License: BSD 3-Clause License
. . .         
Location: /opt/miniconda3/envs/clsProxy/lib/python3.10/site-packages
Requires: bottle, proxy-tools, pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, pyobjc-framework-security, pyobjc-framework-WebKit, typing-extensions
Required-by:

**Comment by r0x0r** [comment]
What do you mean by two titles? Care to provide a screenshot?

**Comment by cleesmith** [comment]
Oops, I forgot the screenshort.
![webview_2_titles](https://github.com/user-attachments/assets/b858c745-e471-41ee-8b67-ac047891f7ac)

**Comment by r0x0r** [comment]
I could not reproduce this with the latest version of pywebview and `simple_browser.py`. Do you get this with NiceGUI?

**Comment by cleesmith** [comment]
Given all of the above on my macbook pro, and just with this code:
```
import webview
if __name__ == '__main__':
    webview.create_window('New Title #2', 'https://pywebview.flowrl.com/hello')
    webview.start()
```
... pip show pywebview = 5.2 with the same screenshot ... there are still two titles.

And it still happens with Nicegui:
```
		ui.run(
			host=HOST,
			port=PORT,
			title="This is my title",
			reload=False,
			show_welcome_message=False,
			native=True,
			window_size=(810, 840),
		)
```

**Comment by r0x0r** [comment]
I am sorry I cannot reproduce this with 5.2, simple_browser.py and macOS 15.0. Screenshot attached

![image](https://github.com/user-attachments/assets/92ed32e2-a591-46bd-acd6-2d056783e2d1)

**Comment by cleesmith** [comment]
Well, I guess I will update and give macOS 15.0 a try ... it's just so weird that it only happens on a macbook pro m3, and not: on an old Intel iMac, nor on a macbook air m1 ... will update this later.

**Comment by r0x0r** [comment]
I updated to 15.0 just recently, but could not reproduce it with 14.x either

**Comment by cleesmith** [comment]
After upgrading to macOS Sequoia 15.0, I see:
```
defaults read /System/Library/Frameworks/WebKit.framework/Resources/version.plist

{
    BuildVersion = 1;
    CFBundleShortVersionString = 20619;
    CFBundleVersion = "20619.1.26.31.6";
    ProjectName = WebKit;
    SourceVersion = 7619001026031006;
}
```
... but the double titles still happen.

So I tried with/without miniconda and just using python/pip with no virtual environment, and using pywebview 5.2 and  simple_browser.py ... but no change as there are still two titles.
I'm ok with no titles, as most users will probably not be using a MacBook Pro M3, and it does work on M1, iMac, and Windows.  The issue is probably in Webkit.
Thanks for taking a look and trying to help.
