### ISSUE TITLE
loadcss example of pywebview

### ISSUE THREAD

**Issue by anthony-cavender** [r0x0r/pywebview#1465]
### Specification
- pywebview version:
import webview
import threading

def load_css():
    webview.load_css('body { background: red !important; }')

if __name__ == '__main__':
    t = threading.Thread(target=load_css)
    t.start()

    webview.create_window('Load CSS Example', 'https://pywebview.flowrl.com/hello')

- operating system:
- windows
- web renderer:
https://pywebview.flowrl.com/2.4/examples/css_load.html

### Description
FIX:
import webview
import threading

def load_css():
    webview..windows[0].load_css('body { background: red !important; }')

if __name__ == '__main__':
    t = threading.Thread(target=load_css)
    t.start()

    webview.create_window('Load CSS Example', 'https://pywebview.flowrl.com/hello')

Issue and fix:
webview does not contain the function loadcss it is within the window. Obviously index 0 would change depending upon the window the css would load into
### Practicalities

The code above would resolve the issue.

**Comment by r0x0r** [comment]
You are looking at the documentation of the ancient version of pywebview. It is left online for archiving purposes
