### ISSUE TITLE
The returned type is different on macOS and windows create_file_dialog open folder_dialog.

### ISSUE THREAD

**Issue by pangxiaobin** [r0x0r/pywebview#1467]
### Specification
-  pywebview version:5.2
- operating system:windows
- web renderer:

### Description    

result =  window.create_file_dialog(
            webview.FOLDER_DIALOG,  directory=''
        )
        
in macOs this code return tuple  but in windows return string.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Fixed in master. Also fixed multiselect for folder dialog.
