### ISSUE TITLE
can i convert current page into pdf in pywebview window

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1469]
its possible

**Comment by r0x0r** [comment]
You may invoke `window.print()` that will bring print dialog and you can export to pdf there.

**Comment by MominIqbal-1234** [comment]
ok thanks so please tell me how to convert pywebview file in exe so hide all the html and other file use in project like electron js its possible

**Comment by r0x0r** [comment]
use pyinstaller's in onefile mode.

**Comment by MominIqbal-1234** [comment]
ok i try this is but one file problem is execution time is very long 
and on the other hand use one directory so its execution time is fast
