### ISSUE TITLE
The interface loaded by pywebview will trigger a CTRL+F5 hard refresh in the frontend after login failure, which will cause the injection of api_js to be cleared

### ISSUE THREAD

**Issue by motcs** [r0x0r/pywebview#1474]
### Discussed in https://github.com/r0x0r/pywebview/discussions/1472

<div type='discussions-op-text'>

<sup>Originally posted by **motcs** September 20, 2024</sup>
The interface loaded by pywebview will trigger a CTRL+F5 hard refresh in the frontend after login failure, which will cause the injection of api_js to be cleared. Please ask whether you can avoid the problem of api_js being cleared after hard refresh, or inject api_js again after hard refresh, instead of invalidating, which causes pywebview.api to fail after logging in again. Here are the details of the error:
Traceback (most recent call last):
  File "D:\xxxx\.venv\lib\site-packages\webview\util.py", line 183, in inject_pywebview
    func_list = generate_func()
  File "D:\xxxx\.venv\lib\site-packages\webview\util.py", line 171, in generate_func
    functions = get_functions(window._js_api)
  File "D:\xxxx\.venv\lib\site-packages\webview\util.py", line 166, in get_functions
    get_functions(attr, full_name, functions)
  File "D:\xxxx\.venv\lib\site-packages\webview\util.py", line 166, in get_functions
    get_functions(attr, full_name, functions)
  File "D:\xxxx\.venv\lib\site-packages\webview\util.py", line 166, in get_functions
    get_functions(attr, full_name, functions)
  [Previous line repeated 1 more time]
  File "D:\xxxx\.venv\lib\site-packages\webview\util.py", line 161, in get_functions
    attr = getattr(obj, name)
  File "D:\xxxx\.venv\lib\site-packages\webview\dom\dom.py", line 18, in body
    return self._elements.get('body', Element(self.__window, 'body'))
  File "D:\xxxx\.venv\lib\site-packages\webview\dom\element.py", line 77, in __init__
    self.__generate_events()
  File "D:\xxxx\.venv\lib\site-packages\webview\dom\element.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "D:\xxxx\.venv\lib\site-packages\webview\dom\element.py", line 426, in __generate_events
    for event in events:
TypeError: 'NoneType' object is not iterable</div>

**Comment by r0x0r** [comment]
JS API is injected on every page navigate event. Please provide a minimal standalone example that would demonstrate this problem.

**Comment by motcs** [comment]
self.api = Api()
   webview.settings = {
                'ALLOW_DOWNLOADS': True,
                'ALLOW_FILE_URLS': False,
                'OPEN_EXTERNAL_LINKS_IN_BROWSER': False,
                'OPEN_DEVTOOLS_IN_DEBUG': False
            }
            self.window = webview.create_window(
                title=self.config.data_json.get("title"),
                url=r'core\client\templates\dist\index.html',
                width=1344, height=900,
                min_size=(1344, 900),
                text_select=False,
                confirm_close=True,
                js_api=self.api,
                on_top=True, focus=True)
  webview.start(self.deactivate, localization=self.chinese, gui='edgechromium', debug=True)

The interface launched in this way, when refreshing the interface using CTRL+R or F5, will cause the injected js_api to fail

**Comment by r0x0r** [comment]
Shortcuts keys are disabled. How do you manage to refresh using F5 or CTRL+R?

**Comment by motcs** [comment]
After checking with the right mouse button on the interface, you can refresh by pressing F5 or CTRL+R in the developer tools

**Comment by r0x0r** [comment]
Yes you are right, context menu and shortcut keys are enabled in debug mode. I still cannot reproduce the issue, `window.pywebview` is injected after page is refreshed

**Comment by r0x0r** [comment]
@xianfei do you get this with vue's development server? If so, my guess is that hot reload is not playing nicely with pywebview's injection logic
