### ISSUE TITLE
The launched GUI window cannot display sub options for menu options.

### ISSUE THREAD

**Issue by zhangke-zhangke** [r0x0r/pywebview#1477]
### Specification
- pywebview version: 5.2
- operating system: Ubuntu
- web renderer: default

### Description

Hello, I am writing a test example using pywebview. The implemented function is that the user login page does not have a menu bar, and can only see the menu bar after logging in. But just as I was completing the test, I found that the menu bar I created couldn't be clicked correctly. The reality is that clicking or moving taskbar options has no response (sub options should be displayed), and there are error logs in the backend console.
Console output: QBasicTimer:: start: Timers cannot be started from another thread.

Here is my code:
```
import webview
import webview.menu as wm
from flask import Flask, render_template, request

app = Flask(__name__)

menu_items = [
        wm.Menu('Test Menu', [
            wm.MenuAction('Change Active Window Content', 'change_active_window_content'),
            wm.MenuSeparator(),
            wm.Menu(
                'Random',
                [
                    wm.MenuAction('Click Me', 'click_me'),
                    wm.MenuAction('File Dialog', 'open_file_dialog'),
                ],
            ),
        ],),
        wm.Menu('Nothing Here', [wm.MenuAction('This will do nothing', 'do_nothing')]),
    ]

@app.route('/login', methods=['post'])
def login():
    user = request.form.get('username')
    if user != 'admin':
        return '''
        <form action="/login" method="post">
            <div>
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div>
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div>
                <button type="submit">Login</button>
            </div>
        </form>
        '''

    # is admin user
    app.config['is_login'] = True

    # open new gui, set menu
    webview.guilib.set_app_menu(menu_items)
    webview.create_window('test', app)

    # close first gui window
    webview.windows[0].destroy()

    return ''

@app.route('/')
def index():
    # login success
    if app.config.get('is_login'):
        return '''
            <div>This is the index page</div>
        '''
    return '''
    <form action="/login" method="post">
        <div>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>
        <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div>
            <button type="submit">Login</button>
        </div>
    </form>
    '''

if __name__ == '__main__':
    window1 = webview.create_window(
        'test-login', app
    )
    webview.start()

```

I am not sure how opening and closing windows in the code will affect the main thread, or is there a better solution? Thank you.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Could you fix your example so that it could be run?

**Comment by zhangke-zhangke** [comment]
> Could you fix your example so that it could be run?

Sorry, the modification has been completed. In addition, in my example program, the login username is admin and there are no restrictions on the login password.

**Comment by r0x0r** [comment]
I managed to run your example, but your menu click handlers are strings and not functions. There are no handler functions either.

**Comment by zhangke-zhangke** [comment]
> I managed to run your example, but your menu click handlers are strings and not functions. There are no handler functions either.

Yes, for convenience, the menu in the demo is a string. However, my problem is that the menu bar cannot be clicked. Normally, when the mouse moves to the menu bar options, there is a dark background. Please refer to the next video for details.


Uploading 录屏_jetbrains-pycharm-ce_20241014125802.mp4…

**Comment by zhangke-zhangke** [comment]
https://github.com/user-attachments/assets/02670456-18a6-47ed-b793-2d1abcc955a1

**Comment by zhangke-zhangke** [comment]
> _jetbrains-pycharm-ce_20241014125802.mp4

As can be seen, when I move to the menu bar options, I cannot click and when I move to a submenu, the console will display the following error print:
Console output: QBasicTimer:: start: Timers cannot be started from another thread.
﻿
In my code, I am using the following code to create a second window and set the menu bar. I am not sure if the method is correct.
webview.guilib.set_app_menu(menu_items)
webview.create_window('test', app)

**Comment by r0x0r** [comment]
Menu is global. Window specific menu is not currently supported unfortunately.

**Comment by zhangke-zhangke** [comment]
> Menu is global. Window specific menu is not currently supported unfortunately.

Okay, thank you very much.
