### ISSUE TITLE
How do i get the window handle?

### ISSUE THREAD

**Issue by Olypolyu** [r0x0r/pywebview#1482]
### Specification
- pywebview version: whatever the latest is.
- operating system: windows 11.
- web renderer: edge.

### Description

  I'm trying to build an app that adds a overlay and for that i want for the window to pop up when a key combo is pressed and for it to assume focus. This probably should just be a part of pywebview itself, but just giving me the window handle so i can control the window with pywin32 is enough.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You can use something like after a window is created (e.g. in the `shown` event handler) `window.gui.BrowserView.instances['master'].Handle`

This will get hwnd for the main window. For other windows instance id will be something else. 

I have been thinking about exposing a native window instance to the window object, so getting handler could be  for example `window.native_window.Handle`. Will try to add at some point.

**Comment by r0x0r** [comment]
Master branch has now `window.native`. You can now get handle via `window.native.Handle`

**Comment by Olypolyu** [comment]
Oh, thank you for that and your answer. Forgot to reply lol. It works.
