### ISSUE TITLE
The pywebview-5.2 shows a blank window with Windows, AMD Radeon(TM) Vega 8 Graphics, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

### ISSUE THREAD

**Issue by creeperyyds** [r0x0r/pywebview#1484]
### Specification
- pywebview version: 5.2
- operating system: Windows 11
- web renderer: Chromium (I think so)
- Python Version: 3.12.5

### Description
**(English is not my native language; please excuse typing errors.)**
When I run this code
```python
import webview

window = webview.create_window('Woah dude!', 'https://pywebview.flowrl.com')
webview.start(debug=True)
```
It shows nothing but a blank window:(I can open the website on Edge)
![image](https://github.com/user-attachments/assets/9687fd54-2cdb-47e3-81ea-1fce4a0e12ad)
And the console only shows: 
```
[pywebview] Using WinForms / Chromium
```

(I have another software that use pywebview,it will shows a native html file,and before I can use it correctly,but now it throws an exception webview.errors.WebViewException: Main window failed to start)

I tried:

- [x] ~~use Python 3.9~~ (Failed)
- [x] ~~use Windows 10 in VMware~~ (Failed)
- [x] ~~modify the website~~ (Failed)
- [x] ~~use local html file~~ (Failed, only shows:
```
[pywebview] Using WinForms / Chromium
Bottle v0.12.25 server starting up (using ThreadedAdapter())...
Listening on http://127.0.0.1:38771/
Hit Ctrl-C to quit.
```
)

Thanks in advance for your attention.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.(I don't have any money)

**Comment by creeperyyds** [comment]
I tried to use Python 3.9 just now, still don't work

**Comment by r0x0r** [comment]
It is difficult to debug without error log, but my bet is that there is something wrong with EdgeChromium runtime. You may try to see if webview runtime ever gets initialized by placing print statements  (breakpoints do not work here) inside `on_webview_ready` handler https://github.com/r0x0r/pywebview/blob/a2b8d0449b206db75f9f364639b85db6eac7f07e/webview/platforms/edgechromium.py#L205

**Comment by creeperyyds** [comment]
It looks like it didn't run ```on_webview_ready```. And sorry because I didn't know how to get an error log.

**Comment by Ciarands** [comment]
Exact same issue here, strangely, using pyenv-win and prepending with `pyenv exec` fixes the issue?
Also using AMD GPU + CPU.

**Comment by creeperyyds** [comment]
Works fine up to and including 5.1,maybe 5.2 changed something

**Comment by creeperyyds** [comment]
If you changed edgechromium.py in 5.2 to edgechromium.py in 5.1, it works.

**Comment by creeperyyds** [comment]
https://github.com/r0x0r/pywebview/blob/a7f7fed662a523ff077288b5d60ab0970f0f5d55/webview/platforms/edgechromium.py
The py file can show the website, although the console shows: 
```
[pywebview] WebView2 initialization failed with exception:
 'CoreWebView2Settings' object is not subscriptable
   在 Python.Runtime.PythonException.ThrowLastAsClrException()
   在 Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   在 Python.Runtime.Dispatcher.Dispatch(Object[] args)
   在 __System_EventHandler`1\[\[Microsoft_Web_WebView2_Core_CoreWebView2InitializationCompletedEventArgs\, Microsoft_Web_WebView2_Core\, Version=1_0_2045_28\, Culture=neutral\, PublicKeyToken=2a8ab48044d2601e\]\]Dispatcher.Invoke(Object , CoreWebView2InitializationCompletedEventArgs )
   在 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()
```

**Comment by creeperyyds** [comment]
https://github.com/r0x0r/pywebview/commit/cdc88c38fa2bfabacca27bf7b337979cbc1e3edb
The commit makes it not works

**Comment by creeperyyds** [comment]
Make a pull request to fix it:https://github.com/r0x0r/pywebview/pull/1488

**Comment by creeperyyds** [comment]
Make a pull request to fix it:https://github.com/r0x0r/pywebview/pull/1489

**Comment by r0x0r** [comment]
I pushed a [fix](https://github.com/r0x0r/pywebview/commit/3e08cce0d2b935a795807c832efd684aeb1c30b1) for storage_path to master. It does two things. First it checks whether storage_path is writeable and raises an exception before initialization. Second, changed slightly how Webview2 is initialized, so storage_path should be not be an issue anymore. Please test.

**Comment by creeperyyds** [comment]
> I pushed a [fix](https://github.com/r0x0r/pywebview/commit/3e08cce0d2b935a795807c832efd684aeb1c30b1) for storage_path to master. It does two things. First it checks whether storage_path is writeable and raises an exception before initialization. Second, changed slightly how Webview2 is initialized, so storage_path should be not be an issue anymore. Please test.

Works well on my device! Thanks for everyone helping! QWQ
