### ISSUE TITLE
Version 5.2 creates left over files in directory next to PyInstaller exe

### ISSUE THREAD

**Issue by divadsn** [r0x0r/pywebview#1487]
### Specification
- pywebview version: 5.2
- operating system: Windows
- web renderer: Edge Chromium

### Description

When pywebview 5.2 is bundled together with the app using PyInstaller and executed, MS WebView creates left over files in the same directory next to the executable instead in %TEMPDIR% even if `private_mode` is explicitly set to True.

![image](https://github.com/user-attachments/assets/1a744a21-c738-4007-b852-660e2a2fe819)

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I just pushed a [fix](https://github.com/r0x0r/pywebview/commit/3e08cce0d2b935a795807c832efd684aeb1c30b1) for to master that should resolve this issue.
