### ISSUE TITLE
Winforms, minimize to system tray

### ISSUE THREAD

**Issue by TailyFair** [r0x0r/pywebview#149]
Is it possible to minimize program to system tray in Windows using winforms ?
I couldn't find way by looking at documentation.

If it's not implemented, I wonder if it would be possible.

I think it would be nice if double clicking would bring it back. And maybe right clicking would return context menu with option to:

- Open application window
- Quit application

**Comment by r0x0r** [comment]
It is not implemented. If you want to give it a go, please go ahead.

There are cross-platform design issues to be resolved first. Should pywebview support tray icon as a separate feature and tray minimization is a side-feature on Windows? Other platforms seem not to have this functionality. Or should it be limited only to minimize to tray on Windows? If we decide to go for the tray icon support on all platforms, then a context menu should be implemented as well. Icon is another consideration. It would be nice to have a custom icon support, as well as an ability to change an icon on the fly (ie. depending on the status of the application).

All in all, it is definitely possible, but seems like a lot of work.

**Comment by shivaprsdv** [comment]
On a similar note, macOS supports keeping the app in the dock after closing it.
This is not implemented for pywebview apps either; it too is a platform specific
feature. Only if Linux too had a similar feature, we could have tried something.

**Comment by shivaprsdv** [comment]
Can we close this?

**Comment by TailyFair** [comment]
Probably yes for now.

I looked a bit into it and it didn't seemed easily done or at least with my knowledge :)
So I don't plan to try implement it.
