### ISSUE TITLE
Error : All files (*.*)  by Create an open file dialog 

### ISSUE THREAD

**Issue by windtersharp** [r0x0r/pywebview#1495]
### Specification
- pywebview version: 5.2.0
- operating system:  macos 14.6.1 

### Description
- After opening the file dialog, switching to "All files" has no effect.
- "WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:." What should I do?

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This issue has been already fixed in master. See this commit https://github.com/r0x0r/pywebview/commit/a2b8d0449b206db75f9f364639b85db6eac7f07e

New release is coming sometime soon.
