### ISSUE TITLE
Help: window toolbar

### ISSUE THREAD

**Issue by windtersharp** [r0x0r/pywebview#1496]
### Specification
- pywebview version: 5.2.0
- operating system: macos 14.6.1

### Description
- Menu: There is a view menu. How do I hide it?
- Frameless : Hide (the close and size control buttons are gone). How to achieve the effect of Google Chrome, where the UI can start from the top?
  

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
1. View menu is added by pywebview. There is currently no way to hide it.
2. What do you mean by the Google Chrome effect?

**Comment by windtersharp** [comment]
<img width="91" alt="image" src="https://github.com/user-attachments/assets/a4895d4a-c661-4c3d-8c78-474fcd6cdc2f">
Customize these buttons, but after set frameless, I can't find these buttons.

**Comment by windtersharp** [comment]
> 1. View menu is added by pywebview. There is currently no way to hide it.
> 2. What do you mean by the Google Chrome effect?
<img width="91" alt="image" src="https://github.com/user-attachments/assets/a4895d4a-c661-4c3d-8c78-474fcd6cdc2f">
Customize these buttons, but after set frameless, I can't find these buttons.

**Comment by windtersharp** [comment]
ok, thanks
