### ISSUE TITLE
Error: The start function stops the python process

### ISSUE THREAD

**Issue by qaqFei** [r0x0r/pywebview#1497]
### Specification
- pywebview version: `5.2`
- operating system: `8.1`
- web renderer: i do not know, maybe is edge webview2

### Description

run this code:
```py
import webview
webview.create_window("test")
webview.start()
```
later, python process stopped:
![2801843682ef836557551796b602497](https://github.com/user-attachments/assets/9115b58c-a792-4d3f-b1c7-97de20963ef8)

#### Methods that may be reproduced
- Install VMWare 16.2.4 build-20089737 on windows 10
- Install Widnows 8.1 Pro Build 9600
- Install WebView2 Runtime
- Install vc_redist.x64
- Install Python 3.12.0
- Update pip
- Install pywebview
- Run python
- `import webview`
- `webview.create_window("test")`
- `webview.start()`
- python process stopped

### Practicalities

- `YES` I am willing to work on this issue myself.
- `NO` I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Windows 8 is officially obsolete. This is a .NET issue I do not know anything about.

**Comment by qaqFei** [comment]
thanks
