### ISSUE TITLE
Add support for CEF

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#15]
Chrome Embedded Framework (CEF) could be a great alternative to IE based renderer on Windows systems. There are Python bindings for CEF found here https://github.com/cztomczak/cefpython, as well as some examples on how embed CEF with various GUI toolkits.

**Comment by shivaprsdv** [comment]
This is nice, but doesn't this mean bundling CEF with the application built on
pywebview, blowing up the app size? The one **killer** feature of pywebview I
found over the _big_ frameworks like Electron or CEF is that it uses the native
API that the user already has in their OS. As _you_ said it:

> If you choose to freeze your application, it does not bundle a heavy GUI
> toolkit with it keeping the executable size small

I would appreciate this if there is some way to embed CEF, while _sticking
to the principle._ 👍

**Comment by r0x0r** [comment]
Yes, this will bloat the distribution size by some 30mb, but still it would be nice to support this (myself I have no problems supporting recentish IE versions). Anyhow, this is very low priority and is unlikely I will work on this anytime soon.

**Comment by shivaprsdv** [comment]
It seems Edge is pretty improved compared to IE. Any idea about Microsoft
letting embed EdgeHTML any time soon?

**Comment by r0x0r** [comment]
No idea, if Microsoft is going to ever support it, as their current focus seems to be on universal apps. Then again Microsoft has a good track of caring about backward compatibility.

**Comment by denfromufa** [comment]
a bit off-topic, but i noticed your 2.0 release with notes about Edge/IE. Apparently it is now possible to use IE in Edge-compatibility mode via a registry key:

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/13198941-webbrowser-control-using-edge-rendering-engine

**Comment by r0x0r** [comment]
Unfortunately this won't work. The registry setting only sets the Edge user
agent, while keeping Trident as a rendering engine. To my knowledge, there
is no way to embed Edge in traditional .NET applications. UWA is the only
choice and god knows if it will be ever possible to get Python working with
UWA.

**Comment by r0x0r** [comment]
I pushed a preliminary implementation of CEF for Windows. Most of the features are implemented, but it is still very buggy. Tests do not pass.

**Comment by r0x0r** [comment]
Another push. Tests passing and pretty much everything, but `toggle_fullscreen` is working.

**Comment by r0x0r** [comment]
Windows implementation is ready. 

PR https://github.com/r0x0r/pywebview/pull/310

**Comment by r0x0r** [comment]
CEF implementation for Windows is now in master. I will release a new version soon.

**Comment by r0x0r** [comment]
CEF Windows is live now with version 2.3.

**Comment by r0x0r** [comment]
TODO implementations

- [ ] macOS
- [ ] GTK
- [ ] QT

**Comment by dtcooper** [comment]
Happy new year! Any update re: CEF support on Mac? :)

**Comment by r0x0r** [comment]
@dtcooper Not really. I am not working on it, and I doubt anyone else is too.

**Comment by dtcooper** [comment]
> @dtcooper Not really. I am not working on it, and I doubt anyone else is too.

All right. Thanks for the honest update.

**Comment by tede12** [comment]
I'm running on macOS Catalina (10.15.4), this line `from ctypes import windll` localized in **webview/platforms/cef.py** on top of the file raise with an **ImportError**.

this would solve the error.
`try:
    from ctypes import windll
except ImportError:
    pass`

**Comment by r0x0r** [comment]
@tede12
What do you mean CEF is not available for macOS?
Cocoa is part of macOS. macOS implementation pywebview is built on top of it.

**Comment by tede12** [comment]
Yes, I know. I didn't understand if I can open a chromium instance with pywebview

**Comment by r0x0r** [comment]
It looks like CEF is a dead end. I am not going to work on CEF support for other platforms.
