### ISSUE TITLE
pywebview multiprocessing with pyinstaller

### ISSUE THREAD

**Issue by Liripo** [r0x0r/pywebview#1501]
### Specification
- pywebview version: 5.3
- operating system: windowns
- web renderer: default

## question
  When I compile this program using pyinstaller, a duplicate window opens.
```python
import webview
import multiprocessing

def test():
    while True:
        1

def on_closed(process):
    if process.is_alive():
        process.terminate()
        process.join()
    return None

process = multiprocessing.Process(target=test)
process.start()

index_html = "index.html"
win = webview.create_window('test!', str(index_html))
win.events.closed += lambda: on_closed(process)
webview.start(http_server=True,debug=False)
```

```ps
pyinstaller --onefile .\test.py
.\dist\test.exe
```
error gif: 
![PixPin_2024-10-18_17-18-25](https://github.com/user-attachments/assets/0278956d-7486-4e25-a8d8-e67c47928c79)

**Comment by r0x0r** [comment]
Maybe wrapping top level code in `if __name__ == '__main__'` helps

**Comment by Sped0n** [comment]
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

**Comment by Liripo** [comment]
@Sped0n Thank you.
