### ISSUE TITLE
OS Windows - How Move o Maximized Form?

### ISSUE THREAD

**Issue by mathbarlow** [r0x0r/pywebview#151]
Hello, I have this basic code:

**webview.create_window('SACTIC', url=params, width=width-50, height=height-100, resizable=True, fullscreen=False)**

By parameters i can have the form in fullscreen mode, but i need this **form Maximized** or move this form from init position, How can I do it in a simple way?

**Comment by r0x0r** [comment]
Currently there is no way to specify an initial position of the window or
start or maximized. You could detect screen dimension and start a pywebview
window with these values.

**Comment by shivaprsdv** [comment]
@mathbarlow Is this clear? Can we close this?

**Comment by mathbarlow** [comment]
Yes, unfortunately there is no adequate solution, but it can be closed

**Comment by shivaprsdv** [comment]
Thanks. We'll notify you if this ever gets implemented.
