### ISSUE TITLE
Cannot resize a frameless window on edge webview2 runtime

### ISSUE THREAD

**Issue by Sped0n** [r0x0r/pywebview#1510]
### Specification
- pywebview version: 5.3.2
- operating system: Windows 11 23H2 22631.4317
- web renderer: edge webview2 (130.0.2849.52)

### Description

When frameless is enabled, unable to resize the window by dragging the edge.

```python
import webview

if __name__ == '__main__':
    # Create a resizable webview window with minimum size constraints
    webview.create_window('Frameless window', 'http://pywebview.flowrl.com/hello',
                          frameless=True, easy_drag=True)
    webview.start()
```
 
### Practicalities

- YES/NO I am willing to work on this issue myself. [NO]

- YES/NO I am prepared to support this issue financially. [NO]

**Comment by r0x0r** [comment]
This is by design. Frameless windows are not supposed to be resized.

**Comment by Sped0n** [comment]
> This is by design. Frameless windows are not supposed to be resized.

But on macOS it did? Never mind, I will close the issue first.

**Comment by r0x0r** [comment]
You are correct. This is the default behaviour of frameless windows on different platform.
One solution could be a new `resizable` param to `create_window` that let you explicitly make a choice.

**Comment by S3idSensei** [comment]
I highly suggest this feature, must people want this to create a custom titlebar in css.

**Comment by r0x0r** [comment]
@S3idSensei Feel free to contribute :)
