### ISSUE TITLE
Microsoft Edge WebView2 Runtime  130.0.2849.52 start eorr

### ISSUE THREAD

**Issue by 534146825** [r0x0r/pywebview#1514]
### Specification
- pywebview version:pywebview-5.3.2
- operating system:win10 professional edition   Version number： 22H2  os Version:19045.4894
- web renderer:Microsoft Edge WebView2 Runtime  130.0.2849.52

### Description

 import webview

try:
    webview.create_window('Example', 'http://example.com')
    webview.start()
except Exception as e:
    print(f"An error occurred: {e}")

eorr：
[pywebview] WebView2 initialization failed with exception:
  (0x80080005): 服务器运行失败 (异常来自 HRESULT:0x80080005 (CO_E_SERVER_EXEC_FAILURE))
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__8.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()

**Comment by r0x0r** [comment]
See https://github.com/MicrosoftEdge/WebView2Feedback/issues/4884
