### ISSUE TITLE
Request: Debug Mode Improvements

### ISSUE THREAD

**Issue by idleDevel** [r0x0r/pywebview#1516]
### Specification
- pywebview version: 5.1
- operating system: Windows 10 (Two different machines) and Windows 11 (One machine)
- web renderer:  Default (Using WinForms / Chromium?)

### Description

1.  Previously I have used debug, where the extra window defaulted to dark mode. It no longer does, and instead tries to default to the system theme (even though it says dark+ is the default). This unfortunately doesn't seem to be working in my case, even with both my OS and Edge set to dark mode. Not sure if this could be made into a selectable option in the python script. Changing it in the menu is not persistent between script runs, and I relaunch mine frequently during development. If this is not at all addressable, I understand. 

2.  Debug mode enables the GUI to respond to refresh commands and other default browser behaviors. I would personally like this to be toggleable for running in non-debug mode. Not having that option (at least I haven't found it) limits the use unnecessarily. 

### Practicalities

- YES/**NO** I am willing to work on this issue myself.

- YES/**NO** I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
1. Nothing has been done on the dark mode front. It may or not work on each platform. Dark mode support will come at some point
2. I guess an extra setting option `"DEBUG_MODE_ENABLE_BROWSER_NAVIGATION": True` or something like that could be introduced. I won't work on it though. If you need it, feel free to submit a complete PR for all the platforms.
