### ISSUE TITLE
 webview.settings['ALLOW_DOWNLOADS'] not working

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#1519]
### Specification
- pywebview version: 4.4.1
- operating system: Ubuntu 24.04.1 LTS
- web renderer:

### Description

i try to download pdf using js its not working

![image](https://github.com/user-attachments/assets/2eaa51fb-76c5-4c59-918a-ad2c3e48f7af)

```python
if __name__ == '__main__':
    window = webview.create_window('example',app,text_select=True,width=1400, height=700,min_size=(1400,700),http_port=9000) # min_size=(1200,700)
    webview.settings['ALLOW_DOWNLOADS'] = True
    webview.start(debug=False,http_server=True,menu=menu_items)
```

**Comment by r0x0r** [comment]
`webview.settings` was intoduced in 5.0

**Comment by MominIqbal-1234** [comment]
and can i run pywebview http server in ip address like 192.168.19.8:8900
