### ISSUE TITLE
Plans for Qt version 6?

### ISSUE THREAD

**Issue by rotdrop** [r0x0r/pywebview#1520]
### Specification
- pywebview version: any
- operating system: Linux
- web renderer: qt version 6 if that would be available

### Description

Are there any plans to support Qt version 6? So this is rather a feature request.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Pywebview should work against qt6 already. 
Version 5.3 in particular introduced a number of improvements addressing qt6 compatibility.

**Comment by rotdrop** [comment]
Mmmh. But Pyside2 is Qt5 only? Ok. I have to investigate further before insisting that this still is a problem. Please accept my apologies for the case that this is an already solved issue.

**Comment by r0x0r** [comment]
Both pyside2 and pyside6 are supported via `qtpy`
