### ISSUE TITLE
White flash on window show (not create!) 

### ISSUE THREAD

**Issue by Barafu** [r0x0r/pywebview#1521]
### Specification
- pywebview version: 5.3.2
- operating system: Win11 - 24H-Hmmm...-updated!
- web renderer: Edge

### Description

**Short description:**  When a window is created, it is initially white while DOM renders. It is normal and IS NOT the issue. However, if I hide the window until the content had been rendered, there is still a white flash when the window is shown - no, there is two of them!

**Long description:** I am making an application that should create a fullscreen black window on every monitor and start drawing on it. I am moving the development from Tauri to PyWebView. I create a window with content, where CSS property on body sets black background. 
In Tauri, if I show the window as is, it flashes white until DOM is loaded. To avoid it, I create the window invisible, and set it to visible after the DOMContentLoaded event, then no flashes. 
In Pywebview, however, when I do the same, I get two white flashes: one when window is created (before `webview.start`) and another when the window is shown, despite having waited after the content is fully rendered, not just DOM loaded. 
As a workaround, I can use minimize/restore instead. It causes an extra TaskBar buttons to appear and does not get rid of the flash completely, but at least it is one, not two.

**Comment by r0x0r** [comment]
Can you provide a standalone example demonstrating the problem?

**Comment by Barafu** [comment]
My screensaver in construction should be a good example. Here: https://github.com/Barafu/Dream_Spinner/tree/Python
The main is currently at "python_src/dreamspinner.py"
