### ISSUE TITLE
ImportError: cannot import name 'windll' from 'ctypes'

### ISSUE THREAD

**Issue by windtersharp** [r0x0r/pywebview#1522]
### Specification
- pywebview version: 5.3.2
- operating system: macos 14.6.1

### Description

  Run Example: Python/3.9/lib/python/site-packages/webview/platforms/cef.py", line 8, in <module>
    from ctypes import windll

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
CEF is Windows only.
What are you trying to do here?
