### ISSUE TITLE
Unable to delete temporary directory.

### ISSUE THREAD

**Issue by zeruniverse** [r0x0r/pywebview#1523]
### Specification
- pywebview version: 5.3.2
- operating system: Windows 11
- web renderer: Edge

### Description

PywebView using Edge leaves a temporary directory inside Temp dir. I need a way to remove those dirs. Is there a way I can pass cache-dir / user-data-dir into webview or webview can give me such information so I can delete those dirs after completing my jobs?

![image](https://github.com/user-attachments/assets/896f3f1f-805b-49bc-a5b2-ff29b752702f)
![image](https://github.com/user-attachments/assets/adbf157c-bce9-4f48-a557-c52217f1bd93)

```python
import webview
window = webview.create_window('Bing', 'https://www.bing.com', width=1920, height=1080)
webview.start()
```

**Comment by r0x0r** [comment]
Yes, there is a `storage_path` param to `webview.start`

**Comment by zeruniverse** [comment]
Thanks!
