### ISSUE TITLE
If there is a new URL redirect program, it will get stuck

### ISSUE THREAD

**Issue by wall-git** [r0x0r/pywebview#1528]
### Specification
- pywebview version:5.2
- operating system:win10
- web renderer: webview2

### Description

When I try to pass window into an object instance ，If there is a new URL redirect program, it will get stuck 
thanks

### code example
~~~python
import webview
api = None
class ViewApi:
    win = None
    def setWindow(self,window):
        self.win = window  
def on_loaded(window):
    print('DOM is ready')
    #If there is a new URL redirect program, it will get stuck
    api.setWindow(window)
    
if __name__ == '__main__':
    api = ViewApi()
    #Click on any link
    window = webview.create_window(
        'Simple browser', 'https://www.bing.com/', js_api=api
    )
    window.events.loaded += on_loaded
    webview.start()
~~~

**Comment by r0x0r** [comment]
This occurs because of it tries to expose to `win` object of `ViewApi` class and goes into an infinite loop. Prefix `win` with an underscore to prevent exposing.

**Comment by wall-git** [comment]
Thank you so much, buddy，It has indeed solved my problem. Can you explain why this happened? esteem it  a favor

**Comment by wall-git** [comment]
Thank you so much, buddy，It has indeed solved my problem. Can you explain why this happened? esteem it  a favor

**Comment by r0x0r** [comment]
Having said that, there is still a bug in JS code loading logic that results in this bug. The root of the problem is that objects under `window.pywebview` are referenced, before they are created.

I will address this.

**Comment by wall-git** [comment]
Looking forward to your solution👍

**Comment by r0x0r** [comment]
Fixed in this PR https://github.com/r0x0r/pywebview/pull/1533 among other improvements
