### ISSUE TITLE
Pywebview stops working on reload

### ISSUE THREAD

**Issue by tothalex** [r0x0r/pywebview#1531]
### Specification
- pywebview version: latest
- operating system: mac

### Description

  With the following code the application stops working on reload

```python
import webview


class Api:
    window: webview.Window

    def on_loaded(self):
        self.window = webview.windows[0]


if __name__ == "__main__":
    api = Api()

    window = webview.create_window(
        "hello", "dist/index.html", width=800, height=430, resizable=False, js_api=api
    )

    window.events.loaded += api.on_loaded

    webview.start(debug=True)

```

**Comment by r0x0r** [comment]
Serializing window object is not possible in the currently released version, but it is fixed in this pr https://github.com/r0x0r/pywebview/pull/1533
