### ISSUE TITLE
When accessing HTTP, it prompts that insecure connections are not supported. How to remove the prompt

### ISSUE THREAD

**Issue by itmeicn** [r0x0r/pywebview#1537]
Every time you visit, it prompts whether you can cancel it directly to the page
![image](https://github.com/user-attachments/assets/821c207c-ff37-4014-bbff-b516698dd8ae)

**Comment by r0x0r** [comment]
There is an option for ignoring certificate errors, but counterintuitively it is enabled only when  `webview.settings['SSL'] = True` (it is originally intented for supporting SSL connections in local http server). Try that.

**Comment by itmeicn** [comment]
I tested webview.settings['SSL'] = True or webview.settings['SSL'] = False ，it not resolved。

**Comment by r0x0r** [comment]
Sorry my bad, it is `webview.start(ssl=True)`. This setting is intended for ssl support in built-in http server, though. 
Having said that I have added `webview.settings['IGNORE_SSL_ERRORS'] = True`. The change is now in master.

**Comment by itmeicn** [comment]
webview.create_window('测试', 'http://www.itmei.cn', width=default_W_h[0], height=default_W_h[1])
    webview.settings = {
        'ALLOW_DOWNLOADS': True,  # Allow file downloads
        'ALLOW_FILE_URLS': True,  # Allow access to file:// urls
        #'IGNORE_SSL_ERRORS':True,
    }
    # 忽略http不是https的错误，好像不起作用
    webview.settings['IGNORE_SSL_ERRORS'] = True

it's not solved.
I have Win11, but it's possible that webview no longer supports HTTP. It's strongly recommended to use HTTPS

**Comment by r0x0r** [comment]
Here is a working example.

```
import webview

if __name__ == '__main__':
    webview.settings['IGNORE_SSL_ERRORS'] = True
    window = webview.create_window('Simple browser', 'https://untrusted-root.badssl.com/')
    webview.start()

```

**Comment by itmeicn** [comment]
ths
