### ISSUE TITLE
Inconsistent rendering on some Windows 7 machines (occasionally)

### ISSUE THREAD

**Issue by pomplesiegel** [r0x0r/pywebview#157]
My program has been running excellently and consistently on Windows 7, 8 and 10 machines. However, today in testing I ran it on a random Toshiba Satellite C655 laptop running Windows 7 Ultimate SP1 64 bit. This time it rendered differently than any other computer I have used. Everything was off the screen:
![image](https://user-images.githubusercontent.com/1450352/33343512-8f563c2c-d453-11e7-85ea-44da37e64e58.png)

I pulled up my program on another PC running the exact same resolution (1366 x 768) and it did not have this issue. The window was a consistent size between them both, but the content was wrong on the Toshiba.

I thought that all Windows machines were rendering using Trident/MSHTML. What could contribute to these variations?

What can i test to provide us more information? 

Thanks so much for your help!

**Comment by pomplesiegel** [comment]
Update: The second time i ran the program, it rendered correctly, even though I have no dynamic layout settings! 
I'm also remembering now some potentially important details. The button shown: "Update from online" should be disabled through CSS, but it instead showed like above, and when hovering over it, it produced a small red symbol. Pardon the size:
![image](https://user-images.githubusercontent.com/1450352/33343780-8d5edc34-d454-11e7-802d-cdb5a33226fa.png)

What could cause the inconsistent rendering to happen just once on just this machine? I have run this program probably a thousand times across various PCs.

**Comment by r0x0r** [comment]
Could you you test your app with the system's IE to see if it produces similar behaviour? pywebview uses vanilla MSHTML, so there should be no differences between in rendering between pywebview and IE

**Comment by pomplesiegel** [comment]
Sure, i'll do that. Given that it's just vanilla MSHTML, i suppose we can close this issue unless something else props up.
