### ISSUE TITLE
Option to set the title tags as the name of the window

### ISSUE THREAD

**Issue by guiscaranse** [r0x0r/pywebview#159]
It would be amazing if we could have the option to set the title of the window by using only the `<title>` tag on the HTML loaded.

**Comment by r0x0r** [comment]
I am not sure how I feel about this. There are several options to tackle this issue
1) Make `title` parameter of `create_window` optional and update the title based on the title of the loaded page. I am not too fond of this approach, as changing the app title on the fly is not good UX in my book. Browsers for example prepend the title with the browser name, but in case of pywebview this cannot be done.
2) Introduce `set_title()` function and leave the logic of updating the title to developer
 
Input is welcomed

**Comment by guiscaranse** [comment]
Both of the solutions are good, even tho I prefer the first approach. In my case changing the title of the window is important because developers can implement things like "notification counters" as many apps currently use.
`set_title()` is good too because developers can make callbacks from the javascript to python, so updating the title whatever they want can be useful.

**Comment by r0x0r** [comment]
Let's go with the `set_title()` function and leave automatic update to end developers.

**Comment by r0x0r** [comment]
I created an implementation skeleton + Cocoa implementation in the `set_title` branch

**Comment by r0x0r** [comment]
The rest is implemented as well. I am yet to test it on Windows, but otherwise it is done.

**Comment by r0x0r** [comment]
PR is here https://github.com/r0x0r/pywebview/pull/167
I will keep it open for a couple of days in hope of comments and suggestions,
