### ISSUE TITLE
mac version fullscreen

### ISSUE THREAD

**Issue by lrusnac** [r0x0r/pywebview#16]
I tried to create a window in fullscreen but it doesn't work for me, it creates a 800x600 window

**Comment by r0x0r** [comment]
Works fine for me on 10.9.5. What OSX version are you using?

The syntax for opening a fullscreen window:
`webview.create_window("Full-screen browser", "http://www.google.com", fullscreen=True)`

**Comment by lrusnac** [comment]
10.11.1, it's not full screen for me

**Comment by r0x0r** [comment]
I guess fullscreen API has changed in El Capitan. I will take a look at it.

**Comment by r0x0r** [comment]
Still cannot reproduce it. Works as intended on El Capitan (10.11.1) for me. Are you using built-in Python or a standalone installation with pyobjc installed?

I have slightly refactored the code related to fullscreen mode, if you are willing to give it one more try. The changes are in master.

**Comment by lrusnac** [comment]
ok, I found the problem, if you start ``webview.create_window("Full-screen browser", "http://www.google.com", fullscreen=True)`` from a fullscreen terminal then the application will be only 800x600 otherwise, if you start it from a normal window is fullscreen

**Comment by tiznull** [comment]
> ok, I found the problem, if you start `webview.create_window("Full-screen browser", "http://www.google.com", fullscreen=True)` from a fullscreen terminal then the application will be only 800x600 otherwise, if you start it from a normal window the application is fullscreen

Thank you! I was going crazy trying to figure this out.
