### ISSUE TITLE
allow flash content

### ISSUE THREAD

**Issue by mathbarlow** [r0x0r/pywebview#160]
Hello, your pywebview has been of great use for me, but i have a webpage with flash content, I can allow flash content by code?

**Comment by r0x0r** [comment]
I haven't researched it, but I assume it is possible. Not exactly convinced though of whether it is worth pursuing as Flash is on the way of becoming obsolete.
What platform, though?

**Comment by mathbarlow** [comment]
Hello, excuse my time answering, I used Jquery Datatables and i change export button for HTML5, link:

https://datatables.net/extensions/buttons/examples/html5/simple.html

I can't export PDF or other.. Is it possible to work with pywebview?

**Comment by r0x0r** [comment]
Sorry, but this is a custom solution and without diving into details I have no idea how this export functionality is implemented and why it does not work.

**Comment by mathbarlow** [comment]
:( is very sad, I need only this functions, the rest is perfect +1: 

I suposse, you can close this forum question
