### ISSUE TITLE
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by Counterdoc** [r0x0r/pywebview#161]
I try to use pywebview (1.8) for a REMI project on Raspbian Stretch. I am using Python 2.7 and PyQt4. There is also Python 3 and PyQt5 installed on my system. When I start my program as standalone (running it with pywebview) this error occurs:

`webview.qt ERROR PyQt5 or one of dependencies is not found`

And at the end also this one occurs:

`RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class`

It seems like pywebview tries to use both Qt installations?

![img_6888](https://user-images.githubusercontent.com/28528387/34512539-70df836c-f063-11e7-93b2-af28ffbf66b2.jpg)

![img_6887](https://user-images.githubusercontent.com/28528387/34512542-7953f186-f063-11e7-808d-8e83486e3d26.jpg)

![img_6891](https://user-images.githubusercontent.com/28528387/34512555-94b0e86c-f063-11e7-95fc-0a3689a992c4.jpg)

**Comment by r0x0r** [comment]
It looks like you have got `QtWebEngineWidgets` missing. Try `sudo apt-get install libqtwebkit-dev`

**Comment by Counterdoc** [comment]
That was one problem, yes. I did a fresh install and tried a simple import which fails:

`from PyQt4.QtWebKit import QWebView`

results in:
`ImportError: No module named QtWebKit`

QtWebKit is no longer supported/installed with PyQt4. So I guess using pywebview with PyQt4 will not work on any new installation.

**Comment by r0x0r** [comment]
Yes, QtWebKit comes with libqtwebkit-dev. You have to install it separately.
I did a fresh install of PyQt4 with QtWebKit on Ubuntu Trusty the other day and it worked fine. No idea about the Raspberry Pi ecosystem though.

**Comment by Counterdoc** [comment]
I did some research: PyQt4 with QtWebKit is not available on the latest Raspbian systems (= Debian stretch). But it is available at Debian jessie. Will try it with Jessie later.

**Comment by shivaprsdv** [comment]
I had a similar issue some time ago. Couldn't get QtWebKit with PyQt4 using
`apt`. That time I had found it had to do with PyQt4 becoming obsolete and
unmaintained. So I guess:
> QtWebKit is no longer supported/installed with PyQt4. So I guess using pywebview with PyQt4 will not work on any new installation.

is true, at least on Debian.

**Comment by Counterdoc** [comment]
That is exactly what I have found too. But only with Debian Stretch. Jessie should work. I am just testing it.

**Comment by Counterdoc** [comment]
Okay, I can confirm it now. 
pywebview is working with Raspbian Jessie (Debian Jessie) and PyQt4.
It is NOT working with any Debian Stretch based distribution.
