### ISSUE TITLE
Option to hide scrollbar from MSHTML 

### ISSUE THREAD

**Issue by guiscaranse** [r0x0r/pywebview#168]
Since we are tied to use the MSHTML as the web renderer, I think it should be possible to hide the scrollbar but yet allow the scroll behavior from mouse wheel. I know that that's not that much important, but it just really annoys me how big the scrollbar really is.
And yes, I know that I can hide the scrollbar with a little CSS but it doesn't allow me to display any custom scrollbars from jQuery plugins and CSS code snippets once hidden.
Not sure tho if it's possible to achieve that.

**Comment by r0x0r** [comment]
Seems to be doable by applying the "-ms-overflow-style: none" style to the html element. Now the next question is how to implement this. Options I can think of are
1. Enable by default
2. Add a new parameter to create_window. 
3. A config flag

I incline to the third option.

**Comment by shivaprsdv** [comment]
I back that. But if it is doable via CSS, can't we leave it to end developers?

**Comment by guiscaranse** [comment]
@shivaprsdv @r0x0r, I've tried many jQuery plugins to try to substitute the original MSHTML scrollbar but they just couldn't replace the default one... until 10 minutes ago, it seens that the only plugin that I've managed to implement sucessfully on the body tag using jquery was [nicescroll.js](https://github.com/inuyaksa/jquery.nicescroll) as you can see [here](https://imgur.com/a/QvIC2). While testing I've thought that was some limitation on the MSHTML form that wouldn't behave as a default browser scrollbar, and I was wrong. 
So, working with CSS and Javascript can really do the trick instead implementing something on the pywebview side. I don't know, I think we can let it to end developers and the issue can be marked as solved

**Comment by shivaprsdv** [comment]
Great! Let me close this then..

**Comment by r0x0r** [comment]
I am undecided on this. On one hand it is nice to have decent user experience out of the box, but on the other hand I don't like to add clutter. If it ever comes to this I will add a `config.windows_hide_scrollbars` option, but let's keep this issue for a reference for the time being.
