### ISSUE TITLE
Frameless windows

### ISSUE THREAD

**Issue by Fizzadar** [r0x0r/pywebview#169]
I'm trying to implement a frameless window (on MacOS w/`pyobjc` but ideally this would be possible everywhere, I think electron does it everywhere).

Getting the titlebar transparent and the content to fill the whole window is pretty simple with:

```py
window_mask = window_mask | AppKit.NSFullSizeContentViewWindowMask
...
self.window.setTitlebarAppearsTransparent_(True)
self.window.setTitleVisibility_(AppKit.NSWindowTitleHidden)
```

However, the frameless window cannot be dragged about because even the very top is covered by the `WebView` - as dragging the mouse moves this into text selection mode. Electron's solution is a Chrome-specific (annoying) `-webkit-app-regon: drag` CSS selector.

My thinking is it might be possible to achieve this by drawing a transparent box over the top X pixels of the `NSWindow` and making that draggable (using `setMovableByWindowBackground_(True)`).

**Comment by r0x0r** [comment]
How about the `window_frame=False` parameter to `create_window`? Setting this parameter to True would hide the frame and enable easy drag. I think there is no value in having a frameless non-draggable window.

Would you get this feature started?

**Comment by Fizzadar** [comment]
`window_frame=False` sounds good to me; I'll see what I can come up with!

**Comment by r0x0r** [comment]
Small correction, the signature is `window_frame=True` not False

**Comment by Fizzadar** [comment]
I got this working last night for Cocoa on my [`frameless-windows`](https://github.com/Fizzadar/pywebview/tree/frameless-windows) branch! Made it draggable using an invisible "drag bar" at the top with code from the [`RoundTransparentWindow`](https://pythonhosted.org/pyobjc/examples/Cocoa/AppKit/RoundTransparentWindow/index.html) pyobjc example. Not sure this is the best approach!

**Comment by shivaprsdv** [comment]
I reckon a better signature would be `frameless=False|True`.

**Comment by r0x0r** [comment]
frameless is fine with me.
@Fizzadar any reason why drag bar is of a specific height and not the whole window?

**Comment by Fizzadar** [comment]
Will update to frameless when I get the chance!

@r0x0r it has to be limited to the top region as it blocks mouse events underneath it from hitting the `webview`. It might be possible to stop this but then dragging the window around might also select all the text on the page/similar. I just chose the height because it roughly fits the traffic light buttons on MacOS.

**Comment by shivaprsdv** [comment]
@Fizzadar What about adding a modifier key, just for dragging? Like:
&nbsp;&nbsp;&nbsp;&nbsp;Simple drag: select text
&nbsp;&nbsp;&nbsp;&nbsp;Ctrl+drag: move window

**Comment by r0x0r** [comment]
I don't like the idea of using a modifier key. It is not explicit and details like this must be documented (and documentation is easily ignored). Anyhow let's leave it like it is for the time being and decide on the dragging behaviour later.
@Fizzadar would you do a PR when you get a chance?

**Comment by shivaprsdv** [comment]
Okay. We need to check if this is possible on Linux and Windows as well.

**Comment by r0x0r** [comment]
I have added Windows support feat. full window easy drag

**Comment by r0x0r** [comment]
Just pushed QT and GTK implementations. Easy drag is yet to be implemented.

**Comment by r0x0r** [comment]
@Fizzadar I modified the Cocoa implementation, so that 
a) standard buttons (close, minimize, maximize) are hidden
b) the whole window area is draggable

Dragging a window in multi-window environment is buggy at least on Cocoa, but I am not able to address this issue right now.

GTK/QT easy drag is on the way.

**Comment by Fizzadar** [comment]
@r0x0r these changes make it impossible to interact with the webpage/UI rendered inside the webview! The drag bar sits over the top of everything so you can't select/interact with the HTML.

For the buttons - why remove these? With the drag bar implementation there _has_ to be a ~22px area across the top of the entire window that's not useful for HTML/UI - but the buttons do work over the top of the drag bar, so I see no reason to remove them...

**Comment by r0x0r** [comment]
Ah true, did not realise dragging disables all the other mouse events. Do
you think if there is any way to make both work?

I would like to have a uniform implementation across all the platforms, ie.
full window drag and no buttons. I see your point about the drag bar, but
if full window drag is possible, then there is no need to reserve space for
the drag bar either.

**Comment by Fizzadar** [comment]
Makes sense re-space/buttons (I'd be keen to make the buttons an option, though!). Would be nice to keep it consistent between platforms.

For the drag when I was playing around I did find a [`movableByWindowBackground`](https://developer.apple.com/documentation/appkit/nswindow/1419072-movablebywindowbackground?language=objc) property which worked - but as soon as you open a webview over the top if ceases to work; hence the whole dragbar thing :)

**Comment by r0x0r** [comment]
I have implemented easy drag for QT and GTK.

**Comment by r0x0r** [comment]
I have implemented macOS support. PR here https://github.com/r0x0r/pywebview/pull/313/files

**Comment by r0x0r** [comment]
Merged into master.
