### ISSUE TITLE
Fullscreen window stuck in corner on Windows 10

### ISSUE THREAD

**Issue by ironman5366** [r0x0r/pywebview#17]
When I create a window in full screen mode, it's stuck in the corner as pictured in the screenshot. I've racked my brains and the web, but nothing works. My attempted fixes include scaling my display res down to 1920*1080 in case it didn't support 4k, running the file in a wide variety of different ways, using different html files, and using gtk instead of qt. So far none have worked. 
![screenshot 73](https://cloud.githubusercontent.com/assets/10326155/11764042/121e7ce0-a0ef-11e5-8652-c57b52a45c3b.png)

**Comment by r0x0r** [comment]
GTK and QT are for Linux based systems. For Windows you should use Win32. Does this occur for Win32?

**Comment by ironman5366** [comment]
If win32 is the default mode on Windows, then that's what I was using when I thought I was using qt. If not, how would I use win32 mode?

**Comment by r0x0r** [comment]
Yes, it uses Win32 by default. I don't have Windows 10 installed at the moment, but will figure something out.

What display resolution are you using?

**Comment by ironman5366** [comment]
Appreciated, 3200*1800, but I've tried scaling down to 1080 and I also don't know what display res the client has. I would normally be testing on Ubuntu as well, but the client exclusively uses Windows 10.

**Comment by r0x0r** [comment]
This post provides an example fullscreen solution used by Chromium
http://stackoverflow.com/questions/2382464/win32-full-screen-and-hiding-taskbar

I will give it a shot. Please feel free to contribute if you are comfortable with translating C++ code to Python.

**Comment by ironman5366** [comment]
Thanks for the help, I'm not overly fluent in that kind of C++ or Windows utilities but I will contribute in any way I can.

**Comment by ironman5366** [comment]
Is this what is being discussed? https://code.google.com/p/cefpython/source/browse/cefpython/var/fullscreen.py?r=00071cbb9dda54d0dc0a187f47f550c081f822d7

**Comment by r0x0r** [comment]
I think I have found the cause for this bug. I have pushed a fix into master. Would you mind checking it out?

**Comment by ironman5366** [comment]
Works like a charm. Thanks

**Comment by bhandariroshan** [comment]
hi, I am facing the same problem. Where is the fix?

**Comment by ironman5366** [comment]
The fix was pushed to github. Not sure if it made it into the pip package
though, so you may have to use the source from git
