### ISSUE TITLE
Error in qt.py

### ISSUE THREAD

**Issue by adbenitez** [r0x0r/pywebview#171]
Error in qt.py in line 28: `_qt_version = float(QT_VERSION_STR[:3])`
this doesn't work for PyQt 5.10 since it takes only 3 chars the results is '5.1'
and it makes pywebview to think PyQt5 < 5.5.
maybe using `str.split('.')` will be a better approach:
`_qt_version = float('.'.join(QT_VERSION_STR.split('.')[:2]))`
also _qt_version should be treated different since `float('5.10') < 5.5`
and line 30: `if _qt_version > 5.5:` will be false.

EDIT:
actually I think it would be better to treat _qt_version as a list:
 `_qt_version = [int(n) for n in QT_VERSION_STR.split('.')]`
an you could do this in line 30 and others:
`if _qt_version > [5, 5]:`

Hope this helps :) I like this project.
Regards,
adb

**Comment by r0x0r** [comment]
Good catch. Could you make a pull request?

**Comment by adbenitez** [comment]
oh, sorry I am new to github and have never colaborated with a project :(

**Comment by adbenitez** [comment]
done, please read my comments in the pull request.

**Comment by r0x0r** [comment]
Thanks, good work! I revised version comparison a bit
