### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jimster121** [r0x0r/pywebview#173]
The example provided to the homepage doesn't seem to be working
![1st](https://user-images.githubusercontent.com/26460223/35766069-442e1d18-08d9-11e8-89ed-68d2a04cb8fd.png)
![2nd](https://user-images.githubusercontent.com/26460223/35766070-44665a70-08d9-11e8-9547-0e852c071cda.png)
Why though? I think I installed everything required
`sudo apt-get install python-setuptools`
`sudo easy_install pip`
`sudo pip install pywebview`

**Comment by r0x0r** [comment]
There is a syntax error in your code. No idea why, but maybe a unicode issue? Try downloading one of examples and running it instead

**Comment by Jimster121** [comment]
I run some of your examples but still nothing works. How can it be a unicode issue since no unicode characters are being used?

Log of "Simple Browser":
`/home/jimmy/Desktop/examples/simple_browser.py: line 5: $'\nThis example demonstrates how to create a webview window.\n': command not found
/home/jimmy/Desktop/examples/simple_browser.py: line 9: syntax error near unexpected token `'Simple browser','
/home/jimmy/Desktop/examples/simple_browser.py: line 9: `    webview.create_window('Simple browser', 'http://www.flowrl.com')'
`

**Comment by shivaprsdv** [comment]
Excuse me, have you tried running it _with_ the python command? Like:

```python /home/jimmy/Desktop/run.py```

**Comment by Jimster121** [comment]
lol, it worked XD

Thank you so much!
