### ISSUE TITLE
Bad HTML5 / Javascript Support

### ISSUE THREAD

**Issue by Jimster121** [r0x0r/pywebview#174]
As soon as I started to experiment I noticed that something was going wrong and web pages wouldn't render correctly. HTML5 Support (about the same as Internet Explorer 11)
![itdoesntwerk](https://user-images.githubusercontent.com/26460223/36047136-e0dee520-0de3-11e8-9fdf-f750ff4e2fc6.png)
1. How can I improve the HTML5 Support? Is it even possible?
2. Is there a compatible library/script that copies text to clipboard? I don't care if it is on Flash or JavaScript. I couldn't find anything compatible 👎

**Comment by shivaprsdv** [comment]
1. I see you are running Linux. Updating GTK/QT (whichever you are using)
should get you the latest version of WebKit.
2. Don't know, but have a look at this [W3Schools tutorial](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp). Here they do it in
pure JS without any libraries.

**Comment by Jimster121** [comment]
1 Running 
```
apt update
apt upgrade
```
didn't show any updates, Im using GalliumOS, an Ubuntu-based distro

2 This tutorial uses Javascript that is not compatible

**Comment by r0x0r** [comment]
pywebview uses a web renderer provided by the operating system (in case of Linux GTK or QT). If you wish to use something else, consider helping with the implementation of CEF #15 .

**Comment by Jimster121** [comment]
The thing is that Chromium uses way too much RAM/CPU & Storage. I have no problems using the pre-installed WebKit, the only thing I want is a way to copy text to clipboard. That's the only thing that keeps me behind

**Comment by shivaprsdv** [comment]
I'm sorry, but what you are asking is purely an HTML/JS question. In web dev,
we cannot expect every feature to work on all platforms; the only workaround
is to use fallbacks for browsers (pywebview is only a window that hosts a built
in browser engine) that does not support it.

We could be of more help if you specify the platforms you are targeting. The
W3Schools tutorial I shared works on the following platforms:

![screen shot 2018-02-10 at 11 16 05 am](https://user-images.githubusercontent.com/18247990/36059019-e5948f40-0e54-11e8-9ab9-2fe1b3b5f584.png)

Both Chrome and Safari now supports it, which means it is available in relatively
newer versions of WebKit, which Linux and macOS uses. As IE9+ supports it, it
will run on Windows 7+.

**Comment by Jimster121** [comment]
Then why it didn't work for me?

**Comment by shivaprsdv** [comment]
I can't say for sure; to make sure your HTML code is fine, have you tried it in an
external browser? [This file](https://gist.githubusercontent.com/shivaprsdv/7f4f35b70f8b04c6f1645cdf26535169/raw/1dc9820a458f70bbd36d24bed86ef265da5d6453/copy.html) is working for me (macOS 10.13.2), you may try it.

**Comment by Jimster121** [comment]
Nope, still doesn't work

**Comment by shivaprsdv** [comment]
Which version of which browser are you using?

**Comment by Jimster121** [comment]
I tested this on Chromium latest version, but I use Firefox latest version for my daily needs

**Comment by shivaprsdv** [comment]
If it does not work in either of those browsers, then it might as well be an OS
issue. Unfortunately I am in no way familiar with GalliumOS; for Linux coding I
use Lubuntu in VirtualBox, and the above file works fine with both the browser
(Firefox 56.0) and pywebview.

**Comment by shivaprsdv** [comment]
Okay. This is likely an OS issue (but nothing likely to do with the kernel version).
Can you visit [this page](http://browserspy.dk/webkit.php) in your pywebview app and post back the WebKit version
it shows?

**Comment by Jimster121** [comment]
Still the same problem... I installed and fully update Lubuntu 16.04 and the script didn't run. It has about the same HTML5 support

![nah](https://user-images.githubusercontent.com/26460223/36157460-86e21644-10e2-11e8-8b1e-030a5fdfc6c5.png)

And the same versions of WebKit...

_Lubuntu 16.04_
![webkitversionlubuntu1604](https://user-images.githubusercontent.com/26460223/36157503-9f67614c-10e2-11e8-97af-274967b13c59.png)

_GalliumOS_
![webkitversiongalliumos](https://user-images.githubusercontent.com/26460223/36157511-a25d913c-10e2-11e8-89ca-0c34dd94f365.png)

**Comment by shivaprsdv** [comment]
@Jimster121 Sorry for the (very) late reply, but I have confirmed that this is
_not_ a GalliumOS issue; both GTK and Qt WebKits on my Lubuntu shows a
similar score on the websites above. The test script I gave you _doesn't_ work
on either of these platforms on my system as well; I had not tested properly
and had mistaken they did.

I doubt it has got anything to do with the WebKit version. I don't know more
about the issue at the moment, but I'll certainly post back if I find out.

**Comment by shivaprsdv** [comment]
My bad! It was just a matter of enabling a flag. Fixed in master. On Qt
it runs perfectly, was only GTK that needed the fix. And no idea if this
works on Windows.

By the way as Roman said,

> pywebview uses a web renderer provided by the operating system

...we can really do nothing to _improve_ the HTML5 support that we are
granted; but there is always scope for enabling flags like this, and also
doing some mock JS with the pywebview JS API. That's all we can do.

If the patch at least solves the text-copying issue, please consider
marking this as closed. Cheers 🙂

**Comment by Jimster121** [comment]
The copy function works great! Thank you so much!
