### ISSUE TITLE
Better type detection of the evaluate_js return value 

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#175]
- [x] **All** Convert JS objects to Python dicts and arrays to lists
- [x] **GTK** Detect return value type. number, string, object, undefined. Could be done by storing `typeof returnValue` as a string parameter
- [x] **All** Harmonize return value types across platforms

**Comment by r0x0r** [comment]
Started working on this in the `evaluate-js-renovation` branch. Cocoa implementation is somewhat done, but is still rough at edges. I will write tests first. I have also added a more elaborate test runner (`run_test2`) that will reduce the amount of boilerplate in test cases.

**Comment by shivaprsdv** [comment]
Can be closed?
