### ISSUE TITLE
webview.start() function

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#181]
I propose an alternative way to start a webview application

`webview.start(title, html, css='', script='', js_api=None, options={})`
 
would start a webview window with the given title and html. Optionally separate CSS and JS can be supplied as parameters (or embedded into the html). `options` would be a new dictionary with window specific options of `create_window`. `start` would be a single window blocking function, subsequent windows shall be opened using `create_window`.

All the building blocks are already in place, so the implementation should pose no challenges.

Comments are welcomed.

**Comment by r0x0r** [comment]
One major issue is linking to local resources (images, fonts, etc). While JS and CSS can be loaded via Javascript, other resources can be not. What can be done though is 
1) using data urls. This only works for images
2) dynamic resolution for dynamic paths. Say urls prefixed with the `pywebview://` protocol will get substituted with `file://path_to_executing_script`. Substitution will be performed for html and css content (and possibly JS too)

Any better options? Other opinions?

**Comment by shivaprsdv** [comment]
Now that's much better, the two initial suggestions seemed far-fetched. But
now how does `start` differ anyway from `create_window`? If we don't want
any options, both syntaxes are the same, which kind of defeats the purpose
of introducing `start`, right?

Before this issue was opened, I had envisioned a `start` function but with a
different objective: to actually _start_ the application. Like the `run` function
of most web-server frameworks. You create all the windows you need with
`create_window` and `start` your app when you're done. So `create_window`
would never block execution, and return the `uid`s of all windows.

I had got this idea when I wrote the doc for multiple windows, realising how
odd it was with only the initial call to `create_window` blocking and giving a
special `uid` "master" to it and all that stuff. But I restrained from proposing
it as implementing such a model would render us backward-incompatible. It
would be also much work. But honestly that would have been a better model
now.

**Comment by r0x0r** [comment]
Yes, you are right. This is exactly the point I have been contemplating. Having done all the work, I got back to the square one, duh. 

A non-blocking `create_window` cannot be done unfortunately, as the GUI libraries require that the GUI is to be run on a main thread. I have attempted to do it a long time ago, but ran into this limitation. Your idea of refactoring the code to the tune of multiple `create_window()` and one `start()` makes sense, but as you said it is too much of a drastic change at this point. Furthermore I reckon the most common use case is a single window scenario, so such a change would complicate the API for no reason. Anyhow, let's keep this suggestion in mind for future releases.

What can be done now though is to get rid of the `start` function altogether and implement its functionality as part of `create_window`. If the url parameter does not have a protocol prefix, `create_window` would assume it is a local relative path and apply path resolution logic currently implemented in `start`.

**Comment by shivaprsdv** [comment]
Agreed. What I suggest is to merge the `base_uri` and `transform_url` functions
into one; The later already does the protocol check, the former properly adds the
path. The new function can be used by both `create_window` and `load_html`.

But about `start` it has occurred to me that this is in fact the best time for such a
drastic change! What, other than a major release like 2.0, can be the best place to
put it? 3.0 would be too late. I know, I said it, it'd be work. But I don't think it would
complicate the API; instead simplify it, if we do it properly. Here's my idea:

- GUI libraries want to run on the main thread. Fine. We'll make`create_window`
open windows _only_ if we're running; if we're not running, we will _postpone_ the
call till `start`. I am imagining a global stack to which `create_window` _pushes_
the 'calls' (store the window-specs) and `start` would execute one by one.
- Obviously, `start` would not take any arguments. It would return nothing  also.
It _has_ to be called from the main thread and it will block. All `create_window`
calls, before or after `start`, will not block, but return the uid of the window.
- API calls work the same way as before. They wait for `_webview_ready`.
- Only `start` will `_initialize_imports`.

Now what all these mean for the single-window scenario is just an extra call to
`start` after their usual `create_window`:
```py
import webview

if __name__ == '__main__':
    webview.create_window('Simple browser', 'http://www.flowrl.com')
    webview.start()
```
It would in no way complicate the API! It complicates our lives, of course. 🙃
I say do it now before the core code gets messier. I dare give it at least a try
before 2.0. Another (not so attractive) option is to release a 1.9 with what we
have now, and 2.0 later, with the task list mentioned in #197 including `start`.

**Comment by r0x0r** [comment]
I think it is not the right time for such a big change, a major release or not. I would not like to go the Webpack route and introduce breaking changes every major release. KISS is the king in my book, after all. Let's keep the current architecture for 2.0 and see if a concrete need for an architectural change arises. If so, it can be implemented for 3.0. 

Some thoughts about potential architecture though. I would create a Window class that would be returned by `create_window` and move all the webview's functions that have the `uid` parameter to it. Another thing that the `start` function could accept an optional callback that would be executed in a separate thread eliminating the need to start a secondary thread manually. ie something like this
```
import webview

def do_stuff(window):
   window.load_html('<p>dope</p>')

if __name__ == '__main__':
    window = webview.create_window('Simple browser')
    webview.start(do_stuff, window)
```

**Comment by shivaprsdv** [comment]
Okay then. And this syntax is cleaner, the natural OOP way to handle windows.
As you said let us keep this issue as a reference.

**Comment by r0x0r** [comment]
Merged the branch with the master. Closing the issue now.
