### ISSUE TITLE
[enhancement] Javascript injection

### ISSUE THREAD

**Issue by adbenitez** [r0x0r/pywebview#182]
It could be nice if there were a way to make something similar to Greasemonkey (https://www.greasespot.net) is user scripts, I mean: to add some Javascript to pages loaded in the webview.

**Comment by r0x0r** [comment]
You can do that by using the `evaluate_js` function.

**Comment by shivaprsdv** [comment]
More specifically, look for `webview.evaluate_js(script)` in the [API documentation](https://github.com/r0x0r/pywebview#api).

**Comment by adbenitez** [comment]
Cool!!! this is very useful.
Sorry, I should had read the code before opening this issue.
Regards,
adb
