### ISSUE TITLE
js_api unclear

### ISSUE THREAD

**Issue by tjohnsonhvac** [r0x0r/pywebview#184]
I tried to run the js_api example from the examples folder. I get an error for no js_api parameter. I deleted the parameter ant ran it again. This time it ran but buttons did nothing. After doing some digging in the closed issues i saw a mention of "webview.set_js_api". I looked through __init__.py and saw no function defined. 
Is this function currently working?
Has it been implemented some other way?

Thanks.

**Comment by r0x0r** [comment]
Are you sure you are running the js_api example against the checked out master, and not the installed webview version? The feature is not released yet.
Also what operating system?

**Comment by tjohnsonhvac** [comment]
Windows 10. I first ran it with the version from pip install pywebview. I realized that version didn't have the code in it. I then downloaded the master from here and replaced the pywebview folder in the python package folder. I now get an io exception for file not found when trying to reference the dll file in winform.py. I checked the folder it was looking for it in and it was there. 
While typing this response I realized I didn't use pip to install the new pywebview file i just replaced the old one. Could that be an issue?

**Comment by tjohnsonhvac** [comment]
I lied. It's actually windows 7.

**Comment by shivaprsdv** [comment]
Try this:

1. Download the pywebview-master zip and unzip it to a folder. Don't need to
    replace your Python package folder, put it anywhere.
2. From the root pywebview directory, run:
        `PYTHONPATH=. python examples/js_api.py`

This will import the local pywebview module instead of the pip-installed one.

**Comment by r0x0r** [comment]
What @shivaprsdv said, except that on Windows you set up environment variables in a different way
https://superuser.com/questions/424001/launch-windows-program-with-custom-environment-variable#424002

**Comment by tjohnsonhvac** [comment]
I've got bash. I'll try and let you know how I make out.

Thanks

**Comment by tjohnsonhvac** [comment]
IT WORKS!! Sweet. 

Thanks for the help!!
