### ISSUE TITLE
Question: how do you link local html/ccs/js files in js_api example?

### ISSUE THREAD

**Issue by tjohnsonhvac** [r0x0r/pywebview#186]
I am looking to use this like electron to create a desktop app. I need to link local html/css/js files for the UI without using a server. 
Does the load html function allow for a local path?

**Comment by r0x0r** [comment]
Sure. Open a local file, load it into a string and feed it to `load_html`

**Comment by tjohnsonhvac** [comment]
And again you are correct. Thanks for the quick response. Also, as a note, the cannot find dll issue that i had on Saturday was because security settings on my computer blocked the dll file. in the file properties there was a button to unblock it.  weird issue. 

Thanks again.
