### ISSUE TITLE
Playing Video

### ISSUE THREAD

**Issue by leoahkun** [r0x0r/pywebview#188]
I'm trying to load a video using `<video>`, but can't get this to work. I'm trying this with a local file. Is this a limitation?

**Comment by shivaprsdv** [comment]
Which platform? Works on macOS, not on Linux.

**Comment by r0x0r** [comment]
Can you play video using a built-in browser? Linux has notoriously got codec issues.

**Comment by r0x0r** [comment]
Closing due inactivity

**Comment by shmrymbd** [comment]
hi. i am looking to play local file .mp4. possible?

**Comment by r0x0r** [comment]
I don't know to be honest.
Try testing your code in a web browser first and if it works, embed it to
the pywebview app. Loading file:// resources might pose a CORS problem, so
serving a video via a HTTP server might be needed.

**Comment by xabispacebiker** [comment]
I have the same problem. Actually what I do is play the video through HTML tag video served by nginx. It works in any browser (chromium) but not in pywebview.
