### ISSUE TITLE
Deprecating PyQt4

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#189]
I upgrade Ubuntu to the latest version and could not install QtWebKit for PyQt4 any more. Googling revealed that the package was removed altogether, as it is no longer maintained. As of now I could not get working PyQt4 environment on my local machine.

Should pywebview remove support for PyQt4 as well? I have very little idea about the Linux ecosystem to be honest, so I would like to get some feedback here. Is PyQt4 still relevant?

**Comment by shivaprsdv** [comment]
I met with this ages ago. IIRC I had posted it in some issue comment. Yes, [here](https://github.com/r0x0r/pywebview/issues/161#issuecomment-355347321).

I won't suggest removing existing support for Qt4. We could stop maintaining it.
Like the Win32 implementation, it can be _'not active maintained and misses some
features'_ for the time being.

I too appreciate feedback from avid Linux users.

**Comment by r0x0r** [comment]
The crucial difference between Win32 and PyQt4 is that the former one is its own module, while PyQt4 is a bunch of ifs that add to the complexity. Deprecation would be gradual: first mark it deprecated (say 2.0) and remove it in 3.0.

The reason I brought this issue is that I have spent the entire day trying to fix a bug in PyQt4 that occurs in Travis and I cannot even reproduce it locally. Installing an older image of Ubuntu would probably help, but it becomes too much work supporting deprecated technology.

**Comment by adbenitez** [comment]
I think it would be better to just remove the support for PyQt4.

**Comment by r0x0r** [comment]
PR here https://github.com/r0x0r/pywebview/pull/305

**Comment by r0x0r** [comment]
Removed and merged
