### ISSUE TITLE
lacking Python 3.5 support on OS X

### ISSUE THREAD

**Issue by aaulich** [r0x0r/pywebview#19]
Seems pywebview requires PyObjC, and when you import webview into your Python 3.5 code with pyobjc version 3.0.4, you run into the error message "Symbol not found: _PyObject_REPR".

You need to upgrade to pyobjc version 3.0.5 or later to fix this.

At the time of this writing, 3.0.5 has not officially been released, yet, so you can either wait for the official release or install a pyobjc beta like:

    pip3 install -U https://github.com/GreatFruitOmsk/pyobjc-core/releases/download/v3.0.5.dev0/pyobjc-core-3.0.5.tar.gz

Take care, that's a third party install location.

**Comment by r0x0r** [comment]
The problem seems to be gone with pyobjc 3.1.1. I am closing this.
