### ISSUE TITLE
TypeError on gui.create_window() function

### ISSUE THREAD

**Issue by emrekgn** [r0x0r/pywebview#191]
Hi,

I tried to run [examles/js_api.py](https://github.com/r0x0r/pywebview/blob/master/examples/js_api.py) on the checked out *master branch* according to the instructions described on #184 :

> 
> Try this:
> 
> 1. Download the pywebview-master zip and unzip it to a folder. Don't need to replace your Python package folder, put it anywhere.
> 2. From the root pywebview directory, run:
> PYTHONPATH=. python examples/js_api.py
> This will import the local pywebview module instead of the pip-installed one.

But it gives me this error:

```
Traceback (most recent call last):
  File "/home/emre/git/external/pywebview/examples/js_api.py", line 131, in <module>
    webview.create_window('API example', js_api=api)
  File "/home/emre/git/external/pywebview/webview/__init__.py", line 216, in create_window
    background_color, debug, js_api, _webview_ready)
TypeError: create_window() takes 10 positional arguments but 13 were given
```

OS: Linux Mint 18
Python version: 3.5.1

Thanks.
Emre

**Comment by r0x0r** [comment]
Are you sure you run the example from the root directory of the project? Try also copying the js_api.py to the project root directory and then running `python js_api.py.py`

**Comment by emrekgn** [comment]
Ok, I guess this was just another python path problem. When I copy it into the root directory, it works properly.

Thanks for the help.
