### ISSUE TITLE
problem with js_api

### ISSUE THREAD

**Issue by lpuglia** [r0x0r/pywebview#192]
I installed pywebview using pip:

`pip install git+https://github.com/r0x0r/pywebview.git`

(I'm not sure but apparently this is the only way to get the `js_api` parameter in `create_window`)

The main problem is that the folder `js` (and `lib` as well) are not copied alongside the python installation in the `site-packages` folder. Enabling the debug flag it is possible to see the error:

`IOError: [Errno 2] No such file or directory: '/opt/miniconda2/lib/python2.7/site-packages/webview/js/npo.js'`

**Comment by r0x0r** [comment]
TLDR: the JS API is not yet in production condition. Check out the master
and point your code to the checked our version if you wish to use it now.

Longer version: setup.py needs to be updated to include assets. I've
converted js files to py files in the `pyinstaller-support` branch. That
will probably take care of the JS files, but the dll needs special
treatment. I have no idea how to do at this point, so if someone has got a
better idea, help is appreciated.

**Comment by shivaprsdv** [comment]
I believe #203 closes both this issue and it's duplicate #200.
