### ISSUE TITLE
QtWebkit deprecated as of Qt5.6

### ISSUE THREAD

**Issue by Crypta-Eve** [r0x0r/pywebview#195]
Im having trouble getting pywebview to work as I am using Qt 5.10, however this does not contain QtWebkit anymore. QtWebkit was deprecated in Qt5.5 and removed in 5.6.

Is there any chance of an update to QtWebEngine?

**Comment by Crypta-Eve** [comment]
Hmmm. I got ahead of myself submitting this issue... Kinda...

I can see the code that detects QtVersion and loads the appropriate module(WebKit or WebEngine) but for some reson mine is trying to load QtWebKit despite having Qt5.10......

**Comment by Crypta-Eve** [comment]
`python3
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import webview
>>> webview.create_window("It works, Jim!", "http://www.flowrl.com")
ERROR:webview:GTK cannot be loaded
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/webview/__init__.py", line 76, in _initialize_imports
    import webview.gtk as gui
  File "/home/michael/.local/lib/python3.6/site-packages/webview/gtk.py", line 19, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
ERROR:webview.qt:PyQt5 or one of dependencies is not found
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/webview/qt.py", line 29, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
Segmentation fault (core dumped)
`

**Comment by shivaprsdv** [comment]
This is a bug in the current production code (`pywebview 1.8`). The problem is
with this line in `webview/qt.py`:
```py
 26     if float(QT_VERSION_STR[:3]) > 5.5:
```
For Qt versions 5.10+, this wrongly evaluates to `5.1 > 5.5` and pywebview is
mistaken that your Qt version is below 5.5.

This was rectified in PR #172. Your issue is likely to be solved if you use the
current `master` branch instead of the pip installed one. It would be pushed
to production code in the next release. 🙂

**Comment by Crypta-Eve** [comment]
Awesome thanks for your help. I will mark this as closed to reflect the code in master.
