### ISSUE TITLE
Getting rid of the command window 

### ISSUE THREAD

**Issue by zeon** [r0x0r/pywebview#196]
Hi,
When I launch the app there are 2 windows displayed, 1 is our main app that contains the web view the other is the parent window. My question is how can I get rid of the parent window?

Andy

**Comment by shivaprsdv** [comment]
Windows?

**Comment by zeon** [comment]
Yes on Windows OS

**Comment by r0x0r** [comment]
Google is your friend
https://stackoverflow.com/questions/764631/how-to-hide-console-window-in-python

**Comment by zeon** [comment]
we use py2exe

**Comment by zeon** [comment]
It looks like that.

![image](https://user-images.githubusercontent.com/450073/37757998-b6a5e986-2de9-11e8-8f80-0f2d14837dd4.png)

**Comment by r0x0r** [comment]
Look for an option in py2exe to hide a command window. At least pyinstaller
has got one.

**Comment by zeon** [comment]
Thanks problem solved.

**Comment by mo-han** [comment]
despite using such extra "non-console" options / mode, there's another in-code approach to do this, using `os.environ`, `sys.argv`, and `subprocess.Popen`.
- if a specific environment variable is set correctly, run the real main function code.
- if the env var is not set or incorrect, set it, and spawn a subprocess with the extractly same intact `sys.argv`, then exit.

```python
def main():
    apr.parse()
    __is_subprocess__ = '__is_subprocess__'
    if os.environ.get(__is_subprocess__) == __file__:
        _real_main()
    else:
        os.environ[__is_subprocess__] = __file__
        subprocess.Popen(sys.argv, shell=True)
```
