### ISSUE TITLE
Qt not supported on Windows

### ISSUE THREAD

**Issue by adbenitez** [r0x0r/pywebview#199]
why isn't Qt supported on Windows?
I mean, currently in `webview/__init__.py` if  `platform.system() == 'Windows'` it  don't check if `config.use_qt` is set to `True`, I have forced it to use PyQt5 and seems to work fine, am I missing something????

**Comment by r0x0r** [comment]
There has been no need.

If you think this should be remedied, consider thoroughly testing it and
submitting a PR.

**Comment by austinorr** [comment]
@adbenitez I too am in need of a working standards-compliant web ui, and I'm willing to bundle Qt into my application if necessary. I tried a naive patch to force QT5 on windows by changing some logic in the `__init__.py` file, but I haven't had success yet when trying it with the test pages. Can you share the change you made that worked for you?

**Comment by r0x0r** [comment]
I enabled QT support in the `qt-windows-support ` branch. @adbenitez @austinorr could you give it a try?

I was not able to test it myself as I could not get a working QT/Windows environment up and running.

**Comment by austinorr** [comment]
@roxor thanks for helping me out with this, your branch works! The one caveat is that it only checks the USE_QT=1 from `os.environ`. This  means that the `qt_test.py` use case of setting the backend programmatically doesn't work since there is no `reinitialize` option.

I enabled logging to show that it's working with the `pyqt5` backend.
```
(pywebview_winqt) >python qt_test.py
DEBUG:webview.qt:Using Qt5
DEBUG:webview:Using QT
```
my environment is easily reproduced on windows with `miniconda`:
```
name: pywebview_winqt
channels:
  - defaults
  - conda-forge
dependencies:
  - certifi=2018.8.24=py36_0
  - pip=18.0=py36_1
  - python=3.6.6=he025d50_0
  - setuptools=40.2.0=py36_0
  - wheel=0.31.1=py36_1
  - wincertstore=0.2=py36_2
  - vc=14.1=h21ff451_3
  - vs2015_runtime=15.5.2=3
  - pip:
    - pyqt5==5.11.2
    - pyqt5-sip==4.19.12
    - pythonnet==2.3.0
    - pywebview==2.0.3
prefix: C:\Users\aorr\Python35\envs\pywebview_winqt
```

This branch has a regression from the current master regarding the default `winforms` behavior. If i 'unset' USE_QT from my environment and try to use the default `pythonnet` based gui it no longer finds the `WebBrowserInterop` dlls for some reason. Again, i just checked master, and it's fine so I'm unsure what's causing this.

here's the interop stacktrace:
```
(pywebview_winqt) >python multiple_windows.py
Traceback (most recent call last):
  File "multiple_windows.py", line 23, in <module>
    webview.create_window('Window #1', width=800, height=600)
  File "c:\users\aorr\dropbox\python\sources\pywebview-qt-windows-support\pywebview-qt-windows-support\webview\__init__.py", line 187, in create_window
    _initialize_imports()
  File "c:\users\aorr\dropbox\python\sources\pywebview-qt-windows-support\pywebview-qt-windows-support\webview\__init__.py", line 125, in _initialize_imports
    import webview.winforms as gui
  File "c:\users\aorr\dropbox\python\sources\pywebview-qt-windows-support\pywebview-qt-windows-support\webview\winforms.py", line 37, in <module>
    clr.AddReference(interop_dll_path())
System.IO.FileNotFoundException: Unable to find assembly 'c:\users\aorr\dropbox\python\sources\pywebview-qt-windows-support\pywebview-qt-windows-support\webview\lib\WebBrowserInterop.x64.dll'.
   at Python.Runtime.CLRModule.AddReference(String name)
```
Thanks again for the support!

**Comment by austinorr** [comment]
This would fix the `qt_test.py` example. actually, this likely needs to be done for all of the other backends too.
```
elif platform.system() == 'Windows':
    if config.gui == 'qt' or config.use_qt:
        try:
            import webview.qt as gui
            logger.debug('Using QT')
        except ImportError as e:
            logger.exception('QT cannot be loaded')
            import_error = True
    elif config.gui == 'win32':
        try:
            import webview.win32 as gui
            logger.debug('Using Win32')
        except ImportError as e:
            logger.exception('PyWin32 cannot be loaded')
            import_error = True

    else:
        try:
            import webview.winforms as gui
            logger.debug('Using .NET')
        except ImportError as e:
            logger.exception('pythonnet cannot be loaded')
            raise Exception(
                'You must have either pythonnet or pywin32 installed in order to use pywebview.')
```

**Comment by austinorr** [comment]
I have made these changes to your branch here:
https://github.com/austinorr/pywebview/tree/qt-windows-support

and can PR anytime, though we should probably test this edit a bit more. I'm worried about changing the flow a bit since there's a lot going in in the init imports function.

**Comment by r0x0r** [comment]
@austinorr The branch is based on this PR https://github.com/r0x0r/pywebview/pull/247, which gets rid of the use_qt variable in favor of `PYWEBVIEW_FORCE_GUI` variable (`config.gui` in the coe). See details of the refactoring here https://github.com/r0x0r/pywebview/issues/220

But yes, you are correct that setting `use_qt` in the code does not work any more. I will look into this. To use QT, set `webview.config.gui = 'qt'` instead. 

Meanwhile can you run the test suite under QT/Windows?

**Comment by austinorr** [comment]
Oh I see, `config.use_qt` is still in the codebase, but we are using another toggle now. I didn’t realize there was an api change. Should I edit the `qt_test.py`? I can run the test suite today, but this branch still doesn’t fall back to `winforms` without editing the third flow statement. I changed it to a simpler `else` statement and in my fork included a logging statement if there had been an import error. I’ll give the tests a try later today :)

**Comment by austinorr** [comment]
@roxor all but one test pass with flying colors using QT on windows.

the offender is the `test_start.py` file in which the `evaluate_js` calls to the existing master window to get the innerText.

trace:
```
tests/test_start.py::test_start DEBUG:webview.qt:Using Qt5
DEBUG:webview:Using QT

DevTools listening on ws://127.0.0.1:55707/devtools/browser/509f3e7a-e8b4-418e-a8b1-af4995cdad0d
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:55707
js: Uncaught TypeError: Cannot read property 'innerText' of null
ERROR:tests.util:
Traceback (most recent call last):
  File "pywebview\tests\util.py", line 50, in thread
    thread_func()
  File "pywebview\tests\test_start.py", line 24, in assert_func
    assert html_result == 'Hello there!'
AssertionError
FAILED
tests/test_url_load.py::test_url_load DEBUG:webview.qt:Using Qt5
DEBUG:webview:Using QT
PASSED

================================== FAILURES ===================================
_________________________________ test_start __________________________________

    def test_start():
>       run_test(main_func, assert_func)
E       Failed: Traceback (most recent call last):
E         File "pywebview\tests\util.py", line 50, in thread
E           thread_func()
E         File "pywebview\tests\test_start.py", line 24, in assert_func
E           assert html_result == 'Hello there!'
E       AssertionError

tests\test_start.py:13: Failed
```
I also tested the example file `evaluate_js.py` to see if it worked with QT on windows, and everything runs fine. I'm not sure what to make of the `pytest` failure.

**Comment by adbenitez** [comment]
@r0x0r @austinorr sorry the late reply I was offline for a while, I hope to be more time online soon.

**Comment by r0x0r** [comment]
With Windows supporting CEF now, I reckon this is not needed any more. 
WONTDO
