### ISSUE TITLE
Listen to page load events

### ISSUE THREAD

**Issue by adbenitez** [r0x0r/pywebview#201]
There are a way to register a function to be called every time the webview loads a page that I am missing???
In my case I would like to listen to this event so I can execute `webview.evaluate_js` to reload my javascript, which is lost every time another url is loaded, but this can be useful for other users too so they can trigger some action when the page has loaded.
I know this is possible with Qt is `QWebView.loadFinished` signal, and guess it can be done with the other WebViews too.

**Comment by r0x0r** [comment]
There is a loaded event handler in each implementation, but it is not
exposed externally.
I have been thinking of implementing event system for most common events,
but it is a task for a future.
