### ISSUE TITLE
Can i use pywebview inside pyqt applications? 

### ISSUE THREAD

**Issue by Shoshin23** [r0x0r/pywebview#206]
### Specification
- Platform: Windows/Mac
- Version: 1.8

### Description
Hi, 
I'm trying to use webview inside my pyqt GUI application. Is there a way to "embed" this webview instead of the QWebView? Is there a way to suppress the creation of a new window but instead render within the application itself? 

Thanks!

**Comment by shivaprsdv** [comment]
I'm afraid not. Currently there is no way; all pywebview apps are made to be
self contained. If you look in `qt.py`, you can see that the core `BrowserView`
class itself is derived from the `QMainWindow` class.

You can make this possible by modifying the source yourself. Still it may be ad
hoc. Can you tell us more about your use-case, why you want to embed instead of
build in-house? Are there any components, widgets, etc. that you want to include
in addition to the QWebView?

**Comment by r0x0r** [comment]
Why would you need this? 
If you don't feel like dwelling into the details of QWebView, just copy the contents of qt.py into your application and remove the code related to creating window and such.

**Comment by Shoshin23** [comment]
Hi @r0x0r and @shivaprsdv, 

I need this because currently QWebView isnt accessible by any screen reader other than NVDA, because it's based on Chromium. Both JAWS and SuperNova, the most popular screen readers out there. Hence, I wanted to find a solution that would use native renderers as much as possible which is why I found this project very interesting for my use. MSHTML is accessible enough by the screen readers I mentioned above.

**Comment by r0x0r** [comment]
Windows implementation is based on WinForms and Mac implementation on Cocoa. Embedding those inside QT sounds like a difficult task to me.
For Windows I would suggest looking into a possibility embedding COM components inside a QT application and if possible, ripping code out of win32.py. For Mac, same thing but with Cocoa.

**Comment by shivaprsdv** [comment]
@Shoshin23 Is it required that you make your app in PyQt?

**Comment by Shoshin23** [comment]
Not really. It has to be a Python based GUI kit. I've tried to work with wxPython for this project but find the process of building a UI with that generally unbearable. Since PyQt was fairly easy in terms of building a UI I decided to proceed with this.

**Comment by shivaprsdv** [comment]
I suggest you use the Pywebview module alone to create your UI. Make the UI
you need using HTML/CSS.

**Comment by shivaprsdv** [comment]
@Shoshin23 Have you sorted it out? Can we close this?
