### ISSUE TITLE
WebBrowserInterop not found

### ISSUE THREAD

**Issue by Scoppio** [r0x0r/pywebview#211]
### Specification
- Platform: Windows 7
- Version: 1.8
- Python 3.6

### Description

After installing the library using the master (I mostly copy-pasted it into my virtual environment), it fixed the problem of the lack of "JS_API", but when I try to start it, the followin error happens
```

  File "C:\Users\Doomsday\Documents\GitHub\Palette-Extractor\venv\lib\site-packages\webview\winforms.py", line 35, in <module>
    clr.AddReference(interop_dll_path())
System.IO.FileNotFoundException: Unable to find assembly 'C:\Users\Doomsday\Documents\GitHub\Palette-Extractor\venv\lib\site-packages\webview\lib\WebBrowserInterop.dll'.
   at Python.Runtime.CLRModule.AddReference(String name)

```
I tried to find something that would be causing this error, but could not find anything. I tried adding the dll to my windows path, moving it to the same relative path of the file, hard coding the filepath, moving it to win32, and a few other fruitless tries...

It seens like that the CLRModule itself is unable to understand the compiled file. Is it necessary IronPython to run it? Thanks :+1:

**Comment by Scoppio** [comment]
Yes, unfortunatelly it does exists inside this specific folder. Thats what was most strange, since it only "returns" the filepath after checking it agains `if os.path.exists(...)`, so I tought that it could be a problem specifically with the clr method AddReference that would accept strings or maybe another kind of object, but no, it should accept Strings, and the path to the file was valid and the file was present in the path.

**Comment by r0x0r** [comment]
Are you running 32 or 64-bit version of Windows 7? Also what .NET do you have installed? 
I think this has to with the dll compatibility settings. The dll is compiled on 64-bit Windows 10 using default settings. The target environment has most likely to be tweaked.

**Comment by Scoppio** [comment]
Im running in a windows-7 64 bits.
I'll see if I can compile the dll in my computer to make it work.

**Comment by r0x0r** [comment]
Ok, I have checked and the target .NET framework is set to 2.0. I recompiled to x86 and update the master though. Can you check if it is any different for you?

**Comment by Scoppio** [comment]
Once I arrive home I'll verify.

2018-04-20 17:48 GMT-03:00 Roman <notifications@github.com>:

**Comment by r0x0r** [comment]
I could not reproduce this on the vanilla Windows 7 32-bit

**Comment by Scoppio** [comment]
It is workig wonderfully now with the new dll file.
I also tried compiling it in my own machine, same great result.

Thanks for your support Roman.

2018-04-26 4:40 GMT-03:00 Roman <notifications@github.com>:
