### ISSUE TITLE
add support for OpenBSD 6.x

### ISSUE THREAD

**Issue by hucste** [r0x0r/pywebview#213]
### Specification
- Platform: OpenBSD
- Version: 6.2, 6.3

### Description
Cant install! 

See this:
```
$ python3 -m pip install -U pywebview 
Collecting pywebview
  Using cached pywebview-1.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dn5vt0ol/pywebview/setup.py", line 29, in <module>
        extras_require=extras_require,
    NameError: name 'extras_require' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dn5vt0ol/pywebview/

```

It seems necessary to modify your ''setup.py'' to add an extras as practically Linux. 

We have modules python3:
- py3-gobject3
- py3-qt5

;)

**Comment by vv221** [comment]
I think the main issue is with the structure of the 'extras_require' definition: an 'if/elif/elif' block without an 'else' statement is prone to error and will break on some exotic configurations.

A simple 'else' statement interrupting the script execution and displaying an error like "Your system does not seem supported. Supported systems are: …" would avoid confusion.

**Comment by shivaprsdv** [comment]
Good point. May be @r0x0r wrote it this way because pywebview explicitly
supports only those there platforms. But I can't see why a BSD with Gtk/Qt
be denied the opportunity to experiment.

@hucste Meanwhile have you tried if it works by cloning the repo locally?

**Comment by hucste** [comment]
@shivaprsdv no, i'm going!

**Comment by hucste** [comment]
Ok, i installed py3-qt5! It seems ok... 
py3-gobject3 was intalled, previously... but, the script cant detect it!

----

I add "or platform.system() == 'OpenBSD':" into '\_\_init\_\_.py' at line 78. 
Egual, into 'qt.py'... into lines 34 and 158, because i dont know the reason but even QT version is 'QT Version: [5, 9, 1]', it cant import this: 
`from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView`

> ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

----

To resume, if wrote '\_\_init\_\_.py' script, line 78 as:
`       elif platform.system() == 'Linux' or platform.system() == 'OpenBSD':`

And modify 'qt.py' script, after adding `import platform`, line 34, and 158, as: 
`    if _qt_version >= [5, 5] and platform.version() == 'Linux':`

this code into test.py run correctly and display webview, with thoses errors: 
```
import webview
webview.create_window("It works, Jim!", "http://www.flowrl.com")
```

> $ ./test.py  
> ERROR:webview:GTK cannot be loaded
> Traceback (most recent call last):
>   File "/home/zou/Documents/Dev/NotMine/pywebview/webview/__init__.py", line 81, in _initialize_imports
>     import webview.gtk as gui
>   File "/home/zou/Documents/Dev/NotMine/pywebview/webview/gtk.py", line 24, in <module>
>     gi.require_version('WebKit', '3.0')
>   File "/usr/local/lib/python3.6/site-packages/gi/__init__.py", line 130, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace WebKit not available
> Segmentation fault (core dumped) 
>

**Comment by r0x0r** [comment]
I have zero experience with BSD systems, but if you create a PR I will
gladly accept it. Regarding your question, in addition to gobject, you need
to have WebKit installed as well. On Debian based systems the package name
is gir1.2-webkit-3.0.

Note that there is currently a ticket open for a WebKit 2 upgrade for GTK
(WebKit 4.0 I believe), so please investigate this option as well to make
it future proof.

**Comment by shivaprsdv** [comment]
@hucste I did a bit of googling, but I couldn't find a QtWebEngine port for
OpenBSD. PyQt5 requires it, that is why the error:
> ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

So the best thing would be to follow Roman's advice to use gobject with the
webkit dependency.

**Comment by hucste** [comment]
@shivaprsdv but it run with 'from PyQt5.QtWebKitWidgets import QWebView' ;)

On OpenBSD 6.x,  webkit (webkit-2.x, webkit-gtk3-2.x) is not installed because is known to have many security vulnerabilities that will NOT be fixed. Avoid browsing with it!!!
But we have webkitgtk4-2.18.0 ;)
without link with python... 

At minimum, we can use pyqt5! :D

**Comment by shivaprsdv** [comment]
Right, but the problem is this won't work in PyQt 5.5+, because QtWebKitWidgets
was removed after that. I thought you said you had Qt 5.9.1. Yet this is working?

**Comment by hucste** [comment]
```
$ pkg_info -Q py-qt5
py-qt5-5.9p1 (installed)
$ pkg_info -Q py3-qt5        
py3-qt5-5.9p1 (installed)

```

Do you want a screenshot to see what i have with the code into my PR?
Have you seen my modifications?!

**Comment by shivaprsdv** [comment]
Yes I have, but I too have zero experience with BSD's, so I can only take your
word that it works. If you have tested it enough, we are good to go. 🙂

**Comment by hucste** [comment]
Just 4u: ;)
see this [screenshot](https://framapic.org/vbuNRtlRhLGu/iuYmb5AisLna)! :p 

FYI: when i close the windows, i've this error: 
> Segmentation fault (core dumped) 

But, it's not necessary a bug pywebview, isnt-it?!

**Comment by shivaprsdv** [comment]
Great! Now we have merged your modifications, I am closing this issue.
Good luck with exploring pywebview on OpenBSD. 👍 

No, the Segmentation fault error when closing the windows is not likely a
pywebview issue, because it doesn't show up in other platforms. Probably
there is a problem with the end cleaning-up. But unfortunately we cannot
investigate, as we said, we haven't got OpenBSD.

**Comment by hucste** [comment]
@shivaprsdv : not a problem! ;)
Thank you for your help :D
