### ISSUE TITLE
Version Check in Code fails for QT Version later than 5.9

### ISSUE THREAD

**Issue by Semnodime** [r0x0r/pywebview#214]
### Specification
- Platform: Platform independet
- Version: latest master

### Description
A version check in the code fails on QT Version later than 5.9
From [qt.py](https://github.com/r0x0r/pywebview/blob/master/webview/qt.py):

![image](https://user-images.githubusercontent.com/19511852/38770274-ba80f378-4010-11e8-8275-b3676296cba7.png)

My patch:
![image](https://user-images.githubusercontent.com/19511852/38770320-7361294e-4011-11e8-9d37-8b782c3eac06.png)

I will create a pull request after I can reference this issue in the patch branch name.

**Comment by shivaprsdv** [comment]
@Semnodime This bug is already fixed. It was merged to master sometime
ago: in #172. The latest master contains the patch (same as your solution):
![screen shot 2018-04-14 at 11 22 40 pm](https://user-images.githubusercontent.com/18247990/38771140-2c26e49a-403b-11e8-9bd8-2cf4008d5a22.png)
