### ISSUE TITLE
can't copy 'webview\lib\WebBrowserInterop.x64.dll'

### ISSUE THREAD

**Issue by Code-ReaQtor** [r0x0r/pywebview#219]
### Specification
- Platform: Windows
- Version: 10
- Python 3.6.4
- pip 10.0.1

### Description
Installing `pywebview 2.0` fails on Windows 10 64-bit using `pip install pywebview`. The following error occurs:
`error: can't copy 'webview\lib\WebBrowserInterop.x64.dll': doesn't exist or not a regular file`

Similar error occurs using `easy_install pywebview`:
`error: Setup script exited with error: can't copy 'webview\lib\WebBrowserInterop.x64.dll': doesn't exist or not a regular file`

**Comment by denfromufa** [comment]
@Code-ReaQtor confirmed - the package on PYPI is missing the pywebview\lib folder:

![image](https://user-images.githubusercontent.com/7870949/39734560-6cdf6d72-523d-11e8-85e8-8443dfe37696.png)


In the meantime install directly from github:

pip install git+https://github.com/r0x0r/pywebview

**Comment by shivaprsdv** [comment]
Ditto. Thanks for the tip. Hopefully Roman will fix it ASAP.

**Comment by mdigi** [comment]
After installing from github I get an error when running my project:
`Exception: Cannot find WebBrowserInterop.dll`

I'm using:
- Windows 10
- python 3.6.5

**Comment by r0x0r** [comment]
I just released a new verison 2.0.1, which includes the libs folder, but alas it is copied to a wrong location. 
On that note I really should be using test PyPi instead of production.

**Comment by r0x0r** [comment]
Ok, 2.0.2 should fix the issue.

**Comment by mdigi** [comment]
The lib folder still is not copying for 2.02, but I think I fixed in this [PR](https://github.com/r0x0r/pywebview/pull/221)

**Comment by r0x0r** [comment]
@mdigi, are you sure you have installed 2.0.2 and not the cached version of 2.0.1? I cannot reproduce the problem any more with the fresh install of 2.0.2. Here is the output 

 ```
$ pip install pywebview
Collecting pywebview
  Downloading https://files.pythonhosted.org/packages/7a/6e/5acc1143938c41201d4ba7dae8ddfa5845532f4cba6aa591fcfc754bf433/pywebview-2.0.2.tar.gz
Installing collected packages: pywebview
  Running setup.py install for pywebview: started
    Running setup.py install for pywebview: finished with status 'done'
Successfully installed pywebview-2.0.2
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

IEUser@MSEDGEWIN10 MINGW64 ~/Code/pywebview/examples (debug-windows-tests)
$ pip show -f pywebview
Name: pywebview
Version: 2.0.2
Summary: A cross-platform lightweight native wrapper around a web view component
Home-page: http://github.com/r0x0r/pywebview
Author: Roman Sirokov
Author-email: roman@flowrl.com
License: New BSD license
Location: c:\users\ieuser\appdata\local\programs\python\python36-32\lib\site-packages
Requires:
Files:
  pywebview-2.0.2-py3.6.egg-info\PKG-INFO
  pywebview-2.0.2-py3.6.egg-info\SOURCES.txt
  pywebview-2.0.2-py3.6.egg-info\dependency_links.txt
  pywebview-2.0.2-py3.6.egg-info\requires.txt
  pywebview-2.0.2-py3.6.egg-info\top_level.txt
  webview\__init__.py
  webview\__pycache__\__init__.cpython-36.pyc
  webview\__pycache__\cocoa.cpython-36.pyc
  webview\__pycache__\gtk.cpython-36.pyc
  webview\__pycache__\localization.cpython-36.pyc
  webview\__pycache__\qt.cpython-36.pyc
  webview\__pycache__\util.cpython-36.pyc
  webview\__pycache__\win32.cpython-36.pyc
  webview\__pycache__\win32_gen.cpython-36.pyc
  webview\__pycache__\win32_shared.cpython-36.pyc
  webview\__pycache__\winforms.cpython-36.pyc
  webview\cocoa.py
  webview\gtk.py
  webview\js\__init__.py
  webview\js\__pycache__\__init__.cpython-36.pyc
  webview\js\__pycache__\alert.cpython-36.pyc
  webview\js\__pycache__\api.cpython-36.pyc
  webview\js\__pycache__\css.cpython-36.pyc
  webview\js\__pycache__\npo.cpython-36.pyc
  webview\js\alert.py
  webview\js\api.py
  webview\js\css.py
  webview\js\npo.py
  webview\lib\WebBrowserInterop.x64.dll
  webview\lib\WebBrowserInterop.x86.dll
  webview\localization.py
  webview\qt.py
  webview\util.py
  webview\win32.py
  webview\win32_gen.py
  webview\win32_shared.py
  webview\winforms.py
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by mdigi** [comment]
@r0x0r, you're right it is working now - must have been a cached version. Thanks!

**Comment by Code-ReaQtor** [comment]
@r0x0r 2.0.2 verified! Thanks.
