### ISSUE TITLE
what do I need to make pywebview work with pypiwin32

### ISSUE THREAD

**Issue by imagitol** [r0x0r/pywebview#22]

**Comment by imagitol** [comment]
I am using pypiwin32 but if I attempt to <code>pip install pywebview </code>it aborts as it does not find <code>pywin32</code>

I downloaded the <code>zipped files</code> and changed setup.py locally and it appears to install, but then run in to a problem with <code>comtypes</code> not working correctly with <code>python3.4</code> - this has already been raised as an issue https://github.com/enthought/comtypes/issues/92 

Not too sure what next steps to take to get <code>pywebview</code> running with <code>pypiwin32</code> and <code>python3.4</code>

**Comment by r0x0r** [comment]
Sorry cannot help right now, as I am travelling. I will take a look at this
when I get back.

**Comment by r0x0r** [comment]
As nothing seems to be happening on the comtypes front, I will look into getting rid of comtypes altogether.

**Comment by r0x0r** [comment]
I have looked into comtypes and there are too many dependencies to copy them verbatim. I am afraid nothing can be done about it, until this issue is fixed.

I have modified setup.py to use pypiwin32 instead of pywin32, though. Thanks for the heads up. 

I will close this issue now.

**Comment by r0x0r** [comment]
The fix has been pushed to the master branch of comtypes, but there's no official release yet. I was unable to install comtypes from the master branch, but by copying and pasting the [fix](https://github.com/enthought/comtypes/pull/95/files) I got it working just fine.
