### ISSUE TITLE
Use Qt GUI per default on Qt-based systems

### ISSUE THREAD

**Issue by flying-sheep** [r0x0r/pywebview#220]
Users on e.g. Plasma or LXQt want this to use Qt without having to define a environment variable.

**Comment by shivaprsdv** [comment]
You don't really need the environment variable, you could put:
```py
webview.config.use_qt = True
```
at the top of your script, as in the `qt_test.py` example.

Anyway if PyGObject is missing, as it is likely on Qt-based systems, pywebview
will default to PyQt.

**Comment by flying-sheep** [comment]
i respectfully disagree in both points:

- on many systems, quite some stuff is installed, which might include pygobject as some dependency. i have it, and i try to keep GTK out as much as feasible
- I know that it’s easy to do progammatically for individual pieces of software, but i want the default to be sensible. Qt on a Qt system, GTK on a GTK system

sadly the `desktop` package is very old, else we could have used that.

the only thing i know out of the top of my head is that if `KDE_FULL_SESSION` is defined, it should be treated as `USE_QT`.

**Comment by shivaprsdv** [comment]
Yes, that makes sense. I'm a school kid in the Linux user land, so thanks
for the tip. Your suggestion is definitely feasible.

**Comment by r0x0r** [comment]
How would you detect which one to default to?

**Comment by r0x0r** [comment]
Done

**Comment by adbenitez** [comment]
I think this most to be analyzed more carefully, what about if now comes a programmer saying that he don't want to use QT if GTK is available??? 
With this approach we can't know if `use_qt` was set by the programmer or by pywebview, also giving an error in a virtual environment with GTK but without QT.
A better approach could be simply check for QT before for GTK in this "Qt-based" systems (with a list of 2 functions and changing the order based on `KDE_FULL_SESSION`, as an example), this way we can know if the programmer wants explicitly  to use QT (and throwing an error if is missing) or just try to use GTK if QT is missing.
This is just a recommendation so feel free to just ignore it :)

**Comment by r0x0r** [comment]
This is a valid point.
QT used to be default, but I switched to GTK at some point, as I felt it
was more popular (I blame Ubuntu). I would not like to make a switch back,
unless somebody convinces me on the QT superiority :)
A crude solution would be to introduce a USE_GTK variable that would force
GTK on QT-based systems, while keeping the current preference order.

**Comment by flying-sheep** [comment]
sure, optimally:

- the default depends on your DE, with some smart detection going on
- an environment variable can be used to override the default and ensure that a specific GUI is used (at the moment, there’s no way to select GTK explicitly)
- you can use python code to do the same

the current behavior is better than before, since it partly implements the first point. now we just need to figure out how to fully implement the second one. options i can come up with:

- `USE_QT=(|yes|1|[tT]rue|no|0|[fF]alse)` (where `USE_QT=` i.e. empty means yes). a possible issue here is that GTK isn’t explicitly mentioned
- `USE_QT=.*` and `USE_GTK=.*`. what if both are specified? fall back to the default?
- `PYWEBVIEW_GUI=([qQ]t|gtk|GTK)`. `USE_QT` already exists and we need to fall back on it if `PYQWEBVEW_GUI` is not defined.

**Comment by shivaprsdv** [comment]
As we would now have 4 options (Qt on GTK, GTK on Qt, and the defaults), it
is impractical to carry on with booleans. So I guess @flying-sheep's last one
is the most feasible. As there is also a proposal for [Qt on Windows](https://github.com/r0x0r/pywebview/issues/199), this param
has a bit more scope.

If this is implemented, `USE_QT` could be deprecated, I don't mind the fuss
on backwards compatibility, I don't think it's that heavily used.

**Comment by adbenitez** [comment]
r0x0r introducing a `USE_GTK` variable can be a quick way to solve this

**Comment by adbenitez** [comment]
shivaprsdv well that way it will be more easy even to add new options in the future

**Comment by shivaprsdv** [comment]
May be, yeah, but I think it would become a headache to implement. Less the
number of options, less `if` blocks, and much easier life for _us_. 😉

**Comment by adbenitez** [comment]
done! I haven't tested this too much because qt webview isn't working in current master branch... only to me??

**Comment by r0x0r** [comment]
I would like to keep it simple, ie add USE_GTK variable and call it a day. The defined order of preference would be then.

USE_GTK -> GTK 
KDE_FULL_SESSION or USE_QT -> QT
Nothing - 1. GTK 2. QT
USE_GTK and USE_QT -> 1. GTK 2. QT

I don't think introducing PYWEBVIEW_GUI variable is a good idea

**Comment by flying-sheep** [comment]
i prefer `PYWEBVIEW_GUI` as it’s unclear what e.g. `USE_GTK` and `USE_QT` mean. also we’d have to add variables for everything new.

`PYWEBVIEW_GUI` is one single variable with clear meaning. order of preference:

1. `PYWEBVIEW_GUI`
2. `USE_QT` for backwards compatibility
3. `KDE_FULL_SESSION` and later other DE indicators
4. GTK for linux, and the native things for windows and OSX

much clearer IMHO

**Comment by r0x0r** [comment]
You have got a point there.
I introduced these variables as a quick way to select a non-default GUI without giving much thought to the architecture. My main objection is the PYWEBVIEW_GUI name itself, but to be honest I cannot think of anything better.

**Comment by r0x0r** [comment]
One issue with PYWEBVIEW_GUI is that possible values shall be set in stone. There are at least 'qt' and 'gtk', but what about the rest? Are they needed at all, as on other platforms GUI selection is done automatically?

**Comment by shivaprsdv** [comment]
I don't think so. This ought to be an optional param. A better name would be
`FORCE_GUI` or `FORCE_DE` or even `USE_GUI`, with functionality just to
force enable a particular non-default framework. In its absence, the order of
preference should be what it is now.

**Comment by adbenitez** [comment]
@r0x0r "I don't think introducing PYWEBVIEW_GUI variable is a good idea" 
The current implementation have some problems: suppose I want to use QT on GNU/Linux I then set `USE_QT` but for users on OSX that don't have PyQt installed the program will crash instead of trying cocoa, and the same for Windows users with `USE_WIN32`, what I mean is that pywebview doesn't try other options if `USE_*` is set.
I think that if someone prefer to QT over GTK anyway will prefer GTK if QT isn't present, that is better than a crash :) 
My PR using `PYWEBVIEW_GUI`, or any other name you prefer, solve this: #227

**Comment by r0x0r** [comment]
@adbenitez, 
Platform specific gui toolkit can be controlled in code using config and platform specific conditions, eg.

```
if sys.platform == "Linux":
  webview.config.force_gui = "qt"
```

I agree though that if the forced GUI is not found, then a default fallback should be attempted before failing.  

Regarding the name, `FORCE_GUI` is a good choice for an environmental variable (`config.force_gui` in the code). I am undecided whether it should be `PYWEBVIEW_FORCE_GUI` to make the name unique enough though.

**Comment by flying-sheep** [comment]
if there is anything used by multiple applications, we could use that.

but if not, we shouldn’t try to invent our own “standard” and stick to a prefixed/unique variable name.

libreoffice for example uses `OOO_FORCE_DESKTOP={gnome,kde,none}`

**Comment by shivaprsdv** [comment]
One last suggestion: what about abbreviating `PYWEBVIEW_FORCE_GUI` to
say, `PWV_FORCE_GUI`? The former feels a bit long. Otherwise ok.

**Comment by r0x0r** [comment]
I don't like the length of `PYWEBVIEW_FORCE_GUI ` either, but `PWV_FORCE_GUI ` is too cryptic, considering the acronym is not used anywhere else.

**Comment by shivaprsdv** [comment]
Not to me, I use the acronym frequently in my local workstation. 😉 The long
version is fine.

**Comment by adbenitez** [comment]
guys I think this most to be more to set preference order instead to force one specific gui, so it most to accept multiple values like `PYWEBVIEW_FORCE_GUI='qt|win32'` which means try to use qt and if isn't present then try win32, and try winforms only if win32 isn't present.

**Comment by r0x0r** [comment]
@adbenitez To be honest I see no point in multiple values. This is a developer, not a user setting after all and a developer has to make a concise choice which one to use anyway.  Besides I will remove the win32 support at some point.

**Comment by shivaprsdv** [comment]
Second that. Only a single-valued flag to force *one* non-default gui.

**Comment by adbenitez** [comment]
fine then, but please I think it most at least to try other options if the forced gui isn't present instead of crashing. BTW what about gtk on Windows? any plans on support it?

**Comment by adbenitez** [comment]
well I will close my PR so sorry not to be useful at all :(

**Comment by flying-sheep** [comment]
Well, your code is reasonably close to the suggested solution, so I’m sure we can profit from it!

You misunderstood the proposed solution though: https://github.com/r0x0r/pywebview/issues/220#issuecomment-391285486

It says that an exception is thrown only if bboth the forced GUI option and the platform default fail to load.

**Comment by shivaprsdv** [comment]
Exactly. @adbenitez If you could modify your commit to address this solution
and resubmit your PR, we'd be glad to test and accept it. 🙂

**Comment by adbenitez** [comment]
sorry guys, but I actually don't have my own PC my pywebview fork is in the laptop of my girlfriend which is far from me this days, I am in a lab at my University, the only way to internet here is this browser, but you can modify my PR or take what you think is fine and make your own PR it doesn't matter who make the PR what matters is to make pywebview better.

**Comment by r0x0r** [comment]
I refactored the import logic once again to make it more robust. Thanks to @adbenitez for the inspiration. 

I will keep PR opened for a couple of more days, if no comments are received.
