### ISSUE TITLE
Pyinstaller hook

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#225]
Let's create a hook for pyinstaller to help it find all the needed dependencies automatically. On Windows that will take copying WebBrowserInterop dlls and Python.Runtime.dll of pythonnet. Other platforms probably work out of the box. Freezing with the --onefile option should be fixed as well. 

Here is a starting point for pyinstaller's hooks
https://pythonhosted.org/PyInstaller/hooks.html

Anybody have prior experience with hooks and is willing to help?

**Comment by denfromufa** [comment]
@r0x0r pyinstaller already has pythonnet hook, you can follow the same pythonnet pattern for your interop dlls in pywebview:

https://github.com/pyinstaller/pyinstaller/issues/1801
https://github.com/pyinstaller/pyinstaller/pull/2048/files

**Comment by tjohnsonhvac** [comment]
@r0x0r Its been a while since I've been on here but I updated the pyinstaller bat file to include the most recent updates of pywebview. 
I copied the js and lib folder from the webview folder in site-packages into my script directory.

```bash
pyinstaller --noconfirm --log-level=DEBUG ^
    --onefile ^
    --add-data="webview/lib/WebBrowserInterop.x64.dll;webview/lib" ^
    --add-data="webview/lib/WebBrowserInterop.x86.dll;webview/lib" ^
    --add-data="webview/js/__pycache__/__init__.cpython-36.pyc;webview/js/__pycache__" ^
    --add-data="webview/js/__pycache__/alert.cpython-36.pyc;webview/js/__pycache__" ^
    --add-data="webview/js/__pycache__/api.cpython-36.pyc;webview/js/__pycache__" ^
    --add-data="webview/js/__pycache__/css.cpython-36.pyc;webview/js/__pycache__" ^
    --add-data="webview/js/__pycache__/npo.cpython-36.pyc;webview/js/__pycache__" ^
    --add-data="webview/js/__init__.py;webview/js" ^
    --add-data="webview/js/alert.py;webview/js" ^
    --add-data="webview/js/api.py;webview/js" ^
    --add-data="webview/js/css.py;webview/js" ^
    --add-data="webview/js/npo.py;webview/js" ^
    --add-data="GUI/index.html;GUI" ^
    --add-data="GUI/js/lib/jquery-3.2.1.min.js;GUI/js/lib" ^
    --hidden-import=clr ^
    --manifest="manifest.xml" ^
    --version-file="file_version_info.txt" ^
    --icon="YOUR_ICON_HERE.ico"^
    YOUR_SCRIPT.py
```
Hopefully this info can help someone else trying to create a onefile .exe

**Comment by austinorr** [comment]
the only line needed for the hook file is this:
```
binaries += collect_dynamic_libs("webview", ".")
```
this works great in my spec file for both onedir and onefile builds, and could easily be made into a hook-webview.py file and pushed upstream to `pyinstaller`

**Comment by fgrzadkowski** [comment]
@austinorr I added line you suggested, but I still get an error when running my app:

```
ERROR:webview:GTK cannot be loaded
Traceback (most recent call last):
  File "webview/__init__.py", line 66, in import_gtk
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "webview/gtk.py", line 25, in <module>
  File "gi/__init__.py", line 79, in require_version
ValueError: Namespace WebKit not available
ERROR:webview:QT cannot be loaded
Traceback (most recent call last):
  File "webview/__init__.py", line 79, in import_qt
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "webview/qt.py", line 68, in <module>
ImportError: This module requires PyQt4 or PyQt5.
Traceback (most recent call last):
  File "ui.py", line 37, in <module>
  File "webview/__init__.py", line 219, in create_window
  File "webview/__init__.py", line 152, in _initialize_imports
Exception: You must have either QT or GTK with Python extensions installed in order to use pywebview.
[23678] Failed to execute script ui
Exception in thread Thread-1:
Traceback (most recent call last):
  File "webview/__init__.py", line 177, in wrapper
  File "webview/__init__.py", line 280, in load_html
NameError: name 'gui' is not defined
```

To make sure I isolate this, I build it inside ubuntu docker container:
```
FROM ubuntu:trusty

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y wget python3 python3-dev python3-pip python3-gi python3-gi-cairo gir1.2-webkit-3.0

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip3 install -r requirements.txt
RUN pip3 install pyinstaller

# This image assumes that source files will be mounted in /usr/src/app
CMD [ "pyinstaller", "control-server-ui.spec", "-n", "control-server-ui" ]
#CMD [ "pyinstaller", "src/ui.py", "-n", "control-server-ui" ]
```

requirements.txt:
```
pywebview
pytest
```

control-server-ui.spec:
```
# -*- mode: python -*-
from PyInstaller.utils.hooks import collect_dynamic_libs

block_cipher = None


a = Analysis(['src/ui.py'],
             pathex=['/usr/src/app'],
             binaries=collect_dynamic_libs('webview', '.'),
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='control-server-ui',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='control-server-ui')
```

**Comment by austinorr** [comment]
I notice two things: the first is that your building on Debian, which should mean that you don’t need the windows interop binaries to be included in your bundle. The second is that your traceback says that you don’t have any of the backends available in the environment your running the program from. Are you running it from a headless docker container that doesn’t even have a windowing library? Or are you just building it there and running it on your regular daily driver computer?

**Comment by austinorr** [comment]
@fgrzadkowski were you able to find a solution that worked for your build?

**Comment by r0x0r** [comment]
I have created a hook. PR here.
https://github.com/pyinstaller/pyinstaller/pull/3771

**Comment by austinorr** [comment]
@r0x0r great work, this hook should help me drop a couple lines from my spec file :) I'm not very familiar with the `ctypes` library, but from what I could see it's doing a lot of the same things as the `collect_dynamic_libs` function from `pyinstaller.utils.hooks`. Did you try that function in the hook and find that it didn't work? I really thought this hook could be a near one-liner; two with the `if is_win` line.

**Comment by r0x0r** [comment]
@austinorr I copied the pythonnet solution almost verbatim and verified that it works. It can probably be simplified. ctypes can probably be omitted altogether, as the dll discovery takes place in the else clause me thinks. Feel free to contribute it.

**Comment by r0x0r** [comment]
PR merged into dev. I am closing this issue now.
