### ISSUE TITLE
toggle_fullscreen doesn't work as expected

### ISSUE THREAD

**Issue by lt94** [r0x0r/pywebview#232]
### Specification
- Platform: winforms
- Version: 2.0.3

### Description

I just ran the example of todos. It came error and existed unexpectedly,when I clicked the to *full screen* button twice. The window didn't resize as beginning and just stop work. Should I make a PR for this?

**Comment by r0x0r** [comment]
It seems like a timing issue related to changing the window size. If you wait a couple of seconds before clicking the fullscreen button the second time, it will work as expected. Similarly adding print statements to the toggle_button code mostly fixes the problem.

I will investigate this issue.

**Comment by lt94** [comment]
I thougt i hadn't explained  what it happended well. It just came error when i clicked the *full screen* button even if i waited a couple of seconds.  BTW, it happended under win10.
