### ISSUE TITLE
Debug is broken on QT

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#233]
Ubuntu 17.10 
QT 5.9.1

There is a missing parameter in the debug window initialization, which is fixed in this PR https://github.com/r0x0r/pywebview/pull/231, but debug functionality is broken nonetheless. 

1) The debug window does not render anything apart from some blue buttons
2) js: Uncaught ReferenceError: jstProcess is not defined error is reported

**Comment by shivaprsdv** [comment]
Fixed.

**Comment by shivaprsdv** [comment]
Any idea why the tests keep failing?

**Comment by r0x0r** [comment]
It looks like a race condition issue. Looking into it.
