### ISSUE TITLE
Opening link inside webview

### ISSUE THREAD

**Issue by fxshpac** [r0x0r/pywebview#235]
### Specification
- Platform: Windows
- Version: pywebview 2.0.3 on Python 2.7.15

### Description
When I click a url link inside the webview, my default browser opens up with that link. Is this possible to let the webview to load the link instead? Sorry if this question has been answered before. I did the search but couldn't find one similar to this so I figure I open an new one for that. Thanks for your great work.

**Comment by shivaprsdv** [comment]
Only links with `target="_blank"` will open in an external browser. Do you have
any control over the HTML loaded into the webview? Then you could simply set
`target="_self"` on the links. I guess this is not likely your case. Currently there
is no functionality built into pywebview to redirect all links to the host webview.
Have you checked if this can be done with JavaScript?

**Comment by fxshpac** [comment]
So my test.py looks like this:

```
import webview
webview.create_window("test", "test.html")
```

and test.html looks like this:

```
<!DOCTYPE html> 
<html> 
<body> 
<p>
<a href="https://www.bigbuckbunny.org/" target="_blank">Big Buck Bunny</a>.
</p>
</body> 
</html>
```

The file test.html is loaded by webview just fine but when I click the link "Big Buck Bunny", my default external browser gets to open the link.

**Comment by fxshpac** [comment]
So it does look like the behavior is expected with target= is set in the link. After removing it, it loads in webview now. Thanks for pointing out this. I wouldn't what that was.

**Comment by shivaprsdv** [comment]
Yes, just remove the `target` attribute. This feature was only recently added
as a matter of convenience. I hope we can close this now. 🙂
