### ISSUE TITLE
load html and execute js_api problem on the  2nd/third/... time the window creation

### ISSUE THREAD

**Issue by fordffx** [r0x0r/pywebview#237]
### Specification
- Platform:windows 7
- Version:2.03

### Description 
#load html and execute js_api problem on the  2nd/third/... time windows creation:
def loadhtml():
-- webview.load_html('<h>1st window html text</h>')
t = threading.Thread(target=loadhtml)
t.start()

webview.create_window('1st window', js_api=api)
#window creation and display succeeded, and html text displayed,
if webview.window_exists(uid='master'):
-- webview.load_html('<h>2nd window html text</h>', uid='master')

webview.create_window('2nd window')
#window creation and display succeeded, but no html text displayed,

#----------------------------------------------------------
#Q1: how can I load html in the second and the third  windows
#Q2: how can I load html in the way below :
if __name__ == '__main__':
--while True:
---- if event.type == MOUSEBUTTONDOWN:
------ if pressed_mouse[0]:
-------- t = threading.Thread(target=loadhtml)
-------- t.start()
-------- webview.create_window('Always this  window, diffrent js_api', js_api=api)
                #When the 1st time I click my right mouse button ,window creation and display succeeded, and html text displayed, but when the 2nd/... time  I click my right mouse button , window creation and display succeeded, no html loaded. how can I load the html and execute js_api the 2nd/... time right mouse button clicked?

**Comment by romansirokov** [comment]
Sorry I don't quite follow your code, but have you checked `examples/multiple_windows.py`? It has the case you describe.

**Comment by r0x0r** [comment]
Sorry I don't quite follow your code, but have you checked `examples/multiple_windows.py`? It has the case similar to what you describe.

**Comment by fordffx** [comment]
[1.txt](https://github.com/r0x0r/pywebview/files/2115983/1.txt)
Run this please,I can't make html displayed the second time and later

**Comment by r0x0r** [comment]
Two things.
You create a main window only once. 
You are missing a window creating function in the thread function

Read the example file I linked earlier.

**Comment by shivaprsdv** [comment]
The first call to `webview.create_window()` blocks. Your `for` loop blocks at
the first iteration itself. You can see window 2, 3, etc only after you close the
first, right? If you want to load html into those windows, you have to store the
uid of the window returned by `create_window` and pass it to `load_html`.
Also, a better threading model would be to call the new `create_window`s on
the thread, like below:

```py
import threading
import webview


def loadhtml():
    webview.load_html('Hello from master')      # Load HTML to master window, no uid needed
    for i in 2, 3, 4, 5:
        uid = webview.create_window('window name', width=304, height=59)    # create new window, store the return value (uid)
        webview.load_html('Hello from ' + uid, uid=uid)     # call load_html with the returned uid


if __name__ == '__main__':
    t = threading.Thread(target=loadhtml)   # Thread that carries out application logic, i.e. opening window 2, 3, ...
    t.start()
    webview.create_window('master window', width=304, height=59)    # master window, blocks program execution
```
This is very similar to the example file r0x0r mentioned. Please check that.

**Comment by fordffx** [comment]
Thank you guys, @shivaprsdv @r0x0r . I changed some code, andthat is the way i prefered of using 'mater' window. I think this could be a typical example,right?
Please run this file:  
[right way of using master window again and again.txt](https://github.com/r0x0r/pywebview/files/2118025/right.way.of.using.master.window.again.and.again.txt)
