### ISSUE TITLE
Playing Video

### ISSUE THREAD

**Issue by shmrymbd** [r0x0r/pywebview#239]
### Specification
- Platform: raspbian
- Version:

### Description

I'm trying to load a video using `<video>`, but not sure how. I'm trying this with a local file. Is this a limitation?

i am using remi GUI. pls advice

**Comment by r0x0r** [comment]
Tested with a locally served/http served mp4 video and Ubuntu and found no problems. If you cannot play a video, I think the reason is missing codecs.
I am closing this issue now. If the problem still persists and you have additional info, feel free to reopen it.
