### ISSUE TITLE
Event listener feature?

### ISSUE THREAD

**Issue by raintears** [r0x0r/pywebview#240]
I'm trying to monitor when user logout from the url loaded in the webview. Electron has event listener so I wonder if pywebview has it?

**Comment by shivaprsdv** [comment]
Sorry, we don't have event listeners at the moment. This has already been asked
in #201, please read [this comment](https://github.com/r0x0r/pywebview/issues/201#issuecomment-375012576) to know our take on this.

Can you specify which event you want to monitor? Have you checked if it can be
done with Javascript itself?

**Comment by raintears** [comment]
Nope, can't be done with js that's why I'm looking at python. During event callback, I need to execute os operations like file deletion using python. Is there a workaround to at least know when the url has changed?

**Comment by shivaprsdv** [comment]
If you only want to call Python code from JS, there is an API for that without
using any event listeners; just see the Readme. But if you certainly want to
monitor the page-navigation event, and you are unable to do just that in JS,
I am afraid currently there is no other way.

But this event is indeed being handled internally at the moment. So you can
tweak the source a bit and expose it to your code if you need. 🙂

**Comment by raintears** [comment]
can you point me to where that is in the source? Cos I need the callback trigger whenever the url of the main frame changes.

**Comment by r0x0r** [comment]
There's a `loaded` / `load_event` in each GUI implementation. It fires on a page load and you can probably wait on it to achieve that you want. 

Bear in mind that it is for internal use only. Something more robust (e.g. observer) should be put as a public interface.

**Comment by r0x0r** [comment]
Let's move the discussion to #201
