### ISSUE TITLE
Edge support for Windows

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#243]
Microsoft has finally added support for hosting UWA controls in Windows Forms / WPF apps. Will be most appreciated if someone can test drive this. 

https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls

**Comment by r0x0r** [comment]
The above docs are not clear on this, but apparently this requires .NET Core 3, which is not released yet.

**Comment by shivaprsdv** [comment]
This is good news.. Winds of change 🙂

**Comment by austinorr** [comment]
@shivaprsdv @r0x0r more [winds](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/) than expected? At first glance this seems like really good news.

**Comment by r0x0r** [comment]
Yep. This news got me thinking if there is any point in implementing
edgehtml support at all when it arrives.

**Comment by shivaprsdv** [comment]
Well well.. First GitHub, now Chromium, are you serious, Microsoft? 😄
This means we can get away without #15 as well. 🤷‍♂️

**Comment by r0x0r** [comment]
Current progress is in the [edge-support](https://github.com/r0x0r/pywebview/tree/edge-support) branch. The basic functionality is there (including auto-detection of Edge support), but JS support is missing.

The main hurdle is that `InvokeScriptAsync` crashes the program for content loaded with `NavigateToString`. The bug is described [here](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2165). It was apparently fixed, but the fix is not present in 5.1.1. Tried installing the preview version of WebView 6.0, but for some reason it did not work. 
There are a couple of solutions described in the issue. All involve using something else than `NavigateToString`. Anyhow the Edge is no different to other implementations - finding odd solutions for quirky bugs.

The architecture will need a major refactor at some point, but won't happen before pywebview 3 release.

**Comment by r0x0r** [comment]
`WebViewControl` is buggy af.
In addition to the bug above  `file:// ` URLs are not supported and there is a bug related to crashing the program after closing a window via `window.close`. This makes the test runner crash.
Anyhow I made it work in a more or less adequate manner. I will not spend any more time polishing it at this point and will release 3.0 using the current version.

Known issues are documented [here](https://github.com/r0x0r/pywebview/blob/edge-support/docs/guide/renderer.md)

**Comment by r0x0r** [comment]
PR is [here](https://github.com/r0x0r/pywebview/pull/340)
Closing this issue now.
