### ISSUE TITLE
Issue when try change page in app

### ISSUE THREAD

**Issue by MrMax836** [r0x0r/pywebview#250]
### Specification
- Platform: Windows 10
- Version: Latest

### Description
Hi, i have a app  whose logic is  being(executing) in the pywebview thread.
Processing takes place on the server.
There are several pages on which transitions are made. The first page is registration . Using JavaScript, the key of the current page changes through api.
On line 37 a request is sent to the server, where the user registration is checked. The point is not this. If line 38 is not true, then nothing should change at all. The page remains the same. But! Instead of the page, a blank (white) screen appears - a blank page.

```

1. import json
2. import time
3. import webview
4. from threading import Thread
5. from bs4 import BeautifulSoup
6. import urllib.request as request
7. 
8. 
9. from functools import partial
10. 
11. from application.my_window import *
12. from application.connect_server import ConnectToServer
13. from application.game_information import GameInformation
14. 
15. 
16. class Application(Thread):
17.     def __init__(self):
18.         super().__init__(target=self._load_html)
19.         self.m_connect = ConnectToServer()
20.         self.storage = []
21.         self.current_key = "sign"
22.         self.windows = {
23.             "sign":'C:/Users/User/Desktop/Economika/sign_up_in.html',
24.             "office": 'C:/Users/User/Desktop/Economika/office.html'
25.         }
26.         super().start()
27.         self._create_window()
28.         self._load_html()
29. 
30.     def add_to_storage(self, elem):
31.         self.storage.append(elem)
32. 
33.     def signIn(self, trash=0):
34.         login = self.storage.pop()
35.         password = self.storage.pop()
36. 
37.         result = self.m_connect.sign_in(login, password)
38.         if result.get('value') is not None and result.get('error') is None:
39.             self.current_key = "office"
40.         self._load_html()
41. 
42.     def _load_html(self):
43.         file = open(self.windows[self.current_key])
44.         webview.load_html('', BeautifulSoup(file.read(), "html5lib"))
45.         file.close()
46. 
47.     def _create_window(self):
48.         webview.create_window('Game', js_api=self, width=1050, height=850)
49. 
50. 
51. if __name__ == '__main__':
52.     Application()`

```

**Comment by r0x0r** [comment]
You load blank HTML on the line 44. The code gets executed no matter what the result of the condition on the line 38 is.

**Comment by MrMax836** [comment]
Can anybody help? Explain? Explain how to correct my mistake? You are welcome
(you can ignore the function)

The application works, it sometimes breaks.

**Comment by MrMax836** [comment]
How to load local files correctly?
Can someone share a really working great example of a program?

**Comment by r0x0r** [comment]
https://github.com/r0x0r/pywebview/tree/master/examples/todos
