### ISSUE TITLE
Platform specific features (eg frameless windows)

### ISSUE THREAD

**Issue by Fizzadar** [r0x0r/pywebview#251]
I'm currently maintaining my fork with the `frameless` branch code and occasionally merge in master - but was thinking that if such features aren't always available on all platforms (dev tools comes to mind) - what about having platform-specific "extras"?

This would mean not having a feature available on all platforms wouldn't hold keeping it merged into master.  Looking at the public API the only way I can think of doing this without altering the API would be something like:

```py
webview.create_window('My title', 'http://google.com', cocoa_kwargs={'frameless': True})
```

The disadvantage of course is keeping track of what platforms support feature X, so I would understand if this is a noop :) Whatcha' think?

**Comment by r0x0r** [comment]
I have no problems with merging platform specific features, as long as it is documented properly. This was done with the debug feature for example. In other words, there is no need to i
