### ISSUE TITLE
Hide A Window

### ISSUE THREAD

**Issue by SoulSen** [r0x0r/pywebview#253]
### Specification
- Platform: Windows 
- Version: 10

### Description
I'm looking for a way to hide the webview GUI but I find no parameter or anything. Could you maybe add this or is their a feature that I can't find?

**Comment by SoulSen** [comment]
Do you know if their is a temporary way right now or with a third party package?

**Comment by r0x0r** [comment]
No, but implementating this feature should be fairly straightforward if you
wish to give it a go.

**Comment by SoulSen** [comment]
Alright then, idk how I would do it but thanks!

**Comment by SoulSen** [comment]
Tell me if you've implemented it or found a way to do it 3rd party.
