### ISSUE TITLE
Program stops injecting CSS when I go to a new page.

### ISSUE THREAD

**Issue by LOL-XDD** [r0x0r/pywebview#256]
### Specification
- Platform: Windows 10
- Version: 2.1

### Description

    import webview
    import threading
    from urllib.request import *
    import gzip
    import codecs

    req = Request('http://www.ioi-xd.net/resources/midlii.css')
    css = gzip.decompress(urlopen(req).read()).decode('utf-8')

    def css_inject():
        webview.load_css(css)

    t = threading.Thread(target=css_inject)
    t.start()
    webview.create_window("Midlii", "https://www.vidlii.com", width=275, height=467)

All of this code works as it should, but when I go to a new page it stops loading the CSS, even though I loaded it using a thread. Any clue on how to get the program to constantly inject CSS?

**Comment by r0x0r** [comment]
How about manually calling `load_css` again when you go to another page? That requires manual URL change using `load_url` of course.

There is a ticket open for event system that would make executing custom code during a load event possible. Until then I cannot think of any way to preserve CSS over a url change.
https://github.com/r0x0r/pywebview/issues/201

**Comment by LOL-XDD** [comment]
I think I got a possible solution, but it throws an error.

    import webview
    import threading
    from urllib.request import *
    import gzip
    import codecs

    req = Request('http://www.ioi-xd.net/resources/midlii.css')
    css = gzip.decompress(urlopen(req).read()).decode('ascii')

    urlCu = ""
    urlPre = ""

    def css_inject():
        webview.load_css(css)
        
    def page_change():
        urlCu = webview.get_current_url(uid='master')
        if(urlCu != urlPre):
            css_inject()
            urlPre = urlCu

    t1 = threading.Thread(target=css_inject)
    t1.start()
    webview.create_window("Midlii", "https://www.vidlii.com/logout", width=210, height=380, min_size=(210, 380))
    webview.load_url('https://www.vidlii.com/my_subscriptions', uid='master')
    urlPre = webview.get_current_url(uid='master')
    t2 = threading.Thread(target=page_change)
    t2.start()

The error:


    C:\Bots\Midlii>python main.py
    Traceback (most recent call last):
      File "C:\Users\Owner\AppData\Local\Programs\Python\Python35-32\lib\site-packages\webview\__init__.py", line 177, in wrapper
        return function(*args, **kwargs)
      File "C:\Users\Owner\AppData\Local\Programs\Python\Python35-32\lib\site-packages\webview\__init__.py", line 267, in load_url
        gui.load_url(url, uid)
      File "C:\Users\Owner\AppData\Local\Programs\Python\Python35-32\lib\site-packages\webview\winforms.py", line 336, in load_url
        window = BrowserView.instances[uid]
    KeyError: 'master'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "main.py", line 25, in <module>
        webview.load_url('https://www.vidlii.com/my_subscriptions', uid='master')
      File "C:\Users\Owner\AppData\Local\Programs\Python\Python35-32\lib\site-packages\webview\__init__.py", line 186, in wrapper
        raise Exception('Cannot call function: No webview exists with uid: {}'.format(uid))
    Exception: Cannot call function: No webview exists with uid: master

**Comment by r0x0r** [comment]
1) You call load_url after create_window. Create_window blocks execution and load_url is executed after the window is destroyed. Place load_url in a thread instead.
2) You can probably achieve what you want by placing get_current_url in a loop on a separate thread, which would poll the current URL and apply CSS changes if required

**Comment by LOL-XDD** [comment]
Is there really no way to have at least one thing running in the background while create_window runs? From tests it seems that even threads stop running after the program ends.

**Comment by r0x0r** [comment]
Create a loop that would keep polling get_current_url. Not that I advocate this type of solution.

**Comment by LOL-XDD** [comment]
> 
> 
> Create a loop that would keep polling get_current_url. Not that I advocate this type of solution.

That's what I'm doing now, am I not?

    import webview
    import threading
    from urllib.request import *
    import gzip
    import codecs
    import datetime

    urlPre = ""
    urlCu = ""

    req = Request('http://www.ioi-xd.net/resources/midlii.css')
    css = gzip.decompress(urlopen(req).read()).decode('ascii')
    firstRun = 1
    gotUrlPre = 0
    ready = 0

    f = open("log.txt","w+")
    f.truncate(0)
    f.write(str(datetime.datetime.now())+"\n")

    def css_inject():
        f.write("thread 1 loaded\n")
        webview.load_css(css)
        print("h")

    def first_run():
        f.write("thread 2 loaded\n")
        try:
            if(firstRun == 1):
                urlPre = webview.get_current_url(uid='master')
                f.write("(got urlPre)\n")
                gotUrlPre = 1
        except:
            f.write("(couldn't get urlPre)\n")
        else:
            f.write("loading anyway though\n")
            if(gotUrlPre == 1):
                webview.load_url('https://www.vidlii.com/my_subscriptions', uid='master')
                firstRun = 0
                ready = 1
                
        
    def page_change():
        f.write("thread 3 loaded\n")
        if(firstRun == 0):
            urlCu = webview.get_current_url(uid='master')
            if(urlPre != urlCu):
                css_inject()
                urlPre = urlCu
            
    t1 = threading.Thread(target=css_inject)
    t2 = threading.Thread(target=first_run)
    t3 = threading.Thread(target=page_change)
    t1.start()
    t2.start()
    webview.create_window("Midlii", "https://www.vidlii.com/logout", width=210, height=380, min_size=(210, 380))

This works but it doesn't execute the third thread at all, as evidenced by the log.

    2018-09-19 17:59:44.535890
    thread 1 loaded
    thread 2 loaded
    (couldn't get urlPre)

**Comment by LOL-XDD** [comment]
I finally got it, after hours of debugging. The solution was not luck, or skill. I'm actually not sure what it was in fact. But as soon as I set up a functioning log for the program, it worked. My guess is that a lower FPS allows the program the handle the requests at it's own pace, but I couldn't tell myself.

Working code:

    import webview
    import threading
    from urllib.request import *
    import gzip
    import codecs
    import datetime
    from goto import with_goto

    x = 1

    req = Request('http://www.ioi-xd.net/resources/midlii.css')
    print('Requesting css file...')
    css = gzip.decompress(urlopen(req).read()).decode('ascii')
    print('Translating css file for use with the program...')
    urlPre = ""
    urlCu = ""
    print('Initalized urlPre and urlCu')
    firstRun = 1
    print('firstRun set to '+str(firstRun)+'')
    gotUrlPre = 0
    print('gotUrlPre set to '+str(gotUrlPre)+'')

    def css_inject():
        while(x == 1):
            try:
                webview.load_css(css)
            except:
                print("thread 1 failed, trying again.")
        print("thread 1 ended.")

    def first_run():
        while(x == 1):
            print("thread 2 started")
            try:
                if(firstRun == 1):
                    urlPre = webview.get_current_url(uid='master')
                    print("got urlPre")
                    gotUrlPre = 1
                    print("gotUrlPre set to 1")
            except:
                if(gotUrlPre == 1):
                    webview.load_url('https://www.vidlii.com/my_subscriptions', uid='master')
                    print("Attempting to load subscriptions page.")
                    firstRun = 0
                    print("firstRun set to 0")
        print("thread 2 ended.")
                
        
    def page_change():
        while(x == 1):
            try:
                if(firstRun == 0):
                    urlCu = webview.get_current_url(uid='master')
                    print("got urlCu")
                    if(urlPre != urlCu):
                        css_inject()
                        urlPre = urlCu
                        webview.set_title(urlCu)
                        print("Updating urlPre")
            except:
                print("thread 3 failed, trying again.")
        print("thread 3 ended.") 
                
    t1 = threading.Thread(target=css_inject)
    print("Initalizing thread 1...")
    t2 = threading.Thread(target=first_run)
    print("Initializing thread 2...")
    t3 = threading.Thread(target=page_change)
    print("Initializing thread 3...")

    print("Starting thread 1...")
    t1.start()
    print("Starting thread 2...")
    t2.start()
    print("Starting thread 3...")
    t3.start()
    print("thread 3 started")

    webview.create_window("Midlii", "https://www.vidlii.com/logout", width=210, height=380, min_size=(210, 380))
