### ISSUE TITLE
What are thread-safety guarantees for javascript code

### ISSUE THREAD

**Issue by fgrzadkowski** [r0x0r/pywebview#257]
Can you please explain what are the thread-safety guarantees for the javascript related code? I have some specific questions:
* is regular javascript code actually single-threaded? (except for pywebview bindings)
* is `window.evaluate_js` regarded thread-safe with the javascript code embedded in the html?
* is there a way to introduce some kind of lock to synchronize javascript embedded in the html and pywebview api bindings?

I'd be great to have this documented :)

**Comment by r0x0r** [comment]
This is a good question, I will try to my best to answer it.

First thing to bear in mind is that there are four different implementations of a web view component: Trident on Windows, WebKit/macOS, WebKit/QT and WebKit/GTK. In addition to their inherent differences, there are differences in implementation how `evaluate_js` value is returned. The general logic goes like this.

- `evaluate_js` is always called on a secondary thread. As GUI related code must always be run on the main thread, `evaluate_js` function is invoked on main thread and value returning code is blocked on the secondary thread using a semaphore. 
- The actual JS code is run either in a synchronous (WinForms, Cocoa, GTK/WebKit1) or async (QT, GTK/WebKit2) manner. In both cases the semaphore is released when the value is obtained.
- There is no synchronization between separate `evaluale_js` calls, nor between `evaluale_js` and JS API calls. I might introduce a lock between JS API and `evaluate_js` in the GTK/WebKit2 implementation to make returning a value possible. This should be seen as an unfortunate side-effect, not a feature though. See details here https://github.com/r0x0r/pywebview/issues/210
- JS API code is executed asynchronously (using promises). The code on Python side spawns a new thread to execute the code and sets the value on the JS side when the result is ready. JS code busy checks for a set value and returns the promise once it is ready.
 
Is it thread-safe? Probably not. There are no synchronizations between JS and Python codes and those should be seen as separate domains. 

What is your use case though? What are you trying to achieve?
