### ISSUE TITLE
installation of GTK version on openSuse Tumbleweed

### ISSUE THREAD

**Issue by MisterY** [r0x0r/pywebview#258]
### Specification
- Platform: openSuse Tumbleweed

### Description

When running a simple demo script, I'm getting an error `You must have either QT or GTK with Python extensions installed in order to use pywebview.`

According to PyGObject [instructions](https://pygobject.readthedocs.io/en/latest/getting_started.html#opensuse-getting-started), the required packages are `python-gobject python3-gobject gtk3`. These are all installed.

What am I missing? What exactly are the dependencies of pywebview?

I would like to run GTK version as I'm using Gnome. However, when I run `pip install pywebview[gtk3]`, I'm getting `pywebview 2.1 does not provide the extra 'gtk3'`.

**Comment by MisterY** [comment]
```
Provides-Extra: qt5
Provides-Extra: cocoa
Provides-Extra: cocoa
Requires-Dist: pyobjc; extra == 'cocoa'
Provides-Extra: qt5
Requires-Dist: PyQt5; extra == 'qt5'
```

**Comment by MisterY** [comment]
According to the [setup.py](https://github.com/r0x0r/pywebview/blob/master/setup.py), it seems that my system is recognized as Darwin?

**Comment by MisterY** [comment]
Tried reinstalling pywebview with pip but no changes.

**Comment by r0x0r** [comment]
What happens if you start a Python console and import GTK dependencies? You can copy import from the top of the gtk.py file

**Comment by r0x0r** [comment]
I am not familiar with OpenSUSE, but these are the Python 3 packages that are used in Travis build
gir1.2-gtk-3.0 gir1.2-webkit-3.0 python3-gi python3-gi-cairo

**Comment by MisterY** [comment]
Just ran the sample from the [Getting Started](https://pygobject.readthedocs.io/en/latest/getting_started.html) page:

```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```
and the window opens up. So GTK should be set-up correctly.

Second, I tried running directly
```
import webview.gtk as gui
gui.create_window("yo", "http://...")
```
and got "Namespace WebKit not available". Now this makes more sense, I guess.

**Comment by MisterY** [comment]
And the [problem](https://bugzilla.opensuse.org/show_bug.cgi?id=1055659) is that webkitgtk is being removed from Tumbleweed, and probably other openSuse distributions, due to project not being maintained for years. :(

**Comment by r0x0r** [comment]
Is WebKit 2 included? There is an effort going on to update the WebKit to
2.0

https://github.com/r0x0r/pywebview/issues/210

**Comment by MisterY** [comment]
OK, so the workaround is to use the Qt5 version. That works fine so I guess I'll be resorting to that solution. The error, however, should be a bit more clear.

**Comment by MisterY** [comment]
Oh, just saw your reply. I see libwebkit2gtk but I'm not sure if there are python bindings. I'll keep an eye on that issue, though. Thanks!

**Comment by MisterY** [comment]
Right. If I run that test script
```
import sys
import gi

try:
    gi.require_version('Gtk', '3.0')
    from gi.repository import Gtk, Gdk # , Gio
except:
    sys.exit("This script requires Gtk 3.0 or newer!")

try:
    gi.require_version('WebKit2', '4.0')
    from gi.repository import WebKit2
except:
    sys.exit("This script requires WebKit2 4.0 or newer!")
```
it completes successfully, meaning WebKit 2 is available.

**Comment by MisterY** [comment]
Hi, @r0x0r. I have not managed to try it out yet. Fortunately the weekend is in front of us again so I hope to have some time for that now. :)

**Comment by MisterY** [comment]
First I just added `webview.config.gui = 'gtk'` on a Linux system and I was getting 
```
ERROR:webview:GTK cannot be loaded
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/webview/__init__.py", line 66, in import_gtk
    import webview.gtk as gui
  File "/usr/lib/python3.6/site-packages/webview/gtk.py", line 25, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```
but the window opens.

Then I've removed the pip version of pywebview, cloned the webkit2 repository branch and registered  with `pip install -e .`. 
Now the browser window simply opens, no error messages in the console. 

To be honest, I couldn't tell which one's which - whether there's a fallback or not. Then I debugged. I see that, by default, use_qt is set to False so perhaps explicitly setting the 'gtk' as the library is not necessary. The initialization goes through. Unfortunately, I don't see the log messages anywhere and I have not really checked how the logger in pywebview is configured. But there are no import errors and the initialization completes successfully, importing gtk. Later, when the window is being created, the debugger goes into gtk.py, so I'd say that the GTK version is being used.
The window opens just fine so I'd say it works! Great job, if you ask me.

**Comment by MisterY** [comment]
I also tried with `webview.config.gui = 'qt'` to have the full picture. But, it seems that this setting is not being checked at all. There is a check for `webview.config.use_qt`, instead, so I tried setting that to True.

The window opens and the fonts are a bit different than with GTK. The debugger shows that qt.py is being run, so that setting actually works. The Readme should be updated, I guess.

Then I ran both versions in parallel, to also compare the output and, indeed, there are minor differences in rendering the same page. Different fonts are being used by default. The point being, though, that both versions work in the WebKit2 branch.

**Comment by MisterY** [comment]
It seems that some Vue components don't work in WebKit2 version but work fine in Qt.

**Comment by shivaprsdv** [comment]
@MisterY As WebKit2 solves it, can we close this?

**Comment by MisterY** [comment]
Absolutely! Thanks, guys!
