### ISSUE TITLE
pywebview for Pythonista

### ISSUE THREAD

**Issue by mikaelho** [r0x0r/pywebview#259]
Would you welcome a PR that implemented a UIKit UIWebView backend for Pythonista (iOS app running Python 3.6.1)? Are there specific requirements besides matching the pywebview API for other platforms?

**Comment by r0x0r** [comment]
I like this idea, but the big question is who is going to support it in the future? It is a big commitment to support a new platform. I am not familiar with Pythonista, nor iOS development in general for that matter. 

As for your second question,  API compatibility and passing tests would be enough. I believe features like window manipulation, file dialogs and multi-window support would be not be applicable to the iOS implementation.

**Comment by r0x0r** [comment]
Let's reopen this, if somebody wishes to commit to this in the future.
