### ISSUE TITLE
Built-in HTTP server

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#260]
I am pondering the idea of bundling a http server for serving local urls, so that it would be http:// instead of file://. So `webview.create_window("index.html")` would server content over HTTP.
Maybe later in the future mirroring `window.pywebview.api` as API endpoints too. 

I would not like to rely on a 3rd party module, so thinking about utilising Python's built-in http server.

Comments, opinions, concerns?

**Comment by shivaprsdv** [comment]
Kudos to utilising Python's built-in http server. Build it based on the existing
`http_server.py` example, may be.

**Comment by ibeex** [comment]
bultin http server in threaded mode would be great or include https://github.com/bottlepy/bottle it is single file library.

**Comment by r0x0r** [comment]
Implemented in the `pywebview-3` branch
