### ISSUE TITLE
Add CSRF warning to README

### ISSUE THREAD

**Issue by therealadityashankar** [r0x0r/pywebview#261]
adding a CSRF warning would be important to users,
after all,  one does not want [utorrent style attacks](https://en.wikipedia.org/wiki/Cross-site_request_forgery#Example_and_characteristics) if a project using pywebview goes popular.

**Comment by r0x0r** [comment]
That's an excellent point. Please create a PR if you get a chance.

**Comment by r0x0r** [comment]
PR is merged. Thanks for the contribution!
