### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#267]
README is getting quite large, so I decided to migrate its content to a dedicated website. 

I have set up a basic infrastructure featuring VuePress and Netlify. The contents of the website are in the https://github.com/r0x0r/pywebview/tree/docs branch that is automatically deployed to https://elegant-wright-387f54.netlify.com/ (I will set up a proper domain later). Whether documentation should be a separate repository or the `docs` branch should be merged into master will be to seen later. Input on how it is should be done is welcomed.

**Comment by r0x0r** [comment]
PR is up https://github.com/r0x0r/pywebview/pull/270. 

The documentation will be merged into master, while the docs branch will be used for automatic deployment. The URL for the documentation website is going to be https://pywebview.flowrl.com. The default landing page for example is changed https://pywebview.flowrl.com/hello and is put under version control as well (in `docs/.vuepress/public/hello`)

**Comment by shivaprsdv** [comment]
What about moving the doc contents the repo's Wiki? Can the documentation
website be deployed based on it?

**Comment by r0x0r** [comment]
I haven't explored this possibility. Myself I rarely note the existence of
Github wiki. There's not much value in storing docs there.

**Comment by r0x0r** [comment]
Documentation is now live 
https://pywebview.flowrl.com/
