### ISSUE TITLE
request: resize_window function

### ISSUE THREAD

**Issue by thekatiemcneil** [r0x0r/pywebview#274]
I'm working on a project where I'm interested in having two set window sizes--a smaller, and a larger. I don't want the user to have the option to resize to any other window sizes.

Something along the lines of:
`webview.resize_window(width, height)` 

Is there already a way to do this?

**Comment by r0x0r** [comment]
This function does not exist, but it should be fairly easy to implement.

If you wish to give it a go, read development guidelines first https://pywebview.flowrl.com/contributing/development.html

**Comment by r0x0r** [comment]
Implementation by @aprowe is now merged with master.
