### ISSUE TITLE
js_api available at onload?

### ISSUE THREAD

**Issue by mikaelho** [r0x0r/pywebview#275]
### Specification
- Platform: Mac Cocoa
- Version:

### Description

Is js_api supposed to be available in an onload event handler? It seems to be undefined.

I am calling the same function later (at resize) and it works fine.

If the api is not available at onload, is there any other recommended way to trigger an action on Python side?

**Comment by shivaprsdv** [comment]
No, the `js_api` is injected _after_ the page has been load, on all platforms.
So it won't be available in the on_load handler.

What action do you want to trigger before the page has even loaded? 🤔

**Comment by mikaelho** [comment]
Thanks for the confirmation. Did I miss this in the documentation?

I want to perform an action, on Python side, after the page has been loaded. Would a short delay with setTimeout be sufficient for the injected code to be in place?

**Comment by mikaelho** [comment]
Looks like setTimeout does the trick.
