### ISSUE TITLE
same html file run different result in firefox and pywebview

### ISSUE THREAD

**Issue by lescpsn** [r0x0r/pywebview#282]
### Specification
- Platform: macOS
- Version: 10.13.6

### Description
same html run in firefox and webview
index.html file content is:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>鼠标悬浮</title>
</head>
<body>
    <div class="dhov" id="dhov">
        <span class="title" id="titlehov">鼠标悬浮</span>
        <span class="close" id="closehov">X</span>
    </div>
</body>
<style>
    .dhov{
        width: 100px;
        height: 60px;
        border: 1px solid #1ebed3;
        cursor: pointer;
    }
    .dhov:hover{
        background-color: chartreuse
    }
    .title{
        text-align: center;
        line-height: 60px;
        width: 75%;
        display: inline-block
    }
    .close{
        display: none
    }
</style>
<script>
    window.onload = function(){
        var dhov = document.getElementById('dhov')
        var titlehov = document.getElementById('titlehov')
        var closehov = document.getElementById('closehov')
        dhov.onmouseover = function(){
            titlehov.style.color = "blueviolet"
            closehov.style.display = "inline-block"
        }
        dhov.onmouseout = function(){
            titlehov.style.color = "#000"
            closehov.style.display = "none"
        }
    } 
</script>
</html>

firefox: open index.html , result is ok
webview:
if __name__ == '__main__':
    webview.create_window("安全邮件", "mytest/index.html", debug=True)
    sys.exit()

result is not ok

why? why?

**Comment by r0x0r** [comment]
https://pywebview.flowrl.com/guide/renderer.html

In other words Gecko is not used as a renderer.

**Comment by lescpsn** [comment]
but I use golang webview is ok

**Comment by r0x0r** [comment]
pywebview uses web rendered supplied with the operating system. I don't know about golang.

You may try testing your app with the `wkbwebview` branch, which is an attempt to upgrade to a more recent version of webview on macOS.
