### ISSUE TITLE
Problem loading local html

### ISSUE THREAD

**Issue by AnselmC** [r0x0r/pywebview#283]
### Specification
- Platform: macOS
- Version: 10.13.6

### Description
Hi,
I've just started using pywebview and am having trouble loading/linking local html/css/js files.
`webview.create_window('Test', 'assets/index.html')` 
only shows a white screen whereas 
```
def load_html():
    with open('assets/index.html') as html:
        webview.load_html(str(html.read()))


if __name__ == '__main__':
    t = threading.Thread(target=load_html)
    t.start()
    webview.create_window('Test')
```
doesn't load the image or stylesheet referenced in the HTML:
```
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="style.css">
  <meta charset="utf-8"/>
</head>
<body bgcolor="#0099ff">
	<div align="center">
            <img src="images/logo.jpg">
            <h1>TEST</h1>
        </div>
</body>
</html>
```
I'm probably missing something very obvious, any help is appreciated. Thanks!

**Comment by r0x0r** [comment]
Try either
`webview.create_window('Test', 'assets/index.html')`

or set BASE tag in your html https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by shivaprsdv** [comment]
Or pass `debug=True` as an argument to `create_window()` and on the white
screen try Control Click -> Inspect Element to inspect the webview.

**Comment by AnselmC** [comment]
Hi, 
thanks for the responses. I've tried `webview.create_window('Test', 'assets/index.html', debug=True)` and ctrl + click (nor cmd + click) doesn't do anything...it all works fine when setting up a local server, so if all else fails, I'll just do that.

**Comment by r0x0r** [comment]
Take a look at [todo app](https://github.com/r0x0r/pywebview/tree/master/examples/todos) handles local files.

**Comment by AnselmC** [comment]
Yeah, that's where I got my inspiration from.
However, I'm having the same problem with that project. I.e. running `python start.py` (both python 2 and 3) results in the attached screenshot (where a ctrl+click doesn't debug). Something seems to be off with my machine...I've tried it on Ubuntu and it works. No idea why..
![image](https://user-images.githubusercontent.com/22545864/48674993-48250a00-eb53-11e8-99e9-1ede8ddd6648.png)

**Comment by AnselmC** [comment]
When I edit util.py to print sys.argv[0] and then run the script, `start.py` is printed twice:
![image](https://user-images.githubusercontent.com/22545864/48677431-453b1100-eb75-11e8-8db6-61dce57c3592.png)

**Comment by shivaprsdv** [comment]
@AnselmC Try printing the entire line: `os.path.dirname(os.path.realpath(sys.argv[0]))`.

**Comment by AnselmC** [comment]
This prints `/Volumes/Macintosh HD/Dokumente/Arbeit/AmazingShop/Code/app`. Could it be that the blank space in `Macintosh HD` is a problem?

**Comment by shivaprsdv** [comment]
Confirmed. Fix is up at [base-uri-fix](https://github.com/r0x0r/pywebview/tree/base-uri-fix), can you please check it @AnselmC ?

**Comment by AnselmC** [comment]
Yup, fix works. Thanks!

**Comment by shivaprsdv** [comment]
Great! Thanks for helping figure it out. 👍
