### ISSUE TITLE
GuiProblem

### ISSUE THREAD

**Issue by VandanDev** [r0x0r/pywebview#286]
Hey there, Im new to PyWebView. 
For some reason, this Gui that i worked on works - https://pastebin.com/hSedmH4X
Which is a Python Calculator which i called in Html Css & Js with. but then this code...
doesn't work https://pastebin.com/5zsEbzTD

Im surely missing something out important about this module or i made some mistake.

Thnx for the help..

**Comment by shivaprsdv** [comment]
There are two problems:

1. The string passed to `webview.load_html()` has backlash escape sequences
(like `\'`). Python automatically processes this and converts it to `'`. To avoid
that make it a raw string by adding `r` before it: `webview.load_html(r"""...`

2. Your script uses jQuery. You need to load it manually just as you would do in
a webpage. Add

**Comment by VandanDev** [comment]
Sorry i didn't understand problem one. Could you elaborate Problem One?

**Comment by VandanDev** [comment]
https://github.com/r0x0r/pywebview/issues/286#issuecomment-439673883

Oh i solved the problem ignore that ^ 

and i needed some more help how do i add a login with google prompt before the gui loads up. : ) 

Thnx. : )

**Comment by shivaprsdv** [comment]
@VandanDev Just google it.
