### ISSUE TITLE
Packaging with PyInstaller: Icon not found.

### ISSUE THREAD

**Issue by LaChocolaterie** [r0x0r/pywebview#29]
I am using PyInstaller to package my application as an executable.
It packages fine, and no special instructions are required for pywebview.
However, when executing the program, it fails to find the icon resource. (win32.py line 98).
I guess it should be possible to configure something on pyinstaller parameters, but it would be nice to just have an option to not load an icon for pywebview. 
(As a workaround I am currently just commenting this line from win32.py: `self.wndclass.hIcon = win32gui.LoadIcon(self.wndclass.hInstance, 1)`)

**Comment by r0x0r** [comment]
What is the error message that PyInstaller reports?
