### ISSUE TITLE
Inspecting Specific Elements

### ISSUE THREAD

**Issue by QeyLogger** [r0x0r/pywebview#292]
This is how it goes ... 
```python
import webview
webview.create_window('ExampleIssue', 'https://www.google.com/')
```
Basically i was wondering if it is possible to inspect an element once we load in a website. 
So in this case we loaded in Google.com. What if i wanted to change the text beneath the search bar which says " Google Search " to "Example Search."

Hopefully, you get where I'm going. Is it possible to tweak HTML, Css and Js with python? or some other way?

Thank You.

**Comment by r0x0r** [comment]
Yes, You can use `webview.evaluate_js` to execute any Javascript you want.

It may be a good idea to introduce `webview.get_elements` at some point. It would invoke `document.querySelectorAll` and a return a subset of properties of the DOM node.

**Comment by r0x0r** [comment]
Current progress is here. https://github.com/r0x0r/pywebview/pull/new/get-element

Implemented  `window.get_elements` that returns a list of matching elements. The DOM node serialization is based on https://github.com/azaslavsky/domJSON

I have discovered a problem with GTK. Namely JS-Python communication via window title has got a limit of 1000 characters. I will look into implementing a proper JS-Python bridge.

**Comment by r0x0r** [comment]
Found a workaround for the issue, but it requires WebKit2 version 2.22 or greater. Debian Stretch, for example, ships with 2.18, but 2.22 can be installed as a backport.
The GTK implementation will throw an exception when calling this function if an old version of WebKit2 is used.

**Comment by r0x0r** [comment]
Implemented in the `pywebview-3` branch.
