### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by AnselmC** [r0x0r/pywebview#295]
### Specification
- Platform: macOS
- Version: Python 3.6.7

### Description
A heads up: I'm not sure whether this is something that is specific to pywebview but I couldn't find anything on my problem in general.

When trying to log to a file, the logs are printed in the console rather than written to the file. This only happens when I create a new window with pywebview. Here an example code snippet:
```
import logging
import webview

logging.basicConfig(
    filename='app.log',
    filemode='w',
    format='%(name)s - %(levelname)s - %(message)s')
logging.getLogger().setLevel(logging.INFO)

class Foo:
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.logger.info('Something informative')
        self.doSomething()

...

if __name__ == '__main__':
    foo = Foo()
    webview.create_window('example.com')
```

Any idea why this might be?

Thanks!

**Comment by shivaprsdv** [comment]
I don't know much about Python's Logger, but apparently some of its config's
are also set by Pywebview. Check `webview/__init__.py`:

```py
 29 logger = logging.getLogger(__name__)
 30 logging.basicConfig(level=logging.INFO)
```

This is somehow conflicting with your code. You must find a way to override
the behaviour set by imported modules.

**Comment by r0x0r** [comment]
I got rid of calling basicConfig in `webview/__init__.py`, which should keep logging configuration local to pywebview.  
@AnselmC could you test if this change makes file logging working out of the box? Changes are now in master.

**Comment by AnselmC** [comment]
@r0x0r It works! Thanks
