### ISSUE TITLE
Mojave issues

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#296]
### Specification
- Platform: OSX
- Version: 10.14

### Description

I recently upgraded to Mojave and noticed following issues. Not sure if there is an issue with my system or Mojave itself.
a) Window hangs after closing (fixed this in master already)
b) Icon is not created in Dock for non-frozen applications.

**Comment by shivaprsdv** [comment]
b) You mean the Python _rocket_ icon? It does appear in mine. 🤔

**Comment by shivaprsdv** [comment]
On a side note, I have found an issue with Dark mode. Running with Python 3.x
opens windows with dark title bar, but running with built-in Python 2.7 opens a
white title bar even in dark mode.

![py](https://user-images.githubusercontent.com/18247990/50139125-bd0c7080-02c6-11e9-8f2b-6804e1258bb2.png)

**Comment by Dopebiz6Dime** [comment]
*ApplePac

**Comment by shivaprsdv** [comment]
Call this fixed? @r0x0r

**Comment by r0x0r** [comment]
Yes, everything works at least on my machine
