### ISSUE TITLE
Howto: Automatic scrolling of webpage until it reaches the bottom

### ISSUE THREAD

**Issue by xabispacebiker** [r0x0r/pywebview#298]
### Specification
- Platform: Debian 
- Version: Stretch

### Description
I would like to load webview and automatically scroll to the bottom. Can you give me any clue on how to do it? Thanks in advance. I'd like to scroll in the window not by javascript as I already tried the same embeding the web in an iframe but I had "cross domain" problems when loading sites from different domains. So my porpouse is to load the websites on fullscreen and do the automatic scrolling until it reaches the bottom.

**Comment by RodolfoPichardo** [comment]
From version 1.8 you can inject javascript from the python code. An basic example of this provided in examples/evaluate_js.py.

In your case, this piece of code should work `webview.evaluate_js('window.scrollTo(0,document.body.scrollHeight);')`

**Comment by shivaprsdv** [comment]
@xabispacebiker You don't need to embed the webpage in an iframe to execute
the JavaScript needed for scrolling. You can load the page "fullscreen" and run
arbitrary JS using `webview.evaluate_js` as @RodolfoPichardo demonstrates in
his comment. The JS gets executed only after the page has loaded.

Refer `evaluate_js.py` in the examples for actual implementation.

**Comment by xabispacebiker** [comment]
Thanks @RodolfoPichardo and @shivaprsdv. I finally solved it by injecting the javascript using evaluate_js function.
