### ISSUE TITLE
Prints not Python 3 compatible

### ISSUE THREAD

**Issue by Firnagzen** [r0x0r/pywebview#3]
Your print statements (in the win32.py) are not compatible with python 3, in that they do not have brackets.

    class EventSink(object):

        # some DWebBrowserEvents
        def OnVisible(self, this, *args):
            print("OnVisible", args)

        def BeforeNavigate(self, this, *args):
            print("BeforeNavigate", args)

        def NavigateComplete(self, this, *args):
            print("NavigateComplete", this, args)
            return

        def OnQuit(self, this, *args):
            print("OnQuit", args)

        # some DWebBrowserEvents2
        def BeforeNavigate2(self, this, *args):
            print("BeforeNavigate2", args)

        def NavigateComplete2(self, this, *args):
            print("NavigateComplete2", args)

        def WindowStateChanged(self, this, *args):
            print("WindowStateChanged", args)

**Comment by r0x0r** [comment]
Thanks for pointing it out. It is actually dead code. I will remove it from the next version

**Comment by Firnagzen** [comment]
Fixed.
