### ISSUE TITLE
Memory leak on linux inside Docker for a trivial ui

### ISSUE THREAD

**Issue by fgrzadkowski** [r0x0r/pywebview#301]
### Specification
- Platform: linux (inside docker container)
- Version: 2.1

### Description
After running a very simple UI for few minutes, memory grows to hundreds of MB (and GB after longer period of time). It's basically enough call the api from javascript in a loop. I'm attaching python code (with requirements.txt), html and dockerfile for reproduction.

*NOTE*: I haven't seen this problem on the newest version (2.2.1), but as it has different system requirements (uses webkit2) we can't update. 

ui.py:
```
import threading
import webview

class Api:
    def getStatus(self, params):
        return None

def read_file(file):
    with open(file, "r", encoding="utf-8") as f:
        return f.read()

def read_html():
    return read_file("index.html")

def create_app():
    webview.load_html(read_html())

def main():
    t = threading.Thread(target=create_app)
    t.start()
    api = Api()
    webview.create_window("UI", js_api=api)
    t.join()

if __name__ == "__main__":
    main()
```

index.html:
```
<!DOCTYPE html>
<html>
<body id="body">
<scrilpt>
    function checkMagicLoaderStatus() {
        pywebview.api.getStatus();
    }
    window.setInterval(checkMagicLoaderStatus, 20);
</scrilpt>
</body>
</html>
```

requirements.txt:
```
requests==2.19.1
PyGObject==3.30.1
pywebview==2.1
pytest==3.8.1
pyrsistent==0.14.4
```

Dockerfile:
```
FROM python:3.7.0

WORKDIR /usr/src/app

RUN apt-get update
RUN apt-get install -y libgirepository1.0-dev gir1.2-webkit-3.0 libcanberra-gtk-module libcanberra-gtk3-module

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# suppress GTK warnings about accessibility because there's no dbus
ENV NO_AT_BRIDGE 1

COPY . .

CMD [ "python", "./ui.py" ]
```

Commands to build and run:
```
docker -- build . -t ${DOCKER_IMAGE}:${DOCKER_TAG}
docker run -it -e DISPLAY -v $XAUTHORITY:/root/.Xauthority --net=host ${DOCKER_IMAGE}:${DOCKER_TAG}
```

**Comment by r0x0r** [comment]
Well, this is tricky. WebKit was upgraded without any thought of supporting the old version. What is the reason you cannot use WebKit2? Trusty?

**Comment by fgrzadkowski** [comment]
@r0x0r We use our UI in a strange way - we always use over ssh with X forwarding. It seems that with the webkit2 we have more network traffic, which kills other apps which are network-sensitive. We don't really understand why this is happening, but it's clearly connected to upgrading to pywebview 2.2.1 and webkit2.

**Comment by r0x0r** [comment]
I see no point in making a fix to an outdated version. However, webkit1 can be brought back as an option. Feel free to contribute or if you wish to get it done in a timely manner, consider sponsoring this issue.

**Comment by kgrygiel** [comment]
For the record, I believe the source of the leak is this code:
```
# Backup the doc title and store the result in it with a custom prefix
unique_id = uuid1().hex
code = 'window.oldTitle{0} = document.title; document.title = {1};'.format(unique_id, script)
```
It creates a new variable with a unique name each time. The fix would be to delete window.oldTitle{0} after use.

**Comment by r0x0r** [comment]
@kgrygiel Looks like you are onto something. Would you create a PR?

**Comment by kgrygiel** [comment]
> @kgrygiel Looks like you are onto something. Would you create a PR?
I would, but I believe the branch for this version (2.1) no longer exists. The newest version doesn't have this code.

**Comment by r0x0r** [comment]
@kgrygiel You are indeed correct. 
As newer version does not seem to have this memory leak and backporting webkit 1 is likely not to happen anytime soon, I am closing this PR. It is good to have a solution documented though.
