### ISSUE TITLE
Cannot add a html file location to the webview.load_html() function

### ISSUE THREAD

**Issue by Z-BOY-1999** [r0x0r/pywebview#303]
### Specification
- Platform:
- Platform: windows
- Version:

### Description

I just started using this module today, but I can only add a the location of a HTML file to the webview.create_window() , when I try to add a location to the function  webview.load_html("/files/main.html"), it prints it out as files/main.html on the window screen instead of opening the file, was just wondering

**Comment by shivaprsdv** [comment]
This is the correct behaviour. `load_html()` is for loading HTML _code_, not an HTML
_file_, i.e., something like `<html>...</html>`. We hope it's clear in the documentation.

**Comment by r0x0r** [comment]
Improvements to documentation can be made directly by clicking the Improve this documentation link on each page, which leads to a relevant Github link. ie https://github.com/r0x0r/pywebview/edit/docs/docs/guide/api.md

I have updated documentation to make it more clear about the function of `load_html`
