### ISSUE TITLE
About the API, license and .NET

### ISSUE THREAD

**Issue by weathon** [r0x0r/pywebview#307]
### Specification
- Platform:
- Version:

**Comment by weathon** [comment]
(Sorry about my English is not well)
First, is it possible to call python by js? Like if I want to use python to read database, Can I use js to call a fubction to do that? Or I must use ajax to do?
Second, my project is GPL v3, and pywebview is BSD. So what need I do if I use pywebview in my project?
At last, I see there are some C# code in this repo., if my computer has no .NET can I use it? And if I want to packet it to exe, is there any problem?
Thanks!

**Comment by weathon** [comment]
# OK thinks!
Another problem is does webview on windows use IE but not Chrome? O see many workframe doesn’t work on ie.

**Comment by weathon** [comment]
@r0x0r

**Comment by r0x0r** [comment]
Yes, Windows currently uses Trident for rendering giving you IE11 at best. There is support for [CEF](https://github.com/r0x0r/pywebview/issues/15), as well as [Edge](https://github.com/r0x0r/pywebview/pull/306)
