### ISSUE TITLE
BSD or GPL

### ISSUE THREAD

**Issue by weathon** [r0x0r/pywebview#308]
### Description
I see that this repo use PyQt, and PyQt is GPL, why this repo is BSD? If I use this repo, need I do things like GPL?

**Comment by r0x0r** [comment]
¯\_(ツ)_/¯

Writing code is one matter, but distributing is a whole different story. In other words you don't have distribute PyQT with your code. If license is an issue for you, then you can always use the GTK implementation.

On that note, PySide uses LGPL that would be a better choice for pywebview. If anyone feels inspired and wants to rewrite PyQT implementation in PySide, I will gladly accept a PR.

**Comment by weathon** [comment]
OK, thank you very much!

**Comment by weathon** [comment]
By the way, if my system is Windows, can I use GTK?

**Comment by r0x0r** [comment]
No, only Trident and upcoming CEF. QT support was planned, but I think I will drop it in favor of CEF.
