### ISSUE TITLE
CSRF token

### ISSUE THREAD

**Issue by ibell** [r0x0r/pywebview#316]
### Specification
- Platform: linux (but it doesn't matter)
- Version:

### Description

I have set up Flask app with some endpoints for doing various things with a pywebview wrapper.  Works totally beautifully, and I'm smitten.  I think this has totally changed my ideas about how to write desktop software.

TL;DR: I would like to know if any of your have experience locking down access to the app via some sort of authentication.  

It doesn't seem that there is the capability to pass authentication headers around.  For instance I would like to retrieve a JWT token from an endpoint, and then use that JWT for all other calls.  This would ensure that I could keep other applications from accessing the Flask webserver that I have started, and reduce one possible vector for inappropriate access of my application.  All routes exposed by the Flask server are accessible to all users, which doesn't seem ideal.  I could also start the Flask server on a random port inside the app, for security by obfuscation, but that's not so nice either, and could be sniffed.  So, what do people do about this?

**Comment by r0x0r** [comment]
What prevents you from using JWT or similar authentication mechanism? 
Personally I would randomize a port number and use a JWT or similar authentication mechanism (or just a session-unique header token)

**Comment by ibell** [comment]
Indeed, I engineered a JWT lockdown for the API on its own: https://github.com/ibell/formerly/blob/master/calculator.py ; that works fine.  What I haven't been able to make sense of is how I could enable JWT lockdown from ``pywebview`` with zero intervention from the user, and then pass around the JWT auth token.  I plan to randomize the port too.  At the moment I'm just doing proof-of-principle testing, and it all seems very, very promising.  Here is my webview wrapper: https://github.com/ibell/formerly/blob/master/run_webview.py, which works, but without any aggressive authentication.

**Comment by r0x0r** [comment]
You can pass a server generated token to the frontend using
`webview.evaluate_js`, e.g.
webview.evaluate_js(`window.authToken=skldxgdlafvkdflagi459t56oewdsigdsogl`).
This way it could be shared with both parties in a secure matter.

I think it might be a good idea to introduce pywebview's very own token
that would be unique to a session. For example `window.pywebview.authToken`

>

**Comment by ibell** [comment]
I'm not sure of the order-of-operations here, since as soon as I call ``create_window``, the main thread locks.  I can't call ``evaluate_js`` _before_ the call to ``create_window`` because the app has not yet been created.  So I can't see how in what order of operations I should start the app, set the auth key, and start the Flask server

``` python
from threading import Thread, Lock
import logging
import webview
from time import sleep
import os
from flask_seasurf import SeaSurf

here = os.path.dirname(__file__)
logger = logging.getLogger(__name__)

from calculator import app, set_verify, verification_on
set_verify(False)

def run_server():
    app.root_path = here
    app.run(host="127.0.0.1", port=23948, threaded=True)
    csrf = SeaSurf(app)

def url_ok(url, port):
    from http.client import HTTPConnection
    try:
        conn = HTTPConnection(url, port)
        conn.request("GET", "/")
        r = conn.getresponse()
        return r.status == 200
    except:
        logger.exception("Server not started")
        return False

if __name__ == '__main__':
    logger.debug("Starting server")
    t = Thread(target=run_server)
    t.daemon = True
    t.start()
    logger.debug("Checking server")
    
    while not url_ok("127.0.0.1", 23948):
        sleep(0.1)

    logger.debug("Server started")
    
    # This doesn't work since create_window not yet called
    # webview.evaluate_js('window.webview.authToken=skldxgdlafvkdflagi459t56oewdsigdsogl')
    uid = webview.create_window("Formerly",
                          "http://127.0.0.1:23948",
                          min_size=(640, 480),
                          debug = False)
    # This doesn't work because we have entered the main loop already, and this line
    # only fires after the app is dead
    webview.evaluate_js('window.webview.authToken=skldxgdlafvkdflagi459t56oewdsigdsogl')
    ```

**Comment by ibell** [comment]
Eventually I connected the dots and I see what you mean.  It's quite slick.  Interested in a fully-functional stripped-down example of this capability?

For posterity, here's an example:
``` python
from threading import Thread, Lock
import logging
import webview
import requests
from time import sleep
import os
import sys
from flask_seasurf import SeaSurf

here = os.path.dirname(__file__)
logger = logging.getLogger(__name__)

from calculator import app, set_verify, verification_on
set_verify(True)

def run_server():
    """ This will run in its own thread """
    app.root_path = here
    app.run(host="127.0.0.1", port=23948, threaded=True)
    csrf = SeaSurf(app)

def load_window():
    # Load our page in the webview
    webview.load_url("http://127.0.0.1:23948", uid='master')

    # Now we retrieve the JWT token from the web service, and set it in the 
    # window's javascript dict
    res = requests.post('http://localhost:23948/login', json={"passkey":"trustme"})
    if res.ok:
        token = res.json()['access_token']
    else:
        print(res.text())
        quit()

    # Store the JWT token in the webview
    webview.evaluate_js('pywebview = {{authToken: "{token:s}"}};'.format(token=token))

    # Double-check we get back the right token
    token_chk = webview.evaluate_js('pywebview.authToken')
    if token_chk != token:
        raise KeyError("JWT tokens didn't match")

def url_ok(url, port):
    from http.client import HTTPConnection
    try:
        conn = HTTPConnection(url, port)
        conn.request("GET", "/")
        r = conn.getresponse()
        return r.status == 200
    except:
        logger.exception("Server not started")
        return False

if __name__ == '__main__':
    logger.debug("Starting server")
    t = Thread(target=run_server)
    t.daemon = True
    t.start()
    logger.debug("Checking server")
    
    while not url_ok("127.0.0.1", 23948):
        sleep(0.1)

    logger.debug("Server started")
    t = Thread(target=load_window)
    t.daemon = True
    t.start()
    
    uid = webview.create_window("Formerly",
        min_size=(640, 480),
        debug = True
    )
    sys.exit()
```

**Comment by r0x0r** [comment]
Something like this

````
auth_token = 'SECRET'

def run_server():
    """ This will run in its own thread """
    webview.evaluate_js('windows.authToken = "%s"' %s auth_token)
    app.root_path = here
    app.run(host="127.0.0.1", port=23948, threaded=True)
    csrf = SeaSurf(app)
```
Import auth_token in your Flask app and use `window.authToken` in frontend.

**Comment by ibell** [comment]
Thanks!  Did you see my updates to the issue?

**Comment by r0x0r** [comment]
Yes.
One suggestion to your solution is do not assign to `window.pywebview` manually, as overwriting this object will interfere with the pywebview logic. Store the token someplace else. 

I will introduce a CSRF token on the house at some point.

**Comment by r0x0r** [comment]
CSRF token implemented in the `pywebview-3` branch. Flask app is also updated with the tokenized version.
