### ISSUE TITLE
window.open() support

### ISSUE THREAD

**Issue by joeysnclr** [r0x0r/pywebview#317]
### Specification
- Platform: Mac
- Version: 2.2.1

### Description
I am using Google sign-in for websites as a way for users to sign in to my web app. I have the google sign in button set up but pressing it doesn't open the sign in window when using pywebview. It works in a normal browser. It doesn't use target=_blank. I believe it is JS. Some help would be appreciated. Thank you!

**Comment by shivaprsdv** [comment]
If it is not `target=_blank`, it should be `window.open`. Pywebview doesn't
support popup windows either way.

**Comment by r0x0r** [comment]
Opening linkes using `window.open` is not currently supported. Feel free to contribute, if you find a solution.

**Comment by r0x0r** [comment]
I found a way to support window.open. 
@joeysnclr However, I am afraid, it won't help your cause, as there is no way to share a window opener object between original and new window.

PR here https://github.com/r0x0r/pywebview/pull/420
