### ISSUE TITLE
module 'clr' has no attribute 'AddReference'

### ISSUE THREAD

**Issue by kongfuzhou** [r0x0r/pywebview#319]
### Specification
- Platform:windows
- Version:2.4

### Description
run a hello world examp like:

import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')

got a error：
AttributeError: module 'clr' has no attribute 'AddReference'

my clr lib version is 1.0.3

**Comment by r0x0r** [comment]
Do you have pythonnet installed?

**Comment by r0x0r** [comment]
Closing due inactivity

**Comment by kongfuzhou** [comment]
> Do you have pythonnet installed?

yes! when I exec "pip install pythonnet" got a message like that:
 Requirement already satisfied: pythonnet in  \venv\lib\site-packages (2.3.0)

**Comment by r0x0r** [comment]
Activate your venv, run python, and type 
`import clr` and `clr.AddReference`. Does it work?
Another guess you have IronPython installed instead of `pythonnet`

**Comment by lacbs** [comment]
Just had the same problem, and here was my solution:
You may have installed the `clr` package thinking that would solve a problem before (not having clr module), but that package conflicts with `pythonnet`.
So the solution is `pip uninstall clr` (this way the `clr` module will come from the `pythonnet` package).

**Comment by icyqwq** [comment]
> Just had the same problem, and here was my solution: You may have installed the `clr` package thinking that would solve a problem before (not having clr module), but that package conflicts with `pythonnet`. So the solution is `pip uninstall clr` (this way the `clr` module will come from the `pythonnet` package).

Try this:

```
pip uninstall clr
pip uninstall pythonnet
pip install pythonnet
```

I guess you installed clr before pythonnet.

**Comment by Sandip-Hapani** [comment]
Tried all the above solution still getting a same error like above,

`AttributeError: module 'clr' has no attribute 'AddRefernce'`

I am using this snippet 
`from pythonnet import load
import clr
clr.AddRefernce("dll/StringLibrary")`
