### ISSUE TITLE
AttributeError: module 'webview' has no attribute 'create_window'

### ISSUE THREAD

**Issue by Sapython** [r0x0r/pywebview#321]
### Specification
- Platform: Windows 
- Version: 10 Enterprise
-Python Version: 3.6.6 

### Description
I am not able to execute the program because it is showing AttributeError: module 'webview' has no attribute 'create_window' error . my full error is

Traceback (most recent call last):
  File "E:\Sync\DevWorx\webview.py", line 1, in <module>
    import webview
  File "E:\Sync\DevWorx\webview.py", line 2, in <module>
    webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
AttributeError: module 'webview' has no attribute 'create_window'
[Finished in 0.3s with exit code 1]
[shell_cmd: python -u "E:\Sync\DevWorx\webview.py"]
[dir: E:\Sync\DevWorx]
[path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Users\SAPTAM\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\SAPTAM\AppData\Local\Programs\Python\Python36\;C:\Users\SAPTAM\AppData\Roaming\npm;C:\Users\SAPTAM\AppData\Local\GitHubDesktop\bin]

**Comment by Sapython** [comment]
I solved my issue by changing its file name from 'webview.py' to 'webviewer.py' or any other name instead of 'webview.py'

**Comment by XiaoPanPanKevinPan** [comment]
> I solved my issue by changing its file name from 'webview.py' to 'webviewer.py' or any other name instead of 'webview.py'

Thanks for the information! Can't believe I spent an hour or two on this problem 😂😂😂

**Comment by chrisdel101** [comment]
I'm getting this error too but I don't have a file named webview.
```
import webview
element = window.dom.create_element('<div>new element</div>')

 element = window.dom.create_element('<div>new element</div>') 
              ^^^^^^
NameError: name 'window' is not defined
```
