### ISSUE TITLE
File Not Found Error during pip install

### ISSUE THREAD

**Issue by twoonion** [r0x0r/pywebview#322]
I received same error as #293 during pip install of pywebview.  I read the solution to issue #293.  "That's an error with pythonnet. Either use Python 3.6 or check out the fixed version from pythonnet master.  pythonnet/pythonnet#609"  Can someone explain what this means?

**Comment by r0x0r** [comment]
You have three options 
1. Use Python 3.6
2. Checkout pythonnet master and install it in place of the pythonnet from pip
3. Wait for a new version of pythonnet
