### ISSUE TITLE
pywebview object not available by the time onload event fires

### ISSUE THREAD

**Issue by Jackodb** [r0x0r/pywebview#323]
I found a partial workaround for this issue that will allow you to mimic a redirect. You may be able to modify this to work for a refresh as well.

Before I had a button that triggered a redirect from '/' to '/home', and the pywebview variable disappeared on the '/home' page, as you've noted.

The fix was instead of redirecting from '/' to 'home', I would AJAX fetch the content of '/home' from '/' and then call document.write() on the '/' page with the response from '/home'. This keeps the location at '/' but allows me to display the content of '/home' while still having access to the pywebview variable. Hope that helps.

_Originally posted by @jrr8 in https://github.com/r0x0r/pywebview/issues/238#issuecomment-409350148_

I'm trying to make this work for my own script but I'm not sure how to do it. I'm trying to trigger JavaScript by using this (instead of a onclick button trigger):
`    window.addEventListener("load", function() {
      showChart();
    });`

This should then trigger this:
`    function showChart() {
      pywebview.api.getData().then(
        function(result) {
          drawChart(result.price,result.mountain,result.profit,result.title);
        }
      );
    }`

It gives me the following error, just like the one in the reference above:
![Screenshot 2019-03-30 at 12 35 27](https://user-images.githubusercontent.com/47478429/55275567-5a286d80-52e8-11e9-99c4-ce203b677564.png)

Any help would be appreciated!

**Comment by r0x0r** [comment]
Hasn't this issue been resolved already? window. pywebview should regenerate on refresh or navigating to another page.

**Comment by Jackodb** [comment]
It might have but I'm not aware of any documentation or resolved issue that could help me. Not sure what your suggestion is by the way. Do you suggest to change it to `window.pywebview.api.getData()`? getData() is a function that is initialised in my Python script. 

The weird thing is that when I include a button in my html page and say: `<button onclick="showChart()">show chart</button>` and press that button, everything loads perfectly. Though, when I use `window.addEventListener("load", function() { showChart(); });` it won't load and give me the error I posted in my initial post.

**Comment by Jackodb** [comment]
In case I use `window.addEventListener("mouseover", showChart);` instead of `window.addEventListener("load", showChart);`, it does work. Though, I still want to make it work on page load instead of hovering with the mouse first.

**Comment by r0x0r** [comment]
As I said earlier `pywebview` gets recreated on page refresh/navigate action.
I am not sure about your case with the JS load event. It might be that pywebview gets recreated after the load event is fired. If this is a case, I am afraid nothing can be done about that as this is by design. However, you might want to debounce your code, ie put it inside a setTimeout with a reasonable timeout value and see if that helps.

**Comment by Jackodb** [comment]
So, just to make sure you understand it correctly, I'm running the app in the following way: 

1. First I run this code in my Python script: 
```
api = Api()  
webview.create_window('<Strategy> visualisation', 'sample.html', js_api=api, width=900, height=650, debug=True)
```
2. I end up in my html file which then triggers my local Javascript file through:
``` <script src="sample.js"></script> ```
3. The following function is trying to get data from Python and run the function showChart:
```
window.addEventListener("DOMContentLoaded", function() {
  pywebview.api.getData().then(
    function(result) {
      drawChart(result.price,result.mountain,result.profit,result.title);
    }
  );
});
```
4. getData is defined as such:
```
class Api:

    def getData(self,params):
        fields = [list of values]
        df = pd.read_csv('test.csv',usecols=fields)
        price_list = [list of values]
        mountain = [list of values]
        return {
            'price': price_list,
            'mountain': mountain,
            'profit': list(df.Profit),
            'title': 'XXX'
        }
```
5. Finally it will run drawChart which is quite a long function which is probably best to not post in here. 

I didn't use `evaluate_js()` because things like `myChart.update();` don't get executed this way. Namely, I previously used:
```
def create_app():
     with open('sample.html', 'r') as x, open('style.css', 'r') as y:
         html = x.read()
         css = y.read()
         webview.load_html(html)
     webview.evaluate_js('showChart();')
     webview.load_css(css)
```
in combination with:
```
     t = threading.Thread(target=create_app)
     t.start()
```

I hope this helps!

**Comment by Jackodb** [comment]
When I use `window.pywebview.api.getData()`, so including the 'window', I get the following error:
![Screenshot 2019-03-31 at 10 28 15](https://user-images.githubusercontent.com/47478429/55286721-d8941680-539f-11e9-8f5a-1d8ef56ab17e.png)

I got this suggestion from https://github.com/r0x0r/pywebview/blob/master/examples/todos/assets/script.js

**Comment by Jackodb** [comment]
I fixed it using a setTimeout like this:

```
window.addEventListener("DOMContentLoaded", function() {
  setTimeout(function () {
    window.pywebview.api.getData().then(
      function(result) {
        drawChart(result.price,result.mountain,result.profit,result.title);
      }
    )}, 5000);
  });
```

Need to find a way to do it without a Timeout()

**Comment by Jackodb** [comment]
Fixed it. I'm using `evaluate_js()` in combination with threading now which seems to work fine. Though, I would like to know how to use an external JavaScript file instead of putting everything in my HTML file. Does any one of you know how to do that?

**Comment by shivaprsdv** [comment]
@Jackodb You just put the JavaScript file in the same directory or a sub directory
and link it the usual way: `<script src="/path/to/file"></script>"` in your HTML.
Check out the todos-app example (`/examples/todos`).

**Comment by shivaprsdv** [comment]
@r0x0r 
> I am not sure about your case with the JS load event. It might be that
pywebview gets recreated after the load event is fired.

Yes. I was about to bring this to notice. The JS `pywebview` object is not
available by the time `window.onload` or `body.onload` fires, as we inject
it _after_ the load has been completed (the load-finish handler on most of
the platforms I think).

> If this is a case, I am afraid nothing can be done about that as this is by
design.

I think it is desirable to have it available in `window.onload`. As the object
does not rely on the page resources at all, I consider it safe to inject it be-
fore the page load has completed, only if we could find a way to do it, that
is to say. It won't interfere with the DOM or JS-context.

**Comment by r0x0r** [comment]
While I agree that it would be desirable to have `window.pywebview` before onload, I am afraid it is not feasible. If anyone wants to investigate it, please go ahead, but bear in mind it should work on all the platforms uniformly.
I will update the documentation about this issue.

**Comment by Jackodb** [comment]
@shivaprsdv 
> You just put the JavaScript file in the same directory or a sub directory
and link it the usual way: <script src="/path/to/file"></script>" in your HTML.
Check out the todos-app example (/examples/todos).

I did this but I receive the following error:
![Screenshot 2019-04-05 at 23 45 08](https://user-images.githubusercontent.com/47478429/55658186-098ba580-57fd-11e9-8938-13bef9c31479.png)

My html code doesn't seem to parse the showChart() function I try to call in my Python script. So,

1. I try to call the JS function showChart in Python: `evaluate_js('showChart();')`
2. I have my JS script in the same directory as my Python script and referenced the JS script only in my html script: `<script src="sample.js"></script>`
3. The code the error message above is referring to (line 17 in sample.js) is the following:
```function showChart() {
  window.pywebview.api.getData().then(
        function(result) {
          drawChart(result.price,result.mountain,result.profit,result.title);
        }
      )}
};
