### ISSUE TITLE
Keystrokes on Windows

### ISSUE THREAD

**Issue by SaschaCowley** [r0x0r/pywebview#325]
### Specification
- Platform: Windows 10 64 bit
- Version: Pywebview 2.4, Python 3.7

### Description

When using the Trident webview, keystrokes are not captured correctly by event listeners.

#### Example

``` js
document.addEventListener("keyup", function(e) {
    alert((e.ctrlKey ? "ctrl + " : "") + (e.altKey ? "alt + " : "") + (e.shiftKey ? "shift + " : "") + (e.key));
});
```

* I press `A`, and it says "A" - good!
* I press `Ctrl` and it says "Control" - good!
* I press `Ctrl`+`A` and it says `Control` - bad

This only seems to affect some keys. For example, the above snippet works as expected with keys like `Tab` and `Enter`, but not with alphanumeric keys.

Note that the above code has been tested in Internet Explorer on the same device, and the code worked as expected.

The only thing I've been able to find that fixes this issue is setting `self.web_browser.WebBrowserShortcutsEnabled = True` in `winforms.py`, but that obviously introduces unwanted side effects.

**Comment by r0x0r** [comment]
Does this occur only with built-in shortcuts like Ctrl+A or with all the modifier keys?

**Comment by SaschaCowley** [comment]
It seems to be only keystrokes involving `Ctrl` and an alphanumeric key. For example, `Shift`+`G` works; `Alt`+`G` works; `Alt`+`Shift`+`G` works, `Ctrl`+`G` does not work; `Ctrl`+`Shift`+`G` does not work. Peculiarly, `Alt`+`Ctrl`+`G` and `Alt`+`Shift`+`Ctrl`+`G` do work.
