### ISSUE TITLE
pywebview cannot be installed using poetry

### ISSUE THREAD

**Issue by uyar** [r0x0r/pywebview#326]
### Specification
- Platform: 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Version: 2.4 (also 2.3 and 2.2 - version 2.1 is OK)

### Description

When using [poetry](https://github.com/sdispater/poetry) for project management, trying to add pywebview to the project using the command `poetry add pywebview --extras qt` fails with the below message:

```
[InvalidRequirement]
Invalid requirement, parse error at "'; <empty'"
```

I'm guessing this is due to the semicolons in the `install_requires` part of the `setup.py` script.

**Comment by r0x0r** [comment]
I have zero experience with poetry. Could you test your guess and report if it solves the issue?

**Comment by uyar** [comment]
I forked the pywebview repository, emptied the install_requires list (good thing I'm on Linux) and installation worked as expected using the following command:

```
poetry add --git https://github.com/uyar/pywebview.git --extras qt
```

So, yes, it must be the semicolons in the install_requires list.

**Comment by r0x0r** [comment]
Semicolons are valid setuptools syntax though. 
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies
May it be the spaces around semicolons?

**Comment by uyar** [comment]
No, I've tried without the spaces around the semicolons and got the same error.

When I look at a setup.py script generated by poetry, I see this kind of conditional requirement:

```
extras_require = \
{':python_version >= "2.7" and python_version < "3.0"': ['enum34>=1.1,<2.0']}
```

Does this help? Or should I report this to poetry?

**Comment by uyar** [comment]
I've been trying a few things but I can't figure this out, it's very strange. First of all, it's not the semicolons or the spaces: If I comment out the pyobjc and PyQt5 requires, it works. If I comment out pythonnet and PyQt5, it fails as described. And if I comment out pyhonnet and pyobjc it works, but it only installs pywebview and not the qt extra.

**Comment by uyar** [comment]
The problem seems to be with pyobjc. If I replace pyobjc with pythonnet for example, it gets installed.

I've posted the issue on poetry too: https://github.com/sdispater/poetry/issues/1024

**Comment by uyar** [comment]
I think there's nothing pywebview can or should do about this. My understanding is that it's a problem between pyobjc and poetry.

**Comment by uyar** [comment]
For future reference, pywebview 3.0 can be added to a project via poetry without problems.
