### ISSUE TITLE
Adding PyQtWebEngine as extra dependency

### ISSUE THREAD

**Issue by uyar** [r0x0r/pywebview#327]
### Specification
- Platform: Linux leylak 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Version: 2.4

### Description

After installing with `pip install pywebview[qt]`, the simple example script given on the documentation fails with the message:

```
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/uyar/Software/BUILD/test/.venv/lib/python3.6/site-packages/webview/__init__.py", line 87, in import_qt
    import webview.qt as gui
  File "/home/uyar/Software/BUILD/test/.venv/lib/python3.6/site-packages/webview/qt.py", line 41, in <module>
    from PyQt5 import QtWebKitWidgets
ImportError: cannot import name 'QtWebKitWidgets'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uyar/Software/BUILD/test/.venv/lib/python3.6/site-packages/webview/__init__.py", line 226, in create_window
    _initialize_imports()
  File "/home/uyar/Software/BUILD/test/.venv/lib/python3.6/site-packages/webview/__init__.py", line 158, in _initialize_imports
    raise Exception('You must have either QT or GTK with Python extensions installed in order to use pywebview.')
Exception: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```
Following the answer to [this StackOverflow question](https://stackoverflow.com/questions/51154871/python-3-7-0-no-module-named-pyqt5-qtwebenginewidgets), I installed `PyQtWebEngine` and the script worked.

I think this should be included in the `setup.py` file, as in:

```
extras_require = {
    'qt': ['PyQt5', 'PyQtWebEngine'],
    'cef': ['cefpython3'],
}
```

**Comment by r0x0r** [comment]
I have always installed QT dependencies using apt-get as per docs. Just to make it clear did you manage to install successfully using pip?

**Comment by uyar** [comment]
Yes, on a clean virtual environment, the following command installs and works correctly:

```
pip install pywebview[qt] pyqtwebengine
```

**Comment by r0x0r** [comment]
I have made changes to setup.py and updated documentation. Will make these changes live with 3.0.
