### ISSUE TITLE
create_window debug param has no effect

### ISSUE THREAD

**Issue by lebedov** [r0x0r/pywebview#328]
### Specification
- Platform: Ubuntu Linux 18.04.2
- Version: 2.4

### Description
When running the `debug.py` example modified to use qt as the GUI toolkit, right clicking on the displayed page does not bring up any menu from which to open the web inspector. I'm using pyqt 5.6.0 and python 3.7.1.

**Comment by r0x0r** [comment]
Debug is supported only with QTWebEngine, not with QTWebKit. In other words
my guess is that you are using QTWebKit

>

**Comment by lebedov** [comment]
Yes - my pyqt installation doesn't contain QtWebEngine for some reason. Would be good to mention the requirement in the online docs.

**Comment by r0x0r** [comment]
I updated the docs.

**Comment by lebedov** [comment]
Thanks!
