### ISSUE TITLE
some JavaScript in loaded HTML page doesn't seem to work

### ISSUE THREAD

**Issue by lebedov** [r0x0r/pywebview#329]
### Specification
- Platform: Ubuntu 18.04.2
- Version: 2.4

### Description

I'm trying to visualize interactive plots generated with HoloViews + Bokeh in pywebview. Although I can display the plots as follows, the interactive features provided by the embedded JavaScript don't seem to be working within the pywebview window; if I save the generated HTML to a file (i.e., by replacing `buf` with an output file name) and view it in a web browser, however, the interactive features do work:

```python
from io import BytesIO
import threading

import numpy as np
import holoviews as hv
import webview

curve = hv.Curve(range(10))
img = hv.Image(np.random.rand(10,10))
buf = BytesIO()
hv.save(curve+img, buf, backend='bokeh', fmt='html')
html = buf.read().decode()

def load_html():
    webview.load_html(html)

if __name__ == '__main__':
    t = threading.Thread(target=load_html)
    t.start()

    webview.config.gui = 'qt'
    webview.create_window('Example')
```

I'm using Python 3.7.1, PyQt 5.6.0, HoloViews 1.11.3, and Bokeh 1.0.4.

**Comment by r0x0r** [comment]
That's not enough information. Get debug going with QTWebEngine and proceed
from there.

>

**Comment by lebedov** [comment]
Must be another issue related to QtWebKit - when I switched to PyQt 5.12 (with QtWebEngine), the problem went away. Oddly, if I use QtWebKit in PyQt 5.6.0 to view the Bokeh plot directly (i.e., without pywebview), the problem doesn't occur.
