### ISSUE TITLE
Windows CEF Support

### ISSUE THREAD

**Issue by parthsdoshi** [r0x0r/pywebview#330]
### Specification
- Platform: Windows 10
- Version: 2.4

### Description
On Windows, I can't seem to get the GUI to use CEF over IE. I have made sure to install `cefpython3` and I call `webview.gui='cef'`. Do I need to do anything else?

**Comment by r0x0r** [comment]
It is webview.config.gui = 'cef'
Note that the syntax will most likely change in pywebview 3.0

>

**Comment by r0x0r** [comment]
Documentation fixed.
