### ISSUE TITLE
Using CEF causes a window inside a window to appear

### ISSUE THREAD

**Issue by parthsdoshi** [r0x0r/pywebview#331]
### Specification
- Platform: Windows 10
- Version:

### Description
It's best to explain with a picture:
https://imgur.com/a/5s8KOUG 

You can see that there is a rendering of the page inside the window.

My best theory right now as to why this happens is that it is a HiDPI problem but it seems like CEF Python has HiDPI support.

Any ideas as to why this happens?

Edit: Oh and this only happens when using CEF rather than IE. Also loading this same page in Chrome works fine.

**Comment by r0x0r** [comment]
Does this occur only with your application or with other pages as well?
Are you using fullscreen functionality?

>

**Comment by parthsdoshi** [comment]
It happens on any page and I'm not using anything past what's in this file:

https://github.com/parthsdoshi/fabel/blob/master/app/main.py

So I'm just calling
`webview.config.gui = 'cef'
webview.create_window('Fabel', 'http://localhost:4994', debug=True)`

I've tried it with debug being False as well.

**Comment by r0x0r** [comment]
This is strange, I have not encountered this behaviour. I vaguely remember something like this occurred with a fullscreen mode, but it was fixed in the early stages of development.

I am travelling right now and have no access to a Windows environment. I will get be able to get back to this in a couple of weeks.

**Comment by parthsdoshi** [comment]
Of course! I hope you have a great time on your trip.

In the mean time, I'll keep this thread posted on any new information.

As of now, I have found that it only happens on my Hi-DPI screen and the problem vanishes if I launch pywebview with CEF on my 1080p monitor instead.

I'll try looking more into cefpython's Hi-DPI settings and see if something needs to be enabled or if this is an issue on their end instead.

**Comment by parthsdoshi** [comment]
So I dug deeper and found a few threads on CEFPython's issue tracker and on CEF's forums.

https://github.com/cztomczak/cefpython/issues/358 
https://magpcss.org/ceforum/viewtopic.php?f=6&t=16687 

There's even one mention in the CEF issue tracker here:
https://bitbucket.org/chromiumembedded/cef/issues/1445

However, none seem to state a solution that can easily be used. I made a post on CEFPython's forum myself and we'll see where it goes from there.

**Comment by parthsdoshi** [comment]
Okay so Czarek Tomczak (author of CEFPython) helped me find a solution documented here:
https://stackoverflow.com/questions/55855723/how-to-stop-html-rendering-twice-in-the-same-window-on-hi-dpi-screens-using-cefp/55869426#55869426 

I'll copy and paste it here too:
The solution for me was to navigate to cefpython3's site-package directory, right click subprocess.exe -> properties -> Compatibility -> Change high DPI settings -> Override high DPI scaling behavior. Scaling performed by: -> Application.

Here's a picture that might make it simpler: https://i.stack.imgur.com/0xv3u.png 

So from what I understand, the subprocess probably wasn't telling Windows it is handling rendering for hi-dpi screens so Windows tries to scale it by itself. So telling Windows to let the subprocess handle it on its own fixes the problem. 

Now, I'm not sure how to programmatically fix this setting.

**Comment by r0x0r** [comment]
Thanks for investigating this. 
I found this way to do this programmatically
https://superuser.com/questions/1230346/overriding-high-dpi-scaling-from-the-command-line

This can be implemented in a similar manner as setting IE mode is done now. See `webview/win32_shared.py` for details. PR is welcome.

**Comment by parthsdoshi** [comment]
I don't know if that's a good solution. That would force `subprocess.exe` to always be run using Application hi-dpi scaling for that user but the CEFPython package can be reused by other projects where system scaling may actually be wanted.

I'm still discussing with the author in the comments here: https://stackoverflow.com/questions/55855723/how-to-stop-html-rendering-twice-in-the-same-window-on-hi-dpi-screens-using-cefp/55869426#55869426 

Let's see if there's a different solution. If not maybe it makes more sense to just tell users to add the manifest file when they're packaging the app into a .exe?

**Comment by cormacc** [comment]
FWIW, packaging your pywebview app with pyinstaller embeds the application manifest necessary to eliminate this. So won't affect your end users if you're distributing. It's still annoying getting the window in window when you're developing and running from your source tree though. I've taken the lazy approach of just setting the compatibility setting on the subprocess.exe in my project venv and letting pyinstaller take care of the distributable version.

**Comment by falan** [comment]
For people who need the manifest for packaging. This should fix the issue when distribute with pyinstaller exe.

<System.Windows.Forms.ApplicationConfigurationSection>
  <add key="DpiAwareness" value="PerMonitorV2" />
  <add key="EnableWindowsFormsHighDpiAutoResizing" value="false" />
</System.Windows.Forms.ApplicationConfigurationSection>

**Comment by justinmoon** [comment]
I just hit this same issue

**Comment by r0x0r** [comment]
PR here https://github.com/r0x0r/pywebview/pull/412
I have added a fix for Pyinstaller's frozen executable as well. Not quite sure whether it should point to subprocess.exe or the executable itself. Somebody please check.

**Comment by parthsdoshi** [comment]
Looks good but I think once pywebview exits, it should reset the registry flags.

**Comment by r0x0r** [comment]
It does that by deleting the subprocess.exe value.
