### ISSUE TITLE
Allow a way to set CEF settings before initialization

### ISSUE THREAD

**Issue by nbrochu** [r0x0r/pywebview#333]
The current CEF settings are hardcoded in the `init` method and allowing the user to customize them would be desirable and beneficial.

For example, in a production build, I do not want to be running a remote debugging server. This is done by setting `remote_debugging_port` to -1. By default, it starts one on a random port since the option isn't set. Nothing allows the user to control that behavior. I might also want to set a constant port of my choice to be able to debug in the same window across restarts or allow the context menu but with fine grain control over what shows up there.

By looking at the code, I think `webview.config` could be leveraged to do this in an agnostic way with something like a `platform_settings` entry that could extend the settings dict. I would venture for a PR but I know a new API is being worked on so maybe it's not the best time for it.

**Comment by shivaprsdv** [comment]
@nbrochu Yes, a new API is being worked on and in it, `webview.config` object is
_gone_, replaced by a new interface. May be this can be considered later on.

**Comment by nbrochu** [comment]
Thanks! I figured it wasn't the ideal timing. I can run a forked version for now but being able to not launch without the remote debugging server is a big deal. No production application would want users to be able to snoop around the debugging server, and that's ignoring the extra resources it takes to run it.

**Comment by r0x0r** [comment]
@nbrochu 
The philosophy of pywebview is to have a simple interface while providing sensible defaults. CEF settings are poorly documented, so it would be a poor choice to introduce this as a documentation dependency.
You have a valid point about remote debugging. Thanks for pointing this out! This option should be controlled via pywebview's own debug parameter.

**Comment by r0x0r** [comment]
The debug issue is fixed in the `pywebview-3` branch
