### ISSUE TITLE
Does not allow text selection

### ISSUE THREAD

**Issue by eltonfabricio10** [r0x0r/pywebview#334]
### Specification
- pywebview version: 2.4
- platform / version: linux / qt

### Description  
  
  Does not allow text selection, even with debug enabled

**Comment by r0x0r** [comment]
Do you have text_select set to True?

>

**Comment by eltonfabricio10** [comment]
No, sorry .... Thank you!

**Comment by eltonfabricio10** [comment]
How to enable cache to remember login?  for example Gmail

**Comment by r0x0r** [comment]
Password login is a browser feature, not available in a web view me thinks.
