### ISSUE TITLE
Pywebview fails to load js_api sometimes

### ISSUE THREAD

**Issue by MrLucio** [r0x0r/pywebview#336]
### Specification
- pywebview version: 3.0
- platform / version: Linux Manjaro

### Description  
  
  Pywebview running cef fails to load js_api sometimes, both on Linux (tested with 2 different computers) and Windows 10.
Windows 10 loads the js_api most of the times while Linux appears to fail every time.

This is the error displayed on the browser console: 

> Unhandled Promise Rejection: ReferenceError: Can't find variable: pywebview

**Comment by r0x0r** [comment]
Are you working with the latest `pywebview-3` branch?
I just tested with QT and GTK (js_api.py and token.py examples) and `window.pywebview` is present on both.

**Comment by MrLucio** [comment]
Yes I was working with the latest `pywebview-3` branch.
Turns out my problem is the same as [#323](https://github.com/r0x0r/pywebview/issues/323), so i just did a polling like system and now it works like a charm.
Thank you a lot anyway!
