### ISSUE TITLE
fullscreen = True not working on Windows

### ISSUE THREAD

**Issue by deiv23** [r0x0r/pywebview#338]
### Specification
- pywebview version: 2.4.0
- platform / version: win32

### Description  
  
fullscreen = True not working on Windows

**Comment by r0x0r** [comment]
win32 is deprecated and will be fully removed in 3.0
Use winforms version instead.

**Comment by deiv23** [comment]
How can I use winforms versión?
I tried this:
pip install pywebview[winforms]
_pywebview 2.4 does not provide the extra 'winforms'_

**Comment by r0x0r** [comment]
There was indeed a bug in the winforms implementation, which is now fixed in the `pywebview-3` branch. Sorry for misunderstanding.

**Comment by deiv23** [comment]
pip install git+https://github.com/r0x0r/pywebview.git@pywebview-3
Successfully installed pywebview-3.0

Now it doesn't work at all, it's not even opening the window.
Sorry I'm not an expert in Python, could you explain how can I make it work?

**Comment by r0x0r** [comment]
3.0 has the whole new API. See doc and examples in that branch for usage details.

**Comment by deiv23** [comment]
Ok, updated the code and now I get:
Cannot find Microsoft.Toolkit.Forms.UI.Controls.WebView.dll

**Comment by r0x0r** [comment]
There was a bug in dll copying. Try again now.

**Comment by deiv23** [comment]
same error.
I tried uninstalling with pip and reinstalling again

**Comment by r0x0r** [comment]
Apologies I forgot to push the code. What about now?

**Comment by deiv23** [comment]
same error.  : (

**Comment by r0x0r** [comment]
Works for me
```
PS C:\pywebview> pip install git+https://github.com/r0x0r/pywebview.git@pywebview-3
Collecting git+https://github.com/r0x0r/pywebview.git@pywebview-3
  Cloning https://github.com/r0x0r/pywebview.git (to revision pywebview-3) to c:\users\roman\appdata\local\temp\pip-req-build-tqxkfb6h
Switched to a new branch 'pywebview-3'
Branch 'pywebview-3' set up to track remote branch 'pywebview-3' from 'origin'.
Requirement already satisfied: pythonnet in c:\users\roman\appdata\local\programs\python\python36\lib\site-packages (from pywebview==3.0) (2.4.0)
Installing collected packages: pywebview
  Running setup.py install for pywebview ... done
Successfully installed pywebview-3.0
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\pywebview> python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import webview
>>> webview.create_window('test', 'https://google.com')
<webview.window.Window object at 0x000001EF4CD5F9E8>
>>> webview.start()
```

**Comment by deiv23** [comment]
It's working, I had another versión of Python installed, it was my mistake.
Now I have another problem, it's not playing a local video with the video tag. I saw an issue about that with no solution given.

**Comment by r0x0r** [comment]
Pywebview 3.0 uses EdgeHTML if available and currently it has a limitation
that it cannot display local URLs. Your options are
1. Use a local web server
2. Force MSHTML ie `webview.start(gui='mshtml')
3. Use CEF

As for video problems, I have never managed to reproduce it. Please get
back to me if it is still present once you get past the local file issue.



>

**Comment by deiv23** [comment]
I have set up a local web server, and its not logging the get for the HTML when I open the webview
		```
webview.create_window('layout 1', 'http://localhost:8000/layout1.html')
webview.start()
```
When I open it in the browser, I see the get in the logs, and it works ok:
127.0.0.1 - - [20/Jun/2019 12:16:24] "GET /layout1.html HTTP/1.1" 304 -
127.0.0.1 - - [20/Jun/2019 12:21:06] "GET /MM/01-Rick_n_Morty.mp4 HTTP/1.1" 200

**Comment by r0x0r** [comment]
The plot thickens. EdgeHTML disable localhost URLs by default. The issue is pretty common
https://www.startpage.com/do/dsearch?query=edgehtml+localhost&cat=web&pl=opensearch&language=english

Try to use MSHTML or CEF renderer, instead, ie
`webview.start(gui='mshtml')` or `webview.start(gui='cef')`

For CEF you need to have to cefpython installed 
`pip install cefpython3`

**Comment by deiv23** [comment]
With CEF, it loads the page, but not the video. I read that doesn't supports proprietary audio and video formats, and I need it to reproduce mp4.
With mshtml it doesn't load the page.

Thanks for your help anyway, and sorry for so many questions here

**Comment by r0x0r** [comment]
I found a workaround for a localhost issue, but it requires a UAC permission. The video works for MSHTML/EdgeHTML/CEF too. CEF can play only WebM videos though. 
Check `examples/http_server.py` for video example.

The fixes are pushed to the `pywebview-3` branch.
