### ISSUE TITLE
Video problems

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#339]
I have analyzed video problems and below is the summary. All tested with `examples/http_server.py` from the `pywebview-3` branch.

## Windows
- CEF / MSHTML / EdgeHTML. No problems with either. CEF supports only WebM and Ogg out of the box (MP4 not supported).

# Cocoa
- Only video frame is displayed, video not playing. Youtube works fine. There are a bunch of flags related to media in WKWebView. An answer might be there.

# QT 
- No problems

# GTK
-  Does not render a page if video is present. Youtube ok. 

This is not a priority. If it is for you, feel free to chime in.

**Comment by tservettaz** [comment]
Hey there,

First of all thanks for your nice work!
I'm not able to play mp4 (h264) or webm or ogg in a video tag. The video is loaded in a local html file with path "file:///c:/***/***/atoms.mp4" (and the html is loaded with "webview.windows[0].load_url("C:/***/index.html")"
It only render with CEF (with a webm video) but it does not autoplay :(

Everything's fine if I load the html file in a browser (chrome, firefox or edge).

My system is Windows 10 (64bits)

Do you have an idea on what could be the difference with your tests?

Thanks in advance for your answer!

Thomas

**Comment by r0x0r** [comment]
Could you upload your video somewhere?

**Comment by tservettaz** [comment]
Hi,
here, you will find 2 videos I used
http://tst.mycast.ch/temp/

PS: I think the problem is related to the fact I'm loading videos with absolute path

**Comment by r0x0r** [comment]
Does it make any difference if you use a builtin http server?

**Comment by tservettaz** [comment]
No...
but I managed to make it "work" with relative path fo medias and html file (starting from main.py script). but an exception occurs at the end of the video:

Exception happened during processing of request from ('127.0.0.1', 56768)
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\Python36\lib\socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python36\lib\socketserver.py", line 724, in __init__
    self.handle()
  File "C:\Program Files\Python36\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\Program Files\Python36\lib\http\server.py", line 406, in handle_one_request
    method()
  File "C:\Program Files\Python36\lib\http\server.py", line 639, in do_GET
    self.copyfile(f, self.wfile)
  File "C:\Program Files\Python36\lib\http\server.py", line 800, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "C:\Program Files\Python36\lib\shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "C:\Program Files\Python36\lib\socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

But it's maybe related to my javascript that removes de video tag after playing.

**Comment by r0x0r** [comment]
Both videos work EdgeHTML, but only webm works with CEF. I get no errors in the console, no idea what is the problem with the mp4 video. 

I get this exception as well, but it seems not to affect anything. I think it is a fault of the Python http server.

**Comment by tservettaz** [comment]
ok thx.
fun fact: if the video url begin with file:///c:/***/***/atom.mp4 it won't play in the pywebview application (ok with extrenal browser).
The src must start with a relative path (starting from py script)... don't know why.
Maybe good to know.

**Comment by r0x0r** [comment]
What renderer does this occur on? EdgeHTML, for one, does not support file:// urls at all, so a http server must be used.

**Comment by tservettaz** [comment]
Ok, so, I must use
`webview.start(http_server=True)`
and src would be something like `http://127.0.0.1/blablabla/atoms.mp4`
Where is the documentRoot of the builtin server? (in other words: where should I copy my 'blablabla' folder?)
thanks again for your support!

**Comment by tservettaz** [comment]
by the way, yes, I use EdgeHTML renderer because I want to use mp4 video files

**Comment by r0x0r** [comment]
For EdgeHTML you don’t have to do anything. HTTP server is started automatically if a file url is detected. Document root is the directory where index.html resides

**Comment by tservettaz** [comment]
ok... is it possible to get the (random) port used by HTTP server?

**Comment by tservettaz** [comment]
My problem is that EdgeHTML loads video cleanly when src begin with http://
When src begin with filename (or relative path) it loads the video with a spinner that is impossible to hide.

**Comment by tservettaz** [comment]
If I load a distant index.html wich plays distant mp4 video, everything's fine: no spinner, no Exception in console...

**Comment by tservettaz** [comment]
Is it anything I can configure on HTTP server thaht is started automatically with EdgeHTML renderer?

**Comment by r0x0r** [comment]
> ok... is it possible to get the (random) port used by HTTP server?

You can now via `webview.http_server.port`. The port is assigned after the server is started.

**Comment by r0x0r** [comment]
> If I load a distant index.html wich plays distant mp4 video, everything's fine: no spinner, no Exception in console...

It seems like a fault of the Python built-in HTTP server. It does not handle streaming media very well. Not sure if this can be fixed. Replacing it with another server might be a better choice.

**Comment by r0x0r** [comment]
FYI a new HTTP (hopefully better) server has been implemented. Now is in master and will be released in 3.3.
