### ISSUE TITLE
Missing installation dependecies for linux

### ISSUE THREAD

**Issue by akshayKMR** [r0x0r/pywebview#34]
Hey there, I have been using pywebview for  [hogwatch](https://github.com/akshayKMR/hogwatch/)

Users reported some missing installation dependencies on linux
https://github.com/akshayKMR/hogwatch/issues/6

Thanks.

**Comment by r0x0r** [comment]
Thanks for letting me know. Any advice on what pypi requirements to include by default? I am not that familiar with the Linux world and on my testing machine everything came preinstalled out of the box

**Comment by akshayKMR** [comment]
I'm not sure myself considering the large number of distros available. For now I've included a link to the issue in the readme.

**Comment by r0x0r** [comment]
I have added a pygobject pypi dependency and made GTK as default. Not sure if it solves the issue, but this is the most I can do without creating a Linux repo distribution package.

**Comment by pik** [comment]
Something is still unsatisfactory here: 

```
Requirement already satisfied: pywebview[gtk3] in /home/pik/.virtualenvs/hogwatch/lib/python2.7/site-packages/pywebview-1.6-py2.7.egg
Collecting PyGObject (from pywebview[gtk3])
  Could not find a version that satisfies the requirement PyGObject (from pywebview[gtk3]) (from versions: )
```
