### ISSUE TITLE
disable opening with default browser when click link

### ISSUE THREAD

**Issue by Batcastle** [r0x0r/pywebview#342]
### Specification
- pywebview version: 2.4
- platform / version: Ubuntu 18.04 LTS

### Description  
  
 I am trying to make a simple app which opens a webpage with pywebview, and does a bunch of other work in the background that will provide this website with more functionality. However, whenever a button or some other link is clicked, it opens the default browser. Is there a way to disable this functionality?
  
### Practicalities

- [X] I am willing to work on this issue myself. - I have moderate Python and basic C++ skills. I am more than willing to contribute in some way to help with this issue.

- [ ] I am prepared to support this issue financially. - I'm broke. Sorry. XD

**Comment by shivaprsdv** [comment]
@Batcastle It is the hyperlinks with `target="_blank` attribute that are opened
in an external browser. This was discussed earlier (check #153 and #235) and
implemented in PR #212. Basically what you need to do is reverse that PR; but
this was a feature that was painstakingly implemented, hard to take it away :she

**Comment by Batcastle** [comment]
That's fair. So if I removed the `target="_blank"` attribute from the link on the website it should remain in the `pywebview` window. Is this correct?

**Comment by shivaprsdv** [comment]
Yes, it would open in the same window. You can also set `target="_self"`,
for that matter.

**Comment by shivaprsdv** [comment]
@r0x0r Is this behaviour documented somewhere?

**Comment by Batcastle** [comment]
Alright. Thank you. I did not see this behavior documented in the Usage or Examples part of the website. Although it may be there and I just missed it :man_shrugging:

**Comment by r0x0r** [comment]
It had not beem documented indeed. I have added some examples now.

**Comment by AZMCode** [comment]
I would very much appreciate if this feature could get added in as an option. I'm working on an OAuth implementation, and the callback is opened in a browser, where i cannot capture it.

**Comment by r0x0r** [comment]
@AZMCode This is a valid concern. What would be a preferred way to handle this case?

**Comment by AZMCode** [comment]
Perhaps an event fired before navigating somewhere, or as @shivaprsd suggested, a flag in the config that switches this behavior

**Comment by r0x0r** [comment]
The switch to open _target=blank links in the same window could work. Would opening links in the same window help your oauth case?

**Comment by AZMCode** [comment]
Sorry, I don't think I understand what you mean.

**Comment by ABSK495** [comment]
We need a switch that allows all hyperlinks containing target=“_blank” redirected inside webview.

**Comment by r0x0r** [comment]
It is coming in 5.0

**Comment by wangruns** [comment]
> It is coming in 5.0

When will the 5.0 version be coming? I'm looking forward to it! I also need to allow all hyperlinks containing target="_blank" open its link inside webview rather than in a default system browser like Chrome or Edge.

**Comment by r0x0r** [comment]
The goal was to release it last year, but winter is a busy time for me. It is feature wise done, but needs to be tested and documentation updated. The current progress is in the `5.0` branch
