### ISSUE TITLE
Pyinstaller hook can't find WebBrowserInterop.x64.dll

### ISSUE THREAD

**Issue by Oracizan** [r0x0r/pywebview#346]
### Specification
- python version: 3.7.4
- pywebview version: 3.0
- pyinstaller version: 3.5
- platform / version: Window 10 64-bit

### Description  
The pyinstaller hook fails for me with the following error:

> Exception: WebBrowserInterop.x64.dll not found

Modifying the pyinstaller hook (**hook-webview.py**) resolved the issue. What I did was change the line  `library = join(sitepack, 'lib', dll_name)` to `library = join(sitepack, 'webview', 'lib', dll_name)`.

Researching the `getsitepackages` function that the hook uses suggests that it only ever returns the global site package directories (e.g. Python37\lib\site-packages) and not directories for specific modules, so the 'webview' directory will always need to be included manually.

I'm curious if this fix is indeed universally needed, or if there is something about my setup that requires it.
  
### Practicalities

- [x] I am willing to work on this issue myself.

**Comment by DominiqueAllen** [comment]
Additionally, I had to force pyinstaller to include `Microsoft.Toolkit.Forms.UI.Controls.WebView.dll` for the exe to run correctly.

**Comment by Oracizan** [comment]
Additionally, I had to force pyinstaller to include `Microsoft.Toolkit.Forms.UI.Controls.WebView.dll` before the exe worked correctly.

**Comment by r0x0r** [comment]
Yes, this is an error in the hook that needs to resolved on the pyinstaller level. Microsoft.Toolkit.Forms.UI.Controls.WebView.dll and its license file must be included as well.
Could you do a PR to Pyinstaller with a fixed hook? 

There is some bureaucracy involved in pyinstaller pull request. You can take a look at the comments in my previous PR to avoid making same mistakes. 
https://github.com/pyinstaller/pyinstaller/pull/3771/

**Comment by Oracizan** [comment]
Yes, will do, though it may be prudent to resolve #347 first in case the solution to that issue necessitates a change in the pyinstaller hook.

**Comment by Oracizan** [comment]
PR submitted: pyinstaller/pyinstaller#4312

This change will hopefully 'future proof' the hook to some extent. Any files added to the libs directory will now be found automatically.

**Comment by Oracizan** [comment]
PR submitted: pyinstaller/pyinstaller#4312

This change will hopefully 'future proof' the hook to some extent. Any files added to the lib directory will now be found automatically.

**Comment by r0x0r** [comment]
Good job!

**Comment by r0x0r** [comment]
@Oracizan I have tested the hook and it bundles the whole webview directory and its subdirectories. What it should instead is to bundle the contents of lib and place them in the same directory as exe.

**Comment by Oracizan** [comment]
Okay. I will adjust the code and report back.

**Comment by Oracizan** [comment]
@r0x0r The pyinstaller documentation for the `collect_data_files` function is incorrect. I will mention this to the PyInstaller team.

Can you confirm that replacing the line `datas = collect_data_files('webview', 'lib')` with `datas = collect_data_files('webview', subdir='lib')` works correctly?

By default PyInstaller places these required files in the webview/lib directory instead of the same directory as the exe, but this has not had an adverse affect on any of my builds.

**Comment by mariolatiffathy** [comment]
I didn't update PyInstaller for like 2 years, until I decided to update it to the latest version (3.5) 3 days ago and then I got the same error `Exception: WebBrowserInterop.x64.dll not found` (or) `Exception: WebBrowserInterop.x86.dll not found`

Packing pywebview using PyInstaller was fine until I had updated to PyInstaller 3.5. The fix of @Oracizan worked just fine!

**Comment by r0x0r** [comment]
@Oracizan `datas = collect_data_files('webview', 'lib')` includes only files under the lib folder, but still places them under `webview\lib`
I tried modifying datas manually to the effect of `[('actual dll path', '.')... ]`. This partly fixes the issue by placing dlls in the root directory, but for some reason it preserves  `webview\lib` as well.

Another thing that this hook should check for Windows.

**Comment by Oracizan** [comment]
All of my builds with the required files in `webview\lib` work correctly (on Windows 10 64-bit, at least). Given that PyInstaller seems to want those files in that location, is there an issue with letting them stay there?

**Comment by r0x0r** [comment]
The main issue is an aesthetic one. I would rather keep the file structure as flat as possible, but in the end whatever what makes it work.

**Comment by Oracizan** [comment]
Great. It is easiest not to fight the packager in my experience. 😄

I am still interested in future proofing this hook as much as possible. If I include a check for Windows before letting PyInstaller collect the `webview\lib` folder, can you foresee that causing any issues down the line for other platforms?

It seems that any future Mac or Linux required files would need their own folder, and the hook would then need to be updated to collect those folders.

I agree with not bundling unnecessary files, but I am wondering if this is something that should be considered before another PR is submitted to the PyInstaller repo.

**Comment by r0x0r** [comment]
Libs are Windows specific. I dont think there will arise a need for libs for other platforms. Even if there is, then a custom logic that would cherry pick correct libs for each platform would be needed anyway.

**Comment by herzit** [comment]
Hey guys,

I'm still facing the problem after trying to convert my py-script into exe through pyinstaller. I already tried the Suggestion from Oracizan. If I do so, pyinstaller creates the .exe file but it doesn't open after cliking it. Any News regarding that issue? 

Thanks in Advance!

**Comment by r0x0r** [comment]
@herzit build your exe with console support and check the output. Likely you have one of dlls missing or Flask or whatever output is not redirected.

**Comment by dweebio** [comment]
> Additionally, I had to force pyinstaller to include `Microsoft.Toolkit.Forms.UI.Controls.WebView.dll` before the exe worked correctly.

How can I do this? I have tried multiple methods, if I compile my application without --onefile I recieve and error saying that WebBrowserInterop.x86.dll is missing. How can I force pyinstaller to include Microsoft.Toolkit.Forms.UI.Controls.WebView.dll?

**Comment by Oracizan** [comment]
@r0x0r My PyInstaller PR (https://github.com/pyinstaller/pyinstaller/pull/4375) was merged. If all looks good to you, I think we can close this issue.

**Comment by RyannnnnnR** [comment]
@Oracizan I've tried the latest PyInstaller(off develop) with your changes and it works great. 👍

**Comment by volcan01010** [comment]
Based on above, I installed the latest pyinstaller (4.0.dev0+g9dd34bdf) directly from GitHub:

```bash
pip install git+https://github.com/pyinstaller/pyinstaller
```
The application was then able to build.  Thanks.
