### ISSUE TITLE
pywebview 3.0 does not work with pyinstaller --noconsole option on Windows 10

### ISSUE THREAD

**Issue by Oracizan** [r0x0r/pywebview#347]
### Specification
- python version: 3.7.4
- pywebview version: 3.0
- pyinstaller version: 3.5
- platform / version: Window 10 64-bit + Windows 7 32-bit

### Description  

pywebview 3.0 does not work on Windows 10 when frozen with pyinstaller using the --noconsole option. After fixing some issues (#346) I was able to get the .exe to build, but it crashes upon running.

I get no error messages from Python, but here are the results of some tests I ran:

#### Pass
- The program works on Windows 10 / 7 when run as a .py file.
- The frozen program, compiled on Windows 7 without the --noconsole option, works on Windows 10 / 7.
- A simple frozen 'Hello World' Python program works on Windows 10 / 7 with or without the --noconsole option.
- Modifying the program to use pywebview 2.4 instead of pywebview 3.0 caused the program to work correctly with the --noconsole option on Windows 10 / 7.

#### Fail
- A simple test webview program (akin to the example on the homepage here: https://pywebview.flowrl.com/) exhibits the same issue as my primary program when the --noconsole option is used.
- The frozen program, compiled on Windows 7 with the --noconsole option, works on Windows 7 but not on Windows 10.
  
### Practicalities

- [ ] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by SaranSundar** [comment]
So I got the frozen exe to work yesterday and today to some extent using this command.

pyinstaller -w -F --add-data "templates;templates" --add-data "static;static" --add-data "WebBrowserInterop.x86.dll;./" --add-data "Microsoft.Toolkit.Forms.UI.Controls.WebView.dll;./" --add-data "Microsoft.Toolkit.Forms.UI.Controls.WebView.LICENSE.md;./" --onefile -y app.py

Make sure you place those files in the local directory your code is.

**Comment by SaranSundar** [comment]
If you bring the .x64 in your local folder and use the command I gave replacing the x86 with x64 it should work.

**Comment by Oracizan** [comment]
What is your OS (and, if you know, what native webview is your exe using)? I reached the same conclusions as you about including those files, but the exe still only runs correctly for me on Windows 7 32-bit, not on Windows 10 64-bit.

**Comment by SaranSundar** [comment]
Im using windows 10 64 bit, the exe works almost, If you take a look at the issues I created one for the window height, but here are my user agents.

So this first user agent is when I run my code locally in pycharm and the next is when I run my exe. Locally works fine exe has a height issue but still works for the most part.

Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by Oracizan** [comment]
I tried your steps above, just to double-check, but they did not work for me.

**Comment by SaranSundar** [comment]
Hmm interesting was there any error? And maybe you might need to uninstall python and reinstall.

**Comment by Oracizan** [comment]
No error (at least not one that I can find).

And maybe so, though it would be very concerning if the executable built on a separate, clean Windows 7 machine was impacted by the Python setup on the Windows 10 machine. I will give it a try on a clean installation of Windows 10 & Python later and report back.

**Comment by Oracizan** [comment]
It works on a clean installation of Windows 10, so it must be something about my setup. I have no clue what, yet, but it is doubtful that it is a universal pywebview problem.
