### ISSUE TITLE
No application menu for Mac apps

### ISSUE THREAD

**Issue by cuibonobo** [r0x0r/pywebview#35]
A common pattern for Mac applications is to have an application menu available to perform functions like quitting the application or viewing the 'About...' menu. I've attached a screenshot of the application menu from a sample application packaged with `py2app` to show what it normally looks like. 

![screenshot 2016-06-06 16 59 13](https://cloud.githubusercontent.com/assets/391241/15837861/1ed37a94-2c09-11e6-83b3-f5b27e571dd4.png)

In apps that are created with `pywebview` and packaged with `py2app` the application menu isn't accessible. The app name appears in its usual place but clicking it does not produce a menu. Is there a way to enable this functionality?

**Comment by r0x0r** [comment]
The application menu is not supported by pywebview. It is definitely possible to implement it, but I don't see a clear strategy on how to integrate it into pywebview, while keeping the syntax clean.
Here's a discussion on how to create it in Cocoa http://stackoverflow.com/questions/3436395/how-i-can-get-the-application-menu-in-cocoa

PR's are welcome.
