### ISSUE TITLE
Option to start window centered and disabling scrollbars

### ISSUE THREAD

**Issue by mariolatiffathy** [r0x0r/pywebview#351]
### Specification
- pywebview version: 3.0
- platform / version: Windows 8.1 64-bits

### Description  
  
  Describe your issue

The PyWebView window starts with a random position on the screen, I'd like to start it centered but it seems PyWebView doesn't have such feature. It'd be appreciated if this could be added.
I've seen a similar issue here: https://github.com/r0x0r/pywebview/issues/158 , but the owner of the issue closed it immediately.
_NOTE_: It will be even better if we can set the X and Y position, so we can do like `position=(0, 0)` to center the window, instead of `position="centered"`

Also there should be an option to disable scrollbars as well, I currently disable them using CSS and JavaScript in HTML itself, but it'd be better if this can be disabled in the window through an option like `scrolling=False`.

**Comment by r0x0r** [comment]
My take on this is that the window should be centered by default with an option to set a custom position with  the `position=(x,y)` parameter.

I see no value in the `scrolling` parameter,  as it would be set with CSS anyway.

**Comment by r0x0r** [comment]
PR is open https://github.com/r0x0r/pywebview/pull/402
macOS logic does not work with multiple screens. I will leave it as is at this point.
