### ISSUE TITLE
Very big filesize when using pywebview with PyInstaller

### ISSUE THREAD

**Issue by mariolatiffathy** [r0x0r/pywebview#353]
### Specification
- pywebview version: 3.0
- platform / version: Windows 8.1 64-bits

### Description  
  
  Describe your issue:

Hello, I've been trying to use pywebview for around 3 days.. I've tried using pywebview with Flask, Django, and BottlePy (I don't mean all of the three in the same time, I mean I tried one of them on each try) - then I packed it using `pyinstaller --onefile --noconsole --add-data 'WebBrowserInterop.x86.dll;.' MyApp.py` but then the final EXE output file size is 80-90MB on the three web frameworks

I've wasted a lot of time trying all the Python web frame works but that didn't solve the problem.. it turned out at the end that `pywebview` was causing the problem, I've tried to remove pywebview and now my EXE output is 10MB

I wanted to use `pywebview` because of what is stated about it on PyPI.org:

> If you choose to freeze your application, pywebview does not bundle a heavy GUI toolkit or web renderer with it keeping the executable size small. pywebview is compatible with both Python 2 and 3.

**Comment by r0x0r** [comment]
It looks like pyinstaller bundles unnecessary dependencies (like PyQT if you have that installed). Solution use a clean virtualenv and install only what it is necessary. If you are using CEF, that's going to add additional 30mb to your bundle. Otherwise the base bundle size is 10-15mb.

**Comment by mariolatiffathy** [comment]
I'm new to the virtual environments, installing some of my packages resulted in errors as they store data in the default Python path :/

Anyway, thank you a lot! This is now a PyInstaller issue.

**Comment by mariolatiffathy** [comment]
I've uninstalled PyQt5 since I find no use of it anymore, this fixed the issue!

Thanks a lot.

**Comment by HuerFu** [comment]
@r0x0r @mariolatiffathy 
hello , My exe packaged in virtual environments is still very large, but I just imported webview, which is strange. I don't know why this happens.
![image](https://user-images.githubusercontent.com/26675540/63145887-bd166900-c02b-11e9-8a45-3003f60faefb.png)
![image](https://user-images.githubusercontent.com/26675540/63145921-d4eded00-c02b-11e9-9780-fe8d05adaf3a.png)
![image](https://user-images.githubusercontent.com/26675540/63145943-f949c980-c02b-11e9-8606-4eccb1c86d22.png)

**Comment by HuerFu** [comment]
I found out that this is the reason for the package cefpython 3. Win10 cannot use pywebview without cefpython 3
