### ISSUE TITLE
Cookie Support

### ISSUE THREAD

**Issue by Batcastle** [r0x0r/pywebview#354]
Is there support for cookies in `pywebview`, and if there is how would I go about using/enabling it?

For clarification, I mean cookie support as in, I want to be able to start a `pywebview` session, do something at a website which downloads a cookie, close the session, then open a new session, with the cookie from the previous session available to the current session.

For context, I am looking to make login to a social media network persistent across  usages of `pywebview`, unless specified in settings not to do this.

Thanks!

**Comment by r0x0r** [comment]
Cookies have not be tested, but I see no reason why they should not work. It should be trivial to test cookie support. Please share your findings.

**Comment by Batcastle** [comment]
In my experience, it seems that it's either saving cookies to some temporary directory which gets deleted after the session closes or cookies get saved to memory which then gets cleared when the program exits.

This is based on the fact that if I log into a website, then go elsewhere, then later come back to the website I logged into I am still logged in. Granted, I am no web dev so I could be wrong in my assumptions :sweat_smile:.

**Comment by humbletyrant** [comment]
> This is based on the fact that if I log into a website, then go elsewhere, then later come back to the website I logged into I am still logged in. Granted, I am no web dev so I could be wrong in my assumptions 😅.

This would be correct as the cookie is used to save user login and only expires if the user is to sign out, or if the user signs in from a separate location.

**Comment by retorquere** [comment]
Is it possible however to retain the cookies? I'd like the app to remain logged in across restarts of the app.

**Comment by retorquere** [comment]
Never mind, seems it just does.
