### ISSUE TITLE
Create_window opens two windows instead of one

### ISSUE THREAD

**Issue by ElhamAryanpur** [r0x0r/pywebview#355]
### Specification
- pywebview version: newest version
- platform / version: Ubuntu

### Description  
  
  When creating only one window with create_window, two windows appear one after another! First I thought it was problem of me using multiprocessing but same thing happen when I DON'T use multiprocessing!
   Thing I was doing was to run flask and webview to build an IDE for a language I made, but even running webview alone with absolutely nothing to interrupt, two windows open instead of one...

**Comment by r0x0r** [comment]
Sounds liek you call `create_window` twice. You can check windows you have created by calling `webview.windows`
