### ISSUE TITLE
AttributeError: module 'webview' has no attribute 'load_html'

### ISSUE THREAD

**Issue by estekadigital** [r0x0r/pywebview#359]
### Specification
- pywebview version: 3.01
- platform / version: Linux Debian 4.9.0-7-686-pae

### Description  
  
  When using webview.load_html I get the following error "AttributeError: module 'webview' has no attribute 'load_html'
  
### Practicalities

- [x] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
One word: RTFM.

The API has changed in 3.0

**Comment by estekadigital** [comment]
So, where can I find documentation and/or examples for version 3.0?

**Comment by r0x0r** [comment]
pywebview.flowrl.com
There is a blog post there too describing 3.0 changes.

>
