### ISSUE TITLE
It doesn't work when i add the `-w` parameter to pyinstaller.The exe can build,but it can't run.

### ISSUE THREAD

**Issue by aaronhua123** [r0x0r/pywebview#360]
### Specification
- pywebview version: 3.0.1
- platform / version: win10 -64

### Description  
  I use this command line to build your example flask_app to exe,
but It doesn't work when i add the `-w` parameter.
The exe can build,but it can't run.
 `pyinstaller -F -w --add-data "gui;gui" --add-data "src;src" --add-data "WebBrowserInterop.x64.dll;./" --add-data "Microsoft.Toolkit.Forms.UI.Controls.WebView.dll;./"
--add-data "Microsoft.Toolkit.Forms.UI.Controls.WebView.LICENSE.md;./" ./src/backend/main.py`
  I'm willing to follow your advice.

### Practicalities
 - [x] I am willing to work on this issue myself.

 - [ ] I am prepared to support this issue

**Comment by r0x0r** [comment]
It looks like a stdout issue with pyinstaller. Please try a solution described here https://github.com/r0x0r/pywebview/issues/343#issuecomment-514800165

**Comment by aaronhua123** [comment]
Wow !!! the solution is wonderful. Thinks，when i add this code，it can run without console.
```
from contextlib import redirect_stdout
from io import StringIO
stream = StringIO()
with redirect_stdout(stream):
    # app entry point
```

**Comment by aaronhua123** [comment]
Maybe we should add this code to the flask_app example, and no more people have this problem.

**Comment by r0x0r** [comment]
Yes, a good idea. Could you do a PR? I am away from computer until next week
