### ISSUE TITLE
exception python.runtime exception the remote procedure call failed

### ISSUE THREAD

**Issue by BlackTurtle123** [r0x0r/pywebview#361]
Python version:  3.7
Pyinstaller version: Git dev version
Pywebview version: latest
OS: windows 10 and windows 8 64 bit
Issue: When running the builded exe as administrator the exe fails and complains about missing RPC calls. Unbuilded version or non administrator running version don't give this issue.
Verified on 3 systems.
Why I report this issue here?
There are issues who point to toolkit/webview
`Onverwerkte uitzondering: Python.Runtime.PythonException: Exception : Kan RPC niet uitvoeren. (Uitzondering van HRESULT: 0x800706BE)
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   bij Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   bij Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   bij Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bij System.Threading.ThreadHelper.ThreadStart()`

![image](https://user-images.githubusercontent.com/16037736/62373368-ecac7800-b539-11e9-800d-87b4b3a6a844.png)

Am I willing to support this:
Potentially if I can get pywebview stable working with my app I am willing to donate or look into helping solve issues. For now I am trying this as experimental to check if it runs more stable then PyFlaDesk

**Comment by r0x0r** [comment]
This error is ahem double Dutch to me. Are you getting the same error with
the provided flask example if you try to freeze it on your computer?

**Comment by BlackTurtle123** [comment]
When it's freezed and we run it as administrator on my or other computers.
So freezing goes okay, running non frozen goes okay, running as non admin also goes okay.
It has some issues with rpc command it can't execute.
Exception in english: 
"Exception : The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
"

**Comment by r0x0r** [comment]
Can you test it with the just released 3.0.2?

**Comment by jorubyp** [comment]
I've been experiencing the same problem, and it doesn't seem like 3.0.2 has solved it for me unfortunately:

`Unhandled Exception: Python.Runtime.PythonException: Exception : The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds)
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize()
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by r0x0r** [comment]
Isolating the problem would help solve the issue. 
a) Does it occur with any examples?
b) What do you do to get this exception?


Googling revealed that the problem seems to occur when running under admin
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/50

EdgeHTML is buggy as af, so I would not hold my breathe that this will get fixed at any point.

**Comment by jorubyp** [comment]
a) Yes, it occurs with the Flask example
b) I run main,py in the Flask example, the server starts and is accessible for 15 seconds after which the error occurs.

**Comment by BlackTurtle123** [comment]
Yes I can confirm
Flask app fails
I start it, it start running and after 10-15sec it fails

Op di 20 aug. 2019 om 14:26 schreef Jo Ruby P <notifications@github.com>:

**Comment by r0x0r** [comment]
Works as non-admin, fails as admin throwing this exception here.

**Comment by flarios** [comment]
I'm getting the same exception when running as admin, when running unelevated it works just fine.

**Comment by r0x0r** [comment]
I have updated the documentation 
https://pywebview.flowrl.com/guide/renderer.html#edgehtml

Closing this issue now

**Comment by amalthomas-exe** [comment]
is there a fix for this issue??

**Comment by r0x0r** [comment]
1. Use other renderer. The new Chromium is way forward
2. Do not run as admin

**Comment by amalthomas-exe** [comment]
my work requires me to have admin priviledges to write information
can you suggest any other rendered..

**Comment by r0x0r** [comment]
Use Chromium or CEF. Instructions for installing Chromium can be found here.
https://pywebview.flowrl.com/guide/renderer.html

**Comment by r0x0r** [comment]
Updated installation guide. https://pywebview.flowrl.com/guide/installation.html

**Comment by amalthomas-exe** [comment]
It's working for me ! Thanks!

**Comment by SuperBoyne** [comment]
You should really try to fix this issue, it's really dumb.
