### ISSUE TITLE
Drop zone to get local full paths

### ISSUE THREAD

**Issue by juanfcocontreras** [r0x0r/pywebview#362]
Hello,

I would like to know if is possible with pywebview to create a "drop zone" in a web to get local file/folder paths?

I know this is not possible with Javascript for security concerns but I find `window.create_file_dialog(webview.OPEN_DIALOG...)` and I think that a drag&drop option will be even more user friendly.

Thanks in advance.

Best.

**Comment by r0x0r** [comment]
What's a drop zone?

**Comment by juanfcocontreras** [comment]
Sorry for the vagueness of the previous comment. I mean something like a div where an event is fired when a file or folder is dropped on. For example, the following javascript library (where I took the name from):

https://www.dropzonejs.com

The idea is to give the full path of a local file or folder to the pywebview app, but instead of picking up from the file system in the tradicional picker, dragging from the system explorer to some part of the pywebview window to that effect.

I hope I have explained myself better this time, and thanks for your time!

**Comment by r0x0r** [comment]
This sounds complicated. Some general level solution that would bypass this security measure might do, but I have no idea how to approach this problem.

**Comment by juanfcocontreras** [comment]
I understand. That's is what I thought. Thanks for your answer.

Please feel free to close this issue.

**Comment by alex-knyaz** [comment]
Hi. I'm also interested in this.

I think I have some idea as to how to approach this:
1. Implement per window drag & drop events for every platform, collect pointer coordinates.
2. Run client JS script, that will find HTML element under cursor, and dispatches corresponding JS event.
