### ISSUE TITLE
Cant call window methods anymore with just webview

### ISSUE THREAD

**Issue by SaranSundar** [r0x0r/pywebview#363]
### Specification
- pywebview version: 
- platform / version: 

### Description  
  
  I don't have access to the window variable in my flask app, I need something like the old 2.4 functionality where you can do webview.create_file_dialog(webview.FOLDER_DIALOG) vs window.create_file_dialog(webview.FOLDER_DIALOG) when I dont have a reference to window in my flask routes. Is this possible anymore or what can I do to make this possible?
  
### Practicalities

- [X] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You can use `webview.windows` to access opened windows. To get a reference
to the first window use `webview.windows[0]`

**Comment by SaranSundar** [comment]
@r0x0r Ok thanks that worked. But now when I use it this message pops up. 


objc[41390]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa0df73d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11826df50). One of the two will be used. Which one is undefined.

DO you know what this means or how to resolve it?

**Comment by SaranSundar** [comment]
Also is there a way to choose only specific kinds of files. Like if i want to look for only files with .signed.bin extension?

**Comment by r0x0r** [comment]
I cannot reproduce this error with file dialog examples. Yes you can
specify file types. Refer to the documentation.

**Comment by SaranSundar** [comment]
I think the error only happens on Mac os but it's consistently happened on any Mac I've tried it on. Also from the documentation I tried using ['All files *.signed.bin'] but that didn't work for me.

**Comment by shivaprsdv** [comment]
> objc[41390]: Class FIFinderSyncExtensionHost is implemented in both...

@SaranSundar This message pops up in the terminal (console), right? It is not an
error, only a warning related to some issue internal to macOS, I guess. Happens in
mine all the time. It causes no harm, just ignore.

> Also from the documentation I tried using ['All files *.signed.bin'] but that didn't work for me.

Use the proper format given in the docs. Something like this (the trailing comma is
required to make it a tuple): `file_types=("Signed Binary (*.signed.bin)",)`

**Comment by SaranSundar** [comment]
@shivaprsdv Yah it pops up in the terminal only. Ok thanks and where do you get the name Signed Binary from. Is it just something you can call whatever you want or is there a place where you get actual names from? Is the only part that matters the (" (*.signed.bin)",)?

**Comment by shivaprsdv** [comment]
Yeah, it is just a descriptive text for the type of file you want to open. Because
some systems (like macOS) shows this description & hides the file extensions.
Others (like Gtk) shows the actual extensions.

You can call it whatever, I just made it up from the extension you gave.
