### ISSUE TITLE
After pywebview runs, Echarts cannot interact

### ISSUE THREAD

**Issue by HuerFu** [r0x0r/pywebview#368]
### Specification
- pywebview version: 3.0.3
- platform / version: win10 64

### Description  
  
  Hello, I have a problem. On the web, I can interact with Echarts charts normally, but after pywebview runs, Echarts charts can not interact, and the mouse on Echarts charts does not respond. I hope you can help me. Thank you.
  
### Practicalities

- [ ] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I am not familiar with Echarts. You have to isolate your problem yourself.

**Comment by HuerFu** [comment]
thank you , I'll try again

**Comment by smpcode** [comment]
I met this problem again, I try to load butterfly url with pywebview, but in window, the mouse cant interact，butterfly can be installed by pip install butterfly
