### ISSUE TITLE
pyinstaller  freeze single app can't work

### ISSUE THREAD

**Issue by HuerFu** [r0x0r/pywebview#369]
### Specification
- pywebview version: pywebview3.0.1
- platform / version: win10 64

### Description  
  
  The pywebview runs normally, but after pyinstaller packages a single application in - F mode, the exe program fails to run, indicating that the breakpoint has reached the breakpoint.
  I hope you can help me. Thank you.
  
### Practicalities

- [ ] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Take a look at a solution described here https://github.com/r0x0r/pywebview/issues/343#issuecomment-514800165

**Comment by HuerFu** [comment]
@r0x0r I did it in your way, as follows：
![image](https://user-images.githubusercontent.com/26675540/62844382-7f47d680-bcf3-11e9-8f6e-677d4ba713d2.png)
But it had no effect.When I open the generated exe file after packaging, I still report the same error, as follows:
![image](https://user-images.githubusercontent.com/26675540/62844496-625fd300-bcf4-11e9-8170-a6d144ce90a6.png)
The debug.log file will output the following information:
[0812/112825.786:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.

**Comment by HuerFu** [comment]
Only in gui='cef' mode will this error occur, other modes are normal. But for some specific reasons, I have to use the gui='cef' model. So I'm wondering why this error occurs when using the cef renderer.
I found a lot of information on the internet, but I didn't find an effective solution. Thank you.

**Comment by falan** [comment]
FYR,
Have you try to pack bare bone cef pywebview app ?
I remember I have encounter something like this. It was the problem with ceftpyhon3 not packing correctly with pyinstaller. You can go to cefpython3 website to use their cefpython3-hook. I use their hook and working correctly after changing the hook of pyinstaller.

**Comment by HuerFu** [comment]
@falan Hello, could you tell me how to use the hook of cefpython 3? Thank you

**Comment by HuerFu** [comment]
> FYR,
> Have you try to pack bare bone cef pywebview app ?
> I remember I have encounter something like this. It was the problem with ceftpyhon3 not packing correctly with pyinstaller. You can go to cefpython3 website to use their cefpython3-hook. I use their hook and working correctly after changing the hook of pyinstaller.

I tried  pack bare bone cef pywebview app ,but report the same error.

**Comment by falan** [comment]
> @falan Hello, could you tell me how to use the hook of cefpython 3? Thank you

Go to
https://github.com/cztomczak/cefpython/tree/master/examples/pyinstaller

you can use the pyinstaller.spec as reference.
Copy hook-cefpython3.py to your local python /site-packages/PyInstaller/hooks/
You might also need to use latest hook-webview.py from pyinstaller 
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-webview.py

Good luck.

**Comment by HuerFu** [comment]
> > @falan Hello, could you tell me how to use the hook of cefpython 3? Thank you
> 
> Go to
> https://github.com/cztomczak/cefpython/tree/master/examples/pyinstaller
> 
> you can use the pyinstaller.spec as reference.
> Copy hook-cefpython3.py to your local python /site-packages/PyInstaller/hooks/
> You might also need to use latest hook-webview.py from pyinstaller
> https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-webview.py
> 
> Good luck.

I successfully solved this problem through your method. That's great. Thank you so much. I've been puzzled by this problem for a long time. I'm really happy to be able to solve it. Thank you again.

**Comment by HuerFu** [comment]
> Take a look at a solution described here [#343 (comment)](https://github.com/r0x0r/pywebview/issues/343#issuecomment-514800165)

Thank you. It's settled. Thank you.
