### ISSUE TITLE
Websockets arent working on WIndows inside pywebview

### ISSUE THREAD

**Issue by SaranSundar** [r0x0r/pywebview#370]
### Specification
- pywebview version: Latest master branch
- platform / version: Windows 10

### Description  
  
When I try to use web sockets to connect my python code to my javascript. It doesnt connect in pywebview window. But it works If i run the flask server and then go to the react ui on localhost in both Edge and Chrome. So it's something about the window being created by pywebview thats causing the localhost websockets connection to not be able to connect.
  
### Practicalities

- [ X] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a duplicate issue of https://github.com/r0x0r/pywebview/issues/241 
The original issue hasn't progressed at all, so input is welcomed.

**Comment by SaranSundar** [comment]
@r0x0r After a few days of debugging I finally resolved the issue. For some reason 127.0.0.1, 0.0.0.0, and localhost are not all treated the same. Only by typing localhost in all my ports everywhere did it finally work. 

If you want to test an example You can use this framework I made that comes with packaging and websocket support out of the box.

https://github.com/SaranSundar/Flair

Just cd into it in gitbash on windows, type python project-flair.py ~/Documents testApp

Then ./create_executable.sh

Then you can navigate to the ~/Documents/testApp/dist and open Flair.exe and you will see a demo with websockets fully working. Let me know if you have any issues.
