### ISSUE TITLE
Packing with pyinstaller is particularly large

### ISSUE THREAD

**Issue by HuerFu** [r0x0r/pywebview#372]
### Specification
- pywebview version: 3.0.1
- platform / version: win10 64

### Description  
  
When I pack it with pyinstaller, exe is very big. What should I do? I referred to this question #353, but it was of no use.
I found that cefpython 3 was responsible for the large size of packaged apps, but I don't know how to solve it.
Thanks a lot
  
### Practicalities

- [ ] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
On Windows you can use EdgeHTML / MSHTML. This will at least keep your bundle size small.

As for cefpython3, CEFPython's support forum is a better place to ask. I have no idea what the target size for CEFPython. CEF binary is around 30mb at least, maybe the rest could be shaved off.

**Comment by HuerFu** [comment]
@r0x0r 
Indeed, on win10 systems, only a dozen M files are packaged using gui= "mshtml" or gui= "gtk". But the files packaged with gui= "cef" are 160M. However, due to the poor compatibility of IE browsers, there will be some display problems with files packaged with gui= "mshtml". I hope that files packaged with gui= "cef" can also be small. Anyway, thank you very much. Thank you again.

**Comment by shivaprsdv** [comment]
This is because the CEF renderer is not present by default in any system, so
you _have_ to package it with your exe, much like what Electron does. It exists
as an option for people who don't care about the package size.
