### ISSUE TITLE
Python 2 support deprecation

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#373]
As it is becoming more laborious to continue supporting Python 2, I have decided to gradually phase the Python 2 support. The current compatibility layer will stay in place for the time being, but I am going to stop compatibility testing for Python 2 starting from macOS. In other words I have removed the Python 2 test job for macOS. The other platforms will follow at some point.

**Comment by Ksengine** [comment]
Contributors can except python2 compatibility in future development

**Comment by r0x0r** [comment]
Python 3.6 is now the minimum version starting from 3.6.
