### ISSUE TITLE
Pipenv install doesnt work for the latest version of pywebview

### ISSUE THREAD

**Issue by SaranSundar** [r0x0r/pywebview#374]
### Specification
- pywebview version: 3.0.2
- platform / version: MacOS High Sierra

### Description  
  
Pipenv install pywebview just stalls indefinitely. The only way I could get around this was using pipenv run pip install pywebview. All other pip packages work fine with pipenv install package-name. Not sure what changed in the latest version to cause this to break.
  
### Practicalities

- [ X] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Cannot reproduce. Clean pipenv install from homebrew, `pipenv install pywebview; pipenv shell` no problems encountered.
