### ISSUE TITLE
Javascript API does not seem to work

### ISSUE THREAD

**Issue by stetso** [r0x0r/pywebview#375]
### Specification
- pywebview version: 3.0.2
- platform / version: Mac OSX 10.14.6

### Description  

When trying to pass a dict from Python to the Javascript engine via the Javascript API, the Promise is never resolved. Nothing happens at all

Minimal example:

```python
  def get_item(self, params):
    return {
      'result': "Hello, World"
    }
```

With this on the Javascript side:

```javascript
function getItems() {
        pywebview.api
          .get_item()
          .then(resp => {
            console.log(resp);
          });
      }
```

I may be doing something wrong here because I cannot get the Javascript API example to run at all (the program simply quits immediately silently).

Additionally, I encountered another problem that may be related when passing through a payload that contains single quotes. I will open an another issue for that as well.

### Practicalities

- [ ] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Do you get any error output at all? Terminal or Console (the application)?
