### ISSUE TITLE
Javascript API: payload not parsed if it contains single quotes

### ISSUE THREAD

**Issue by stetso** [r0x0r/pywebview#376]
### Specification
- pywebview version: 3.0.2
- platform / version: Mac OSX 10.14.6

### Description  

When trying to pass a dict from Python to the Javascript engine via the Javascript API, the deserialization does not seem to work when the payload contains single quotes ('), but something is happening on the JS side at least.

Minimal example:

```python
  def get_item(self, params):
    return {
      'result': "Hello, 'World'" # Single quotes here
    }
```

With this on the Javascript side:

```javascript
function getItems() {
        pywebview.api
          .get_item()
          .then(resp => {
            console.log(resp);
          });
      }
```

Throws the following error in the Browser console: `[Error] SyntaxError: Unexpected identifier 'World'. Expected '}' to end an object literal.`

### Practicalities

- [ ] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Thanks for pointing this out. I have fixed this issue in master.
