### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#377]
I have research adding support for Android and it seems to be feasible via Kivy. The goal is to have Android supported with some tooling/documentation that would simplify/automate producing an APK. 

I have set up fundraising page to make this happen. If you want to see Android support implemented, donate to the issue.

https://opencollective.com/pywebview/expenses/

**Comment by Ksengine** [comment]
https://github.com/razzbee/kivy-android-webview

**Comment by Ksengine** [comment]
can you ask a help from @razzbee owner of above project

**Comment by razzbee** [comment]
> can you ask a help from @razzbee owner of above project

I will be glad to help, any instructions on contributing to the project??

**Comment by r0x0r** [comment]
@razzbee It would be great if you give this a tackle.

General contribution guidelines can be found here https://pywebview.flowrl.com/contributing/development.html

Android implementation would go `platforms/android.py`. It should implement methods specified by the window object (window.py) and `create_window`. Relevant window object methods are: `evaluate_js`, `load_html`, `load_url`, `get_current_url ` and `destroy`. Other window management methods are probably not applicable. There are four events: loaded, shown, closing and closed and window attributes such as transparent, background_color, confirn_close that should be implemented separately.

Additionally JS API support is a thing. It is done by exposing a python object to Javascript using logic in `js/api.py`. Object parsing is platform agnostic and should work as it is. The only thing that has to be added is a way to invoke Python code from Javascript (`_bridge.call` function in `api.py`).

Browser controls are not needed. All browser artefacts are disabled by default. Navigation keys, right click etc (some are probably not applicable to Android).

I am not sure about multiwindow support. At least the easiest way would be to drop it at this point.

**Comment by Ksengine** [comment]
@razzbee ?

**Comment by Ksengine** [comment]
for [beeware](https://github.com/beeware/)
```python
from rubicon.java import JavaClass
WebView = JavaClass("android/webkit/WebView")
WebViewClient = JavaClass("android/webkit/WebViewClient")
```

**Comment by Ksengine** [comment]
API is https://developer.android.com/reference/android/webkit/WebView

**Comment by razzbee** [comment]
> @razzbee It would be great if you give this a tackle.
> 
> General contribution guidelines can be found here https://pywebview.flowrl.com/contributing/development.html
> 
> Android implementation would go `platforms/android.py`. It should implement methods specified by the window object (window.py) and `create_window`. Relevant window object methods are: `evaluate_js`, `load_html`, `load_url`, `get_current_url ` and `destroy`. Other window management methods are probably not applicable. There are four events: loaded, shown, closing and closed and window attributes such as transparent, background_color, confirn_close that should be implemented separately.
> 
> Additionally JS API support is a thing. It is done by exposing a python object to Javascript using logic in `js/api.py`. Object parsing is platform agnostic and should work as it is. The only thing that has to be added is a way to invoke Python code from Javascript (`_bridge.call` function in `api.py`).
> 
> Browser controls are not needed. All browser artefacts are disabled by default. Navigation keys, right click etc (some are probably not applicable to Android).
> 
> I am not sure about multiwindow support. At least the easiest way would be to drop it at this point.

Sure, I will start working on it

**Comment by Ksengine** [comment]
@razzbee you hadnt forked it yet.

**Comment by Ksengine** [comment]
> for [beeware](https://github.com/beeware/)
> 
> ```python
> from rubicon.java import JavaClass
> WebView = JavaClass("android/webkit/WebView")
> WebViewClient = JavaClass("android/webkit/WebViewClient")
> ```

basic imports
```python
from rubicon.java import JavaClass, JavaInterface

# The Android cookiecutter template creates an app whose main Activity is
# called `MainActivity`. The activity assumes that we will store a reference
# to an implementation/subclass of `IPythonApp` in it.
MainActivity = JavaClass('org/beeware/android/MainActivity')


# The `IPythonApp` interface in Java allows Python code to
# run on Android activity lifecycle hooks such as `onCreate()`.
IPythonApp = JavaInterface('org/beeware/android/IPythonApp')
```

**Comment by razzbee** [comment]
Was setting up the environment, I don't build apps in python any longer, so
I had to setup the environment again.

**Comment by razzbee** [comment]
> > for [beeware](https://github.com/beeware/)
> > ```python
> > from rubicon.java import JavaClass
> > WebView = JavaClass("android/webkit/WebView")
> > WebViewClient = JavaClass("android/webkit/WebViewClient")
> > ```
> 
> basic imports
> 
> ```python
> from rubicon.java import JavaClass, JavaInterface
> 
> # The Android cookiecutter template creates an app whose main Activity is
> # called `MainActivity`. The activity assumes that we will store a reference
> # to an implementation/subclass of `IPythonApp` in it.
> MainActivity = JavaClass('org/beeware/android/MainActivity')
> 
> 
> # The `IPythonApp` interface in Java allows Python code to
> # run on Android activity lifecycle hooks such as `onCreate()`.
> IPythonApp = JavaInterface('org/beeware/android/IPythonApp')
> ```



> > for [beeware](https://github.com/beeware/)
> > ```python
> > from rubicon.java import JavaClass
> > WebView = JavaClass("android/webkit/WebView")
> > WebViewClient = JavaClass("android/webkit/WebViewClient")
> > ```
> 
> basic imports
> 
> ```python
> from rubicon.java import JavaClass, JavaInterface
> 
> # The Android cookiecutter template creates an app whose main Activity is
> # called `MainActivity`. The activity assumes that we will store a reference
> # to an implementation/subclass of `IPythonApp` in it.
> MainActivity = JavaClass('org/beeware/android/MainActivity')
> 
> 
> # The `IPythonApp` interface in Java allows Python code to
> # run on Android activity lifecycle hooks such as `onCreate()`.
> IPythonApp = JavaInterface('org/beeware/android/IPythonApp')
> ```

Back then I used pyjnius, but I will look into beeware implementation, seems its cool

**Comment by Ksengine** [comment]
its extracted from beeware/toga

**Comment by razzbee** [comment]
I am testing beeware as it provides native UI compared to kivy environment.

**Comment by Ksengine** [comment]
first beeware, then kivy

**Comment by zyugyzarc** [comment]
any updates?

**Comment by mohamed99elsokary** [comment]
any news ??

**Comment by r0x0r** [comment]
Not really. I have not been working on this, nor I have any idea whenever I have time or inspiration to work on this. Help is weclomed.

**Comment by meow464** [comment]
I'm working on a beeware implementation and doing iOS first. I know there is an ongoing effort to use kivy but as I see it, beeware and kivy are not exactly the same and it would be nice to support both like qt and gtk.

**Comment by Mglt-b** [comment]
Hi, any news?

**Comment by r0x0r** [comment]
I have now a working Android implementation based on Kivy / buildozer in the `android` branch.  Most of features are now implemented (minus window manipulation functionalities that do not scale to mobile), but implementation is probably buggy. I have considered `chaquopy`, as it has a better syntax / Java support than `pyjnius`. But I found a need for a rigid Gradle like project directory structure rather un-Pythonic. Buildozer's approach of just pointing to an entry file and including assets is much more appealing.

APK can be built with buildozer, but you need to explicitly include Java classes in `buildozer.spec`. In other words add either 
`android.add_jars = webview/lib/android.jar` or `android.add_src = interop/android/lib/src/main/java/com/pywebview`. Ideally android.jar should be included by pywebview, but I have not figured how to do it. Simply setting classpath lilke this has no effect.

```
import jnius_config
class_path = os.path.join(os.path.dirname(__file__), '..', 'lib', 'android.jar')
jnius_config.set_classpath('.', class_path)
```

Not sure if this can be done this way or maybe via p4a recipe. 
As always help is welcomed with this and other issues. There are a couple of TODOs in the android  code that should be solved. Testing would be appreciated too.

**Comment by r0x0r** [comment]
Released in 5.0.1

**Comment by diyism** [comment]
@r0x0r You're a genius.
I think pywebview is the first desktop+mobile webview platform in the world.
Thank you!

**Comment by kengoon** [comment]
@r0x0r Great work here, I think the best way to include a java or a jar file is by not including it at all. From my experience, the simplest and fastest way is to deploy the java module to maven and just add the Gradle dependency to buildozer.

**Comment by kengoon** [comment]
@r0x0r Also I'm well experienced with kivy and pyjnius and I can help with the android support.

Further improvement I want to propose: 

There's no need to really create a WebView around kivy widget because that will add to the size of the application. Pywebview focus i believe is only for WebView and wrapping around frameworks will create extra dependency and thus bloat the size of the application. I suggest doing this in 2 ways if possible: 1) creating an independent WebView without the help of any third party framework. 2) Having a separate module that supports Kivy for anyone who wants to integrate pywebview with Kivy.
That way, pywebview can still remain simple and less bloated and also offers support for a third-party framework.

**Comment by kengoon** [comment]
@r0x0r I can also build a hot-reloader for android first, then other platforms later. This will further reduce the stress of writing code and re-compiling (or re-running on desktop) all the time.

**Comment by r0x0r** [comment]
@kengoon 
This sounds very cool. I am not well versed in Android and kivy seemed like the path of least resistance. You are right that it is just webview with some minimal native ui functionality (like fullscreen or back button). 

If you find a way to improve it any way then please do. Use `6.0 branch as a base. 

There is no test suite for Android either. I haven't figured out how to make the current test suite running on Android. If you can figure it that would be most appreciated.

**Comment by kengoon** [comment]
@r0x0r I will get to work

**Comment by r0x0r** [comment]
@kengoon There are new Android related changes in the 6.0 branch, you might want to rebase if you already started

**Comment by kengoon** [comment]
@r0x0r I have forked the repo, but will start this weekend.
