### ISSUE TITLE
Pywebview JS API Not Loaded

### ISSUE THREAD

**Issue by mdushkoff** [r0x0r/pywebview#378]
### Specification
- pywebview version: 3.0.2
- platform / version: Windows 10

### Description  
After trying to implement a basic serverless application, it has come to my attention that the order of JavaScript injection seems to be affecting some basic functionalities.

It seems that the `pywebview` global variable is not injected by the time that the window's `onload` event fires, however I could not find in the documentation any JavaScript-level event that allows the detection of when it is actually ready to be used.

The very basic use case for this is the following:

```python
import webview

html = """
<!DOCTYPE html>
<html data-framework="javascript">
  <head>
  </head>
  <body>
    <div id='t'></div>
    <script>
      window.onload = function(){
        pywebview.api.run().then(function(res){
          document.getElementById('t').innerText += res;
        });
      }
    </script>
  </body>
</html>
"""

class API:
    def run():
        return 0

if __name__ == '__main__':
    api = API()
    webview.create_window("Test", html=html, js_api=api)
    webview.start(debug=True)
```

The expected output of this is to append a `0` to the proper element (accessing the `pywebview.api` and calling its `run` function).  Instead, the web console reports an error:

```
SCRIPT5009: SCRIPT5009: 'pywebview' is not defined
```

### Practicalities

- [x] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
JS API is available some time after onload. There is no way around that I am afraid.

What could be done, though, is to introduce a new custom event like `window.onwebviewready` or something along this lines.

**Comment by mdushkoff** [comment]
I figured that this would be the case already and created the following minimal working example that creates a `window.onbridge` function to detect this:

```python
import webview

html = """
<!DOCTYPE html>
<html data-framework="javascript">
  <head>
  </head>
  <body>
    <div id='t'></div>
    <script>
      window.onbridge = function(){
        pywebview.api.run().then(function(res){
          document.getElementById('t').innerText += res;
        });
      }
    </script>
  </body>
</html>
"""

def on_bridge(window):
    window.evaluate_js("if(window.onbridge){window.onbridge();}")

class API:
    def run(self, a):
        return 0

if __name__ == '__main__':
    api = API()
    window = webview.create_window("Test", html=html, js_api=api)
    webview.start(on_bridge, window, debug=True)
```

It may be more convenient to have an event built into the JS injection that fires on completion however instead of having to do something like this every time.

**Comment by r0x0r** [comment]
_pywebview_ now exposes a `pywebviewready` DOM event. For usage see `examples/js_api.py`
Change is merged with master.

**Comment by kletel** [comment]
example with javascript : 

// Function to wait for pywebview to become available
const waitForPywebview = async () => {
    return new Promise((resolve) => {
        const interval = setInterval(() => {
            if (typeof pywebview !== 'undefined' && pywebview.api) {
                clearInterval(interval);
                resolve();
            }
        }, 100); // Check every 100ms if pywebview is available
    });
};

const boot = async () => {
    try {
        await waitForPywebview(); // Wait for pywebview to be available
        // do something with pywebview python api here
    } catch (error) {
        console.error('Error waiting for pywebview:', error);
    }
};

onMounted(() => {
    boot();
});
