### ISSUE TITLE
CEF Javascript module import error: Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain"...

### ISSUE THREAD

**Issue by darthglowball** [r0x0r/pywebview#379]
Hi,

Importing anything in a HTML script tag results in the error:

`Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

When using `import './script.js'` or `import * from './script.js'` in a script tag which has `type="module"`. The pywebview HTTP server is active.

OS used: Windows 7, 32-bit

**Comment by r0x0r** [comment]
The built-in server does not implement content-type headers. It looks like those should be implemented by hand.

**Comment by r0x0r** [comment]
Actually screw the previous comment.
I could not reproduce the issue with CEF / Windows 10. Imports work without a problem.

**Comment by darthglowball** [comment]
@r0x0r could you give me something to try? The error message is consistent so I can't use any Javascript modules.

**Comment by r0x0r** [comment]
@darthglowball I think the crux of the problem is Windows 7.  As far as I remember CEF is using an older version on Windows 7. CEFPython support is probably a better place to ask.

**Comment by darthglowball** [comment]
@r0x0r I asked in cefpython. Meanwhile, I tried adding the header to `http_server.HTTPHandler.translate_path` with:
```
        if fullpath.find(".js") > -1:
            self.send_header("Content-type", "application/javascript")
            self.end_headers()
```

But I get the following error in CEF:
`Failed to load resource: net::ERR_INVALID_HTTP_RESPONSE`

**Comment by r0x0r** [comment]
As a wild guess you have to set a 200 http response as well. Use curl or
similar to see what your response looks like.

**Comment by darthglowball** [comment]
@r0x0r thank you, it works by adding 200 response! Would you add this fix to pywebview? It could help windows 7 users and make them stay with pywebview instead of immediately turning away, and it shouldn't harm other OS'es. Be aware of the standardisation MIME debate on "application/javascript" (can't remember wether this was the correct standard, but it works in my case).

**Comment by darthglowball** [comment]
@r0x0r wait.. Now there's another problem: the HTTP headers are inserted at the beginning of the .js files, making a syntax error occur when they're run..

**Comment by darthglowball** [comment]
Well, I have no idea how SimpleHTTPRequestHandler works but it seems that doing
```
            self.send_header("Content-type", "application/javascript")
            self.end_headers()
```
doesn't remove the old headers. I went into server.py and added `'.js': 'application/javascript'` to extensions_map.update and now the errors are gone. One more problem, the modules are never run and fetched, until you open Developer Tools. Once I right mouse click > Developer Tools, the python shell reports the HTTP gets of the .js files. But how to make this happen without having to open Developer Tools?
