### ISSUE TITLE
AttributeError: 'BrowserView' object has no attribute 'browser'

### ISSUE THREAD

**Issue by jicho** [r0x0r/pywebview#38]
Hi,

When I send a request from a controller in the web.py webserver (running in its of thread) I get the following error:

> INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): web.site.example
> ERROR:comtypes._comobject:Exception in DWebBrowserEvents2.DocumentComplete implementation:
> Traceback (most recent call last):
>   File "comtypes\_comobject.pyo", line 147, in call_without_this
>   File "comtypes\client\_events.pyo", line 117, in error_printer
>   File "webview\win32.pyo", line 273, in DocumentComplete
> AttributeError: 'BrowserView' object has no attribute 'browser'

Do you have any idea why this error is thrown on Windows 2003 / 2012? When I run the App in Pycharm in combination with Linux everything works like a charm...

This is the code that I'm using for the request:

```
import web
import json
import requests
from requests.auth import HTTPBasicAuth


class ApiSettings:

    def GET(self):
        practice_number = web.input().practice_number
        data = {
            'status': 404,
            'message': '',
            'data': {}
        }

        if len(practice_number) == 4 and practice_number.isdigit():

            r = requests.get('https://web.site.example/something'.format(practice_number),
                             auth=HTTPBasicAuth('user', 'password'))

            if r.status_code != 200:
                data['status'] = r.status_code
                data['message'] = 'Can\'t retrieve data'
            else:
                 response = r.json()

                 data['status'] = response['status']
                 data['message'] = response['message']

        web.header('Content-Type', 'application/json')
        return json.dumps(data)


```

Thanks for looking at this :)

**Comment by r0x0r** [comment]
It looks like the webview window is not created successfully, thus the
error. Show me the code where you create a webview window.

**Comment by jicho** [comment]
Hi,

This is how I create the webview window:

```
import sys
import threading
import web
import wegview
from app.helpers.startup import Startup
from app.urls import urls

# Disable error and print logging
# Source: www.p2exe.org/index.cgi/StderrorLog
sys.stdout = open('collector.log', 'w')
sys.stderr = open('collector.log', 'w')

webserver_port = Startup.get_free_port(port=8000)


def start_webserver():
    app = Startup(urls, globals())
    web.config.debug = False
    app.run(port=webserver_port)


if __name__ == '__main__':
    webserver = threading.Thread(target=start_webserver)
    webserver.daemon = True
    webserver.start()

    webview.create_window('Application',
                          'http://127.0.0.1:{0}/'.format(webserver_port),
                          width=800,
                          height=600,
                          resizable=True)

    sys.exit()
```

app.run(port=webserver_port) is the following code:

```
    def run(self, port=8080, *middleware):
        func = self.wsgifunc(*middleware)
        return web.httpserver.runsimple(func, ('127.0.0.1', port))
```

Looking forward to your reaction.

**Comment by jicho** [comment]
Hmmm... Looks like I've solved my issue after finding some more log date

The request was done to a https url, that caused the requests module to break because it could not find the certificates. 

For me the solution was to disable SSL verification, I know... it's an ugly solution, but in this cause no security issue.

Found the solution after reading this:
http://stackoverflow.com/questions/27726815/requests-exceptions-sslerror-errno-2-no-such-file-or-directory
