### ISSUE TITLE
Window close event?

### ISSUE THREAD

**Issue by noriellecruz** [r0x0r/pywebview#381]
### Specification
- pywebview version: 3.0.2
- platform / version: ubuntu / 18.04

### Description  
  
Hello, I'm trying to check or at least run a function when a window was closed but failed, there's also no event or way listed in the documentation.

I want to disable a button when a function from js api was called then enable it again when the window is is closed.  Is this possible? 
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
There is no such an event, but there should be one. It should be
fairly straightforward to implement it, as these events are already caught
for other purposes in the code. A closing event would not hurt as well. The
declarations would be:
`window.closed`
`window.closing`

Feel free to tackle this.

>

**Comment by r0x0r** [comment]
PR https://github.com/r0x0r/pywebview/pull/411
