### ISSUE TITLE
In "JS API", processing stops when some characters are used for the return value.

### ISSUE THREAD

**Issue by TakamiChie** [r0x0r/pywebview#383]
### Specification
- pywebview version: 3.0.2
- platform / version: Windows / 10 Home 1903

### Description  
  
In Python code called by the JS API, returning a string containing a single quotation (') to some of the data to be returned will result in an infinite loop and no processing will return to the caller's JavaScript.

#### JavaScript Code

```js
  pywebview.api.pdfwork(params).then((r) => {
    // do something...
  }
```
  
#### Python Code

```python
class Api:

  def pdfwork(self, params):
    # do something...
    responce = {
      "error": True,
      "message": "name 'Path' is not defined"
    }
    return responce
```

### The basis for determining that single quotation was the cause

Replacing a single quotation in message with &amp;apos;, the problem no longer occurs.

### Check around

If you specified double quotation marks or backslashes in the string, the problem did not occur.

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This issue has been fixed in the master branch
