### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by justinmoon** [r0x0r/pywebview#386]
### Description  
  
My app has one command that needs to be run as `sudo`. Is it possible for a pywebview app that wasn't launched as sudo to run a single command as `sudo`? To pop open a native "enter your admin password" window in some manner?

Something like [sudo-prompt](https://www.npmjs.com/package/sudo-prompt) on Electron?
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

yes

- YES/NO I am prepared to support this issue financially.

no

**Comment by r0x0r** [comment]
This is not a pywebview issue, but you can use this technique https://github.com/r0x0r/pywebview/blob/f0e731b2ff65da73a510cc12abd91f63851d1dc6/webview/platforms/winforms.py#L572
