### ISSUE TITLE
Modules are fetched only sometimes by the HTTP server, and clicking on Developer Tools fetches/runs everything

### ISSUE THREAD

**Issue by darthglowball** [r0x0r/pywebview#388]
Hi,

I have some scripts with `type="module"` and they don't always load. The Python shell doesn't always show a GET request for the .js module files. The HTTP server is activated. When there are no GET requests, no scripts are run. When having debugging enabled and right clicking and choosing Developer Tools, all modules will run and you will see corresponding GET requests in the Python shell and in the Developer Tools network section.

I'm using Windows 7.

**Comment by r0x0r** [comment]
Microsoft will end support for Window 7 in a couple of month, so I see no reason putting effort into supporting a 10 years old operating system.

Having said that, I will accept patches, if you find a solution. You can try serving your content with Flask or similar to see if that fixes the problem. See `examples/flask_app`

**Comment by darthglowball** [comment]
@r0x0r thanks for the suggestion. I fixed the problem by using the javascript bundler Parcel so that there is only a main script that contains everything.
