### ISSUE TITLE
Keyboard input not working with PyInstaller

### ISSUE THREAD

**Issue by psytron** [r0x0r/pywebview#389]
### Specification
- pywebview version:  3.0.2
- platform / version:  MacOSX Mojave 10.14.6. Python 3.7.4 ( brew install ) 

### Description  
Attempting to use PyWebView as GUI layer for python application compiled with PyInstaller --onefile.   For some reason the keyboard input is routed to the console and does not register in the pywebview window.

**Comment by psytron** [comment]
I realize this is probably similar to: https://github.com/r0x0r/pywebview/issues/66
But that issue is closed despite it still occurring in both VirtualEnv and Non-Venv python install. 
Is there a recommended workaround or fix for this?

**Comment by r0x0r** [comment]
I have successfully frozen apps on Mac using py2app. I have no idea about pyinstaller on Mac.

**Comment by danpalmer** [comment]
Hi all, I'm having the same issue running pywebview from the console.

pywebview: master
platform: macOS 10.15.4.

Looks like keyboard focus remains with whichever application had it before the window was shown.

**Comment by bascurtiz** [comment]
> Hi all, I'm having the same issue running pywebview from the console.
> 
> pywebview: master
> platform: macOS 10.15.4.
> 
> Looks like keyboard focus remains with whichever application had it before the window was shown.

Same here, see: 
https://stackoverflow.com/questions/64943328/input-fields-not-editable-wonky-arrows-when-compiled-on-macos

@danpalmer 
Have you managed to work around it?
