### ISSUE TITLE
Add load_string support.

### ISSUE THREAD

**Issue by ysobolev** [r0x0r/pywebview#39]
Please add a load_string method for when the HTML is stored in memory.

**Comment by r0x0r** [comment]
Please elaborate

**Comment by ysobolev** [comment]
Sure. Sometimes the HTML is stored in a variable. It is convenient to load it directly into the webview. For example, in the Gtk version you can do:
`webview.load_html_string("<html>foobar</html>", "")`
There is also a more general `load_string` method for non-HTML resources.

I wrote a small application which monitors a markdown file for changes, compiles it to HTML, and updates the webview. At the moment, it accomplishes this by writing the HTML to a temporary file and calling `load_url("file:///path/to/temp/file")`. It would be nice to load the HTML directly into the webview without having to save it first.

**Comment by r0x0r** [comment]
It has been discussed before and the implementation would involve creating
a temporary html file anyway as webview renderers work with urls, not html
content. It is a valid feature request though. If you would like to see it
done rather sooner than later, then feel free to submit a PR. :)

**Comment by ysobolev** [comment]
There is no need for a temporary file (except maybe on Windows). Gtk already has a `webview.load_string()` method, Qt has `QWebView.setContent()`, and Cocoa has `WebFrame.loadData`. I can write the Gtk and Qt versions if you like. They are about 5 lines of code each. I can also try to write the Cocoa version. However, I do not have a Mac or Windows box to test.

**Comment by r0x0r** [comment]
Ok gotcha. Did not know that. 
Please write an implementation if you have got time. I will be away for a couple of weeks, but will be able to get back to this issue after it.

**Comment by ysobolev** [comment]
Sure thing. It appears there is a way to do this on Windows as well. I already wrote the Gtk version. I will write the Qt version in the next few days. I will submit a PR when it is ready.

**Comment by ysobolev** [comment]
OK, I made a PR. Someone still needs to write the Cocoa and Win32 versions.

Also, my method will not work with binary resources (such as PNGs). Presumably, load_string should take a byte array, however Python 3 Gtk insists on a string object. So, I decided to give up on loading binary resources.

**Comment by r0x0r** [comment]
GTK and QT implementations are merged with master. Thank you! 

By the way how do you make sure that the webview window is loaded, before loading HTML? I have used a timeout of several seconds in testing, but it is far from a robust solution

**Comment by ysobolev** [comment]
Thanks!

I have been using a timeout as well. I suspect there is a better way. I will take a look in a few days and see what I can come up with.

**Comment by ysobolev** [comment]
So, one way to know when a webview window is ready is to listen for a signal. I think some code changes need to be made to expose this functionality to the user of pywebview. You need to attach the signal handler to the `webkit.WebView` object. For example, inside the `BrowserView` class:

    class BrowserView:
        def __init__(self, ...)
            # ... stuff ...
            webview = webkit.WebView()
            webview.connect("notify::visible", callback)

Here `callback` is a function you want to run when the webview is visible. There is also a `web-view-ready` signal, but I could not get it to work.

**Comment by r0x0r** [comment]
Thanks for investigating this. This should be integrated into the code somehow. Maybe introduce a webview_ready lock that would block load_html from executing until the webview is loaded.

By the way I have pushed a Cocoa implementation into master.

**Comment by r0x0r** [comment]
I have implemented signaling for Cocoa, GTK and QT. The whole Windows implementation is the only thing missing now. Once it is done, we are good to go.

**Comment by r0x0r** [comment]
There is now a Windows Forms version of webview that has a load_html implementation. Win32 is the only platform that is missing its implementation, but as WinForms covers Windows now I think we are good to go. 

PS: Here is an example code of how html content can be loaded in Win32, if anybody feels like giving it a go.
https://msdn.microsoft.com/en-us/library/aa752047(v=vs.85).aspx
