### ISSUE TITLE
gui='qt' doesn't work on MacOS?

### ISSUE THREAD

**Issue by rotu** [r0x0r/pywebview#393]
### Specification
- pywebview version: 3.0.2
- platform / version: MacOS Catalina

### Description

I'm encountering javascript crashes when trying to run my app with `webview.start(http_server=True, gui='qt')`. It works fine with the default (cocoa) gui on MacOS. I don't know if gui='qt' is expected to work on MacOS.

```
Connected to pydev debugger (build 193.4099.14)
127.0.0.1 - - [09/Oct/2019 17:57:37] "GET /main.html HTTP/1.1" 200 -
127.0.0.1 - - [09/Oct/2019 17:57:37] "GET /main.js HTTP/1.1" 200 -
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
127.0.0.1 - - [09/Oct/2019 17:57:38] code 404, message File not found
127.0.0.1 - - [09/Oct/2019 17:57:38] "GET /favicon.ico HTTP/1.1" 404 -
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
js: Uncaught TypeError: channel.execCallbacks[message.id] is not a function
[31799:775:1009/175743.688756:ERROR:permission_manager_qt.cpp(82)] Not implemented reached in ProfileAdapter::PermissionType QtWebEngineCore::toQt(content::PermissionType)Unsupported permission type: 13
[31799:775:1009/175743.688812:ERROR:permission_manager_qt.cpp(82)] Not implemented reached in ProfileAdapter::PermissionType QtWebEngineCore::toQt(content::PermissionType)Unsupported permission type: 13
```

In Debug mode, I'm able to get this trace:
```
VM27:137 Uncaught TypeError: channel.execCallbacks[message.id] is not a function
   at QWebChannel.handleResponse (<anonymous>:137:42)
   at Object.QWebChannel.transport.onmessage (<anonymous>:86:25)
```

When looking into this issue, I realize we create a new `QWebChannel` for every call to `window.pywebview._bridge.call`, which may or may not be a contributing factor.

### Practicalities

- YESI am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Another user pushed for support  QT on Mac, myself I haven't touched QT on Mac for ages, so no idea if it works or not. Fix is welcome though, if you manage to find a solution

**Comment by rotu** [comment]
It’s hard to say if this is user error or a problem in pywebview. I wish there were a current listing of which platforms are known to work and which are not.

**Comment by r0x0r** [comment]
Platforms covered by Travis tests are officially supported. In case of macOS QT it is somewhat in limbo. Personally I see no value in it.

**Comment by rotu** [comment]
Good to know. The main reason I wanted to try QT on Mac is because I intend to deploy to other platforms with QT and it would be nice to validate that development on my Mac.
