### ISSUE TITLE
When an exception occurs in the JS API, JavaScript does not return to control.

### ISSUE THREAD

**Issue by TakamiChie** [r0x0r/pywebview#394]
### Specification
- pywebview version: 3.0.2
- platform Windows 10 Home / version:  1903

### Description  
  
If you set a Python class in the JS_API of the constructor and an exception occurs in the methods of that class, javascript does not return to control.

```python
class Api:
  def test(self, parameter_list):
    with open("not_exists.txt", mode="r") as f:
      f.read()

api = Api()
window = webview.create_window(title="title", html = "<hrml></html>",
    width=640, height=320, js_api=api, min_size=(640, 400))
  webview.start(load_proc, window, gui="cef", debug="true")
```

```js
document.getElementById("execute").addEventListener("click", (e) => {
  pywebview.api.test().then((r) => {
    print("then") // not called.
  }).catch((r) => {
    print("catch") // not called.
  });
});
```

This problem was analyzed in my environment.
As a result, `window.pywebview._returnValues()` in the `_checkValue()` method described in `webview\js\api.py` is always `isSet = false` data has been returned, and it turned out that the process was not finished.

```js
    _checkValue: function(funcName, resolve) {
         var check = setInterval(function () {
            var returnObj = window.pywebview._returnValues[funcName]; // Always isSet = false.
            if (returnObj.isSet) {
                returnObj.isSet = false;
                try {
                    resolve(JSON.parse(returnObj.value));
                } catch(e) {
                    resolve(returnObj.value);
                }

                clearInterval(check);
            }
         }, 100)
    },
```

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Exception handling has never been much thought actually and silent fail has been modus operandi. As far as I understand, returning a value from a Python function is the only way to pass data from Python and Javascript, which makes exception handling difficult. 

What can be done though is returning an exception object to JS, detecting it as such and rejecting the promise. The JS API code would be written like this: 
```
    def func(self, params):
        try:
            raise Exception()
        except Exception as e:
            return e
```

**Comment by r0x0r** [comment]
On a closer look catching an exception manually is not needed. The entire logic can be done behind the scenes.

**Comment by r0x0r** [comment]
PR is open
