### ISSUE TITLE
Is possible to change webkit settings?

### ISSUE THREAD

**Issue by t-walker-wei** [r0x0r/pywebview#401]
### Specification
- pywebview version: 3.0.2
- platform / version: Debian

### Description  
  Is possible to change webkit settings? For example 'enable-webgl'?
  Thanks advance.

**Comment by r0x0r** [comment]
Currently no.
I am open to suggestions for enabling some options by default. Feel free to
investigate and report back.

>

**Comment by t-walker-wei** [comment]
Thanks.I hope coming soon.
