### ISSUE TITLE
How to embed the webview window to tkinter ui ?

### ISSUE THREAD

**Issue by idotools-xuqiang** [r0x0r/pywebview#405]
How to embed the webview window to tkinter ui ?

**Comment by r0x0r** [comment]
You cannot do that, at least not to my knowledge, as this defeats
pywebview's purpose. Use webview provided by tkinter if there is one.

**Comment by POMXARK** [comment]
> You cannot do that, at least not to my knowledge, as this defeats pywebview's purpose. Use webview provided by tkinter if there is one.

https://www.geeksforgeeks.org/how-to-open-a-website-in-a-tkinter-window/

is it possible or have you modified it?

**Comment by r0x0r** [comment]
No and no.
