### ISSUE TITLE
Two or more 'location.reload();' cause the engine EdgeHTML to freeze.

### ISSUE THREAD

**Issue by MirkoCovizzi** [r0x0r/pywebview#414]
### Specification
- pywebview version: 3.0.2
- platform / version: Python 3.7.4, Windows 10 64 bit

### Description  
  
Two or more 'location.reload();' (even from console) cause the engine EdgeHTML to freeze. A subsequent call to 'location.reload();' causes an 'unspecified error.'

**Comment by r0x0r** [comment]
Could you provide a barebone example?

**Comment by MirkoCovizzi** [comment]
Even the hello world example is enough. Load it, open the console through MS DevTools. Execute 'location.reload();' a couple of times and then the engine will freeze (not the whole ui, only the engine). Subsequent executions of 'location.reload();' will yield an 'unspecified error'.

**Comment by r0x0r** [comment]
How do you load your html?

**Comment by r0x0r** [comment]
This issue is apparently caused by SimpleHTTPServer stalling on a request and being unable to process the next one. 

Some relevant info:
https://stackoverflow.com/questions/43146298/http-request-from-chrome-hangs-python-webserver

**Comment by r0x0r** [comment]
I have pushed a fix to the master branch. Please test if it solves the problem for you.
