### ISSUE TITLE
How to do SSE (Server-Sent Events) when using pywebview's serverless architecture?

### ISSUE THREAD

**Issue by roniemartinez** [r0x0r/pywebview#418]
### Specification
- pywebview version: N/A
- platform / version: N/A

### Description  
  
How to do SSE (Server-Sent Events) when using pywebview's [serverless](https://pywebview.flowrl.com/guide/architecture.html#local-web-server) architecture? This is useful for real-time events like monitoring progress or system messages.

**Comment by r0x0r** [comment]
As SSE work only with URLs, you cannot use them in the serverless architecture.
Alternatively you can put `evaluate_js`in a loop or invoke it using events or something like that

**Comment by roniemartinez** [comment]
Hi @r0x0r 

Are there any other alternatives? I was hoping for a way to update the UI from a long running task in a JS API thread (like a push or similar). Polling is not really a great solution.

**Comment by r0x0r** [comment]
Just use evaluate_js to invoke an appropriate JS function, fire a JS event
or whatever.

>
