### ISSUE TITLE
Freezing - PyInstaller - Issues with 'WebBrowserInterop.x64.dll'

### ISSUE THREAD

**Issue by Mefteg** [r0x0r/pywebview#421]
### Specification
- pywebview version: 3.0.2
- platform / version: Windows / python 3.7.4

### Description  
  
Hi,

When freezing my app with `pyinstaller`, I have troubles with "WebBrowserInterop.x64.dll".
I don't know where to put it and when I launch the ".exe", the console logs `System.IO.FileNotFoundException` but the path is correct.

Could you help me with this and/or give a template/backbone for freezing please ?

Thanks,
Tom
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
See this issue https://github.com/r0x0r/pywebview/issues/346

**Comment by Mefteg** [comment]
Thank you for the answer.
I also had an issue with `cefpython3` but I managed to resolve it by manually copying all the module inside the "freeze" folder after pyinstall process.
If you know a better way, I'm all ears :)
