### ISSUE TITLE
js_api doesn't pass multiple arguments

### ISSUE THREAD

**Issue by melvinkcx** [r0x0r/pywebview#422]
### Specification
- pywebview version: 3.0.2
- platform / version: ArchLinux

### Description  
  
 js_api doesn't pass multiple arguments.

Python:
```
class API: 
    def foo(self, x, y, z):
          return True
```

When trying to invoke `foo()` in 
JS:
```
window.pywebview.api.foo(x, y, z);
```

I get this in Python:
```
TypeError: foo() missing 2 required positional arguments: 'y' and 'z'

```

  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a limitation of the underlying platforms. The number of arguments must be fixed. 
If you need to pass multiple arguments, pass an array or Javascript object instead.

**Comment by melvinkcx** [comment]
Thank you for your prompt response. It would be great if this can also be added into the documentation.

**Comment by r0x0r** [comment]
Screw my previous comment. I found a way to accept an arbitrary number of parameters. The change is now in master.
