### ISSUE TITLE
Webview is not found after frozen with PyInstaller on MacOS

### ISSUE THREAD

**Issue by melvinkcx** [r0x0r/pywebview#424]
### Specification
- pywebview version: 3.1
- platform / version: MacOS 10.14 Mojave with Python 3.8 (using pipenv)

### Description  

This is my first time freezing app on MacOS, I first tried to using py2app, but to no avail. On linux, the exact same script did the trick:

```
pyinstaller --onefile \
  --windowed \
  --hidden-import configparser \
  --add-data './view/dist:./view/dist' \
  --icon icon.ico \
  --log-level DEBUG \
  main.py
```

Build log:
[build.log](https://github.com/r0x0r/pywebview/files/3828214/build.log)
 
It is successfully built, however, when I run the app in `/dist`:
![Screen Shot 2019-11-10 at 0 21 59](https://user-images.githubusercontent.com/16914545/68541099-37673880-0350-11ea-8edb-97ad598fc0dd.png)

I appreciate any input for this issue. Thanks.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by melvinkcx** [comment]
I tried to add `webview`/`pywebview` as hidden imports too.

**Comment by melvinkcx** [comment]
I managed to make it work by not using pipenv or any virtual environment.

**Comment by AlexanderWillner** [comment]
@melvinkcx any specific details? I think my issue #496 relates to this one.
