### ISSUE TITLE
Supports App Icon on Qt/GTK based platforms

### ISSUE THREAD

**Issue by melvinkcx** [r0x0r/pywebview#427]
### Specification
- pywebview version: 
- platform / version: Linux

### Description  
  
Correct me if I'm wrong. App icon on Taskbar is only supported on Windows. It would also be great if this is also supported on Qt/GTK based system. 
  
### Practicalities

- YES I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Both QT and GTK support tray icons:
https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html
https://doc.qt.io/qt-5/qsystemtrayicon.html
