### ISSUE TITLE
Add minimize to System Tray 

### ISSUE THREAD

**Issue by melvinkcx** [r0x0r/pywebview#428]
### Specification
- pywebview version: 
- platform / version: Linux

### Description  
  
I know this has been brought up in the past but was dismissed due to the complexity. I am really interested to add this feature on a project I'm working on. I haven't look much into the complexity of implementation. My question would be if this is possible?  

### Practicalities

- YES am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Support for taskbar icon has been requested, but nobody has given it a go and it has not progressed anywhere. It is definitely possible and should not be too hard. Some issues that need to be solved include
- system tray icon format suitable for all the platforms
- menu items format and syntax
