### ISSUE TITLE
Inspector error

### ISSUE THREAD

**Issue by t-walker-wei** [r0x0r/pywebview#429]
### Specification
- pywebview version: 3.1
- platform / version: Debian

### Description  
  
  When I tried debug the page in pywebview. The inspector show me internal error:
`TypeError: failed to initialize NumberFormat due to invalid locale (at Utilities.js:801:57)
    NumberFormat @ [native code]
    toLocaleString @ [native code]
    d @ Utilities.js:801:57
    value @ Utilities.js:881:64
    value @ Utilities.js:899:29
    _loadNewRecording @ TimelineManager.js:655:108
    reset @ TimelineManager.js:114:31
    TimelineManager @ TimelineManager.js:62:19
    loaded @ Main.js:130:50
    global code @ Main.html:808:18`
I use pywebview 3.0.2 before, it was ok for debug.

**Comment by r0x0r** [comment]
Cannot reproduce with QT or GTK.

**Comment by t-walker-wei** [comment]
I found the solution. This is my system and webkit issue. After change my system locale, the inspector works.
[Bug description](https://bugs.webkit.org/show_bug.cgi?format=multiple&id=167991)
[How to change debian locale](https://wiki.debian.org/ChangeLanguage)
