### ISSUE TITLE
WebViewException: "Main window failed to start" when using js_api

### ISSUE THREAD

**Issue by MirkoCovizzi** [r0x0r/pywebview#431]
### Specification
- pywebview version: 3.1
- platform / version: Python 3.7.5 x64 Windows 10, default web engine

### Description  
  
I have an application in which about 60 times per second a short python function is called from Javascript when a specific element is used (a knob). As soon as I stop using the element that triggers the function for more than 15 seconds the exception above starts to be raised randomly. I fear this could lead to memory leak since some 
"Desktop App Web Viewers" processes sometimes are not closed correctly. Is there any way to solve this or is this a feature and not a bug? Thanks.

Update:
The leak appears to be happening only when the python process gets killed, without closing the window. If at start it spawns two Web Viewers, when killed it kills only one, leaving one behind, probably the api one.

**Comment by r0x0r** [comment]
`WebViewException: "Main window failed to start"` occurs when you try to invoke any window methods and either loaded or shown event is not set for one or another. It is impossible to say that causes this.  Could you provide code that would illustrate the problem?

**Comment by MirkoCovizzi** [comment]
It's very simple code. I have a javascript call to pywebview.api.set_value(v); every 17ms in a listener function that triggers only when I actually interact with the ui object. Then, the set_value(self, params) is just a single api funciton that simply sets a variable to the params value. That's it. The exceptions start to get thrown 15 seconds after the interaction and on a number of threads proportional to the number of calls to set_value(), always starting from Thread-13. For example, if I interact with the object in a way that calls the api 4 times, after 15 seconds I get 4 exceptions (on Thread-13 up to Thread-16).

**Comment by MirkoCovizzi** [comment]
Found the culprit. For some reason, exceptions appear to be silent.

If I have:
window = webview.create_window(...)
window.loaded += start_func
webview.start()

and:

def start_func():
    ...
    raise ValueError("Error")

The error is not thrown and is silent in the console. This, after 15 seconds of interaction with the UI triggers those WebViewExceptions for each call of the api. Of course I'm not raising exceptions on purpose in my project, but I had an exception being thrown in the start_func and was silent so I couldn't of course pinpoint what was the problem.

A simple way to test for this behavior is to take the js_api example in the documentation (on the website) and add "window.loaded += start_func" between window creation and webview.start(). Then define a start_func() that raises a ValueError. After clicking for example the "HELLO PYTHON" button the response is not received and not shown and after 15 seconds the WebViewException is thrown.

**Comment by r0x0r** [comment]
Yep this is the case. Exceptions are silently ignored in python.net threads.  I don't know exactly why is that, but I suspect the reason is with python.net. The best course of action would be to wrap your code in try.. except in case of an uncaught an exception. At least this way you can track an exception.

**Comment by MirkoCovizzi** [comment]
What about swapping .net threads for python threads? I assume the .net one and the python one both use Windows threading api, so at this point I think it's safer to use a threading layer safer and proved which is the one python offers officially. In the end a thread is a thread. Unless there is a specific reason to use .net threads.

**Comment by r0x0r** [comment]
I introduced event catching in event handlers. PR here https://github.com/r0x0r/pywebview/pull/441
This should do the job.
