### ISSUE TITLE
JS alert() not working on Windows 10 and EdgeHTML option

### ISSUE THREAD

**Issue by Yossli** [r0x0r/pywebview#432]
### Specification
- pywebview version: 3.1
- platform / version: Windows 10 (build 18362), Python 3.7.2, Flask 1.1.1, Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18362

### Description  
 
If the application (front end) use JS alert() function, no alert box is displayed. When gui='mshtml' is set, alert() pop-up the alert box. When page is opened in normal browser (outside of application), no issue.
  
### Practicalities

- NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Fixed in master.
