### ISSUE TITLE
External killing of the python process where main thread is running leaves zombie (Desktop App Web Viewer)

### ISSUE THREAD

**Issue by MirkoCovizzi** [r0x0r/pywebview#433]
### Specification
- pywebview version: 3.1
- platform / version: Python 3.7.5 x64 Windows 10, default web engine

### Description  

If the python process running the main script gets killed externally, one of the two Desktop App Web Viewer processes doesn't terminate, causing memory leak.
Steps to reproduce: execute any of the demos. 2 Desktop App Web Viewer processes will spawn. Kill the python process that runs the script. One of the two Desktop App Web Viewer processes (Microsoft.Win32WebViewHost) will stay alive.

**Comment by MirkoCovizzi** [comment]
It appears the problem arises because the window.browser.js_result_semaphore is not released if BrowserForm.on_close() is not called from winforms.destroy_window(). Adding self.pywebview_window.browser.js_result_semaphore.release() at the end of BrowserForm.on_close() solves the issue.

**Comment by r0x0r** [comment]
Thanks for investigating this. Could you create a PR?

**Comment by MirkoCovizzi** [comment]
Sadly, the problem persists if the application terminates unexpectedly (because of exceptions or something else), because it doesn't have occasion to reach into the closing function. We need a way to safely release the semaphore from somewhere else that doesn't depend on the .net api.

**Comment by r0x0r** [comment]
Might the atexit handler be of help?
https://docs.python.org/3/library/atexit.html

**Comment by SebastienWae** [comment]
> Might the atexit handler be of help?
> https://docs.python.org/3/library/atexit.html

Unfortunately, that won't work.
> Note: The functions registered via this module are not called when the program is killed by a signal not handled by Python, when a Python fatal internal error is detected, or when os._exit() is called.

**Comment by abmyii** [comment]
Sorry for butting in, but can the signal be caught?
https://docs.python.org/3/library/signal.html
https://nattster.wordpress.com/2013/06/05/catch-kill-signal-in-python/
https://stackabuse.com/handling-unix-signals-in-python/
https://www.devdungeon.com/content/python-catch-sigint-ctrl-c
https://stackoverflow.com/questions/18499497/how-to-process-sigterm-signal-gracefully

**Comment by abmyii** [comment]
For Windows-specific kill signals:
https://stackoverflow.com/questions/47306805/signal-sigterm-not-received-by-subprocess-on-windows?rq=1
https://stackoverflow.com/questions/35772001/how-to-handle-the-signal-in-python-on-windows-machine
https://danielkaes.wordpress.com/2009/06/04/how-to-catch-kill-events-with-python/

**Comment by r0x0r** [comment]
If somebody wants to give it a go, I will be happy to accept a PR.

>

**Comment by abmyii** [comment]
Unfortunately I cannot, not being a Windows user.

**Comment by bustawin** [comment]
This, or something similar, happens too when in Mac.

If you execute the following and then try to close the window (by clicking on the 'x' or stopping python directly) it just hangs.

```python
import webview

def ev(window):
    window.evaluate_js("""while(true){}""")

window = webview.create_window('')
webview.start(ev, window)
```

The same semaphore is the one hanging (but in the `cocoa.py` file).

**Comment by Ksengine** [comment]
@bustawin which semaphore?
