### ISSUE TITLE
Creating a CEF window and destroying it repeatedly causes memory leak

### ISSUE THREAD

**Issue by darthglowball** [r0x0r/pywebview#434]
### Specification
- pywebview version: latest (installed today)
- platform / version: Windows 7, 32-bit (I'm almost afraid to mention this. Let's see if this is a multi-platform issue before I'll show myself out ;] )
### Description  
 Create a window and destroy it in a loop with window.destroy(). Watch the pythonw.exe process increase memory with every iteration in the task manager.

Code:

```
import webview
import time

def hide_show():
    while True:
        running_script_window = webview.create_window("window", html= "<html><body><svg><rect width='100' height='100' fill='red'/></svg></body></html>", text_select = False, width = 1000, height = 600)
        time.sleep(5)
        running_script_window.destroy()
        time.sleep(5)
webview.create_window("window")
webview.start(hide_show, gui="cef")

```

**Comment by r0x0r** [comment]
Sorry man. I ran your example and memory usage keeps floating around 30mb, no sign of a memory leak. I am afraid this is a CEF build for Windows 7 that is leaking memory.

**Comment by darthglowball** [comment]
@r0x0r okay thanks for testing. I think I can work around this with `window.hide`, `window.show` and `window.load_url` to create the effect as if a new window is created with fresh content. I didn't find a memory leak with this.
