### ISSUE TITLE
Get reason for exception

### ISSUE THREAD

**Issue by RyannnnnnR** [r0x0r/pywebview#435]
### Specification
- pywebview version: 3.1
- platform / version: MacOS 10.15.1

### Description  
  
Is there a way to get the reason of the exception without printing the entire stacktrace when catching errors in the javascript promise?
For example:
```js 
pywebview.api.handle_error.catch(err => console.error(err.reason)) // Will return "Test Exception"
```
```python 
def handle_error:
       raise Exception("Test exception")
```
 
### Practicalities

- YES I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Yes. Definitely possible.
A error format should be decided first though. I would like to preserve an ability to see the stacktrace, but maybe it does not have to be a default option.

**Comment by RyannnnnnR** [comment]
I'm inclined to agree with you on keeping the ability to see the stacktrace. My initial thought was to turn the error into and object.  So something like:
```python
 except Exception as e:
            result = {'reason': str(e), 'stacktrace': json.dumps(traceback.format_exc()).replace('\\', '\\\\').replace('\'', '\\\'')
            code = 'window.pywebview._returnValues["{0}"]["{1}"] = {{isError: true, value: \'{2}\'}}'.format(func_name, value_id, result)
````

But thinking about this a bit more, it probably introduces a regression -- since most people are probably using error.message and I think it might break that syntax.

**Comment by r0x0r** [comment]
Implementation of an error object here 
https://github.com/r0x0r/pywebview/pull/436

I have used Mozilla's version of the Error object (with the `stack` property) as a basis.

**Comment by RyannnnnnR** [comment]
Looks good!  I added one small knit-picky comment.
