### ISSUE TITLE
File open events

### ISSUE THREAD

**Issue by sarimabbas** [r0x0r/pywebview#439]
### Specification
- pywebview version: 3.1
- platform / version: macOS 10.15.1

### Description  
  
Hi, thank you for your work on this project. Is there a way to intercept file open events e.g. when dragging a file to app icon in dock or double-clicking in Finder? Thanks for the help!

**Comment by r0x0r** [comment]
Sorry I don't follow. Do you want to intercept an event when a file is dragged to a pywebview application icon in the Dock?

**Comment by sarimabbas** [comment]
Yes, sorry if my earlier comment was unclear. I want to build a text editor, and get the path to a file (e.g txt file) when it is dragged to the icon. Or alternatively when the file is opened from Finder on macOS. In Electron, this event can be detected (https://electronjs.org/docs/api/app#event-open-file-macos). Can it be possible to do the same here? Thank you!

**Comment by r0x0r** [comment]
I don't see any reason why it could not be done. Feel free to investigate the issue. Here is some info for starters
https://stackoverflow.com/questions/2489961/dropping-files-onto-dock-icon-in-cocoa

**Comment by sarimabbas** [comment]
Thanks! I will read up more on it

**Comment by bustawin** [comment]
The following works when double-clicking a file registered with the app using `info.plist`:
```python
class ApplicationDelegate(AppKit.NSObject):
    def application_openFile_(self, application, fileName):
        print('Passed-in file is ', fileName)
        return Foundation.YES


cocoa.BrowserView.app.setDelegate_(ApplicationDelegate.alloc().init().retain())
```
However it does not work once the app is opened, although it should. [This link](https://stackoverflow.com/questions/19655919/nsapplicationdelegate-applicationopenfile-never-reaches-to-openfile-function) hints what could cause it, but I am too newbie to get it straight :-)
