### ISSUE TITLE
Extended Screens

### ISSUE THREAD

**Issue by peterhoth** [r0x0r/pywebview#44]
I have dual screens on my computer and i would like to have pywebview to run fullscreen on the secondary screen instead of the primary screen. It would be nice if there's option to run full screen on my secondary screen on the right, etc. 
e.g. webview.create_window("Full-screen browser", "http://www.flowrl.com", left=1024, top=0,  fullscreen=True)

**Comment by r0x0r** [comment]
With a myriad of different monitor configurations that would make the implementation complicated and fragile.
A better approach would be be to introduce a toggle_fullscreen function that would switch the window to fullscreen mode on an active screen.  The actual fullscreen button would have to be implemented in GUI.

**Comment by peterhoth** [comment]
I managed to change the codes to cater to my requirement. If you are interested to know, please let me know so that i can send you the modified codes. It may not be that elegant but it does the job for me. Thanks and keep up with the good work with Pywebview.

**Comment by r0x0r** [comment]
Yes, that would be great. Please share it and I will take a look at what I can do.

**Comment by peterhoth** [comment]
How do I share the source codes to you ? I'm sorry as i do not know the procedure to send source codes to the owner for review.

**Comment by r0x0r** [comment]
You can create a pull request, but it requires forking the project and is
slightly complicated. Or just paste the affected code changes to
https://gist.github.com/.

**Comment by peterhoth** [comment]
https://gist.github.com/peterhoth/40a74029edd245651add23f4dcaa7cd8
Please review it. It's a simple fix but gets the job done for me. I hope you can add this as a new feature for your next release. Thanks!

**Comment by r0x0r** [comment]
A problem with this approach, as there is no way to make it a general solution suitable for everyone. It that would require getting a screen configuration and a resolution for each screen. Given that we still do not know anything about a particular monitor configuration. What if a second monitor is a video projector in another room? What if it is turned off? What about three monitors? There are too many unknowns to make it work.

I will go with a toggle_fullscreen() approach that would make a window fullscreen on a currently active screen. Thanks for pointing me to this problem.

**Comment by r0x0r** [comment]
Toggle fullscreen functionality is now implemented in master. When the function is called, the fullscreen window is opened on the same monitor as the application window.
