### ISSUE TITLE
Is it possible to yield python generator function from JS in serverless mode?

### ISSUE THREAD

**Issue by melvinkcx** [r0x0r/pywebview#444]
### Specification
- pywebview version: 3.1
- platform / version: Linux

### Description  
  
Is it possible to yield a Python generator function from JS in serverless mode? 

I'm looking for a solution to stream data from Python back to the UI. I'm using serverless mode, so using WebSocket is unlikely. Correct me if I'm wrong. 

My idea is to yield a Python generator function from JS. Any suggestions are also very much appreciated.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I haven't explored this possibility, but I think it should be doable. It
would fit nicely with a promise on the JS side.

>

**Comment by melvinkcx** [comment]
I played around with it today, this is totally doable, though kinda verbose. Here is a dumb example:

In Python:

```
class JsApi:
    def gen_logs(self, _):
        def gen():
            x = 1
            while True:
                yield x
                x += 1

        if not hasattr(self, 'g'):
            self.g = gen()

        return next(self.g)
```

In JS:

```
async *genLogs() {
    while (true) {
        yield await window.pywebview.api.gen_logs();
    }
}

const g = genLogs();

(await g.next()).value     // 1
(await g.next()).value     // 2
```
