### ISSUE TITLE
cant play m3u8 format video

### ISSUE THREAD

**Issue by pgit363** [r0x0r/pywebview#448]
### Specification
- pywebview version: 3.1
- platform / version: python 3.7

### Description  
  
  iam trying to create a webview of my website which contains m3u8 videos
all webpages loaded properly but cant load videos .
  
### Practicalities

-NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
There is already  a topic covering video issues. Read through it and describe your issue there.  Mentioning operating system would not hurt.
