### ISSUE TITLE
Using window.get_elements() to get html element, but how can I set the html element value ?

### ISSUE THREAD

**Issue by kailotus** [r0x0r/pywebview#449]
### Specification
- pywebview version: 3.1
- platform / version: Windows 8.1

### Description  
Hello :
    I wrote an html file with the following snippet :
![input_field](https://user-images.githubusercontent.com/7297066/71658624-c5bfcf80-2d7f-11ea-83f8-3f55860611fd.png)
    I can get the content of html elements through 
    window.get_elements ("# getName") [0] ["value"], 
    but how can I set and assign a content value to the
    id="getNameg" field? Thank you ~
    wish all the best
-kailotus

**Comment by r0x0r** [comment]
get_elements is read only, but you can use evaluate_js to modify DOM.

**Comment by kailotus** [comment]
Thank you for your reply, I also thought about using the method evaluate_js, 
and I did the following test? But the results puzzle to me ..

**msg = 123**
jsCommand = "document.getElementById('getName').value={ve}".format(ve=str(msg))
window.evaluate_js(jsCommand)

_123 in the field of getName can appear correctly_
But if I use:

**msg = "Mark"**
jsCommand = "document.getElementById('getName').value={ve}".format(ve=msg)
window.evaluate_js(jsCommand)

_Nothing is displayed in the field of getName .._
Could you please explain the problem? Thanks a lot.

**Comment by r0x0r** [comment]
You have to escape the value in quotes.

**Comment by kailotus** [comment]
Thank you very much, the problem has been solved. I rewritten it into the following program snippet and it is correct, thank you
jsCommand = "document.getElementById('getName').value=**_'{ve}'_**".format(ve=msg)
