### ISSUE TITLE
passing settings to cef gui

### ISSUE THREAD

**Issue by francescomeloni** [r0x0r/pywebview#450]
I am using the latest version on windows
and i need to pass this settings on the cef gui because i need to persist preferences and cookies between sessions:
  
        "cache_path": "cache_path/",
        "persist_session_cookies": True,
        "persist_user_preferences": True,
  
any way to do it?
thanks

**Comment by r0x0r** [comment]
Not in a released version, but I just implemented a way to do it. See `examples/cef.py` in the master branch.
Disclaimer: it is not tested yet.

**Comment by francescomeloni** [comment]
thank you! 
I have to wait because i need this for a "pip installation" . 
When i try to insert the lib in my source directly edge and mshtml doesn't work properly.

**Comment by r0x0r** [comment]
I got it working, see the `examples/cef.py` for an example.
