### ISSUE TITLE
pywebview is undefined after reload page

### ISSUE THREAD

**Issue by francescomeloni** [r0x0r/pywebview#451]
### Specification
- pywebview version: 3.1
- platform / version: windows

### Description  
  
i coded a interdomain solution with js_api and it works well. I have an issue when reload the page to give some change settings take effects. the problem is that  i loose pywebview that is undefined. 
how can i "reinsert" pywebview in the dom ? 

thanks
  
F

**Comment by r0x0r** [comment]
window.pywebview should be automatically reinjected on page reload. It is a bug, if it does not.
Please provide more details on how to reintroduce it.

**Comment by francescomeloni** [comment]
i just found that location.href works ...
this daesn't work:    
   location.reload(true);
this does:
    if (!window.location.hash) {
    window.location.href = window.location.href;
} else {
    window.location.reload();
}
i ll try to provide a simple case 
thanks again

**Comment by francescomeloni** [comment]
i just found that location.href works ...
this daesn't work:    
   location.reload(true);
this does:
    if (!window.location.hash) {
    window.location.href = window.location.href;
} else {
    window.location.reload();
}
i ll try to provide a simple case 
thanks again
