### ISSUE TITLE
how to trigger window events ?

### ISSUE THREAD

**Issue by francescomeloni** [r0x0r/pywebview#452]
### Specification
- pywebview version: 3.1
- platform / version: windows

### Description  
  
i studied  all the examples and i like the possibilities like toggle fullscreen, hide, show,  but except to trigger the event using a time.sleep i can't find another  way explained. Using js_api i can execute functions but i can't access to "window" methods.  is there  a "get_main_mindow" somewhere? 
can someone indicate some example?  thanks
F

**Comment by r0x0r** [comment]
What do you want to achieve exactly? Built-in events like shown, loaded, closed, closing are triggered automatically and there are no other events. 

All the window objects are stored in `webview.windows`. The main window object can be accessed as `webview.windows[0]`

**Comment by francescomeloni** [comment]
for example:
i d like to have two buttons in my html page to toggle fullscreen on and off.
i can use js_api to catch the click, execute the python function like in the js_api.py 
it is like to add two buttons ( if possible) in that example not only to generate a random number or greet  back a name but  to toggle  fullscreen window on and off 
thanks

**Comment by r0x0r** [comment]
Call `webview.windows[0].toggle_fullscreen()` in your js_api handler. I believe there is an example of this case in the` todos` app example.

**Comment by francescomeloni** [comment]
it works thanks
