### ISSUE TITLE
Cannot trigger HTML5 <video> tag 'ended' event

### ISSUE THREAD

**Issue by t-walker-wei** [r0x0r/pywebview#453]
### Specification
- pywebview version: 3.1
- platform / version: Raspbian Buster 

### Description  
  
  I had listen to 'ended' event of video and worked fine in chrome/firefox.But not worked in pywebview.Have any idea?

**Comment by r0x0r** [comment]
Have you tested it on Raspberry's built-in browser, ie the one that is used by web renderer? Getting it to work on an unrelated cutting-edge browser is no good.

**Comment by t-walker-wei** [comment]
> Have you tested it on Raspberry's built-in browser, ie the one that is used by web renderer? Getting it to work on an unrelated cutting-edge browser is no good.

I use RPI4, the default browser is chromium,and the 'ended' event works in chromium

**Comment by t-walker-wei** [comment]
I installed [Midori](https://en.wikipedia.org/wiki/Midori_%28web_browser%29), browser base on webkit + GTK, the 'ended' event also not work. The video automatic play in loop even I didn't set **loop** attribute. After I set **loop="false"** to the <video>, still not trigger the 'ended' event.

**Comment by r0x0r** [comment]
You can try installing a more recent version of WebGTK from Debian backports or alternatively QtWebKit.
