### ISSUE TITLE
Messages sent immediately on `pywebviewready` don't arrive

### ISSUE THREAD

**Issue by numirias** [r0x0r/pywebview#455]
### Specification
- pywebview version: 3.1
- platform / version: CPython 3.8.1 on Linux

### Description  
  
I'm sending an API message from JS to Python on `pywebviewready`, but the message isn't received on the Python side.

#### Full reproduction case

```python
import webview

class Api():
    def hello(self, *args):
        print('hello called')
        return 'hello from python'


html = '''
<button onclick="hello()">hello</button>
<script>
    window.addEventListener('pywebviewready', function() {
        hello();
    });
    function hello() {
        pywebview.api.hello().then((...args) => {
            document.body.innerHTML += JSON.stringify(args);
        });
    }
</script>
'''

def main():
    api = Api()
    webview.create_window('test', html=html, js_api=api)
    webview.start(debug=True)
 
if __name__ == '__main__':
    main()
```

#### Expected result
- When the page loads and `pywebview` is ready, `hello()` gets called on the Python side.

#### Actual result
- When the page loads, the `pywebviewready` event is triggered, but the `hello()` call isn't relayed.
- Only when I later manually click the `hello` button, the message is correctly sent to Python and responded to.

**Comment by r0x0r** [comment]
Looks like a timing issue. Adding a setTimeout solves this, but this definitely must be fixed.

By the way, a really nice bug report. Much appreciated.

**Comment by r0x0r** [comment]
I fixed this in master.

**Comment by numirias** [comment]
Thanks, can confirm.
