### ISSUE TITLE
API methods called without arguments from JS do receive single `None` argument

### ISSUE THREAD

**Issue by numirias** [r0x0r/pywebview#456]
### Specification
- pywebview version: 3.1
- platform / version: CPython 3.8.1 on Linux

### Description  
  
The API relay is adding an empty argument even if a method is called without arguments. This currently also breaks examples from the docs.

#### Full reproduction case

```python
import webview

class Api():
    def hello(self):
        print('hello called')

    def hello_with_args(self, *args):
        print('hello with args called, args:', args)


html = '''
<button onclick="pywebview.api.hello()">hello</button>
<button onclick="pywebview.api.hello_with_args()">hello with args</button>
'''

def main():
    api = Api()
    webview.create_window('test', html=html, js_api=api)
    webview.start(debug=True)
 
if __name__ == '__main__':
    main()
```

#### Expected result
- When I click the first button, Python should call `hello()´ without arguments.
- When I click the second button, Python should call `hello_with_args()´ without arguments.

#### Actual result
- When I click the first button, Python raises:
```
Traceback (most recent call last):
  File \"webview/util.py\", line 90, in _call
    result = func(func_params)\nTypeError: hello() takes 1 positional argument but 2 were given
```
- When I click the second button, the API method receives a `None` argument.

#### Solution

When an API method is called without arguments, don't add a single `None` argument.

**Comment by r0x0r** [comment]
I haven't managed to reproduce it with master. The output of both button clicks is.
```
hello called
hello with args called, args: ()
```

Is this with GTK or QT?

**Comment by numirias** [comment]
> Is this with GTK or QT?

Both, the bug occurs with all frontends on master.

A clarification on the bug: The API methods simply always gets arguments as a single argument tuple instead of separate arguments. So, `hello(1, 2, 3)` from JS was called as `hello((1,2,3))` in Python.

**Update:** Now this is awkward. I installed 3.1 via pip instead of the current master. It's fixed on master, I assume via https://github.com/r0x0r/pywebview/commit/4d7c651038be7eddf38e683b316029fd89b63234? Would love to see it working in the PyPI release though! Thanks for your work on this.

**Comment by r0x0r** [comment]
I will release a new version in the near future.
