### ISSUE TITLE
PyInstaller breaks CEF Engine

### ISSUE THREAD

**Issue by TheDemystifier** [r0x0r/pywebview#457]
### Specification
- pywebview version: 3.1
- platform / version: Windows 10 64Bit

### Description  
  
Try packaging this code using pyInstaller :
```python
import webview

webview.create_window('PyWebView', url='https://www.google.com')
webview.start(gui='cef')
```
I ran `pyinstaller -y  "R:/test.py"`.
Running the `.exe` file gives crashes with : 
`[0117/164120.680:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.`

**Comment by r0x0r** [comment]
I believe CEFPython or PyInstaller repos are more appropriate forums for
this issue.

**Comment by TheDemystifier** [comment]
Thanks 👍
