### ISSUE TITLE
Python function not triggered using JS

### ISSUE THREAD

**Issue by aayusharora** [r0x0r/pywebview#458]
### Specification
- pywebview version: 3.1
- platform / version:  MacOS 10.14.6

### Description  
  Like the serverless architecture, the code snippet is unable to trigger the defined python code function _open_file_dialog_ using JS.
**HTML with JS**
 _i.e inside assets folder_

```
<html lang="en" data-framework="javascript">
	<head>
		<meta charset="utf-8">
		<title>Aftershoot</title>
		<link rel="stylesheet" href="styles.css">
	</head>
	<body>
		<section class="logo">
			<img src="logo.jpg" alt="maumaumau">
		</section>
		<section class="todoapp">
			<header class="header">
				<h1>Aftershoot</h1>
				<button class="new-todo" onClick='chooseDir()'>Upload</button>
			</header>
		</section>
		<script>
		function chooseDir() {
			alert('hello')
			pywebview.api.open_file_dialog(window)
		}
		</script>
	</body>
</html>
```
**Python Implementation**
```
import os
import webview


class Api():

    def open_file_dialog(self, window):
        print('Hello')
        result = window.create_file_dialog(webview.FOLDER_DIALOG, directory='')
        return result


if __name__ == '__main__':
    api = Api()
    webview.create_window('Aftershoot', 'assets/index.html', js_api=api, min_size=(600, 450))
    webview.start()


```
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

Reference Docs: https://pywebview.flowrl.com/examples/js_api.html

**Comment by r0x0r** [comment]
Can you run `examples/js_api.py`?

>

**Comment by aayusharora** [comment]
Hi @r0x0r 
The input box does not work.
Only the JS code works, but the JS is unable to execute any python function in `examples/ks_api.py`

**Comment by aayusharora** [comment]
On Inspecting further, this is the error on console
<img width="799" alt="Screenshot 2020-01-23 at 3 13 23 PM" src="https://user-images.githubusercontent.com/12194719/72973264-f8933b80-3df2-11ea-898a-88b004342f9d.png">

**Comment by r0x0r** [comment]
Try the latest master. The issue with fixed arguments was fixed there.

**Comment by aayusharora** [comment]
Can you please elaborate a bit?
The version of pywebview that we are using is 3.1
The code snippet which I tested is the latest one from master:
https://github.com/r0x0r/pywebview/blob/master/examples/js_api.py

**Comment by r0x0r** [comment]
Checkout and install the master branch.  Google for "pip install from git"

>

**Comment by aayusharora** [comment]
Thanks for the quick reply.
Everything works now :)

Closing the issue.
