### ISSUE TITLE
Access port 3000

### ISSUE THREAD

**Issue by Leio99** [r0x0r/pywebview#460]
### Specification
- pywebview version: latest
- platform / version: Windows10 / Python 3.7

### Description  
  
  I created a website with React on my localhost (port 3000), but I am not able to open a window for http://localhost:3000 (or http://127.0.0.1:3000) to access the website. I can only access http://localhost without a specific port. How can I solve that?
  
### Practicalities

- YES/NO I am willing to work on this issue myself. Yes

- YES/NO I am prepared to support this issue financially. No

**Comment by r0x0r** [comment]
Sorry, I have no idea. This sounds like it has nothing to do with
pywebview.
