### ISSUE TITLE
Issue trying use python with HTML

### ISSUE THREAD

**Issue by PxreSmoke** [r0x0r/pywebview#461]
### Specification
- pywebview version:  3.2 
- platform / version: Windows 10 64bit

### Description  

Is there a way I can call a python function from the my GUI html file. 

For example like onclick=“myPythonFunction”

**Comment by r0x0r** [comment]
Yes this is what JS api and expose functions are for. RTFM.

**Comment by PxreSmoke** [comment]
alright I need the docs and now i understand but can i use a external html file?

**Comment by r0x0r** [comment]
You can open html files as as file:// or http:// urls. See todos app for an
example.

**Comment by PxreSmoke** [comment]
ah ok thanks
