### ISSUE TITLE
When icall the javaScript API, did the previously optional parameter su/he become mandatory?

### ISSUE THREAD

**Issue by TakamiChie** [r0x0r/pywebview#462]
### Specification
- pywebview version: 3.2
- platform / version: Windows 10 Home 1909

### Description  
  
I upgraded PyWebView in my project and made an existing program work, and at the point where the JavaScript API was called`Uncaught (in promise) Error: init() Missing 1 required positional argument: The message 'params'` was displayed.
According to the investigation, the parameters at the time of JavaScript API call, which was previously optional, seem to be required.
The sample code has not been corrected for this matter, but has this incident confirmed?
If it does not seem to have been confirmed, please confirm the area of influence.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Which sample code are you referring to?
Parameter to JS API functions are made arbitrary in 3.2, while previously
they always accepted a single param.

>
