### ISSUE TITLE
is it possible to disable x-frame-options support?

### ISSUE THREAD

**Issue by overflow** [r0x0r/pywebview#464]
I need to display a website using iframe inside the webview but I got the error "Refused to display "http:/...." in a frame because it set "X-Frame-IOptions" to "SAMEORIGIN".

**Comment by r0x0r** [comment]
What web renderer/platform are you using?
Without going into details, I suspect there is a setting of each or some web renderer to disable security features.

**Comment by overflow** [comment]
python 3.7.3 GTK

**Comment by r0x0r** [comment]
Not possible from my findings https://bugs.webkit.org/show_bug.cgi?id=130398
Feel free to investigate on your own.
