### ISSUE TITLE
Final assessment grades

### ISSUE THREAD

**Issue by khaludi2** [r0x0r/pywebview#465]
I thought that this error comes in relation to student group with out students. but not. Every mandatory fields are correctly given. the academic Year, the student group and Assesment Group. The report generation tool also gives similar error and the Course wise assessment report does not show any thing.
Please can you work on this. I saw on the Education webnar it is working well and perfect. I am using on Virtualbox and
my Erpnext v11.1.1.38(master) and Frappe framwork: v11.1.35(master)

Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/app.py”, line 61, in application
response = frappe.handler.handle()
File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 21, in handle
data = execute_cmd(cmd)
File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 56, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 1036, in call
return fn(*args, **newargs)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 511, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File “/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py”, line 201, in run
result = generate_report_result(report, filters, user)
File “/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py”, line 76, in generate_report_result
res = frappe.get_attr(method_name)(frappe.dict(filters))
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/education/report/final_assessment_grades/final_assessment_grades.py”, line 35, in execute
scrub_course = frappe.scrub(course)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 812, in scrub
return txt.replace(’ ‘,’’).replace(’-’, ‘_’).lower()
AttributeError: ‘NoneType’ object has no attribute ‘replace’

**Comment by r0x0r** [comment]
I fail to see how this is related to pywebview
