### ISSUE TITLE
Support for webcam in CEF

### ISSUE THREAD

**Issue by ErickAlexander3** [r0x0r/pywebview#467]
### Specification
- pywebview version: 3.2
- platform / version: python 3.7

### Description  
  
Webcam permissions using CEF can be easily enabled by changing the following:

https://github.com/r0x0r/pywebview/blob/1d62b9b5571e0cac7b18706ca592f5dc63ed5836/webview/platforms/cef.py#L218

to:

`cef.Initialize(settings=all_settings, commandLineSwitches={"enable-media-stream": ""})`
  
### Practicalities

- YES, I am willing to work on this issue myself.

**Comment by ErickAlexander3** [comment]
Or maybe allowing to pass commandLineSwitches to CEF (similar to setting the settings dict) would help. That way, many other new features could be tested.

**Comment by r0x0r** [comment]
In my opinion this could be enabled by default, unless there is some security/privacy concern. Opinions?

**Comment by ErickAlexander3** [comment]
Since the application asks for permissions before you use the camera, I do not think there would be security issues. If there are no issues with that, I submitted a PR (#468) with the change in questio
