### ISSUE TITLE
Question about CEF/Pywebview

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#470]
Hi, 

In the current version, embedding CEF with Pywebview, offers advantages over embedding CEF with wxPython? 

I really need to be able to deploy serverless apps, with the main interface in HTML but I need several things like a splash screen and menus and some native windows as well. So, is it better to do it with pywebview, or should I implement CEF with wxPython so that I have access to those missing native features?

Thanks!

**Comment by r0x0r** [comment]
The main advantage of pywebview is that it handles all the boilerplate behind the scenes. With wxPython you will have to write all the glue code yourself. 
pywebview does not support a splash screen or menus. 
Splash screen could be emulated with a frameless window and the app being in another window. I haven’t done it, but it is definitely doable.
Menus could be implemented in JS as well, but I suppose they may feel a bit off comparing to native window.

**Comment by martinlombana** [comment]
And, anyway, if I embed CEF with pywebview (doable as I saw in the docs), using CEF, can I still develop serverless apps and do python calls from the JS code, and vice-versa, right? 

I have developed several apps for clients, based on electron + spawning a local python server process and working with api calls.  But for some simple apps, that might be a bit overkill. 
Thus, I was looking for alternatives. 


PS: Thanks for the great work, the project seems very nice.

**Comment by r0x0r** [comment]
Yes, Python-Javascript is pretty robust, so it should not pose any problems. Would love to hear about your experience.

Note that CEF is currently supported only under Windows. Other platforms use native WebKit implementations.

**Comment by martinlombana** [comment]
For now, I only need it for windows. But I need to have a reliable browser behind, because I would need to support windows 7 and onwards. I like the way that is lightweight, but I am "afraid" of the Internet Explorer browser renderer...
