### ISSUE TITLE
Can't install using pip3 on Linux - Raspbian

### ISSUE THREAD

**Issue by Valkhan** [r0x0r/pywebview#471]
### Specification
- pywebview version: latest
- platform / version: raspbian latest

### Description  
  
Can't install using pip3

packages:
pywebview
pywebview[qt]
pyqtwebengine

```
$ sudo pip3 install -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pywebview (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c6/54/578dfa87c4d8bb6cb2c3618223feb33ebbd0f54b6af53fcd75c2231e9d48/pywebview-3.2-py3-none-any.whl (115kB)
    100% |████████████████████████████████| 122kB 965kB/s 
Collecting pyqtwebengine (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/47/9f/60e630711fd1dd14ef3bd95c86c733c86b8c0853749c7a03691f681f13fd/PyQtWebEngine-5.14.0.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 443kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-rveawdsz/pyqtwebengine/setup.py'
```

  
### Practicalities

- NO I am willing to work on this issue myself. I lack the knowledge required to do so.

- NO I am prepared to support this issue financially. Not at the moment at least

**Comment by r0x0r** [comment]
I don't have a raspbian environment, but have you tried GTK implementation?
Also you may try installing Dependencies using apt as outlined in the
documentation.

**Comment by Valkhan** [comment]
i've tried to follow the installation on linux written in the docs, had to change some package names that are different but i'm not sure exaclty what i did to get it to "work".

Raspbian is an environment with 1gb and 1.4ghz (raspberry pi 3b+), on browser (chrome) my website runs fine, animations runs smooth, but while on webview is outragerous slow.

do you have any clues on what could I do to improove CSS animations (animate.css) rendering?

I'm not yet done testing but once i'm done, i'll try to reproduce the install steps i've taken.

**Comment by r0x0r** [comment]
Do you use GTK or QT implementation?
WebKitGTK that comes with Raspbian is ancient, so upgrading it to a more recent version might help. Look into Raspbian backports. 
If you manage to get it working, consider documentating the process on the installation page.

**Comment by Valkhan** [comment]
as of my understanding, GTK is the default for raspbian, i've tried both, but i'm inclined to say that GTK is the one for raspbian.

I'll begin again from scratch, document every step to help in the documentation and try to get the best from webkit
