### ISSUE TITLE
Why doesn't support URL.createObjectURL?

### ISSUE THREAD

**Issue by korykim** [r0x0r/pywebview#479]
### Specification
- pywebview version: 3.2
- platform / version:  windows 10 pro 64bit

### Description  
  
I want to use `URL.createObjectURL` for file download。But pywebview not support!

This is my js code

```js
function openDownloadDialog(url, saveName)
{
    if(typeof url == 'object' && url instanceof Blob)
    {
        url = URL.createObjectURL(url); // create blob address
    }
    var aLink = document.createElement('a');
    aLink.href = url;
    aLink.download = saveName || ''; 
    var event;
    if(window.MouseEvent) event = new MouseEvent('click');
    else
    {
        event = document.createEvent('MouseEvents');
        event.initMouseEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    }
    aLink.dispatchEvent(event);
}
```
 

  
### Practicalities

- YES  I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
I am not familiar with this API. What is its purpose exactly?

Integrated webviews omit support for certain features for one reason or another. In certain cases, it may be possible to reimplement them manually, in other cases it is completely out of reach.

**Comment by astronouth7303** [comment]
I'm not sure what exactly OP is doing. In my case, I'm trying to stream media, which apparently isn't allowed.

```
  async function next_track() {
    var meta = await pywebview.api.track_open();
    elems.title.innerText = meta.title;
    elems.desc.innerText = meta.desc;

    console.log("Starting to load", meta.title);

    var source = new MediaSource;
    elems.player.src = URL.createObjectURL(source);
    var buffer = source.addSourceBuffer(meta.mimetype);  // <-- Error here

    console.log("Things configured; reading data");

    while (true) {
      resp = await pywebview.api.track_open(4 * 1024);
      console.log("Got chunk")
      if (resp.eof) {
        console.log("Got EOF")
        break;
      }
      data = base64_to_buffer(resp);
      buffer.appendBuffer(data);
    }
  }
```

`[Error] Not allowed to load local resource: blob:null/0e6f4db0-787f-4161-8356-4f6949b1f188`

Under Linux+GTK.

I'm sure this is largely out of your control. It's just frustrating.

**Comment by astronouth7303** [comment]
OH, I think OP is trying to make a link to download a synthesized file.

**Comment by astronouth7303** [comment]
btw, @korykim `data:` URLs might work for your case?

**Comment by astronouth7303** [comment]
Shush, stale bot

**Comment by astronouth7303** [comment]
I think the bot is broken because I commented and it still closed it.

**Comment by astronouth7303** [comment]
this stale bot is worse than the usual stale bot.

**Comment by r0x0r** [comment]
f

**Comment by r0x0r** [comment]
The bot does not react to commenting, only removing the state label seems to help. 

Anyhow, on the topic of the issue itself, I am not going to work on this. If somebody wants to implement this, then by all means. Otherwise, there is no point in keeping this issue open.

Some Javascript functionality can be reimplemented either purely in Javascript or with a mix of Python and Javascript. This way the code is injected into a webpage just after loading. `window.alert()` is implemented this way for example. 

This issue seems like might be solved with giving a webview necessary permissions. This is just a guess. and probably depends on a web renderer as well.
