### ISSUE TITLE
Error: This module requires PyQt4 or PyQt5 to work under Linux.

### ISSUE THREAD

**Issue by danidee10** [r0x0r/pywebview#48]
I was getting an error that 'PyQt5 was not found' and also `This module requires PyQt4 or PyQt5 to work under Linux.` even though it was actually installed on my Linux Machine (Arch Linux), this is due to the fact that QtWebKitWidgets has been deprecated in Qt 5.5 and eventually removed in Qt 5.6 in favour of QtWebEngineWidgets, all this came from an `ImportError` that was raised when QtWebKitWidgets wasn't found in PyQt5. it's likely to affect Arch Linux / Fedora users or other users who run an updated version of Qt5 for some reason (Kde5 maybe)

I've already made a PR to address this
[This commit fixed an issue when trying to import PyQt5 #47 ](https://github.com/r0x0r/pywebview/pull/47)
#47

**Comment by r0x0r** [comment]
Thanks for the PR. Much appreciated :+1:

**Comment by danidee10** [comment]
Uwc :smile:
