### ISSUE TITLE
Serverless Bulk Data transfer?

### ISSUE THREAD

**Issue by astronouth7303** [r0x0r/pywebview#482]
### Specification
- pywebview version: 3.2
- platform / version: Debian, gtk

### Description  
  
Currently, there isn't a good way to stream large data when working serverless.

### Practicalities

- MAYBE I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by astronouth7303** [comment]
Ok, what I'm doing is making a basic audio player and want to stream-load data into an `<audio>` without spinning up a server.

**Comment by r0x0r** [comment]
Do you have any ideas on how large data transfer could be implemented?
There was an issue here where python's yield was used to send data to JS
using async / await. Maybe that could be used for pushing audio?

>

**Comment by astronouth7303** [comment]
Ok, so I finally found something that does the right thing for my application the JS side https://github.com/nickdesaulniers/netfix/tree/gh-pages/demo

My plan is to basically implement the stream API: calls to open, read, seek. My application will only have one stream open at a time, so close is implicit. The trick is that you can't send `bytes` (JSON limitations, i'm guessing?), so it'll need to be base64.

As far as improving the developer experience, I can think of two options:
* Marshaling callbacks, so the python method can call a JS callback as data becomes available
* Allowing generators to be returned, which get transformed into JS async iterators.

**Comment by astronouth7303** [comment]
my current solution is to build a base64'd data URL on the python side, but that can be sluggish.

**Comment by r0x0r** [comment]
If media files are stored locally, could you load them directly using local
URLs?

**Comment by astronouth7303** [comment]
If you're running a server. Pretty sure `about:blank` can't access `file:` URLs.

Hell, I'm not even sure `file:` pages can access `file:` URLs.

**Comment by astronouth7303** [comment]
Shush bot

**Comment by astronouth7303** [comment]
i said SHUSH BOT.
