### ISSUE TITLE
cef hangs while resizing in certain conditions

### ISSUE THREAD

**Issue by MarkusFF** [r0x0r/pywebview#484]
### Specification
- pywebview version: 3.2
- platform / version: Win7 Pro SP1
- cefpython3 version 66.0

### Description  
  
  Observed reproducible hang during use of cef gui, if triggering some kind of update while resizing the window. Minimally this code usually (but not 100% of the time) hangs on my machine:

```python
import webview
window=webview.create_window('Hello world', html='<h1>hello</h1>')
def reload_and_resize():
    window.evaluate_js("location.reload()")
    window.resize(1000, 420)
webview.start(reload_and_resize, gui="cef")
```

or while manually resizing something more like this:

```python
import webview,time
window=webview.create_window('Hello world', html='<h1>hello</h1>')
def keep_reloading():
    while True:
        time.sleep(1)
        window.evaluate_js("location.reload()")
webview.start(keep_reloading, gui="cef")
```

This may be a cefpython issue.

**Comment by MarkusFF** [comment]
Could be this: https://github.com/cztomczak/cefpython/issues/464

**Comment by r0x0r** [comment]
I have reproduced it and it looks like a race condition issue to me. At least adding a debug print statement somewhere in an execution chain seem to eliminate the problem. I will look into it.

**Comment by ikhmyz** [comment]
> I have reproduced it and it looks like a race condition issue to me. At least adding a debug print statement somewhere in an execution chain seem to eliminate the problem. I will look into it.

Is there any news?

**Comment by r0x0r** [comment]
I gave it a try, but did not make any progress. The problem is that as soon as I add any debugging statements, the problem is gone. For example

This hangs
```
import webview
window=webview.create_window('Hello world', html='<h1>hello</h1>')
def reload_and_resize():
    window.evaluate_js("location.reload()")
    window.resize(1000, 420)
webview.start(reload_and_resize, gui="cef")
```

This does not 
```
import webview
window=webview.create_window('Hello world', html='<h1>hello</h1>')
def reload_and_resize():
    window.evaluate_js("location.reload()")
    print('w00t')
    window.resize(1000, 420)
webview.start(reload_and_resize, gui="cef")
```
Similarly adding print statements elsewhere in the CEF code eliminates the problem. Breakpoints set in sub threads are not invoked either. A dumb solution would be add a short sleep noop.

The second example in the original post did not result in hanging on my machine.

**Comment by ikhmyz** [comment]
This problem is fixed in [cefpython ](https://github.com/cztomczak/cefpython/tree/dev)repo in dev branch (I hope so), but I had no luck in building it on Win 10 so I madde changes to `cef.py` here in pywebview

```
#add inner window hwnd to Browser class
class Browser:
    def __init__(self, window, handle, browser):
        ...
        self.inner_hwnd = self.browser.GetWindowHandle()
        ...

# resize through win api
@_cef_call
def resize(width, height, uid):
    instance = instances[uid]
    win32gui.SetWindowPos(instance.inner_hwnd, 0, 0, 0, width-16, height-38, win32con.SWP_NOZORDER | win32con.SWP_NOMOVE | win32con.SWP_NOACTIVATE)
    instance.browser.NotifyMoveOrResizeStarted()
```
`width-16, height-38`  is a temporary solution to not let inner window become bigger than outer and content on the sides not visible

**Comment by r0x0r** [comment]
Have you tested if this fixes the problem?

**Comment by ikhmyz** [comment]
> Have you tested if this fixes the problem?

Not a single hang after this patch, tried to resize window with mouse in different ways for a long time.
Your sample that hangs also not hanging

**Comment by r0x0r** [comment]
Nice one. Would you mind creating a PR?

**Comment by ikhmyz** [comment]
Ok I'll try, but this is temporary solution until cefpython release 66.1 version (after that Browser.SetBounds methid will be available on Win and we should use it)

**Comment by ikhmyz** [comment]
https://github.com/r0x0r/pywebview/pull/504

**Comment by r0x0r** [comment]
@MarkusFF Can you verify if @ikhmyz PR fixes this problem for you?

**Comment by ikhmyz** [comment]
> @MarkusFF Can you verify if @ikhmyz PR fixes this problem for you?

Actual PR contains code using ctypes windll instead of win32gui as you suggested and it still hangs, need to check it and if the problem reproduced check win32gui version then.

**Comment by r0x0r** [comment]
@ikhmyz Would you share an example that results in a hanging? I could not reproduce it with this code
```
import webview
window=webview.create_window('Hello world', html='<h1>hello</h1>')
def reload_and_resize():
    window.evaluate_js("location.reload()")
    window.resize(1000, 420)
webview.start(reload_and_resize, gui="cef")
```

**Comment by MarkusFF** [comment]
I'll try it out.

**Comment by MarkusFF** [comment]
I've checked out and installed ikhmyz:win_cef_resize_hang. I didn't manage to crash either of my minimal examples, nor the app I observed the problem in the first place. Seems like it works!

**Comment by ikhmyz** [comment]
> @ikhmyz Would you share an example that results in a hanging? I could not reproduce it with this code
> 
> ```
> import webview
> window=webview.create_window('Hello world', html='<h1>hello</h1>')
> def reload_and_resize():
>     window.evaluate_js("location.reload()")
>     window.resize(1000, 420)
> webview.start(reload_and_resize, gui="cef")
> ```

Dont have acces to Windows machine right now. It hangs when you resize the window with mouse very fast in random directions, not programatically with `window.resize()`

**Comment by NiceneNerd** [comment]
I'm also having problems with CEF windows hanging if resized with the mouse. Usually it only happens when there is background activity on the Python end. Same on Windows 10 Home and Windows Server 2019.

**Comment by ikhmyz** [comment]
> I'm also having problems with CEF windows hanging if resized with the mouse. Usually it only happens when there is background activity on the Python end. Same on Windows 10 Home and Windows Server 2019.

Maybe it is the reason, I had another thread with socketio running when it happened.

**Comment by ragods** [comment]
url = 'http://localhost'
dsize = ctypes.windll.user32
window = webview.create_window('title', url, js_api=api, fullscreen=True, min_size=(dsize.GetSystemMetrics(0), dsize.GetSystemMetrics(1)))

**Comment by r0x0r** [comment]
The pull request is merged into master. Can this be closed or are there any issues left?

**Comment by MarkusFF** [comment]
Thanks!
