### ISSUE TITLE
Encode problem :: seats in the text - [pt-br] :: CEF :: Windows

### ISSUE THREAD

**Issue by csouza95** [r0x0r/pywebview#487]
Hello guys!

I'm using the pywebview with gui=CEF with Windows
All files from my structure are encoded as UTF-8 included the head of html structure.
Each view of structure has 3 files (.html, .js, .css) and using py scripts I read this files and put the content inside pywebview window using webview.create_window(html)

My problem is it:
I'm brazilian guy and my projects are in portuguese. At try put a seats in the text like ã, é, õ, í, ô, ü, the text are replaced by diferent characteristics and I don`t know why.

Follow the picture of my problem:
![image](https://user-images.githubusercontent.com/60274917/76863223-f3c09600-683d-11ea-93bb-c5e12b312596.png)

On the table below search input, "Cliente", "Projeto", "Nome" are ok!
But on the fourth and fifth columns for write correct are "Revisão" and "Rev. Responsável"

Ty

**Comment by r0x0r** [comment]
Do you have encoding set in your HTML file?
How do you load HTML?

**Comment by csouza95** [comment]
Yes, my html structure has the encode setted as utf-8

`<!DOCTYPE html>
<html>
    <head>
        **<meta charset="utf-8">**
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style>{_bootstrapStyle}</style>
        <style>{_fontAwesomeStyle}</style>
        <script>{_jquery}</script>
        <script>{_bootstrapScript}</script>
        <script>{_fontAwesomeScript}</script>
            
        <style>
            {_style_sheet}
        </style>
    </head>
    <body class="bg-light">
        {_structure}
    </body>
    <script>
        {_script}
    </script>
</html>`

I used the same concept of this example:
https://pywebview.flowrl.com/examples/html_load.html

My HTML, CSS and JS are stored on .html, .css and .js files.
To get the content I using `open(fileName, 'r').read()`.
After load the stardard structure, has a `.format()` to insert the content of my app inside the standard structure.
After it I used this code:
`webview.create_window('i-weldi', fullscreen=False, html=document, js_api=Api(), width=1010, height=600, min_size=(1010, 600))
webview.start(gui='cef', debug=True)`

**Comment by csouza95** [comment]
Roman! What is status of  problem? Can you help me?
I can do any thing to help u?

**Comment by r0x0r** [comment]
Sorry for not getting back to this earlier.  Does `open(fname, "rt", encoding="utf-8")`make any difference? You may also try pasting the html file content into your Python file as a string variable and load via the html param.

**Comment by csouza95** [comment]
Roman!! Thank you so much... it solved my problem..!!
All loads pass on one def of my scripts and at add encoding parameter to it all begins work fine!!

Thanks again for the support
