### ISSUE TITLE
Support for Window Transparency

### ISSUE THREAD

**Issue by nhhollander** [r0x0r/pywebview#488]
It would be nice to have support for background transparency to support use cases such as splash screens, desktop widgets, and allow for greater customization of window appearance.

I did a bit of tinkering and was able to get this working in both Gtk and Qt, and I believe it is possible to extend this functionality to other platforms.  Currently I have support for transparency included as an optional flag in the window constructor, which can be called as `window.create_window("title","url",transparent=True)`

I've pushed my code to https://github.com/nhhollander/pywebview/tree/transparent_windows, and my changes are visible at https://github.com/nhhollander/pywebview/commit/cb939401e742ca9c38386229b6b8c90061b3802e.

I have included a couple examples I made quickly to demonstrate potential use cases.

### Examples
![image](https://user-images.githubusercontent.com/31573882/76928972-5f941480-68b9-11ea-8406-2f4e498f5125.png)

![image](https://user-images.githubusercontent.com/31573882/76929433-83a42580-68ba-11ea-91e9-e818360af4d0.png)
  
### Practicalities

I am willing to work in this issue myself, however I do not have a Windows or Mac OS system to test on at this time.

**Comment by r0x0r** [comment]
Looks good to me. Please go ahead. I will take a look at Windows or macOS whenever I get a chance.

**Comment by r0x0r** [comment]
@nhhollander Would you happen to have samplecode for a transparent window example. Like the one in your screenshots?

**Comment by nhhollander** [comment]
https://gist.github.com/nhhollander/69f15236b6f5c8c9f67d222b196e6dd3

**Comment by r0x0r** [comment]
Implemented Cocoa. As a side-effect transparent window cannot be moved around (as toolbar is hidden as well). Maybe easy drag move should be turned on by default for transparent windows.

**Comment by martinlombana** [comment]
> Implemented Cocoa. As a side-effect transparent window cannot be moved around (as toolbar is hidden as well). Maybe easy drag move should be turned on by default for transparent windows.

I think it should be optional and there should be (if there isn't already) a function to initDrag and StopDrag. That way we could create titlebars in HTML/CSS in order to have a custom design for the whole window, while maintaining the ability to drag it in a "native" way.

What do you think?

**Comment by martinlombana** [comment]
@r0x0r , or is there, maybe, a way to disable the drag in all the window and add it to an specific area already?

**Comment by r0x0r** [comment]
No there is not. Disabling easy_drag would be easy via a param, but adding
a specific drag area is a whole different matter.

**Comment by martinlombana** [comment]
I see.

Then it would be impossible, as of now, to create a 100% custom titlebar,
with dragging capabilities, right?

What would be the changes necessary to do that? (I might look into it to
collaborate for a future PR).
-- 

___________________________________

*Martín Lombana*

*TODOLOGIC.COM <http://TODOLOGIC.COM> | APPS & MORE*

*+34 633 63 02 35  |   *+34 946 759 137

*INSTAGRAM *→* @ <https://instagram.com/todologic>TODOLOGIC
<https://instagram.com/todologic>*

**Comment by martinlombana** [comment]
As a point of reference, Electron does it. Whatsapp Desktop, Slack and Skype are all built using electron. And Visual Studio Code. They do have this feature, because all of their apps have a custom titlebar and are using a framelesss window. Maybe I should create a new _issue_ and reference it here?

**Comment by martinlombana** [comment]
Wouldn't if be doable just with this?
1. Listen to HTML drag event in a specific zone
2. Get the global position of the window
3. Move the window: https://pywebview.flowrl.com/examples/move_window.html

I didn't try it out though.

**Comment by r0x0r** [comment]
This might do a trick. Another way would be to intercept DOM events directly in Python, but I am afraid support for this is renderer specific.

I see two ways to implement this 

a) Add a magic class (.pywebview-drag-area or similar) that would indicate that an element is draggable. I think Electron implements it like this.
b) Add a draggable rectangle to a window constructor (either in pixels or relative units). Seems clunky, but could be implemented natively.

**Comment by r0x0r** [comment]
An update on this. 
macOS is implemented, but I could not get window transparency to work on Windows. Making window background transparent is easy enough, but a transparent webview is a whole different matter. MSHTML seems not to support it at all, EdgeHTML no idea and CEF seems doable, but I could not find a suitable combination of settings to make it transparent. 

I will release this without Windows support for now. I will not explore Windows support any further for now.

**Comment by grintor** [comment]
Window transparency on windows is not hard, but it is temperamental. The problem is that the WS_EX_LAYERED attribute is missing from the window. Once you have that, you can call SetLayeredWindowAttributes and enable LWA_ALPHA and LWA_COLORKEY then you have yourself a transparent window. Here is a fully working example of a pywebview mshtml transparent window, feel free to use this to add support for window transparency officially.

```python
import os, time
import webview
import win32gui, win32process, win32api, win32con # pip install pywin32

os.environ['PYWEBVIEW_GUI'] = 'mshtml'

html = """
    <html>
        <head>
            <style>
                body {
                    background-color: black;
                    -ms-overflow-style: none;
                }
                .dot {
                  height: 250px;
                  width: 250px;
                  background-color: grey;
                  border-radius: 50%;
                  text-align: center;
                  vertical-align: middle;
                  display: table-cell;
                }
            </style>
        </head>
        <body>
            <div class="dot"><font face="Arial" color="red"><b>My Transparent Window<b></font></div>
        </body>
    </html>
"""

def get_hwnds_for_pid(pid):
    hwnds = []
    def callback (hwnd, hwnds):
        if win32gui.IsWindowVisible (hwnd) and win32gui.IsWindowEnabled (hwnd):
            found_tid, found_pid = win32process.GetWindowThreadProcessId(hwnd)
            if found_pid == pid:
                hwnds.append (hwnd)
        return True
    win32gui.EnumWindows (callback, hwnds)
    return hwnds

def on_loaded():
    time.sleep(0.1) # win32gui.SetWindowLong can hang without this sometimes for some reason
    hwnd = get_hwnds_for_pid(os.getpid())[0]
    win32gui.SetWindowLong(hwnd, win32con.GWL_EXSTYLE, win32gui.GetWindowLong(hwnd, win32con.GWL_EXSTYLE ) | win32con.WS_EX_LAYERED )
    win32gui.SetLayeredWindowAttributes(hwnd, win32api.RGB(0,0,0), 200, win32con.LWA_ALPHA | win32con.LWA_COLORKEY)
    window.restore()

if __name__ == '__main__':
    window = webview.create_window('My Transparent Window', html=html, frameless=True, on_top=True, minimized=True)
    window.loaded += on_loaded
    webview.start()
```

**Comment by ItsCubeTime** [comment]
I would also like to see window, transparency, in my case I just want to add a slight fillet to the window edges.

```py
windowObj.frameless = True
windowObj.transparent = True
```
seems to make it impossible to interact with the html content in the widow (I can see it, but click & hover events goes to whatever window is below)?

**Comment by Xavlight** [comment]
I confirm, this is the problem under the Windows environment.
Otherwise it would be great, just what I'm looking for.

@grintor had found an alternative solution, but it doesn't work anymore with version 4.01.
And moreover, it worked in gui=mshtml (IE11), which is not the best.

other ideas?

Thanks

Xav

**Comment by r0x0r** [comment]
This is a bug in WebView2. See https://github.com/MicrosoftEdge/WebView2Feedback/issues/1004 for details.

**Comment by Xavlight** [comment]
It's a shame about that.

Forced to make buttons without transparency, which take up the entire 200x100 mini area.
It's a pity that you can't reduce the size of the webview as you wish.

**Comment by blazgocompany** [comment]
Working on Win11? I see my theme color as background rather than a transparent background.
