### ISSUE TITLE
Installation via pip fails on Linux under Python 3

### ISSUE THREAD

**Issue by mivade** [r0x0r/pywebview#49]
The version of PyGObject on PyPI is extremely old (last upload was 2011) and fails to install under Python 3 due to a syntax error. This makes pywebview unusable in a virtualenv (unless using the `--system-site-packages` option) or when using something like Anaconda rather than the system Python. Possible solutions:

* Switch to Qt as the default on Linux since PyQt4/5 are installable via pip (possibly just for Python 3)
* Don't explicitly require `pygobject` in `setup.py` but instead add installation instructions that note needing to use the system package for Linux

**Comment by r0x0r** [comment]
Thanks for reporting this.
I think the best course would be to get rid of installation dependencies. I will implement it in the next version.

**Comment by r0x0r** [comment]
Just released version 1.2 that does not have installation dependencies for Linux or Windows
