### ISSUE TITLE
Javascript Events not Triggering on All Machines

### ISSUE THREAD

**Issue by jcomish** [r0x0r/pywebview#490]
### Specification
- pywebview version: pywebview==3.2
- platform / version: Windows 10

### Description  
  
My team is working on a project using pywebview. We have recently run into an issue where javascript and jquery events only trigger on some people's machines. They run successfully on everyone's browsers. We have tried using the javascript onclick event in the element itself as well as the jquery below.
Is there a particular version of chromedriver that must be used?
Any other ideas why this might not work?

Here is the event that is not triggering:
$(".option").click(function(){
    alert("got here");
});
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry, I have no clue based no this information.
Are you using CEF? If so, CEFPython https://github.com/cztomczak/cefpython <https://github.com/cztomczak/cefpython> might be a better place to ask.

**Comment by jcomish** [comment]
Sorry, maybe I am misunderstanding how pywebview works... I thought that it opens up a chromium browser and navigates to the page where your server is running. Does it work a different way?

**Comment by r0x0r** [comment]
Pywebview embeds a webview component in a native window (in your case a WinForms window). For Windows webview can be EdgeHTML (default for modern Windows 10 installations), MSHTML (default for older Windows) or CEF (requires cefpython and must be started with gui=‘cef’ parameter).

**Comment by jcomish** [comment]
Installing CEF and updating window.start with that parameter worked. Thank you for your timely support!
