### ISSUE TITLE
Does pywebview support kivy implementation? Is it possible to open a pywebview file inside kivy, without creating a new window?

### ISSUE THREAD

**Issue by iulianastroia** [r0x0r/pywebview#492]
### Specification
- pywebview version: 
- platform / version: 

### Description  
  
  Describe your issue
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Short answer is no.
Longer answer is that I have been planning Android support, which would be implemented via Kivy. So the Kivy support will arrive in some form or another at some point.
