### ISSUE TITLE
window.load_html() :: CEF

### ISSUE THREAD

**Issue by csouza95** [r0x0r/pywebview#494]
hey guys!!
I hope all is well!!

I need a help to solve a problem with gui=cef

The flow:
1. At click on green button the code load another html file using LOAD_HTML()
2. On the next view has a grey button and it back to first view with same code

The problem:
- Using CEF, are necessary click two times on button to load_html() works fine

Follow this example working good:
![WhatsApp-Video-2020-04-03-at-19 00 35](https://user-images.githubusercontent.com/60274917/78408669-1abced00-75de-11ea-9d31-43f3f7def6e8.gif)

Now this example working not good:
![WhatsApp-Video-2020-04-03-at-19 01 05](https://user-images.githubusercontent.com/60274917/78408673-1bee1a00-75de-11ea-9b36-a05928ce5462.gif)

The difference between the good example and the other is the code to start the webview, that use or not **gui=cef**
> webview.start(http_server=False, **gui='cef'**, debug=True).

Thanks!!

**Comment by r0x0r** [comment]
Could you post an isolated barebones example that would demonstrate this problem?

**Comment by csouza95** [comment]
Roman thaks again for the fast response!

Isn't complicade. 
All loads good and works fine!
But inside my code has many views transitions that read and load another views with another contents from another files using load_html() function.

On first transition havent problems, but on the nexts loads are necessary two time to change the view, that is, at click on button it beggins the load but return the same view... at click again it works fine and load the required view. And all transitions after this point require this second click

On my script has the webview.start() that gui parameter are setted as 'cef'
Trying solve my problem I removed to test the gui parameter and all runs without problems.

The questions is why with CEF the loads required a second time to load the requested view

**Comment by r0x0r** [comment]
@csouza95 Timing and synchronicity problems are tricky to investigate. Your best bet to get help is to post a barebones example that demonstrate the problem.

**Comment by csouza95** [comment]
@ r0x0r 
I understand now !! You need the _**barebones**_ of my project or a similar example with it!
but what's the barebones?? sorry I can't translate it to my language !!

I hope all is well!

**Comment by r0x0r** [comment]
A minimal example with just enough code (no more) to get the problem reproduced.

**Comment by csouza95** [comment]
app.py
This my main/root file! The app beggins here!
```
import sys
import os
import webview
import json

import subprocess
import uuid

class Api():
    def __init__(self):
        self.view_module = None
        self.cancel_heavy_stuff_flag = False

    def set_ViewModule(self, ViewModuleName):
        self.view_module = global_functions.get_views(ViewModuleName)

    def get_ViewModule(self):
        return self.view_module

    def set_View(self, viewName, layout= None, params= None):
        self.set_ViewModule(viewName)

        if layout == None:
            new_html= self.get_ViewModule().get_content(params= params)
        else:
            new_html= self.get_ViewModule().get_content(layout= layout, params= params)

        window.load_html(new_html)

    def jsToPy(self, functionName, params = None):
        func = getattr(self.view_module.functions, functionName)
        
        if params == None:
            func(window)
        else:
            func(window, params)

    def quit(self):
        window.destroy()

if __name__ == '__main__':
    jsApi = Api()

    if not iKey_check():
        jsApi.set_ViewModule('view_keygen')
    else:
        jsApi.set_ViewModule('view_iFiles')

    window= webview.create_window('i-weldi', fullscreen=False, html=jsApi.get_ViewModule().get_content(), js_api=jsApi, width=1210, height=700, min_size=(1210, 700))
    webview.start(http_server=False, gui='cef')
```

structure.html
This my button that I call the function on JS.
```
<button class="btn btn-success ml-2" id="btn-new-iFile"><i class="fas fa-plus"></i></button>
```

scripts.js
This are used inside the html content to call the views changes from api() class
```
window.addEventListener('pywebviewready', function() {
    $("#btn-new-iFile").on({
        click : function(){
            setTimeout(function(){
                pywebview.api.set_View("view_iFiles", "create");
            },500)
        }
    });

    $("#btn-new-analyses").on({
        click : function(){
            var iFile= $(this).attr('data-ref');
            pywebview.api.set_View("view_reports", "index", iFile);
        }
    })
})
```

My scripts load bootstrap, jquery, and fontawesome.

**Comment by idatabiCarlosSouza** [comment]
@r0x0r, any one solucition to it?

**Comment by r0x0r** [comment]
I haven't looked at it sorry. The example you provided is not standalone and has references to other code. Could you provide a completely isolated example?
