### ISSUE TITLE
py2app example: bindings not installed

### ISSUE THREAD

**Issue by AlexanderWillner** [r0x0r/pywebview#496]
### Specification
- pywebview version: master
- platform / version: macOS 10.14.6 (18G4032) / Python 3.7.7

### Description  

Executing the [py2app example](https://github.com/r0x0r/pywebview/blob/master/examples/py2app_setup.py) throws the following error: `webview.util.WebViewException: You must have either PyObjC (for Cocoa support) or Qt with Python bindings installed in order to use pywebview.`. 

The specific steps to reproduce under the platform mentioned above:
  
```
$ git clone https://github.com/r0x0r/pywebview.git
$ cd pywebview/examples/
$ python3 py2app_setup.py py2app
$ ./dist/simple_browser.app/Contents/MacOS/simple_browser 
```

Already tried to convince py2app to include `pyobjc`, however, with no success so far.
  
### Practicalities

- YES I am willing to work on this issue myself (however, couldn't find a solution yet)

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry for a late response. I just spent some time fixing this issue and it came to not having pyobjc and pywebview having installed for the Python interpreter I was using. Pay attention to the "Modules not found (unconditional imports):" section of the py2app output.

**Comment by AlexanderWillner** [comment]
Not sure I understood your comment correctly. I‘ve suggested a fix that works for me in a fork.
