### ISSUE TITLE
Add support for custom user-agents

### ISSUE THREAD

**Issue by tognee** [r0x0r/pywebview#498]
### Description  
For the app I'm working on I need to open a new window and load a site with a specific user-agent and right now that's not possible.
I added support for it in gtk (as it's what I'm using now). (#499)

### Practicalities
I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
Some implementation links

WinForms / MSHTML https://stackoverflow.com/questions/937573/changing-the-user-agent-of-the-webbrowser-control
WinForms / EdgeHTML https://www.pedrolamas.com/2017/03/21/setting-a-custom-user-agent-in-the-uwp-webview-control/ (seems tricky)
CEF: https://github.com/cztomczak/cefpython/blob/master/docs/Tutorial.md#change-user-agent-string

QT: https://doc.qt.io/qt-5/qwebengineprofile.html#setHttpUserAgent

Cocoa: https://stackoverflow.com/questions/28109668/osx-10-10-wkwebview-set-useragent-swift

**Comment by tognee** [comment]
gtk, qt, cocoa, cef and mshtml are now implemented in my pull request and tested.

The only one left is EdgeHTML and as you said it seems tricky. I don't think I can implement that one by myself as I'm not that fluent with c#

**Comment by r0x0r** [comment]
@tognee I have implemented a global user agent via `start(user_agent='')`. The settings approach is there too, it can be used as a way to set a user agent individually per window (would not work in CEF though). PR is here if you want to take a look https://github.com/r0x0r/pywebview/pull/509

**Comment by tognee** [comment]
Looks fine to me!
I think it can be merged without any problems.

Should I wait for the merge before closing this issue?
