### ISSUE TITLE
pyinstaller linux freezing big size > 230mb/gtk , 415mb/qt on todos example

### ISSUE THREAD

**Issue by YacoubBelaoura** [r0x0r/pywebview#501]
### Specification
- pywebview version: 3.2
- platform / version: Linux 5.4.23-1-MANJARO / python 3.8.2

### Description  
  the 'onefile' option on pyinstaller on the example  `todos` is really big 262mb/gtk
  Describe your issue
 how to reproduce :
on the 'todos' example folder
```sh
$ pipenv install pywebview pyinstaller pygobject
$ pipenv graph
PyGObject==3.36.0
  - pycairo [required: >=1.11.1, installed: 1.19.1]
PyInstaller==3.6
  - altgraph [required: Any, installed: 0.17]
  - setuptools [required: Any, installed: 46.1.3]
pywebview==3.2
$ pipenv shell
$ pyinstaller --onefile --add-data="assets/*:assets" start.py
$ du -sh dist/start
263M    dist/start
```
if i remove `pygobject` the size will be 9mb but it will not work, and complain about missing gtk or qt.
i don't know why it not looking on the system like when using python script

and i used docker container but got the same result.
thanks in advance
  
### Practicalities

- [x] I am willing to work on this issue myself.

- [ ] I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry, I have no experience in freezing under Linux. Maybe somebody else here can help.
Besides it is an issue with Pyinstaller not pywebview, so asking there might help.

**Comment by YacoubBelaoura** [comment]
ok, thank
i will try to ask on pyinstaller, and i think the only problem is with pyinstaller hook for pywebview.
i will close this for now and if i get it working i will comment it here for reference.
