### ISSUE TITLE
Source code view

### ISSUE THREAD

**Issue by rgvillanueva28** [r0x0r/pywebview#507]
### Specification
- pywebview version: 3.2
- platform / version:  Python 3.7

### Description  
  
  Is there any way to enable the inspect element on the pywebview or any way how to see the source code of my html since it is generated with javascript? I'm creating a serverless app and I use cef as the GUI.

  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You can use debug mode to open web inspector. Web inspector is available on all platforms except MSHTML. EdgeHTML requires an external tool. See documentation for info.

**Comment by rgvillanueva28** [comment]
I made it work. I just didn't try to right-click the page since I was trying before and nothing shows up. I just have to set Debug=True. Thank You!

**Comment by fastlaner** [comment]
This is awesome.
