### ISSUE TITLE
Incompatibility With FormBorderStyle Enum & Python Keyword

### ISSUE THREAD

**Issue by zachee** [r0x0r/pywebview#51]
So I'm testing out pywebview for possible inclusion to a project I'm working on. One of the appeals is its OS agnosticism. I'm trying out the http_server.py example module and I'm getting an exception thrown in winforms.py;Line 48.

```
C:\...>python webtest.py
Traceback (most recent call last):
  File "webtest.py", line 33, in <module>
    webview.create_window("My first HTML5 application", "http://127.0.0.1:23948")
  File "C:\Python35\lib\site-packages\webview\__init__.py", line 159, in create_window_initialize_imports()
  File "C:\Python35\lib\site-packages\webview\__init__.py", line 73, in _initialize_imports
    import webview.winforms as gui
  File "C:\Python35\lib\site-packages\webview\winforms.py", line 48
    self.FormBorderStyle = WinForms.FormBorderStyle.None
                                                                                      ^
SyntaxError: invalid syntax
```

What seems to be the problem is that the FormBorderStyle enumeration value of "None" is causing errors because that's also a python keyword. I ran a little test in IDLE to further investigate this. 

```
>>> import clr
>>> import System.Windows.Forms as WinForms
>>> test = WinForms.FormBorderStyle
>>> test.None
SyntaxError: invalid syntax
>>> test.Fixed3D
2
>>> test.FixedDialog
3
>>> test.FixedSingle
1
>>> test.FixedToolWindow
5
>>> test.Sizable
4
>>> test.SizableToolWindow
6
```

Let me know if I'm missing something.

-Zach

**Comment by zachee** [comment]
Forgot to mention my system.

Python: Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Windows: Windows 7 Enterprise, SP1, 64-bit
.NET Framework: 4.6.1
pip list:
astroid (1.4.8)
colorama (0.3.7)
comtypes (1.1.2)
isort (4.2.5)
lazy-object-proxy (1.2.2)
mccabe (0.5.2)
nose (1.3.7)
pip (8.1.2)
pylint (1.6.4)
pyserial (3.1.1)
pythonnet (2.1.0)
pywebview (1.2.1)
pywin32 (219)
setuptools (20.10.1)
six (1.10.0)
wrapt (1.10.8)

**Comment by r0x0r** [comment]
It seems like None keyword in this context is disallowed in Python 3. I have pushed a workaround into the master, seems to do the job. Please tell me if it solves the problem for you.

**Comment by zachee** [comment]
Yep, hard coding the enum seems to work fine.
