### ISSUE TITLE
Silently fails after save file dialog in cocoa

### ISSUE THREAD

**Issue by bustawin** [r0x0r/pywebview#510]
### Specification
- pywebview version: 3.2
- platform / version: python 3.8.2 / macOS

### Description  
Performing the [Save file dialog](https://pywebview.flowrl.com/examples/save_file_dialog.html) example using cocoa nothing happens after writing the name of the file to save.

This is because [the following line](https://github.com/r0x0r/pywebview/blob/b24211f2b494b6e34c1892b9253fddc556c50f54/webview/platforms/cocoa.py#L545) fails silently:
```python
file = save_dlg.filenames()
```

If this is changed by
```python
self._file_name = save_dlg.filename()
```

Then in works. It would be interesting to not allow these errors to fail silently too :-)

**Comment by r0x0r** [comment]
Could you create a PR?

**Comment by bustawin** [comment]
Yes, I can do one. Do you have any related test that I could use as a base / modify?

**Comment by r0x0r** [comment]
There are no tests for file dialogs. They are tricky to test as they require user interaction.
