### ISSUE TITLE
Unnecessarily broad pyobjc dependencies on macOS

### ISSUE THREAD

**Issue by ulope** [r0x0r/pywebview#511]
### Specification
- pywebview version: 3.2
- platform / version: macOS (N/A)

### Description  

For macOS `pyobjc` is listed as a dependency: 
https://github.com/r0x0r/pywebview/blob/b24211f2b494b6e34c1892b9253fddc556c50f54/setup.py#L13

That is a meta-package that depends on all available pyobjc sub-packages.
This leads to a lot of packages being installed and installation taking a long time.

As far as I can tell from the code in reality only the following are needed:
- `pyobjc-core`
- `pyobjc-framework-Cocoa`
- `pyobjc-framework-WebKit`

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a good call. Would importing those three libraries be enough? Could you test and create a PR? Frozen binary shall be tested as well.

**Comment by ulope** [comment]
It’s not stale.
Man I dislike those bots...

**Comment by ulope** [comment]
Still not stale

**Comment by r0x0r** [comment]
Let's try another stale bot.

**Comment by ulope** [comment]
Not stale

**Comment by ulope** [comment]
not stale

**Comment by ulope** [comment]
Still not stale

**Comment by Fizzadar** [comment]
Have PR'd a fix for this (https://github.com/r0x0r/pywebview/pull/655).

**Comment by ulope** [comment]
Awesome. Just changing the install requirements is a much easier solution that I had in mind.
