### ISSUE TITLE
GTK crashes if given x/y

### ISSUE THREAD

**Issue by astronouth7303** [r0x0r/pywebview#515]
### Specification
- pywebview version: master
- platform / version: gtk

### Description  
  
Working on #513, found a crash in code I didn't touch.

```
🐚 python move_window.py
Segmentation fault (core dumped)
```  

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by astronouth7303** [comment]
Might be related:

```
🐚 python resize.py
Segmentation fault (core dumped)
```

**Comment by r0x0r** [comment]
Again could not reproduce this with PyGObject 3.20.

**Comment by r0x0r** [comment]
Fixed on master
