### ISSUE TITLE
Running pywebview in seperate thread

### ISSUE THREAD

**Issue by niklaskeerl** [r0x0r/pywebview#517]
### Specification
- pywebview version: 3.2
- platform / version: Arch Linux Python 3.8.2

### Description  
  
First of all, I want to thank you all for putting so much time in this project.

My question is: Why do you try to prevent users from running pywebview in a seperate thread?

I ask this, as I try to implement a webview in a code editor which loads plugins in the PYTHONPATH environment variable and calls a function there in its main thread as seen [here](https://github.com/thonny/thonny/wiki/Plugins). Calling your webview start method results in blocking the code editor, making it unusable. So I tried running pywebview in a seperate thread. Calling the start method of pywebview resulted in this exception: https://github.com/r0x0r/pywebview/blob/master/webview/__init__.py#L75-L76

I changed the new threads name to "MainThread" and then it worked (in QT). I could use both GUIs at the same time. The only weird issue I observed was that if I closed the webview there would still be two processes remaining.

![processes](https://user-images.githubusercontent.com/33728607/81806904-6cca2a00-951d-11ea-8062-56c31249a935.png)

Also, when I tried to create another thread for the pywebview everything would crash and I received the following error (again QT):

```shell
QObject::startTimer: Timers can only be used with threads started with QThread
```

Using GTK, it did not work at all and I received the follong error:

```shell
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

Only, when I used multiprocessing it worked but this would result in blocking the code editor again.

I read the information about the threading model on your website (https://pywebview.flowrl.com/guide/usage.html#threading-model) but this doesn't answer my question.

I would be very thankful if you could provide some information on the decision to try to prevent people from running this in a seperate thread.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This is a constraint by underlying GUI frameworks, that is the GUI must be run on a main thread. All the GUI frameworks used by pywebview have same requirement. I am not familiar with any ways to circumvent this (as in your QT example), but that sounds hacky to me. I would say multiprocessing is a way to go in your case. I started working on a multiprocessing support some time ago, but it had been put on hold.

**Comment by niklaskeerl** [comment]
Thank you for the quick answer again :)

The issue is that the code editor uses tk as its GUI and I wanted that those two GUIs were able to communicate with each other. Seeing it working with qt had me wondering. I will try multiprocessing then.

**Comment by r0x0r** [comment]
Some reading on this subject
https://stackoverflow.com/questions/32437130/why-ui-operation-must-be-performed-on-main-thread-in-android
