### ISSUE TITLE
Flask issues with pywebview

### ISSUE THREAD

**Issue by juanfcocontreras** [r0x0r/pywebview#518]
### Specification
- pywebview version: 3.2
- platform / version: OS X Catalina 10.15.4

### Description  
  
I'm trying to work with Flask and Pywebview from the example of the repository. My goal is to change views through Flask, not through links on the page itself. For example, when an event happens, redirect to another view or render another template.

However, I have the problem that `flask.redirect` method doesn't work within Pywebview. I have also noticed that when I have made a `flask.render_template` call, the following `flask.render_template` calls don't seem to have any effect either.

Am I doing something wrong or is there a limitation to this?
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Sorry no idea why it does not work. As far as I understand Flask generates a redirect http code, which should be understood by web renderer. Could you turn on debug mode and see if web inspector produces anything useful?

**Comment by juanfcocontreras** [comment]
If a turn on flask debug mode, I have the following error:

```
ValueError: signal only works in main thread
```

My goal is to get this issue working:

https://github.com/r0x0r/pywebview/issues/362

In this webview go port they say it is possible at native level:

https://github.com/zserge/webview/issues/151

Nevertheless, I'm trying to get it working by javascript (like it is mentioned here https://github.com/Boscop/web-view/issues/80).

So my project is using flask-dropzone (https://github.com/greyli/flask-dropzone). When you drag and drop a file to the dropzone, it is copied to a temporal folder and then render a new template. where I can use this file (I have the full path of the copied file).

This last action doesn't seem to be working:

```
        f = request.files.get("file")
        filepath = os.path.join(server.config["UPLOADED_PATH"], f.filename)
        f.save(filepath)
        return render_template("table.html", token=server_token, data=filepath)  # <-- this is not working
```

I attach you the project, so you can test yourself.

[flask_app_drop.zip](https://github.com/r0x0r/pywebview/files/4678732/flask_app_drop.zip)

Thank you very much!

**Comment by juanfcocontreras** [comment]
I think it was my mistake. I didn't quite figure out how the `flask-dropzone` package worked and assumed that the redirect problem was from `pywebview`.

I'm very sorry for the confusion, I would just like to clarify how to debug with `flask` and `pywebview`, because as I said in the previous message, I get the following error when I activate the debug with Flask:

```
ValueError: signal only works in main thread
```
