### ISSUE TITLE
js_api functions cant return data

### ISSUE THREAD

**Issue by mrh1997** [r0x0r/pywebview#519]
### Specification
- pywebview version: 3.2
- platform / version: Windows 10 Pro 1909

### Description  
  
  The return value of python functions provided via js_api parameter is not visible from a
  calling javascript function. The resulting value is either {} (on when using edge) or {'__NPO__': 1} (whing using mshtml). I get the same result when using the expose() function instead of the js_api parameter.

```python
import webview

class Api:
    def pyfunc(self):
        return "TESTSTR"

def call_pyfunc(window):
    # will print {} or {'__NPO__': 1} instead of TESTSTR:
    print(window.evaluate_js("pywebview.api.pyfunc()"))

if __name__ == "__main__":
    api = Api()
    window = webview.create_window(
        "JS Expose Example",
        html="<html><head></head><body><h1>JS Expost</body></html>",
        js_api=api,
    )

    def x():
        return "teststr"

    webview.start(call_pyfunc, window, gui="mshtml")
``` 
  
### Practicalities

- I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
JS API functions return a promise not a value. See `examples\js_api.py`

**Comment by mrh1997** [comment]
Ah didn't see that.
Thanks!

Maybe you could add a small note at the API doc (https://pywebview.flowrl.com/guide/api.html) about the promise.

**Comment by r0x0r** [comment]
Feel free to contribute to the documentation by submitting a PR.
