### ISSUE TITLE
Edge WebView2 support

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#521]
Windows Forms support for Chromium based WebView2 has finally arrived.  Implementing this for pywebview should be doable at this point.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

**Comment by kvnxiao** [comment]
Any chance of this being done any time soon?

**Comment by r0x0r** [comment]
@kvnxiao I am not working on this actively at the moment, not sure when I have time and energy to devote to this issue. 

However, if you want to see this implemented fast, consider sponsoring this issue.

**Comment by kvnxiao** [comment]
Suppose if I have time to contribute to this, what exactly is required to get WebView2 up and running together?

**Comment by r0x0r** [comment]
1) WebView2 implementation is to be done in the same manner as EdgeHTML, ie no changes would be needed to made to window logic. WebView2 component would be attached as a child to the form.

2) WebView2 detection logic is needed (checking for .NET and Window 10 versions ), as it is done with Edge https://github.com/r0x0r/pywebview/blob/746fd6a16fb678d4d63b4fe8cd61476154f5516d/webview/platforms/winforms.py#L68

3) `winforms.py` will require a refactor at some point, as it is already too large for a single file. In practice that would be mean splitting renderer code to separate files.

4) `renderer` value for WebView2 can be `chromium`

5) EdgeHTML is buggy af, not sure if WebView2 is any better. In any case, one should prepare for all kinds of quirks and funky solutions.

**Comment by kvnxiao** [comment]
WebView2 uses Chromium so it should not be buggy in any way; it would be as buggy as using chromium on other platforms.

**Comment by dmwyatt** [comment]
@kvnxiao Are you going to work on this?

**Comment by kvnxiao** [comment]
@dmwyatt I don't think I have the time to contribute on this one, but just simply wanted to ask for a clear roadmap in case someone else would like to work on it.

**Comment by tshemeng** [comment]
[Announcing Microsoft Edge WebView2 General Availability](https://blogs.windows.com/msedgedev/2020/10/19/edge-webview2-general-availability/)

**Comment by Ksengine** [comment]
https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2WindowsFormsBrowser

**?**

**Comment by Ksengine** [comment]
[webview2 latest](https://github.com/r0x0r/pywebview/files/5493612/zip.zip)
dlls

**Comment by Ksengine** [comment]
users should install webview2 runtime
we can programatically install it
get a link from https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by sbbosco** [comment]
I have created a working first draft with Edge Webview2 support.
The modified files and notes are here https://github.com/sbbosco/pywebview 

I am new to Github, so let be known if a break any protocols.
Thanks

**Comment by tshemeng** [comment]
@sbbosco I tested on Windows10 20H2, it works well, maybe you can send PR to this repo.

**Comment by martinlombana** [comment]
> I have created a working first draft with Edge Webview2 support.
> The modified files and notes are here https://github.com/sbbosco/pywebview
> 
> I am new to Github, so let me know if I break any protocols.
> Thanks

Hi!, Just out of curiosity. With this approach, could we ship the DLLS with the app when freezing it with pyinstaller, so that we can use that webview, but if the final user does not have it, it can still work?

Thanks!

**Comment by tshemeng** [comment]
Edge 87 stable will release end of 2020 which includes webview2, soon user don't need to install webview2 runtime or Edge insider version.

**Comment by sbbosco** [comment]
@tshemeng I'm glad you were able to successfully test the webview2 changes. I am new to Github and I may need some guidance on how to submit a PR.  I may also want to wait for a blessing from @r0x0r. I my intention was always to directly contribute to this repo.

**Comment by sbbosco** [comment]
@martinlombana There are 2 separate requirements.

- The 3 SDK DLLs that I image would be included in a future release of pywebview.
- The Webview2 Runtime or supported Edge browser.

If you distributed a frozen program, you would probably need to check if the **runtime** is installed and programmatically install a runtime if it is not present.

Hopefully the comment from @tshemeng about Edge 87 will  save us from this extra requirement in most cases.

Here's a link about app distribution https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by tshemeng** [comment]
@sbbosco Sorry I check webview2 docs again, it does not say Edge 87 contains webview2.
I decide emmbed a webview2 runtime web installer in my exe.

**Comment by r0x0r** [comment]
@sbbosco Good work. Please create a PR.

I was hoping to refactor the whole winforms.py for better handling of different renderers. With four different renderers it is becoming unruly. Alas I don't have a Windows development machine at the moment. 
If anyone has got ideas for a better architecture, please share your thoughts here.

**Comment by sbbosco** [comment]
@r0x0r Please take a look here and let me know if this is what you had in mind for refactoring. Any suggestions are welcome.

https://github.com/sbbosco/pywebview/tree/edge-webview2/webview/platforms

**Comment by r0x0r** [comment]
@sbbosco yes, this would do for now. `chromium.py` can have a more descriptive name to indicate that it is not cross-platform, maybe `edgechromium.py`

**Comment by sbbosco** [comment]
@r0x0r Thanks. I will create a PR after the **noblock**  changes are stable.

**Comment by r0x0r** [comment]
@sbbosco The noblock might take a while, as there is no solution in sight. So no need to wait for it.

**Comment by r0x0r** [comment]
Chromium support merged into master. Many thanks to @sbbosco for the outstanding work.

I have updated documentation here https://github.com/r0x0r/pywebview/blob/master/docs/guide/renderer.md

Feel free to test this and report your findings. I will release a new pywebview version next week or so.

**Comment by Ksengine** [comment]
I need a help for **noblock** 
Can anyone find a method to do multiprocessing using `spawn` method on frozen apps

**Comment by sbbosco** [comment]
@r0x0r You may want to consider updating the `edgehtml` evaluate_js function similar to the `chromium` method.

I have an app that works well with `cef` and `chromium`, but has lots of errors when using `edgehtml`. After updating the code, `edgehtml` also runs without errors.

[winforms.py](https://github.com/sbbosco/pywebview/commit/9c124e7c7c95b5d2377bc9edb8a545f7c177c18f)
[edgehtml.py](https://github.com/sbbosco/pywebview/commit/70597e6e63ace10bad4794ad5f62d366c73e9d49)

**Comment by r0x0r** [comment]
@sbbosco Could you create a PR?

**Comment by martinlombana** [comment]
Hi, 

Any idea on how to package the DLLs with pywebview, and froze it with pyinstaller in an standalone/controlled manner? Has anyone done that?
@sbbosco, @r0x0r 

Thanks!

**Comment by r0x0r** [comment]
You can specify a data dir that would be embedded with the exe in pyinstaller

**Comment by martinlombana** [comment]
@r0x0r , thanks. But how do I instruct pywebview to load the runtime from that exact folder?
That is my doubt :)

**Comment by r0x0r** [comment]
You can use pyinstaller's `sys._MEIPASS` to obtain the current directory of the executable. You may look at pywebview's code for example usages of this variable.

**Comment by martinlombana** [comment]
Thanks, 

I can't seem to be able to locate the example that you are referring to, in order to set the executable to be used by Pywebview. Could you point me to it? Thanks in advance.

**Comment by r0x0r** [comment]
@martinlombana Check  this https://github.com/r0x0r/pywebview/blob/c2d3435430f11c46723e1db7f75b440e7c6f993f/webview/util.py#L44
