### ISSUE TITLE
Script doesn't end when using multiple CEF windows

### ISSUE THREAD

**Issue by NiceneNerd** [r0x0r/pywebview#524]
### Specification
- pywebview version: 3.2
- platform / version: Windows 10 Home 18363

### Description  
  
If I try to use multiple windows with CEF, the Python process never terminates after both have been closed.
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
Yes
- YES/NO I am prepared to support this issue financially.
Perhaps

**Comment by r0x0r** [comment]
https://github.com/r0x0r/pywebview/issues/433
This might be related

**Comment by r0x0r** [comment]
Cannot reproduce with `examples/multiple_windows.py`

**Comment by NiceneNerd** [comment]
Hmm, seems to have gone away after reinstalling Windows for other reasons. Weird.
