### ISSUE TITLE
Qt failing to find debug port

### ISSUE THREAD

**Issue by NiceneNerd** [r0x0r/pywebview#526]
### Specification
- pywebview version: 3.2
- platform / version: Manjaro Linux 64-bit, using Qt

### Description  
  
When using the Qt renderer with debugging enabled, actually opening developer tools and then closing the app causes the next run to hang on a very long loop of searching for a port. It runs through several thousand ports and then crashes. The only way to get the app running again is to wait some time roughly between 30 to 90 seconds.
 
### Practicalities

- YES/NO I am willing to work on this issue myself.
Yes
- YES/NO I am prepared to support this issue financially.
No

**Comment by r0x0r** [comment]
Fixed in master
