### ISSUE TITLE
window methods do not work in 'loaded' event

### ISSUE THREAD

**Issue by bvukotic** [r0x0r/pywebview#528]
### Specification
- pywebview version: 3.2
- platform / version: Windows 10

### Description  
 
My code is:
def on_loaded():
&nbsp;&nbsp;&nbsp;&nbsp;    print("loaded....")
&nbsp;&nbsp;&nbsp;&nbsp;    print(webview.windows[0].get_current_url())

window = webview.create_window('MyApp', "http://127.0.0.1:8000/")
window.loaded += on_loaded
webview.start()

Problem is in
webview.windows[0].get_current_url()
it does not execute. It does not raise exception, it is just stuck there and nothing happens, method 'on_loaded' does not continue. Actually this also happens when I try to call:

webview.windows[0].evaluate_js('... some my javascript....')

I tried to use 'window' instead of webview.windows[0] but result is the same

**Comment by r0x0r** [comment]
There were at least two issues.
a) callbacks were executed before the loaded event was set
b) callbacks were executed on the same thread, which resulted in hanging at least on macOS. 

I have opened a PR. There might be side-effects of the logic change, so testing on different platforms and with different events is much appreciated.

**Comment by bvukotic** [comment]
I tried it on windows 10, didn't have any problems!

Great job!
