### ISSUE TITLE
Pyinstaller works without further action -> Update docs?

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#532]
### Specification
PyInstaller==3.6
pywebview==3.2

### Description  
  
In the docs (https://pywebview.flowrl.com/guide/freezing.html) you state that, in order to use pyinstaller, we shall add manually 2 dlls when freezing with it. But I just tried and it is not necessary, it seems, with latest versions:

**Comment by r0x0r** [comment]
Yes, the pywebview hook has been incorporated into 3.6. Could you update the docs?

**Comment by martinlombana** [comment]
Will do. I really want to start contributing to this project. ;).

One question: What system do you use to generate the docs online from the .md files automatically? I am curious.

**Comment by r0x0r** [comment]
It is Vuepress. 
You update documentation by submitting a PR to the docs branch. Once merged it is automatically deployed to the website. Each page has an Update documentation link at the bottom of the page.

**Comment by martinlombana** [comment]
Humm. I just saw your message. I created a pull request https://github.com/r0x0r/pywebview/pull/533
But I guess I didn't check it against the docs branch. sorry.
