### ISSUE TITLE
OS Overlay autocomplete on input text

### ISSUE THREAD

**Issue by psytron** [r0x0r/pywebview#535]
### Specification
- pywebview version: pywebview 3.2    
- platform / version: Mac OSX Catalina, Mac OSX Mojave

### Description  
 When typing into input text fields, pywebview on Mac OS overlays floating auto-completion boxes which interfere with UI and capture keyboard inputs. Is there a way to disable this behavior and make it function just like WebKit/Safari/Chrome? 

Example screenshots: 

Expected Behavior: 
Safari/Webkit:  UI Element works as dropdown:
![desiredx2](https://user-images.githubusercontent.com/7834453/83324564-5edb0f80-a266-11ea-8e01-16f2091d3670.png)

Unexpected Behavior: 
PyWebView: Overlays autocomplete bubbles, captures keyboard inputs and blocks UI interactivity:
![undesiredx](https://user-images.githubusercontent.com/7834453/83324478-c9d81680-a265-11ea-9182-f833702f04a9.png)

**Comment by r0x0r** [comment]
I believe this behaviour can be disabled by adding  `spellcheck="false"` on your input field.

**Comment by psytron** [comment]
Yes! That works :) Thanks @r0x0r
