### ISSUE TITLE
CEF option for OSX + Linux

### ISSUE THREAD

**Issue by psytron** [r0x0r/pywebview#536]
### Specification
- pywebview version: 3.2
- platform / version:  Mac OSX Catalina

### Description  
pywebview has a brilliant interface and very intuitive API specification. The option to enable CEF rendering on Windows is great, and for people rendering 3D WebGL the performance appears to be significantly faster in CEF.  Comparing rendering speed of CEF to default WebKit shows Frame Rate of 40FPS in webkit compared to 60FPS on CEFPython.  Any plans to enable CEF on OSX and Linux ?

**Comment by r0x0r** [comment]
Support for CEF on other platforms has been in the backlog, but no progress has been made. Here is the original ticket
https://github.com/r0x0r/pywebview/issues/15

Lately I have been busy with another project, so chances to see support soon are low. If you want to see it implemented, the choices are either
1) do it yourself or
2) sponsor this issue
