### ISSUE TITLE
Question about renderer

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#537]
If we don't specify anything, windows will render with IE, in whatever version the system has, right?
When does it render with edgeHTML? Because in the docs:
https://pywebview.flowrl.com/guide/renderer.html#gtk-webkit2

There is no "code" for edgeHTML. Does it choose it itself it it's available? (Due to the problems that are described in that section, I prefer not to use edgeHTML). That is why I am asking.

Thanks,

**Comment by r0x0r** [comment]
EdgeHTML is used by default if available. EdgeHTML requires at least .NET Framework 4.6.2 and Windows 10 build 17110. 
MSHTML is available in all cases. To force MSHTML use `gui=mshtml`

**Comment by martinlombana** [comment]
Ok. Then, in the described problems:

Destroying a window via window.close() and starting a new instance will
crash the program.
-> How should we close the window, if not with window.close() ? sys.exit(),
to avoid this problem?

Running the program under elevated privileges will throw an exception.
-> Is there any way to avoid this when using edgeHTML?

Thanks,

**Comment by r0x0r** [comment]
It is `window.destroy()` not close. As for the second matter, it is a bug in EdgeHTML webview. I would not hold my breathe for Microsoft fixing it to be honest.
On a positive side, Chromium based Webview2 has arrived, so eventually EdgeHTML will be phased out. Here is the ticket for Webview2: https://github.com/r0x0r/pywebview/issues/521

**Comment by martinlombana** [comment]
okey. So the docs are wrong. They state: window.close().
