### ISSUE TITLE
[GTK] Cash on multiple window open/clos

### ISSUE THREAD

**Issue by Fizzadar** [r0x0r/pywebview#543]
### Specification
- pywebview version: 3.2
- platform / version: GTK/Ubuntu 18+20

### Description  
  
Application crashing when opening/closing a window over and over or in a short timeframe:

```py
import webview

html = '<button onClick="pywebview.api.cycleWindows()">Click me!</button>'

WINDOWS = {}

class Api:
    def cycleWindows(self):
        other_window = WINDOWS.get('other')
        if other_window:
            other_window.destroy()

        # sleep(1)
        # WINDOWS['main'].evaluate_js('window.location.reload();')
        other = webview.create_window('windowyes', html='<h1>window</h1>', x=0, y=0)
        WINDOWS['other'] = other

if __name__ == '__main__':
    api = Api()
    window = webview.create_window('API example', html=html, js_api=api)
    WINDOWS['main'] = window
    webview.start()
```
 
This works fine on Mac/Cocoa, but pressing the button repeatedly when using GTK/Linux causes a segfault almost immediately. If you enable the 1s sleep before reloading the problem goes away. Am going to continue investigating this!

### Practicalities

- YES I am willing to work on this issue myself.
- NO I am prepared to support this issue financially.

**Comment by Ksengine** [comment]
web dont want to fix it

**Comment by r0x0r** [comment]
@Fizzadar  
I could not reproduce it with the latest pygojbect on Ubuntu 20.04.1

**Comment by Fizzadar** [comment]
@r0x0r thank you for checking - also cannot reproduce on the latest versions/Ubuntu20 👍
