### ISSUE TITLE
Blocking alt + tab 

### ISSUE THREAD

**Issue by jersobh** [r0x0r/pywebview#546]
### Specification
- pywebview version:  3.2
- platform / version: Linux

### Description  
  
   Hi there
First of all, awesome tool. I'm trying to avoid or catch if the user to leave the window once it's opened, is it possible? I've tried all events with no luck.

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Not currently possible.
Are you trying to implement a kiosk mode?

**Comment by HackerIndustrial** [comment]
You might be able to catch and override the key combination with some javascript on the web app.

**Comment by jersobh** [comment]
Yes, the idea is to have a kiosk mode. I'm using electron right now, but I'd really like to use this one.

**Comment by koolkunz** [comment]
> Not currently possible. Are you trying to implement a kiosk mode?

is kiosk mode now possible with pywebview?

**Comment by r0x0r** [comment]
No
