### ISSUE TITLE
Flask_app example does not run using pip install of pywebview 3.2

### ISSUE THREAD

**Issue by arnoldn1** [r0x0r/pywebview#547]
### Specification
- pywebview version: pip version 3.2
- platform / version: MacOS 10.14.6

### Description  
  
Example for flask-based app does not work using pip install of pywebview (3.2).
using `server` in `window = webview.create_window('My first pywebview application', server)` returns `TypeError: argument of type 'Flask' is not iterable`

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Are you using 3.2 from pip? If so, the new http server that supports WSGI apps is not part of that release. I merged the http server to the master some days ago and it is not released yet.

**Comment by arnoldn1** [comment]
Ah yes, that is likely to be the case. If it is, should there not be a note about this somewhere on the main website? It does specifically say to install through pip under the getting started, with links directly below the “hello world” for examples.

**Comment by r0x0r** [comment]
Good point. The link o the flask app on the website leads to the master branch, while it would be more logical if it pointed to the docs branch.

**Comment by arnoldn1** [comment]
Just to confirm, installing from master does fix the issue.

**Comment by r0x0r** [comment]
I updated the docs

**Comment by lehanest95** [comment]
> Just to confirm, installing from master does fix the issue.

Can u please give instruction on how to install it from master? I'm pretty new to Python, and something like "git clone" didn't work, neither official docs solve the issue.

**Comment by r0x0r** [comment]
https://www.startpage.com/do/dsearch?query=pip+install+from+git&cat=web&pl=opensearch&language=english <https://www.startpage.com/do/dsearch?query=pip+install+from+git&cat=web&pl=opensearch&language=english>

**Comment by lehanest95** [comment]
> https://www.startpage.com/do/dsearch?query=pip+install+from+git&cat=web&pl=opensearch&language=english <https://www.startpage.com/do/dsearch?query=pip+install+from+git&cat=web&pl=opensearch&language=english>

Thanks!!! It worked!!!
`python -m pip install git+https://github.com/r0x0r/pywebview
`
