### ISSUE TITLE
Event for window being ready

### ISSUE THREAD

**Issue by danpalmer** [r0x0r/pywebview#549]
### Specification
- pywebview version: all
- platform / version: macOS 10.15

### Description  
  
The current lifecycle of a window is roughly...

1. Create window
2. Event loop starts
3. Simultaneously:
   - Start callback function is called
   - Window backing view/environment is created
4. URL is loaded
5. First event, `loaded` is fired.

I'm attempting to inject some custom configuration (cookies, see #548) directly into the `WKWebView` backing a window, but there isn't a convenient hook to do this when the webview has been instantiated. My current solution is to wait for 1 second in the init function.

I can work around this, but it seems like it would be nice to have another event for this more advanced use-case.
  
### Practicalities

No and No. This isn't blocking me so I'm afraid I can't dedicate time to solving it.

**Comment by r0x0r** [comment]
Does `window.shown` work for you?

**Comment by danpalmer** [comment]
It doesn't appear to. The window appears to be shown as soon as it's created.

**Comment by r0x0r** [comment]
`shown` is implemented as a mixed bag. In some cases it is fired in the constructor after everything else, in other cases on a dedicated event. The best course would be to fire shown after a webview is ready.
Would this help your use case?
