### ISSUE TITLE
Using function of pywebview is strange.

### ISSUE THREAD

**Issue by ryan3216** [r0x0r/pywebview#550]
### Specification
- pywebview version: 
  3.2
- platform / version: 
  cef3-66
### Description  

Hi sir,
I feel that Using function of pywebview is strange.  I just want to call a function of pywebview sometimes, not on the beginning.  Can you help me?

### The demo code as follow:

import webview
import time
def save_file_dialog(window):
    time.sleep(5)
    result = window.create_file_dialog(webview.SAVE_DIALOG, directory='/', save_filename='test.file')
    print(result)
if __name__ == '__main__':
    window = webview.create_window('Save file dialog', 'https://pywebview.flowrl.com/hello')
    webview.start()
    save_file_dialog(window)

**Comment by r0x0r** [comment]
https://pywebview.flowrl.com/examples/save_file_dialog.html

>

**Comment by ryan3216** [comment]
You know the offical demo must use webview.start() to call create_file_dialog(),  Can I call create_file_dialog() independent;

**Comment by r0x0r** [comment]
No.

**Comment by ryan3216** [comment]
Sir, Thank you for your reply.   I want to use javascript to call create_file_dialog(),  Would you please help me ?
