### ISSUE TITLE
Corners not rounded on macOS webview

### ISSUE THREAD

**Issue by jj0e** [r0x0r/pywebview#551]
### Specification
- pywebview version: Latest
- platform / version: macOS Catalina 

### Description  
  
This is extremely minor however I'm curious to see if it can be fixed. I noticed on macOS that when you launch a web view it's not rounded on the corners like other macOS apps are. I've attached a screenshot [here](https://imgur.com/a/2wHS6EU) to show what I mean.

Again, it's very minor but is this able to be fixed?
  
### Practicalities

- YES I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Cannot reproduce with the latest Catalina and simple_browser.py

<img width="898" alt="Screenshot 2020-06-22 at 13 57 59" src="https://user-images.githubusercontent.com/1549657/85280351-a6813f80-b490-11ea-98d3-81dde5358092.png">

**Comment by atcbackdoor** [comment]
I've tried without dark mode and it seems to work fine as you screen shotted. Are you able to replicate with dark mode bar? @r0x0r

**Comment by r0x0r** [comment]
No luck reproducing it with the dark mode as well 

![image](https://user-images.githubusercontent.com/1549657/85933902-d000f780-b8e4-11ea-8711-dcff2ce00547.png)
