### ISSUE TITLE
Asking admin password

### ISSUE THREAD

**Issue by qaniere** [r0x0r/pywebview#552]
### Specification
- pywebview version: 3.2
- platform / version:  Windows 10

### Description  
  
Before the webview appear, it's asking the admin password, even if http_server = false

**Comment by r0x0r** [comment]
Are you loading html? EdgeHTML does not support loading HTML natively, so http server must be used to mimic html load

**Comment by qaniere** [comment]
I try the following code :
`import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
webview.start()`

And "Appcontainer network isolation diagnostic tool" still asking for the admin password.

**Comment by r0x0r** [comment]
True. Localhost code is invoked no matter what URL is loaded. This should be fixed.
On a positive side this setting needs to be set only once. So if you accept it, it won’t show the admin password dialog again.

**Comment by r0x0r** [comment]
I pushed a fix to the master. Would you mind giving it a test?

**Comment by qaniere** [comment]
Yes of course, the fix is already on PyPi or I have to do some other manipulations to test it ?

**Comment by r0x0r** [comment]
Google for "pip install from git” to install master on your computer.

**Comment by qaniere** [comment]
No problem, I will do it quickly :)

**Comment by qaniere** [comment]
Sorry for the delay. The fix it's working has I expected it, thank you very much !
