### ISSUE TITLE
how should I invoke create_window from js?

### ISSUE THREAD

**Issue by Voyageson** [r0x0r/pywebview#553]
### Specification
- pywebview version: 3.2
- platform / version: windows 10

### Description  
class Api:
- def creat():
    - webview.create_window(
        title='new',
        url='./index.html',
    )
    return True
  
but failed to create a new window

### error

-   File "D:\python37\lib\site-packages\webview\http_server.py", line 72, in start_server
    - base_path = os.path.dirname(url.replace('file://', ''))

AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by r0x0r** [comment]
Could you check if the version from master solves this issue?

**Comment by Voyageson** [comment]
thanks a lot
issue is solved with master
