### ISSUE TITLE
window should show favicon

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#555]
## window should show icon.
 you can find favicon of website and add it to webview window.
can i help you?

**Comment by r0x0r** [comment]
You can add a window icon via a freezer like pyinstaller or py2app/py2exe.
Adding an icon directly with pywebview is not supported. This feature has been request before, so if you feel like implementing it, go ahead. It is not trivial though with cross-platform support (a common image format should be decided for one).

**Comment by Ksengine** [comment]
we can use favicon of website as icon using two methods.

1. favicon is placed on main folder of server(favicon for www.google.com is www.google.com/favicon.ico)
2. favicon is placed on head tag of html source.

**webview should handle various image formats.(specially png and ico)**

**Comment by Ksengine** [comment]
I had found method for qt. i'll add it

**Comment by Ksengine** [comment]
I had found harder ways for qt,gtk and winforms
qt is working
gtk is working
winforms is not working
