### ISSUE TITLE
Css?

### ISSUE THREAD

**Issue by httpproxx** [r0x0r/pywebview#558]
### Specification
- pywebview version: 
- platform / version: 

### Description  
 I cannot get the css and images stored in local files to load. Also I was using a SpeechHandler with an onclick. Will that change anything?
  Describe your issue
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Describing your problem in more details would help.

**Comment by httpproxx** [comment]
I can’t get the css working ;/.
