### ISSUE TITLE
App crashes when using CEF renderer

### ISSUE THREAD

**Issue by tognee** [r0x0r/pywebview#559]
### Specification
- pywebview version: 3.3 (installed from PyPi)
- platform / version: Windows 10 v2004 using CEF renderer

### Description  
App crashes when using the cef renderer

## Steps to reproduce:
- Copy the sample code from the readme
- add `gui="cef"` to `webview.start`
- launch the app and see it crashing

The error that is shown is this:
![image](https://user-images.githubusercontent.com/18465347/86156230-ea65eb80-bb05-11ea-9ebf-a3fe05dea428.png)

pywebview version is 3.3 and cefpython3 version is 66.0

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
AppVeyor showed green, even though every single test was failing. 

Anyhow it is fixed and 3.3.1 is released now.

**Comment by tognee** [comment]
Also released on PyPi, closing
