### ISSUE TITLE
Not working in virtualenvwrapper

### ISSUE THREAD

**Issue by jwallden** [r0x0r/pywebview#57]
Hello!

When I run pywebview inside a virtualenv everthing seems to work fine. However, recently i started using virtualenvwrapper instead and suddenly I get this:

`WARNING:webview.gtk:PyGObject is not found
Traceback (most recent call last):
  File "/home/joakim/.virtualenvs/tradebuddy/lib/python3.5/site-packages/webview/gtk.py", line 15, in <module>
    from gi.repository import Gtk as gtk
ImportError: No module named 'gi'
INFO:webview:Using GTK
Traceback (most recent call last):
  File "web-view-gui.py", line 6, in <module>
    webview.create_window("Simple browser", "http://localhost:3000", width=1200, height=800, resizable=True)
  File "/home/joakim/.virtualenvs/tradebuddy/lib/python3.5/site-packages/webview/__init__.py", line 160, in create_window
    gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscreen, min_size, _webview_ready)
  File "/home/joakim/.virtualenvs/tradebuddy/lib/python3.5/site-packages/webview/gtk.py", line 127, in create_window
    browser = BrowserView(title, url, width, height, resizable, fullscreen, min_size, webview_ready)
  File "/home/joakim/.virtualenvs/tradebuddy/lib/python3.5/site-packages/webview/gtk.py", line 34, in __init__
    Gdk.threads_init()
NameError: name 'Gdk' is not defined
`
I can not for my life understand why there whould be a difference. But there is...
I'm on Arch using Python 3.5.2, python-gopbject 3.22.0-1 and pywebview 1.2.2

**Comment by r0x0r** [comment]
I am not familiar with virtualenvwrapper, but have you tried installing PyGObject separately for the environment you had created/

**Comment by jwallden** [comment]
I'm on Arch and have the python-gobject package installed which seems to be used in the virtualenv. However, I tried installing pygobject from PyPi, in my environment created with virtualenvwrapper and got the following error:

Collecting pygobject
  Using cached pygobject-2.28.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-be56p__6/pygobject/setup.py", line 272
        raise SystemExit, 'ERROR: Nothing to do, gio could not be found and is essential.'
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-be56p__6/pygobject/

**Comment by r0x0r** [comment]
This discussion seems to address the situation you have described.
http://stackoverflow.com/questions/31324430/installing-pygobject-via-pip-in-virtualenv

**Comment by jwallden** [comment]
One of the comments in the link talked about vext.gi. I installed that in the virtual environment (made with virtualenvwrapper) and now it works! So, very pleased with that. I still don't understand why it didn't work in the first place, but that's something for another day :)

Thanks!
