### ISSUE TITLE
window.evaluate_js() always executed in main window

### ISSUE THREAD

**Issue by jokil123** [r0x0r/pywebview#572]
### Specification
- pywebview version: 3.3.1
- platform / version: Windows 10 Pro 10.0.19041

### Description  
  
window.evaluate_js() will only execute in the main window if two windows have the same JavaScript function.
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
No
- YES/NO I am prepared to support this issue financially.
No

**Comment by r0x0r** [comment]
Do you have an example?
