### ISSUE TITLE
onQuit like events?

### ISSUE THREAD

**Issue by rakibtg** [r0x0r/pywebview#58]
Hi, THANKS for such module.

Is there any event like when a user close the window the event will trigger? I have a bottle server running so what i wanted to do is when the user close the app the server will be destroyed on closing the app.

**Comment by r0x0r** [comment]
create_window blocks until the window is closed. You can put the code that kills the server after calling close_window. Or alternatively lunch a thread that runs bottle as a daemon and it will be killed automatically when the main thread exits.
