### ISSUE TITLE
Override Content Security Policy

### ISSUE THREAD

**Issue by corbindavenport** [r0x0r/pywebview#581]
### Specification
- pywebview version: 3.3.1
- platform / version: Ubuntu (Pop_OS) 20.04

### Description  
  
  I'm trying to write a basic app for Linux that displays Twitter in a webview and injects code to better integrate with the host OS (detect dark theme, change the font, and so on). Pywebview is working great, except I don't see a way to override [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) directives, which means injected JS code isn't running.

Here's my code:

```
#!/usr/bin/env python
import webview

def inject_code(window):
    jsCode = open('content.js', 'r').read()
    # content.js just has alert("hello") as a test
    window.evaluate_js(jsCode)
    css_code = 'body { background: red !important; }'
    window.load_css(css_code)

# Start the window
mainWindow = webview.create_window(
    title='Twitter',
    url='https://mobile.twitter.com',
    width=800,
    height=600,
    resizable=True
)
webview.start(inject_code, mainWindow, gui='gtk')
pass
```
When I run it, the injected CSS code runs, but not the JS code. I get this error in the terminal:
```
js: Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.twimg.com   https://www.google-analytics.com https://twitter.com https://app.link  'nonce-NjNiNmE0ZjItZGE4YS00NWUyLTk2MjctMTBlYzBiYmI4OTg4'".
```

Is there a way to override this that I didn't see in the docs, or maybe just a general-purpose method of changing HTTP headers?
  
### Practicalities

- NO I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I dunno.
Is this any of help? https://webkit.org/blog/6830/a-refined-content-security-policy/

**Comment by corbindavenport** [comment]
There's nothing there about disabling CSP, sadly. Maybe that's something Apple/WebKit would have to implement on their end first.
