### ISSUE TITLE
Opening multiple windows in GTK is unstable

### ISSUE THREAD

**Issue by tognee** [r0x0r/pywebview#586]
### Specification
- pywebview version: 3.3.3
- platform / version: Manjaro Linux (GNOME)

### Description  
  Making an app open a new window after a button press sometimes makes the app crash with a `Aborted (Core Dumped)` message.  
I'm using pywebview with a flask server. In the webpage I've added a button to send a message to the server to open the window.  
Opening and closing the window three times makes the app crash. Sometimes it crashes on closing the first window.

Tested the same thing on Windows with CEF and it works as intended.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by tognee** [comment]
Made a gist to easily reproduce the issue
[gist](https://gist.github.com/tognee/b229b6ebf53094c5825f6f2b2eb61b25)

**Comment by r0x0r** [comment]
Debugging GTK segmentation faults is tricky. My best guess is that it has something to do with how GTK threads are (mis-)used. Maybe someone with more GTK knowledge could chime in.

QT implementation should be more stable.

**Comment by lavchandaria** [comment]
Has this issue been solved?

**Comment by r0x0r** [comment]
@lavchandaria 
I have investigated a similar issue [here](https://github.com/r0x0r/pywebview/issues/543) and could not reproduce it with the latest Ubuntu. My best guess is that the issue is caused by outdated GTK depenencies.

**Comment by lavchandaria** [comment]
@r0x0r okay. I will look into that, thanks for the reply.
