### ISSUE TITLE
[Feature Request] Add option to open a window in incognito mode

### ISSUE THREAD

**Issue by tognee** [r0x0r/pywebview#587]
### Description  
Add a parameter to `webview.create_window()` to create the window as an incognito one (So it doesn't save cache/cookies)

- In GTK you can use `webkit.WebView(is_ephemeral=True)`  
[Documentation](https://lazka.github.io/pgi-docs/#WebKit2-4.0/classes/WebContext.html#WebKit2.WebContext.new_ephemeral)  
- In CEF you need to use `CefRequestContext` to separate the context of the windows, then you need to set the settings to `persist_session_cookies` to False and `cache_path` to None
- On macOS you need to set `nonPersistentDataStore` for `WKWebsiteDataStore` for `WKWebviewConfiguration` for `WKWebView`  
[Documentation](https://developer.apple.com/documentation/webkit/wkwebsitedatastore/1532934-nonpersistent)

I haven't checked for other platforms yet.

**Comment by r0x0r** [comment]
Duplicate of https://github.com/r0x0r/pywebview/issues/531
This is in the pipeline, but I am not working on it actively. Feel free to contribute.

**Comment by tognee** [comment]
Sorry, searched incognito and didn't find anything

Closing as duplicate
