### ISSUE TITLE
pywebview vs Eel

### ISSUE THREAD

**Issue by TensorTom** [r0x0r/pywebview#588]
What are the differences and similarities between pywebview and Eel?

**Comment by r0x0r** [comment]
I have no experience with Eel and I learned about it only half a year ago. As I can see the main difference is that
 Eel uses either Chrome App mode or Node / Electron for rendering, while pywebview relies on bundled web renderers (or optional CEF). Both approaches have their pros and cons. Most notable advantage for a built-in web renderer is a small executable size. On the other hand built-in web renderers tend to lag in terms of supporting web standards, so cutting edge technologies are out of question with pywebview.

Also From what I understand Google is phasing out Chrome app mode in the near future, so this approach will render all the existing apps useless.
