### ISSUE TITLE
white space appear at left and bottom of window after minimize and restore.

### ISSUE THREAD

**Issue by plasticanne** [r0x0r/pywebview#589]
### Specification
- pywebview version: 3.3.3
- platform / version:  win10 
- cefpython3 version 66.0
### Description  
With   set  frameless=True or fullscreen=True.  
Once  window.minimize()  and then restore window by click windows taskbar,  a white space appear at left and bottom of window about 16px and 38px. 
I believe this problem is related to the fix of #484 .

**Comment by plasticanne** [comment]
At webview.platforms.cef.Browser

> def resize(self, width, height):
>         webview.platforms.cef.windll.user32.SetWindowPos(self.inner_hwnd, 0, 0, 0, width - 16, height - 38,
>                                    0x0002 | 0x0004 | 0x0010)
>         self.browser.NotifyMoveOrResizeStarted()  

remove - 16, - 38 will fix this issue,   but  at the same time,  non-fullscreen window's  scroll bar will disappear.

**Comment by r0x0r** [comment]
Cannot reproduce it with this example

```
import webview
from time import sleep

def minimize(window):
    sleep(5)
    print('Minimizing window')
    window.minimize()


if __name__ == '__main__':
    window = webview.create_window('Minimize window example', html='<body style="background:red;"><h1>Minimize window</h1></body>', minimized=False)
    webview.start(minimize, window)
```

**Comment by oddmario** [comment]
I have the same issue.

**Comment by oddmario** [comment]
> Cannot reproduce it with this example
> 
> ```
> import webview
> from time import sleep
> 
> def minimize(window):
>     sleep(5)
>     print('Minimizing window')
>     window.minimize()
> 
> 
> if __name__ == '__main__':
>     window = webview.create_window('Minimize window example', html='<body style="background:red;"><h1>Minimize window</h1></body>', minimized=False)
>     webview.start(minimize, window)
> ```

@r0x0r You couldn't reproduce the issue because you didn't specify `cef` as the engine.

**Comment by oddmario** [comment]
> At webview.platforms.cef.Browser
> 
> > def resize(self, width, height):
> > webview.platforms.cef.windll.user32.SetWindowPos(self.inner_hwnd, 0, 0, 0, width - 16, height - 38,
> > 0x0002 | 0x0004 | 0x0010)
> > self.browser.NotifyMoveOrResizeStarted()
> 
> remove - 16, - 38 will fix this issue, but at the same time, non-fullscreen window's scroll bar will disappear.

This fixed it. I'm not sure why such hardcoded values were put. Should I submit a PR for this?

**Comment by r0x0r** [comment]
@oddmario I specify cef renderer via an environment  variable in my tests.

Those hard-coded values were put to compensate for titlebar and scrollbars as we derive the dimensions of the cef component from the dimensions of the parent window. Hard-coded values do not seem to do the trick in all cases, so a better solution needed. 
If you remove these values it will crop cef view contents.
