### ISSUE TITLE
Problem with downloading files from websites

### ISSUE THREAD

**Issue by MisterNox** [r0x0r/pywebview#590]
### Specification
- pywebview version: 3.3.3
- platform / version: windows 10 / python 3.8

### Description  
  
Hi,
I have a quite specific question regarding the download possibilites in pywebview.

**What is the problem?**

On websites there are download possibilities (<a> tags, buttons etc.) for files (jpg, png, txt, zip etc.).  

I struggle with downloading these files from the webview, because I could not find out where it gets downloaded (in my general browser download folder it is not) or wether it is even downloaded.

One approach that actually works if the href-url within the a-tag is pointing directly to the file (e.g. https:// example-page.com /static/image.png) is to use the javascript-python-bridge  to catch the url and start a request in my python code to save it somewhere. This does not work when I receive a blob-url (e.g. created by a javascript library). I hope, I explained the problem well enough for you to understand it.

**What am I looking for?**

 - Either a way to specify the download folder in pywebview (normaly not possible due to security lacks) or to get the location of the default download destination if it gets downloaded
 - handle the blob download with javascript/python/js-py-bridge

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

Thank you in advance for your help or any kind of hints you can give me.

**Comment by r0x0r** [comment]
I have never looked into downloading files. It is highly platform specific and my guess is that 
1) it is not implemented by default, so files are not downloaded anywhere
2) could be done by intercepting `on navigating` events or something along these lines

**Comment by MisterNox** [comment]
Yeah I tried to dive deeper into it and from my point of view it has to be integrated into the windows.forms controll dll. There is a webbrowser method called downloadFile and an event to handle that. I will try to get this to work, but maybe I need some guidance with the windows.forms stuff as this is completely different from what I have done so far. First question would be: Is it only compiling the stuff in visual studio or do I have to consider something special about it when I added the event and so on? Thanks in advance.

**Comment by r0x0r** [comment]
I think this could be done in Python alone, without need to make change to C# code in the dll.

As this is clearly a new feature,the download behaviour should be defined first. The way I see it
1) Downloads are ignored by default. 
2) `webview.start(download_dir='dir')` would enable downloads.
3) Some MIME logic should probably be introduced as well. E.g. what do with jpeg files that have an application/octet-stream MIME type?

**Comment by MisterNox** [comment]
First of all thank you for your time and answer. Well, for downloading static files it can be done in python, I already did that. But blobs are in browser cache so if I catch the url and start a request for example, I will not get the browser cache, because the server does not know the path. I was reading a little bit the last days about this topic and the webview (edge) itself cannot handle downloads, but there is a trigger event when navigating called UnviewableContentIdentified. Thats why I think there should be a general approach in the dll to handle both scenarios.

**Comment by r0x0r** [comment]
On the second thoughts, a better approach would be to introduce a `window.navigating` event that would  trigger for every link click. This way developer could decide for themselves that to do with unviewable content. Default download logic (if any) should be disabled.

**Comment by MisterNox** [comment]
Do you think it should be implemented as a lifecycle hook like the events loaded, shown etc. or simply as a window method which can be overwritten in case you want to do something with the args?

**Comment by r0x0r** [comment]
Lifecycle hook like other events. Its name could be window.navigating
(loading is too vague imo). URL as an event param is probably enough.
