### ISSUE TITLE
Embed in gui framework

### ISSUE THREAD

**Issue by AndiLeni** [r0x0r/pywebview#594]
### Specification
- pywebview version: newest
- platform / version: windows 10

### Description  
  
Hello,
I wanted to ask, wether it is possible to embed a pywebview window in another gui application (like qt,kivy, toga).
My intention was to create a application to contain windows for each of my regulary used websites and switching between them with buttons from a sidebar. 
Is this somehow possible or are there any experiences with a topic like this one?

Regards
Andi

**Comment by r0x0r** [comment]
Not really.

What you can do is to rip for example QT code and embed in your application.
