### ISSUE TITLE
Windows 10 - Administrator's CheckNetIsolation.exe authorization box appears

### ISSUE THREAD

**Issue by dgasparri** [r0x0r/pywebview#595]
### Specification
- pywebview library version: 3.3.3 (pip installed)
- pywebview examples/load_html.py file: from commit 458b215 (latest Git master commit)
- platform / version: Windows 10, Python 3.8.5

### Description  
  
When I try to run `python load_html.py` it shows the administrator's CheckNetIsolation.exe authorization box (see image attached).

Other example files like load_css.py work just fine.

Attached are the dump of the `python -v load_html.py` command and the screenshot of the required authorization.
  
### Practicalities

- NO I am willing to work on this issue myself (far beyond my abilities)

- NO I am prepared to support this issue financially.

[python load_html.py.log](https://github.com/r0x0r/pywebview/files/5157945/python.load_html.py.log)
![20200901_193653](https://user-images.githubusercontent.com/553197/91887821-943f3100-ec8b-11ea-9a3a-656ef3122381.jpg)

**Comment by r0x0r** [comment]
This is by design due buggy limitations of EdgeHTML. The good news is that you have to accept it only once.

https://pywebview.flowrl.com/guide/renderer.html#edgehtml
