### ISSUE TITLE
Example todos displays a white window with no content 

### ISSUE THREAD

**Issue by dgasparri** [r0x0r/pywebview#596]
### Specification
- pywebview library version: 3.3.3 (pip installed)
- pywebview todos/start.py example file: from commit 458b215 (latest Git master commit)
- platform / version: Windows 10, Python 3.8.5

### Description  
  
  The command `python start.py` opens a window with title "Todos magnificos" but no content (empty). It does not output any error to console.

 Some other examples work just fine (like load_css.py or simple_browser.py), while others don't with a strange error. Could be connected to Issue #595 but since they give different errors (here no Windows admin authorization is required), I opened two separate tickets.

[python todos_start.py.log](https://github.com/r0x0r/pywebview/files/5157968/python.todos_start.py.log)

### Practicalities

- NO I am willing to work on this issue myself (with no debugging info or output error, I don't know where to start!)

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Confirmed. Seems like the new web server has broken this.

**Comment by r0x0r** [comment]
I pushed a fix to the `http-server-fix` branch.
