### ISSUE TITLE
Option to keep standard window controls on frameless windows in MacOS

### ISSUE THREAD

**Issue by Alex979** [r0x0r/pywebview#597]
### Specification
- pywebview version: 3.3.3
- platform / version: MacOS Big Sur

### Description  
  
Currently, since version [3.3](https://pywebview.flowrl.com/CHANGELOG.html#_3-3-detroit-edition) the frameless option in `create_window` hides the standard window controls (close, minimize, fullscreen). However, many applications in MacOS implement custom title bars by implementing a fullscreen window but still keeping the standard window controls. For example, Todoist has a custom title bar that matches the theme of the application as shown here:
![Todoist screenshot](https://i.imgur.com/8HZyFrF.png)
This is possible in Electron with the ["titleBarStyle"](https://pywebview.flowrl.com/CHANGELOG.html#_3-3-detroit-edition) option for MacOS applications which can be set to "hidden" which "results in a hidden title bar and a full size content window, yet the title bar still has the standard window controls ("traffic lights") in the top left."

I think this would be a good feature to add, as the appeal of frameless windows in my opinion is making custom title bars that match the theme of your application, but it would be nice if we could still keep the standard window controls when we do this, perhaps with a similar option to Electron's titleBarStyle.
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by Alex979** [comment]
To assist a bit with this, [these three lines of code](https://github.com/r0x0r/pywebview/blob/458b21513e979f50f1a738f7cc3e1cd101912737/webview/platforms/cocoa.py#L372) are where the window controls are hidden. There could be a MacOS specific option in `create_window` to not hide these, as commenting out these three lines yields the desired result.

```python3
# These are the lines of code in question (webview/platforms/cocoa.py lines 372-374)
self.window.standardWindowButton_(AppKit.NSWindowCloseButton).setHidden_(True)
self.window.standardWindowButton_(AppKit.NSWindowMiniaturizeButton).setHidden_(True)
self.window.standardWindowButton_(AppKit.NSWindowZoomButton).setHidden_(True)
```

**Comment by Alex979** [comment]
I've created a fork of this repository [here](https://github.com/Alex979/pywebview/tree/frameless-window-controls) that adds a "preserve_controls" option to do what I described above. However, I don't want to create a pull request unless this is a feature you would like to see added. Let me know what you think!

**Comment by r0x0r** [comment]
It used to preserve controls on macOS until I realised that it was not consistent with other platforms. I will think of a possible solution that would be more or less platform agnostic.

**Comment by r0x0r** [comment]
Bump

**Comment by AlexanderWillner** [comment]
As an alternative, I suggest that for example these lines

```python
self.window.standardWindowButton_(AppKit.NSWindowCloseButton).setHidden_(True)
self.window.standardWindowButton_(AppKit.NSWindowMiniaturizeButton).setHidden_(True)
self.window.standardWindowButton_(AppKit.NSWindowZoomButton).setHidden_(True)
``` 

should be callable directly from outside of the class, e.g. by exposing the `self.window` variable. For example:

```python
window = webview.create_window(title='test', frameless=True)
window._getWindow().standardWindowButton_(AppKit.NSWindowCloseButton).setHidden_(False)
```

**Comment by r0x0r** [comment]
@AlexanderWillner I have been thinking about a similar solution for a while, ie https://github.com/r0x0r/pywebview/issues/617#issuecomment-748354414
It would make sense to expose both native window and native application objects in a window instance to tackle platform specific cases like this. Suggestions for object names are welcomed.
