### ISSUE TITLE
cannot terminate from within script

### ISSUE THREAD

**Issue by petri** [r0x0r/pywebview#600]
### Specification

Newest pywebview, MacOS, Python 3.8

### Description  
  
I tried using pywebview for fetching some data from webpage that's exposed via JS code on page. 

So I tried to:

1. open the page with `hidden=True`
1. run `evaluate_js` to get the data
1. `window.destroy()` -> `sys.exit()`

This kind of works; the app gets the foreground, gets the data. And exits, BUT only after it gets some user input such as keypress or mouse movement. So it does not seem this is feasible for an automated solution.

Any way to do everything in the background, and/or have pywebview release control without user kb/mouse intervention?

**Comment by r0x0r** [comment]
Could you post a code example?

**Comment by petri** [comment]
Here. Interestingly, if I remove the `evaluate_js` call, the script runs through and exits without hiccup.

```
import sys
import webview

def evaluate_js(window):
    result = window.evaluate_js(r"""window""")
    window.destroy()
    print("killed window")

if __name__ == '__main__':
    window = webview.create_window('Test', "https://www.google.com", hidden=True)
    webview.start(evaluate_js, window)
    print("exiting")
    sys.exit()
```

**Comment by r0x0r** [comment]
This is an old problem I haven’t found a solution for. In tests, it is circumvented by generating a programmatic mouse event. Functions for programmatic Cocoa events can be found here  https://github.com/r0x0r/pywebview/blob/master/tests/util_cocoa.py <https://github.com/r0x0r/pywebview/blob/master/tests/util_cocoa.py>

**Comment by petri** [comment]
Oh ok thanks!
