### ISSUE TITLE
Fixing the get_app_root to make Pywebview works from Python interpreter and Jupyter notebook 

### ISSUE THREAD

**Issue by alhabshi3k** [r0x0r/pywebview#601]
### Specification
- pywebview version: 3.3.2
- platform / version: Windows 10 64-bit

### Description  
  
  While I was testing and learning Pywebview. I tried to make an application that loads an HTML with CSS from a folder relevant to the Python code. 
```python 
import webview
webview.create_window('Hello world', 'assets/index.html')
webview.start() # http_server=True # for altering between using a Server or Serverless.
```
My finding when having the HTML/CSS/JS files and Python Application code are:

-  When writing the Python code and saving it a file, eg app.py, then calling the app by ```python app.py``` the code works.
-  When writing the Python code in a cell Jupyter notebook, eg. prototype-with-pywebview.ipynb, PyWebView could not recognize where is the HTML/CSS/JS content, even it is directly relevant to the prototype-with-pywebview.ipynb.
-  A similar case, when running Python interpreter in the same folder that has the HTML/CSS/JS assets and executes the above three lines of Pywebview application, it could not recognize the assets folder.
- Tracking the issue where it is originated, I found it is in the Util.py of PyWebView where calling for base_uri goes to get_app_root which leads to the `sys.argv[0]`. This works if running a Python script file, but not in the case of Jupyter Notebook and code running from Python interpreter where the sys.argv[0] refers to Python modules in `site-package` folder.

### Practicalities

- At the stage of development in different scripting editing mode for testing ideas, considering the separation of Python as back-end support, and HTML/CSS/JS as front-end, PyWebView made me ask my self "what is wrong with my code, although it is same ?!?". PyWebView does not behave in a pythonic manner and digests the assets that are directly in-front the interpreter environment circumstance, specifically the current directory where the code is executed.
- A quick money patch around it for the moment is by substitute the call of `get_app_root` with `os.cwd`. it works with all the mentioned scenarios, But I don't know it will work with PyInstaller.
``` python
# a Monkey-patch  :P
webview.util.get_app_root = os.getcwd
```
- The patch works when running PyWebView as Server mode or being Serverless.
- A permanent fix can be done in the `get_app_root` function in the util.py script.

And thank you for PyWebView, it small, and _partially pythonic_. The good part it does not burden coders with other heavy dependencies, although they can be extra support.

**Comment by r0x0r** [comment]
I haven't used Jupyter personally, but the best course would be adding Jupyter specific path resolving logic to https://github.com/r0x0r/pywebview/blob/746fd6a16fb678d4d63b4fe8cd61476154f5516d/webview/util.py#L44 similarly as it is done with pytest.
