### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by S41L0R** [r0x0r/pywebview#603]
### Specification
- pywebview version: 3.3.3
- platform / version: Windows 10

### Description  
  
  I upgraded to this version of pywebview in the hopes that pointerlock would be supported. Now, I only get a blank screen unless I'm on cef. I can't be on cef as my page doesn't work properly, for a reason I cannot debug due to the debug feature not working. When I have it set to edgeHTML and debug it with the Edge Devtools debugger, I find that it has routed me to about:blank. This was broken as of 3.3.2, as it works on 3.3.1 but stops working on 3.3.2.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Please post a code example. You can also try master, it has a fix for a http server problem.

**Comment by S41L0R** [comment]
Ok, master did fix the blank screen problem. The next thing would be, is it possible to somehow implement pointerlock? I know my code is set up correctly because I can use it in chrome, I just can't actually lock my pointer in pywebview.

**Comment by r0x0r** [comment]
What is a pointer lock?

**Comment by S41L0R** [comment]
Sorry for the late reply. It's essentially when your pointer disappears and always registers as within a certain element. Here's the doc page: [https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API).

And here's the demo they have hidden away on that page: [https://mdn.github.io/dom-examples/pointer-lock/](https://mdn.github.io/dom-examples/pointer-lock/)

**Comment by r0x0r** [comment]
Might be that it is not supported by renderer. Have you tried CEF to see if it is any different?

**Comment by S41L0R** [comment]
Yep, I've been using CEF as well as Edge.

**Comment by r0x0r** [comment]
It seems pointer lock is not supported by CEF https://bitbucket.org/chromiumembedded/cef/pull-requests/51/added-support-for-pointer-locking/diff
