### ISSUE TITLE
Flask Object error

### ISSUE THREAD

**Issue by Eliasmgprado** [r0x0r/pywebview#608]
### Specification
- pywebview version:  3.3.4
- platform / version:  windowns 10

### Description  

Getting this error when set flask object as url.

MY CODE:

app = Flask(__name__, instance_relative_config=True,static_folder='./static', template_folder='./templates')

if __name__ == '__main__':
        window = webview.create_window('MLTurb Tools', app)
        webview.start()

ERROR:
  
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    webview.start()
  File "C:\Users\Elias Prado\.conda\envs\MLTurb_tools\lib\site-packages\webview\__init__.py", line 99, in start
    window._initialize(guilib, multiprocessing, http_server)
  File "C:\Users\Elias Prado\.conda\envs\MLTurb_tools\lib\site-packages\webview\window.py", line 90, in _initialize
    if gui.renderer == "edgehtml" and self.original_url and (self.original_url.startswith('file://') or '://' not in self.original_url):
AttributeError: 'Flask' object has no attribute 'startswith'

**Comment by imadonmwinyi** [comment]
I have this same error working with pywebview in flask, its seems not to accept the flask app instance as argument in webview.create_window() 
Any quick fix will be appreciated or guide on how to setup flask and pywebview

**Comment by r0x0r** [comment]
Fixed in master. I will release a fixed version shortly
