### ISSUE TITLE
Question - is it possible to catch keystroke events?

### ISSUE THREAD

**Issue by 99hats** [r0x0r/pywebview#610]
### Specification
- pywebview version: n/a
- platform / version: n/a

### Description  
  
It would be nice to capture things like the alt-lftarrow to navigate backwards or escape to quit.
  
### Practicalities

- NO I am willing to work on this issue myself. 

- NO I am prepared to support this issue financially. Depends.

**Comment by r0x0r** [comment]
Could not you do it via Javascript?

**Comment by 99hats** [comment]
Mostly, except when the user is sent off to another website there's no back button.  IFrames could be used in this case, but I've found iFrames hard to work with you never know how the links may be targetted.

This is a great platform. You've done a wonderful job with it. I like it so much better than Electron.

I can't believe how long it took me to stumble upon though.
