### ISSUE TITLE
Window movement example return an Error

### ISSUE THREAD

**Issue by PROgramJEDI** [r0x0r/pywebview#611]
### Specification
- pywebview version: 3.3.5
- platform / version: ?

### Description  
  
 I ran the following example: https://pywebview.flowrl.com/examples/move_window.html
and I get the following error (Ubuntu 20):
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3.8: ../../src/xcb_io.c:641: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Gdk-Message: 13:11:58.717: webv.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

[Finished in 0.3s with exit code 1]
[cmd: ['python3.8', '-u', '/home/*****/******/******/Library/WorkingOn/webv.py']]
[dir: /home/*****/******/******/Library/WorkingOn]
[path: /home/*****r/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin]
```
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
No
- YES/NO I am prepared to support this issue financially.
No

**Comment by r0x0r** [comment]
There are a bunch of bugs open related to threading in GTK. Looks like something changed in recent version of GTK that breaks the current implementation. Or maybe GTK threads were misused in the first place.
I will take a look at this whenever I get a chance. Meanwhile help is welcomed.
