### ISSUE TITLE
How to create a window after clicking a button?

### ISSUE THREAD

**Issue by eoogo** [r0x0r/pywebview#612]
### Specification
- pywebview version:  3.3.5
- platform / version:  win10 19042.546

### Description  
  
  I wanted to create a new window when I clicked a button, but I couldn't
  
### Practicalities

- YES/NO I am willing to work on this issue myself.    Yes, but now I have to finish this project first

- YES/NO I am prepared to support this issue financially. No

**Comment by eoogo** [comment]
I tried to create a window with the parameter hidden to true and call the `show()` method when I clicked the button, but the Main window failed to start error occurred

**Comment by r0x0r** [comment]
JS API combined with webview.create_window.
