### ISSUE TITLE
CEF High DPI issue (probably) - window inside window

### ISSUE THREAD

**Issue by bekatd** [r0x0r/pywebview#613]
### Specification
- pywebview version: 3.3.3
- platform / version: Windows 10

### Description  
  
  I am facing window inside window issue on some machines.
![image](https://user-images.githubusercontent.com/6948919/95775646-db313500-0cd3-11eb-8258-859c45887437.png)
After some research I found that it should be High DPI related issue, and tried to create manifest files for main executable app.exe and subprocess.exe files with dpiaware settings true, but it caused blank screen upon launch.

  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This issue was fixed here https://github.com/r0x0r/pywebview/issues/331
Has it resurfaced?

**Comment by bekatd** [comment]
Unfortunately yes. In order to reproduce issue you can change scaling in windows while application is already running
![image](https://user-images.githubusercontent.com/6948919/95783705-7251b900-0ce3-11eb-8e9e-da7e028acff8.png)

**Comment by bekatd** [comment]
And also. I don't understand how manifest files work. I created files but they have not effect at all.

**Comment by bekatd** [comment]
I tested and its completely `cefpython` related issue, since `mshtml` is rednering everything correctly when changing scale

**Comment by r0x0r** [comment]
I don’t understand manifest files either.

One thing that I can think of is the path to subprocess.exe set by pywebview is not correct. As result it fails to apply correct DPI settings.

**Comment by bekatd** [comment]
I looked at you changes and seems it expects subprocess file to be in the cefpython package right?
![image](https://user-images.githubusercontent.com/6948919/95785437-cb6f1c00-0ce6-11eb-86a9-43c3058f3be7.png)

**Comment by r0x0r** [comment]
Either cefpython package or bundled along with pyinstaller

**Comment by bekatd** [comment]
I use cx-freeze, since with pyinstaller I get trojan virus alerts on windows machines.
Issue exists for both installers, as its completely cefpython related issue not freezers

**Comment by r0x0r** [comment]
I have no experience with cxfreeze. Feel free to contribute a patch.

**Comment by bekatd** [comment]
Results of my little investigations that might be helpful.
I tried to set different scale options
![image](https://user-images.githubusercontent.com/6948919/95789729-18ef8700-0cef-11eb-90cf-ea406fe35419.png)
and eventually I got it working if BOTH `app.exe` (executable of application) and `subprocess.exe` have the same scale settings, BUT with small bug - window content remains unchanged, until forcefully cause repaint (for example, slightly changing size of window) and whoala everything in its place again.

The problem now is that main executable can't set own scale settings after running :(

any thoughts?

**Comment by bekatd** [comment]
@r0x0r 
I found solution, it so simple.
Just set DPI scale mode programmatically before invoking window with `ctypes`:
**`ctypes.windll.user32.SetProcessDpiAwarenessContext(-4)`**
link to description: [https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext](url)

list of options:
- DPI_AWARENESS_CONTEXT_UNAWARE					(-1)
- DPI_AWARENESS_CONTEXT_SYSTEM_AWARE				(-2)
- DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE		(-3)
- DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2	(-4)
- DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED		(-5)

**Comment by bekatd** [comment]
@r0x0r Would be great if you inject this `ctypes.windll.user32.SetProcessDpiAwarenessContext(-4)` before window initialization and also ensure that `subprocess.exe` file is discovered in case it's not inside `cefpython` package folder.

For some reason `cx_Freeze` needs to place `subprocess.exe` (and all other `cefpython` files, except `cefpython_XX.pyd` and `__init__.py` files) alongside main executable (outside of `cefpython` directory) and I manually fixed the correct reference to it

**Comment by r0x0r** [comment]
Does this setting replace the registry hack in place?

**Comment by bekatd** [comment]
> 
> Does this setting replace the registry hack in place?

Unfortunately no. Only combination of those two (main.exe and subprocess.exe) dpi settings does the job

**Comment by r0x0r** [comment]
To support cx_freeze there should be a way to detect that program is run under cx_freeze (like with pyinstaller’s sys._MEIPASS) and set the subprocess.exe path accordingly.

**Comment by bekatd** [comment]
> 
> To support cx_freeze there should be a way to detect that program is run under cx_freeze (like with pyinstaller’s sys._MEIPASS) and set the subprocess.exe path accordingly.

I think its sys.frozen for cxfreeze

[https://cx-freeze.readthedocs.io/en/latest/faq.html#using-data-files](url)
