### ISSUE TITLE
Cannot open the debug console

### ISSUE THREAD

**Issue by plutarch29a** [r0x0r/pywebview#614]
### Specification
- pywebview version: 3.3.5
- platform / version: win10

### Description  
  
  Right click looks disabled.
 
```
import webview

if __name__ == '__main__':
    webview.create_window('Debug window', 'https://pywebview.flowrl.com/hello')
    webview.start(gui="qt", debug=True)

```

**Comment by r0x0r** [comment]
Is this QT on Windows?

**Comment by plutarch29a** [comment]
> 
> Is this QT on Windows?

yes, installed with pip install pywebview[qt]

**Comment by plutarch29a** [comment]
:) I'm pretty sure to have used the QT engine with pywebview (and the debug console) a few months ago.
Anyway, it seems that a small change in gui.py, line 96, is enough
~~~
#guis = [import_winforms]
guis = [import_qt, import_winforms]
~~~
