### ISSUE TITLE
can we take screenshot of the window?

### ISSUE THREAD

**Issue by gauravniltech** [r0x0r/pywebview#615]
I am trying to render html and take a screenshot to merge it in a video stream for streaming. Is there any way to take a screenshot?

**Comment by r0x0r** [comment]
Searching for "python screenshot" reveals a myriad of options
https://www.startpage.com/do/dsearch?query=python+screenshot&cat=web&pl=opensearch&language=english

**Comment by gauravniltech** [comment]
though none of them are relevant, I want to screenshot of render html and want to run the process in backend, so I can show merged preview on the screen, so does this have an option like window.capture or something?

**Comment by r0x0r** [comment]
No there is nothing like that in pywebview.
