### ISSUE TITLE
MacOS input type="file" brakes if filename contains cyrillic characters

### ISSUE THREAD

**Issue by ikhmyz** [r0x0r/pywebview#616]
### Specification
- pywebview version: 3.3.5
- platform / version: macos 10.15.5

Probably the macos webkit bug but:
```
<input type="file">
```
after selecting file containing cyrillic characters in its name eg ("файл.txt") input.change event not received and all file inputs stop responding.

the only log message is:
```2020-10-14 17:33:41.193 Python[13779:2548578] -[NSNull path]: unrecognized selector sent to instance 0x7fff8a99aea0```

**Comment by r0x0r** [comment]
There was a bug in the open file handler, which is now fixed in master. 

Можешь протестировать?

**Comment by ikhmyz** [comment]
> There was a bug in the open file handler, which is now fixed in master. Можешь протестировать?

Tested in master, works fine
