### ISSUE TITLE
Accent Colour in Pages

### ISSUE THREAD

**Issue by lorisobi** [r0x0r/pywebview#617]
Add a way to use the windows accent colour in windows applications with a fallback for linux and macos

**Comment by r0x0r** [comment]
What is an accent colour?

**Comment by lorisobi** [comment]
![image](https://user-images.githubusercontent.com/28399150/96108959-772e8c80-0ede-11eb-9955-cd0e23bb0d7b.png)
 so in windows you can choose an basic color which is used in buttons in the whole system

![image](https://user-images.githubusercontent.com/28399150/96109142-a47b3a80-0ede-11eb-9185-363ede8375df.png)
![image](https://user-images.githubusercontent.com/28399150/96109176-ac3adf00-0ede-11eb-8604-6f84f03eec3c.png)
it  would be great if we could use these colors in our applications (via DOM from python) to make them look more native
there are ways for windows programs to get the colour value from the system but no ways for html/css to achieve this

**Comment by kakksanthusa** [comment]
You can get that colour code from python and 
Add css using window.load_css
https://pywebview.flowrl.com/guide/api.html#load-css

**Comment by r0x0r** [comment]
This can be done relatively simply. 

https://stackoverflow.com/questions/39257539/get-the-users-accent-color-winform-c

I am not sure how to make it available. Maybe expose to DOM via pywebview's object.

**Comment by r0x0r** [comment]
I think the best general approach to this would be exposing a native GUI object to pywebview's native window. Eg. something like `window.native_window` would point to the underlying form so your case would translate to `window.native_window.Resources["SystemAccentColor"]`.
