### ISSUE TITLE
on_top-Windows didn`t work

### ISSUE THREAD

**Issue by abc01170303** [r0x0r/pywebview#618]
### Specification
- pywebview version: 3.3.5
- platform / version: window10

### Description  

pywebview window Cannot display topmost 
![123](https://user-images.githubusercontent.com/72924780/96129286-052f6500-0f29-11eb-9ec6-d53d9f8b5fd5.jpg)

### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Cannot reproduce with `examples/on_top.py`

**Comment by Ksengine** [comment]
> Cannot reproduce with `examples/on_top.py`

Yes
Close this issue
