### ISSUE TITLE
Support for PyQt on Mac

### ISSUE THREAD

**Issue by josePhoenix** [r0x0r/pywebview#62]
There's a (perhaps narrow) use case where it would be beneficial to have pywebview on Mac try PyQt as well as PyObjC. The Anaconda scientific distribution does not (as far as I know) package PyObjC, but I am led to believe Qt is supported by the vendor as the anointed cross-platform GUI toolkit.

(I haven't yet tried fiddling with a local clone to see if it's as simple as adding a `try`/`except ImportError` for the Mac path in `__init__`...)

**Comment by josePhoenix** [comment]
A brief unscientific test seems to indicate things "just work" when importing the Qt GUI on a Mac in the case where PyObjC is unavailable. Nice.

**Comment by r0x0r** [comment]
Nice one. Actually I originally started a QT implementation on OSX  for some reason I don't remember right now.
It is unlikely I will work on this port, if any issues arise. But if you submit a PR, I will gladly accept it.
