### ISSUE TITLE
Proxy support for a window

### ISSUE THREAD

**Issue by analogaio** [r0x0r/pywebview#620]
### Specification
- pywebview version: 3.2
- platform / version: Any

### Description  
  
  I think it would be greatly useful to be able to add http & https proxy support to each window instance. Perhaps it could be included as an argument like:

window = webview.create_window("Example Window", "https://examplewebsite.com", proxy=(101.0.1.0, 1010))

Or something of that sort! 
  
### Practicalities

- NO I am not willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Just a head up on the realities of this project. I am the sole developer and I don't have much time due other work. While I have nothing against this, it is unlikely that I will find time to work on this in foreseeable future.

As always you are welcomed to submit a pull request or sponsor this issue.

**Comment by Ksengine** [comment]
@analogaio  can you tell more info?

**Comment by Ksengine** [comment]
GTK - https://stackoverflow.com/questions/6915840/python-webkit-with-proxy-support/19068804

**Comment by Ksengine** [comment]
Qt -https://github.com/jsoffer/eilat/

**Comment by zhengxiaoyao0716** [comment]
Windows Edge(Chromium):
``` python
        os.environ['WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS'] = ' '.join((
            f'--proxy-server="{url},direct://"',
            # f'--proxy-pac-url="{url}/proxy.pac"',
        ))
```
