### ISSUE TITLE
add window object methods

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#624]
- window.moveTo
- window.resizeTo
- window.moveBy
- window.resizeBy
- window.fullscreen
- window.unFullscreen
- window.toggleFullscreen
- window.maximize 
etc
### Description  
  
add this methods to use from javascript(from webpage side)
this methods are not supported in most browsers   

### Practicalities

-  I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
Good suggestion.
I disagree with overloading the window object, but these could be placed into `pywebview.window`. The api and method names could be same or at least similar to the methods of the `window.py`. 

Comments? Other ideas?

**Comment by Ksengine** [comment]
we can set pywebview.window methods to window
eg:
`window.moveTo=pywebview.window.moveTo;`

**Comment by Ksengine** [comment]
can u set suitable labels to this issue

**Comment by Ksengine** [comment]
can we add this methods to jsbridge class.
please, explain it

**Comment by Ksengine** [comment]
can i make a pull

**Comment by Ksengine** [comment]
https://www.w3schools.com/jsref/obj_window.asp

**Comment by r0x0r** [comment]
Overwriting Javascript built-in functions is a bad practice. I would rather have these separately, for example under `pywebview.window`. The API could be 

`pywebview.window.createFileDialog(params)`
`pywebview.window.destroy()`
`pywebview.window.hide()`
`pywebview.window.minimize()`
`pywebview.window.move(x, y)`
`pywebview.window.resize(width, height)`
`pywebview.window.restore()`
`pywebview.window.show()`
`pywebview.window.toggleFullscreen()`

I am not sure what to with properties.

**Comment by Ksengine** [comment]
> Overwriting Javascript built-in functions is a bad practice
why?

**Comment by Ksengine** [comment]
We can use ECMAScript5 (for properties)

**Browser Support**

![chrome](https://icons.iconarchive.com/icons/google/chrome/128/Google-Chrome-icon.png)  | ![IE/Edge](https://icons.iconarchive.com/icons/tatice/cristal-intense/128/Internet-Explorer-icon.png)  | ![Firefox](https://icons.iconarchive.com/icons/carlosjj/mozilla/128/Firefox-icon.png)  | ![Safari](https://icons.iconarchive.com/icons/johanchalibert/mac-osx-yosemite/128/safari-icon.png)  |  ![Opera](http://files.softicons.com/download/application-icons/round-app-icons-by-ampeross/png/128x128/Opera.png) 
-- | -- | -- | -- | --
Chrome 23 | IE10 / Edge | Firefox 21 | Safari 6 | Opera 15
Sep 2012 | Sep 2012 | Apr 2013 | Jul 2012 | Jul 2013

**Comment by Ksengine** [comment]
example
```
// Define object
var obj = {counter : 0};

// Define setters
Object.defineProperty(obj, "reset", {
  get : function () {this.counter = 0;}
});
Object.defineProperty(obj, "increment", {
  get : function () {this.counter++;}
});
Object.defineProperty(obj, "decrement", {
  get : function () {this.counter--;}
});
Object.defineProperty(obj, "add", {
  set : function (value) {this.counter += value;}
});
Object.defineProperty(obj, "subtract", {
  set : function (value) {this.counter -= value;}
});

// Play with the counter:
obj.reset;
obj.add = 5;
obj.subtract = 1;
obj.increment;
obj.decrement;
```

**Comment by Ksengine** [comment]
if not supported;(older than IE10)

```
window.__defineGetter__('innerWidth', function() { return pywebview.window.getInnerWidth(); });

window.__defineSetter__('innerWidth', function(val) { pywebview.window.setInnerWidth(val); });

window.innerWidth = 5;
console.log(window.innerWidth); 

```

**Comment by Ksengine** [comment]
can i make a pull

**Comment by kakksanthusa** [comment]
Its good

**Comment by r0x0r** [comment]
> can i make a pull

Please go ahead.
