### ISSUE TITLE
Path /index.html was not found after package(pyinstaller)

### ISSUE THREAD

**Issue by Voyageson** [r0x0r/pywebview#625]
### Specification
- pywebview version: 3.3.5
- platform / version: window 10

### Description  

I test a demo from doc

import webview

window = webview.create_window('Woah dude!', 'index.html')
webview.start(http_server=True)

--------
really awesome project among so many webview implementations!
But in Python, generating exe is a big problem.....

**Comment by Voyageson** [comment]
![Snipaste_2020-10-22_13-32-37](https://user-images.githubusercontent.com/46949655/96828937-1ae1e480-146b-11eb-8a79-487b0fd6905d.png)
![Snipaste_2020-10-22_13-36-08](https://user-images.githubusercontent.com/46949655/96829154-917ee200-146b-11eb-991a-daf174886e39.png)

**Comment by r0x0r** [comment]
I agree that generating an exe in Python is a big problem. 

pywebview has a basic support for freezing with Pyinstaller, but this is about it. Other freezing solutions either have not been tested or proved to be too much work.
However, I have nothing against support for freezing solutions, if somebody has got energy for research and investigation.

Maybe you could start by first stating what freezing solution you tried.

**Comment by Voyageson** [comment]
Thank you for your reply!

As I said in the title of this issue, I used pyinstaller.
I'm afraid that maybe I made an silly mistake, so I describe my problem more detailed.

|--- index.html
|--- demo.py
it does work with 'python demo.py' command

then 'pyinstaller -F demo.py'
|--- index.html
|--- demo.exe
error of 'path XXX was not found' occured after running demo.exe

Your criticism is welcome.

**Comment by r0x0r** [comment]
Oh sorry the mail client truncated the title, so did not notice the pyinstaller bit. 

Does it work without the onefile option?

**Comment by Voyageson** [comment]
With -F or without -F
With http_server or without http_server
And I try to put html file in an ‘assets’ directory
These all didn’t work

Actually, the thing I want to know most is whether this situation only appears to me?
If so,  I may consider more about the problem of MY environment, or my computer
Maybe, I should try to restart from reinstalling python.  haha

**Comment by r0x0r** [comment]
I will check paths when I get a chance.

The thing with one file is that you have to include your asset inside your executable using the data switch. Placing it along the exe file would not work.

**Comment by r0x0r** [comment]
Bad news. My Windows machine broke so I am not able to look into this at the moment.

**Comment by r0x0r** [comment]
I managed to test it and this is caused by the `assets` dir not being included with pyinstaller. Look into the Adding files section of pyinstaller docs.
https://pyinstaller.readthedocs.io/en/stable/spec-files.html

**Comment by Voyageson** [comment]
Thank you soooo much!
