### ISSUE TITLE
Keyboard shortcut for 'back'

### ISSUE THREAD

**Issue by nst0022** [r0x0r/pywebview#626]
### Specification
- pywebview version: 3.3.5
- platform / version: Debian 10 buster

### Description  
  
If I load an HTML page and click on a link which leads me to another page, which key combination do I have to press to get back to the first page?

For the WebKit engine, Ctrl-Logo-LeftArrow should do the trick, but neither this nor any other weird combination I tried brought me back.

**Comment by r0x0r** [comment]
Back and other navigation keys are disabled and there is no way to enable
them using API. You can probably emulate back key functionality with
injecting relevant Javascript code on each page load.

**Comment by Ksengine** [comment]
can we add this to api

**Comment by r0x0r** [comment]
The philosophy of pywebview is to hide browser controls and the fact the UI is run inside a web control. Back key is an artefact of a web browser and does not go along with this philosophy. 
What is a use case for a back key?
