### ISSUE TITLE
Stop freezing Main thread

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#627]
can we stop freezing main thread.
Its working with gtk and qt.
not working on windows MSHTML
Cocoa not tested.

We can do it with multiprocessing.

**Comment by r0x0r** [comment]
Are you suggesting to run GUI loop as a separate process and keep the main thread of the main process free?

**Comment by Ksengine** [comment]
yes,
you added multiproessing as an argument of start method
but not supported yet

**Comment by Ksengine** [comment]
I can help

**Comment by r0x0r** [comment]
The original multiprocessing idea was to use internally processes instead
of threads. But I like your approach more. Feel free to go ahead with
implementation. The parameter name could be `webview.start(block=True)`.
The default value is True by default to keep it backward compatibility.

**Comment by Ksengine** [comment]
ok i will add this feature

**Comment by Ksengine** [comment]
can you add labels to this issue

**Comment by r0x0r** [comment]
One consideration that should be decided is the exit logic. Normally the
program exits after the gui loop ends but with a non-blocking gui what
would be the default logic? With a non-blocking user code what is the
behaviour after the code finishes executing?

**Comment by r0x0r** [comment]
I like the join syntax, as it is inline with the Python API. Let's name the parameter `daemon` instead of `block` and make `start` return a process object in the daemon mode. ie.

```
process = webview.start(daemon=True)
do_stuff()
process.join()
# app is exited after this
```

We need to think of a way to signal the gui process to quit after the join, as it would not happen automatically.

**Comment by Ksengine** [comment]
i added my pull request.
**sorry, i hadn't read your last reply**
so i added both `daemon` and `block` methods
but they are different
i copied from #632 
> - multiprocessing added
> - fixed threading
> - added two keyword arguments to start method
>     - block(default : True)
>     - daemon(default : True)(works if block is False)
> 
> ex(block):-
> ```python
> import webview
> w = webview.create_window("ssss","https://www.google.com")
> join = webview.start(block=False) # set block option to False( default:True )
> print('free main thread')
> # Some code
> print('blocked main thread')
> join() # join gui loop to main thread
> print('free main thread') # this line works after gui loop ended
> ```
> 
> ex(block without join):-
> ```python
> import webview
> w = webview.create_window("ssss","https://www.google.com")
> join = webview.start(block=False) # set block option to False( default:True )
> print('free main thread')
> # Some code
> # program exits when no any code run and gui loop ended
> ```
> 
> ex(daemon):-
> ```python
> import webview
> w = webview.create_window("ssss","https://www.google.com")
> join = webview.start(block=False, daemon=False) # set daemon option to False( default:True )
> print('free main thread')
> # Some code
>  # gui loop stops and exit program
> ```

**Comment by Ksengine** [comment]
can we update docs

**Comment by Ksengine** [comment]
> I like the join syntax, as it is inline with the Python API. Let's name the parameter `daemon` instead of `block` and make `start` return a process object in the daemon mode. ie.
> 
> ```
> process = webview.start(daemon=True)
> do_stuff()
> process.join()
> # app is exited after this
> ```
> 
> We need to think of a way to signal the gui process to quit after the join, as it would not happen automatically.

if you accept my pull
then we can make this change in few minutes

**Comment by Ksengine** [comment]
i had recently made a pull (#638 )
view it and accept

**Comment by Ksengine** [comment]
@analogaio reported a issue on #638 pr. I hope he will report it here

**Comment by analogaio** [comment]
- Issue: Process taking an extremely long amount of time to start

- Operating System: Windows 10 

- GUI Lib: Not using any web-based one, using Tkinter. 

- Notes: It takes exponentially longer to open each webview if you open more processes.

- Sample code:
```
def create_window():
    def configure():
          window.resize(432, 630)
          window = webview.create_window('Captcha Harvester', 'https://accounts.google.com/AccountChooser',
                                   min_size=(432, 630), on_top=True)
          webview.start(configure)


if __name__ == '__main__':
    multiprocessing.Process(target=create_window).start()  # Takes about 10+ seconds to start, sometimes even 30-50 seconds
    main()  # Tkinter main loop
```

**Comment by Ksengine** [comment]
GUI Lib: Not using any web-based one, using Tkinter. :disappointed: 
**pywebview always use some GUI libraries for display webview**
- GTK - linux.using GTK Webkit
- Qt - linux.using Qt Webkit
- Cocoa - MacOS. using Webkit(based on Safari)
- IE(Internet Explorer) - Windows. IE based webbrowser control with Windows .Net GUI(included)
- Edge - Windows. Edge browser based webbrowser control with Windows .Net GUI(included)
- CEF - Windows. Chrome/Chromium like python port of Chromium Embedded Framework based webbrowser control with Windows .Net GUI(included)

I think you are using Edge

**Comment by analogaio** [comment]
> GUI Lib: Not using any web-based one, using Tkinter. 😞
> **pywebview always use some GUI libraries for display webview**
> 
> * GTK - linux.using GTK Webkit
> * Qt - linux.using Qt Webkit
> * Cocoa - MacOS. using Webkit(based on Safari)
> * IE(Internet Explorer) - Windows. IE based webbrowser control with Windows .Net GUI(included)
> * Edge - Windows. Edge browser based webbrowser control with Windows .Net GUI(included)
> * CEF - Windows. Chrome/Chromium like python port of Chromium Embedded Framework based webbrowser control with Windows .Net GUI(included)
> 
> I think you are using Edge

Ah yes, I think I misunderstood the question. It's probably Edge then

**Comment by Ksengine** [comment]
> Sample code:
...

some errors? are you a python beginner?
fixed example
```python
def create_window():
    def configure():
          window.resize(432, 630)
    window = webview.create_window('Captcha Harvester', 'https://accounts.google.com/AccountChooser', min_size=(432, 630), on_top=True)
    webview.start(configure)


if __name__ == '__main__':
    multiprocessing.Process(target=create_window).start()
    main()  # Tkinter main loop
```

using multiprocessing on windows is bad and walk-around like method.
- download [@Ksengine/pywebview](https://github.com/Ksengine/pywebview/)(30+mb) or [@KsTGTeam/pywebview](https://github.com/KsTGTeam/pywebview/)(2-5mb)
- unzip files
- place following code file on that folder and run

```python
if __name__ == '__main__':
    window = webview.create_window('Captcha Harvester', 'https://accounts.google.com/AccountChooser', min_size=(432, 630), on_top=True)
    window.resize(432, 630)
    webview.start(block = False)
    main()  # Tkinter main loop

```

**Comment by analogaio** [comment]
Thanks for the fix! Seems to be opening perfectly now. 

Another issue I noticed is that after opening 1 webview, if I run the function to open another one, it will open 3 for some reason.

Exact code to reproduce:
```
import webview
import time


def create_window():
    window = webview.create_window('Test', 'https://google.com',
                                   min_size=(432, 630), on_top=True)
    webview.start(block=False)


create_window()
time.sleep(5)
create_window()
time.sleep(10)
```
The first window opens perfectly, the second function creates 3 windows in a row. No error codes btw.

**Comment by Ksengine** [comment]
**threre is another error**
I will explain both
1. in your early script
`create_window` creates a method named `configure` but does nothing
try following code, it will print `1` twice it cant print `0`.
I think you copied code wrongly
```python
def create_window():
    print(1)
    def configure():
          print(0)
          window.resize(432, 630)
          window = webview.create_window('Captcha Harvester', 'https://accounts.google.com/AccountChooser',
                                   min_size=(432, 630), on_top=True)
          webview.start(configure)
    print(1)


if __name__ == '__main__':
    multiprocessing.Process(target=create_window).start()  # run create_window on another process 
    main()  # Tkinter main loop
```

2. now
- first you import `webview and `time`
- create method named `create_window`
- runs `create_window`
  - run `webview.create_window`
  - run `webview.start` (GUI event loop)
**GUI event loop opens one window**
- sleep 5 secs
- run `create_window`
  - run `webview.create_window`
  - run `webview.start` (second GUI event loop)
**frist GUI event loop opens one window**
**second GUI event loop opens one window**
**now there are 3 windows**

Then fixed code 
```python
import webview
import time


def create_window():
    window = webview.create_window('Test', 'https://google.com',
                                   min_size=(432, 630), on_top=True)

create_window()
webview.start(block=False)

time.sleep(5)
create_window()
time.sleep(10)
create_window()
```

**Tip :**
> you can highlight syntax of your code on github markdown
> \`\`\`python
> your code goes here
> \`\`\`

**Comment by Ksengine** [comment]
@analogaio I sent an github invite for you.

**Comment by ItsCubeTime** [comment]
Why did this not get merged? Im currently in a situation where I wish to run a flask instance to create the html page that I want to display with pywebview - cant quite seem to be able to successfully run both in concurrence

**Comment by ItsCubeTime** [comment]
Why did this not get merged?

Im currently in a scenario where I want to run a flask webserver in combination with pywebview to host the content of the page on the same python instance.

Seems flask *can* run outside of the main thread, but I would prefer to run everything outside the main thread to feel confident I dont run into any dependency incompatibility issues in the future

**Comment by r0x0r** [comment]
@ItsCubeTime macOS has never been fixed, nor I have any idea if it is possible at all. Generally GUI programs are designed with UI thread running on the main thread and everything else on sub-threads. 

Personally I see no problems running Flask on a sub-thread and I have never run into any issues with it. If you are so adamant about running a web server on a main thread, just use multiprocessing for launching Flask.

**Comment by ItsCubeTime** [comment]
I see, well it makes sense then if this PR didnt support all platforms 👍

**Comment by josh0xA** [comment]
Ugh, I hate to bring this up again and apologies if I misread previous messages (I'm a bit drunk right now). Has there been any developments in being able to run a pywebview window instance outside of a Tkinter main thread? Basically, I'm working on an application that has a tkinter listbox, and upon selection of an item in the list (a link) it opens a webview window - I would like to do it for multiple items in the listbox at the same time. Is it just that Qt and GTK are simply terrible in which they like to contain external window instances within the main thread? I would love to know if there's anything that can be done about this or do I just have to suck it up and keep everything in the main thread? Fantastic library by the way.

**Comment by r0x0r** [comment]
Just use multiprocessing and open pywebview in a separate process.
