### ISSUE TITLE
Unable to debug with CEF on Windows

### ISSUE THREAD

**Issue by jgentil** [r0x0r/pywebview#628]
### Specification
- pywebview version: 3.3.5
- platform / version: Windows + CEF

### Description  
  
`debug=True` doesn't propagate properly from `start()`
 While trying to get the debugger working in CEF, I noticed that as soon as `create_window` calls `CEF.init(window)` the value of `_debug` flips from `True` to `False` for some reason.  They seem to be in the same thread, so I can only gather that it has something to do with the nature of declaring `global _debug` and changing it in `start()` doesn't change it where it's imported, sometimes.  It seems fine in winforms.py but not in cef.py.  Maybe because cef is conditionally imported?  Dropping a breakpoint at line 72 https://github.com/r0x0r/pywebview/blob/952b3115c1b3b884e6a4d213a0a031bdea9e6609/webview/platforms/winforms.py#L71-L73 shows me that after this import, `CEF._debug` == `False` instead of `True`. 

I actually came to post that I didn't understand why, but I put a breakpoint on the line in cef.py where _debug is imported, and I realized that I was importing cef.py long before `_debug` is set to true in order to get to `cef.settings` .  I don't know why it became disjointed and lost the fact that the reference changed, but it feels like maybe this should be a `is_debug()` function in `__init__.py` instead of relying on it being a global variable.

Unfortunately there's no workaround since you can't pass the settings.  I can't change the settings after start() is called, and I can't import it before either.  The best I can do is force setting `webview._debug=True` and then importing `cef.settings` after that.
  
### Practicalities

- YES I am willing to work on this issue myself.

-  NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
I could not reproduce this with 
```
    window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
    webview.start(gui='cef', debug=True)
```

Console output
```
[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:50479/devtools/browser/60f389b9-d993-4677-8ea1-c42bb7c78812
```

**Comment by kakksanthusa** [comment]
> I could not reproduce this with
> 
> ```
>     window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
>     webview.start(gui='cef', debug=True)
> ```
> 
> Console output
> 
> ```
> [pywebview] Using WinForms / CEF
> 
> DevTools listening on ws://127.0.0.1:50479/devtools/browser/60f389b9-d993-4677-8ea1-c42bb7c78812
> ```

Hey,
I am ksengine
This link is a websocket url
works like Chrome devtools
Eg:-
- open websocket server
- open devtools frontend
- frontend starts a websocket connection to devtools backend websocket server
- two ends share debug data through connection as JSON messages
So cef should has a devtools window(like cefsharp)
Or we had to add entire devtools frontend to project

**Comment by Ksengine** [comment]
ok i am Ksengine
I had found a method
i an make a pull. but i haven't a windows machine to test.
- [check if this browser currently has an associated DevTools browser](https://github.com/cztomczak/cefpython/blob/master/api/Browser.md#hasdevtools)
- [Open developer tools (DevTools) in its own browser.](https://github.com/cztomczak/cefpython/blob/master/api/Browser.md#showdevtools)
- [close the associated DevTools browser](https://github.com/cztomczak/cefpython/blob/master/api/Browser.md#closedevtools)
so the rwference is https://github.com/cztomczak/cefpython/blob/master/api/Browser.md

**Comment by jgentil** [comment]
Sorry I've not had time to post a more accurate reproduction of this.  I will attempt to soon.  This doesn't have anything to do with the DevTools websocket though.

**Comment by jgentil** [comment]
Here's how to reproduce.  Observe the behavior of these two snippets of code.

#### This first snippet runs fine.
```python
import webview

def main():
    window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
    webview.start(gui='cef', debug=True)

if __name__ == '__main__':
    main()
```
#### This snippet, however, does not, because upon importing `webview.platforms.cef` the persistence of `webview._debug` changes for some reason.
```python
import webview
from webview.platforms.cef import settings
settings['persist_session_cookies'] = True

def main():
    window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello')
    webview.start(gui='cef', debug=True)

if __name__ == '__main__':
    main()
```
The only work-around is to manually set `webview._debug = True` just before calling `create_window`

**Comment by jgentil** [comment]
Silly bot, this is still a problem!

**Comment by r0x0r** [comment]
@jgentil I think this has to with how settings are processed in cef.py lines 205-231. When you import and set settings, all_settings is getting overwritten for some reason. 
I still do not have a Windows machine to dive into this, and I cannot spot the problem by just looking at the code, but my guess the problem is there.

**Comment by jgentil** [comment]
I'll try to make some headway into patching this and submitting a PR.  I've worked around the issue so I think I have an idea on how to fix it too.

**Comment by r0x0r** [comment]
PR here https://github.com/r0x0r/pywebview/pull/712
