### ISSUE TITLE
Set custom window icon

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#635]
### Description  
  
**Feature Request**
add method to set custom icon without freezers like pywebview
 
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Aye, good idea.  `create_window(icon=icon_path)` or something like that.

Some considerations
1) No external libraries like pillow please
2) Must be cross-platform
3) Accepted icon formats at least png. I don't think there is a need to support platform specific icon formats like .ico or ICNS

**Comment by Ksengine** [comment]
> Aye, good idea. create_window(icon=icon_path) or something like that.
icon is always a file path

**Comment by Ksengine** [comment]
**question**
can we extract the icon of currently loaded webpage

**Comment by Ksengine** [comment]
- Qt - window.setWindowIcon(QtGui.QIcon('icon.png'))

**Comment by Ksengine** [comment]
Dont close this issue

**Comment by OttomanZ** [comment]
@Ksengine I agree this should be an implemented feature, has this been implemented yet?

**Comment by r0x0r** [comment]
There is a stale PR that implements this feature https://github.com/r0x0r/pywebview/pull/786
The OP never addressed change requests. Feel free to continue.

**Comment by v479038280** [comment]
Is there an example about set-icon?
