### ISSUE TITLE
add sciter webview

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#641]
add [sciter](https://sciter.com/) webview

there is also a python implementation [pysciter](https://pypi.org/project/PySciter/) 

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
My previous concern about spreading thin applies here as well. I understand you are prepared to help, but would you stick around to maintain the code? 

As for sciter, this is the second time I hear about it. Have you used it personally? Is it mature? Is it good?

**Comment by Ksengine** [comment]
sciter website says:
> In almost 10 years, Sciter UI engine has become the secret weapon of success for some of the most prominent antivirus products on the market: Norton Antivirus and Internet Security, Comodo Internet Security, ESET Antivirus, BitDefender Antivirus, and others. The use of HTML/CSS has allowed their UI to stay in touch with modern GUI trends throughout all these years, and will continue to well into the future.

read this page; https://sciter.com/developers/for-web-programmers/

**Comment by Ksengine** [comment]
main problem of sciter is no js
so we can use https://github.com/c-smile/sciter-js-sdk
