### ISSUE TITLE
web browser runtimes 

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#642]
## add web browser runtimes 

we can use chrome and firefox as runtimes.
we can remove menus, search bar and other decorations.
i have experience with doing this

chrome is easy
firefox is bit complex

- YES I am willing to work on this issue myself.

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Do you mean Chrome's app mode?

**Comment by Ksengine** [comment]
yes

**Comment by Ksengine** [comment]
and xul apps on firefox

**Comment by Ksengine** [comment]
we can control window using ajax long polling.
and iframe is used to show window.

**Comment by r0x0r** [comment]
If I am not mistaken Google is sunsetting Chrome's app mode. I would not pursue that.

I am not familiar with XUL, but the thing about additional renderers that implementations require support. With the current situation I am being the sole developer, I cannot take on board any more renderers.

**Comment by Ksengine** [comment]
> If I am not mistaken Google is sunsetting Chrome's app mode. I would not pursue that.

more info?

**Comment by Ksengine** [comment]
i can help

**Comment by r0x0r** [comment]
https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html

**Comment by Ksengine** [comment]
sorry. you understood it wrongly.
chrome apps are extensions with some files(manifest etc.)
i am saying about chrome app mode.
we can run chrme with `--app` flag
eg:-
```
<chrome path> --app="https://www.google.com"
```

**Comment by Ksengine** [comment]
you should visit #641

**Comment by Ksengine** [comment]
add suitable labels

**Comment by r0x0r** [comment]
You are correct about the app mode.
I see the rationale behind adding Chrome as a renderer. However several issues must be resolved first.
1) It has browser menu bar and other controls. Is there anyway to hide those?
2) What would happen if chrome is selected as a renderer and Chrome is not installed on user machine?
3) How does JS-Python bridge would work?

**Comment by Ksengine** [comment]
i thought about hose problems.
i can explain

**Comment by Ksengine** [comment]
1. app mode hides them
2. they can't use chrome as renderer.(we can force them to install)
    add it to `guilib.py` like other methods(gtk, qt...)
3. we can use wesockets, SSE, ajax long polling, ajax requests etc

**Comment by r0x0r** [comment]
Menu bar is not hidden on MacOS 
![image](https://user-images.githubusercontent.com/1549657/98460074-a1a3fa80-21a9-11eb-993a-564ccb02b10a.png)

Is it different on other OSes?

**Comment by Ksengine** [comment]
sorry, menu bar is showing on any platform

**Comment by Ksengine** [comment]
if you are saying about `frameless` mode
`--kiosk` mode can remove them

**Comment by Ksengine** [comment]
chrome.py
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
import platform
import os

name = "Google Chrome/Chromium"


def find_path():
    """
    find the chrome executable path on Windows, Linux/OpenBSD, Mac or Unknown system.
    """
    if platform.system() == "Windows":
        return _find_chrome_win()

    elif platform.system() == "Darwin":  # Mac OS
        return _find_chrome_mac()

    elif platform.system() == "Linux" or platform.system() == "OpenBSD":
        return _find_chrome_linux()

    else:
        try:
            return _find_chrome_linux()
        except:
            try:
                return _find_chrome_mac()
            except:
                try:
                    return _find_chrome_win()
                except:
                    return None


def _find_chrome_mac():
    paths = [  # mac os chrome path list
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        "/usr/bin/google-chrome-stable",
        "/usr/bin/google-chrome",
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
    ]

    chrome_path = None

    for path in paths:  # loop through paths
        if os.path.exists(path):
            chrome_path = path

    if chrome_path != None:
        return chrome_path

    else:  # use which command to find chrome
        for browser in ("google-chrome", "chrome", "chromium", "chromium-browser"):
            a = os.popen("which " + browser).read()
            if a == "":
                pass
            else:
                return a[:-1]

        return None


def _find_chrome_linux():
    paths = [
        "/usr/bin/google-chrome-stable",  # linux chrome path list
        "/usr/bin/google-chrome",
        "/usr/bin/chromium",
        "/usr/bin/chromium-browser",
        "/snap/bin/chromium",
    ]

    chrome_path = None

    for path in paths:
        if os.path.exists(path):
            chrome_path = path

    if chrome_path != None:
        return chrome_path

    else:  # use which command to find chrome
        for browser in ("google-chrome", "chrome", "chromium", "chromium-browser"):
            a = os.popen("which " + browser).read()
            if a == "":
                pass
            else:
                return a[:-1]

        return None


def _find_chrome_win():
    import winreg as reg  # import registry

    chrome_path = None
    reg_path = r"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe"

    for install_type in (reg.HKEY_CURRENT_USER, reg.HKEY_LOCAL_MACHINE):
        try:
            reg_key = reg.OpenKey(install_type, reg_path, 0, reg.KEY_READ)
            chrome_path = reg.QueryValue(reg_key, None)
            reg_key.Close()
            if not os.path.isfile(chrome_path):
                continue
        except WindowsError:
            chrome_path = None
        else:
            break

    for browser in ("google-chrome", "chrome", "chromium", "chromium-browser"):
        a = os.popen("where " + browser).read()
        if a == "":
            pass
        else:
            chrome_path = a[:-1]

    return chrome_path


chrome_path = find_path()
if not chrome_path:
    raise Exception("No chrome")


class ChromeView:
    def __init__(self, url="data:text/html,<h1>DicksonUI</h1>", options=[]):
        cmd = chrome_path
        for option in options:
            cmd += " "
            cmd += option
        cmd += " --incognito"
        cmd += " --new-window"
        cmd += ' --app="'
        cmd += url + '"'
        os.popen(cmd)

    def version(self, path):
        try:
            v = os.popen(find_path() + " --version").read()
            v2 = v[v.find(" ") + 1 :]
            return int(v2[: v2.find(".")])
        except:
            return None

    def is_chromium(self, path):
        try:
            if os.popen(path + " --version").read().startswith("Chromium"):
                return True
            else:
                return False
        except:
            return None
```

**Comment by Ksengine** [comment]
example with DicksonUI(my project)
```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
from dicksonui import Application, window
from chrome import ChromeView
mywindow=window()
App = Application(('',1024))
App.add(mywindow)
mywindow.document.body.innerHTML=open('index.tmp').read()
print("Navigate To - "+App.location)
ChromeView(App.location)
```

**Comment by Ksengine** [comment]
screenshot
![Screenshot_2020-11-08_11-46-42](https://user-images.githubusercontent.com/63494497/98464072-31e93c00-21b8-11eb-8cf3-67ff29369889.png)

**Comment by Ksengine** [comment]
index.tmp is a html code with bootstrap.

**Comment by r0x0r** [comment]
I am not keen on including Chrome due UX reasons.

However, a plugin support for external renderers could be a viable idea. Something like this
```
import webview
import chrome_webview # external plugin

webview.register(chrome_webview)
webview.create_window(...)
webiew.start(gui='chrome')
```

**Comment by Ksengine** [comment]
> I am not keen on including Chrome due UX reasons.

UX(user experiense)

explain more

**Comment by Ksengine** [comment]
why plugin?
we can include it as a gui

**Comment by Ksengine** [comment]
Poor UX ?

**Comment by Ksengine** [comment]
i had given you an example, not the real code of new gui

**Comment by Ksengine** [comment]
> Contributors come and go. People solve their problem, submit a PR and after that it is not their problem any more. Should bugs occur, it all comes back to me.

it's not Contributors' fault, they help you(even for bug fixes.)
i will make pull requests and fixing bugs until  i like.
this is not my job.this is my hobby

**Comment by Ksengine** [comment]
ok i will explain all things

**Comment by Ksengine** [comment]
# webview.start

to use chrome as a webview, we need a server(WSGI is better)
- open localhost on chrome(using subprocess or os.popen)
- server sends controller page
- controller page sets properties and opens a shows the page using iframe
    - title - `document.title`
    - url -  url can be a http url(`url`option of  `webview.start`), file url or  data url(`html` option)
        iframe can open localhost connections to local servers
    - html - use data url for iframe
    - width , height - `window.resizeTo`
    - x, y - `window.moveTo`
    - resizable - (default is True) if False use `window` events to detect resizing and set width and height
    - fullscreen - use `--kiosk` flag or js [fullscreen api](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) or css
    -  min_size - use `window` events to detect resizing and set width and height
    - hidden - dont open chrome until `pywebview_window.show` called
    - frameless - not supported
    - minimized - not supported
    - on_top - not supported
    - confirm_close - using `window` events,
    - background_color - using css
    -  text_select - using css and js
- controller page opens a websocket connection to server

**Comment by Ksengine** [comment]
# Then
- controller page opens a websocket connection to server
- use wesocket to control window, js api and interdomain communication

**Comment by Ksengine** [comment]
# Window object

- on_top -always False
- x, y - returns `window.screenX` and `window.screenY`
- width, height - return `window.outerWidth` and `window.outerHeight`
- create_file_dialog - create input with type="file" and raise fake click event
- destroy - kill chrome process
- evaluate_js - send js through websocket and get results as JSON
- get_current_url - return `window.location.href`
- get_elements - using evaluate_js
- hide - not supported
- load_css - using evaluate set css
- load_html - using evaluate_js
- load_url - using evaluate_js
- minimize - not supported
- move - `window.moveTo`
- restore - not supported
- set_title - set `document.title`
- show - not supported
- toggle_fulscreen - js [fullscreen api](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)

and all events supported through websocket
drag area supported

**Comment by Ksengine** [comment]
for websocket i hope to use @Ksengine/wsocket

**Comment by r0x0r** [comment]
> it's not Contributors' fault, they help you(even for bug fixes.)
> i will make pull requests and fixing bugs until i like.
> this is not my job.this is my hobby

You are correct.
This is not my job as well. I do this on my free time and I do not get paid for this.
Exactly for this reason I choose code I work with and how I do it.

**Comment by Ksengine** [comment]
Yes, we will work together to develop this project.
Users should contribute if they need more features

**Comment by Ksengine** [comment]
we can add chrome webview as experimental feature.
i wrote a long description. say your ideas and questions.

**Comment by Ksengine** [comment]
no reply?

**Comment by Ksengine** [comment]
cna i make a PR

**Comment by r0x0r** [comment]
> Two reasons
> 
> 1. Poor UX
> 2. I don't want to support code I am not comfortable with.
> 
> I appreciate your enthusiasm, but ask yourself will you be here making pull requests and fixing bugs two years from now? What about five years?
> 
> Contributors come and go. People solve their problem, submit a PR and after that it is not their problem any more. Should bugs occur, it all comes back to me.

This still stands. By poor UX, I mean Chrome menubar and other browser artefacts. If you manage to make Chrome window more app like, this will make a difference. Otherwise if you want to see this future, I am ready to discuss plugin architecture.

**Comment by Ksengine** [comment]
> screenshot
> ![Screenshot_2020-11-08_11-46-42](https://user-images.githubusercontent.com/63494497/98464072-31e93c00-21b8-11eb-8cf3-67ff29369889.png)

This as a python web app on chrome.
in this example It has no menubar and other browser artefacts.

**Comment by Ksengine** [comment]
I will make a PR for basic `guilib`.
then we can discuss about.
