### ISSUE TITLE
remove large assets  

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#643]
this repo is around 30mb
- https://github.com/r0x0r/pywebview/blob/master/examples/assets/video.mp4 (12mb)
- https://github.com/r0x0r/pywebview/blob/master/examples/assets/video.webm (12mb)

remove these files
i can upload better one

**Comment by Ksengine** [comment]
[video.zip](https://github.com/r0x0r/pywebview/files/5504409/video.zip)

include this link https://creativecommons.org/licenses/by/3.0/legalcode

**Comment by r0x0r** [comment]
I would rather keep the existing video. It is my dear cat Luna.

The videos can probably be compressed to save on the size.

**Comment by Ksengine** [comment]
you can store them in another place

**Comment by Ksengine** [comment]
then users can download it manually or script(we can add python script to download file)

**Comment by Ksengine** [comment]
if you cant remove your dear cat Luna, minimize the resolution or place them in another place to download

**Comment by r0x0r** [comment]
Please keep this discussion civil. 
If size of the videos is a problem for you, you are welcome to make a pull request with optimized videos.
