### ISSUE TITLE
fast js api

### ISSUE THREAD

**Issue by Ksengine** [r0x0r/pywebview#645]
in docs
> `window.pywebview.api` is not guaranteed to be available on `window.onload`

`window.pywebview.api` should be available on `window.onload`

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
JS API is injected on a webview's load event. I don't see a way to inject it earlier in a reliable way, but if you find a way, please go ahead.

**Comment by Ksengine** [comment]
I know methods for Qt and GTK
I will be able to fix winforms
But cocoa?

**Comment by Ksengine** [comment]
Reopen please
