### ISSUE TITLE
 raise WebViewException('Main window failed to load')

### ISSUE THREAD

**Issue by tarquo23** [r0x0r/pywebview#653]
### Specification
- pywebview version:  3.3.5
- platform / version:  Windows python 3.7

### Description  
  
  Hi, I'm working on my thesis project for neurological experiments. So far I have used Tkinter to build a desktop application and start from it some experiments using Psychopy.
Now I would need to display some web pages inside my application to give the user instructions on how to move around the page. So I decided to use your library to open a webpage within my application.
I don't know if this is not possible but when I launch the code below, 
` web = webview.create_window('Experiment',  'https://www.nespresso.com/it/it/our-choices/esperienza-caffe/lean-in-and-listen-stories-behind-nespresso-fairtrade-coffee')` 
  ` webview.start()`
the application crashes and I get the following output. Am I doing something wrong or just a Tkinter GUI can't live with your library?

[
![Issue](https://user-images.githubusercontent.com/32510884/100110232-fe233d00-2e6c-11eb-9160-fb05d1adba8b.PNG)
](url)
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I could not reproduce it ran as a standalone application. 

I have no clue how to use pywebview from tkinter or another gui application. pywebview was not designed for that, but apparently people try to do it all the time.

**Comment by tarquo23** [comment]
I guess it's because on the internet it's recommended when you ask how you can open web pages, but not when you're looking for which framework to build an application with. So the needs are discovered when a good part of the functions have already been written with other libraries, such as Tkinter.

**Comment by r0x0r** [comment]
One solution is to open pywebview as a separate window along with tktinter gui in another window. Here is an example of multiprocessing architecture 
https://github.com/r0x0r/pywebview/blob/2cff89a76fd70a621900e5e806355affc24f787d/docs/examples/no_block.md

**Comment by tarquo23** [comment]
Thanks for your availability, these days I try to see if I can make it work!

**Comment by Ksengine** [comment]
you can run Tkinter GUI loop (`root.mainloop()`) in another thread
