### ISSUE TITLE
Will supported automating web sites in the future?

### ISSUE THREAD

**Issue by XHXIAIEIN** [r0x0r/pywebview#657]
pywebview if supported  web automation it would be helpfulness. such as:  
- [Selenium](https://selenium-python.readthedocs.io/)
- [Helium](https://github.com/mherrmann/selenium-python-helium)

For example, can support some automation, like Helium:
https://github.com/mherrmann/selenium-python-helium/blob/master/docs/cheatsheet.md

```
write()
press()
click()

hover()
rightclick()
doubleclick()
select()

wait_until()
find_all()

elements.exists()

highlight()
```

### Specification
- pywebview version: 
- platform / version: 

### Description  
  
  Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I am rather conservative regarding extending APIs, but I have thought about this. In particular `window.get_elements` was introduced with web automation in mind. Having said that, something like this sounds more like a job for a separate library built on top of `pywebview`.

**Comment by Ksengine** [comment]
## you can use javascript.
simple fake click
```python
...
window.evaluate_js("document.getElementById('link').click();")
...
```
js has methods to do all methods(mentioned above).
