### ISSUE TITLE
How do destroy window by calling a Python function via the JS API?

### ISSUE THREAD

**Issue by zc3945** [r0x0r/pywebview#659]
### Specification
- pywebview version: 3.3.5
- platform / version: Windows 10

### Description  
  
  ```python
import webview


html = """
<!DOCTYPE html>
<html>
<head lang="en">
</head>
<body>
<h1>JS API Example</h1>
<button onclick="close()">close</button>
<script>
    function close() {
        pywebview.api.close();
    }
</script>
</body>
</html>
"""


class Api:

    def close(self):
        window.destroy()


window = webview.create_window('test',
                               html=html,
                               easy_drag=False,
                               js_api=Api,
                               frameless=True)
webview.start()
```
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by dtmilano** [comment]
You need an instance of `Api`:
```
...
js_api=Api(),
...
```

**Comment by zc3945** [comment]
> You need an instance of `Api`:
> 
> ```
> ...
> js_api=Api(),
> ...
> ```

Thank you, Sir！
I think my simplified example really does have this problem. But my actual situation is as follows, there should not be such a problem?

- js_api.py
```python
window = None
def close():
    window.destroy()
```
- index.html
```html
<!DOCTYPE html>
<html>
<head lang="en">
</head>
<body>
<h1>JS API Example</h1>
<button onclick="close()">close</button>
<script>
    function close() {
        pywebview.api.close();
    }
</script>
</body>
</html>
```
- main.py
```python
import js_api
window = webview.create_window('test', url="index.html",js_api=js_api,frameless=True)
js_api.window = window
webview.start(gui='mshtml')
```

**Comment by dtmilano** [comment]
Try `_close()` as `close()` is already defined

```
<!DOCTYPE html>
<html>
<head lang="en">
</head>
<body>
<h1>JS API Example</h1>
<button onclick="_close()">close</button>
<script>
    function _close() {
        pywebview.api.close();
    }
</script>
</body>
</html>
```

**Comment by zc3945** [comment]
> script

Thank you, this method is effective.
It seems that the python methods open through js_api coexist with the methods declared in javascript, and not in the window.pywebview.api object alone. Is this understanding correct?

**Comment by zc3945** [comment]
> Try `_close()` as `close()` is already defined
> 
> ```
> <!DOCTYPE html>
> <html>
> <head lang="en">
> </head>
> <body>
> <h1>JS API Example</h1>
> <button onclick="_close()">close</button>
> <script>
>     function _close() {
>         pywebview.api.close();
>     }
> </script>
> </body>
> </html>
> ```

Thank you, this method is effective.
It seems that the python methods open through js_api coexist with the methods declared in javascript, and not in the window.pywebview.api object alone. Is this understanding correct?

**Comment by r0x0r** [comment]
close is a global js function. this has nothing to do with pywebview.
