### ISSUE TITLE
Get cookies from webview

### ISSUE THREAD

**Issue by sam-goode** [r0x0r/pywebview#668]
### Specification
- pywebview version: 3.3.5
- platform / version: Windows 10

### Description  
  
Is there any way of getting the cookies out of pywebview?

For example if I present a window for the user to login to a website, and I then want to take the cookies and use them to perform some background requests e.g. using requests or pdfkit.
 
I know I can do evaluate_js('document.cookie') but that only gets the 'visible' cookies from the current page, and I would need to grab everything from the session. 
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
No

- YES/NO I am prepared to support this issue financially.
Depends on the cost I suppose, probably not

**Comment by r0x0r** [comment]
evaluate_js('document.cookie')
evaluate_js('window.localStorage')
evaluate_js('window.sessionStorage')
?

**Comment by choczilla** [comment]
Comparing these methods against something like Helium/Selenium I get very different data. 

```
import helium
driver = helium.start_chrome('https://google.com')
driver.get_cookies()
[{'domain': '.google.com', 'expiry': 2146723199.436621, 'httpOnly': False, 'name': 'CONSENT', 'path': '/', 'secure': True, 'value': 'YES+GB.en-GB+V9+BX'}, {'domain': 'www.google.com', 'expiry': 1607028265, 'httpOnly': False, 'name': 'UULE', 'path': '/', 'secure': False, 'value': 'a+cm9sZTogMQpwcm9kdWNlcjogMTIKdGltZXN0YW1wOiAxNjA3MDA2NjY1NTgyMDAwCmxhdGxuZyB7CiAgbGF0aXR1ZGVfZTc6IDUxOTQ0MTg0MgogIGxvbmdpdHVkZV9lNzogLTg3NzM4MTIKfQpyYWRpdXM6IDk4MDIyMApwcm92ZW5hbmNlOiA2Cg=='}, {'domain': '.google.com', 'expiry': 1622817865.158668, 'httpOnly': True, 'name': 'NID', 'path': '/', 'secure': True, 'value': '204=WoG_6PKakvsu-WcMSpaIffSr6FkKim8E3ZR5bqkJS-efChflDzokiVhEnwGKfNr6nofl98xVJ58yWq_UAJY1rq5rNrebYad4a5-b_naj3zo3I_Wa_c9GQc6qxyQ0wG1W-3weUyR1b8ci96iUJDSjaDzX4_djxAJwmfXk4NvZDiE'}]
```

vs
```

import webview
import pdb

def trace(window):
	pdb.trace()

window = webview.create_window('title','https://google.com')
webview.start(trace, window)


> <pyshell#11>(2)trace()->None
(Pdb) window.evaluate_js('document.cookie')
'CONSENT=YES+GB.en-GB+V9+BX'

(Pdb) window.evaluate_js('window.localStorage')
{'sb_wiz.zpc.': '[[["sony playstation ps5 console stock",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["professor jonathan van tam masks",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["adolf hitler wins election namibia",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["manchester airport covid testing centre",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["maria fyfe labour",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["gcses exams 2021",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["welsh government covid travel",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["gavin williamson",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["dpd parcel delivery scams",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}],["tiers guidance",0,[362,143],{"zf":33,"zl":8,"zp":{"gs_ss":"1"}}]],{"ag":{"a":{"8":"TRENDING SEARCHES"}},"q":"iryufd7SDRPxiGOnC2JAlilVYpM"}]'}

(Pdb) window.evaluate_js('window.sessionStorage')
{'_c;;i': 'p:*|l:9007199254740991_2', 'hsb;;1607006560726': 'p:*|l:0_[1607006560725]', 'hsb;;1607006560725': 'p:*|l:1_{"state":null,"url":"/","metadata":{"bda":1607006560724,"$k":1607006560725,"TU":1607006560726,"aN":0}}'}
```

If I needed to do something with that UULE cookie for example, is it possible to get that with webview? I'm not sure if it's accessible via JavaScript or not

**Comment by r0x0r** [comment]
I have tested it with macOS and `document.cookie` returns an empty string both with evaluate_js and debug inspector. My guess is up to a web renderer on how it handles cookies. Behaviour is probably configurable too.

Cookies is definitely something that should be looked into and a proper support built. There is a related issue https://github.com/r0x0r/pywebview/issues/531

**Comment by jokil123** [comment]
Is reading Http-only cookies possible by now?

**Comment by ThatOtherAndrew** [comment]
Bumping this - directly manipulating cookies, especially HttpOnly cookies, is a pretty critical feature for a webview IMO.

**Comment by r0x0r** [comment]
There is now a cookie implementation in the 4.0 branch. Cookies can be enabled via `webview.start(private_mode=False)`. Support for cookies varies from one platform to another.

**Comment by ThatOtherAndrew** [comment]
Great to know, thank you. I'm using the 4.0 branch now, with `private_mode` set to false - if I understand correctly this allows cookies to persist between sessions, but I'm still not understanding how to access and manipulate the cookies. Could you point me in the right direction please?

**Comment by r0x0r** [comment]
Just use Javascript via `document.cookie` or your favourite cookie library

**Comment by ThatOtherAndrew** [comment]
I am currently unable to test as it appears the `site-packages/webview/lib` directory is missing some various DLLs, however just to confirm - would `document.cookie` allow me to access `HttpOnly` cookies?

**Comment by geekzsp** [comment]
The same question. How to readto read the `HttpOnly`cookie?

**Comment by r0x0r** [comment]
Sorry HttpOnly cookies cannot be obviously accessed via Javascript. This however could be implemented in Python at least for some platforms.
What is the use case for HttpOnly cookies?

**Comment by ThatOtherAndrew** [comment]
In my case, it's for authentication - however I can see many other cases where the option would be very useful. For example, if you want to start with a clean environment for a specific server, or persist some active session.

**Comment by r0x0r** [comment]
@ThatOtherAndrew I have implemented `window.get_cookies()` method. It returns a list of Python's built-in SimpleCookies. The change is pushed into the 4.0 branch

**Comment by ThatOtherAndrew** [comment]
> @ThatOtherAndrew I have implemented `window.get_cookies()` method. It returns a list of Python's built-in SimpleCookies. The change is pushed into the 4.0 branch

Incredible, thank you so much!

**Comment by ReAlberto24** [comment]
window.get_cookies() Is giving ''KeyError: 'master'" error

**Comment by peng0928** [comment]
Version: pywebview==5.1
Question:  window.get_cookies()
Error: 
[pywebview] 'type' object is not subscriptable
Traceback (most recent call last):
  File "D:\python3.7.7\lib\site-packages\webview\platforms\edgechromium.py", line 124, in _parse_cookies
    cookie = create_cookie(data)
  File "D:\python3.7.7\lib\site-packages\webview\util.py", line 109, in create_cookie
    cookie = SimpleCookie[str]()
TypeError: 'type' object is not subscriptable
[pywebview] 'type' object is not subscriptable
Solved: I hope the author optimizes it early
from webview import util


# 猴子补丁
def create_cookie(input_: dict) -> SimpleCookie:
    if isinstance(input_, dict):
        cookie = SimpleCookie()
        name = input_['name']
        cookie[name] = input_['value']
        cookie[name]['path'] = input_['path']
        cookie[name]['domain'] = input_['domain']
        cookie[name]['expires'] = input_['expires']
        cookie[name]['secure'] = input_['secure']
        cookie[name]['httponly'] = input_['httponly']

        if sys.version_info.major >= 3 and sys.version_info.minor >= 8:
            cookie[name]['samesite'] = input_.get('samesite')

        return cookie

    if isinstance(input_, str):
        return SimpleCookie(input_)

    raise WebViewException('Unknown input to create_cookie')


util.create_cookie = create_cookie
![image](https://github.com/r0x0r/pywebview/assets/84308519/859b1dae-1a10-4293-b6d6-aa337157bce6)
