### ISSUE TITLE
Customize about window

### ISSUE THREAD

**Issue by rocchidavide** [r0x0r/pywebview#672]
Is it possible to customize about window? I mean the window that can be opened with `cmd` + `;` shortcut

Thank you :)

**Comment by r0x0r** [comment]
No, that's not possible.
 
I have been thinking about making a native window object (NSWindow, System.Windows.Form etc) visible through a `Window` object. Not sure if  an about window can be implemented this way, but at least it will pave a way for custom logic.

**Comment by rocchidavide** [comment]
Neither the version? I see that is set as 0.0.0

**Comment by r0x0r** [comment]
What is your platform?

**Comment by rocchidavide** [comment]
I use both MacOS and Windows

**Comment by r0x0r** [comment]
Version support could be incorporated into pywebview. I have no clue what it would take and what API should be used, so help is welcomed. 
First thing that should be looked into is whether version info could be injected via pyinstaller or such.

**Comment by Ksengine** [comment]
> Is it possible to customize about window? I mean the window that can be opened with `cmd` + `;` shortcut
> 
> Thank you :)

please Explain more.
