### ISSUE TITLE
Feature request: Parameter maxWidth, maxHeight

### ISSUE THREAD

**Issue by bascurtiz** [r0x0r/pywebview#675]
### Specification
- pywebview version: 3.4
- platform / version: Linux, macOS, Windows

### Description  
  
This isn't a bug, but more like a missing feature. 
Like electron has a bunch of parameters to control the window, I esp. miss the maxWidth parameter.
See: https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions

Scenario:
```
window = webview.create_window(
        height=725,
        width=400,
        min_size=(400, 725),
```
Someone using my app on low resolution (1366x768), will see it perfect.
Now users with high resolution (1080 and up for ex.) want to show it somewhat bigger:
```
window = webview.create_window(
        height=925,
        width=400,
        min_size=(400, 925),
```

So I'm willing to make the content responsive, based on `@media screen (max-height: 726px) `
but when using `resize = True`, it gets maximized over the whole screen.
I want to only let it grow in height.

`max_size` parameter would be a great addition!
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Good suggestion. Pull request is welcomed.
