### ISSUE TITLE
Right-click context menu not showing up on Windows 

### ISSUE THREAD

**Issue by bascurtiz** [r0x0r/pywebview#676]
### Specification
- pywebview 3
- platform / version: Windows 10 / 1909 & 2004 64-bit

### Description  
  
When running, as shown here, https://pywebview.flowrl.com/guide/debugging.html :

    webview.create_window('Example', 'https://pywebview.flowrl.com/hello')
    webview.start(debug=True)
    
I can right-click what I want , but the contextmenu (with reload option) is not showing up.
On macOS it does.

I looked into https://github.com/r0x0r/pywebview/issues/170 but if i read it correctly,
`IsWebBrowserContextMenuEnabled` is enabled when `debug` is set to `true` for `start`.

Why I need the right-click menu is to get the user to click Reload, cause I have issues with cache displaying instead.

Tried with:

    app.config['TEMPLATES_AUTO_RELOAD'] = True

    app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0
  
which helps when going to `localhost:12345` to show my `index.html` in a local browser,
but within the pywebview it's not updating.

Sure, I can use DevEdge Tool to `location.reload()` but I can't ask that  users, who already used the app, and don't see the updated css, html, js.

On Windows 10, when I set it to `webview.start(debug=True, gui='cef')` it does show the right-click context menu.
On macOS it shows Reload in any case either using `cef` or not, `debug=False` or `True`.
On Windows 7 it does show the right-click contextmenu, when `debug=True`.

**Comment by r0x0r** [comment]
What renderer is your problem with?

**Comment by bascurtiz** [comment]
I found the solution here, I guess.
By forcing it to use `gui='mshtml'` instead of leaving it non-specified (which if i read it correctly, should just use `mshtml` by default).

It now shows [this](https://i.imgur.com/PIoAfUM.png) renderer.
Before, without that specification, it showed [that](https://i.imgur.com/gmd3poM.png) renderer.

**Comment by r0x0r** [comment]
Windows has three renderers: Chromium (latest and greatest), EdgeHTML and MSHTML (IE11).
Renderer is automatically chosen starting from Chromium and defaulting to MSHTML.

Your case defaults to EdgeHTML, which is buggy af and by all account is rather a misnomer.  If you are ok with IE11, then go for it, otherwise I would suggest using Chromium. You need to install a separate binary for that. Instructions can be found here https://pywebview.flowrl.com/guide/renderer.html

**Comment by bascurtiz** [comment]
Thanks! That explains it all. Consider issue closed.
