### ISSUE TITLE
Catching errors when using js_api

### ISSUE THREAD

**Issue by aran159** [r0x0r/pywebview#677]
### Specification
- pywebview version: 3.4
- platform / version: Windows

### Description  

I am using a custom `Api() ` class to communicate Javascript withPython. My problem is any error/exception won't show in the Python terminal. I can see the python error in the Chromium console, but I'd like to catch it in the terminal also.

This is the code:
```
if __name__ == '__main__':

    api = Api()
    window = webview.create_window('Wear Indicator Tool',
                                   url="web/conexion.html",
                                   js_api=api,
                                   resizable=True,
                                   min_size=(1200, 800),
                                   )
    webview.start(debug=True)
```

I believe the issue has to do more with threading than with pywebview, but I'm unable to solve it.

- https://bugs.python.org/issue36666

Any help is greatly appreciated.

**Comment by r0x0r** [comment]
Yeah, this is a threading problem. You can wrap your threading code in try .. except, display an exception and rethrow an exception if needed.

**Comment by aran159** [comment]
Thank you for the solution, it works. However, having to do this with every method of the api is not very clean. Is there another way to spread the error?

Using pywebview 2.4 (create_window started the GUI loop) the exceptions where logged in the main thread too.

**Comment by r0x0r** [comment]
@aran159 I have no clue unfortunately.
I did not realize it had been different with 2.x.  There is probably something that can be done about that, as Windows threading model is quite flexible.

**Comment by aran159** [comment]
No problem, thank you!
