### ISSUE TITLE
[pywebview] Error occurred while evaluating function 

### ISSUE THREAD

**Issue by 7R3** [r0x0r/pywebview#678]
### Specification
- pywebview version:  Version: 3.4
- platform / version: 5.20.4
Operating System: Manjaro Linux 

### Description  

JavaScript API

        $(document).ready(function () {
            $("#formChave").submit(function (event) { 
                var user = $('.paramA').val();
                var passWord = $('.paramB').val();  

                pywebview.api.chave_insta_Open(paramA,paramB);  

                event.preventDefault();
            }); 
        });

**Result**
  
[pywebview] Error occurred while evaluating function chave_insta_Open
Traceback (most recent call last):
  File "/home/trace/.local/lib/python3.8/site-packages/webview/**util.py**", **line 160**, in js_bridge_call
    param if not param else json.loads(param)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

  
### Practicalities

**I accessed the util.py file on line 160 and found this code snippet.**

       try:
            func_params = param if not param else json.loads(param)
            t = Thread(target=_call)
            t.start()
        except Exception:
            logger.exception('Error occurred while evaluating function {0}'.format(func_name))

I made a change and added **param = json.dumps (param)**
The error stopped happening. Is this change correct?
This is the code.

       try:
            param = json.dumps(param)
            func_params = param if not param else json.loads(param)
            t = Thread(target=_call)
            t.start()
        except Exception:
            logger.exception('Error occurred while evaluating function {0}'.format(func_name))

**Comment by r0x0r** [comment]
Can you run `examples\js_api.py`?
What does your chave_insta_Open function signature looks like?
Is this GTK or QT?

**Comment by 7R3** [comment]
test js_api.py without and with the line of code.

        param = json.dumps(param)


https://user-images.githubusercontent.com/76504901/102991392-7b36e600-44ef-11eb-9184-b794bd53f567.mp4

**Comment by Ksengine** [comment]
@7R3 format your code samples and error logs
```js
    $(document).ready(function () {
        $("#formChave").submit(function (event) { 
            var user = $('.paramA').val();
            var passWord = $('.paramB').val();  

            pywebview.api.chave_insta_Open(paramA,paramB);  

            event.preventDefault();
        }); 
    });
```
```python
[pywebview] Error occurred while evaluating function chave_insta_Open
Traceback (most recent call last):
File "/home/trace/.local/lib/python3.8/site-packages/webview/util.py", line 160, in js_bridge_call
param if not param else json.loads(param)
File "/usr/lib/python3.8/json/init.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```
```python
   try:
        func_params = param if not param else json.loads(param)
        t = Thread(target=_call)
        t.start()
    except Exception:
        logger.exception('Error occurred while evaluating function {0}'.format(func_name))
```

**Comment by Ksengine** [comment]
```python
   try:
        print(param)
        param = json.dumps(param)
        func_params = param if not param else json.loads(param)
        t = Thread(target=_call)
        t.start()
    except Exception:
        logger.exception('Error occurred while evaluating function {0}'.format(func_name))
```

Try this code in util.py and show me the log.

**Comment by 7R3** [comment]
I added json.dumps to the util.py file to resolve the error. See the result.
I solved my error with json.dumps.
I wonder if my approach is correct?


https://user-images.githubusercontent.com/76504901/103258653-62ee1d80-496c-11eb-891e-cbe0cf16b18e.mp4

**Comment by Ksengine** [comment]
# The Solution
the code in `util.py` should be
```python
   try:
        func_params = param
        t = Thread(target=_call)
        t.start()
    except Exception:
        logger.exception('Error occurred while evaluating function {0}'.format(func_name))
```

I had not tested it.

**Comment by Ksengine** [comment]
@7R3  please make a pull request after some tests.
