### ISSUE TITLE
Cmd-tab doesn't work for command-line app

### ISSUE THREAD

**Issue by ericmjl** [r0x0r/pywebview#68]
Hi @r0x0r, before I go on, just wanted to say a big thanks for putting out pywebview! I've used it to successfully build a [small Flask app](http://github.com/ericmjl/imgdisplay), and the documentation and examples were excellent in helping me get started.

I have a question, though I'm not quite sure whether it belongs under pywebview or under PyObjC. I made a few observations interacting with my app:

- When I launch my app from the command line, I cannot command-tab into the app.
- With Exposé (on macOS Sierra, at least), when I switch away from my app into any other app, and then try to use Exposé to get back in, the focus does not return to my app. I have to first switch to Terminal before I can use Exposé to focus on my app.

Is this normal behaviour, or might I be doing something incorrectly? It's not causing me big problems right now, so if you're too busy to respond then no worries.

**Comment by ericmjl** [comment]
It doesn't, as I'm using the Anaconda distribution of Python, and use conda environments rather than virtualenv environments. However, this behaviour is happening without activating a conda environment as well. If it helps, `imgdisplay` is available via pip: `pip install imgdisplay`, and then it is runnable from any directory using the command `$ imgdisplay`.

**Comment by r0x0r** [comment]
I could not reproduce this when installed from pip.
https://goo.gl/photos/HwQam5Bw5FQ72nvQ8

There is a separate issue #66 that deals with a keyboard focus problem under virtualenv. It sounds like it might be related to this.

**Comment by ericmjl** [comment]
Hmm... it definitely looks related to that. I'm hoping to try out your system configuration - what Python are you using? Is it the one bundled with macOS, or is it an externally-installed version?

**Comment by r0x0r** [comment]
I am using Python 3.5.1 installed from homebrew. No oth

**Comment by r0x0r** [comment]
See https://github.com/r0x0r/pywebview/issues/66#issuecomment-272528313 for the resolution
