### ISSUE TITLE
Disable CORS

### ISSUE THREAD

**Issue by x011** [r0x0r/pywebview#680]
Hi,
Is it possible to disable CORS.? If so, how can this be done?
Thank you.

**Comment by r0x0r** [comment]
CORS can be possibly disabled on per individual web render basis but your mileage may vary. A sure proof solution would be make XHR requests in Python and access them via JS API.

**Comment by x011** [comment]
Ok, that's also an option , thank you.

**Comment by zishenWang** [comment]
is there a option for developer to disable CORS in the render process like [Electron](https://stackoverflow.com/questions/30101537/cross-domain-ajax-call-in-atom-shell)？
`var BrowserWindow = require('browser-window');`
`var win = new BrowserWindow({
  webPreferences: { webSecurity: false }
});`
although we can sent request in python runtime, but sometime we need to do this in js runtime. @r0x0r

**Comment by r0x0r** [comment]
You can disable web security (including CORS) at least for CEF.  IE.

```
from webview.platforms.cef import settings
settings.update({
    'disable_web_security': True
})
```
