### ISSUE TITLE
PyQt4 installable?

### ISSUE THREAD

**Issue by astronouth7303** [r0x0r/pywebview#69]
For some reason, `pip install PyQt4` is failing for me, but `PyQt5` is still working. Is `PyQt4` obsolete now?

**Comment by carlosperate** [comment]
I haven't really used PyQt4, but PyQt5 has only being available in PyPI recently. So I would assume PyQt4 was never available through pip, you would have to install it using the installers available for your OS.

**Comment by astronouth7303** [comment]
Oh, excuse me. Like pywin32, pyqt4 is registered in pypi, but there are no downloadables.

The PyQt5 modules are available, but this doesn't include the QT libraries themselves.

So I think PyQt5 would be the preferred method for venvs on linux.

**Comment by r0x0r** [comment]
As a resolution, I will remove pyqt4 from setup.py and add a note to README. What do you think?

**Comment by astronouth7303** [comment]
Sounds good.

**Comment by r0x0r** [comment]
Resolved in 1.4
