### ISSUE TITLE
Programmatically does not close PyWebview running GTK

### ISSUE THREAD

**Issue by aug2uag** [r0x0r/pywebview#690]
### Specification
- pywebview version: 3.4
- platform / version: Ubuntu 20LTS and OSX Catalina 10.15.7

### Description  
  
I have a shutdown button on the application. Previously running QT the following would work for shutdown:

```python
def shutdown():
    utils.kill_other_processes()
    time.sleep(0.5)
    os._exit(0)
```

Since switching to GTK this procedure no longer works. I tried to `destroy` as follows:

```python
def shutdown():
    from app import window
    window.destroy()
    utils.kill_other_processes()
    time.sleep(0.5)
```

It raises the following warning:

`PyObjC: Exception during dealloc of proxy: Completion handler passed to -[BrowserDelegate webView:runJavaScriptConfirmPanelWithMessage:initiatedByFrame:completionHandler:] was not called`

How would I call this delegate method with the API or is there something wrong with my procedure?

**Comment by r0x0r** [comment]
Can you run `examples/destroy_window.py`?

**Comment by aug2uag** [comment]
the examples file destroys the window-- on mine, window is destroyed with qt no problem, gtk raises the pyObjC message

the examples creates a hang on same machine that can't close gtk though, program doesn't end with SIGINT

```
% python deswindow.py 
Destroying window..
Destroyed!
^C^C

^C^C^C




```

**Comment by r0x0r** [comment]
I could not reproduce it with `destroy_window` either on macOS or Ubuntu/GTK. 
GTK problems sound like a myriad of other threading problems with GTK here, which are probably caused by an old/buggy version of GTK.

**Comment by PlumpMath** [comment]
Me too... I can't close the window.
MacOS monterey intel
How can I get back to the terminal console?
