### ISSUE TITLE
Using create_window with hidden=True makes the show() command not work

### ISSUE THREAD

**Issue by semaj4712** [r0x0r/pywebview#692]
### Specification
- pywebview version: pywebview-3.4
- platform / version: python-3.8.7

### Description  
  
  Using create_window with hidden=True makes the show() command not work.
  `gui = webview.create_window('load', 'gui/views/load.html', resizable=False, frameless=True, easy_drag=True, background_color='#222', hidden=True)
  gui.loaded += onLoad
  webview.start(http_server=True)

  def onLoad():
        gui.loaded -= onLoad
        gui.show()`

It will hang on gui.show() and eventually give the error [pywebview] Main window failed to start
  
### Practicalities

- NO I am willing to work on this issue myself. 

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What platform?
