### ISSUE TITLE
"Cannot read property" error on Windows but not on macOS

### ISSUE THREAD

**Issue by pauldev20** [r0x0r/pywebview#693]
### Specification
- pywebview version: 3.4
- platform / version: Windows 10

### Description  
  
I am trying to access the Discord OAuth2 login page via pywebview. On macOS it works without any problem. But on Windows 10 I get these errors from devtools:
![unknown-1](https://user-images.githubusercontent.com/25722176/106968198-ac3e4380-6748-11eb-9190-40b410467dc9.png)

Is there any solution for this?
Thanks in advance.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What web renderer is used? You can determine the used renderer by setting "PYWEBVIEW_LOG=debug" environment variable

**Comment by pauldev20** [comment]
How should I set the environment variable? Because I tried setting it with:
```python
os.environ['PYWEBVIEW_LOG'] = 'debug'
```
But it didn't change anything and I didn't see which renderer was used. Was this the wrong way to set the environment variable?

**Comment by r0x0r** [comment]
Google for how to set environment variables for Powershell or cmd.exe.
Alternatively point your URL to https://pywebview.flowrl.com/hello and check for UA string.
