### ISSUE TITLE
Per-window localization

### ISSUE THREAD

**Issue by Fizzadar** [r0x0r/pywebview#697]
### Description  
  
Customize the `localization` dictionary on a per-window basis; for example a custom "You have unsaved changes, are you sure you wish to close the window" kinda thing specifically for a settings window. Currently can easily override the defaults but it'd be nice to have per-window API support. Can look into this myself if pro the idea :)
  
### Practicalities

- YES I am willing to work on this issue myself.
- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I don't see a reason why not. Should be a `localization` parameter to `create_window` with its taking precedence over the global localization?

**Comment by Fizzadar** [comment]
Also  thought the same, hoping to get a chance to look at this over the weekend!

**Comment by Fizzadar** [comment]
Not stale, just not had any time to look at this yet but is on my todo list!

**Comment by Fizzadar** [comment]
Not stale, draft PR in progress now! https://github.com/r0x0r/pywebview/pull/726
