### ISSUE TITLE
[Cocoa] cmd+w bypasses exit confirmation dialogue

### ISSUE THREAD

**Issue by Fizzadar** [r0x0r/pywebview#698]
### Specification
- pywebview version: 3.4
- operating system: MacOS
- web renderer: cocoa

### Description  
  
The `cmd + w` window close ignores any `confirm_exit` value - totally my bad I believe the fix is to use `window.performClose` rather than just `close` which [skips the `windowShouldClose` check](https://developer.apple.com/documentation/appkit/nswindow/1419662-close). Will PR a fix!

### Practicalities

- YES I am willing to work on this issue myself.
- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Please go ahead
