### ISSUE TITLE
Vertical scrollbar is always visible in PyQT4

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#7]
When using QT4 vertical scrollbar is always present, no matter how big viewport is. Screenshot attached.

![screenshot from 2015-10-06 23 26 13](https://cloud.githubusercontent.com/assets/1549657/10321531/ef1ce390-6c81-11e5-9a80-b73c7987143e.png)

**Comment by lrusnac** [comment]
unfortunately I don't have a linux machine at the moment to test it but it seams like it's enough to add a line at the 75th line in the qt.py `self.view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)`

**Comment by r0x0r** [comment]
The QWebView does not have this method. A proper way to set a scrollbar for QWebView seems to be         self.view.page().mainFrame().setScrollBarPolicy(QtCore.Qt.Vertical, QtCore.Qt.ScrollBarAsNeeded). It did not help either and ScrollBarAsNeeded is a default behaviour anyway.

However the problem seems to be with the way how QT renders www.google.com. The examples/index.html is displayed without a vertical scrollbar for that matter. I will close this issue now.
