### ISSUE TITLE
Help needed! Vote pywebview into the awesome-python curated list

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#70]
If you think pywebview is a cool library and deservers more exposure, please vote for pywebview to be added to  the [awesome-python](https://github.com/vinta/awesome-python) curated list

Vote here https://github.com/vinta/awesome-python/pull/810

**Comment by shivaprsdv** [comment]
Just did the 20th 👍 vote. Cheers! 🥂 

Great project btw. Very much interested.

**Comment by r0x0r** [comment]
Yes we did it! Thanks to everyone who has voted.
