### ISSUE TITLE
Request: Cross-platform access to screen frame rectangle/size

### ISSUE THREAD

**Issue by shepazon** [r0x0r/pywebview#702]
### Specification
- pywebview version: 3.4
- operating system: macOS
- web renderer: WebKit

### Description  
  
In order to aid in positioning windows, it would be useful to have information about the geometry of the screen (or, better, all the screens, if there are multiple, but I'd settle for just the "main" screen). For just the main screen, just width and height is enough, but for multiple you'd need the frame rectangle of each display in order to understand how to place the window where you want it on a given screen.

My use case: I want to position my window at the top-left corner of the main screen. I can do that for Mac by using PyObjC, but then I'm not able to run on Linux or Windows, which I'm trying to be able to do. Since PyWebView already deals with the various platforms' runtimes, it should be able to relatively easily get this information and expose it.

For just width and height of the main screen, could be done using a `webview.screen_size` tuple. For multiple screens, `webview.screens[0]` being the main screen, and subsequent objects for added screens. Each of these would be either a tuple or a rectangle object of some form. Wonderful :)
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

Unfortunately, I can't at this time due to time constraints.

- YES/NO I am prepared to support this issue financially.

Yep, I think that could be arranged.

**Comment by shepazon** [comment]
Actually, another option would be to simply make it so you could use negative numbers for the `x` and `y` parameters to specify the position of the window relative to the bottom-right of the screen instead of the top-left. Or mix and match. Like (40, -40) to put the window 40 pixels from the left edge and 40 from the bottom.

Then you don't need to do any fussing with adding a bunch of new API for getting screen sizes, at least for the use case of wanting to position a window relative to the other edges of the screen.

There are a lot of interesting things you could do going beyond this, like accepting percentages instead of pixel values for position and size information, but that's another issue perhaps. :)

(FWIW, even if things like this won't come to BitBar but I hope they get thought about for the new project)

**Comment by r0x0r** [comment]
Good suggestion. I would go with `webview.screens` that would contain a list of tuples (width, height). screens[0] would always point to the main screen (if applicable). I am not fond of using negative numbers, at least not at this point. 

Some considerations. GUI library is not determined until `webview.start` is called. In order for `webview.screens` to work before `start`, GUI library detection logic should be applied to screens as well. To make the matter more complicated, we cannot take the `gui` parameter of the `start` method into account, only `PYWEBVIEW_GUI`  environment variable. I reckon it is not a big deal and would matter only Linux systems and for these case it should just try whatever is available.

If you are willing to sponsor this issue, I can give it a go in the near future.

**Comment by shepazon** [comment]
One thought is that if there's even the slightest chance other information about the screens may be wanted in the future, it would be worth calling this something like `webview.screenSizes` in order to allow a `screens` property to be used later to provide more detailed information. Just a thought on that.

Any guess how much time it would take to implement? It feels like it should be "easy" for the usual hand-wavy "I know enough to guess but not enough to guess accurately" kind of way these things usually get figured. :)

**Comment by r0x0r** [comment]
This is a valid concern. I think the best approach would be `window.screens` with Screen class object. The screen object would have only `width` and `height` for now. 

My guesstimation for work load is 5 hours. It seems mostly straightforward apart from the GUI toolkit logic. Also it would be nice if `webview.screens` would be property like, ie it would not be evaluated until called. Vanilla Python cannot do that, but there are 3rd party libraries for that. Suggestions on how to tackle this are welcomed.

**Comment by shepazon** [comment]
@r0x0r LMK what's involved in sponsoring this. I have not done this before in the past, so I don't know what the best practices are, or what you ask for, or whatever. I don't even know exactly what to ask. :)

**Comment by shepazon** [comment]
@r0x0r I'm tentatively game to go for that, as long as it's not open-ended. I can manage 5 hours or so, but if it goes significantly over, that'd be an issue. :)

**Comment by r0x0r** [comment]
@shepazon Do not worry about overtime. Let's agree on five hours, the rest is on me. I have submitted an expense to opencollective here and will start working on it tomorrow.

https://opencollective.com/pywebview/expenses/36088

**Comment by shepazon** [comment]
@r0x0r FWIW, I don't know how (and when) to go about contributing the money needed, so if you can tell me I would appreciate it. I'd expected to find a way to just click on an expense and offer to pay some or all of it, but that doesn't seem to be there.

**Comment by r0x0r** [comment]
@shepazon PR here https://github.com/r0x0r/pywebview/pull/711
Please test.
 
As for the payment, just donate this amount to the collective here https://opencollective.com/pywebview/donate

**Comment by r0x0r** [comment]
PR merged.
@shepazon you can donate the agreed amount to the collective now.

**Comment by r0x0r** [comment]
Thanks for sponsoring this @shepazon 
I will make a new release with this feature soon.
