### ISSUE TITLE
Support CEFPython v66.1 / Python 3.8 & 3.9

### ISSUE THREAD

**Issue by jgentil** [r0x0r/pywebview#703]
It looks like CEFPython released support for Python 3.8 and 3.9 in their [latest release](https://github.com/cztomczak/cefpython/releases/tag/v66.1).  

I'm willing to do this work myself to get it working in Windows.  @r0x0r do you have any tips or concerns?  if you want you can mark this as an enhancement request and assign it to me, and I'll get started on it.

**Comment by r0x0r** [comment]
Please go ahead. It looks like it is compatible with previous versions, so no drastic changes would be needed.

**Comment by Ksengine** [comment]
Cefpython also supports MacOS and Linux. Why only windows?

**Comment by r0x0r** [comment]
@Ksengine nobody has bothered to do cefpython gtk or macos implementations (myself included). If you could give it a go or would be much appreciated. 🙏

**Comment by Ksengine** [comment]
> @Ksengine nobody has bothered to do cefpython gtk or macos implementations (myself included). If you could give it a go or would be much appreciated.

Sorry @r0x0r. i have no macos machine or linux macine(except arm). arm is not supported.

**Comment by Ksengine** [comment]
But there are few examples included in cefpython repo.
https://github.com/cztomczak/cefpython/tree/master/examples
for gtk, qt and wxpython
