### ISSUE TITLE
`y` parameter doesn't seem to work (macOS)

### ISSUE THREAD

**Issue by shepazon** [r0x0r/pywebview#704]
### Specification
- pywebview version: 3.4
- operating system: macOS 10.15.7
- web renderer: WebKit

### Description  
  The `y` parameter does not seem to be functional. I've tried setting it to all kinds of values, and nothing works. `x` works just fine. It doesn't matter whether I set it using `webview.create_window()` or `window.move()`. It just sits at its default vertical position.

  The only way not to have the window centered vertically is to set `x` to a specific value when creating the window. Then `y` is changed to be a short distance below the menu bar on my Mac. But I still can't choose a specific value of `y`.

  Looking through the code I also just discovered you can't set just one of `x` or `y` in `create_window()`; it would be fantastic to be able to just set `y` so it would be centered horizontally but, say, positioned near the top of the screen, or whatever. Anyway...

### Practicalities

- YES/NO I am willing to work on this issue myself.
Hypothetically though I've already looked through the code and it sure looks like it ought to "just work." Any amount of complexity and it's probably beyond the scope of the time I have.

- YES/NO I am prepared to support this issue financially.

Yes, within reason. :)

**Comment by r0x0r** [comment]
I have just tested with `window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello', x=0, y=200)
` and `window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/hello', x=0, y=0)`. Both cases work as expected.

Tested with a MacBook with no external monitor attached. What is your setup?

**Comment by shepazon** [comment]
I do have an external monitor as a secondary display.

**Comment by r0x0r** [comment]
This has to do with reprojecting Cocoa coordinates (Cartesian with 0,0 at bottom-left) with computer ones (0,0 at top-left). See https://github.com/r0x0r/pywebview/blob/3a45089c85bf4c675c7488a7fc4251bd61e79ca4/webview/platforms/cocoa.py#L501

This approach seems to work with a single monitor, but in a multi-monitor setup produces weird results. I am not sure how to tackle this. Ideas are welcome.

**Comment by shepazon** [comment]
This may be something that has to be addressed in the context of the `webview.screens` array of screen information objects; if a window has both a `y` property and a `window.screen` which is a reference to one of the screens in `webview.screens`, you can then use the size information found in that along with the value of `y` to compute the actual position in top-down fashion.

--
Eric Shepherd
Sr. Developer Writer
AWS Documentation

From: Roman ***@***.***>
Reply-To: r0x0r/pywebview ***@***.***>
Date: Monday, March 22, 2021 at 4:42 PM
To: r0x0r/pywebview ***@***.***>
Cc: "Shepherd, Eric" ***@***.***>, Author ***@***.***>
Subject: Re: [r0x0r/pywebview] `y` parameter doesn't seem to work (macOS) (#704)


This has to do with reprojecting Cocoa coordinates (Cartesian with 0,0 at bottom-left) with computer ones (0,0 at top-left). See https://github.com/r0x0r/pywebview/blob/3a45089c85bf4c675c7488a7fc4251bd61e79ca4/webview/platforms/cocoa.py#L501

This approach seems to work with a single monitor, but in a multi-monitor setup produces weird results. I am not sure how to tackle this. Ideas are welcome.

**Comment by shepazon** [comment]
While the PR for the addition of `webview.screens` is working well for me in and of itself, it won't really be helpful until this issue is fixed as well. I'm hoping we can combine this with the `screens` thing... :)

**Comment by r0x0r** [comment]
I pushed a tentative fix for this. Could you give it a test?

**Comment by shepazon** [comment]
Doesn't seem to be there yet.

**Comment by shepazon** [comment]
Hang on, need to reevaluate, just realized a problem with setup that may have borked my testing.

**Comment by shepazon** [comment]
I retract my "doesn't work." It does.

**Comment by r0x0r** [comment]
Changed to `NSWindow.screen().frame()`.
This might fail when setting initial coordinates in a multi-monitor setup. I cannot see a solution now and at least it is documented here.
