### ISSUE TITLE
Pywebview & WxPython

### ISSUE THREAD

**Issue by vsvad** [r0x0r/pywebview#707]
I want to use pywebview with wxpython (`wx.html2`).
Example:
```python
import wx
import wx.html2

app = wx.App()
win = wx.Frame(title="Webview")
sizer = wx.BoxSizer(wx.VERTICAL)
bro = wx.html2.WebView()
bro.LoadURL('https://google.com')
sizer.Add(bro, 1, wx.EXPAND, 10)
win.SetSizer(sizer)
app.MainLoop()
```
Can I do it?

**Comment by r0x0r** [comment]
No, not currently. CEF could probably be integrated into WxPython, so it could be one way to do it.

**Comment by vsvad** [comment]
I meant that you can use [this](https://github.com/r0x0r/pywebview/issues/707#issue-830856170) example to implement it.

**Comment by r0x0r** [comment]
I see.
In my opinion it is like reinventing a wheel as wxPython's webview does a same thing as pywebview. If you use wxPython, why use pywebview at all?

**Comment by FI-Mihej** [comment]
@r0x0r Hi! Actually wxPython support could be big advantage in terms of licensing: it is much easier to use wxPython in a commercial code than Qt. And wxPython is three times smaller which is also not bad.
