### ISSUE TITLE
Random crashes under Linux GTK : "XInitThreads has not been called"

### ISSUE THREAD

**Issue by chezyann** [r0x0r/pywebview#708]
### Specification
- pywebview version: 3.4
- operating system: sabayon 20.10 (gentoo)
- web renderer: GTK

### Description  
Random crashes when using window.move in api calls.
In some rare times it works just fine otherwise it crashes and provide some errors (2 different error messages encountered).

**Note :** there's no crashes with QT.

mwe.py :

```
import webview
import time

class Api:
    def move(self,e):
        global window
        sleep(2)
        window.move((window.x+10)%400,window.y)

if __name__ == '__main__':
    api = Api()
    window = webview.create_window('mwe', 'mwe.html', js_api=api,  x=0, y=0)
    webview.start(debug=True)
```

mwe.html :

```
<html>
<body>
<button id="move-button">Move me</button>
</body>
</html>
<script>
    window.addEventListener('pywebviewready', function() {
      document.getElementById("move-button").onclick = pywebview.api.move;
    })
</script>
```

Error message 1 :
`Gdk-Message: 15:05:03.516: mwe.py: Fatal IO error 11 (Ressource temporairement non disponible) on X server :0.0.`

Error message 2 :
```
[xcb] Unknown sequence number while awaiting reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: /var/tmp/portage/x11-libs/libX11-1.6.12/work/libX11-1.6.12/src/xcb_io.c :297 : poll_for_response:  l'assertion « !xcb_xlib_threads_sequence_lost » a échoué.
Abandon (core dumped)
```

### Practicalities

- YES I am willing to work on this issue myself.
though I already tried
- NO I am not prepared to support this issue financially (but I'm prepared to support pywebview development)

**Comment by r0x0r** [comment]
These GTK crashes have been traced to outdated versions of GTK dependencies. I would start by checking what version of GTK libraries you have installed and whether you can update them manually. The WebKit2 version is of particular interest. Other libraries to check are python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.0

**Comment by chezyann** [comment]
Thank you for your answer !

These are our versions :
gtk : 2.24.32 & 3.24.22
webkit-gtk : 2.30.3 (tried 2.30.5 - bug persists)
gi & gi-cairo : 3.36.1
gir gtk & gir webkit : provided by gtk+-3.24.22 package

**Comment by r0x0r** [comment]
Got it reproduced.

1) I took a look at https://pygobject.readthedocs.io/en/latest/guide/threading.html and could not see anything threading wise that would be done incorrectly in pywebview code.
2) Googling for these errors produce some results and bug reports. eg https://bugs.launchpad.net/mutter/+bug/1877075 
Looks like a bug in GTK
3) There might be a workaround for this (a cleverly placed sleep or something along), but this is just a guess.
