### ISSUE TITLE
Chromium and EdgeHTML engines got removed in a Windows 10 update?

### ISSUE THREAD

**Issue by ZooLSmith** [r0x0r/pywebview#709]
### Specification
- pywebview version: 3.4
- operating system: Windows 10 20H2
- web renderer: edgechromium and edgehtml 

### Description  

it always fallback to mshtml, it'd seem both got removed after a Windows 10 update. 
.NET Framework 4.6.2 and the Edge Runtime are both installed, no changes even when forcing.

Edit: I've managed to do a workaround to get my project to work when using file://, but surely others might have the issue if they must host their web app.

**Comment by r0x0r** [comment]
If I understand correctly edgehtml was removed from 20H2. As for edgechromium, not sure why it does not work. Does reinstalling Edge Runtime help?

**Comment by ZooLSmith** [comment]
Yeah you were right, reinstalling it did help. That's very strange. Thanks for the help!

**Comment by r0x0r** [comment]
@ZooLSmith care to provide a PR that would disable EdgeHTML for 20H2 upwards?

**Comment by ZooLSmith** [comment]
I don't think there's anything to fix or disable from your wrapper as you use "what's available".

From what I understand, edgechromium and edgehtml are still present in the latest Windows 10 builds, but they behave differently than what they used to before 20H2 which made me believe pywebview had fallback to another engine, but it didn't, and was actually working as expected.

Depending on the web content you'll throw at it, it will or will not work based on what web technologies you're using for your web application. In my case with Angular I had a few tweaks to do in order to make the app able to run locally without being hosted on a server (which one of your implementations does). It wont run on MSHTML as it has less compatibility with modern web features, while more generic things will work.

I did some more tests and went to grab the variables inside platforms/winforms.py (forced_gui_, renderer, is_chromium) to check what was running and indeed edgechromium runs by default as expected, edgehtml still runs but differently it'd seem, as previously I couldn't be able to run my app on it.. but now it works.. and mshtml works but has less features as I said.

My issue seemed way too specific, I'd say it really comes down to what other developers require.
