### ISSUE TITLE
JSON Parse script error in example flask app

### ISSUE THREAD

**Issue by anasofoz** [r0x0r/pywebview#71]
![capture](https://cloud.githubusercontent.com/assets/5099764/21862683/00a89a4a-d843-11e6-85cc-cfde5a215167.PNG)
this is what I get when I run the flask_app example project, specifically when I click on a button I instantly receive this script error, if I click (yes) everything works out, but this error keeps popping up and it is annoying,I checked IE options and script error options were turned off, after following the error line, I found out it was a problem with JSON parsing.. I am not sure why this is happening.
Thanks a lot !!

**Comment by r0x0r** [comment]
What OS are you on?

**Comment by anasofoz** [comment]
windows 10 ( 64 bit) , and btw i tried running the app with internet explorer browser itself through the local server domain (i believe it is something that starts with 127) and no error messages appeared.

**Comment by r0x0r** [comment]
I managed to reproduce it. The FEATURE_BROWSER_EMULATION does not work for some reason, so it defaults the webview mode to IE7. Not sure why it happens, I will check if it works with a frozen executable.

**Comment by r0x0r** [comment]
Ignore the previous comment, there was an error in the JS code. JSON.parse produces an error in IE if the input is empty. The example is fixed now. I also instructed WinForms's WebView to ignore any script errors (for better or worse), so the error dialog should be a thing of the past.
