### ISSUE TITLE
Add warning in the documentation to avoid webview.py in scripts

### ISSUE THREAD

**Issue by twopelu** [r0x0r/pywebview#710]
### Specification
- pywebview version: 3.4
- operating system: Windows 10
- web renderer:  CEF

### Description  
  
I think it should be added a warning in the documentation in order to prevent misleading errors when naming the "Hello World" script as webview.py.

I have found that this has happened to other people  and I first though it was a problem with my installation, before realizing it was just a naming mistake.

I changed the name of the script to main.py and it worked.

**Related pages**

https://pywebview.flowrl.com/
https://pywebview.flowrl.com/guide/usage.html#basics

**Error thrown**

![image](https://user-images.githubusercontent.com/12948190/111768214-eeaa8280-88a7-11eb-9a85-a463d1602272.png)

### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
I kinda see your point, but this is more like a Python 101 issue. Anyhow at least it is documented here.
