### ISSUE TITLE
Parentheses in URL

### ISSUE THREAD

**Issue by michi927** [r0x0r/pywebview#716]
Hey,
I try to display my website in a python GUI but my URL includes parentheses 
So if i start the program it went to my "basepage" (without any information what I give in my http request) what I don´t want to do
I need the parentheses in my URL because they have sth to do with my session
I used other libraries like webkit and had the same issue
I already tested to replace the parentheses like:

(   =  %28
)   =  %29

but nothing worked

The parentheses (and their content) always are added to the URL after calling the URL (for example in the browser)

If I delete the parentheses with their content I get this error:
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/usr/lib/python3/dist-packages/thonny/plugins/cpython/cpython_backend.py", line 314, in _custom_import
    module = self._original_import(*args, **kw)
  File "/home/pi/.local/lib/python3.7/site-packages/webview/platforms/gtk.py", line 28, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no

And nothing show up in the window.

I work on a raspberry pi 4 with python 3.7 

I hope sb could help me 👍

**Comment by r0x0r** [comment]
Could you post an example URL? I have tested with a first sample url from google https://www.website.com/?utm_source=google%5BB%2B%5D&utm_medium=cpc&utm_content=google_ad(B)&utm_campaign=product and could not reproduce the problem.

**Comment by michi927** [comment]
Unfortunately I can´t because all my URLs are local URLs
I saw your URL you have postet also works without the parentheses 

I´ve tested with this: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752574(v=vs.85)?redirectedfrom=MSDN
There is an similar problem like mine but not the same. The page is loading successfully but a little something is missing like the left scrollbar or the heading. It starts with IHTMLDocument2 interface
I know thats no good or specific information for you but one thing I is that the parentheses have sth to do with my session
In the parentheses is sth like (asDEdgoiLondfF==) 
Also it is an SAP link if this helps you
