### ISSUE TITLE
Unsupported Device 

### ISSUE THREAD

**Issue by Etherll** [r0x0r/pywebview#727]
### Specification
- pywebview version: 3.4
- operating system: Windows
- web renderer: edge

### Description  
when i try to render https://play.geforcenow.com/ its sayes unsupported device for some reason its work in browser fine 
  

```py
import webview

webview.create_window('Hello world', 'https://play.geforcenow.com/')
webview.start()
```

**Comment by r0x0r** [comment]
Try setting user agent to Chrome or something 
https://pywebview.flowrl.com/examples/user_agent.html

**Comment by Etherll** [comment]
> Try setting user agent to Chrome or something
> https://pywebview.flowrl.com/examples/user_agent.html

same thing didnt work i think the problem from edge because is now supported i have change the default web browser  to chrome  (thats work fine ) but the same problem and https://www.whatismybrowser.com/ says i am uses edge

**Comment by r0x0r** [comment]
Edge becomes increasingly unsupported. I would look into Edge Chromium or CEF.

**Comment by r0x0r** [comment]
This is most likely related to the fact that setting user agent is currently not supported for EdgeHTML or EdgeChromium. See this ticket for details https://github.com/r0x0r/pywebview/issues/728
