### ISSUE TITLE
user agent is not set in windows

### ISSUE THREAD

**Issue by Kikos02** [r0x0r/pywebview#728]
### Specification
- pywebview version: 3.4
- operating system: win 10
- web renderer: 

### Description  
  
The user agent is not set in the browser : webview.start(user_agent="another useragent")
only in windows, in linux and max its working

**Comment by r0x0r** [comment]
User agent is working for MSHTML and CEF.
EdgeHTML does not support it all and EdgeChromium has got user agent support added only recently and only in a prerelease version so far. It is a hassle to use EdgeChromium prereleases, so I would wait for for a final version.

**Comment by Kikos02** [comment]
**cef** : needs codecs for mp4, webm (rebuild)
**mshtml** : not working with remote url

for **edgehtml** : this is what i found

I saw in the official documentation that there is a way how to set the headers with the navigate function 

instant of using **Navigate(Uri)** we can use the **Navigate(Uri, HttpMethod, String, IEnumerable<KeyValuePair<String,String>>)**

I am trying to map, the parameters to the python function but i didnt success so far, maybe this could be a hint or a workaround,.

`edgehtml.py`

       **clr.AddReference('System.Net.Http')

        from System.Collections.Generic import KeyValuePair,Dictionary,List,IEnumerable
        from System.ComponentModel import ISupportInitialize

        httpMethod = HttpMethod("Get")
        content = ""
        headers = Dictionary[str,str]({"User-Agent": "ok"})

        self.web_view.Navigate(url, httpMethod, content, headers)**

**Comment by jalil0seth** [comment]
I think it's a good hint, we need only to try and test it. Maybe @r0x0r can give some inputs.

**Comment by jalil0seth** [comment]
Any solution or ideas guys? How to implement the Navigate with httpMethod and headers, aa shown in the answer of @Kikos02


Navigate(Uri, HttpMethod, String, IEnumerable<KeyValuePair<String,String>>)

**Comment by r0x0r** [comment]
@Kikos02 The problem parameter is url. It must be Uri, not string. 
I fixed this issue and the page loads fine, but user agent is not changed. You can find test code in the `edgehtml-useragent` branch https://github.com/r0x0r/pywebview/compare/edgehtml-useragent?expand=1
