### ISSUE TITLE
Pywebview does not start

### ISSUE THREAD

**Issue by Kzapas** [r0x0r/pywebview#729]
Whenever I run a simple script like the one below:

`import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()`

It builds but never launches the window. No errors are thrown either. Anyone else experiencing this?

**Comment by r0x0r** [comment]
It would help if you could specify basic information like os, version and web renderer,

**Comment by SolomonLeon** [comment]
If you are trying to run pywebview on Windows 10, please try the following:
`webview.start(gui="cef", debug=True)`
The reason is here: [known issues and limitations](https://pywebview.flowrl.com/guide/renderer.html#known-issues-and-limitations)

**Comment by Kzapas** [comment]
> If you are trying to run pywebview on Windows 10, please try the following:
> `webview.start(gui="mshtml")`
> The reason is here: [known issues and limitations](https://pywebview.flowrl.com/guide/renderer.html#known-issues-and-limitations)

Thank you!
