### ISSUE TITLE
Title Bar's font-color and background-color

### ISSUE THREAD

**Issue by chrisljm** [r0x0r/pywebview#730]
Now I can set title and icon on the title bar, but i also want to change 'font-color' and 'background-color', could I do that?

**Comment by r0x0r** [comment]
No can do. Generally it is a bad practice to style window title bar.

**Comment by chrisljm** [comment]
Ok, I get it, thanks

**Comment by timonwimmer-git** [comment]
So how come there are lots of UWP apps with a colored title bar (even some made by Microsoft)?

**Comment by r0x0r** [comment]
My bad, seems like I have fallen behind Windows's best practices. 
Indeed, UWP has got this ability, while pywebview is based on Windows Forms. I reckon the best way to approach this would be just to expose WinForm's GUI objects via a window object.  This way it would give user flexibility of accessing native gui API for cases like this. Maybe something like this.

```
w = webview.create_window(...)
w.native.application # this would point to System.Windows.Forms.Application
w.native.window # this would point to System.Windows.Forms.Form
```
