### ISSUE TITLE
Loading Resource while using Dynamic HTML

### ISSUE THREAD

**Issue by vishva238** [r0x0r/pywebview#731]
Specification
- pywebview version: Latest
- operating system:Win 10
- web renderer: Chromium

Description  
  
I created an serverless application. To protect the source code I encrypted the web files in Zip
I was successfully able to load the webpage by reading html file in variable

**But The Issue is Other files are not loading while html is rendered from variable.**
This problem is not raised while using local html file

**But I need to load it from the variable and still load the local files.**

**Comment by r0x0r** [comment]
You may encode your resources inline using base64. See for example
https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html
https://stackoverflow.com/questions/26867893/converting-and-rendering-web-fonts-to-base64-keep-original-look

**Comment by vishva238** [comment]
That's good.
But Actually My problem is about protecting the source code from local storage.(Say Installation folder)

**Comment by vishva238** [comment]
The Perfect Question will be

While using html with "html=" parameter
How can I point the localhost http server to specific location.

It is not finding any files in working directory.

**Comment by vishva238** [comment]
> That's good.
> But Actually My problem is about protecting the source code from local storage.(Say Installation f

> You may encode your resources inline using base64. See for example
> https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html
> https://stackoverflow.com/questions/26867893/converting-and-rendering-web-fonts-to-base64-keep-original-look



> That's good.
> But Actually My problem is about protecting the source code from local storage.(Say Installation folder)

I have solution for this 
But the problem is in serving files.

**Comment by r0x0r** [comment]
When serving html via `load_html` or `html=''` file system is not available. You can either load resources via the base64 trick or use a http server (either a local or a remote one).

**Comment by vishva238** [comment]
Thank You So Much for the note. Base64 trial successful. I'll try in my main project and post here.

**Comment by vishva238** [comment]
Planning on AES encoding to protect source. Your hint for base64 will help a lot in that process

**Comment by vishva238** [comment]
There is a new problem.

I'm doing a get request wit parameters in html

It is perfectly working in browser

But through pywebview the parameters are not passed to the server

**Comment by r0x0r** [comment]
What do you make a get request to?

**Comment by vishva238** [comment]
> What do you make a get request to?

Dynamically Created Text content Or Text file. 
I'm using Python http.server simplehttprequesthandler

**Comment by r0x0r** [comment]
I have never thought of this use case. My guess is that CEF might block all outside ajax requests from locally loaded html. But this is just a guess, a proper investigation is needed.

**Comment by macfire** [comment]
Error received while attempting to load image using `window.load_html('<img src="my_image.png" />')`
MacOS 11.6

    Failed to load resource: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)

It appears to be a permissions issue.
https://apple.stackexchange.com/questions/361245/safari-kcferrordomaincfnetwork-error-1-on-local-html-files

(I'm not sure if this  information helps or not)
