### ISSUE TITLE
Drag area error

### ISSUE THREAD

**Issue by SolomonLeon** [r0x0r/pywebview#734]
### Specification
- pywebview version: 3.4
- operating system: windows10 1909
- web renderer: MSHTML, CEF

### MSHTML

![issue1](https://upload.cc/i1/2021/06/14/nIjYpm.png)

Translation: Script error, The call to the COM component returned the wrong HRESULT E_FAIL

Like the screenshot, when you start dragging, this error will freeze the window

### CEF

![issue2](https://upload.cc/i1/2021/06/14/JpKafe.gif)

Like the screenshot, window movement behavior is inconsistent with dragging behavior.

This may be because I modified the Scale and layout setting. [like this](https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10)

### Practicalities

- NO I am not willing to work on this issue myself now. If the issue is not fixed until July, I will try to fix it.

**Comment by r0x0r** [comment]
I could not reproduce it with MSHTML, but reproduced the CEF issue. It looks like CEF interprets coordinates differently resulting in this behaviour. If you like to investigate it, onMouseMove function in `js/drag.py` would be a good starting point.
