### ISSUE TITLE
problems with layout when minimizing window

### ISSUE THREAD

**Issue by lejovaar7** [r0x0r/pywebview#735]
### Specification
- pywebview version: pywebview==3.4
- operating system: windows 7
- web renderer: cef

### Description  

I am using a button to minimize the window. I am using minimize() method. When I minimize the window, a white border appears on the window, which only disappears when I restart the script.

Before to minimize the window:

![image](https://user-images.githubusercontent.com/26439842/121995828-3472cc00-cd6d-11eb-94c0-04cdfbc26649.png)

When i minimize the window:

![image](https://user-images.githubusercontent.com/26439842/121996079-a0edcb00-cd6d-11eb-87f7-edafd509b8b4.png)

**Comment by paulo-coutinho** [comment]
I have the same problem when open the inspector. The content go to top out of screen.

**Comment by r0x0r** [comment]
Could not reproduce with minimize_window.py.
Please provide a working stand-alone example if you want to see this fixed.
