### ISSUE TITLE
Some beginner questions and my sample for community

### ISSUE THREAD

**Issue by paulo-coutinho** [r0x0r/pywebview#736]
Hi,

After develop a sample project for the community (https://github.com/paulo-coutinho/pyinstaller-sample) and with github action build, i have some questions:

1 - There is any way to use the same "gui" folder, but without use Flask? If yes, how?
2 - I see that EdgeHTML not load local files, what it means (https://github.com/r0x0r/pywebview/blob/72a448e97e4f16a6763e65af4a517d6c5a30a324/docs/blog/pywebview3.md#edge-support)?
3 - There is any way to "ignore" edge html from auto selection but always a render that load local files?
4 - When embed the application with pyinstaller my "gui" folder is open to final user, so, there is any way to "embed" it to be protected (samples can be download here: https://github.com/paulo-coutinho/pyinstaller-sample/actions)?
5 - When i generate application with pyinstaller, windows detect it as a virus/trojan, so, there is any way to bypass it (windows binaries are generated here: https://github.com/paulo-coutinho/pyinstaller-sample/actions)?
6 - Sometimes the application start but with all white without load the content, and i need restart 2/3 times to it open and render. There is any solution for this?

Thanks.

**Comment by r0x0r** [comment]
First of all, I would recommend ditching EdgeHTML. It is a) buggy b) support dropped by Microsoft c) it won't receive any future updates. Look into EdgeChromium instead.

1. Yes. Flask is entirely optional. Check out todos app in the examples folder for serverless architecture or alternatively you can use a built-in http server for serving your files.
2. It loads up a built-in http server to mimic local file loading. Ghetto af.
3. ?
4. You may try pysintaller's onefile mode to "hide" your sources.
5. This is a problem of pyinstaller. Check for a solution with them.
6. Probably related to bugginess of EdgeHTML.

**Comment by paulo-coutinho** [comment]
Hi,

Thanks for the answers.

3. I want that pywebview never select EdgeHTML as render. There is any option to ignore/exclude this render for the list?

Thanks.

**Comment by paulo-coutinho** [comment]
Hi,

7. There is any option to use more than one class as "js_api".

Thanks.

**Comment by paulo-coutinho** [comment]
Hi,

8. Local files are not loaded when use without server in my vue application:

![image](https://user-images.githubusercontent.com/395096/122693272-902ad280-d20f-11eb-97cd-cbd3a6861923.png)

Code:

```
# window
window = webview.create_window(
    "My App",
    os.path.abspath(os.path.join("gui", "index.html")),
    js_api=api.API,
    min_size=(800, 600),
)

is_debug = True if "DEBUG" in os.environ else False

webview.start(debug=is_debug)
```

Thanks.

**Comment by r0x0r** [comment]
3. No. Renderer is chosen in this order: Chromium, Edge, IE. You can force to use a specific renderer via gui parameter though.
7 + 8: No, but you can use a helper function to merge/flatten your classes.

**Comment by paulo-coutinho** [comment]
Ok.

But what you mean with merge/flatten my classes?

**Comment by r0x0r** [comment]
https://www.google.com/search?q=python+merge+classes&oq=python+merge+classes&aqs=chrome..69i57j69i64.4091j0j7&sourceid=chrome&ie=UTF-8

**Comment by paulo-coutinho** [comment]
Ok,

I made a simple test to understand because never used it before (if anyone need if after):

```
class A(object) :
    def __init__(self, args):
        self.a = 'letter a'
        self.args = args

    def getattA(self):
        return self.a, self.args

class B(object) :
    b = 'letter b' 
    def __init__(self, args) :
        self.b_init = args

    def getattB(self):
        return self.b

C = type('C', (A,B), dict(c='c'))

api = C('test arguments')

print('attributes :', api.a,  api.args, api.b, api.c)
print('methods :', api.getattA(), api.getattB())
```

Thanks.

**Comment by paulo-coutinho** [comment]
Hi,

There is something that we can do to support inner classes like my first example?

Thanks.

**Comment by paulo-coutinho** [comment]
Hi,

I made a way to call dynamically the modules without need merge/flatten.

I put into my project and write on readme the way:
https://github.com/paulo-coutinho/pyinstaller-sample

Thanks for the help. 

My community sample is working nice now and can be extended as need by anyone.
