### ISSUE TITLE
built-in local http server not working with es6 module

### ISSUE THREAD

**Issue by frozenflow** [r0x0r/pywebview#738]
### Specification
- pywebview version: 3.4
- operating system:windows10
- web renderer: edgewebview

### Description  
  
The built-in http-server (when use `window.start(http_server=True)`)  use `mimetype.guess_type()`(in wsgi.py)  to get the Content-Type of files ,when it comes to javascript file, it returns 'text/plain'. So when use javascript as es6 module`<script type="module" src="main.js"></script>` which need a strict mimeType matching, the browers throw an error and failed to load the .js files .  when i forced the wsgi server return 'application/javascript ', it works out. so should we alter the guess_type function or must use .mjs extension for all module javascript

**Comment by r0x0r** [comment]
@AstraLuma any input on this one?

**Comment by AstraLuma** [comment]
Use a distro with a better MIME database? Use whitenoise and your own MIME mapping instead?

I think when it comes to the built-in server, you should draw some strong scope lines. Web serving options are a bottomless hole, and the wsgi option exists as an escape hatch for complex use cases.
