### ISSUE TITLE
Javascript execution order

### ISSUE THREAD

**Issue by pianoboysai** [r0x0r/pywebview#739]
### Specification
- pywebview version: 3.4
- operating system: windows
- web renderer: default

### Description  
  
```
import webview
def evaluate_js():
    result = g_window.evaluate_js(
        r"""
        try{
            var h1 = document.aaa();
        }
        catch (error) {
            //pywebview.api.error(error.message);
            window.alert(error.message);
        }
        window.alert(123);
        """
    )
    return

g_window = webview.create_window('Todos magnificos', 
            html='<script>document.write(document.location.href)</script>', js_api=api, min_size=(600, 450))
webview.start(evaluate_js)
```

Above code always shows 123 first, then shows error message, but in other browsers like Chrome or Edge will show error message first, then show 123.

### Practicalities

- YES, I am willing to work on this issue myself.

- YES, I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What web renderer?

**Comment by pianoboysai** [comment]
> What web renderer?

Hi r0x0r, as you can see the code, I don't set render parameter, so I think it uses default render in my windows 10.

**Comment by r0x0r** [comment]
There is no such a thing as default renderer for Windows. Set environment variable PYWEBVIEW_LOG=debug before launching your program to see which renderer is used.

**Comment by pianoboysai** [comment]
`[pywebview] Using WinForms / EdgeHTML`

ok, I got this.

**Comment by r0x0r** [comment]
Please take a look at EdgeChromium or CEF as a renderer. EdgeHTML is being phased out by Microsoft.
