### ISSUE TITLE
Executable size too big

### ISSUE THREAD

**Issue by juanfcocontreras** [r0x0r/pywebview#74]
Hello,

I compiled simple_browser example in Windows 10, with Anaconda distribution (Python 2.7) and latest pyinstaller and pywebview versions:

`pyinstaller -F -w simple_browser.py`

However, the executable file size is 149.724KB. Is that normal? I would like to use pywebview because electron generate huge executables, and I think that pywebview is more lightweight, am I right?

**Comment by r0x0r** [comment]
That's not normal. A typical frozen bundle size is around 10-15mb. For example, the distribution size of [Next](http://flowrl.com/next/) is 9.4mb for OSX and 10.9 for Windows.

My guess is Pyinstaller bundles unnecessary libraries. Maybe try freezing with a standard Python distribution?

**Comment by denfromufa** [comment]
Create a virtualenv or conda env, activate it and install only your
dependencies (pywebview + pyinstaller) in that environment. Then built
executable should be smaller.

**Comment by juanfcocontreras** [comment]
Thanks for your answers. I'll keep you posted when I try in a virtualenv.

By the way, I try to compile the same example in Mac, but I can't get it working, so I don't know how big was the executable.

I wasn't sure if my problem was related to pywebview or pyinstaller, so I created the issue in the pyinstaller web:

https://github.com/pyinstaller/pyinstaller/issues/2407

Have you try pywebview and anaconda distribution on OS X? If yes, did you have any issues.

**Comment by r0x0r** [comment]
Py2app did the trick for me on OSX.
It is mind-boggling how difficult producing an executable in Python is.
Took many hours to figure a configuration that would produce a working
executable on different platforms.

**Comment by r0x0r** [comment]
Is this still relevant?

**Comment by juanfcocontreras** [comment]
I hadn't time to try it yet, but please close this issue. If I have problems when I can test I'll let you know.

Thanks!
