### ISSUE TITLE
Does Pywebview support Angular ?

### ISSUE THREAD

**Issue by maycuatroi** [r0x0r/pywebview#740]
Is there any way to apply angular to build GUI in pywebview?

**Comment by r0x0r** [comment]
Sure, you can use any js library with pywebview.

**Comment by maycuatroi** [comment]
> Sure, you can use any js library with Pywebview.

I saw the serverless example, and I loved it. But I don't know how to expose javascript API when I build it with Angular TS.

**Comment by r0x0r** [comment]
Do you have troubles loading Angular or using JS API? If the latter, it is not different when using JS API in other cases, you just make calls to respective `pywebview.api` functions.
