### ISSUE TITLE
Console.info etc does not work .

### ISSUE THREAD

**Issue by Fxztam** [r0x0r/pywebview#742]
Hi, 
I am trying PyWebView **_WebView2_** on Win10 and cannot console.info, .warn, .error, etc:
https://developer.chrome.com/docs/devtools/console/log/

![PyWebView2-2021-07-05_21-12-29](https://user-images.githubusercontent.com/5808032/124511489-90fa6180-ddd6-11eb-9abf-c069238d0ed3.png)

Regards,
Friedhold

**Comment by r0x0r** [comment]
Is console.log available?
Regardless this is a feature/bug of EdgeChromium.
