### ISSUE TITLE
Window.load_html doesn't work

### ISSUE THREAD

**Issue by Priyansh2001here** [r0x0r/pywebview#743]
### Specification
- pywebview version: latest
- operating system:win10
- web renderer: default

### Description  
 I am new to pywebview and want to change html when i click on a button. For this i figured it out to use event listeners using JavaScript and then call python function to change HTML. but load_html function doesn't work. I even tried example given on docs but that too doesn't work.

  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
There is no such a thing as default renderer for Windows. Set environment variable PYWEBVIEW_LOG=debug before launching your program to see which renderer is used.

**Comment by Priyansh2001here** [comment]
well, i was unable to get which renderer i am using but 
![image](https://user-images.githubusercontent.com/57267750/125157292-c3fe7580-e187-11eb-9f67-bc6e43e4dcec.png)
according to this i guess i am using CEF
