### ISSUE TITLE
Window Webview2 transparency support

### ISSUE THREAD

**Issue by ODtian** [r0x0r/pywebview#745]
### Specification
- pywebview version: 3.4
- operating system: Windows 10
- web renderer: edge chromium

### Description  
  
  it seems easy to make the window become transparent by setting 
`webView2.DefaultBackgroundColor = System.Drawing.Color.Transparent;`
If this is supported, that'll be cool.
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Have you tested it?

**Comment by ODtian** [comment]
![图片](https://user-images.githubusercontent.com/40318251/125149023-fe0c4f00-e168-11eb-8734-5b74136ff131.png)
### Yes, I update the dll to version 1.0.902 and set the prop 
### `self.web_view.DefaultBackgroundColor = Color.Transparent`

**Comment by Timoses** [comment]
I did some research previously as I am looking for a way to display a transparent window as well and found this:

```
import sys
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtGui import *
from PyQt5 import QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtCore import *


class MyNotification(QMainWindow):

    def __init__(self):

        QMainWindow.__init__(self)

        # < Styles >
        self.background_style_css = "background-color: rgba(22, 160, 133, 100); border-radius: 4px;"
        self.close_button_style_css = """
                                        QPushButton{
                                                    background-color: none;
                                                    color: white; border-radius: 6px;
                                                    font-size: 18px;
                                                    }
                                    """
        # </ Styles >

        # < Global Settings >
        self.setFixedSize(510, 210)
        self.move(400, 30)
        # </ Global Settings >

        # < Main Style >
        self.main_back = QLabel(self)
        self.main_back.resize(500, 200)
        self.main_back.setStyleSheet(self.background_style_css)
        # </ Main Style >

        # < Text Label >
        self.text_label = QLabel(self)
        self.text_label.move(10, 5)
        self.text_label.resize(300, 100)
        self.text_label.setText("Hi YUVI, How are You ? :)")
        # < Text Label >

        # < Header Style >
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        # This Line Set Your Window Always on To
        self.setWindowFlags(Qt.SplashScreen | Qt.WindowStaysOnTopHint)
        # </ Header Style >

    def terminal_ask(self):

        while True:

            print("If you want to close this window, type stop: ")

            get_input = input()

            if get_input.lstrip().rstrip().lower() == "stop":
                self.close_window()

            else:
                print("Invalid Syntax, Try it again.")

            QApplication.processEvents()

    def close_window(self):

        self.close()
        sys.exit()


if __name__ == '__main__':

    My_Application = QApplication(sys.argv)
    MainWindow = MyNotification()
    MainWindow.show()
    MainWindow.terminal_ask()
    sys.exit(My_Application.exec_())
```
(https://stackoverflow.com/questions/47121960/python-project-text-to-screen-on-transparent-unobtrusive-overlay-box/47123665#47123665)


The line that does the trick seems to be:
```
self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
```


The result from above looks like this:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/6923843/128935751-20df9da9-c392-47d4-a975-5eb90fe0b4b8.png">

**Comment by ODtian** [comment]
> I did some research previously as I am looking for a way to display a transparent window as well and found this:
> 
> ```
> import sys
> from PyQt5.QtCore import pyqtSlot
> from PyQt5.QtGui import *
> from PyQt5 import QtCore
> from PyQt5.QtWidgets import *
> from PyQt5.QtCore import pyqtSignal
> from PyQt5.QtCore import *
> 
> 
> class MyNotification(QMainWindow):
> 
>     def __init__(self):
> 
>         QMainWindow.__init__(self)
> 
>         # < Styles >
>         self.background_style_css = "background-color: rgba(22, 160, 133, 100); border-radius: 4px;"
>         self.close_button_style_css = """
>                                         QPushButton{
>                                                     background-color: none;
>                                                     color: white; border-radius: 6px;
>                                                     font-size: 18px;
>                                                     }
>                                     """
>         # </ Styles >
> 
>         # < Global Settings >
>         self.setFixedSize(510, 210)
>         self.move(400, 30)
>         # </ Global Settings >
> 
>         # < Main Style >
>         self.main_back = QLabel(self)
>         self.main_back.resize(500, 200)
>         self.main_back.setStyleSheet(self.background_style_css)
>         # </ Main Style >
> 
>         # < Text Label >
>         self.text_label = QLabel(self)
>         self.text_label.move(10, 5)
>         self.text_label.resize(300, 100)
>         self.text_label.setText("Hi YUVI, How are You ? :)")
>         # < Text Label >
> 
>         # < Header Style >
>         self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
>         self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
> 
>         # This Line Set Your Window Always on To
>         self.setWindowFlags(Qt.SplashScreen | Qt.WindowStaysOnTopHint)
>         # </ Header Style >
> 
>     def terminal_ask(self):
> 
>         while True:
> 
>             print("If you want to close this window, type stop: ")
> 
>             get_input = input()
> 
>             if get_input.lstrip().rstrip().lower() == "stop":
>                 self.close_window()
> 
>             else:
>                 print("Invalid Syntax, Try it again.")
> 
>             QApplication.processEvents()
> 
>     def close_window(self):
> 
>         self.close()
>         sys.exit()
> 
> 
> if __name__ == '__main__':
> 
>     My_Application = QApplication(sys.argv)
>     MainWindow = MyNotification()
>     MainWindow.show()
>     MainWindow.terminal_ask()
>     sys.exit(My_Application.exec_())
> ```
> (https://stackoverflow.com/questions/47121960/python-project-text-to-screen-on-transparent-unobtrusive-overlay-box/47123665#47123665)
> 
> 
> The line that does the trick seems to be:
> ```
> self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
> ```
> 
> 
> The result from above looks like this:
> 
> <img width="747" alt="image" src="https://user-images.githubusercontent.com/6923843/128935751-20df9da9-c392-47d4-a975-5eb90fe0b4b8.png">
> 

well, pyqt dose support transparent background well, but we can't run webview 2 on it, we can use wpf, winform or winui3 to run a webview 2 through pythonnet, which the way pywebview is using.

**Comment by Timoses** [comment]
Yes, I apologize, I seem to have missed the point of this issue (and that transparency is generally already [supported by pywebview](https://github.com/r0x0r/pywebview/blob/master/webview/__init__.py#L166).
