### ISSUE TITLE
how to download file?

### ISSUE THREAD

**Issue by hexiaominitao** [r0x0r/pywebview#748]
### Specification
- pywebview version: 3.4
- operating system: mac os 11
- web renderer: webkit

### Description  
  
  I try to download .txt file from my application, but no file download.

### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
There is no straightforward way to do that. An easiest solution would be to create a link with target=_blank so it would be opened in a browser window and browser would handle the download. If you can control your links and download locations, you could build a custom solution using a save dialog with `webview.create_file_dialog` and handle the download in Python.

**Comment by Robin88818** [comment]
I have the same question

**Comment by timlib** [comment]
Please keep alive.

**Comment by MichaelSoftWare2025** [comment]
### ? I have the same question.
**What the?**

**Comment by Param-Harrison** [comment]
This issue should be reopened as there is no way to download easily with `<a download>` in pywebview.
