### ISSUE TITLE
Change windows property

### ISSUE THREAD

**Issue by FedericoDiMarzo** [r0x0r/pywebview#75]
Is there a way to change window property after it's created?

For example, I'm trying to set "resizable" parameter after window creation with no success.
An alternative would be destroying current window and opening a new one, but I can't understand how to handle that properly; thanks

**Comment by r0x0r** [comment]
You cannot change the resizable property after window is created, nor this feature is planned. I will implement toggle_fullscreen() functionality at some point, though.

**Comment by FedericoDiMarzo** [comment]
Thanks for the answer, and for the second point, is there a way to create a window after previous is destroyed? I'm using cocoa on MacOs if it worth

**Comment by r0x0r** [comment]
Just call create_window again.
