### ISSUE TITLE
Any way to uncap fps using pywebview?

### ISSUE THREAD

**Issue by BluZed** [r0x0r/pywebview#753]
### Specification
- pywebview version: 2.20
- operating system: Windows 10 64bit

### Description  
  
I just wanted to know, is there any way to uncap fps using this webview? It is capped at 60fps ( 60hz monitor )
I am new to programming so any help is welcome :D

EDIT -
Maybe tell me a way to pass flags like --diable-frame-rate-limit or --disable-gpu-vsync
My code is just taken from the Hello World example on the website 
`import webview
webview.create_window('ZK-new', 'https://link-to-a-website)
webview.start()`

**Comment by jgentil** [comment]
Well, unless you specify CEF as the framework, those flags will likely not work, as they are specific to Chrome.  

I am not sure if WebView2 bothers looking for them, and at a glance I don't see any way to specify those options or parameters.  So try CEF first.

**Comment by BluZed** [comment]
@jgentil  Okay thank you. 😊
