### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by lushythedev** [r0x0r/pywebview#761]
### Specification
- pywebview version: pywebview 3.5
- operating system: windows
- web renderer: not sure what this is, sorry. 

### Description  
  
I am trying to install pywebview https://pypi.org/project/pywebview/, which pumps out a gigantic error that I do not understand. I've tried upgrading wheel, python-dev-tools, etc etc.

Here is a link to the output: [https://hastebin.com/iyaseluliq.sql](url)
### Practicalities

- YES/NO I am willing to work on this issue myself.
No
- YES/NO I am prepared to support this issue financially.
No

**Comment by r0x0r** [comment]
Your link aint working. It would help if you provide the error log here.
