### ISSUE TITLE
Question: Is Pythonnet needed?

### ISSUE THREAD

**Issue by NostalgiaRunner** [r0x0r/pywebview#766]
### Specification
- pywebview version: 3.5
- operating system: Windows 10
- web renderer: ?

### Description  
  
  Hello,
 I'm hoping to bring a product to market in the coming months and I'm greatly appreciative of pywebview making my interface a whole lot more approachable. Despite my eventual plans to move the software to Rust because of issues I take with Python itself, I'd happily throw some money at this project after launch to help with the PC situation. How much are we talking for a new machine? However, I can't supply that funding without first launching, and one of the things preventing me from launching is pythonnet. Pythonnet is not yet ready for Python 3.9. My daily driver is Linux, so I've been using the Qt version and have coded my client in 3.9 while being blissfully unaware of the pythonnet dependency failure on Windows 10. Pythonnet tries to install regardless of picking Qt or CEF as the web renderer package for pywebview. The wiki wasn't clear on whether I could use Qt on Windows or only CEF, so I wanted to ask. Because right now Pythonnet is holding up QA, and I'll happily use whichever renderer will let me use get pywebview working on 3.9. So all that to say, can I get it at all working without pythonnet? What does pythonnet do in this project in particular?
Thank you.
 - NR
  
### Practicalities

- I don't know anything about C#.

- I can help out with funding. Though I can't probably donate more than $50, until after launch.

**Comment by r0x0r** [comment]
Yes, pythonnet is needed for rendering the actual application window and everything related to it. CEF is rendered inside that window.
However, there is a good chance that QT will work for Windows with minimum changes. I don't want to support for Qt for Windows. If you find it working though, I see no reason why it should not be enabled. Take a look at guilib.py line 96. Replace it with the following code and Qt should be enabled.

```
        if forced_gui == 'qt':
            guis = [import_qt, import_winforms]
        else:
            guis = [import_winforms, import_qt]
```

**Comment by r0x0r** [comment]
https://github.com/pythonnet/pythonnet/releases/tag/v2.5.2
pythonnet 2.5.2 seems to support Python 3.9. Have you tried it?

**Comment by NostalgiaRunner** [comment]
Thank you for the patch! I have gotten Qt for Windows working great and may just use that as it's half the ram usage of CEF. But I understand it's YMMV. But as far as 2.5.2 goes, they had a 3.9 supporting build but removed it because it failed unit tests or something. So they walked it back and just promised it in the 3.0.0 release.

**Comment by sbbosco** [comment]
@NostalgiaRunner  You can download a wheel for **pythonnet** from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet and install it using `pip install \path\to\wheel\pythonnet-2.5.2-cp39-cp39-win_amd64.whl`

I have been running **pywebview** on python 3.9 with this wheel distribution for 6 months without any issues. I think the **pythonnet** team didn't create a wheel install because of some obscure issues, but those issues do do seem to be a problem with **pywebview**.

**Comment by JT-Potato** [comment]
To anyone who needs this in the future:
Pip releases are still stuck on 2.5.2, install from their github instead. Something like this:
`pip install git+https://github.com/pythonnet/pythonnet`

Works for Python 3.10 and I assume future versions of python.
