### ISSUE TITLE
Add support for ASGI

### ISSUE THREAD

**Issue by adamlwgriffiths** [r0x0r/pywebview#768]
### Description  
  
PyWebView supports WSGI, which is the basic of most web frameworks.
A new [ASGI](https://asgi.readthedocs.io/en/latest/) standard has come out to support async frameworks in Py3+.
Eg. [Starlette](https://github.com/encode/starlette)

It should be possible to support both WSGI and ASGI protocols.

**Comment by r0x0r** [comment]
I am not familiar with ASGI myself, nor I have played any major part in implementing WSGI. If there is demand for this and somebody wants to implement and support this, then we can agree on incorporating it.
