### ISSUE TITLE
No Animation When Minimizing

### ISSUE THREAD

**Issue by KiddoV** [r0x0r/pywebview#770]
Hi there! I am new in python, and thank you for this awesome lib.
Anyway, I was trying to make a frameless window and add a custom minimize button with html/js using ``window.minimize()``. I don't see the animation that usually happens on all the windows applications.
I was wondering if it is a bug or it was built like that? And if it is, how do I add that minimize animation?
I'm on Windows 10, Py 3.9

I noted that when ``frameless=False``, I can see the animation when using ``window.minimize()``, but if it ``frameless=True``, no animation!!

Thanks,

**Comment by KiddoV** [comment]
Any update on this one?

**Comment by r0x0r** [comment]
A quick Google search reveals that this is a limitation of Windows Forms. There seems to be a solution for this problem here https://stackoverflow.com/questions/31473489/use-windows-animations-on-borderless-form

If you wish to give it a go, I will gladly accept a PR.

**Comment by KiddoV** [comment]
That was all in C# tho. IDK how to convert it to Python. Sorry!
