### ISSUE TITLE
How to Reduce Size for EXE

### ISSUE THREAD

**Issue by KiddoV** [r0x0r/pywebview#778]
Not sure if I miss anything or maybe I imported too much libraries. My exe file is always ~70mb -> ~100mb with ``pyinstaller``, although, it is just a basic ``Flask`` with ``Pywebview`` window. I tried to use the option ``upx-ignores`` (correct me if I'm wrong) to ignore some file, ex: the ``libcef.dll``, it helps reduce 10mb down.
So, I wonder if anybody have a list of files that I can ignore when export py to exe?
Or any suggestions to reduce the size of my app are welcome.
Thanks,

```py
#My dependencies
from flask import Flask, request, jsonify, send_from_directory, send_file, Response
from flask_cors import CORS
from ahk import AHK
from requests_ntlm import HttpNtlmAuth
from PIL import Image
from pystray._base import MenuItem, Menu
from json.decoder import JSONDecodeError
import os, io, sys, re, shutil, json, socket, sqlite3, base64, requests, webview, threading, time, ctypes, logging, pystray._win32
```

**Comment by r0x0r** [comment]
What renderer do you use? 
If you rely on builtin renderers, the executable size tends to be around 10-15mb. libcef adds additional 30mb. 
pyinstaller tends to bundle PyQT too if you have it installed on your system. You have to explicitly ignore i. Or even better approach would be to build in a virtual environment with only dependencies you need.
Other than that, take a look at the pyinstaller log to see what it bundles.

**Comment by KiddoV** [comment]
I only use the Windows system so I guess it is **edgehtml** on win10 and **mshtml** on win7. I never build the virtual environment before. Can I just make a list of ignore dll file because I use auto-py-to-exe, so I can save the configuration to use it later. The question is what are the name of those dll files so I can put it in the ignored list. Is it only because it bundle many renderers that make the size bigger or maybe it bundle a big library in my import list that I didn't know about?

**Comment by KiddoV** [comment]
I guess making a virtual environment is the best method for this issue.
Thanks,
