### ISSUE TITLE
window.load_html() not working

### ISSUE THREAD

**Issue by kantonia** [r0x0r/pywebview#779]
### Specification
- pywebview version: 3.5
- operating system: Windows 10 Version 20H2
- web renderer: gtk, edgechromium, cef

### Description  
  
when I use window.load_html() on my system, it dosen't work at all.
using webview.create_window(html="something") works, but window.load_html() dosen't work at all
I tried using gtk, edgechromium, cef. but it dosen't work at all
tried example code: https://pywebview.flowrl.com/examples/html_load.html
it dosen't output a error log.

sorry for my bad english

### Practicalities

None

**Comment by SimpleSamples** [comment]
Me too. I installed pywebview today and tried a few samples and everything works except for load_html. I modified the sample to be as in the following.

`import webview
import time

def load_html(window):
    print("Sleeping")
    time.sleep(5)
    print("Slept")
    # The following does not work
    window.load_html('<h1>This is dynamically loaded HTML</h1>')
    print("Dynamically loaded")

if __name__ == '__main__':
    window = webview.create_window('Load HTML Example', html='<h1>This is initial HTML</h1>')
    webview.start(load_html, window)
`

Everything works as expected except load_html does not dynamically load the new HTML.
