### ISSUE TITLE
No module named 'webview'

### ISSUE THREAD

**Issue by SpyrexDE** [r0x0r/pywebview#781]
### Specification
- pywebview version: 3.5
- operating system: Windows 10
- web renderer: default

### Description  
  
  Although I reinstalled the newest version of Python3 and reinstalled the pip package pywebview
 I always get the same error:

`>>> import webview`

`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import webview
ModuleNotFoundError: No module named 'webview'`
  
### Practicalities

- YES/**NO** I am willing to work on this issue myself.

- YES/**NO** I am prepared to support this issue financially.

**Comment by JT-Potato** [comment]
Have you tried `python -m pip`
instead? I'm not sure what's going on here but it could work

**Comment by SpyrexDE** [comment]
> Have you tried `python -m pip` instead? I'm not sure what's going on here but it could work

Thanks for the suggestion but it didn't help :/

**Comment by SpyrexDE** [comment]
There also is an error when installing now:
`   ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Spyrex\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Spyrex\\AppData\\Local\\Temp\\pip-install-27njuw6z\\pythonnet_480e4d8fca7d473c80652d78665421e4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Spyrex\\AppData\\Local\\Temp\\pip-install-27njuw6z\\pythonnet_480e4d8fca7d473c80652d78665421e4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Spyrex\AppData\Local\Temp\pip-record-i7firq78\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Spyrex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\pythonnet'
         cwd: C:\Users\Spyrex\AppData\Local\Temp\pip-install-27njuw6z\pythonnet_480e4d8fca7d473c80652d78665421e4\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Spyrex\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Spyrex\\AppData\\Local\\Temp\\pip-install-27njuw6z\\pythonnet_480e4d8fca7d473c80652d78665421e4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Spyrex\\AppData\\Local\\Temp\\pip-install-27njuw6z\\pythonnet_480e4d8fca7d473c80652d78665421e4\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Spyrex\AppData\Local\Temp\pip-record-i7firq78\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Spyrex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\pythonnet' Check the logs for full command output.`

**Comment by r0x0r** [comment]
Try lower version of Python like 3.7
