### ISSUE TITLE
Way to display 2 webviews in 1 window?

### ISSUE THREAD

**Issue by JT-Potato** [r0x0r/pywebview#784]
### Specification
- pywebview version: 3.5
- operating system: Windows 10 (21H1)
- web renderer: Edge Chromium

### Description
This is a feature request (unless it already exists and I'm not aware of it)

Could I create something split-screen, so there's remote web content (that doesn't work inside of an iframe) and on the other side, some HTML? I don't see a way to do this with pywebview, and I don't know how tricky this could be.

If anyone's familiar with Electron, something like a `BrowserView`.
  
### Practicalities

- YES/NO I am willing to work on this issue myself. (Depends on the level of complexity)

- YES/NO I am prepared to support this issue financially. (No.)

**Comment by r0x0r** [comment]
No this is not possible. pywebview has a single webview/multi window architecture. 
Two iframes is probably the best way to mimic dual webview functionality.
