### ISSUE TITLE
windows edgechromium engine `transparent = true`,Element cannot be clicked

### ISSUE THREAD

**Issue by yorunw** [r0x0r/pywebview#785]
### Specification
- pywebview version: 3.5
- operating system:windows10
- web renderer: edgechromium

### Description  
  
  When I use the edgechromium engine in Windows 10 to turn on the option of transparent = true, the buttons rendered on the page cannot be clicked. There is no problem using QT WebView under Linux
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by yorunw** [comment]
@ODtian Can you help me diagnose this problem,thanks.

**Comment by ODtian** [comment]
that's a feature in winform, you can't catch any event if you set transparent to true.

**Comment by yorunw** [comment]
> that's a feature in winform(actually more like a bug, but they write it in their doc), you can't catch any event if you set transparent to true.

那样开始窗口透明没用了，看来只有放弃这个功能了

**Comment by ODtian** [comment]
对的，支持透明的wpf启动不了webview2（是个bug），暂时没别的办法。

**Comment by yorunw** [comment]
> 对的，支持透明的wpf启动不了webview2（是个bug），暂时没别的办法。

好的，谢谢解答

**Comment by ODtian** [comment]
Good News, webview2 has been fixed and now we can launch webview2 with wpf, which means transparency is also available now.
