### ISSUE TITLE
get_current_url not work in google street view

### ISSUE THREAD

**Issue by hisashisak25** [r0x0r/pywebview#787]
### Specification
- pywebview version: 3.5
- operating system:windows10
- web renderer: default,edgechromium

### Description  
  
I set a url of google street view page as initial url in argument of webview.create_window.
My code displays the initial street view page, however "OK" and a current url of next street view page aren't printed after click direction arrow on the displayed street view page to move. My code is follows.

`import webview

def on_loaded():
    print("OK")
    gcu =  window.get_current_url()
    print(gcu)

if __name__ == '__main__':
    window = webview.create_window('Streetview URL', 'https://www.google.com/maps/@35.687365,-105.9390126,3a,75y,35.56h,89.92t/data=!3m7!1e1!3m5!1sfNKGZXp1FF6qwXH_cNSgwg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DfNKGZXp1FF6qwXH_cNSgwg%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D93.79706%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656?hl=en')
    window.loaded += on_loaded
    webview.start(gui='edgechromium')`

In this connection, setting "https://www.google.com/?hl=en' as initial url, My code prints "OK" and new url of the result of googl search. It's no problem.
And modern browsers which mean Edge,Chrome etc can display a url of current street view page in address bar after click.
I would like to get a url of current  street view page according to astreet view moving.
  
### Practicalities

none

**Comment by r0x0r** [comment]
Sor
