### ISSUE TITLE
How to stop program when close window by Alt-F4 or click X Button

### ISSUE THREAD

**Issue by thienphuoc86** [r0x0r/pywebview#793]
### Specification
- pywebview version: 3.5
- operating system: Windows 10 64b
- web renderer: 

### Description  
  
When I close the windows by Alt-F4 or click X button the python program  does not stop
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Could you close the window with `examples/simple_browser.py` ?

**Comment by thienphuoc86** [comment]
Hi r0x0r,
I tried with windows.closed attribute and it worked. Thanks!

**Comment by brainard52** [comment]
> Could you close the window with `examples/simple_browser.py` ?

I am unable to close the window with the [X] for this on macOS. I have no tested on other versions, but I'm running macOS 12.0.1 on an M1 MBP with python 3.9.7 and pywebview 3.5 installed using pip3. Command+q does kill the window, however. Additionally, the full screen and hide buttons each work.

**Comment by brainard52** [comment]
@r0x0r Does the [x] button emit a signal I could handle myself  as a workaround for now?

**Comment by BarnabasSzabolcs** [comment]
> > Could you close the window with `examples/simple_browser.py` ?
> 
> I am unable to close the window with the [X] for this on macOS. I have not tested on other versions, but I'm running macOS 12.0.1 on an M1 MBP with python 3.9.7 and pywebview 3.5 installed using pip3. Command+q does kill the window, however. Additionally, the full screen and hide buttons each work.

I also cannot close the window by clicking [x] on macOS Catilina 10.15.7 (19H2) with python 3.9 pywebview 3.5.

However, I figured that

`window.closing += lambda: api.close_window(False)`

closes the app just fine when closing the last window. 
(the webview event loop finishes and you have probably no more lines)

**Comment by edporteous** [comment]
I also have this issue on macOS Big Sur (11.6.1) with Python 3.10 pywebview 3.5.

@BarnabasSzabolcs What is `api` in your workaround? Could you provide an executable example? Thanks.

**Comment by BarnabasSzabolcs** [comment]
@edporteous I have edited my comment. I accidentally thought the api was on pywebview side :) 
But it turns out it was mine. So, I think now my comment is good. `window.closing += lambda: window.destroy()` (Here you can see my full code: https://github.com/BarnabasSzabolcs/pyquasargui )

**Comment by brainard52** [comment]
Hello, is there any information on this bug?

**Comment by BarnabasSzabolcs** [comment]
I don't think it is a bug, ```window.closing += window.destroy``` solves it, as I wrote it earlier.

**Comment by r0x0r** [comment]
This issue keeps resurfacing, so here is my take again. It is a bug in the application logic in my opinion. Ie in the original poster's code it is the application loop that prevents the program from terminating. You have to break it on window.closing, otherwise the application fails to terminate.

**Comment by brainard52** [comment]
If I remember correctly, I was able to reproduce this with a, more or less, completely empty program.

**Comment by nadaa** [comment]
Hi,
I used window.distroy, but I got an error :
 window = BrowserView.instances[uid]
[1] KeyError: 'master'

Any idea how to fix this?
Thanks
