### ISSUE TITLE
JavaScript not executing correctly

### ISSUE THREAD

**Issue by johannes-luebke** [r0x0r/pywebview#794]
### Specification
- pywebview version: 3.5
- operating system: Windows and Mac 
- web renderer: edgechromium, edgehtml, cef, mshtml, macOS

### Description  
  Using pywebview with flask and the require.js library gives an error in the Browser Console and stops require.js from working correctly.
Opening the flask localhost website from any other browser (tested Chrome, Firefox, PySide webview and the native-web-app package) works fine, without any errors.
I don't fully understand how pywebview creates its windows and renders the html, but it seems somewhere along the way it has an impact on the JavaScript execution.

Example to recreate the behaviour:
/main.py
/assets/
    └ [jquery.js](https://code.jquery.com/jquery-3.6.0.min.js)
    └ [require.js](https://requirejs.org/docs/release/2.3.6/minified/require.js)
    └ main.js
/templates/
    └ index.html

/main.py
```python
import webview
from flask import Flask
from flask import render_template

app = Flask(__name__, static_folder='assets')


@app.route('/')
def index():
    return render_template('index.html')


webview.create_window("Bug Demo", app)
webview.start(debug=True)
```
/assets/main.js
```javascript
alert("MAIN");

require(['jquery'], function ($) {
    $('#output').html('Hello World!')
})
```
/templates/index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Javascript -->
    <script data-main="{{ url_for('static', filename='main') }}"
        src="{{ url_for('static', filename='require.js') }}"></script>
</head>

<body>
    <h1>Index</h1>
    <h1 id="output"></h1>
</body>

</html>
```

Expected Behavior:
- pywebview window opens
- alert message "MAIN" appears
- "Hello World!" gets inserted by jquery

Observed Behavior:
- pywebview window opens
- alert message "MAIN" appears
- "Hello World!" **doesn't** get inserted by jquery
- Browser Console shows:
```javascript
require.js:5 
        
       Uncaught Error: Mismatched anonymous define() module: function $AMD$(){ return context[name]; }
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:5)
    at T (require.js:5)
    at Object.s [as require] (require.js:5)
    at requirejs (require.js:5)
    at main.js:3
```
- Opening webpage from other browser results in expected behavior
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
1) Do you get the same behaviour with all the renderers? 
2) Would it work if you load your script separately via a new script tag?

pywebview does not perform any special magic when it comes to handling Javascript. I don't see any reason why it would not work, except only the case if the chosen renderer is not supported by requirejs

**Comment by maartenbreddels** [comment]
I also see the same issue with requirejs. I don't observe the error outside of pywebview, only for pywebview (on OSX).
