### ISSUE TITLE
Application icon issues when freezing with Nuitka

### ISSUE THREAD

**Issue by chanchan69** [r0x0r/pywebview#802]
### Specification
- pywebview version: 3.4
- operating system: windows 10 home/pro, windows server 2012/2016/2019
- web renderer: microsoft edge

### Description  
  
  When freezing a pywebview powered program using nuitka the icon is not correctly displayed in the pywebview window. The icon which I do get is attached in case that is useful. I am sure this is a very niche usecase for pywebview and I think that a more practical solution for the issue is to add a feature to pywebview to set the window icon from a file. This way, icon support does not need to get fixed on a freezer by freezer basis. However, I am not prepared to implement this feature myself. 
  
### Practicalities

- NO I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.
![image](https://user-images.githubusercontent.com/64930470/139759960-87e8774d-c8c6-4ad7-b248-851b2dd438a5.png)

**Comment by r0x0r** [comment]
There is a PR that implements setting window icon. https://github.com/r0x0r/pywebview/pull/786
It became stale, but I hope the creator would address the review comments.
