### ISSUE TITLE
"Window closing can be cancelled by returning False from a closing event handler" not working on macOS Monterey

### ISSUE THREAD

**Issue by mve001** [r0x0r/pywebview#804]
### Specification
- pywebview version: 3.5
- operating system: macOS 12.0.1
- web renderer: WebKit

### Description  
  
On macOS Monterey, returning False in the closing event for a window does not cancel closing. The window closes anyway. 

Example:

```
import webview

def on_closing():
    return False

window = webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
window.closing += on_closing
webview.start()
```

Expected behavior:

The window should stay open.
  
### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
It works in Big Sur.  Dunno what has changed in Monterey.

The logic is in cocoa.py line 70.

**Comment by mve001** [comment]
Indeed, this seems to be the affected code:

```
if not i.confirm_close or BrowserView.display_confirmation_dialog(quit, cancel, msg):
                should_cancel = not i.closing.set()

                if should_cancel:
                    return Foundation.NO
                else:
                    return Foundation.YES
```

The behavior seems to be somewhat reversed on Monterey:

If I don't set a closing event listener, the window will always stay open when I click the close button. In this case `should_cancel = not i.closing.set()` will evaluate to `True` and `Foundation.NO`, which equals `False`, will be returned, causing the window to remain open.

If I set a closing event listener, `should_cancel = not i.closing.set()` will always evaluate to `False`, and `Foundation.YES`, which equals `True`, will be returned. It seems, whatever value I return in my `on_closing` function is completely ignored at this point.

**Comment by mve001** [comment]
UPDATE: I have now set up a machine with macOS Big Sur and the behavior is identical to Monterey:

If I use `window.closing += on_closing`, I again have to return `True` in my method to cancel closing and `False` to allow it.

I can again rectify this by changing `should_cancel = not i.closing.set()` to `should_cancel = i.closing.set()` in `cocoa.py`.

Are you sure the current build works as expected on your Big Sur machine?

**Comment by r0x0r** [comment]
This issue was fixed some time ago (https://github.com/r0x0r/pywebview/pull/769/files), but is not yet in any released versions. The fix is in the master.
