### ISSUE TITLE
Enabling copy-paste in CEF via cefpython browser_settings (proposal to make browser_settings configurable)

### ISSUE THREAD

**Issue by Rolf-MP** [r0x0r/pywebview#806]
### Specification
- pywebview version: 3.5
- operating system: win 10
- web renderer: cef

### Description  

We have been trying to make copy-paste work with pywebview/CEF (for a local application).

To cut a long story short:

1. The new asynchronous clipboard api / permissions model is not supported yet in CEF (and certainly not in v66)
    See: https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=18097
2. So we need to fall back to executeCommand('copy') and executeCommand('paste').
3. In order to make the latter work we need to pass a browser_setting `"dom_paste_disabled": False` to cefpython.
4. pywebview's cef.py does not provide this option.
5. Adding a settings to the cef.CreatBrowserSync in create_browser() in cef.py per the "isolated" code section below resolved the issue.

```
def create_browser(window, handle, alert_func):
    def _create():
        real_url = 'data:text/html,{0}'.format(window.html) if window.html else window.real_url or 'data:text/html,{0}'.format(default_html)



        browser_settings = {
            "dom_paste_disabled": False
        }
        cef_browser = cef.CreateBrowserSync(window_info=window_info, settings=browser_settings, url=real_url)



        browser = Browser(window, handle, cef_browser)

        bindings = cef.JavascriptBindings()
        bindings.SetObject('external', browser.js_bridge)
        bindings.SetFunction('alert', alert_func)

        cef_browser.SetJavascriptBindings(bindings)
        cef_browser.SetClientHandler(LoadHandler())

        instances[window.uid] = browser
        window.shown.set()

    window_info = cef.WindowInfo()
    window_info.SetAsChild(handle)
    cef.PostTask(cef.TID_UI, _create)
```

6. As there are many more relevant browser settings it seems obvious to opt for a similar construct as in place already for making the (application) `settings` and `command_line_switches` configurable.
  
### Practicalities
Put quite a bit of effort in tracking the issue down but I am not an expert in pywebview. 
Solution is proposed - would rather leave the (simple) implementation to a core contributor.

**Comment by r0x0r** [comment]
You can set CEF settings using this code snippet

```
from webview.platforms.cef import settings
settings.update({
    'dom_paste_disabled': False
})
```

Are there any drawbacks of enabling this feature? If it is a sensible one, it can be enabled by default.

**Comment by Rolf-MP** [comment]
> 
> 
> You can set CEF settings using this code snippet
> 
> ```
> from webview.platforms.cef import settings
> settings.update({
>     'dom_paste_disabled': False
> })
> ```
> 
> Are there any drawbacks of enabling this feature? If it is a sensible one, it can be enabled by default.

Thank you Roman! Will give that a try.
I do think it is a security issue to enable this by default.
It should not be an issue for local usage of a trusted webapp - but enabling it for generic online browsing would be unwise.

**Comment by Rolf-MP** [comment]
The `webview.platforms.cef import settings` gives us access to the application settings whilst the `'dom_paste_disabled': False` is a browser setting.

The suggested code actually throws an error as `dom_paste_disabled` is not a setting for the application.

The same idea could be reused to set browser specific settings actually (that was the suggested approach in the issue).

**Comment by Rolf-MP** [comment]
This flies:

1. At the top of webview/platforms/cef.py add `browser_settings = {}`:

```
import json
import logging
import os
import shutil
import sys
import webbrowser

from ctypes import windll
from functools import wraps
from uuid import uuid1
from threading import Event
from cefpython3 import cefpython as cef
from copy import copy
from time import sleep

from webview.js.css import disable_text_select
from webview.js import dom
from webview import _debug, _user_agent
from webview.util import parse_api_js, default_html, js_bridge_call


sys.excepthook = cef.ExceptHook
instances = {}

logger = logging.getLogger(__name__)

settings = {}

browser_settings = {}

command_line_switches = {}

```
2. Do the same as with `settings `and `command_line_switches` to add the `browser_settings` to `CreateBrowserSync`:

```
def create_browser(window, handle, alert_func):
    def _create():
        real_url = 'data:text/html,{0}'.format(window.html) if window.html else window.real_url or 'data:text/html,{0}'.format(default_html)
        
        default_browser_settings = {}
        all_browser_settings = dict(default_browser_settings, **browser_settings)

        cef_browser = cef.CreateBrowserSync(window_info=window_info, settings=browser_settings, url=real_url)
        browser = Browser(window, handle, cef_browser)

        bindings = cef.JavascriptBindings()
        bindings.SetObject('external', browser.js_bridge)
        bindings.SetFunction('alert', alert_func)

        cef_browser.SetJavascriptBindings(bindings)
        cef_browser.SetClientHandler(LoadHandler())

        instances[window.uid] = browser
        window.shown.set()

    window_info = cef.WindowInfo()
    window_info.SetAsChild(handle)
    cef.PostTask(cef.TID_UI, _create)
```
