### ISSUE TITLE
Frameless window is missing buttons on macOS Monterey

### ISSUE THREAD

**Issue by AlexanderWillner** [r0x0r/pywebview#807]
### Specification
- pywebview version: 3.5
- operating system: macOS 12.0.1 (21A559)
- web renderer: n/a

### Description  

It seems that frameless windows are now missing the buttons on macOS Monterey. Code:

```python
#!/usr/bin/env python3

import webview  # type: ignore


class Demo:
    """Demo for bug."""

    def main(self):
        """Run the app."""

        self.window = webview.create_window(
            title="Title",
            url=f"https://google.com",
            frameless=False,  # if True, buttons are missing on macOS 12
        )
        # needed of frameless=False, otherwise clicking on the red "x" doesn't close the app
        self.window.closing += self.closing
        webview.start(self.window)  # blocking

    def closing(self):
        """Close the app"""
        self.window.destroy()


def main():
    """Main entry point for Demo."""
    Demo().main()


if __name__ == "__main__":
    main()
```
  
### Practicalities

- MAYBE I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

#### MacOS 11 Frameless True
![macos-11-frameless-true](https://user-images.githubusercontent.com/307605/140645828-11d49e63-9f68-41a1-b1d2-5b47ea7afb50.png)

#### MacOS 12 Frameless True
![macos-12-frameless-true](https://user-images.githubusercontent.com/307605/140645847-835134d8-d9f7-480f-9419-b21b96b39bb7.png)

#### MacOS 12 Frameless False
![macos-12-frame-false](https://user-images.githubusercontent.com/307605/140645837-2552b084-47a6-488e-9112-318f5470c4d7.png)

**Comment by r0x0r** [comment]
I don't have Monterey yet.
The logic for frameless buttons is in cocoa.py lines 382-388. PR is welcomed.

**Comment by AlexanderWillner** [comment]
For reference, this would be https://github.com/r0x0r/pywebview/blob/d41dd4a01cbe02aeca143e9248eafeaf32377b28/webview/platforms/cocoa.py#L382

It might also make sense to expose the internal `self.window` reference in order to manipulate the parameters from the calling application.
