### ISSUE TITLE
When using pywebview `debug` mode on edgeHTML only console.log works and other calls fail

### ISSUE THREAD

**Issue by xylix** [r0x0r/pywebview#808]
### Specification
- pywebview version: 3.5
- operating system: Windows 10
- web renderer: edge HTML

### Description  
  
Describe your issue in details. Please provide a stand-alone code example that would demonstrate the nature of the issue.

This line here, that is run when edgehtml is used in debug mode:
https://github.com/r0x0r/pywebview/blob/d41dd4a01cbe02aeca143e9248eafeaf32377b28/webview/platforms/edgehtml.py#L149

Overrides the `window.console` object to inject a custom `window.console.log` function. As a side effect it also deletes `window.console.debug`, `window.console.warning` and other such functions.

So when running pywebview in edgehtml any calls to `console.debug` or `console.warning` will cause an error. (This error will _not_ happen when using the windows edge developer tools, presumably they override console with their own functions that happens to fix this bug.)

### Proposed solution

I would presume the line could be changed to only override the specific `window.console.log` function, e.g.:
```
self.web_view.InvokeScript('eval', ('window.console.log = (msg) => window.external.notify(JSON.stringify(["console", msg+"", ""]))',))
```
But I have no clue how to test this change.
  
### Practicalities

- MAYBE I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
An easy fix would be to add error and warning properties to the console object as well
