### ISSUE TITLE
Suggestion: Do not re-route console.log 

### ISSUE THREAD

**Issue by dmwyatt** [r0x0r/pywebview#810]
As the docs state console logging is rerouted to the python console.  I can understand the motivation for this, however as someone very used to using DevTools it is pretty inconvenient for me.

I now have to switch between two different windows...DevTools and python console...for my debugging needs. 

I propose making this behavior optional.

Thoughts? If this change is welcome, I will prepare a PR.

**Comment by r0x0r** [comment]
console.log rerouting is turned on only in debug mode. If this is not the case, then this is clearly a bug.

I see your point though. How about pywebview would do both types of logging?

**Comment by dmwyatt** [comment]
To be clear, I was referring to debug mode. No bug there.

pywebview doing both types of logging would work fine in the short term.

**Comment by zhengxiaoyao0716** [comment]
I agree to make this behavior optional, too. The browser `console` has lots of methods besides `console.log`, such as `info`, `warn` and `error`, and [this issue](https://github.com/r0x0r/pywebview/issues/808) already got the problem.

I make a polyfill temporary to avoid the problem:
``` javascript
const browserConsole = window.console;
window.addEventListener('pywebviewready', () => {
    const pywebviewConsole = window.console;
    const logMethods = ['log', 'info', 'warn', 'error']
        .map((name) => [name, (msg, ...args) => {
            pywebviewConsole.log(msg);
            browserConsole[name](msg, args);
        }]);
    window.console = { ...browserConsole, ...Object.fromEntries(logMethods) };
});
```
