### ISSUE TITLE
Use logging module instead of print for console.log

### ISSUE THREAD

**Issue by dmwyatt** [r0x0r/pywebview#813]
Python's `logging` module seems like a more natural counterpart to `console.log`.  

By using the `logging` module the developer can choose the format of log messages and whether they go to file or console.  

If I were using some python GUI framework for a user application, my UI code would be using logging just like the rest of my code so the end user would have log files they could send me and during local development I'd be able to configure logging to output to console.

As it is, I must write a python function that I can use from the JS side to send my log messages to and as someone who writes a lot of javascript it's hard to remember to be writing `pywebview.api.my_custom_logger` instead of `console.log`.

Maybe an idea is to default to using `print` but allow the developer to provide a custom function that gets called instead?

**Comment by r0x0r** [comment]
Print as console.log was a quick and dirty solution and I fully agree that it deserves an upgrade. If you would like to work on this, PR would be most welcomed. 

To summarize the changes

1. console.log should do both console.log as well as Python logging
2. print to be replaced with logging with a sensible default (print like?)
3. support for string literals and unlimited number of parameters should be added to Python logging. I think this could be achieved with some JS magic and eval.

**Comment by dmwyatt** [comment]
I'll start working on this.
