### ISSUE TITLE
GTK JS bridge fix

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#829]
GTK's JS/Python bridge is pretty much broken, as it mangles data as well as has got an upper limit on the message size. The bridge is implemented by changing document title and watching for a corresponding message on the Python side. 

A better approach could be putting a built-in http server into use. Currently the http server is fitted only for serving static files. This approach would require introducing support for POST requests. @AstraLuma any pointers on how could one add POST support to the http server?

**Comment by AstraLuma** [comment]
Stop shipping an ad-hoc just enough server and lean into the WSGI/ASGI community?

Yeah, you could relatively easily add a special handler for a special route. But at the end of the day, python already has several excellent servers--did you want to be in the business of writing another? How sure are you that the feature-constrained server that's in there will stay feature constrained?

**Comment by AstraLuma** [comment]
I don't think it was a "mistake", but I think you're running into the problem of:

* You want to minimize code you have to maintain
* You want to minimize dependencies
* You want to ship new features and improve usability

I wrote the server at the time when the first two were big and the last was non-obvious. But if the last is becoming evident, it feels more like a "pick two" situation.

And given the restrictions of `file:` sites and apparently that the js/python bridge is variably tenable, there's the argument to be made that the app framework should be revisited. Maybe take a step back and look at that more formally? (Should it be thin and low-impact? Would users be better served by a more opinionated framework? Would a python-in-the-browser tool like brython be helpful? Should this be core or a suggested add-on?)
