### ISSUE TITLE
cmd-Q and the Quit menu item seem to kill the process before cleanup on macOS with a Cocoa GUI

### ISSUE THREAD

**Issue by profittlich** [r0x0r/pywebview#841]
### Specification
- pywebview version: master
- operating system: macOS 11.6
- web renderer: default

### Description  
  
When closing the program on macOS with cmd-Q or the _Python->Quit Python_ menu entry, cleanup code does not fully run:

```
import webview
import time
import atexit

def onclosed():
	print("Shown (but not during debugging with PyCharm when pressing cmd-Q).")
	time.sleep(1.0)
	print("Not shown in Cocoa when pressing cmd-Q, shown in Qt")

def bye():
	print("Also not shown in Cocoa when pressing cmd-Q, shown in Qt")

w = webview.create_window('hello', 'https://www.duckduckgo.com')
w.closed += onclosed

atexit.register(bye)

webview.start()
```
Looks like a race between onclosed() and the Cocoa exit process.

When exiting the program by closing the window, everything works as expected.
When using PYWEBVIEW_GUI=qt, everything also works as expected.

### Practicalities

- YES I am willing to work on this issue myself (to a degree, I know nothing about Cocoa and am not prepared to dive into it).

- NO I am not prepared to support this issue financially.

**Comment by r0x0r** [comment]
Closing problem is caused by the fact that windowShouldClose is not fired for quitting application.

applicationShouldTerminate seems to be the right event to catch in this scenario
https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428642-applicationshouldterminate

There is applicationWillTerminate too, it might solve the closed problem
https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428522-applicationwillterminate

These are rather different events than window closing and closed, though. Using them for window handling logic might have unwanted side effects.

**Comment by profittlich** [comment]
This tidbit is from an (outdated) document on [Apple's developer site](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/AppArchitecture/Tasks/GracefulAppTermination.html) (emphasis mine):

> In Cocoa, all raw events requiring application termination result in the invocation of the NSApplication delegation method **applicationShouldTerminate**:. If the delegate does not implement this method, the application is terminated regardless of any unsaved documents. Moreover, quitting, logging out, restarting, or shutting down does not automatically lead to the invocation of the NSWindow delegation method **windowShouldClose**: in any of the application’s windows. This method is immediately invoked when users click the close box or choose the Close command. It is typically the place the window’s (NSWindow) delegate displays a sheet asking users if they want to save any data associated with the window. To gracefully terminate your application (assuming it has data to save) you must ensure that windowShouldClose: is invoked for each of your windows, or that the behavior commonly implemented in this method occurs elsewhere in your application.

Is this helpful?

**Comment by r0x0r** [comment]
I pushed a fix to master. `closing` on cmd+q has got its limitations, namely it is not possible to cancel window closing, nor confirmation dialog is displayed.
