### ISSUE TITLE
No attribute '_handle_current_url' in qt.py

### ISSUE THREAD

**Issue by maroc81** [r0x0r/pywebview#85]
Getting the exception:

`
  File "/usr/lib/python2.6/site-packages/webview/__init__.py", line 175, in create_window
    gui.create_window(_make_unicode(title), _transform_url(url), width, height, resizable, fullscreen, min_size, _webview_ready)
  File "/usr/lib/python2.6/site-packages/webview/qt.py", line 181, in create_window
    browser = BrowserView(title, url, width, height, resizable, fullscreen, min_size, webview_ready)
  File "/usr/lib/python2.6/site-packages/webview/qt.py", line 96, in __init__
    self.current_url_trigger.connect(self._handle_current_url)
AttributeError: 'BrowserView' object has no attribute '_handle_current_url
`

Looks like the function is incorrectly named '_handle_get_current_url' in qt.py.  I changed this to '_handle_current_url' and now it works even on an ancient python 2.6 system (CentOS 6)

**Comment by r0x0r** [comment]
Care to make a pr? Thanks
