### ISSUE TITLE
New feature request: adding event on_resize

### ISSUE THREAD

**Issue by BillBridge** [r0x0r/pywebview#851]
### Description  
  
Would it be possible to add the event: on_resize?
When the enduser resizes the pywebview window this event shall be triggered.

And do you have suggestions for other events as well of which you may think these will be of added value to pywebview?
Of course I will support this financially.
  
### Practicalities

- NO I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Yes this can be implemented. My estimate for this is 2h.

BTW I decided against `on_` events, it will be `window.events.resized` instead
https://github.com/r0x0r/pywebview/issues/845

**Comment by BillBridge** [comment]
This is OK. Hereby I confirm the financial support.
Please can you also add an example on how to use the event?
Thanks very much.

**Comment by r0x0r** [comment]
Yes will do. Examples are added for all the new features.

Should resized be fired on window minimize, maximize and restore or only if none of this event is fired? Most GUI frameworks seem to be fire both.

**Comment by BillBridge** [comment]
Yeh right. Keep these separate.

And BTW, if you think there are more usefull events to be added, just let me know and I will finance these as well.

**Comment by r0x0r** [comment]
PR here https://github.com/r0x0r/pywebview/pull/857

**Comment by r0x0r** [comment]
PR merged into master. I am preparing 3.6 now.

Expense here https://opencollective.com/pywebview/expenses/64270

**Comment by BillBridge** [comment]
> PR merged into master. I am preparing 3.6 now.
> 
> Expense here https://opencollective.com/pywebview/expenses/64270

Hi Roman,
Thanks for the implementation. I just transferred $200 to the collective.
Best regards,
Wim

**Comment by r0x0r** [comment]
3.6 released with window management events. Thanks for sponsoring this.
