### ISSUE TITLE
Through js_api  passed parameters cannot exceed 722 characters 

### ISSUE THREAD

**Issue by buff07** [r0x0r/pywebview#852]
### Specification
- Version 3.5: 
- Linux Debian bookworm :
- Firefox: 

### Description  
  
  I wrote a textarea on the front end to receive the text. After testing, when the textarea length is less than 722, the front end and the back end can be displayed normally. When the length is over 722, the front end can be normal alert, but the back end can not get the parameters.

  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Is this GTK?

**Comment by buff07** [comment]
this is my code,when the length of textarea execeed 722 ,the print(data) in index.py will not run.But it can run nomalily when the length lower 722. 
index.py:
import webview

class Api:

    def requests(self, data):
        print(data)

`if __name__ == "__main__":`
   ` api = Api()`
   ` windows = webview.create_window("test", './nav.html', js_api=api)`
    `webview.start()`

nav.html:

`<body>`
`<textarea id="data" rows="5" cols="80"></textarea>`
`<div id="response-container"></div>`
`<button onclick="commit()">Request</button>`

`<script>`
    
   ` function commit(){`
      `  var data = document.getElementById("data").value;`
        `pywebview.api.requests(data).then(getResponse)`
   ` }`
`</script>`
`</body>`
`</html>`

**Comment by r0x0r** [comment]
Add `debug=True` to start to see which renderer is used. My guess is that GTK and this is a known issue. The problem is caused by the old GTK webview and can be partly resolved by upgrading GTK dependencies. Or use QT, as GTK's JS-Python bridge is rather dodgy.
