### ISSUE TITLE
Would you consider supporting the set transparency form?

### ISSUE THREAD

**Issue by Autumn-one** [r0x0r/pywebview#853]
### Specification
- pywebview version: 3.5
- operating system: windows11
- web renderer: default

### Description  
  
Some applications want to be able to adjust the transparency of their form, but the current version does not allow you to change the transparency by setting the background color of the HTML body. Hopefully this will be added in the next version  
  
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Windows transparency had been left out as it proved to be difficult to make a web view control transparent. However, I just revisited this problem for Edge Chromium and making window transparent turned out to be easy enough. The transparent window, has still got a shadow on Windows 11 though. This is something to be resolved.

I pushed changes to master

**Comment by Autumn-one** [comment]
> 

I tried out the transparency feature.  It works well. but. After I set frameless=True, I couldn't drag the window. I used to develop applications using Electron.  Here's a suggestion. Transparent Windows are generally frameless=True .That's what it looks like now. It shows up pretty well. The problem is window dragging.  Electron can be set An HTML tag  -webkit-app-region: drag;  So you can use HTML to simulate a nice menu bar, and I thought we could use that idea

**Comment by r0x0r** [comment]
Unfortunately this is a bug in the WebView2
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1004

**Comment by grintor** [comment]
@r0x0r have you seen my transparency example [here](https://github.com/r0x0r/pywebview/issues/488#issuecomment-931719690)?

**Comment by Autumn-one** [comment]
> 

@grintor @r0x0r  I tried your code and it works hopefully the author can integrate into PyWebView

**Comment by r0x0r** [comment]
MSHTML is deprecated and I won't do any more changes to it. However, if somebody wants to integrate these changes, I will accept a PR.
