### ISSUE TITLE
How to ignore invalid certificate of the webpage?

### ISSUE THREAD

**Issue by lennylxx** [r0x0r/pywebview#855]
### Specification
- pywebview version:   3.5
- operating system: macOS 12.2
- web renderer: Safari

### Description  
  
  When opening an URL with invalid certificate (e.g. hosting a webserver with self-signed cert), the webview is blank, totally white, not showing anything.
How to ignore the invalid certificate and proceed to show the webpage? 

  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
pywebview does not support that, but this appears to be possible in macOS, if somebody wants to give this a go.

https://developer.apple.com/documentation/foundation/url_loading_system/handling_an_authentication_challenge/performing_manual_server_trust_authentication
