### ISSUE TITLE
when `debug=True` app takes too long to load updated frontend code

### ISSUE THREAD

**Issue by Hyuto** [r0x0r/pywebview#859]
### Specification
- pywebview version:  3.5
- operating system: Windows 11
- web renderer: WinForms / Chromium

### Description  
  
I am working on Vue boilerplate using parcel as bundler which you can find [here](https://github.com/Hyuto/pywebview-vue) .  When the frontend code updated app takes too long to load updated frontend code even though app is refreshed immediately (around 30-40 seconds).  I think it's because "Cache-Control" have too long `max-age` when run the app with `http_server=True`. It works fine when using external server like flask because I can disable caching myself. 

Maybe the library have it's own rules but I think it's better to disable caching when running app on debug mode so we can just refresh to see changes immediately.
  
### Practicalities

- NO I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Current built-in HTTP server is unmaintainable and will be replaced with something else. I am inching towards bottle.py.

**Comment by r0x0r** [comment]
A new bottle.py based server can be tested here https://github.com/r0x0r/pywebview/tree/bottle-server
I have added no-cache headers to the response, which should solve this issue. Would you test it out?

**Comment by Hyuto** [comment]
Thanks, I have test it out but have some errors here.

```
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
[pywebview] pythonnet cannot be loaded
Traceback (most recent call last):
  File "c:\users\wahyu setianto\desktop\github\pywebview-vue\pywebview\webview\guilib.py", line 52, in import_winforms
    import webview.platforms.winforms as guilib
  File "c:\users\wahyu setianto\desktop\github\pywebview-vue\pywebview\webview\platforms\winforms.py", line 140, in <module>
    from . import edgechromium as Chromium
  File "c:\users\wahyu setianto\desktop\github\pywebview-vue\pywebview\webview\platforms\edgechromium.py", line 19, in <module>
    from webview.serving import resolve_url
ModuleNotFoundError: No module named 'webview.serving'
Traceback (most recent call last):
  File ".\src\main.py", line 45, in <module>
    WebViewApp()
  File ".\src\main.py", line 41, in WebViewApp
    webview.start(debug=DEBUG, http_server=True)
  File "c:\users\wahyu setianto\desktop\github\pywebview-vue\pywebview\webview\__init__.py", line 129, in start
    guilib = initialize(gui)
  File "c:\users\wahyu setianto\desktop\github\pywebview-vue\pywebview\webview\guilib.py", line 102, in initialize
    raise WebViewException('You must have pythonnet installed in order to use pywebview.')
webview.util.WebViewException: You must have pythonnet installed in order to use pywebview.
```

**Comment by Hyuto** [comment]
Thanks, it work perfectly and now the app didn't  have to be refreshed to update the frontend. I think I'm using EdgeChromium because every time I run the app it log

```
[pywebview] Using WinForms / Chromium
```
