### ISSUE TITLE
Defined x and y position overrules minimized=True in create_window

### ISSUE THREAD

**Issue by BillBridge** [r0x0r/pywebview#860]
### Specification
- pywebview version:  3.6
- operating system: Windows 10
- web renderer:  cef

### Description  
  
When you define x and y values in webview.create_window, the minimized=True status will be overrules and becomes False. Shouldn't the minimized status have higher priority than x and y values?

```
import webview


def minimize(window):
    print('Window is started minimized')
    

if __name__ == '__main__':
    window = webview.create_window('Minimize window example', html='<h1>Minimize window</h1>', minimized=True,
                                   width=300, height=300, x=10, y=10)
    webview.start(minimize, window)
```

### Practicalities

- NO I am willing to work on this issue myself.

- YES I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Not sure I understood your problem correctly, but what I noticed that the window appears quickly before being minimized when both coordinates and minimized params are set. This problem is now fixed and the fix is pushed to master.
