### ISSUE TITLE
frameless Error

### ISSUE THREAD

**Issue by halou11** [r0x0r/pywebview#861]
### Specification
- pywebview version: pywebview-3.4-py3.10
- operating system: windows10 21H2
- web renderer: default

### Code
import webview
webview.create_window(None, 'https://pywebview.flowrl.com/', x = 0 , y = 0 , resizable = False , frameless = True)
webview.start()

### Description  
When the parameter frameless of create_window is True, it will cause this exception to exit.
And when the parameter x is 0, there will be obvious gaps in the x-axis of the window. When it is adjusted to a negative number, there is no such problem.

### Command Line
Python.Runtime.PythonException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value)
    Python.Runtime.PythonException.ThrowLastAsClrException()
    Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
    Python.Runtime.Dispatcher.Dispatch(Object[] args)
    __System_Threading_ThreadStartDispatcher.Invoke()
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    System.Threading.ThreadHelper.ThreadStart()

**Comment by r0x0r** [comment]
This should be fixed in pywebview 3.6.
