### ISSUE TITLE
The JS file introduced by < script type = "module" > < / script > cannot run normally

### ISSUE THREAD

**Issue by Autumn-one** [r0x0r/pywebview#862]
### Specification
- pywebview version:  3.5
- operating system: win11
- web renderer: default

### Description  
  
At present, the final code generated by the latest front-end technology will be in the form of ES module, but this is different from the traditional script introduction method. It is obviously cumbersome to start a static server. I think there should be a direct setting to support the direct introduction and operation of ES module
### Practicalities

- YES/NO I am willing to work on this issue myself.

- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
How do you propose solving this problem? both file:// and html from code have got their limitations, which cannot be overcome I am afraid.
Which http server do you find cumbersome? built-in or external?

**Comment by Autumn-one** [comment]
> 

I know chrome can address cross-domain issues by adding browser parameters   --disable-web-security --user-data-dir=D:\test
But this method has no real effect on the way type=module is introduced and it will still report other errors  
This is not to say that it would be particularly difficult to build a static service, but it would be a little easier if it could be implemented. Perhaps this suggestion is difficult to implement or is not in line with the design philosophy of the browser itself
