### ISSUE TITLE
White space appears at right and bottom side of window after minimize/restore

### ISSUE THREAD

**Issue by bastien8060** [r0x0r/pywebview#864]
### Specification
- pywebview version: 3.6.1
- operating system: Win10/11
- web renderer: CEF

### Description  
  
  related to #589 in which a white space of 16px and 38px is created. This happens, when I have enabled borderless/fullscreen

The bug only happens when I minimize the window, and re-open it up from the taskbar. I have tested both Win10/11.

I had a look at #589 where it was suggested to make an edit to the souce file of pywebview. However, my current work environment does not let me edit any dependency's source code.

I thought a pull-request should be made, where:

- webview.platforms.cef.Browser.resize checks if we are running in fullscreen/borderless

or

- we pass a flag to webview.create_window, which alters resize's behavious. This could be an extension to the API. 

I could work on the push-request myself too. What are your thoughts on this?

**Comment by bastien8060** [comment]
But all that is assuming that:
```py
def resize(self, width, height):
  webview.platforms.cef.windll.user32.SetWindowPos(self.inner_hwnd, 0, 0, 0, width - 16, height - 38, 0x0002 | 0x0004 | 0x0010)
  self.browser.NotifyMoveOrResizeStarted()
```
is the real culprit.

**Comment by r0x0r** [comment]
I have made a tentative fix for this issue here https://github.com/r0x0r/pywebview/tree/cef-resize-fix
Please test it and report if this solves the issue.

**Comment by bastien8060** [comment]
@r0x0r Hey :)

Thanks for the reply! I just tested it, but unfortunately to no avail. It is now 12px wide, according to the change you made. 

I was thinking perhaps something like this would work: 
- a ternary/if else, which checks for the property `borderless` in the `window` object (window.borderless). In case if `self.window.borderless == True`, then a variable, say `wh_diff` will be equal to 0, otherwise 12

```py
  webview.platforms.cef.windll.user32.SetWindowPos(self.inner_hwnd, 0, 0, 0, width - wh_diff, height - wh_diff, 0x0002 | 0x0004 | 0x0010)
```

**Comment by bastien8060** [comment]
I actually didn't check in the code if the `browser` class/object contains the `window` object, in a way that would let us access it with `self`. If not, then we would need to route the window object to the browser class, by expanding the api.

**Comment by r0x0r** [comment]
window object is available via `self.window`. To be honest I do not have full understanding how this logic should work. Please test your solution to see if it addresses all the edge cases.

**Comment by bastien8060** [comment]
Oh I see, thanks for the reply. I will start working on a push request monday morning! :)
