### ISSUE TITLE
Upcoming 4.0 release

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#868]
4.0 is going to be next major release with the following breaking changes

- New [bottle.py](https://bottlepy.org/docs/dev/) based built-in HTTP server. The new server can be previewed in the https://github.com/r0x0r/pywebview/tree/bottle-server branch
- Local relative URLs (eg. `src/index.html`) will be opened using the built-in http server by default. Support for local URLs will still be possible using file:// schema
- EdgeHTML support will be removed.
- Deprecated events will be removed.

Other changes planned for this release:
- Cookie / incognito support https://github.com/r0x0r/pywebview/issues/531
- GTK JS bridge fix using http server https://github.com/r0x0r/pywebview/issues/829
- TBA

To be released some time this year.

**Comment by r0x0r** [comment]
New http server and incognito mode merged into the https://github.com/r0x0r/pywebview/tree/4.0 branch

**Comment by BilityLeu** [comment]
How is the android support progressing?

**Comment by r0x0r** [comment]
Not progressing at all unfortunately.

**Comment by shirooo39** [comment]
Will there be support for Python > 3.8 coming soon?

I'm currently on 3.10 and I'm not sure how the setup will be if I install another version of Python.
I've never done that before and I've only been working with single version.

**Comment by r0x0r** [comment]
@shirooo39 support for > 3.8 is already possible by installing pythonnet 3.0

**Comment by martinlombana** [comment]
Hi, 

What is the recommended way to install the 4.0 version? 

pip install git+https://github.com/r0x0r/pywebview/tree/4.0 does not seem to work propertly.

Thanks.

**Comment by MominIqbal-1234** [comment]
https://pypi.org/project/pywebview/#history

this pywebview 4.0 version is not show in pypi.org

in this current time show 3.6.3 version

**Comment by r0x0r** [comment]
@martinlombana the correct syntax is `pip install git+https://github.com/r0x0r/pywebview@4.0`
@MominIqbal-1234 4.0 is not on pypi, as it is not released yet

**Comment by simonrob** [comment]
> @shirooo39 support for > 3.8 is already possible by installing pythonnet 3.0

Is another 3.6 series release planned before 4.0? It would be nice to have 3.6.4 with [this fix](https://github.com/r0x0r/pywebview/pull/922/files) (already merged) that adds compatibility with pythonnet 3.0.0.

**Comment by r0x0r** [comment]
@simonrob Yeah, I will release a new 3.x version before 4.0 as there are too many critical fixes.

**Comment by r0x0r** [comment]
@simonrob 3.7 is now on pypi

**Comment by GGTEC** [comment]
Can you add an easy way to change the title bar color?

**Comment by r0x0r** [comment]
@GGTEC This is not a simple task because of platform differences.

**Comment by NethercraftMC5608** [comment]
**Hey, i encountered this error when trying the 4.0 release. Any fixes?**
`/js_api/c584c2ff-7534-11ed-9e25-a26cf82fcc7f
[pywebview] WebView2 initialization failed with exception:
 Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: The specified module could not be found (0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()
`
I am using Windows 11. Thanks.

**Comment by MominIqbal-1234** [comment]
@GGTEC 

create the frame less window and create the customized title bar using html css and js

**Comment by GGTEC** [comment]
> @GGTEC 
> 
> create the frame less window and create the customized title bar using html css and js 

Yea, i make that, but the problem is when need resize the window

**Comment by MominIqbal-1234** [comment]
hi @r0x0r 
when you release stable version of webview 4.0
and please tell me why you use bottle framework  in webview 4.0 
in my option flask is best 
and please explain your option
thanks :)

**Comment by MominIqbal-1234** [comment]
@GGTEC
you try this codeimport webview


import time
def resize(window):
    print('Window size is ({0}, {1})'.format(window.width, window.height))
    time.sleep(2)
    window.resize(420, 420)
    print('Window size is ({0}, {1})'.format(window.width, window.height))



window = webview.create_window('Resize window example', html='hello world',frameless=True, width=800, height=600)
webview.start(resize, window)

#https://pywebview.flowrl.com/examples/resize_window.html

**Comment by r0x0r** [comment]
> hi @r0x0r 
> when you release stable version of webview 4.0
> and please tell me why you use bottle framework  in webview 4.0 
> in my option flask is best 
> and please explain your option
> thanks :)

It is fast, simple, single file and has no external dependencies

**Comment by GGTEC** [comment]
> 

This is good for simple resizing, nothing dynamic, I use it to maximize the window, but the problem is when it is necessary to change the monitor... or change the size of just one side, it is something complex for something 'simple'

**Comment by MominIqbal-1234** [comment]
@r0x0r
and please tell me data of stable release  webview 4.0 because i am very excited to use webview 4.0 
and thanks so much to improve continues pywebview

**Comment by MominIqbal-1234** [comment]
@GGTEC

i got your problem solution in this links

1) https://stackoverflow.com/questions/26233180/resize-a-div-on-border-drag-and-drop-without-adding-extra-markup
2) https://stackoverflow.com/questions/67463673/detect-if-user-trying-resize-a-draggable-element
3) https://stackoverflow.com/questions/67014828/drag-bar-on-side-to-resize-element-width-independently-any-number-of-elements-o

**Comment by GGTEC** [comment]
> 

Thanks, maybe this can help

**Comment by MominIqbal-1234** [comment]
@GGTEC

if this links solve your problem so tell me
because if it works so i drop this link in codegrepper community 
thanks :)

**Comment by r0x0r** [comment]
4.0 is now released. Discussion for this release is here https://github.com/r0x0r/pywebview/discussions/1016

**Comment by Skjolbir** [comment]
> **Hey, i encountered this error when trying the 4.0 release. Any fixes?** `/js_api/c584c2ff-7534-11ed-9e25-a26cf82fcc7f [pywebview] WebView2 initialization failed with exception: Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: The specified module could not be found (0x8007007E) at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll() at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext() ` I am using Windows 11. Thanks.


https://stackoverflow.com/a/74107882
This fixed it for me
