### ISSUE TITLE
The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path

### ISSUE THREAD

**Issue by x011** [r0x0r/pywebview#872]
### Specification
- pywebview version:  3.6.2 (installed via pip)
- operating system: Windows 11

### Description  
  
Error while starting :

```
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
[pywebview] Using WinForms / Chromium
```
  
The keys exists under:

`Computer\HKEY_CURRENT_USER\Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}`

**Comment by x011** [comment]
The problem is that my app, which works on windows 10, doesn't work on windows 11 due to this error. Any idea how to fix it?

**Comment by r0x0r** [comment]
Could you post the full stack trace?

**Comment by x011** [comment]
What should I do in order to send this?

**Comment by r0x0r** [comment]
What is your program output on Windows 11?

**Comment by x011** [comment]
I don't know what you mean by _program output_. Can you please help me providing the necessary debug information by giving clear instructions on how to do so?
Thank you.

**Comment by x011** [comment]
Here's the problem and the fix in my case:

webview on windows 10 allowed me to load resources like this:

`<script src="//cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta/dist/js/bootstrap-select.min.js"></script>`

but on windows 11 **not**, because it opens such reources as `file://cdn.jsdelivr.net...`, which obviously don't exist, changing `//` for the correct protocol (eg: `https://`) fixed the problem, which, after all, wasn't directly related to pywebview, but thanks anyway.

**Comment by ppvergarag** [comment]
I have the same issue but the fix does not work. I'm using django/Vue  with pywebview. 
It opens in edge, chrome and firefox without pywebview.

In index.html:

{% load static %}
<!DOCTYPE html>
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

<body>
    <div id="app"></div>
    <script type="text/javascript" src="{% static 'src/vue/dist/js/chunk-vendors.js' %}"></script>
    <script type="text/javascript" src="{% static 'src/vue/dist/js/app.js' %}"></script>
</body>
</html>


the error:

[pywebview] [WinError 2] The system cannot find the file specified
[pywebview] [WinError 2] The system cannot find the file specified
[pywebview] [WinError 2] The system cannot find the file specified
[pywebview] Using WinForms / EdgeHTML

in Microsoft Edge DevTools:

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
[app.js (1129,1)](http://localhost:8000/static/src/vue/dist/js/app.js)

**Comment by KiritoKing** [comment]
I recommend u to enable http-server property
