### ISSUE TITLE
python 3.10 Support?

### ISSUE THREAD

**Issue by elibroftw** [r0x0r/pywebview#873]
### Specification
- pywebview version: 
- operating system:
- web renderer: 

### Description  
  
I migrated my app from Python3.8 to Python3.10 so going back to 3.8 just for this module is kinda impractical for me. I'm actually just trying to test it out to see if it's faster to develop with this that it would with Tauri 😂.
  
### Practicalities

- YES am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What operating system are you on?
pywebview should work on 3.10. On Windows you should upgrade pythonnet to the 3.0 version.

**Comment by elibroftw** [comment]
I'm on windows
