### ISSUE TITLE
Python always escapes symbols such as \ when executing JavaScript  

### ISSUE THREAD

**Issue by Autumn-one** [r0x0r/pywebview#874]
### Specification
- pywebview version:  3.6
- operating system: win11
- web renderer: default

### Description  
  
  Python always escapes symbols such as \ when executing JavaScript . This results in me always having to replace all the special characters before I splice javascript code and then replace them back in javascript which doesn't look very elegant

**Comment by r0x0r** [comment]
Does r strings solve your issue?
Could you post an example demonstrating the problem?
