### ISSUE TITLE
Drag'n'drop

### ISSUE THREAD

**Issue by FeralFox** [r0x0r/pywebview#877]
### Specification
- pywebview version: 3.6.2
- operating system: Windows
- web renderer: Edge Chromium

### Description  
  
I would like to drop files from and to the webview to the desktop (or other applications) and want to ask whether this is possible.
I did some research on Windows and this is what I found out:

**Regarding drop files to Webview**
Summary: Everything works, but I cannot retrieve the path of a file, only its name.

Details: I can drag and drop files from Windows Explorer to my HTML. When I do this, "on_drag_end" will be fired and with event.dataTransfer.files I can get some file information. The only information I don't get is the file path (I only get the name) but this is what I would need. Normally Edge would open this file on drop with the default viewer. I can avoid this by using event.preventDefault() and event.stopPropagation()
When I drag a file from e.g. Windows Explorer to the WebView, WinForms will fire the "DragEnter" event whenever I cross the windows boundaries. From this event I can extract the file paths. These data could be provided using JavaScript API. The problem here is that when Windows Explorer overlaps the webview I can drag a file without passing the boundary. So the DragEnter event will not be fired in this edge case. An (ugly) solution could be to add a transparent overlay above the webview to intercept the event and directly extract the data from it. The idea is described [here](https://stackoverflow.com/questions/46630809/c-sharp-winforms-transparent-drag-and-drop-overlay).

**Regarding drag files from WebView**
Summary: Edge currently supports drag'n'drop of links and images

Details: What I would need is the ability to drop any file or folder from Webview to other applications. I did some research and found out two things:
  1) (The obvious one): From WinForms it would be possible to drag files or folders to Windows Explorer / Other windows.
  2) When I drag a link or any other draggable element (like a draggable div), a "DragEnter"-Event will be thrown as soon as I cross the borders of the window. This has a DataObject set but I did not find a way how to manipulate the data (which means replacing the data with the actual file data). In WinForms, the dataobject is initialized during MouseDown. It could be possible to again do this trick with the transparent layer, but there I think the problem will be that you will want to first call JavaScript, then find out what files to copy and after that set the data to the WinForms object.

I could also share my "experiment" branch if this helps
  
### Practicalities

- YES I am willing to work on this issue myself but I am really not good at the Windows API

- YES I am prepared to support this issue financially - I am not sure what figure will come up if I say "yes" here

**Comment by FeralFox** [comment]
Thanks to some help I got this working at least for Edge Chromium.
Basically, dragging files works without limitations, dropping files works with a workaround but is by far not as ugly as in my original idea mentioned above.
However, it is a new API endpoint necessary for both, dragging and dropping. So it is not that straightforward to use. 
If you are interested in a solution I can post it to a branch.

**Comment by r0x0r** [comment]
Yes, please post it.

**Comment by FeralFox** [comment]
I have added the solution here: https://github.com/FeralFox/pywebview/commit/ffe645bd699001a730a24805b3a0abc9c29cbf72
It is an adaption of the solution of @hbl917070 as posted here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2313

Summary:
* To start a drag in JS, you need to use the new "dragfile" command and provide a list of file paths.
* During a drop, you will receive the file names in JavaScript, but the name of the source folder has to be fetched in Python API (this could probably be summarized for convenience)
* Known issue: If you drop files from multiple different folders (However you do that), this will fail.
