### ISSUE TITLE
travis ci, appveyor and basic testing

### ISSUE THREAD

**Issue by denfromufa** [r0x0r/pywebview#88]

**Comment by r0x0r** [comment]
Please elaborate on how you would approach building a test suite. I've been thinking about converting examples into simple tests that would check that they run without exceptions. As for how to run it automatically on three different platforms is a mystery to me.

**Comment by r0x0r** [comment]
I have introduced a basic test suite that checks for syntax errors, obvious exceptions and exit codes (no functionality testing). It can be found in this branch https://github.com/r0x0r/pywebview/tree/test-suite

I have tested it with OSX and Windows so far.  On Windows there are no issues so far and on OSX some tests require mouse movement in order to close the webview window programmatically. I haven't tested it with Linux yet.

**Comment by r0x0r** [comment]
Another issue is how to close windows with opened dialogs.

**Comment by r0x0r** [comment]
I have merged a test suite with master. Based on examples, implemented with pytest and tested on all the platforms. It does not do any functional testing, but rather runs different scenarios and verifies that no exceptions occur and checks for exit codes. A timeout detection should be added to prevent hanging.

Other notes:
- test_load_html fails on WinForms at the moment. I am working on a fix.
- Tests cannot be run on OSX Sierra (every test crashes). Not sure if it is a problem with the OS itself or my configuration. Works fine on previous versions of OSX
- There are no tests for file dialogs

**Comment by shivaprsdv** [comment]
It is showing 'All checks have failed' on recent commits. What is missing?

**Comment by r0x0r** [comment]
I have signed up for both travis and appveyor, but haven't had time to configure them. So configuration for both is missing, hence the error.

**Comment by r0x0r** [comment]
CI for GTK and QT are set up on Travis now.

**Comment by r0x0r** [comment]
OSX is covered too.

The current problem is that sometimes tests hang, i.e. destroy_window logic used by tests does not work in some cases.

**Comment by shivaprsdv** [comment]
Can we add an AppVeyor badge now?

**Comment by r0x0r** [comment]
Done. I have updated README with information on testing as well.
There are still issues with Python 3 on OSX, but other than that everything else is covered. I am closing this issue now.
