### ISSUE TITLE
Window is not draggable when frameless is set to True

### ISSUE THREAD

**Issue by nanna7077** [r0x0r/pywebview#883]
### Specification
- pywebview version: 3.6.3
- operating system: Arch Linux - GNOME
- web renderer: GTK

### Description  
  
The window is not draggable when using the frameless is set to True even with easy_drag set to True (or False). Using the ```pywebview-drag-region``` doesn't work too.
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Could not reproduce this when using `frameless=True, easy_drag=True` flags. Works as expected.

**Comment by nanna7077** [comment]
Is there anything I can do to check if its due to something on my side?
