### ISSUE TITLE
Hello word crash in M1 with pyinstaller

### ISSUE THREAD

**Issue by marcom1981** [r0x0r/pywebview#884]
### Specification
- pywebview Latest 
- operating OSX 12.3.1 AMR64 M1:

### Description    
Create FAT executable with pyinstaller, 
if target-architecture is intel the executable work fine.
if target-architecture is arm64 the executable crash.

I use hello word script.

Other script working in both architecture.

**Comment by r0x0r** [comment]
I don't have a M1 machine, so unfortunately I cannot test this.
