### ISSUE TITLE
Disable document zooming

### ISSUE THREAD

**Issue by TheColorRed** [r0x0r/pywebview#888]
### Specification
- pywebview version: 3.6.3
- operating system: Windows
- web renderer: Chrome Edge

### Description  

Document zoom (ctrl+wheel) should be disableable/enableable. Some apps (such as image editors) use that to do a custom zoom.

**Comment by r0x0r** [comment]
There is a fix for this in the `4.0` branch. It addresses a pinch zoom, not sure about ctrl+wheel. Please test and report back.
