### ISSUE TITLE
Win7 platform operation error

### ISSUE THREAD

**Issue by kevin3061** [r0x0r/pywebview#891]
### Specification
- pywebview version: 3.6.3
- operating system: windows7
- web renderer: Chrome Edge

### Description  
  
 Win7 platform operation error, unable to start normally：：：
```
System.IO.FileNotFoundException: Unable to find assembly 'System.Collections'.
   在 Python.Runtime.CLRModule.AddReference(String name)
```

![image](https://user-images.githubusercontent.com/15794385/167827715-0ea201c2-1c6e-4e34-ade6-1cd5e5a9030b.png)

**Comment by kevin3061** [comment]
> Windows 7 is not supported

Will version 4.0 be supported?

**Comment by r0x0r** [comment]
Windows 7 is not supported by Microsoft either. I don't see any reason why I should support an outdated operating system. 

Having said that, check what version of .NET you have. Upgrading .NET to a more recent version may fix this problem.

**Comment by kevin3061** [comment]
OK, I see. Thank you

**Comment by marcelodiaz558** [comment]
> Windows 7 is not supported by Microsoft either. I don't see any reason why I should support an outdated operating system.
> 
> Having said that, check what version of .NET you have. Upgrading .NET to a more recent version may fix this problem.

Hey, quick question, I see that W7 is not supported. However, if I develop using a compatible Windows version, and then I freeze my app with something such as Pyinstaller, is there any chance of supporting W7?

**Comment by r0x0r** [comment]
Well, if somebody fixes this, I will gladly incorporate changes. I don't have Windows 7 installed.

Now looking at the code, it seems that System.Collections assembly is not used. You can try remove all the references to it

**Comment by happylittle2010** [comment]
When packaging NiceGUI using the native mode, it utilizes pywebview, which is no longer officially supported on Windows 7.

Solution: Install the .NET 4.7.2 runtime and the Edge WebView2 Runtime 109 (109 is the last version that supports Windows 7).

109 installer: https://archive.org/details/microsoft-edge-web-view-2-runtime-installer-v109.0.1518.78

**Comment by happylittle2010** [comment]
Since my clients are still using the Windows 7 system and my program uses pywebview during development, after some exploration, I found the following solution:

Install the .NET 4.7.2 runtime and the Edge WebView2 Runtime 109 version (109 is the last version that supports Windows 7).

109 installer: https://archive.org/details/microsoft-edge-web-view-2-runtime-installer-v109.0.1518.78
