### ISSUE TITLE
seems no method to set favor icon on the window

### ISSUE THREAD

**Issue by Jzhenli** [r0x0r/pywebview#897]
not sure if the latest version V3.6.3 have method to set favor icon on the window?

if yes, would u give a brief example.
if not, do u have a plan to add in the coming V4.0?

thanks

**Comment by r0x0r** [comment]
A traditional way to add an application icon is via a freezing utility (ie. pyinstaller). There has been an attempt to add an icon parameter to `create_window` https://github.com/r0x0r/pywebview/pull/786, but the PR got stale.
favicons are not supported.
