### ISSUE TITLE
API not support the new page

### ISSUE THREAD

**Issue by mkeyno** [r0x0r/pywebview#898]
### Specification
- pywebview version: 3.6.3
- operating system:windows 10
- web renderer: QT

### Description  
  
  I'm using the following code and its works fine , but it's too old to support new page 
  
  ```python
import webview

webview.create_window('Hello world', 'https://twitter.com/')
webview.start(gui='mshtml')
webview.start()
```
  
![image](https://user-images.githubusercontent.com/6232001/170995073-c72a7a59-1eb8-44ab-ae3e-cd3e913c4864.png)

### Practicalities

- YES/ I am willing to work on this issue myself.

- /NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Why do you set gui='mshtml'? You force IE renderer this way.

**Comment by mkeyno** [comment]
@r0x0r  because its only GUI that works
