### ISSUE TITLE
Exe not working after making  | how to make exe pywebview proprer way

### ISSUE THREAD

**Issue by mominiqbal1234** [r0x0r/pywebview#903]
### Code
 webview.start(debug=True,http_server=True,gui='cef')
this is line not working in exe and and available proper way to create exe file 
i am using this script using exe file
-python -m eel main.py templete --onefile --noconsole --icon=1.ico

**Comment by detritophage** [comment]
You seem to be following instructions for packaging an Eel application, which isn't likely to work for pywebview. You should [use PyInstaller directly](https://pywebview.flowrl.com/guide/freezing.html).
