### ISSUE TITLE
is there a way to download html from loaded page?

### ISSUE THREAD

**Issue by vv2006-mc** [r0x0r/pywebview#907]
I am trying to get a html page which is post rendered by javascript. is there a way to download the loaded page to html? I know that there are better alternatives to do so (ex: requests-html) but I am currently already using pywebview in my project and am planning to publish it. so for the sake of not increasing size of the project, checking if it is even possible.

**Comment by detritophage** [comment]
`html = window.evaluate_js("document.documentElement.outerHTML")`?

**Comment by vv2006-mc** [comment]
thank you it worked. here is the code for anyone referencing this in the future

`
import webview

def evaluate_js(window):
    result = window.evaluate_js("document.documentElement.outerHTML")

    with open('index.html', 'w', encoding='utf-8') as file:
        file.write(result)


if __name__ == '__main__':
    window = webview.create_window('Run custom JavaScript', 'https://www.google.com')
    webview.start(evaluate_js, window)
`
