### ISSUE TITLE
Webcam with navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by josephernest** [r0x0r/pywebview#909]
Hello,
How is it possible to enable the computer's webcam inside a `pywebview`?
The following code does not seem to get access to the camera (like it happens in a normal Chrome window).

System: Windows 7, Python 3.8, [WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) (is this the `edgechromium` renderer probably?)

```
import webview
html = """
<html>
<head>
<style>
#cam { height: 400px; width: 400px; border: 1px solid black; }
</style>
</head>
<body>
<div id="cam"></div>
<div id="container"></div>
<script>
    window.addEventListener('pywebviewready', function() {
        var container = document.getElementById('container');
        container.innerHTML = '<i>pywebview</i> is ready';
        var video = document.getElementById("cam");
        navigator.mediaDevices.getUserMedia({ video: true }).then(function (stream) { video.srcObject = stream; }).catch(function (error) { container.innerHTML = 'webcam error' });
    })
</script>
</body>
</html>
"""
window = webview.create_window('', html=html)
webview.start()
```

**Comment by r0x0r** [comment]
There is a discussion you might want to take a look at https://github.com/MicrosoftEdge/WebView2Feedback/issues/750
