### ISSUE TITLE
Customisable icon

### ISSUE THREAD

**Issue by cateee** [r0x0r/pywebview#91]
It would be nice to have a customizable icon (e.g. in titlebar), e.g. using favicon framework, or just as an option when creating the window.  Now we get the standard (yellow-blue) python icon.

**Comment by r0x0r** [comment]
You can get an application icon by freezing your application. It works on OSX, but is semi-broken on Windows when frozen with pyinstaller (the icon is displayed in the exe file, but not in the titlebar). I will get to fix the PyInstaller issue at some point. No idea about freezing in Linux. 
Is there a use case for having an application icon without freezing?

**Comment by cateee** [comment]
Icon by freezing is nice to me. I can see some use cases on big companies, which use often various intern-developed tools. These tools could have advantage of having both different icons and sources. But it is not my use case, so I'm not so sure about it.

**Comment by r0x0r** [comment]
The fix to the icon issue is in master now. The icon should be visible, when you freeze your application with pyinstaller and supply an icon with the --icon option.
