### ISSUE TITLE
Internal links

### ISSUE THREAD

**Issue by vlachoudis** [r0x0r/pywebview#910]
When trying to open a page with an internal link
```
import webview
window = webview.create_window('Help', '/home/page.html#link')
webview.start()
```
 it tries to open the file **/home/page.html#link**

**Comment by r0x0r** [comment]
Loading local links is rather unpredictable on how they behave. For this reason 4.0 will load local links via a new bottle.py based http server. Would you test this against 4.0 branch to see if it is fixed there already?

**Comment by vlachoudis** [comment]
Thank @r0x0r I will check 4.0
