### ISSUE TITLE
Url change event

### ISSUE THREAD

**Issue by imLinguin** [r0x0r/pywebview#911]
Would be nice to have: ability to listen for url change.
I know QTWebEngine supports this feature (don't know about other back-ends though).

**Comment by r0x0r** [comment]
Could be done easily, as all the back-ends process this event already. Triggering a custom event is only needed to be added.  PR is welcomed.

**Comment by elvinos** [comment]
Would be excellent to find a simple way to get this working

**Comment by Dorian25** [comment]
Hi, has this feature been implemented or is it not current?

**Comment by Dorian25** [comment]
would be nice to had this in the [events.py](https://github.com/r0x0r/pywebview/blob/master/examples/events.py)

**Comment by thewh1teagle** [comment]
You already have that.
Just remove these 2 lines and everytime url changing it will fire
https://github.com/r0x0r/pywebview/blob/master/examples/events.py#L42
