### ISSUE TITLE
print html document with printer silent such as electron?

### ISSUE THREAD

**Issue by XieB** [r0x0r/pywebview#916]
### Specification
- pywebview version: 3.6.3
- operating system: windows 10
- web renderer:  edge

### Description  
  
  Is any way to print html document with printer silent such as electron？though i think it is the function with python，but i can't found any solution? any ideas? thanks a lot
  
### Practicalities

- YES/NO I am willing to work on this issue myself.
YES
- YES/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
What do you mean by printer silent? Would `window.print()` in JS work for your case?

**Comment by XieB** [comment]
> What do you mean by printer silent? Would `window.print()` in JS work for your case?

yeah，window.print() will preview，not silent.

**Comment by r0x0r** [comment]
Do you mean sending a page directly to printing, skipping the print dialog?

**Comment by XieB** [comment]
> Do you mean sending a page directly to printing, skipping the print dialog?
yes
