### ISSUE TITLE
How to maximize window on startup?

### ISSUE THREAD

**Issue by dominggo1999** [r0x0r/pywebview#917]
### Specification
- pywebview version:  3.6.3
- operating system: windows 7 64
- web renderer: edge

### Description  
  
 I want to maximize the window when the app is launched (* I don't want to make it full-screen), but it seems there is no method available to do it

![image](https://user-images.githubusercontent.com/64012087/180188766-ffb164f2-f57b-43e9-83e9-4f751cf2b5ec.png)

 Is this feature still not implemented ?

**Comment by r0x0r** [comment]
maximized is indeed not implemented. If there is demand for it and somebody wants to give this a go, a PR is welcomed.
