### ISSUE TITLE
Window is not draggable when web rendere is webview2

### ISSUE THREAD

**Issue by lmh87883819** [r0x0r/pywebview#918]
Specification
pywebview version: 3.6.3
operating system: Windows 10
web renderer: webview2
Description
The window is not draggable when using the frameless is set to True even with easy_drag set to True (or False). Using the pywebview-drag-region doesn't work too. And webview2 does not support -webkit app region: drag

**Comment by r0x0r** [comment]
Apologies for the late response. I got this reproduced and will try to address at some point. Meanwhile any help is welcomed.
