### ISSUE TITLE
Script gets stuck when executing Invalid JS Script (CEF)

### ISSUE THREAD

**Issue by irtimir** [r0x0r/pywebview#925]
### Specification
- pywebview version: 3.6.3[cef]
- operating system: windows 10
- web renderer: 

### Description  
  
```python
import time

import webview


def eval_js():
    for _ in range(3):
        print('pre eval js')
        webview.windows[0].evaluate_js('invalid(js, string)')
        print('post eval js')
        time.sleep(1)


def main():
    webview.create_window('Woah dude!', html='<h1>Woah dude!<h1>')
    webview.start(eval_js, debug=True, gui='cef')


if __name__ == '__main__':
    main()
```
<img width="706" alt="image" src="https://user-images.githubusercontent.com/22493187/181744689-8ef060ce-4f82-441e-b6e1-1f50081ac2a1.png">

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/22493187/181744837-491a284b-373a-4a4c-8073-c7c1b72b736b.png">

i suggest a fix #924  according to [version 3.5](https://github.com/r0x0r/pywebview/blob/3.5/webview/platforms/cef.py#L117)
  
### Practicalities

- YES/NO I am willing to work on this issue myself. YES

- YES/NO I am prepared to support this issue financially. NO

**Comment by MominIqbal-1234** [comment]
this solution is not working https://github.com/r0x0r/pywebview/pull/924 according to [version 3.5](https://github.com/r0x0r/pywebview/blob/3.5/webview/platforms/cef.py#L117)

**Comment by irtimir** [comment]
@MominIqbal-1234, please describe the problem reproduction in more detail

**Comment by MominIqbal-1234** [comment]
hi i have same to same problem how can i solve
CEF window with uid master does not exist

**Comment by irtimir** [comment]
i have another problem
the message "CEF window with uid master does not exist" does not cause problems

**Comment by MominIqbal-1234** [comment]
CEF window with uid master does not exist 
When this error occurs, the EXE  file is not being processed
