### ISSUE TITLE
pythonnet doesn't install from requirements file or pip

### ISSUE THREAD

**Issue by silverv** [r0x0r/pywebview#928]
### Specification
- pywebview version: not needed
- operating system: Windows 10
- web renderer: not needed

### Description  
  
Doing pip install pythonnet no longer works, I guess they don't use pypi anymore. But doing pip install git+https://github.com/pythonnet/pythonnet as stated in pythonnet docs works. This also breaks the install progress of pywebview on Windows.

The solution is to edit the requirements file with a github source of pythonnet master branch.
(https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source)
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
Pypi version of pythonnet is still at 2.5. Recent versions of python require 3.0 that could be installed via github.
