### ISSUE TITLE
No HTML content displayed on Ubuntu 22.04 with QT

### ISSUE THREAD

**Issue by silverv** [r0x0r/pywebview#929]
### Specification
- pywebview version: 3.6.3
- operating system: Kubuntu 22.04
- web renderer: QtWebChannel

### Description  

The TODO example and the examples provided on the website do not work. There is no way to display HTML content in the window that results. I tried via url and made sure that the paths do not contain any spaces. Then I tried by loading the html file into a variable and feeding it in through the html parameter of the start function. Then I also tried running a flash server and serving html through that and it didn't work. I tried the TODO app and it didn't work.

I made sure all the dependencies were available in the venv in which the executable is run.
pip install pywebview[qt]
pip install qtpy pyside2
sudo apt install python3-pyqt5 python3-pyqt5.qtwebengine python3-pyqt5.qtwebchannel libqt5webkit5-dev
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by silverv** [comment]
I confirmed that this issue doesn't appear with Ubuntu 20.04 and otherwise same pywebview version and webrenderer

**Comment by r0x0r** [comment]
Do you get any errors or warnings in the console?

**Comment by silverv** [comment]
No errors and when I use Chrome to see the debugging window (usually I can see the windows here for debugging), then I don't see any windows listed. I cannot see any HTML content rendered in these windows and there are no console errors.
Here is the code I am working with, otherwise the application is progressing very well (on Ubuntu 20 and Windows 10/11) and pywebview is a great tool:
https://github.com/Zubax/kucherx/tree/executables

**Comment by r0x0r** [comment]
I have no means to reproduce this (no ARM image of Kubuntu), but this has most likely something to do with QT dependencies. Comparing versions of QT libraries would probably be a good start.
