### ISSUE TITLE
load_html.py does not work

### ISSUE THREAD

**Issue by rxng** [r0x0r/pywebview#93]
Hi,

The window opens, but then the page is blank and it starts to hang. I have also tried it on my own script - the contents of the window are always empty

R

**Comment by r0x0r** [comment]
What OS?

**Comment by rxng** [comment]
macOS 10.12

**Comment by r0x0r** [comment]
There was a bug in event handling and the event blocking timeout for load_html was set to 50 seconds (instead of the usual 5). Now both issues are fixed and pushed to master.
