### ISSUE TITLE
Distribute is difficulty?

### ISSUE THREAD

**Issue by XieB** [r0x0r/pywebview#932]
### Specification
- pywebview version: 3.6.3
- operating system: windows 7 32bit
- web renderer:  edgechromium or cef

### Description  
  I am developing with python3.6/vue3 + vite + typescript，i have three questions
    1、i must intall more than three dependencies and it is difficulty installing .net4.6 when i use edgechromium on windows7 32 bit
    2、although i has install all dependencies and force gui = edgechromium，but render allways use mshtml，why?
    3、chrome version is too old when i use cef. I search cefpython issues, the author think upgrade bind version is difficulty. I don't know how to do this.
expecting reply, thank you a lot.

**Comment by r0x0r** [comment]
Windows 7 is not supported by Microsoft, nor by me. If you get edgechromium to work under Windows 7, I will accept a patch though.
