### ISSUE TITLE
Prevent pywebview app from closing

### ISSUE THREAD

**Issue by gelflein** [r0x0r/pywebview#933]
### Specification
- pywebview version: pywebview
- operating system: Windows 10
- web renderer: edgechromium (webview2)

### Description  
I don't have an issue. It's more likely a question, I cannot find an answer to.
At first, I have the requirement for my application that it is always open and cannot be closed.
Therefore, I set frameless to "true". But the app can still be closed using right-click in the taskbar or the keyboard shortcut ALT+F4.

From another development project using QT I know it could be possible to catch the close events.
How can I prevent my pywebview app from closing?

**Comment by r0x0r** [comment]
Close events are already caught in the code and they can be aborted as well. Implementing this should not be too laborious. A bigger issue is in the details on how exactly this feature should work. Should it be available only to frameless windows? If it is applicable to regular windows, the close button should be hidden as well.
I don't have much time to work on this at the moment, but if somebody wants to tackle this, then help is most welcomed.

**Comment by MicahTa** [comment]
window.destroy()

**Comment by MicahTa** [comment]
Oh shi nvm I cannot read lol

**Comment by MicahTa** [comment]
def onClosing():
    for i in range (1000000):
        print (i)
    # This false will abort the window closing
    return False


API=Api()
window = webview.create_window("Title", 'main.html', js_api=API, confirm_close=True)
window.events.closing += onClosing
webview.start(API.load, debug=True)

# This is is how you abort closing its kinda looks weird and the documentation barley mentions this too, I am surprized I found it but I needed to know this too, have a nice day (:
