### ISSUE TITLE
ModuleNotFoundError: No module named 'android'

### ISSUE THREAD

**Issue by nsde** [r0x0r/pywebview#934]
### Specification
- pywebview version: **3.6.3**
- operating system: Arch Linux
- web renderer: -

### Description  
Code
```py
import webview
```

Output
```py
Traceback (most recent call last):
  File "/home/lix/Documents/NSDEarch/muse/muse/client.py", line 3, in <module>
    import webview
  File "/home/lix/.local/lib/python3.10/site-packages/webview/__init__.py", line 1, in <module>
    from .webview import WebView
  File "/home/lix/.local/lib/python3.10/site-packages/webview/webview.py", line 1, in <module>
    from android.runnable import run_on_ui_thread as run_thread
ModuleNotFoundError: No module named 'android'
```
OS Info
![image](https://user-images.githubusercontent.com/67185896/183930054-2604b7bf-f1ae-400c-9e46-fe7b0d171c7e.png)

### Practicalities

- YES/**NO** I am willing to work on this issue myself.

- YES/**NO** I am prepared to support this issue financially.

**Comment by nsde** [comment]
Python Version: 3.10.5

**Comment by nsde** [comment]
I'm pretty sure it worked before flawlessly. Maybe an update of the package caused the problem?

**Comment by nsde** [comment]
Pip freeze output:
```c
...
pywebview==3.6.3
...
webview-android==0.10
...
```

**Comment by nsde** [comment]
Solved by installing the correct package.

**Comment by vimevim** [comment]
> Solved by installing the correct package.

Could you please share the correct packages?

**Comment by nsde** [comment]
> > Solved by installing the correct package.
> 
> Could you please share the correct packages?

Sure. Simply make sure you actually install `pip install pywebview`.

**Comment by vimevim** [comment]
Thanks for your answer, ```pip install pywebview``` was not the fix for my situation. "No module named 'android'" error kept coming so I checked it... IDK when but I pip installed this library "webview-android" globally, cuz I didn't use virtual environment, pywebview imported android but from this new package... So I ran this command "pip uninstall webview-android" and the problem was solved.

I think I installed "webview-android" when i was playing with kivy and android stuff...

**Comment by nsde** [comment]
Great to hear. I think it was the same issue for me!

**Comment by vimevim** [comment]
Most probably, I decided to start to use a virtual environment after this issue for good.
