### ISSUE TITLE
In frameless mode, the titlebar is displayed and draggable （macos）

### ISSUE THREAD

**Issue by CahierX** [r0x0r/pywebview#937]
### Specification
- pywebview version: 3.6.3
- operating system: macos 12.4
- web renderer:  react

### Description  
First of all, frameless mode is very easy to use, but I want to still display the titlebar in frameless mode, and keep the top draggable. Now, I can't do it.
It's looks like this
![image](https://user-images.githubusercontent.com/31394482/184889354-10842c40-9346-412f-9913-abdebf37a00c.png)

https://user-images.githubusercontent.com/31394482/184896489-b63173d5-aab5-4a59-91d1-6eb4c3aa4bc6.mov

### Practicalities

- YES/NO I am willing to work on this issue myself.
YES
- YES/NO I am prepared to support this issue financially.
NO

**Comment by r0x0r** [comment]
Do you have any examples  of macOS apps that would implement this feature? While I can see the need for something like this, I am rather conservative about adding edge cases as core features. Also if something like this to be introduced it would be nice to have it for other platforms as well.

**Comment by CahierX** [comment]
> Do you have any examples of macOS apps that would implement this feature? While I can see the need for something like this, I am rather conservative about adding edge cases as core features. Also if something like this to be introduced it would be nice to have it for other platforms as well.

This pr has a demo  [938](https://github.com/r0x0r/pywebview/pull/938)
file: examples/frameless_titlebar.py
