### ISSUE TITLE
Doesn't work when ported

### ISSUE THREAD

**Issue by rxng** [r0x0r/pywebview#94]
Hi,

Works perfectly on my  macOS but not friend running same version. It still can load an external URL on his, but not the same local file that I can on mine. 

On a related note - is there a way of putting an error message instead of waiting at a blank white screen ?

**Comment by r0x0r** [comment]
Please be more specific. Steps, versions, error messages, installed libraries and such

**Comment by r0x0r** [comment]
Closing due inactvity and vagueness
