### ISSUE TITLE
Hangs after destroy_window

### ISSUE THREAD

**Issue by jorants** [r0x0r/pywebview#95]
If I run the example for destroy_window() then the thread that created the window keeps hanging after the window disappears. 
I downloaded the current branch, it is using GTK, python2.7.

**Comment by jorants** [comment]
It does quit when it gets a manual emit
webview.gui.BrowserView.instance.window.emit('delete-event',webview.gui.Gdk.Event())

**Comment by r0x0r** [comment]
Fixed in master

**Comment by jorants** [comment]
[destroy_bug.zip](https://github.com/r0x0r/pywebview/files/1151260/destroy_bug.zip)
Hey, just got back to this. The thread does not hang but the window does not disapear until the script exits.
See attachement.
