### ISSUE TITLE
no error.log with cef backend

### ISSUE THREAD

**Issue by eseunghwan** [r0x0r/pywebview#950]
### Specification
- pywebview version: 3.6.3
- operating system: Windows 10 Home 21H2(Build 19044.1889), AMD64
- web renderer: cef(cefpython3)

### Description  
  
  I have to refer to the error log to get feedback from the client, but the error.log file is not generated, so I cannot view the log.
How can I generate error.log with pywebview + cefpython?
  
### Practicalities

- YES/NO I am willing to work on this issue myself. Trying for 2 days

- YES/NO I am prepared to support this issue financially. YES

**Comment by r0x0r** [comment]
error.log is deleted along with other log files on application quit. This behaviour can be overridden by commenting out lines 326-327 in `cef.py`
A more general solution would be to introduce some kind of a configuration flags for platform specific features. Suggestions are welcomed on how this should be tackled.

**Comment by r0x0r** [comment]
@eseunghwan I fixed this issue by suppressing deletion of error.log in debug mode. Hopefully this solution will work for you. 
The change is in the master  branch.
