### ISSUE TITLE
Fix PythonNet and Thread / Assembly Errors for Python 3.8 <  .(Tested on 3.10.7)

### ISSUE THREAD

**Issue by DizzyduckAR** [r0x0r/pywebview#952]
### Specification
- pywebview version:  >=3.6.3
- operating system: Windows OS
- web renderer:  ALL Engines

### Description  
   Fix install and Dependencies for python 3.10.7
   while PythonNet pip install Trigger Errors on any ENV above 3.8 User can bypass with
   pythonnet==3.0.0a2
   //
   pip install pythonnet==3.0.0a2
   
   To fix Thread and Assembly DotNet errors you will need
   clr-loader==0.1.7
   //
   pip install clr-loader==0.1.7
   
   Only Then a pip install pywebview will go clean and Work Normally
  
### Practicalities
** Only the egg needed in the site-package folder. yo can still update the package

requirements.txt
clr-loader==0.1.7
pythonnet==3.0.0a2
pywebview

Demo pywebview

![Code_5fm8FiowSb](https://user-images.githubusercontent.com/52171360/191752955-bc604abb-0925-4b00-b4e3-bc202e2fab4a.gif)

**Comment by fbravohz** [comment]
Thanks @DizzyduckAR very helpful solution.
