### ISSUE TITLE
 [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime 

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#953]
### Specification
**Python 3.10.3** 

- pywebview version:  3.6.3
- altgraph==0.17.2
bottle==0.12.23
cffi==1.15.1
clr-loader==0.1.7
future==0.18.2
pefile==2022.5.30
proxy-tools==0.1.0
pycparser==2.21
pyinstaller==5.4.1
pyinstaller-hooks-contrib==2022.10
pythonnet==3.0.0a2
pywebview==3.6.3
pywin32-ctypes==0.2.0

- operating system: WINDOWS 10
- web renderer:  WEBVIEW2

### Description  

I am getting this error, but when I hit F12, the console shows that it is using Edge, indeed.   
[pywebview] [WinError 2] The system cannot find the file specified - Microsoft Edge WebView2 Runtime Registry path: Computer\HKEY_CURRENT_USER\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
[pywebview] Using WinForms / Chromium

---> I can confirm this KEY does not exist, but I do have the runtime installed:

![image](https://user-images.githubusercontent.com/18351919/192116524-14f2e40c-fbe3-4dda-a373-26f371df80f7.png)

And this is my Edge version:
Version 105.0.1343.50 (Official build) (64-bit)

Thanks,

**Comment by r0x0r** [comment]
This error is displayed even if webview2 is loaded. It will be fixed in the next release.

**Comment by dbilewicz** [comment]
Same question here, is there any quick fix for this?

**Comment by martinlombana** [comment]
As Roman said, and I concurr, it works. It’s just the error display.

But it does use, indeed, webview2. (You can check if you activate the
debug=True and hit F12. You’ll see EdgeView2 dev tools).
-- 

___________________________________

*Martín Lombana*

*(+34) 633 63 02 35*
*TODOLOGIC.COM <https://todologic.com> *—* APPS & MORE *

**Comment by thefreelight** [comment]
the same problem

**Comment by rangwea** [comment]
the same problem too
