### ISSUE TITLE
Disable EdgeView2 Context menu

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#954]
### Specification
**Python 3.10.3** 

- pywebview version:  3.6.3
- altgraph==0.17.2
bottle==0.12.23
cffi==1.15.1
clr-loader==0.1.7
future==0.18.2
pefile==2022.5.30
proxy-tools==0.1.0
pycparser==2.21
pyinstaller==5.4.1
pyinstaller-hooks-contrib==2022.10
pythonnet==3.0.0a2
pywebview==3.6.3
pywin32-ctypes==0.2.0

- operating system: WINDOWS 10
- web renderer:  WEBVIEW2

### Description  

Is ther any way to disable the automatic context menu that Edge offers? It is annoying to have the 3 dots there. 

![image](https://user-images.githubusercontent.com/18351919/192117907-36e554d7-6a8c-4820-8745-35710b11e1a4.png)

Thanks!

**Comment by r0x0r** [comment]
Is this menu displayed on text select?

**Comment by r0x0r** [comment]
I could not reproduce this with <textarea/>. It display only a spell check menu, but not the context menu as in the screenshot.
