### ISSUE TITLE
Loading HTML page with video gives blackscreen

### ISSUE THREAD

**Issue by Linzo99** [r0x0r/pywebview#959]
### Specification
- pywebview version: 3.6.3
- operating system: Linux 4.15.0-192-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux
- web renderer: WebKit

### Description  
 Trying to load a HTML page with video ( video tag )  but got a blackscreen
or this error
```bash
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[7077:12:0929/132931.416977:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[7077:1:0929/132931.475627:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
```

**Comment by r0x0r** [comment]
What format the video is in? Have you tried loading other video formats?

**Comment by Linzo99** [comment]
it's a mp4 video. I was trying to create a web player, but i found another way. Thx
