### ISSUE TITLE
debug=True does not route edgeview2 consolelogs to python console

### ISSUE THREAD

**Issue by martinlombana** [r0x0r/pywebview#964]
### Specification
- pywebview version: pywebview==3.6.3
- operating system: Windows 10
- web renderer: EdgeView2

### Description  
  
When using debug= true, the console.logs are not re-routed to the python console (they should? or it is not possible in this setup? I read in the docs, that they should be re-routed, here https://pywebview.flowrl.com/guide/debugging.html)

On top of that, is there any way (this could be a nice feature) to automatically open the debug window on launch, with an option like:
open_debug_console=true? This way, we avoid having to open it manually each time when debugging. 

Thanks!
  
### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
The implementation for Edge Chromium has been left behind by mistake. This should be fixed.

The other suggestion is good too. This seems to be doable for most renderers. I propose that devtools to be opened automatically in debug mode. 

PR is welcomed.

**Comment by r0x0r** [comment]
Correction to the previous message. Routing `console.log` to Python console has been implemented only for MSHTML and EdgeHTML (both are deprecated now), as there is no other way to debug for these platforms.  Overriding `console.log` in favour of Python logging can be done for other platforms, but in my opinion it is rather moot as you can just use devtools.
