### ISSUE TITLE
Python API Fakepath

### ISSUE THREAD

**Issue by DanielRios549** [r0x0r/pywebview#967]
### Specification
- pywebview version: 3.6.3
- operating system: Ubuntu 20.04
- web renderer: Qt

### Description  
  
  I am trying to send a file from the frontend to save it in the disk with the backend, but the filepath is masked buy Chromium.
  

![image](https://user-images.githubusercontent.com/11152535/194681441-4a935137-9fe0-4e9e-ad7a-e919f4150b23.png)

**Comment by r0x0r** [comment]
This is Chrome's security feature, there is no way around it. You may however use `Webview.create_file_dialog` function to create a save file dialog that would give you the filepath. You may call it in your Javascript with pywebview's js api.

**Comment by r0x0r** [comment]
Another workaround is to use a http server. That should enable input type file
