### ISSUE TITLE
pywebview have no availalbe menu button like electron-js

### ISSUE THREAD

**Issue by MominIqbal-1234** [r0x0r/pywebview#969]
### Specification
- pywebview version:  3.6.3
- operating system: windows 10

### Description  
pywebview have no availalbe menu button like electron js

![Screenshot (81)](https://user-images.githubusercontent.com/61788052/196053674-3e7c6890-0f13-43f8-a07a-fbd0f09203ee.png)

  if available so please tell me how i am add menu button in my pywebview app

**Comment by r0x0r** [comment]
There is a work in progress menu implementation in the 4.0 branch
