### ISSUE TITLE
JavaScript window.print() method not working in macOS

### ISSUE THREAD

**Issue by shivaprsdv** [r0x0r/pywebview#97]
For that matters, `window.alert()`, `window.confirm()`, etc. are also not functioning in `cocoa`. `window.prompt()` is working fine. I'm on `macOS Sierra 10.12.3` with `Safari 10.10.3`, using `pywebview 1.6`. I checked it on Linux with `GTK` and everything works fine. It seems weird `WebKit` should handle only some of JavaScript `window` methods. Any idea?

I am using `pywebview` to make an app that crucially needs printing functionality. So I went ahead and implemented the functionality myself. If you are interested, I can submit a pull request from my fork of `pywebview`. Wanna have a look?

**Comment by r0x0r** [comment]
According to this post http://stackoverflow.com/questions/2101611/javascript-alert-not-working-in-embedded-webview this functionality is not implemented by default. So yeah, please share your code. 
Thank you!

**Comment by shivaprsdv** [comment]
Never found ^that SO thread myself. Could have saved the time I took to find it out myself the hard way...

So be it. I'll follow up with the PR. Cheers!

**Comment by hadiawahab** [comment]
Any updates regarding this issue?
