### ISSUE TITLE
Fail to launch file dialog when using <input type=file />

### ISSUE THREAD

**Issue by KiritoKing** [r0x0r/pywebview#970]
### Specification
- pywebview version: 3.6.3
- operating system: Windows 11 22H2
- web renderer: default(not configured, cuz sthin goes wrong when using cef)

### Description  
  
I had no problem using the file input to launch a file dialog in pywebview while my teammates did had trouble with it.

Their OS is also Windows 11 and we are running the same code, but they cannot open the file dialog successfully. It seemed like that the window was closed at the moment it started. By the way, the same code works just fine in other browsers like Edge and Chrome.

I have read the past issues on that but still had no idea about that.
  
### Practicalities

- NO I am willing to work on this issue myself. (I don't have that ability haha~)

- NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
How do you serve your html? is it via http, local file or via load_html?

**Comment by KiritoKing** [comment]
> How do you serve your html? is it via http, local file or via load_html?

Relevant code is here. 

```
if __name__ == '__main__':
    debug = verify_debug()
    webview.create_window('Video Processor', 
		url=get_entrypoint(debug),
		# resizable=False,
		width=1000,
		height=800,
        js_api=Api()
    )
    webview.start(http_server=True, gui="edgechromium", debug=debug)
```

**Comment by r0x0r** [comment]
I could not reproduce this with http server. Tested both with master and 4.0 branches.
As a workaround you can use `webview.create_file_dialog` with js_api.

**Comment by KiritoKing** [comment]
> I could not reproduce this with http server. Tested both with master and 4.0 branches. As a workaround you can use `webview.create_file_dialog` with js_api.

Yep, I have used `webview.create_file_dialog` instead in my project. 
According to my tests, it seems that something goes wrong with the renderer.
