### ISSUE TITLE
Add support for Open Directory mode 

### ISSUE THREAD

**Issue by HanslettTheDev** [r0x0r/pywebview#971]
### Problem
There is currently no way to spawn a folder directory selection window or **OPEN FOLDER** Dialog which returns the path to the folder.

### Proposed solution  
If it was possible, we could make use of the tkinter module to launch a folder directory selection window. The difficulties that I found while trying to implement this was the window will open once and hit the RuntimeError of the tk not being in the main event loop. Maybe my approach to implementing this is not the best. 
  
### Practicalities

- YES I am willing to work on this issue myself.

- No I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
You can use `window.create_file_dialog(dialog_type=webview.FOLDER_DIALOG)`
Does this work for you?

**Comment by HanslettTheDev** [comment]
> You can use `window.create_file_dialog(dialog_type=webview.FOLDER_DIALOG)` Does this work for you?

😅I had no idea about this. I didn't check the docs well, thanks for the quick response.

**Comment by HanslettTheDev** [comment]
Thanks it works now
