### ISSUE TITLE
Some machines fail to load properly

### ISSUE THREAD

**Issue by yiyuan1218** [r0x0r/pywebview#974]
### Specification
- pywebview version: 3.6.3
- python version: 3.9.0
- operating system: Windows 10
- web renderer:  WinForms / Chromium

### Description  
  
I'm working on a tool

There was a problem when it was packaged to run on the client machine

My own computer is running fine

The client's computer is not working

I had to try Chromium

The error is this

After the software is started, the screen is blank. After debugging mode is enabled, there is no response from right-clicking

```python
class App:

    def __init__(self):
        self._function = Function()
        self._window = webview.create_window('Product-Tool',
                                             url='./view/index.html',
                                             js_api=self._function,
                                             width=1200,
                                             height=700,
                                             resizable=False,
                                             background_color="#3b5ce6"
                                             )

if __name__ == '__main__':
    app = App()
    webview.start(debug=True)
```

  
### Practicalities

- YES, I am willing to work on this issue myself.

- YES, I am prepared to support this issue financially.

**Comment by MrLiu1218** [comment]
![error example](https://user-images.githubusercontent.com/57576341/198897428-55f5ac79-8b80-4d82-af14-77ed49016516.png)

Blue is my background # 3b5ce6
which failed to render the webview window of this application as shown in the screenshot.

**Comment by MrLiu1218** [comment]
locate error details ` 'NoneType' object has no attribute 'NewWindowRequested' `

**Comment by r0x0r** [comment]
This looks like an ARM issue. In short Chromium binaries bundled with pywebview  are not ARM compatible https://github.com/r0x0r/pywebview/issues/972
Microsoft has released ARM binaries for newer builds of webview2. I have attempted to fix in the `chromium-arm64` branch, but could not get it working (tested on Mac M1 via Parallels). 
Help is welcomed.

**Comment by MrLiu1218** [comment]
@r0x0r  Thank you for your answer, but I am quite sure that the client machine is not ARM processor architecture, the client machine is based on x64, do you have any good ways to recommend me to try? I don't want to waste the effort of building the application.

**Comment by MrLiu1218** [comment]
![AMD64](https://user-images.githubusercontent.com/57576341/198939338-4331b232-5f43-4a22-bc7c-2092378578f9.png)

**Comment by r0x0r** [comment]
This error indicates that webview2 cannot be loaded. Is webview2 runtime installed on your client's machine?  Are webview2 dlls present in the lib folder? What about .net version? Does version from the chromium-arm64 branch make any difference? 
One thing that could definitely be improved is proper error reporting in this handler

**Comment by MrLiu1218** [comment]
@r0x0r I have tried everything you said, the DLL under Lib is normal, the folder of x84&x64 is WebView2Loader.dll, and I am sure that I have normal installation at run time, through the official website. .net is the same, if the installed version is greater than 4.6, it means that everything seems to be all right, but it just can't accurately locate the way to solve the problem.

**Comment by MrLiu1218** [comment]
Because I want to use him to build a tool widely used by many people.

**Comment by MrLiu1218** [comment]
Still failed to solve, can we use the self-bundling rendering engine to achieve compatibility with each machine? I don't care about the size of the software. I can't find a good way.

**Comment by MrLiu1218** [comment]
Do you think I can try to use Pyside2 to build pywebview applications? is there any example of this method?


??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r0x0r/pywebview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 下午2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [r0x0r/pywebview] Some machines fail to load properly (Issue #974)





 
This error indicates that webview2 cannot be loaded. Is webview2 runtime installed on your client's machine?  Are webview2 dlls present in the lib folder? What about .net version? Does version from the chromium-arm64 branch make any difference?
 One thing that could definitely be improved is proper error reporting in this handler

**Comment by r0x0r** [comment]
You may try the cef option. It will bundle cef runtime  with your executable.

It would be nice to fix this issue, so any additional information is appreciated

**Comment by MrLiu1218** [comment]
Oh, thank God you finally replied me, CEF I tried, on my side does not work properly, I tried QT, it can work properly ┭┮﹏┭┮

**Comment by MrLiu1218** [comment]
I have been tortured by him for too long, if I use CEF, what version I install depends on

**Comment by r0x0r** [comment]
`pip install cefpython3` should do the trick

**Comment by MrLiu1218** [comment]
thanks you , but cefpython3 in pyinstaller exists error , I am try... , because I must .py to .exe 😫

**Comment by MrLiu1218** [comment]
I am so sorry, I can't find a way ! Could your please give me a suitable CEF3 package?

**Comment by r0x0r** [comment]
What error does it give? Anyhow turning to cefpython repo would be a right step in fixing this problem.

**Comment by MrLiu1218** [comment]
It gives such an error, I don't think it's the problem with pywebview, but I don't know how to solve it.

` [0812/112825.786:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received. `

Up to now, I still haven't found a way, so I can only build desktop program in other development languages first.

**Comment by r0x0r** [comment]
@MrLiu1218 I have improved platform detection for Edge Chromium. It fixed at least problems I had on my Apple M1 machine. The fix is in master

**Comment by kletel** [comment]
I know how to do exe with cefpython3 and pywebview.

**Comment by MrLiu1218** [comment]
@r0x0r So can I try to build the application with the latest version now?
@kletel Oh! Give me a hand

**Comment by yiyuan1218** [comment]
So far, I still haven't found a solution. How can I turn off this question?
