### ISSUE TITLE
In javascript, the dialog "confirm()" don't works and stops program.

### ISSUE THREAD

**Issue by jczic** [r0x0r/pywebview#976]
### Specification
- pywebview version: 3.6.3
- operating system: MacOS (M1)
- web renderer: WebKit

### Description  
  
  In web page side, in javascript, the dialog "alert()" works but the dialog "confirm()" bug and all the program stops.

**Comment by MrLiu1218** [comment]
Missing error details!! This is not a good standard for asking questions.

**Comment by r0x0r** [comment]
confirm is not implemented, but the good news is there is a PR that goes in this direction https://github.com/r0x0r/pywebview/pull/949

**Comment by r0x0r** [comment]
I could not override `window.confirm` with a custom implementation for the simple reason as `window.confirm` is sync and js_api is async, which makes returning result incompatible.

As for the macOS implementation, there seems to be a bug in pyobjc metadata that prevents from returning a result (and which results in hanging). I have raised an issue upstream, so stay tuned.

**Comment by r0x0r** [comment]
A small update before stale bot closes this. This issue has been fixed in pyobjc and the fix will be hopefully released in the next version of pyobjc. Relevant issue https://github.com/ronaldoussoren/pyobjc/issues/512

**Comment by r0x0r** [comment]
Fixed in a recent version of pyobjc and a relevant fix on the pywebview side is pushed to master.
