### ISSUE TITLE
QtWebEngineProc core dump

### ISSUE THREAD

**Issue by vsakkas** [r0x0r/pywebview#986]
### Specification
- pywebview version: `3.7.2`
- operating system: `Manjaro KDE`
- web renderer: `qt`

### Description  
  
Installed `pywebview[qt]==3.7.2`, `pyqtwebengine==5.15.6` and `qtpy==2.3.0`. Tried to run this code with python `3.10.7`:
```python
import webview

window = webview.create_window(title='Hello world', url='https://pywebview.flowrl.com/hello')
webview.start(gui='qt', debug=True)
```

A window opens and the title is correct, but the page is blank and right clicking does nothing.

I looked into `KSystemLog` and found the following error:
```
Process 430047 (QtWebEngineProc) of user 1000 dumped core.

Stack trace of thread 1:
#0  0x00007f3e242eaa4d n/a (libc.so.6 + 0x108a4d)
ELF object binary architecture: AMD x86-64
```

Any ideas on what is causing this?
  
### Practicalities

- YES I am willing to work on this issue myself.

- NO I am prepared to support this issue financially.

**Comment by vsakkas** [comment]
### Workaround
I managed to get the above code working by using the `gtk` web render instead of the `qt` one:
- Install `webkit2gtk` using `pamac`.
- Install `pygobject==3.42.2` and `pycairo==1.21.0`.
- Use this code instead:
```python
import webview

window = webview.create_window(title='Hello world', url='https://pywebview.flowrl.com/hello')
webview.start(gui='gtk', debug=True)
```
It works, but I haven't been able to find a solution for the original issue.

**Comment by r0x0r** [comment]
My guess is that it has something to do with qt binaries and other dependencies. Maybe installing qt / webengine via apt or such might help.
