### ISSUE TITLE
WebRTC Functionality in PyWebview

### ISSUE THREAD

**Issue by highboi** [r0x0r/pywebview#989]
### Specification
- pywebview version: 3.7.2 
- operating system: Linuxmint 20.1 ulyssa x86_64 Linux 5.4.0-126-generic
- web renderer: GTK Webkit

### Description  
  
  I am building an application that requires the use of WebRTC but the console tells me that the RTCPeerConnection object is not defined. How would I go about implementing WebRTC functionality inside the webview?
  
### Practicalities

- YES I am willing to work on this issue myself.

**Comment by r0x0r** [comment]
I have enabled a bunch of webkit settings in the 4.0 branch, one of them is enable_media_stream which I believe is WebRTC support. Please test the 4.0 branch and report if it solves your problem.

**Comment by highboi** [comment]
Where do I set this setting? I try to use this keyword but it throws an error for both the create_window() and start() functions.

**Comment by r0x0r** [comment]
It is set automatically in the GTK constructor. Try to run your program as is

**Comment by highboi** [comment]
It still throws the same error unfortunately. I modified the 4.0 branch to grab https://github.com/r0x0r/pywebview/archive/4.0.tar.gz instead of https://github.com/r0x0r/pywebview/archive/3.7.tar.gz which it (setup.py) was getting instead.

**Comment by r0x0r** [comment]
Sorry I have no idea about this. I would go through GTK's webkit settings to see if something relevant can be found and enabled.

**Comment by highboi** [comment]
I found the webkit settings in gtk.py and the enable_media_stream setting is enabled as you said, but the webview still can't access WebRTC functionality from the webview. I will investigate further.
