### ISSUE TITLE
Color input field inverted y-position

### ISSUE THREAD

**Issue by max-uho** [r0x0r/pywebview#991]
### Specification
- pywebview version: 3.7
- operating system: MacOS 13 (Cocoa)
- web renderer: WebKit

### Description  
  
`<input type="color">` at the top of the page will have its tooltip appear at the bottom. The same placed at the bottom will appear at the top. This issue doesn't occur when the same html is rendered directly in Safari.

### Practicalities

- YES/<s>NO</s> I am willing to work on this issue myself. (But I can't figure it out yet)

- <s>YES</s>/NO I am prepared to support this issue financially.

**Comment by r0x0r** [comment]
This sounds like a built-in behaviour to me, in other words tooltip does not overflow out of the window area.
Care to provide a screenshot?

**Comment by max-uho** [comment]
`<h1>Hello</h1>
<input type="color">`

<img width="967" alt="Screenshot 2023-01-02 at 11 49 09" src="https://user-images.githubusercontent.com/1388993/210221584-307cced3-7c1c-4de1-9695-1844d9602692.png">

**Comment by r0x0r** [comment]
Sorry, I have no idea what causes this or how to fix this. My guess is that it has something to do with how webview frame is constructed and its dimensions are calculated.
