### ISSUE TITLE
Unable to run exe using pywebview on virtual machine

### ISSUE THREAD

**Issue by s-t123** [r0x0r/pywebview#992]
### Specification
- pywebview version: 3.7.2
- operating system: windows 10
- web renderer: 

### Description  
  
 Unable to run exe (created using py2exe software) bundled with following dlls on windows virtual machines.
dlls used: 
(a) Microsoft.Web.WebView2.Core.dll (found in webview library in site-packages)
(b) Microsoft.Toolkit.Forms.UI.Controls.WebView.dll (found in webview library in site packages)
(c) Python.Runtime.dll

**Comment by r0x0r** [comment]
What is the error?
